- app/services/importers/seed_schedule.rb
- spec/services/importers/seed_schedule_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-969
- this class will no longer create new schedule if the name of a schedule is renamed
- instead simply update the name of the existing schedule
- a schedule is therefore now targeted by cohort and schedule-identifier
- ssh into review app
- get schedule count `Finance::Schedule.count`
- modify a schedule eg `/app/db/seeds/schedules/npq_specialist.csv`
- change a schedule name of a row
- import the schedule eg.
```
Importers::SeedSchedule.new(
path_to_csv: Rails.root.join("db/seeds/schedules/npq_specialist.csv"),
klass: Finance::Schedule::NPQSpecialist,
).call
```
- Schedule count `Finance::Schedule.count` should not change
- none
> [CPDLP-969] fix Importers::SeedSchedule bug

- app/forms/schools/add_participant_form.rb
- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- db/migrate/20220207133656_change_default_start_term_on_participant_profile.rb
- db/schema.rb
- spec/forms/schools/add_participant_form_spec.rb
It was noticed that we are storing the `start_term` value on `ParticipantProfile` inconsistently in the database.
This PR moves the defaults to the underscore type of text eg `autumn_2021` instead of `Autumn 2021`.
> Change default for start_term

- app/controllers/finance/ecf/payment_breakdowns_controller.rb
- app/controllers/finance/npq/course_payment_breakdowns_controller.rb
- app/controllers/finance/npq/statements_controller.rb
- app/controllers/finance/payment_breakdowns_controller.rb
- app/models/finance/statement/base.rb
- app/models/finance/statement/ecf.rb
- app/models/finance/statement/npq.rb
- app/models/participant_declaration.rb
- app/services/finance/npq/calculation_orchestrator.rb
- app/services/finance/npq/calculation_overview_orchestrator.rb
- app/services/importers/seed_statements.rb
- app/views/finance/npq/statements/show.html.erb
- db/migrate/20220124125023_create_statements.rb
- db/migrate/20220125122219_add_statement_to_declarations.rb
- db/schema.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/models/finance/statement/base_spec.rb
- spec/models/participant_declaration_spec.rb
- spec/services/finance/npq/calculation_orchestrator_spec.rb
- spec/services/importers/seed_statements_spec.rb
- there is some temporary hardcoding of statements
- as when this commit is deployed expected ActiveRecord statements will
not exist yet
- post deployment this data will be seeded and the temporary hard coded
coded removed
- added a seeded mechanism for statements
- this mechanism uses static code but can easily be changed to take csv
- interval is no longer passed thru from the payment breakdowns
- the interval concept can now be removed but is not part of this commit
Ticket:
> Finance::Statement is now an ActiveRecord thing

- spec/cypress/app_commands/scenarios/schools/multiple_schools.rb
- spec/cypress/support/step_definitions/common-navigation.js
- spec/features/schools/change_sit/change_sit_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
If Percy takes snapshots of information that are generated dynamically in factories then it will always alert to 'new' content when in fact it hasn't materially changed.
This PR fixes one such instance.
> Factories that are used with Percy must be deterministic

- app/views/finance/participants/_ecf_profile.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- spec/views/finance/participants/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-959
- Adds schedule when viewing a profile via participant drilldown in the finance area 
- Find a user in the participant drilldown area
- eg `2e2857b8-be3e-48ab-a718-32a7fded1cba`
- Should see their schedule assuming they have a profile 
- None
> [CPDLP-959] Add schedule to finance participant drilldown

- app/models/participant_profile/npq.rb
When we need to manually reject applications that have been accepted in error, we want to delete the profile but not the application.
Ticket:
> Remove dependent destroy from ParticipantProfile::NPQ/NPQApplication

- app/models/finance/statement.rb
- app/models/finance/statement/ecf.rb
- db/migrate/20220208121107_add_cached_value_to_statements.rb
- db/schema.rb
- spec/models/finance/statement/ecf_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-997
- We want to be able to persist the value of a statement against the record
- This is need as we will soon be introducing the ability to void payable declarations
- This would affect the value of a "frozen" statement. Therefore wish to store this value
- One can also the store the value of NPQ statement but by hand
- I have not added the automatic caching of NPQ statements as feel the code is still somewhat fluid and it would be counter-product to do this whereas adding it by hand would probably be more time productive
- ssh into a rails console
- find a `Finance::Statement::ECF`
- call `#cache_original_value!`
- see `original_value` persisted against the statement
- None
> [CPDLP-997] Can persist value of an ECF statement

- app/controllers/admin/participants_controller.rb
- app/controllers/schools/participants_controller.rb
- app/models/participant_profile/ecf.rb
- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- spec/models/participant_profile_spec.rb
We are having difficulty keeping the analytics table in sync because we are being specific about _which_ things should trigger an update. Instead of trying to find all the places that a profile might be updated we can just update the analytics table whenever _any_ field on an ECF profile gets updated.
One example is that we're not updating the table when a schedule is changed.
The risk here is that we increase the number of writes to that table significantly, but I think the benefit of having a correctly synced table outweighs that.
When this is merged and deployed we'll want to re-sync _all_ ECF profiles:
```ruby
ParticipantProfile::ECF.find_each do |participant_profile|
Analytics::UpsertECFParticipantProfileJob.perform_later(participant_profile: participant_profile)
end
> Update analytics when any attribute on ECF profile changes

- app/jobs/api_request_job.rb
- app/middlewares/api_request_middleware.rb
- config/environments/test.rb
- spec/middlewares/api_request_middleware_spec.rb
This warning was being spat out every time an ApiRequestJob was created:
```
WARN: Job arguments to ApiRequestJob do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```
The documentation advises against using symbolised keys in hashes as they will be turned into string keys when reserialized from json.
It turns out this was a good warning as we are accessing these hashes using symbols in the job itself, leading to a bunch of nils. Example of the last api request created:
```
ApiRequest id: "ffffcfd6-d8eb-4db6-ace7-c43a80ffb3d7", request_path: nil, status_code: 200, request_headers: {}, request_body: nil, response_body: …
```
> Fix API request job arg serialization

- db/seeds.rb
This isn't providing any benefit and we need to speed up the seeds as deployments are timing out to review apps
> Disable papertrail during seeds

- db/seeds/initial_seed.rb
- lib/tasks/valid_test_data_generator.rb
Ticket: n/a
- Our deployments involving seeding are timing out
- These are limited to 60 seconds and we are often over this limit causing a deployment to fail which it time costly
- This should reduce that time but only seeding statements once and not repeatedly
- Review app should be available otherwise the deploy failed
- None
> Only seed statements once

- app/services/void_participant_declaration.rb
- app/views/finance/ecf/declarations/voided.html.erb
- app/views/finance/npq/statements/voided.html.erb
- config/locales/en.yml
- spec/services/void_participant_declaration_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-962
- Previously limiting voids to last declaration only may have made sense
- However now this does not seem a reasonable constraint to have
- So has been removed
- For a given statement in play
- Assign some payable declarations to it if there aren't any
- Note the value of the statement
- Should be able to void a payable declaration via the api
- Value of statement should drop
- When viewing the statement at the bottom should be able to click through to the declaration(s) that have been voided
- Nothing that needs documenting
> [CPDLP-962] Can void not last declaration

- app/services/record_declarations/base.rb
- app/services/record_declarations/ecf.rb
- app/services/record_declarations/npq.rb
- config/locales/en.yml
- lib/tasks/valid_test_data_generator.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/features/finance/payment_breakdown_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/base_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1001
- It was assumed `declaration_type` is tied to the the groupings ECF/NPQ
- However this is not quite the case and can be gathered from the schedule they are on
- Remove the hardcoded declaration type from `RecordDeclarations` as we now want to delegate this to the schedule
- Therefore we can now validate the incoming `declaration_type` against the current schedule
- Attempt to submit a `retained-7` declaration for any participant as this milestones does not exist
- Should see a relevant validation error message returned
- Another test is to find/create a participant on one of the `npq-specialist` schedules
- Attempt to send a `retained-2` declaration which does not exist
- Should see a relevant validation error message returned
- …
> [CPDLP-1001] Validate declaration type for schedule

- app/models/induction_record.rb
- app/models/participant_profile/ecf.rb
- app/services/early_career_teachers/create.rb
- app/services/induction/check_participant_records_are_synced.rb
- app/services/induction/enrol.rb
- app/services/induction/transfer.rb
- app/services/induction/withdraw.rb
- app/services/mentors/create.rb
- db/migrate/20220214170448_add_training_status_to_induction_record.rb
- db/schema.rb
- spec/factories/induction_record.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/services/admin/change_induction_choice_service_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/induction/transfer_spec.rb
- spec/services/induction/withdraw_spec.rb
- spec/services/mentors/create_spec.rb
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-283)
Adds services to aid changes to induction programmes
Adds `training_status` to `InductionRecord` to mirror the value from `ParticipantProfile`
Populate the new models and keep them up to date:
* enrols the participants into the default induction programme for their school cohort when a new ECT or Mentor is added.
* sync changes to `status` and `training_status` on `ParticipantProfile` to the associated `InductionRecord`
* added tooling to help check that participant records are in sync
Once code is deployed the `training_status` value needs to be populated from the `ParticipantProfile`
```ruby
InductionRecord.includes(:participant_profile).find_each do |induction_record|
induction_record.update!(training_status: …
```
> CST-283 Data Model changes - sync data model

- app/jobs/npq/stream_big_query_profile_job.rb
- app/models/participant_profile/npq.rb
- spec/features/finance/payment_breakdown_spec.rb
- spec/jobs/npq/stream_big_query_profile_job_spec.rb
- spec/models/participant_profile/npq_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1014
- Whenever an NPQ profile is created or updated we stream some of the information to BigQuery
- Post deployment I will add all existing NPQ profiles to the async queue to stream current records to BigQuery
- ssh into review app
- find a `ParticipantProfile::NPQ` and `touch` it
- Should now see record in BigQuery
- None
> [CPDLP-1014] Stream NPQ profiles to BigQuery

- app/models/participant_declaration.rb
- app/services/record_declarations/base.rb
- spec/features/participant-declarations/block_participant_declaration_paid_twice_spec.rb
- spec/features/participant-declarations/participant_declaration_steps.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/base_spec.rb
- spec/support/shared_examples/participant_declaration_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1040
- This fixes a bug where by a provider could submit a declaration for an existing payable declaration causing it to revert back to eligible
- All incoming declarations now create a new record regardless if another similar one exists or not
- We now create a DeclarationState record when a ParticipantDeclation is created as an ActiveRecord callback
- Find a declaration in payable or paid state
- Submit the same declaration again as the provider
- NOTE: timestamps MUST be identical otherwise it will be considered as a different declaration and you get some kind of error which doesn't test this edge case
- It will create another declaration that is ineligible
- The original declaration will remain in original state of payable or paid …
> [CPDLP-1040] Stop payable declarations reverting to eligible

- app/controllers/concerns/current_user.rb
- spec/features/dedup/session_spec.rb
https://teachercpdhelp.zendesk.com/agent/tickets/12103
When automated deduplication was implemented we were forced to use a "temporary" hack to swap the `current_user` with the user an actual `current_user` has been merged into. This hack unfortunately means that after the transfer, the `current_user` and `true_user` are different, which system interpretes as impersonification.
This "fixes" this by carrying the same hack for a `true_user`.
> Fixed  bug after succesful deduplication

- app/views/finance/participants/_npq_profile.html.erb
- spec/views/finance/participants/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1066
- When viewing participant drill down pages in finance area
- When viewing an NPQ profile
- Added school URN and lead provider
- View a user with an NPQ profile
- Should see school URN and lead provider
- None
> [CPDLP-1066] Add NPQ school and provider to drill down page

- app/components/finance/statements/statement_selector.html.erb
- app/components/finance/statements/statement_selector.rb
- app/controllers/finance/ecf/declarations_controller.rb
- app/controllers/finance/ecf/statements_controller.rb
- app/controllers/finance/npq/course_payment_breakdowns_controller.rb
- app/controllers/finance/npq/statements_controller.rb
- app/controllers/finance/payment_breakdowns_controller.rb
- app/models/finance/statement.rb
- app/services/importers/seed_statements.rb
- app/views/finance/ecf/declarations/voided.html.erb
- app/views/finance/ecf/statements/show.html.erb
- app/views/finance/npq/course_payment_breakdowns/show.html.erb
- app/views/finance/npq/statements/show.html.erb
- app/views/finance/npq/statements/voided.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/statement_selector.scss
- config/routes.rb
- spec/components/finance/statements/statement_selector_spec.rb
- spec/factories/finance/statement/npq.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/services/importers/seed_statements_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1025
- Add NPQ statement selector component
- Pre-selects values to whatever the current statement is
- LHS Nav is gone and now full width
- Visit https://ecf-review-pr-1751.london.cloudapps.digital/
- View an NPQ statement
- Should be able to switch to a different provider and/or statement without leaving the page
- None
> [CPDLP-1025] Add NPQ statement selector

- spec/features/finance/payment_breakdown_spec.rb
The payment breakdown now requires that there is a current statement for each lead provider. This PR creates a statement so that the test doesn't fail.
> Add now required statement to breakdown spec

- spec/features/finance/banding_tracker_spec.rb
It's seems to be taking over an hour to run under some conditions.
It something on CI is making it not run correctly.
My hunch is that it maybe related to running the tests in parallel but not
having enough connection in the pool or connection timing out.
This will need a bit more investigation but as of now we don't have the
exact (with the seed nuber use to run the tests)
command that run by CI to reproduce this
Ticket:
> Temporarily remove banding tracker test.

- .scss-lint.yml
- app/components/finance/statements/statement_selector.html.erb
- app/webpacker/styles/components/statement_selector.scss
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1081
- Tweak statement selector so each dropdown is one third
- Unfortunately small CSS hack required as can't seem to inject desired CSS classes via govuk form builder
- Increased spacing for mobile view
- https://ecf-review-pr-1782.london.cloudapps.digital/
- Login as finance user
- Find an NPQ statement
- Increased dropdowns to to thirds
- Mobile view has increased spacing
- None
> [CPDLP-1081] tweak width of selects on statement selector

- app/controllers/finance/npq/statements_controller.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1091
- The selecting of correct aggregator for NPQ statement was inverted
- Maybe
- Sign in as a finance user
- Find a statement that already has declarations assigned to it
- Submit an `eligible` declaration with correct provider and course
- Should have zero affect on the statement 
- None
> [CPDLP-1091] fix toggle for NPQ aggregator which was inverted

- app/controllers/finance/npq/course_payment_breakdowns_controller.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1091
- this was due to inverted choice when selecting correct aggregator
- Sign in as a finance user
- Find a statement that already has declarations assigned to it
- View the course breakdown
- Submit an `eligible` declaration with correct provider and course
- Should have zero affect on the statement 
- None
> [CPDLP-1091] fix NPQ course statements

- app/services/finance/npq/participant_eligible_and_payable_aggregator.rb
- spec/services/finance/npq/participant_eligible_and_payable_aggregator_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1091
- aggregates on declarations not assigned to any statements
- as this aggregator operates on non frozen statements
- Sign in as a finance user
- Find a current statement ie has no declarations assigned to it
- View the course breakdown
- Submit/Create a `payable` declaration with correct provider and course on a previous frozen statement
- Should have zero affect on the statement
- None
> [CPDLP-1091] Tweak ParticipantEligibleAndPayableAggregator

- Gemfile
- Gemfile.lock
- bin/delayed_job
Ticket: n/a
- this gem is no longer needed
- it was previously used to run delayed job as a process
- delayed job has been removed for some time
- sidekiq is used now and does not require this gem
- The worker doesn't run on reviews so probably can't be tested
- Might be able to scale up workers and ensure they still work
- none
> remove the daemons gem

- app/jobs/stream_big_query_participant_declarations_job.rb
- spec/jobs/stream_big_query_participant_declarations_job_spec.rb
Sometimes we might change the schema on declarations but forget to update the BigQuery schema. Previously this would fail the BigQuery participant stream silently because we push _all_ attributes on that model. 
This change accepts rows that contain values that do not match the schema. The unknown values are ignored.
> BigQuery should accept rows that don't match schema

- terraform/monitoring/resources.tf
https://github.com/DFE-Digital/cf-monitoring/commit/0c104bab70659e769b464cd76fd6f97b27568668 and other commits are generated with a newer version of Grafana and this broke our instance. Instead, we can unpin from the version we were targeting and be on the latest and greatest.
> Remove Grafana version pin

- app/components/content_list_component.html.erb
- app/components/finance/npq/payment_overviews/output_payment_row.html.erb
- app/components/finance/npq/payment_overviews/output_payment_row.rb
- app/components/finance/npq/payment_overviews/payment_overview_milestone_summary.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_milestone_summary.rb
- app/components/finance/npq/payment_overviews/payment_overview_summary.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_summary.rb
- app/components/finance/npq/payment_overviews/payment_overview_table.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_table.rb
- app/components/finance/npq/payment_overviews/payment_overview_table_header.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_table_header.rb
- app/components/finance/npq/payment_overviews/payment_overview_total.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_total.rb
- app/components/finance/npq/payment_overviews/service_fee_row.html.erb
- app/components/finance/npq/payment_overviews/service_fee_row.rb
- app/controllers/finance/npq/statements_controller.rb
- app/models/finance/statement.rb
- app/models/participant_declaration.rb
- app/views/finance/npq/statements/show.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/lead_providers/statements.scss
- config/locales/en.yml
- lib/tasks/valid_test_data_generator.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/features/finance/npq/view_contract_spec.rb
Includes both [1026 ](https://dfedigital.atlassian.net/browse/CPDLP-1026) and [1027](https://dfedigital.atlassian.net/browse/CPDLP-1027)
1026 - adds Statement Summary
1027 - adds course breakdowns
- This view is for internal users only
- Refer to prototype / tickets for details & acceptance criteria
> CPDLP  1026 & 1027 - NPQ course breakdown

- .github/workflows/review.yml
Don't create dependabot review apps — it fails by default because we don't want to expose our secrets to it.
> Don't create dependabot review apps

- app/services/importers/ecf_manual_validation.rb
The ECF manual validation importer has been broken for a long time, this fixes the issues.
> Fix issues with manual validation importer

- app/services/induction/create_relationship.rb
- db/migrate/20220314120140_add_relationship_to_partnerships.rb
- db/schema.rb
- spec/services/induction/create_relationship_spec.rb
As part of enabling transferring participants to continue their current FIP, we need to represent their `Partnership` with the new school.  The business is calling this a "relationship" to differentiate the two things. A relationship can be added by a SIT and doesn't need to originate from a provider. It is intended only for the transferring participant's use but otherwise it is the same as the current `Partnership`. It would not normally be challenged and would not be reused for wider use, but just to act as the glue between the school/providers and transferring participant's induction.
Adds a boolean `relationship` to `Partnership`
Adds a service to create a partnership with this flag set
2. Follow the steps from …
> Change of Circumstances: Add relationship partnership

- docs/source/release-notes.html.erb
Ticket: n/a
- Add missing release note for change of URL in docs
- visit docs in review app
- see release notes
- should see missing release note dated 8th March
- none
> add release note for change of url in docs

- app/components/finance/npq/payment_overviews/contract_info.html.erb
- app/components/finance/npq/payment_overviews/contract_info.rb
- app/components/finance/npq/payment_overviews/payment_overview_summary.html.erb
- app/components/finance/npq/payment_overviews/payment_overview_summary.rb
- app/components/finance/npq/payment_overviews/payment_overview_table_header.html.erb
- app/controllers/finance/base_controller.rb
- app/helpers/application_helper.rb
- app/views/finance/npq/statements/show.html.erb
- app/views/layouts/_application.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_footer_wide.html.erb
- app/views/layouts/_phase_banner.erb
- app/views/layouts/_phase_banner_wide.html.erb
- app/views/layouts/_width_container_wide.html.erb
- app/views/layouts/finance.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/lead_providers/statements.scss
- config/locales/en.yml
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/features/finance/npq/view_contract_spec.rb
Ticket: [CPDLP-1113](https://dfedigital.atlassian.net/browse/CPDLP-1113)
**Changes include:**
1. Widening the container width for the finance area of the application (including banner at top of page and footer)
2. Copy updates as per CPDLP-1113
3. Make voided declarations accessible by link in summary (remove link from bottom of page)
4. Remove link to contract info and move info to bottom of payments summary
5. Remove unique scope on declarations in summary table - this was preventing numbers adding up correctly when a participant is doing more than one NPQ (on the statement)
6. Recruitment total removed from course breakdown table
7. Ordering of milestones 
This is a follow up to CPDLP-1026 & 1027 which was deployed last week
1. Click the link to review app (posted by a `github-actions` …
> CPDLP-1113 NPQ breakdown post release changes

- app/controllers/api/v2/npq_enrollments_controller.rb
- app/serializers/api/v2/npq_enrollments_csv_serializer.rb
- config/routes.rb
- spec/docs/v2/npq_enrollments_spec.rb
- spec/requests/api/v2/npq_enrollments_spec.rb
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/MultipleNPQEnrollmentsCsvResponse.yml
- swagger/v2/component_schemas/NPQEnrollmentCsvRow.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1043
- NOTE: Before merging ensure v2 api docs are removed
- Add new endpoint for v2 API to fetch NPQ enrollments via CSV format
- Update docs fro this new endpoint
- docs available at https://ecf-review-pr-1809.london.cloudapps.digital/api-reference/reference-v2.html#api-v2-npq-enrollments-csv-get
- call the new endpoint
- should see relevant enrollments in csv format
- Yes for v2
- But v2 is not been exposed yet
> [CPDLP-1043] API v2 NPQ enrollments CSV endpoint

- app/services/store_participant_eligibility.rb
- spec/services/store_participant_eligibility_spec.rb
We don't want to send these emails to limit the impact on support
> CST-285 Don't send any emails to users transitioning from eligible to exempt if they don't have declarations

- app/services/store_participant_eligibility.rb
- spec/services/store_participant_eligibility_spec.rb
We don't want to prevent this email from being sent when revalidating participants, we just want to prevent other ineligible emails being sent, for which there are specific emails for when the participant was previously eligible.
There was a different bug (now fixed) that was misevaluating these users as being exempt from induction, for which we have sent specific comms to tell them this was a mistake, so we don't need to re-run eligibility checks for these users.
Ticket:
> CST-287 Send no-induction emails when participant was previously eligible

- terraform/monitoring/config/development/alert.rules.yml
Ticket: n/a
- dev gets very low traffic so if there is one error this alert will trigger causing noise
- n/a
- None
> Remove dev errors alerting rule

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/ecf_participants_controller.rb
- config/initializers/pagy.rb
We've observed some issues with pagination on the `/participants` endpoints where the some records were missing. This PR is a bit of a shot in the dark, but it seems to fix the issues:
- The issue is applicable only to the JSON endpoint. The CSV endpoint returns the correct data.
- It appears that there is an issue with our pagination: we aren’t seeing a final page of results where we’d expect to.
- Some empty records are being 'counted' by pagy which means the offsets are incorrect later.
We discovered that removing an unnecessary outer join resolves the issue, but we still don't know why. This PR also updates Pagy.
The main thing for reviewers to check is I'm not introducing N+1 queries in the serializer. My benchmarks suggest not:
```
with join:
=> #<Benchmark::Tms:0x00007fec60e38498 …
```
> Fix ECF participants pagination

- .github/workflows/deploy_to_staging.yml
Ticket: N/A
On each staging release we get Slack notifications with empty release notes. It seems the git tags are not available to the CI step that sets the release notes, ending up comparing the same tag. 
This PR will:
- make the git tags available to the `Set release notes` step, which should fix the issue. 
- change the release notes to display the commit subjects instead of the commit body. Not all commits have a body, so this change avoids release notes with just the author name.
> Fix the release notes

- .github/workflows/review.yml
Ticket: N/A
We don't want to create review apps when dependabot creates PRs.
Changes:
- Seems the `branches` and `branches-ignore` filters check only the target branches, so I removed the `branch-ignore` filter
- Added an `if` statement in the jobs to not run when Dependabot is the PR author
> Skip creating review apps for the dependabot PRs

- app/jobs/check_participants_induction_job.rb
- app/services/store_participant_eligibility.rb
- spec/jobs/check_participants_induction_job_spec.rb
- spec/services/store_participant_eligibility_spec.rb
There is a job to recheck all no induction/previous induction participants on monday mornings. We don't want to keep resending emails about the participant
status when it doesn't change
Ticket: https://dfedigital.atlassian.net/browse/CST-288
> [CST-288] Don't resend manual check emails when the status doesn't change

- spec/services/store_participant_eligibility_spec.rb
There was a version upgrade before this test was added, the interface for have_enqueued_mail now doesn't require the args key and you have to pass the
args directly.
Ticket:
> Fix failing spec after merge

- app/serializers/api/v1/npq_participant_serializer.rb
- app/serializers/api/v1/participant_serializer.rb
- app/serializers/api/v2/npq_participant_serializer.rb
- app/serializers/api/v2/participant_serializer.rb
- app/services/npq/is_user_withdrawn.rb
- spec/docs/v1/participants_spec.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/requests/api/v2/participants_spec.rb
- spec/serializers/api/v1/npq_participant_serializer_spec.rb
- spec/serializers/api/v1/participant_serializer_spec.rb
- spec/serializers/api/v2/ecf_user_serializer_spec.rb
- spec/serializers/api/v2/npq_participant_serializer_spec.rb
- spec/serializers/api/v2/participant_serializer_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
- swagger/v1/component_schemas/ECFParticipantCsvRow.yml
- swagger/v1/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
- swagger/v1/component_schemas/NPQParticipantAttributes.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/ECFParticipantAttributes.yml
- swagger/v2/component_schemas/ECFParticipantCsvRow.yml
- swagger/v2/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v2/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v2/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
- swagger/v2/component_schemas/NPQParticipantAttributes.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1121
- only email is now nullified
- all other fields are left intact
- this affects participant serializers
- this is so when provider withdraws they no see their details
- Find an ECF user that is present via `/ecf/participants` endpoint
- Withdraw them either `status` or `training_status` set to `withdrawn`
- `email` should now be nullified via same api call
- Perform the same tests for CSV version
- Perform the same tests for NPQ + extra tests
- Additional feature for NPQ only. If you have 2 enrollments with the same provider, you must withdraw both enrollments in order for the email to be nullified
- Yes, to some degree. Some fields that could be previously nullified can no longer be nullified. Docs have been updated accordingly
> [CPDLP-1121] Nullify when training_status is withdrawn

- app/controllers/api/v1/test_ecf_participants_controller.rb
- app/models/participant_profile/ecf.rb
- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- config/routes.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- fetching of these participants hangs off induction records
- to run in parallel with current endpoint for testing
- requires privileged api key for access so not accessible to providers
- hopefully removed the need to fetch mentors in a different query then inject in as implemented in existing endpoint
- Will require quite some effort to setup data
- Setup all the required induction records
- Setup a privileged key
- hit the old ecf participants endpoint
- hit the new test endpoint
- data should the same or similar to the existing endpoint
- Nothing that is accessible to providers
> [CPDLP-1159] new test participants endpoint

- app/models/induction_record.rb
- app/models/participant_profile/ecf.rb
- db/migrate/20220322172748_add_mentor_to_induction_record.rb
- db/schema.rb
- spec/models/induction_record_spec.rb
Add `mentor_profile` to `InductionRecord` and keep in sync with changes to `ParticipantProfile`.
This will eventually enable us to separate the mentor profile from the participant profile and track an ECTs mentorship it via induction records instead. This will also allow us to show that a transferring ECT could have a mentor in their current school and also be assigned a different mentor in their new school.
> Change of circumstances: Add mentor_profile to induction_record

- .github/workflows/deploy_to_staging.yml
This reverts commit c114717cd7f2883e4f46f4d8edd887d9ad27627e.
Ticket: N/A
The commit subjects are always merge messages from github, which are not that useful.
> Revert "Display the commit subjects in the release notes"

- app/controllers/api/v1/test_ecf_participants_controller.rb
- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- Handle scenario where a profile could have multiple induction records
- Crudely handles scenario where a user has more than one profile
- For the above point I feel the implementation is not perfect and buggy
- In order to rid of the bugs we need to fundamentally address de-dupe problems, these workarounds can only get us so far
- Will be tested on prod behind auth wall
- None
> [CPDLP-1159] Multiple profiles or induction records

- analytics_queries/participants.sql
We would like to be able to report on the reason why `training_status` was set. This PR adds that field into the analytics output.
> Add participant profile state reason to analytics queries

- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- Base nullification off the induction record not the profile
- Setup api key with private access on 2 providers
- Move a profile from one lead provider to another
- or create relevant induction records
- hit test endpoint as old provider should see nullified email
- hit test endpoint as new provider should not see nullified email
- None
> [CPDLP-1159] nullification based off induction record

- .github/workflows/destroy.yml
Ticket: N/A
#1835 added a check in the create review app workflow to skip review apps for dependabot PRs, but missed to also add it in the destroy workflow which now fails every time a dependabot PRs is closed.
> Ingore the destroy CI workflow for dependabot PRs

- app/services/participants/change_schedule/ecf.rb
- spec/services/participants/change_schedule/early_career_teacher_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1128
- There is now a schedule fields on the induction record
- When a provider changes schedule we now also update the relevant induction record
- Once we swap over the schedule on the profile will become defunct
- However I am leaving the profile schedule present as there will be existing code that utilises it therefore maintain backwards compatibility
- assuming you have a participant with an induction record otherwise no induction record will get updated
- change their schedule
- should also change the schedule on the induction record on top of the profile schedule
- NPQ should not be affected
- None
> [CPDLP-1128] Change schedule updates induction record

- spec/services/participants/defer/early_career_teacher_spec.rb
- spec/services/participants/defer/mentor_spec.rb
- spec/services/participants/defer/npq_spec.rb
- spec/support/shared_examples/participant_actions_defer_support.rb
- spec/support/shared_examples/participant_declaration_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1170
- Refactor only
- Removes shared tests for defer services
- This increases test duplication code but far easier to make changes rather than tests shared across multiple with aren't very localised
- This will be needed as NPQ and ECF code will diverge soon with the introduction of induction records
- Noticed a bug for deferring withdrawn folk. this already exists and not in scope for this PR for fixing
- These tests now run in about a quarter of the time the original tests took due to the fact we no longer load in so many unrelated test setups due to the shared nature
n/a
- None
> [CPDLP-1170] Refactor deferring tests

- spec/features/finance/payment_breakdown_spec.rb
Removing the percy snapshot, it does not offer any value here, the page already has extensive checks on all the numbers this page is generated from.
> [chore] - remove percy snapshot on already well tested page

- spec/services/participants/resume/early_career_teacher_spec.rb
- spec/services/participants/resume/mentor_spec.rb
- spec/services/participants/resume/npq_spec.rb
- spec/support/shared_examples/participant_actions_resume_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1170
- Refactor only
- Removed shared tests
- Replaced with mostly duplicated tests
- Despite the duplication makes for making changes far easier. Which will be necessary as ECF and NPQ will soon diverge
- New tests run in half the time as it does not setup unused test objects
- n/a
- None
> [CPDLP-1170] refactor resume participant tests

- spec/services/record_participant_declaration_spec.rb
Ticket: n/a
- There seems to be a CI test failure around future declarations
- I've ripped out all the shared test setups from relevant file and re-implemented inline
- We want to rip out the shared tests at some point anyway so this is one step closer
- I highly recommend NOT having a global test setup that is called before a large number of different tests
- n/a
- None
> Remove shared tests from declarations spec

- db/seeds/test_data.rb
Our seeds have been steadily growing without much time spent pruning unused or an excess of data created. This PR reduces the volume of data we create.
Before:
```
❯ time rake db:safe_reset
Re-seeded the database!
rake db:safe_reset  22.05s user 2.20s system 56% cpu 42.933 total
```
After:
```
❯ time rake db:safe_reset
Re-seeded the database!
rake db:safe_reset  12.72s user 1.55s system 57% cpu 25.005 total
```
> Reduce amount of seed data created

- app/views/schools/add_participants/start_term.html.erb
- app/views/schools/participants/index.html.erb
Ticket: [CST-447](https://dfedigital.atlassian.net/browse/CST-447)
We need to let people know adding ECTs/mentors for next year is not yet available and that emails will be sent out once it is.
> Add text content in the registration journey

- Gemfile
- Gemfile.lock
- app/helpers/markdown_helper.rb
These gems and helpers are no longer used.
> Remove rouge and govuk_markdown gems

- app/controllers/schools/participants_controller.rb
- app/forms/participant_start_term_form.rb
- app/models/participant_profile/ecf.rb
- app/views/schools/participants/edit_start_term.html.erb
- spec/requests/schools/participants_request_spec.rb
Ticket: CST-519
The ticket includes a fix related to a bug found in the participant start term edit page where if no term was selected before hitting the submit button then an error was shown (missing parameter exception).
The code fixes the issue and show validation messages instead.
> "Autumn 2021" removed from add participant journey

- app/models/participant_profile/ecf.rb
- app/services/participants/defer/validate_and_change_state.rb
- app/services/participants/ecf.rb
- app/services/participants/npq.rb
- db/seeds/test_data.rb
- lib/tasks/valid_test_data_generator.rb
- spec/features/finance/payment_breakdown_spec.rb
- spec/features/participant_declarations/block_participant_declaration_paid_twice_spec.rb
- spec/features/participant_declarations/participant_declaration_steps.rb
- spec/models/participant_declaration_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/requests/api/v2/participants_spec.rb
- spec/services/participants/defer/early_career_teacher_spec.rb
- spec/services/participants/defer/mentor_spec.rb
- spec/services/participants/resume/early_career_teacher_spec.rb
- spec/services/participants/resume/mentor_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/participants/withdraw/mentor_spec.rb
- spec/services/record_declarations/base_spec.rb
- spec/services/record_declarations/retained/early_career_teacher_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
- spec/services/record_participant_declaration_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/support/shared_examples/participant_service_ect_support.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1170
- Lead providers deferring, resuming, withdrawn now affect induction records for `training_status`
- The AR callback for syncing `training_status` has been removed
- Seeds have been updated to support this. I will continue to admit the state of the seeds is appalling and needs a re-vamp
- Assuming induction records are setup
- As a lead provider defer/resume/withdraw a participant
- Relevant induction record should be updated
- None
> [CPDLP-1170] InductionRecord#training_status updates via API

- app/controllers/api/v1/test_ecf_participants_controller.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- this is done by scoping to the current cohort
- how we deal with future cohorts is a future problem
- this will be tested on prod behind an auth wall
- None
> [CPDLP-1159] Test endpoint excludes NQT+1

- app/services/participants/change_schedule/ecf.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/requests/api/v2/participants_spec.rb
- spec/services/participants/change_schedule/early_career_teacher_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1128
- Access to change schedule is now based off the induction record
- As previous check via `school_cohort` will soon be no longer supported
- Assuming induction records are present
- Change the schedule of a participant
- Induction record should be updated
- Delete association via `school_cohort`
- Change the schedule of a participant
- Induction record should be updated. This would previously have failed
- None
> [CPDLP-1128] Change schedule access scoped by induction record

- app/controllers/schools/choose_programme_controller.rb
- app/forms/schools/year2020_form.rb
- app/services/induction/set_cohort_induction_programme.rb
- spec/services/induction/set_cohort_induction_programme_spec.rb
Ensure we create an `InductionProgramme` to represent the training programme choice made for the school cohort.
> Change of Circumstances: Add induction_programme during school_cohort choice

- app/controllers/admin/suppliers/suppliers_controller.rb
- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/helpers/pagination_helper.rb
- app/views/admin/suppliers/suppliers/index.html.erb
- app/views/shared/_paginator.html.erb
- config/initializers/pagy.rb
- config/locales/en.yml
Ticket: CST-587
This is a proposed approach to migrate away from Kaminari and use Pagy instead.
The pagination is widely used in the app so I propose to do it in a few PRs instead of a big one.
This implementation changes the govuk_paginate helper to handle both Kaminari and Pagy pagination.
This way the migration can be done without breaking the retro compatibility.
> replace Kaminari with Pagy for Suppliers admin

- app/services/participants/resume/validate_and_change_state.rb
- app/services/participants/withdraw/validate_and_change_state.rb
- spec/services/participants/resume/early_career_teacher_spec.rb
- spec/services/participants/resume/mentor_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/participants/withdraw/mentor_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1170
- Actions defer/resume/withdraw now affect induction records if one can be found
- n/a
- None
> [CPDLP-1170] Actions affect induction records

- app/jobs/enrol_school_cohorts_job.rb
- config/sidekiq_cron_schedule.yml
- spec/jobs/enrol_school_cohorts_job_spec.rb
Probably only a temporary need, this job tries to ensure that any school cohort change that we've missed gets an induction programme, and the participants enrolled into that programme.
e.g. a school takes on an ECT and adds/changes their school_cohort
I've set this to run at 3am every day.
> Change of Circumstances: Add job to enrol school cohorts

- lib/tasks/one_offs.rake
Ticket:
https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1164
* A new one off rake task `one_offs:resolve_issues_in_ecf_schedule_start_date` to update the start dates of milestones
> [CPDLP-1164] one off rake task to resolve issues in ECF schedule start date

- app/controllers/api/v1/test_ecf_participants_controller.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- when lead provider views participants exclude any where the partnership has been challenged
- n/a
- None
> [CPDLP-1159] exclude participants if partnership is challenged

- app/views/participants/validations/check_trn_given.html.erb
- app/views/participants/validations/dob.html.erb
- app/views/participants/validations/name.html.erb
- app/views/participants/validations/name_changed.html.erb
- app/views/participants/validations/nino.html.erb
- app/views/participants/validations/trn.html.erb
- app/views/schools/add_participants/choose_mentor.html.erb
- app/views/schools/add_participants/email.html.erb
- app/views/schools/add_participants/name.html.erb
- app/views/schools/add_participants/start_term.html.erb
- app/views/schools/participants/edit_email.html.erb
- app/views/schools/participants/edit_name.html.erb
- config/locales/en.yml
- spec/features/participants/validation_spec.rb
- spec/features/schools/participants/add_participants_spec.rb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/requests/schools/participants_request_spec.rb
Ticket: N/A
Some of the participant pages are not displaying the error summary when the question forms return validation errors. 
This PR:
- adds the missing error summary
- updates some of the validation error messages to be more accessible
- adds some more Percy screenshots
> Add missing error summary to participant pages

- .tool-versions
- db/seeds/schedules/npq_aso.csv
- db/seeds/schedules/npq_leadership.csv
- db/seeds/schedules/npq_specialist.csv
- lib/tasks/one_offs.rake
- spec/factories/finance/schedules.rb
Ticket:
https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1164
* Reverted commit for rake task `one_offs:resolve_issues_in_ecf_schedule_start_date` : https://github.com/DFE-Digital/early-careers-framework/pull/1921
* Updated seed files and spec factory to replace long dash (–) with normal dash (-)
> [CPDLP-1164] one off rake task to resolve issues in ECF schedule start date - revert & dash fixes

- app/services/induction/change_preferred_identity.rb
- app/services/induction/enrol.rb
- spec/requests/api/v1/participant_declarations_spec.rb
Ticket: [1125](https://dfedigital.atlassian.net/browse/CPDLP-1125)
Updates to services/participants/ecf.rb `matches_lead_provider?` now allow LP after transfer to submit declarations - this PR adds test scenarios to demonstrate this. These tests will be extended in under separate tickets e.g. new LP not being able to post duplicate PR
> CPDLP-1125 Add test scenarios to ensure new LP can post declarations after transfer

- .github/workflows/scenarios.yml
- bin/rspec_ci
- bin/scenarios_ci
Sets up scenario test action to run in parallel on 10 nodes, also adds default values to `rspec_ci` so it can be used to run locally without setting env vars.
> 10 nodes for scenarios

- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/serializers/api/v1/participant_from_induction_record_serializer_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1221
- `InductionRecord#status` has been deprecated
- We now figure out a participant status from the `InductionRecord#induction_status`
- Everything tallies up in prod so there should be no data issues:
```
InductionRecord.joins(:participant_profile).where("participant_profiles.status != induction_records.induction_status").count
=> 0
```
- Find a user and fetch via api
- Change their induction status via backend
- Fetch from API again
- Should see different status
- Changes are transparent
> [CPDLP-1221] Infer participant#status from induction record

- app/models/induction_record.rb
- app/services/induction/enrol.rb
- db/migrate/20220413092522_remove_status_from_induction_record.rb
- db/schema.rb
- spec/services/induction/change_preferred_email_spec.rb
- spec/services/induction/change_programme_spec.rb
- spec/services/set_participant_categories_spec.rb
We previously added `induction_status` to `InductionRecord` to provide a better named replacement for `status`.
This PR now removes `status` from `InductionRecord`
> Remove "status" column from InductionRecord

- app/views/finance/participants/_ecf_profile.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- spec/views/finance/participants/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1209
- Adds induction records to finance area participants drill down
- Also render placeholder copy when there are no declarations
- Login as finance user
- Find a user with an induction record
- View them in participant drill down
- Should see their induction records
- None
> [CPDLP-1209] Add induction records to finance area

- spec/requests/api/v1/participant_declarations_spec.rb
Test scenario to ensure providers can't see future declarations once a participant has transferred 
Ticket: [1122 ](https://dfedigital.atlassian.net/browse/CPDLP-1122)
> CPDLP-1122 ensure providers cant see future declarations

- app/controllers/schools/transferring_participants_controller.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_withdrawn_participant_spec.rb
[JIRA Ticket](https://dfedigital.atlassian.net/browse/CST-658)
During the transfer participant journey, once we are able to match the participant, if the participant has been withdrawn by the provider then prevent the transfer and show the "contact support" page.
> CST-658 - Prevent withdrawn participants transferring

- app/components/subnav_component/nav_item_component.html.erb
- app/controllers/lead_providers/partnerships_controller.rb
- app/controllers/lead_providers/report_schools/base_controller.rb
- app/controllers/lead_providers/your_schools_controller.rb
- app/models/cohort.rb
- app/services/feature_flag.rb
- app/views/dashboard/_navigation.html.erb
- app/views/dashboard/show.html.erb
- app/views/lead_providers/your_schools/index.html.erb
- db/seeds/initial_seed.rb
- spec/cypress/integration/Dashboard.feature
- spec/cypress/integration/lead_providers/ReportSchools.feature
- spec/cypress/integration/lead_providers/YourSchools.feature
- spec/factories/cohorts.rb
- spec/models/cohort_spec.rb
- spec/requests/lead_providers/partnerships_spec.rb
- spec/requests/lead_providers/report_schools/base_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-583
We want the lead providers to view their school partnerships from multiple cohorts and allow them to begin reporting any new partnerships to DfE ahead of the start of the 2022/23 cohort.
The early registrations for the new cohort will start early May, so a feature flag is required.
Changes:
- Add the `multiple_cohorts` feature flag to enable the changes when we the new cohort opens for early registrations
- Add multiple cohort support to the lead provider dashboard by using the `cohort` param in the urls
- Scope the displayed schools, school exports and search results to the selected cohort
- Use better filenames when exporting the school partnerships
- Display the `confirm more schools` button only for the cohort that's open for …
> [CST-583] Update the lead provider dashboard to report partnerships for the new cohort

- docs/source/release-notes.html.erb
These changes are missing from the changelog and have been highlighted by consumers of the API as not having been entered. Getting them in retroactively so that everyone is aware.
> Add changes to NPQApplicationAttributes to release notes

- app/mailers/participant_transfer_mailer.rb
Lead provider reported unknown IDs reported in participant transfer mailers.
It appears the `induction_record.preferred_identity.external_identifier` was being sent as the participant ID when it should have been the `induction_record.participant_profile.participant_identity.external_identifier`
This PR fixes this.
> Mailers to providers should use identity on profile

- app/views/schools/transferring_participants/check_answers.html.erb
Quick bugfix from Sentry.  It is possible that the school transferring a participant does not yet have a partnership in place so the lead provider could be be nil.
> Bugfix: Handle no lead provider in check details view

- app/services/induction/create_relationship.rb
- spec/services/induction/create_relationship_spec.rb
Fixes issue with a "relationship" type of `Partnership` where the `challenge_deadline` isn't being set and subsequently any calls to `Partnership#in_challenge_window?` generate an error.
> Bugfix: Set challenge_deadline to current time for relationship

- app/views/admin/participants/show.html.erb
The previous way of checking for the participant was using legacy associations and it looks like that not all users have this, i.e. an early career teacher profile or mentor profile against the user. The previous call was causing it to check for the ECTPending view, which has been removed from admin/participant/details component. Doing the check directly on the participant profile should stop this error.
See [commit that removed the ECTPending and MentorPending](https://github.com/DFE-Digital/early-careers-framework/commit/fd2a8e1cbf94f9f15713079aa44bec0b3cc1f87e), which has been replaced with the details, schools and history partials - [admin views](https://github.com/DFE-Digital/early-careers-framework/tree/develop/app/views/admin/participants)
[Error in …
> Bugfix: Check for npq profile in admin/participants/show

- app/views/finance/participants/_ecf_profile.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- spec/views/finance/participants/show.html.erb_spec.rb
Ticket:
https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1217
* Added `Eligible for funding` row for participants drill down page.
> [CPDLP-1217] Add eligible_for_funding status to drilldown

- app/controllers/schools/transferring_participants_controller.rb
- app/forms/schools/transferring_participant_form.rb
- app/views/schools/transferring_participants/cannot_add.html.erb
- app/views/schools/transferring_participants/cannot_find_their_details.html.erb
- app/views/schools/transferring_participants/check_answers.html.erb
- app/views/schools/transferring_participants/choose_mentor.html.erb
- app/views/schools/transferring_participants/dob.html.erb
- app/views/schools/transferring_participants/email.html.erb
- app/views/schools/transferring_participants/full_name.html.erb
- app/views/schools/transferring_participants/schools_current_programme.html.erb
- app/views/schools/transferring_participants/teacher_start_date.html.erb
- app/views/schools/transferring_participants/teachers_current_programme.html.erb
- app/views/schools/transferring_participants/trn.html.erb
- spec/cypress/app_commands/scenarios/admin/school_participants.rb
- spec/forms/schools/transferring_participant_form_spec.rb
Because of the different routes you can go through the transferring participant journey the standard back links aren't sufficient, as you can end up in loops or redirected to the wrong previous page. This is attempting to address that problem. 
3. login in as a SIT, go through the transferring journey. 
4. Use the test DQT data to get past validation. 
5. Check back links act as they should
> Transferring participant back link fix

- app/services/record_declarations/base.rb
- db/migrate/20220503132944_change_schedule_milestones_index.rb
- db/schema.rb
- db/seeds/schedules/ecf_standard.csv
- spec/factories/finance/schedules.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/models/finance/schedule/ecf_spec.rb
- spec/services/record_declarations/base_spec.rb
- spec/services/record_declarations/retained/npq_spec.rb
- spec/support/with_default_schedules.rb
Use milestone_schedule to for validation which was left over from previous statment
automation story - deduplicating milestones which will allow to edit a
milestone's `milestone_date` easily, as there now is only one milestone for a
given start_date + milestone_date pair.
We can now have multiple start date within a schedule allowing us to as this
extra period.
Ticket:
> [CPDLP-1185] - add extra started milestone for ECF April standard

- app/services/api/participant_declarations/index.rb
Ticket:
* Added created_at order to `ParticipantDeclarations::Index`, which fixes the issue.
> Declarations pagination error with UNION fix

- app/mailers/participant_mailer.rb
- app/models/concerns/gias_types.rb
- app/services/invite_ects.rb
- spec/services/invite_ects_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-624
The criteria should be:
To send to existing schools:
- defined as any school registered in our service with a nominated SIT (this includes SITs that opted out for 2021 to 2022)
- we'll email the SIT directly
- the SIT will sign in and use the new multiple cohort journey (to confirm their programme for FIP, or select again for CIP and DIY)
- once the SIT has confirmed their programme choice for 2022 to 2023, the school will leave this list
- links to ((sign_in)) which should include GA tracking
- variable ((SIT_name)) should include the full name of the SIT
> CST-624 Add mailer to invite existing schools to choose programme for 22/23

- app/models/participant_profile/mentor.rb
- app/models/school.rb
- app/models/school_mentor.rb
- app/services/mentors/add_to_school.rb
- app/services/mentors/remove_from_school.rb
- db/migrate/20220429144309_create_school_mentors.rb
- db/schema.rb
- spec/services/mentors/add_to_school_spec.rb
- spec/services/mentors/remove_from_school_spec.rb
[Jira Ticket:](https://dfedigital.atlassian.net/browse/CST-510)
Back-end changes to support having a cross-cohort pool of mentors at a school
* Migration to add new "join" table `school_mentors`
* Adds new join model `SchoolMentor` to link `School` and `ParticipantProfile::Mentor` types
* Adds services to add and remove mentors from `school_mentors`
* Adds `preferred_identity` on the `SchoolMentor` so we can use this later to provide a preferred email when we get to handling mentors at multiple schools (same as `InductionRecord.preferred_identity` method).
UI changes to adding mentors to follow in subsequent PRs.
Does this change anything in our external APIs? If so, did you …
> [CST-510] Mentors in multiple cohorts - Part 1

- app/forms/schools/add_participant_form.rb
- app/mailers/participant_mailer.rb
- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/mentors/create_spec.rb
Ticket: [573](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-573)
***TO BE MERGED AFTER THE UPDATE ADD PARTICIPANTS JOURNEY HAS BEEN MERGED**
2. Login as a SIT 
- FIP tutor cpd-test+tutor-10@example.com
- CIP tutor cip-tutor-202@example.com
4. Go to add an ECT or Mentor
5. Go through the journey
- For a teacher you can validate use a record from the test dqt
- For someone you can't validate or don't know the trn add an example email
6. Check that it's the right email you've received
> [CST-573] Email to ECT or Mentor when SIT validates them

- app/controllers/schools/add_participants_controller.rb
- app/forms/schools/add_participant_form.rb
- app/forms/schools/new_participant_or_transfer_form.rb
- app/lib/multistep/controller.rb
- app/views/schools/add_participants/who.html.erb
- app/views/schools/participants/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/requests/schools/add_participants_spec.rb
We're getting an error [in Sentry](https://sentry.io/organizations/dfe-teacher-services/issues/3187412149/?project=5748989&query=is%3Aunresolved) when no option is selected in whether to add an ECT or Mentor or Transfer a participant. There was no validation being done. 
Because of how the existing add participant form works and having the new routing behind a feature flag i thought it'd be easier just to have a new form for this. 
Note, see commit `3569355` for info on updating the multistep controller before_action. It was causing slightly odd behaviour locally but adding the exceptions seemed to stop it.
3. login as a SIT
4. Go to the dashboard
5. Add a new ECT or Mentor
6. …
> Fix validation for add or transfer participant page

- app/controllers/schools/setup_school_cohort_controller.rb
- app/mailers/lead_provider_mailer.rb
- app/models/school_cohort.rb
- config/locales/en.yml
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/forms/schools/setup_school_cohort_form_spec.rb
- spec/mailers/lead_provider_mailer_spec.rb
Ticket: CST-610
Let the previous LP know the school has chosen a different programme for the new cohort.
> Create the programme changed email

- app/controllers/finance/participants_controller.rb
- app/views/finance/participants/index.html.erb
- spec/features/finance/participant_drilldown_spec.rb
Ticket:
https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?assignee=602cf8957b23f400685d969d&selectedIssue=CPDLP-1215
* Updated controller to look for `ParticipantDeclaration` by id.
* Updated rspec tests
> [CPDLP-1215] Enable search by declaration ID on participant drilldown

- app/controllers/schools/participants_controller.rb
- app/controllers/schools/transferring_participants_controller.rb
- app/forms/participant_mentor_form.rb
- app/forms/schools/add_participant_form.rb
- app/helpers/transferring_participant_helper.rb
- app/models/school.rb
- app/views/schools/transferring_participants/check_answers.html.erb
- app/views/schools/transferring_participants/choose_mentor.html.erb
- spec/forms/participant_mentor_form_spec.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/requests/schools/participants_request_spec.rb
[Jira Ticket:](https://dfedigital.atlassian.net/browse/CST-510)
[Part 1](https://github.com/DFE-Digital/early-careers-framework/pull/2036) added the back-end changes to support having a mentor "pool" at schools to facilitate making mentors visible across cohorts.
Part 2 now implementing this for selecting mentors for ECTs in the UI. 
**Note:** Because of the tight deadline we've decided only to enable selecting mentors across any cohort at this point. The user journey changes in the ticket will be implemented after go live.
**Note:** Before this can go live we need to populate the `school_mentors` of each school with the active mentors in that school
Does this change anything in …
> [CST-510] Mentors in multiple cohorts (Part 2)

- app/controllers/api/v1/npq_profiles_controller.rb
- app/helpers/application_helper.rb
- app/views/finance/participants/_npq_application.html.erb
- db/migrate/20220509091143_add_extra_eligiblity_npq_applications.rb
- db/schema.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- spec/views/finance/participants/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CN-133
- Added database migration to support extra NPQ funding flag on applications
- Incoming API requests from NPQ rails app can now populate this field
- After the integration is complete was can start exposing this in the API to lead providers via another PR to come
- Flag has been added to finance area for visibility
- View a user with an NPQ application
- Should see their application as not eligible for the new funding flag
- None
> [CN-133] Targeted NPQ funding

- app/views/schools/dashboard/_school_cohort_details.html.erb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
We should not display the Lead Provider and Delivery Partner names when the partnership is challenged.
Retrieve the latest partnership for the cohort and display:
- the LP and DP names, when it's not challenged
- "To be confirmed", when the partnership does not exist yet (pending)
-  no LP and DP names, when it's challenged
> Display blank LP and DP names when the partnership is challenged

- app/controllers/schools/setup_school_cohort_controller.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
Currently we allow FIP schools to choose to continue in the new cohort with the previous programme, even when it is challenged. 
Schools should be able to do that only when there is an active partnership in the previous cohort.
Update the journey logic when ects are expected for the new cohort, to also check if there's an active partnership in the previous cohort.
> Update the journeys router in school manage training

- spec/features/schools/choose_programme/choose_programme_spec.rb
The `and_i_see_the_current_lead_provider` was renamed to `and_i_see_the_lead_provider` and  the tests are failing.
Use the new step in the failing scenario.
> Fix the failing scenario

- app/helpers/dashboard_helper.rb
- app/services/coc_set_participant_categories.rb
- app/services/set_participant_categories.rb
- app/views/schools/participants/_ects.html.erb
- spec/features/schools/participant_dashboard/manage_fip_unpartnered_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/services/coc_set_participant_categories_spec.rb
- spec/services/set_participant_categories_spec.rb
- Ticket: NA
Showing a new section for participants with No qts on the dashboard. I've just followed the pattern for details being checked participants to decide where they should be displayed depending on the flag. 
Login as `cpd-test+tutor-10@example.com. A ppt with no qts is already on the dashboard.
> Add no qts section to ECT tab on participants dashboard

- app/models/induction_record.rb
- app/services/coc_set_participant_categories.rb
- app/services/mentors/create.rb
- db/seeds/multi_cohort_seeds.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/services/coc_set_participant_categories_spec.rb
- spec/services/mentors/create_spec.rb
Seed the `school_mentors` with the active mentors at each school.
Fix adding mentor to school mentors pool on creation
Temp fix for future induction start dates always appearing as participants transferring in
> Seed the school_mentors for mentors in multiple cohorts

- app/controllers/schools/setup_school_cohort_controller.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
Sentry reports a unique constraint violation caused by the `use_the_same_training_programme!` method.
It's likely users go back in history and click submit again.
Call the method only when there's no active partnership for the cohort.
> Guard copying the previous cohort programme

- app/forms/schools/add_participant_form.rb
- spec/forms/schools/add_participant_form_spec.rb
When a SIT adds themselves as a mentor it's erroring because there is no template for this instance. We're adding a temporary conditional to check if they're adding selves so that sentry doesn't error. We'll decide later whether to stick with this or add a new template.
[Error in sentry](https://sentry.io/organizations/dfe-teacher-services/issues/3262680691/?project=5748989&query=is%3Aunresolved)
> Extra conditional on sending added_and_validated_email

- app/models/finance/statement/ecf.rb
- spec/factories/call_off_contract.rb
- spec/features/finance/payment_breakdown_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1285
* Use `Finance::Statement::ECF.contract_version` to specify `CallOffContract.version`
> [CPDLP-1285] ECF Statements specify contract_version

- app/controllers/api/v1/npq_profiles_controller.rb
- app/models/npq_application.rb
- app/services/npq/build_application.rb
- db/migrate/20220510115548_add_cohort_npq_applications.rb
- db/schema.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1316
- NPQ applications are not cohort aware
- This PR gets us a step closer
- Default all existing NPQ applications to 2021
- Allow NPQ rails app to inject the cohort when applying
- Client work for this change is yet to be written
- So you could hand craft an API call and application should be assigned to set cohort
> [CPDLP-1316] NPQ app can pass cohort along

- app/controllers/participants/validations_controller.rb
- spec/requests/participants/validation_spec.rb
When a 2021 cohort user is trying to validation, the controller errors because it's trying to find their 2022 profile, which they don't have.
I was getting an error as below. This PR aims to resolve that.
> Fix validation controller error for 2021 cohort

- app/views/schools/participants/show.html.erb
- config/locales/en.yml
Feature spec that tests updating a participants email was failing. This fixes it.
2 issues:
1. Incorrect error shown for blank email address
2. Code to update email assumed change_of_circumstances feature, but spec running without that on.
> [Bugfix] Fix issue with changing participant email failing feature spec 

- spec/features/schools/participants/add_participants/unhappy_path_cannot_validate_spec.rb
Spec was failing because button label text had been updated elsewhere.
> [Bugfix] Update spec with new button label text

- app/forms/nomination_request_form.rb
- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- lib/tasks/schools.rake
- spec/services/invite_schools_spec.rb
We're about to invite schools without a SIT for 22/23. This PR allows the mailer to run in the background so that we can depend on Sidekiq to automatically retry invitations if they were to fail.
> Allow school inviter to run in the background

- app/views/schools/participants/_ects.html.erb
- app/views/schools/participants/_mentors.html.erb
- app/views/schools/participants/_moving_school.html.erb
- app/views/schools/participants/_not_training.html.erb
Put correct grid system in for each status so the content wraps after 2/3 and tightened up the spacing between headers and paragraphs. 
as examples.
> [Design update] - ECT and mentors dashboard

- app/services/induction/change_partnership.rb
- app/services/induction/migrate_participants_to_new_programme.rb
- app/services/partnerships/report.rb
- spec/services/induction/change_partnership_spec.rb
- spec/services/induction/migrate_participants_to_new_programme_spec.rb
When a partnership is challenged and subsequently a new partnership declared we should:
* Add a new `InductionProgramme`
* Add any participants from the previous (default) induction programme to the new induction programme
* Set the new induction programme as the default for the school cohort
> [Bug fix] Handle partnership change

- db/seeds/npq_applications.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1353
- Add a class than can then be called to generate test NPQ applications for environments
- Fire up a rails console
- Execute the following
```
require_relative "db/seeds/npq_applications.rb"
cpd = CpdLeadProvider.all.sample
Seeds::NPQApplication.new(cpd_lead_provider: cpd).call
```
- Should have a new NPQ application against the provider
> [CPDLP-1353] add class to encapsulate seeding of NPQ apps

- app/views/admin/participants/_details.html.erb
In the participant details view for admins the external id presented was from the preferred_identity on the induction record when it should be from the participant_identity on the participant_profile
> Use correct identity for admin view external id

- app/controllers/lead_providers/report_schools/base_controller.rb
- app/controllers/lead_providers/report_schools/delivery_partners_controller.rb
- app/views/dashboard/show.html.erb
- app/views/lead_providers/report_schools/base/start.html.erb
- Allow lead providers to report on _all_ cohorts they are a part of, not just the current one.
> Allow lead providers to report for any cohort they belong to

- app/controllers/schools/dashboard_controller.rb
- app/controllers/schools/setup_school_cohort_controller.rb
- app/models/school_cohort.rb
- app/services/induction/set_cohort_induction_programme.rb
- app/views/schools/dashboard/_school_cohort_details.html.erb
- db/migrate/20220516123711_add_to_be_confirmed_to_induction_programme.rb
- db/schema.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/support/matchers/have_summary_row.rb
- Ticket: CST-723
When a school set up the next cohort and choose to either change the lead provider or the delivery partner the dashboard shows that both of them need to be confirmed.
This is happening because the partnership is not created in the case above.
The solution proposed is to have two flags on the induction programme that store whether the lead provider or the delivery partner need to be confirmed.
> CST-723 - change LD DP issue

- app/controllers/api/v1/npq_funding_controller.rb
- app/services/npq/accept.rb
- app/services/npq/funding_eligibility.rb
- config/routes.rb
- spec/requests/api/v1/npq_funding_spec.rb
- spec/services/npq/funding_eligibility_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1335
- Added service class to calculate NPQ funding eligibility based on TRN and course
- Added private api endpoint so it is accessible via NPQ rails app api call
- Create a private api token
- Using this token request NPQ funding with `trn` and `npq_course_identifier`
- Should return appropriate result
> [CPDLP-1335] Internal API NPQ funding

- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- spec/serializers/api/v1/participant_from_induction_record_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1360
- Providers are not updating/refreshing records as the `updated_at` field is not accurately reflecting when a record has been updated
- `ParticipantFromInductionRecordSerializer` `updated_at` now considers more info to more accurately reflect when record was updated at
- Find ECF user via API
- Touch their induction record
- `updated_at` should have been affected
> [CPDLP-1360] Improve InductionRecord serializer updated_at

- lib/tasks/update_participant_profile_states.rake
e.g. 
1. participants with two induction records and same lead provider
2. participants with two induction records and different lead provider - is there any way of knowing which profile state belongs to which LP
CPDLP-1124 we have added lead providers to participant_profile_states - to backfill data we have some issues if the participant has already two induction records as they are likely to have states that belong to different lead providers
- Ticket: CPDLP-1124 (an extension)
This PR will try to capture as many scenarios as possible for the backfill, including the most straight forward which is copying the lead provider if there is only a single induction record as these participants are likely to only have had a single LP
> Back fill only those with a single induction record

- app/jobs/analytics/upsert_ecf_school_cohort_job.rb
- app/models/analytics/ecf_school_cohort.rb
- app/models/school_cohort.rb
- app/services/analytics/ecf_school_cohort_service.rb
- db/analytics_migrate/20220520074752_create_analytics_ecf_school_cohorts.rb
- db/analytics_schema.rb
- spec/models/school_cohort_spec.rb
This PR adds `school_cohorts` to the analytics database and it in sync with the primary table. There is an `after_save` callback on `SchoolCohort` that runs a background job to create or update the school cohort in the analytics database.
> Maintain school cohorts in analytics database

- app/views/schools/change_sit/success.html.erb
- Ticket: CST-764
Link "Return to manage your training" added to change SIT success page
> Add link "Return to manage your training" to change SIT success page

- config/sidekiq_cron_schedule.yml
This was accidentally left in when i was combined to separate jobs. It can be removed.
Its causing an error in [sentry](https://sentry.io/organizations/dfe-teacher-services/issues/3294481982/?project=5748989&query=is%3Aunresolved)
> Remove unused job

- app/services/participants/change_schedule/ecf.rb
- spec/features/inducation_nomination_spec.rb
- spec/services/participants/change_schedule/ecf_spec.rb
- [CPDLP-1371](https://dfedigital.atlassian.net/browse/CPDLP-1371): 
Is the user profile is nil because the participant is withdrawn then flag as invalid participant.
> [CPDLP-1371] - fix change schedule 500 errors

- app/jobs/finance/statements/mark_as_payable.rb
- app/models/finance/statement.rb
- app/models/finance/statement_line_item.rb
- app/models/participant_declaration.rb
- app/services/finance/declaration_statement_attacher.rb
- app/services/importers/statement_line_items.rb
- app/services/void_participant_declaration.rb
- db/migrate/20220518120740_create_statement_line_items.rb
- db/schema.rb
- spec/jobs/finance/statements/mark_as_payable_spec.rb
- spec/models/finance/statement_line_item_spec.rb
- spec/services/finance/declaration_statement_attacher_spec.rb
- spec/services/void_participant_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1049
- In order to accomplish clawbacks we need to associate a declaration with multiple statements
- One for where we payout and potentially another for when we do a refund
- At the moment a declaration can only be associated with a single statement
- So a join table has been introduced to overcome this limitation
- Introduce statement line items
- This joins statements and declarations together
- The old mechanism has been left in place as it is still used whilst new mechanism is slotted into position and missing data backfilled
- Added class to backfill line items for existing declarations associated with a statement
- When declarations are auto attached to a statement the line item is also created
- When voiding a declaration the …
> [CPDLP-1049] Introduce statement line items

- app/controllers/schools/transferring_participants_controller.rb
- config/locales/en.yml
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
There have been occurrences of SITs entering participants birth dates in the "start date" fields during the transfer of an existing participant.  Although we check for a valid date, we don't check that the date is chronologically correct in respect of the participant's existing schedule. This PR add a check to ensure the entered start date is after the start date of the first milestone of the participant's schedule.
> [Bugfix] Add check for start_date prior to schedule start_date during transfer

- app/controllers/admin/schools/participants_controller.rb
- app/models/school.rb
- spec/requests/admin/schools/participants_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-578)
Enable admin users to see all active participants in the school regardless of which cohort that are in
> [CST-578] Not all participants visible in admin view

- app/forms/schools/add_participant_form.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/requests/schools/add_participants_spec.rb
There was a sentry error showing again that the mailer had failed because of a incorrect template match. I think this is because they've gone through the journey fully rather than just adding themselves via the 'add yourself as a mentor'. This will stop the email being sent if they do go through the full journey.
> Add additional restriction on sending email for sit adding themselves

- app/controllers/schools/transferring_participants_controller.rb
- spec/requests/schools/transferring_participants_spec.rb
We were checking against a full name match when searching for ecf validation data in the transfer journey. This was causing problems when people were transferring ppts as this is the name stored from the DQT. If there's any difference in this then it won't match. Reducing it to just a first name matches how we initially validate against the DQT.
I've tested the updated statement a few times with some Zendesk tickets that have been raised because of the initial problem, it's finding the validation data just using the first name, trn and dob.
> Check only first name matches when checking for existing validation data

- app/controllers/api/v1/npq_profiles_controller.rb
- db/migrate/20220523120336_add_early_years_and_eligibility_field_to_npq_applications.rb
- db/schema.rb
- db/seeds/npq_applications.rb
- spec/factories/npq_application.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CN-167
For the lead provider team to be able to send this information through to providers if required, they need the data available to the API serialisers in ECF.
- Add extra optional params to create NPQApplication endpoint
- Adds works_in_nursery => Whether an applicant has indicated they work in a nursery, answered only if in catchment and indicated they work in childcare
- Adds works_in_childcare => Whether an applicant has indicated they work in childcare
- Adds kind_of_nursery => Which type of nursery an applicant works in, only asked if they indicated their work in a nursery
- Adds private_childcare_provider_urn => Ofsted URN of private childcare provider applicant works at if they work in a private nursery with an Ofsted URN
- …
> [CN-167] Accept new NPQ data

- app/components/delivery_partners/participants/table_row.rb
- app/views/delivery_partners/participants/index.html.erb
- spec/components/delivery_partners/participants/table_row_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1379
* Added fix to table row component to make sure correct `induction_record` was used for training_status and lead provider
> [CPDLP-1379] Fix where we get a participant's status from in the DP proposition

- app/controllers/admin/schools/cohorts/change_programme_controller.rb
- app/controllers/admin/schools/cohorts/change_training_materials_controller.rb
- app/models/partnership.rb
- app/services/induction/change_cohort_induction_programme.rb
- app/services/induction/change_core_induction_programme.rb
- spec/services/induction/change_cohort_induction_programme_spec.rb
- spec/services/induction/change_core_induction_programme_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-776)
Changing the induction programme choice via the admin UI was not:
* setting up a new `InductionProgramme`
* making it the default programme for the school cohort
* migrating participants from the previous programme to the new one
This PR adds a couple of services to replace the existing method.
> [CST-776] Fix change induction programme via admin ui

- app/controllers/schools/transferring_participants_controller.rb
- app/services/induction/enrol.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-775)
Currently we prevent withdrawn participants from transferring in the FIP to FIP transfer journey because of complications regarding making their `training_status` "active" with use of the `ParticipantProfileState`.  Work is underway to enable this in the LP team, in the meantime we can enable transfers and set the `training_status` without using the `ParticipantProfileState`.
There have been some assumptions made in the transfer journey, given that the participant has been withdrawn:
1. The participant is treated as if they are at the same LP and DP as the school (no options to choose different programme)
2. Only the new LP is notified of the transfer in
I've added a placeholder to reactivate the `ParticipantProfileState` …
> [CST-775] Enable withdrawn participants to transfer to FIP school

- app/models/npq_course.rb
- app/services/npq/funding_eligibility.rb
- spec/services/npq/funding_eligibility_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1385
- ASO and EHCO are the same course
- EHCO is merely rebranded ASO
- When checking funding make sure if user had funded ASO and now applying for ECHO treat them as the same course
- A similar thing will have to be done for the lead provider api side as it does not use the same service class but i might switch it to see it we can one point in the code to handle this
> [CPDLP-1385] funding treats ASO and EHCO as the same course

- app/models/npq_application.rb
- app/serializers/api/v1/npq_application_csv_serializer.rb
- app/serializers/api/v1/npq_application_serializer.rb
- app/serializers/api/v2/npq_application_csv_serializer.rb
- spec/factories/npq_courses.rb
- spec/models/npq_application_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NPQApplicationAttributes.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/NPQApplicationAttributes.yml
- https://dfedigital.atlassian.net/browse/CPDLP-1303
- Enhances `eligible_for_funding` flag in API
- It now takes into consideration if the participant has a previously accepted application for the same course
- If it does, it now returns not eligible for funding
- Added `ineligible_for_funding_reason` which provides a reason why an application is ineligible if it is ineligible
- Find someone with a previously accepted application
- Create a new application for them
- Download/View applications via API
- `eligible_for_funding` should be false
- `ineligible_for_funding_reason` should be populated with `previously-funded`
- Another test...
- Create an application for a private school
- `ineligible_for_funding_reason` should be populated with `establishment-ineligible`
- See updated docs at …
> [CN-131] [CPDLP-1303] Enhanced funding flag

- app/controllers/admin/schools_controller.rb
- spec/requests/admin/schools_spec.rb
Sometimes a school has more than one SIT registered (perhaps as the result of a school merger) and this results in a cartesian product and the school appearing more than once in the list.
This PR just adds a `distinct` clause to the query to prevent this from appearing.
> [Bugfix] Prevent schools appearing twice in admin view

- app/models/school.rb
- app/models/school_cohort.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/models/school_cohort_spec.rb
Now that we have the ability to create `Partnership`s to represent "relationships" (for participants that have transferred and are doing a different induction programme) these are being surfaced instead of the actual `Partnership` providers in the UI.  This PR ensures we only select active partnerships that are not relationships `where(relationship: false)` when retrieving lead provider and delivery partners for the school cohort.
> [Bugfix] Prevent showing relationship providers on dashboard

- spec/models/school_cohort_spec.rb
- Ticket: related to CST-153
Rubocop is raising new lint issues now that Ruby 3.1 is used.
The PR contains the fixes suggested.
> Ruby 3.1 Rubocop fix

- .github/workflows/test.yml
We recently upgraded Ruby to `3.1.2` but forgot to update the E2E test environment so that it also uses that version
> Use Ruby 3.1.2 for E2E tests

- db/seeds.rb
If you require these seeds you can add them to your PR/review app.
> Don't load transfer and multi-cohort seeds by default

- app/models/participant_declaration.rb
- app/models/participant_profile.rb
- spec/factories/participant_declaration.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
- Ticket: Second part of [CPDLP-1084](https://dfedigital.atlassian.net/browse/CPDLP-1084)
Instead of reading uplifts from profile, calculator now reads cached values from participant declaration
> Make calculator read cached uplifts

- Dockerfile
Ruby upgrade changed path to bundle exe that was stored in the shell history file for convenience.  This PR updated the path to use the new one
> Update path to bundle

- app/forms/schools/add_participant_form.rb
- app/helpers/sit_validate_participant_helper.rb
- app/views/schools/add_participants/_ect_or_mentor_details_summary.html.erb
- app/views/schools/add_participants/_sit_confirm_self_details_summary.html.erb
- app/views/schools/add_participants/complete.html.erb
- app/views/schools/add_participants/confirm.html.erb
- app/views/schools/add_participants/dob.html.erb
- app/views/schools/add_participants/trn.html.erb
- app/views/schools/add_participants/yourself.html.erb
- spec/features/schools/participants/add_participants/sit_adding_self_as_mentor/happy_path_sit_adds_self_as_mentor_spec.rb
- spec/features/schools/participants/add_participants/sit_adding_self_as_mentor/unhappy_path_sit_adds_themselves_as_mentor.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/helpers/sit_validate_participant_helper_spec.rb
- Ticket: [733](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-733)
SIT validating themselves as a mentor journey. 
- TRN and DOB pages for sit adding themselves as a mentor. 
**If a SIT attempts to validate themselves but we find no DQT record. we do not let them know this. It will continue to ask for them to update their information with the notification banner at the top of the page or when they log back in to the service** 
This will be iterated on in future work. Brian is aware of the loop and we'll look to improve the flow at a later date.
> [CST-733 ] SIT validates themselves via add journey

- app/components/admin/participants/table_row.html.erb
- app/components/admin/participants/table_row.rb
- app/components/participant_status_tag_component.rb
- app/views/admin/schools/participants/index.html.erb
- spec/components/admin/participants/table_row_spec.rb
- spec/components/participant_status_tag_component_spec.rb
The admin ui is inconsistent with the view the SIT sees when a participant has withdrawn training status.  The status tag component uses the `training_status` from the participant profile not the induction record so this PR adds the induction record to the call when available.
> [Bugfix] Use InductionRecord.training_status when available for status tag component

- lib/devise/strategies/passwordless_authenticatable.rb
- spec/cypress/support/step_definitions/database.js
- spec/factories/users.rb
- spec/support/features/user_helper.rb
- Ticket: [754](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=6239ad1e761efb0069ccde5e&selectedIssue=CST-754)
Extending the login time for user session. See linked ticket for reasons as to why it's being extended
> [CST-754] Extend login expiry time from 1 hour to 12 hours

- Dockerfile
- Ticket: n/a
- New ruby IRB changes has introduced autocomplete. This is super slow over the wire therefore should be disabled
- Disables IRB autocomplete for Docker build
- login to box and start rails console
- autocomplete should no longer work
> Disable autocomplete in Docker build

- app/services/early_career_teachers/create.rb
- app/services/induction/enrol.rb
- app/services/mentors/create.rb
- spec/services/induction/enrol_spec.rb
- Ticket: 1440
CPDLP-1383 removed the validations in PPS, and here it is possible to start recording an active profile state when a ppt transfers
It also adds in the Lead Provider (if it exists, and sometimes it won't when a ppt is created)
I would re-run some backfilling on PPSs following this PR
> CPDLP-1440 Allow active state to be recorded

- app/models/call_off_contract.rb
- app/models/finance/statement.rb
- app/models/finance/statement/ecf.rb
- app/models/finance/statement_line_item.rb
- app/models/participant_declaration.rb
- app/services/finance/ecf/output_calculator.rb
- app/services/finance/ecf/statement_calculator.rb
- app/views/finance/ecf/statements/show.html.erb
- spec/factories/call_off_contract.rb
- spec/lib/payment_calculator/ecf/contract/uplift_payment_calculations_spec.rb
- spec/models/call_off_contract_spec.rb
- spec/models/finance/statement/ecf_spec.rb
- spec/models/participant_band_spec.rb
- spec/services/finance/ecf/calculation_orchestrator_spec.rb
- spec/services/finance/ecf/output_calculator_spec.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1055
- ECF statements are now more interested in `Finance::StatementLineItem` rather than the declaration itself
- Removed `cache_original_value` as it does not appear to be used, I can introduce it back at a later date
- For ECF statements no longer use aggregators nor orchestrators
- The above has been re-implemented from the ground up with calculators instead
- These new classes have been plumbed into the frontend interface
- Uplift cap has been rounded upwards to the nearest £100 to prevent any partial uplift payments this makes clawback logic substantially easier
- I have not pruned the dead/dormant code of orchestrators and aggregators to prevent bloat of this PR
- Only via the backend can clawbacks can be introduced. There is …
> [CPDLP-1055] ECF Statement handles clawbacks

- app/components/schools/participants/coc_status_table.rb
- app/components/schools/participants/coc_status_table_row.rb
- app/controllers/schools/transfer_out_controller.rb
- app/forms/schools/transfer_out_form.rb
- app/models/induction_record.rb
- app/services/coc_set_participant_categories.rb
- app/views/schools/participants/_not_training.html.erb
- app/views/schools/participants/index.html.erb
- app/views/schools/participants/show.html.erb
- app/views/schools/transfer_out/check_answers.html.erb
- app/views/schools/transfer_out/check_transfer.html.erb
- app/views/schools/transfer_out/complete.html.erb
- app/views/schools/transfer_out/teacher_end_date.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/schools/participants/transfer_out/no_transfer_out.rb
- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- spec/services/coc_set_participant_categories_spec.rb
- Ticket: [432](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-432)
In addition to the transfer out route i've amended the participant categories and added a scope on the induction record. 
This is to cover the following scenarios
- PPT is transferred in but *is not* transferred out, old SIT still see's the PPT in either ECTs or Mentors. They never show on the 'Moving school' tab
- PPT is transferred out and moves straight into 'Moving School' tab
- PPT is transferred in and then transferred out. Goes in to moving schools tab once transferred out. 
For all the above, a PPT will only ever move into the Not training tab once the end date on the latest induction record for that school has passed.
> [CST-432] Transfer out journey

- app/models/finance/statement/ecf.rb
- app/models/finance/statement/npq.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1055
- this is need as there are many subclasses of a statement
- when looking a previous limits we hardcode the subclass we want to use since there are many subclasses
- otherwise does not form correct query to find previous statements
- none
> [CPDLP-1055] fix previous statements

- app/controllers/schools/transfer_out_controller.rb
- app/mailers/participant_transfer_mailer.rb
- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- spec/mailers/participant_transfer_mailer_spec.rb
- Ticket: [653](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-653)
Add notifications to ECTs and Mentors once a SIT has transferred them out. 
I'll rebase this once [the transfer out journey](https://github.com/DFE-Digital/early-careers-framework/pull/2149) has been merged
Notify templates are in the ticket linked above. 
I must have originally added the templates in the initial transfer journey work.
> [CST-653] Transfer out notifications

- app/views/admin/participants/_details.html.erb
Pass induction record to (recently fixed) participant status tag component to ensure correct training status is displayed to admin on the details tab view for a participant.
> [Bugfix] Pass induction_record to participant status tag component

- app/models/participant_declaration.rb
- spec/models/participant_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1439
- Using a blacklist strategy for this kind of thing is a recipe for bugs. As when new states are introduced this code must be changed to keep up
- Use whitelist to work out if a state is voidable instead
- none
> [CPDLP-1439] Whitelist voidable states

- app/models/declaration_state.rb
- app/models/finance/statement_line_item.rb
- app/services/finance/clawback_declaration.rb
- app/services/importers/clawbacks.rb
- spec/factories/participant_declaration.rb
- spec/models/finance/statement_line_item_spec.rb
- spec/services/finance/clawback_declaration_spec.rb
- spec/services/finance/declaration_statement_attacher_spec.rb
- spec/services/importers/clawbacks_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1054
- We have a load of declarations ids in spreadsheets that we want to be able to clawback for
- Adds a service that can process a single clawback for a given participant declaration
- It has been designed so that eventually we can plug this class into the API
- Adds an importer class that can process a CSV of declaration ids so we can bulk process clawbacks from the backend
- none
> [CPDLP-1054] Clawback service

- app/models/participant_declaration.rb
- app/services/record_declarations/base.rb
- config/locales/en.yml
- spec/features/participant_declarations/block_participant_declaration_paid_twice_spec.rb
- spec/features/participant_declarations/participant_declaration_steps.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/services/record_declarations/base_spec.rb
- spec/services/record_declarations/started/npq_spec.rb
- spec/support/shared_examples/participant_declaration_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1464
- After something has clawed back we want providers to be able to submit again for this event
- After a declaration is `awaiting_clawback` or `clawed_back` then a subsequent new declaration can be sent
- also no longer creates an additional declaration if submitted (or onwards) event is found and returns an error instead
- none
> [CPDLP-1464] Permit declarations after a clawback

- app/helpers/application_helper.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb
- spec/helpers/application_helper_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-824)
Make default tab for SITs the active registration cohort for their school
Make the default tab always be the one for the active registration cohort
> Default to active registration cohort tab for SITs

- app/services/participants/npq.rb
- spec/services/participants/npq_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1467
- We have data issues that around de-dupe that have not been resolved and are causing issues
- And at the moment we need to workaround these
- when a user has 2 active NPQ profiles from different lead providers
- select the profile that matches the calling lead provider
- none
> [CPDLP-1467] return relevant npq profile for calling provider

- app/services/npq/accept.rb
- spec/services/npq/accept_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1472
- EHCO and ASO are conceptually the same course just rebranded
- But under the hood in the implementation these are different courses
- Ensure that if a user is on ASO or EHCO any other ASO or EHCO application cannot be accepted
- none
> [CPDLP-1472] cannot accept EHCO if already on ASO

- app/controllers/api/v1/ecf_participants_controller.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1382
* Set order column to induction_records.updated_at/created_at to fix issues of ordering in pagination
> [CPDLP-1382] EDT seeing mismatches between ecf/participants JSON and CSV endpoints

- app/models/participant_profile.rb
- Ticket: n/a
- This is a pointless association auto touch that is an overhead with zero benefit
- Remove association touch
- none
> remove pointless auto touch on association

- spec/serializers/api/v1/participant_from_induction_record_serializer_spec.rb
PR #2288 broke the specs in #2287 as the new `touch` callbacks triggered during set up of the test data.
Wrap data set up in `ActiveRecord::Base.no_touching` blocks
> Prevented touch on data set up

- app/services/importers/seed_statements.rb
- spec/services/importers/seed_statements_spec.rb
- Ticket: [CPDLP-1456](https://dfedigital.atlassian.net/browse/CPDLP-1456)
The seed statements import create duplicate records when updating the contract version in the seed data. We want to update the contract version instead of creating a new statement.
The issue was revealed when the contract version of the NPQ statement for "March 2022" when bumped up to `0.0.2`.
Look for statements based on their name, provider and cohort and update the contract version once the statement is found or created.
1. Run the import on your local
2. Confirm 30 ECF records and 36 NPQ records were created
3. Update the contract version in some of the records and do step 1 and step 2 again. No new records should be created.
**Note:** I've not changed the contract version of the NPQ statement for "March 2022" …
> Prevent duplicate statements when importing the SeedStatements

- app/jobs/create_new_fake_sandbox_data_job.rb
- spec/jobs/create_new_fake_sandbox_data_job_spec.rb
- Ticket: [CPDLP-1474](https://dfedigital.atlassian.net/browse/CPDLP-1474)
Providers have been reporting that they are unable to see the NPQ Applications test data on sandbox. The issue seems to be that the NPQ applications are not associated to any cohorts, so we need to associate them to a cohort.
Associate the records to the active registration cohort when they are created.
> Associate the NPQ applications on sandbox to the active registration cohort

- app/models/induction_record.rb
- app/models/participant_profile_state.rb
- app/services/early_career_teachers/create.rb
- app/services/induction/enrol.rb
- app/services/mentors/create.rb
- app/services/participants/defer/validate_and_change_state.rb
- app/services/participants/resume/validate_and_change_state.rb
- app/services/participants/withdraw/validate_and_change_state.rb
- spec/docs/v1/participants_ecf_spec.rb
- spec/docs/v1/participants_spec.rb
- spec/docs/v2/participants_ecf_spec.rb
- spec/docs/v2/participants_spec.rb
- spec/models/induction_record_spec.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v1/test_ecf_participants_spec.rb
- spec/services/induction/enrol_spec.rb
- spec/services/participants/defer/early_career_teacher_spec.rb
- spec/services/participants/defer/mentor_spec.rb
- spec/services/participants/defer/npq_spec.rb
- spec/services/participants/resume/early_career_teacher_spec.rb
- spec/services/participants/resume/mentor_spec.rb
- spec/services/participants/resume/npq_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/participants/withdraw/mentor_spec.rb
- spec/services/participants/withdraw/npq_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/support/shared_examples/participant_actions_defer_support.rb
- spec/support/shared_examples/participant_actions_resume_support.rb
- spec/support/shared_examples/participant_actions_withdraw_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1383
If we are starting to record state changes from more than one LP from within the app, rather than a single LP through the api, we cannot keep the validations on participant_profile_states as they are:
e.g. If a participant is in an active state but is transferred to a new school (prior to being withdrawn), if we want to record the new active state, we should not receive a validation error
e.g. If a participant is in a withdrawn state, but is transferred to a new school, an active state following a withdrawn state would cause a validation error
Requirement of ticket: Current functionality remains the same, this means:
1) API users should still receive error messages if they: a) try to activate a withdrawn ppt, b) try to defer a …
> CPDLP-1383 Relocate validations and update tests

- app/controllers/schools/transferring_participants_controller.rb
- app/views/schools/transferring_participants/already_enrolled_at_school.html.erb
- spec/features/schools/participants/transferring_participants/already_enrolled_at_school_spec.rb
- spec/requests/schools/transferring_participants_spec.rb
This is to fix https://sentry.io/organizations/dfe-teacher-services/issues/3244970437/?project=5748989&query=is%3Aunresolved
- Ticket: 
Stopping a user from transferring a participant who is already enrolled at the school from being transferred in. We're getting a few sentry errors coming through.
> [Bug fix]  Stop a SIT from transferring a user who's already enrolled at the school

- app/services/record_declarations/actions/make_declarations_eligible_for_participant_profile.rb
- spec/services/record_declarations/actions/make_declarations_eligible_for_participant_profile_spec.rb
- spec/services/store_participant_eligibility_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1468
- There is a case where a participant is not yet eligible but a declaration has been submitted
- Later the participant is found to be eligible as a result their declaration(s) are changed to payable
- However when this happens we are not attaching them to a relevant statement therefore will not be paid for
- When participant becomes eligible also attach declarations to relevant statement
- after this is deployed will need to find eligible declarations left behind and attach them to the next statement
> [CPDLP-1468] When profile becomes eligible, attach declarations

- app/views/admin/schools/show.html.erb
Without the `class: 'govuk-link'` it doesn't pick up the GOV.UK styles and is the wrong shade of blue.
Use the `govuk_mail_to` (from [govuk-components](https://govuk-components.netlify.app/helpers/link/#output-rendered-using-the-class-helpers)) helper instead of the regular Rails `mail_to` one.
| ----- | ------ |
| ![Screenshot from 2022-07-04 15-41-42](https://user-images.githubusercontent.com/128088/177177138-8eb99be7-f177-43a9-9caf-d437acc217a3.png) | ![Screenshot from 2022-07-04 15-41-50](https://user-images.githubusercontent.com/128088/177177149-b20b7cdf-4ad0-4710-a069-8e7f044bdd63.png) |
> Fix the induction tutor email link style

- app/helpers/transfer_participant_helper.rb
- app/views/schools/transferring_participants/check_transfer.html.erb
- app/views/schools/transferring_participants/contact_support.html.erb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_active_cohort_speedbump_spec.rb
There's a [sentry error](https://sentry.io/organizations/dfe-teacher-services/issues/3353853344/?project=5748989&referrer=issue_alert-slack) where if a SIT can try to transfer a ppt from to the 2021 to their school, even if they don't have a school cohort for that year. This blocks them from doing it. We need them, at the minute, to create a full induction programme before they're able to do so. This is a quick fix, as agreed with Mili, Brian and Jo, that tells the user to go to support.
- Ticket: No ticket, but there is one in the backlog to handle this in a better way [828](https://dfedigital.atlassian.net/browse/CST-828)
Redirecting to contact support if the school cohort does not have a FIP for the 2021 cohort year set up.
> [Bug-fix] Prevent a SIT from transferring a user without a previous cohort

- config/routes.rb
Mili spotted the mythbusting redirect wasn't working but this fixes it. 
I don't think this has been noticed, at least we haven't had any sentry errors for it.
> Fix mythbusting redirect

- db/migrate/20220707091857_add_induction_start_date_to_participant_profile.rb
- db/schema.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-842)
Store the official induction start date for a participant so that it persists over their training
This needs to be populated either by some backfill task or at the point of adding/validating a participant.
Add `induction_start_date` column to `participant_profiles` table.
> CST-842 Store official induction start date

- app/mailers/participant_mailer.rb
- app/services/contact_school.rb
- spec/services/contact_school_spec.rb
We sent a batch of comms in May asking school induction tutors to register a programme for the 2022 cohort. We had a number of email addresses that bounced back. We have a specific template to contact all the schools to check that the SITs email is still correct or update it if necessary.
A list of the emails will be retrieved from prod. You can get a list of these from the status we've added when tagging
````Email.where(tags: "{preterm_reminder}", status: %w[permanent-failure temporary-failure technical-failure])````
Emails in may were tagged with ````preterm_reminder````
- Ticket: [827](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-827)
Adding a service to contact schools for SIT emails that have bounced.
This …
> Add email to send to schools whose SITs email has bounced

- app/services/participants/change_schedule/npq.rb
- spec/services/participants/change_schedule/npq_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1475
- this is a workaround for bad data where users have multiple NPQ profiles
- providers are failing to change schedule as it is not picking the correct profile
- users with multiple NPQ profiles with different providers can now change schedule
- we observe the calling provider and scope profiles to that provider
- none
> [CPDLP-1475] users with 2+ NPQ profiles can change schedule

- app/services/participants/change_schedule/ecf.rb
- spec/services/participants/change_schedule/ecf_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1414
- A user with 2 profiles where first provider has withdrawn
- This is causing the new provider not able to change schedule
- As we are still observing the state of the profile when we should be observing the state of the relevant induction record
- When changing schedule check the state of the relevant induction record not the profile 
- none
> [CPDLP-1414] can change schedule on withdrawn profile

- app/controllers/api/v1/npq_participants_controller.rb
- spec/docs/v1/npq_participants_spec.rb
- spec/factories/npq_application.rb
- spec/requests/api/v1/npq_participants_spec.rb
- Ticket: [CPDLP-1342](https://dfedigital.atlassian.net/browse/CPDLP-1342)
Withdrawals affect providers KPIs and SRM do not want providers submitting withdrawals if the participant has not started.
Overriding the `withdraw` API method in the NPQ participants controller to check if there is a started declaration for the participant and the course the lead provider is submitting the withdraw for. If it exists, then perform the withdraw action, otherwise return an error.
Scenario 1:
Send a [participant withdraw request](https://ecf-sandbox.london.cloudapps.digital/api-reference/reference-v1.html#api-v1-participants-npq-id-withdraw-put) that doesn't have a started declaration. You should receive an error instead.
Scenario 2:
Send a [participant withdraw …
> Reject npq withdrawals without started declarations

- app/services/induction/transfer_to_correct_school_cohort.rb
- spec/services/induction/transfer_to_correct_school_cohort_spec.rb
- Ticket: [838](https://dfedigital.atlassian.net/browse/CST-838) 
[Cohort transfers spreadsheet](https://docs.google.com/spreadsheets/d/12sL1aNI3IsGtHlR3OUDzemsfMTj_RHzcBjQu6skbdpw/edit#gid=0). To help speed up resolving cohort transfer support tickets we want to be able to quickly transfer the minimum required details to the correct school cohort. 
**this only allows a participant between school cohorts at their current school.** 
Adding a service that updates a users induction record and participant profile. 
Induction Record:
- induction programme
- start date
- schedule
Participant Profile:
- school cohort
- schedule
The start date is taken from the cohort academic year start date
At the minute this is to be used in the console
> Add a service to transfer a participant to a correct school cohort

- app/controllers/schools/setup_school_cohort_controller.rb
- app/forms/schools/setup_school_cohort_form.rb
- app/views/schools/setup_school_cohort/_change_delivery_partner_confirmation.html.erb
- app/views/schools/setup_school_cohort/_change_delivery_partner_submitted.html.erb
- app/views/schools/setup_school_cohort/_change_lead_provider_confirmation.html.erb
- app/views/schools/setup_school_cohort/_change_lead_provider_submitted.html.erb
- app/views/schools/setup_school_cohort/provider_relation_invalid.html.erb
- app/views/schools/setup_school_cohort/use_different_delivery_partner.html.erb
- app/views/schools/setup_school_cohort/what_changes.html.erb
- config/locales/en.yml
- config/routes.rb
- db/seeds/multi_cohort_seeds.rb
- spec/features/schools/choose_programme/choose_programme_invalid_provider_relationship_spec.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/forms/schools/setup_school_cohort_form_spec.rb
- Ticket: [594](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-594)
- Checking that a ProviderRelationship exists to prevent invalid partnerships
- Additional views showing SITs why they can't continue with creating a SchoolCohort and programme if the ProviderRelationship doesnt exist
- Specs for the above
- Updating exists SchoolCohort setup specs to create the ProviderRelationship, ensuring existing tests pass
- Updated routes for the new steps
- Updated SchoolCohortSetupForm
- Error messages, i spotted one was missing for the existing journey, so have added that. 
ProviderRelationships are created in the admin console. I think this is the first we've used a check against this, when creating a …
> [CST-594] Prevent school creating a cohort with an invalid partnership

- app/components/admin/npq/applications/analysis/table.html.erb
- app/components/admin/npq/applications/analysis/table.rb
- app/components/admin/npq/applications/analysis/table_row.html.erb
- app/components/admin/npq/applications/analysis/table_row.rb
- app/controllers/admin/npq/applications/analysis_controller.rb
- app/policies/npq_application_policy.rb
- app/views/admin/npq/applications/analysis/invalid_payments_analysis.html.erb
- config/routes.rb
- spec/components/admin/npq/applications/analysis/table_row_spec.rb
- spec/components/admin/npq/applications/analysis/table_spec.rb
- spec/factories/npq_application.rb
- spec/requests/admin/npq/applications/analysis_spec.rb
- Ticket: [CPDLP-1529](https://dfedigital.atlassian.net/browse/CPDLP-1529)
Add a new view to the admin area available only to AdminProfiles which lists all NPQ applications know to have payments made against them or payable declarations even though the NPQ Application associated with the NPQ Profile is not "Accepted"
login as an Admin user and visit `/admin/npq/applications/analysis`
```
NPQApplication.left_outer_joins(profile: [:participant_declarations])
.where.not(participant_profiles: { id: nil })
.where(lead_provider_approval_status: %w[pending rejected],
participant_profiles: {
participant_declarations: { state: %w[paid payable] },
})
.uniq
```
> Adds a page to view invalid payments against applications

- app/controllers/finance/ecf/statements_controller.rb
- app/services/finance/ecf/output_calculator.rb
- app/services/finance/ecf/output_calculator2.rb
- app/services/finance/ecf/statement_calculator2.rb
- config/routes.rb
- spec/services/finance/ecf/output_calculator2_spec.rb
- spec/services/finance/ecf/statement_calculator2_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1469
- We are discounting duplicates for ECF statements
- This was to counter people who had double posted due to duplicates
- We now need to remove this feature so we can count legal double postings with a declaration followed by a clawback followed by another declaration
- Added under a different endpoint so this can be tested with prod data before we roll out
- Do not discount duplicates for ECF
- Assess the damage there maybe none
- This way we can identity duplicates and clawback if needed
- If all is good the new version will supersede the old version and merged back into the one true version
- To view the new version of a statement, when view an existing ECF statement change the end of the URL to `statements/august-2022/show2` …
> [CPDLP-1469] Don't de-dupe declarations for ECF statements

- app/services/finance/ecf/output_calculator2.rb
- spec/services/finance/ecf/output_calculator2_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1469
- With the removal of duplicates the new test calculator does not count uplifts correctly
- Count only uplifts on started declarations
- none
> [CPDLP-1469] ECF calculator only considers uplifts for started

- app/services/npq/ehco/targeted_delivery_funding_eligibility_updater.rb
- lib/tasks/npq/ehco/update_targeted_delivery_funding_eligibility.rake
- spec/services/npq/ehco/targeted_delivery_funding_eligibility_updater_spec.rb
https://dfedigital.atlassian.net/browse/CN-308
Adds rake task that updates `targeted_delivery_funding_eligibility` to false for all Application records with the EHCO course, `targeted_delivery_funding_eligibility` set to true, and where created after the relaunch.
1. Create an Application record with these attributes:
```
course == Course.ehco.first
created_at >= 6 June 2022 12:00
targeted_delivery_funding_eligibility == true
```
2. Run ehco:update_targeted_delivery_funding_eligibility:dry_run 
3. See that it has shown that this record will be updated
4. Check that targeted_delivery_funding_eligibility change has not been persisted.
5. Run ehco:update_targeted_delivery_funding_eligibility:run
6. Check that targeted_delivery_funding_eligibility change has been persisted.
> [CN-308] Retrospectively remove ECHO from targeted support funding eligibility

- app/views/schools/transferring_participants/contact_support.html.erb
• Replaced “sart” with “start”
• Replaced “tam” with “team”
• Added request for "previous school's name"
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119/backlog?selectedIssue=CST-876
This PR covers some of the quick fixes referenced in the ticket. 
The only outstanding task on this ticket is the addition of the participant name variable into the H1 and body content (see screengrab). I'll refer this to Brian as I don't want to do this incorrectly.
> Quick typo fix, added to requested information

- app/views/schools/transferring_participants/cannot_add.html.erb
Noticed typo "progamme" in live content. Changed to "programme".
> Correcting typo - progamme

- .githooks/pre-commit
- app/controllers/api/v1/ecf_participants_controller.rb
- app/controllers/api/v1/npq_participants_controller.rb
- app/services/api/v1/ecf_participants/index.rb
- config/routes.rb
- spec/docs/v1/npq_participants_spec.rb
- spec/docs/v1/participants_ecf_spec.rb
- spec/docs/v2/npq_participants_spec.rb
- spec/docs/v2/participants_ecf_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/npq_participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/requests/api/v2/npq_participants_spec.rb
- swagger/v1/api_spec.json
- swagger/v2/api_spec.json
- Ticket: [CPDLP-1443](https://dfedigital.atlassian.net/browse/CPDLP-1443)
We want to enable providers to retrieve single participant records via the API, by using the participant's id.
- Updated the pre-commit git hook to stop falsely reporting AWS keys in the swagger `components/schemas`
- Add API endpoints to retrieve single ECF and NPQ participants
- GET /api/v1/participants/ecf/:id
- GET /api/v1/participants/npq/:id 
- Update the swagger V1 API spec
1. Retrieve a single ECF participant via the API
2. Retrieve a single NPQ participant via the API
3. Check the changes are reflected in the swagger docs
You can use the index endpoints to retrieve all the ECF/NPQ participants, pick a participant id from the list and then try the new api endpoints to retrieve the participant. Confirm the …
> [CPDLP-1443] Retrieve single participant records via the API

- app/controllers/schools/participants_controller.rb
- app/helpers/schools/participants_helper.rb
- app/models/induction_programme.rb
- app/policies/participant_profile/ecf_policy.rb
- app/services/participants/withdraw/validate_and_change_state.rb
- app/views/schools/participants/edit_email.html.erb
- app/views/schools/participants/edit_name.html.erb
- app/views/schools/participants/reason_to_edit_name.html.erb
- app/views/schools/participants/replace_with_a_different_person.html.erb
- app/views/schools/participants/should_not_have_been_registered.html.erb
- app/views/schools/participants/show.html.erb
- app/views/schools/participants/update_email.html.erb
- config/locales/en.yml
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/policies/participant_profile/ecf_policy_spec.rb
- spec/requests/schools/participants_request_spec.rb
- spec/support/features/pages/schools/edit_school_participant_email_page.rb
- spec/support/features/pages/schools/edit_school_participant_name_page.rb
- spec/support/features/pages/schools/reason_to_change_school_participant_name_page.rb
- spec/support/features/pages/schools/school_participant_details_page.rb
- spec/support/features/pages/schools/school_participant_email_updated_page.rb
- spec/support/features/pages/schools/school_participant_replaced_by_a_different_person_page.rb
- spec/support/features/pages/schools/school_participant_should_not_have_been_registered_page.rb
- spec/support/features/steps/changes_of_circumstance_steps.rb
- Ticket: [As a SIT, I can edit a participant's email address](https://dfedigital.atlassian.net/browse/CST-188)
Added a confirmation view once a tutor has been able to successfully update the email address of one of their participants.
It also includes a few tweaks:
- Keep marked the option selected by a SIT when they click back in one of the views to change a participant's name 
- Do not pre-fill the input box to edit a participant's name or email address
> [CST-188]: add confirmation page when tutor changes a participant's email address

- app/models/provider_relationship.rb
Being able to see provider relationship events would be useful when diagnosing problems. Recently some have been unexpectedly changed and we've not been able to work out how/why.
> Add has_paper_trail to ProviderRelationship

- app/services/induction/change_induction_record.rb
- config/initializers/secure_headers.rb
- spec/services/induction/change_induction_record_spec.rb
The change process for an `InductionRecord` involves duplicating the existing record and applying the changes to the duplicate and updating the existing one with a `changing` status and an `end_date`.  When a record has a future `start_date` we need to preserve it and so this creates records with duplicate `start_date`s. This becomes an issue when trying to sort on `start_date` or when trying to traverse InductionRecords by start and end dates. As there is no real need to preserve the history of future events that haven't happened, we can prevent this and just update a future record instead of creating a new successor record.
Update `Induction::ChangeInductionRecord` to handle future induction records.
> [Bug fix] Prevent duplicate start_dates in induction records

- app/controllers/schools/choose_programme_controller.rb
- app/views/schools/choose_programme/appropriate_body_type.html.erb
- app/views/schools/choose_programme/confirm_programme.html.erb
- config/routes.rb
- data/appropriate_bodies.csv
- spec/cypress/integration/schools/ChooseProgramme.feature
- spec/cypress/integration/schools/ChooseProgrammeCIPOnly.feature
- spec/features/schools/choose_programme/new_schools_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/requests/schools/choose_programme_spec.rb
- spec/support/features/pages/schools/school_report_programme_wizard.rb
- Ticket: CST-798
* Appropriate body type copy missing on new school choose programme journey.
* Two appropriate body's names fixes.
* When a new school set a programme the confirmation screen is shown before the appropriate body selection.
> [CST-798] Fixes

- app/services/importers/seed_statements.rb
- spec/services/importers/seed_statements_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1263
- `Importers::SeedStatements` was used to mutate data which had undesired outcomes
- We want to make this class do initial seeding only
- Make this importer for genesis data only
- If it finds a record already exists it will simply skip it
- We do not want to use this class to mutate data this needs to be done by hand
- none
> [CPDLP-1263] Statement seeder only provides genesis seeds

- app/services/importers/clawbacks.rb
- spec/services/importers/clawbacks_spec.rb
- Ticket: n/a
- This improves the class that processes clawbacks in csv format
- If there are any exceptions they are caught and logged and no longer exit the process part way thru
- none
> Better clawback service with logging of exceptions

- app/controllers/finance/change_training_statuses_controller.rb
- app/forms/finance/change_training_status_form.rb
- app/models/induction_record.rb
- app/services/participants/base.rb
- app/services/participants/defer/validate_and_change_state.rb
- app/services/participants/profile_attributes.rb
- app/services/participants/resume/validate_and_change_state.rb
- app/services/participants/withdraw/validate_and_change_state.rb
- app/views/finance/change_training_statuses/new.html.erb
- app/views/finance/participants/_ecf_profile.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/finance/change_training_status_spec.rb
- spec/forms/finance/change_training_status_form_spec.rb
- Ticket: 
- https://dfedigital.atlassian.net/browse/CPDLP-1489
- https://dfedigital.atlassian.net/browse/CPDLP-1490
- https://dfedigital.atlassian.net/browse/CPDLP-1522
* Added new form to allow changing of `training_status`
* Updated validation to allow admin user to change status
* Login as finance role
* Go to finance drill down page
* Click change on participant profile
* https://ecf-review-pr-2362.london.cloudapps.digital/finance/participants/9956f5f2-030c-4bdf-90be-784621dfc49e
* https://ecf-review-pr-2362.london.cloudapps.digital/finance/participants/3ee6c188-9586-44f6-a271-4933295fec05
> [CPDLP-1489] allow DfE user to change training status

- app/components/delivery_partners/participants/table_row.html.erb
- app/components/delivery_partners/participants/table_row.rb
- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- app/serializers/delivery_partners/participants_serializer.rb
- spec/components/delivery_partners/participants/table_row_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/models/participant_profile_spec.rb
- spec/serializers/delivery_partners/participants_serializer_spec.rb
- Ticket: [CPDLP-1552](https://dfedigital.atlassian.net/browse/CPDLP-1552)
The check data service shows wrong participant roles in the UI and csv extract, when users are both Mentors and Induction Tutors.
- I created the `role` method in the `ParticipantProfile::ECF` model to determine the participant's role based on their participant type
- Replaced the `User#user_description` method that shows the wrong role in both the UI and CSV serializer, with the `ParticipantProfile::ECF#role`
> [CPDLP-1552] Show the correct participant role in the delivery partners check data service

- app/controllers/schools/transferring_participants_controller.rb
- app/forms/participants/participant_validation_form.rb
- app/forms/schools/add_participant_form.rb
- app/forms/schools/transferring_participant_form.rb
- app/lib/teacher_reference_number.rb
- app/validators/teacher_reference_number_validator.rb
- config/locales/en.yml
- spec/features/participants/participant_validation_spec.rb
- spec/features/schools/participants/add_participants/reporting_participants_with_trn_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/forms/participants/participant_validation_form_spec.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/forms/schools/transferring_participant_form_spec.rb
- spec/lib/teacher_reference_number_spec.rb
- spec/validators/teacher_reference_number_validator_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-891)
Allow SITs and participants to enter TRNs as per the guidance on the forms and handle the stripping of the unwanted characters.
TRN could contain letters and slashes e.g. RP99/12345
Once stripped of everything except numerical digits:
* TRN should be between 5 and 7 digits long
* We should pad with zeros on the left to make the TRN 7 digits long if not e.g. "123456" becomes "0123456"
Adds a `TeacherReferenceNumber` class that handles the formatting
Adds a `TeacherReferenceNumberValidator` to simplify validation of TRN entry.
Modify forms that add, transfer or validate participants to use these new classes
> [CST-891] Accept slashes and letters in TRN input

- config/routes.rb
- spec/docs/v2/npq_applications_spec.rb
- spec/docs/v2/npq_participants_spec.rb
- spec/requests/api/v1/npq_participants_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/requests/api/v2/npq_participants_spec.rb
- swagger/v2/api_spec.json
- Ticket: [CPDLP-1550](https://dfedigital.atlassian.net/browse/CPDLP-1550)
This is a follow up PR to the #2323, #2335 PRs, in order to add missing changes to API v2.
- Added missing API v2 specs for the NPQ withdrawals
- Added the API v2 endpoint for retrieving single NPQ applications. Also, I added some specs
> [CPDLP-1550] Add missing NPQ related changes to API v2

- spec/forms/participants/participant_validation_form_spec.rb
Fix intermittent spec fail, spec uses random length TRN, we are now formatting those with padded zero to send to validation, however spec expects unformatted version so fails when TRN length < 7.
Change spec to expect `formatted_trn` from the form object.
> Fix flaky spec

- app/controllers/admin/schools/participants_controller.rb
- app/models/induction_record.rb
- spec/features/admin/schools/view_school_participants_spec.rb
- spec/models/induction_record_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-904)
Participants that are transferring in/out should be listed in the admin console when viewing a school's participant list
Additional scope on `InductionRecord` for `current_or_transferring_in`
Changes to participants query in the admin schools participants controller.
> [CST-904] Ensure transferring participants appear in the admin view for a school

- app/models/partnership.rb
- spec/models/partnership_spec.rb
The `#in_challenge_window?` method expects `challenge_deadline` is set. When it's `nil` we're throwing an error.
If there is no deadline I assume we cannot be in a window.
> Stop challenge window check fail on nil deadline

- app/controllers/api/v1/npq_applications_controller.rb
- app/controllers/finance/change_lead_provider_approval_statuses_controller.rb
- app/forms/finance/change_lead_provider_approval_status_form.rb
- app/models/npq_application.rb
- app/services/npq/accept.rb
- app/services/npq/change_to_pending.rb
- app/services/npq/reject.rb
- app/views/finance/change_lead_provider_approval_statuses/new.html.erb
- app/views/finance/participants/_npq_application.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/finance/change_lead_provider_approval_status_spec.rb
- spec/forms/finance/change_lead_provider_approval_status_form_spec.rb
- spec/jobs/admin/npq_applications/eligibility_import_job_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/services/npq/accept_spec.rb
- spec/services/npq/change_to_pending_spec.rb
- spec/services/npq/reject_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1244
* New "Change to pending" link added to participant drill down support page
* Login as `finance@example.com`
* Go to the participant drill down page
* Enter participant id with NPQ Application
> [CPDLP-1244] Allow a DfE user to change the status of an NPQ application from the support page

- config/initializers/google_drive_credentials.rb
- Ticket: [CPDNPQ-422](https://dfedigital.atlassian.net/browse/CPDNPQ-422)
This needs to be followed up with a PR that moves the lookups for GOOGLE_DRIVE_NPQ_UPLOAD_FOLDER_ID and GOOGLE_DRIVE_NPQ_DOWNLOAD_FOLDER_ID to use the credentials file. I'm doing this here so that we can get things working so that records can be updated immediately.
> [CPDNPQ-422] Copy GOOGLE_DRIVE_NPQ_DOWNLOAD_FOLDER_ID to ENV

- app/services/admin/npq_applications/eligibility_import/csv_parser.rb
- spec/jobs/admin/npq_applications/eligibility_import_job_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CN-422
This makes sure that “TRUE”, “true”, “TRue”, and “ TRUE” all resolve to true. It also ensures whitespace in other columns does not prevent the importer working correctly.
> [CN-422] Fix whitespace and case issues in CSV parser

- app/controllers/finance/schedules_controller.rb
- app/views/finance/schedules/index.html.erb
- db/seeds/schedules/ecf_extended.csv
- db/seeds/schedules/ecf_reduced.csv
- db/seeds/schedules/ecf_replacement.csv
- spec/features/finance/schedules_spec.rb
- spec/models/finance/schedule/ecf_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1476
- Add missing 2022 extended, reduced and replacement schedules for ECF
- In finance area split schedules by cohort for improved readabilty
- none
> [CPDLP-1476] add extra 2022 ECF schedules

- docs/source/release-notes.html.erb
- Ticket: n/a
- Add release notes for newly added non-standard ECF schedules for 2022 cohort
- See https://ecf-review-pr-2404.london.cloudapps.digital/api-reference/release-notes.html#17-8-2022
- none
> release note for 2022 non standard ecf schedules

- app/views/finance/change_training_statuses/new.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- spec/factories/participant_profiles.rb
- spec/features/finance/change_training_status_spec.rb
The drilldown page is using the cached training_status value from the
participant profile record to display the participant training status
for NPQ participants, when the API is using the latest participant profile
state record. These two can go out of sync and cause issues and confusion.
Replacing the ParticipantProfile training_status in the drilldown page with the 
ParticipantProfile state method ensures the correct state is always displayed.
Eventually the InductionRecord will replace both the training_status and the 
ParticipantProfileState. ECF participants already using the InductionRecord,
but the NPQ ones not just yet.
- Ticket: CPDLP-1655
I changed the drilldown page to display the `ParticipantProfile.state` instead of the `training_status`, but only for the NPQs
> CPDLP-1655-npqs-training-status

- config/initializers/filter_parameter_logging.rb
I noticed some detail we probably shouldn't be logging while hunting down an error in the logs.
Added the immediate offenders here:
Others that _might_ be worth filtering:
> Stop full name and date of birth from being logged

- app/forms/schools/setup_school_cohort_form.rb
- app/helpers/schools/dashboard_helper.rb
- app/helpers/schools/setup_school_cohort_helper.rb
- app/views/schools/dashboard/_school_cohort_details.html.erb
- app/views/schools/setup_school_cohort/_training_confirmation_school_funded_fip.html.erb
- app/views/schools/setup_school_cohort/how_will_you_run_training.html.erb
- app/views/schools/setup_school_cohort/programme_confirmation.html.erb
- app/views/schools/setup_school_cohort/training_confirmation.html.erb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/forms/schools/setup_school_cohort_form_spec.rb
- spec/support/features/pages/schools/choose_programme/school_funded_fip_training_submitted_page.rb
- Ticket: [Update registration journeys for CIP-only schools setting up their 2022/23 cohort](https://dfedigital.atlassian.net/browse/CST-965)
- Remove "ects and mentors" row from the school dashboard for CIP-only schools, so they can't manage participants.
- Add copy saying it at the botom.
- Do not show FIP choice when a CIP-only school is choosing an induction programme
- Customize the confirmation screen for schools that choose a school funded fip programme.
> [CST-965] update registration journeys for cip only schools setting up their 2022 23 cohort

- app/services/api/v1/ecf_participants/index.rb
- spec/requests/api/v1/ecf_participants_spec.rb
When filtering by cohorts while retrieving ECF participants we are getting a 500
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1721
Return a list of records rather than one record to allow mapping the id in the cohorts query. 
Is the test setup correct or am I missing something?
> [CPDLP-1721]: Fix bug in cohorts filter on ECF participants endpoint

- app/services/participants/ecf.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/participants/ecf_spec.rb
A provider is using the header: `X-With-Server-Date` to time travel on sandbox to test different declarations.
They are getting a 422 when attempting to set milestones that occur in the subsequent year (eg `retain-3`)
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1538
For an ECF participant, when retrieving induction records, we are only returning records from the current cohort. The current cohort is dependant on the time of year if the `multiple_cohorts` flag has been activated. This means when we attempt to return induction records for a cohort with milestones in the next year, we end up querying the incorrect cohort (current cohort will return 2022 although the one we need is 2021). Trying to tie induction records to the wrong …
> [CPDLP-1538] Return all cohorts past 2021 when querying participant induction records

- .githooks/pre-commit
```
> rubocop --auto-correct
--auto-correct is deprecated; use --autocorrect instead.
```
https://github.com/rubocop/rubocop/issues/10095
Swap --auto-correct to --autocorrect.
> Use --autocorrect instead of --auto-correct

- spec/serializers/api/v1/participant_serializer_spec.rb
The serializer was using the user and the expectation was using the profile. This lead to intermittent failures due to possible rounding differences between the two.
Use the correct updated_at column
https://github.com/DFE-Digital/early-careers-framework/blob/develop/app/serializers/api/v1/participant_serializer.rb#L88
> Intermittent Failure - Use correct updated_at for expected_json

- app/controllers/schools/transfer_out_controller.rb
- app/models/induction_record.rb
- app/services/coc_set_participant_categories.rb
- spec/models/induction_record_spec.rb
- spec/services/coc_set_participant_categories_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-881)
When a SIT tells us a participant is leaving, they should still have a `current` induction record until their leaving date has passed.
Participants claimed by another school should be treated as active participants in their old school's dashboard until they have left the school.
Fix the `InductionRecord.current` scope
Fix the `CocSetParticipantCategories` service to include the claimed participants with the active induction records.
> [CST-881] fix issues with leaving participants

- analytics_queries/Makefile
- analytics_queries/README
- analytics_queries/declarations.sql
- analytics_queries/participants.sql
- analytics_queries/partnerships.sql
- analytics_queries/schools.sql
No code changes here, just streamlining the analyics export.
The process is made easier by:
* moving the `\copy` statement inside the SQL files
* adding a `Makefile` that creates an export directory and moves the queries to the right location
* automatically strips `\n` from the SQL files so they work with `\copy`
Would recommend disabling whitespace to review, most of the changes are adding indentation as we're wrapping the queries in `\copy ( ... )`.
> Add Makefile to ease analytics exporting

- spec/docs/v3/participant_declarations_spec.rb
Testing strategy recently changed removing large setup contexts.
- Ticket: N/A
Remove old setup as it no longer exists, in favour of new strategy.
V3 tests are ignored as they fail anyway, but get the test to the point it fails on the endpoints not existing and not the setup
> Remove now deprecated shared context in favour of new test setup

- app/jobs/remove_school_mentor_job.rb
- app/models/school_mentor.rb
- app/services/induction/transfer_and_continue_existing_fip.rb
- app/services/induction/transfer_to_schools_programme.rb
- app/services/mentors/change_school.rb
- app/services/mentors/remove_from_school.rb
- config/sidekiq_cron_schedule.yml
- db/migrate/20220909081139_add_remove_from_school_on_to_school_mentors.rb
- db/schema.rb
- spec/jobs/remove_school_mentor_job_spec.rb
- spec/models/school_mentor_spec.rb
- spec/services/induction/transfer_and_continue_existing_fip_spec.rb
- spec/services/induction/transfer_to_schools_programme_spec.rb
- spec/services/mentors/change_school_spec.rb
- spec/services/mentors/remove_from_school_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-998)
When a mentor is transferred to a different school, we are not adding/removing `SchoolMentor` records so that the mentor can appear in the list of mentors at the new school (and be removed from the list at the old school)
Also need to ensure that the mentees are disassociated.
There is a complication in that a transfer can happen with a future date. In this case we need to defer removing from the old school and mentees until the transfer date.  I've added a `Date` field to `SchoolMentor` named `remove_from_school_on` that can be used for this, in conjunction with a daily cron job.
Add new column `remove_from_school_on` to `school_mentors`
Add new service `Mentors::ChangeSchool`
Update school transfer services to call …
> [CST-998] Add mentors to new school and remove from old when transferring

- app/services/participants/change_schedule/ecf.rb
- app/services/participants/defer/validate_and_change_state.rb
- app/services/participants/profile_attributes.rb
- app/services/participants/resume/validate_and_change_state.rb
- app/services/record_declaration.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/services/participants/change_schedule/early_career_teacher_spec.rb
- spec/services/participants/change_schedule/ecf_spec.rb
- spec/services/participants/change_schedule/npq_spec.rb
- spec/services/participants/defer/early_career_teacher_spec.rb
- spec/services/participants/defer/mentor_spec.rb
- spec/services/participants/defer/npq_spec.rb
- spec/services/participants/resume/early_career_teacher_spec.rb
- spec/services/participants/resume/mentor_spec.rb
- spec/services/participants/resume/npq_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/participants/withdraw/mentor_spec.rb
- spec/services/participants/withdraw/npq_spec.rb
On different endpoints, if we pass in a course identifier that exists but is not associated to the participant, we raise a 500 rather than a 422 error with the correct message
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1541
- Reuse the course validation added for record declarations in Profile attribute validations which are used across resume/defer/withdraw actions. Expose private method `participant_identity` to allow validation to complete
- Skip validations if user profile does not exist (as it won't if the course identifier is incorrect)
- Ensure change schedule ECF validates course identifier as well
- To tidy up validations and avoid raising unnecessary ones validate milestone on declarations if `participant_profile` …
> [CPDLP-1541] Validation error when passing in wrong course-identifier

- app/services/record_declaration.rb
- config/locales/en.yml
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1770
- There is a regression whereby providers cannot re-post for a declaration after it has been clawed back. ie the original declaration is in `awaiting_clawback` or `clawed_back` state
- This removes the validation `record_does_not_exists_with_different_declaration_date`
- I'm not sure why we have this validation and what purposes it serves so I have removed it as it blocking providers from reposting
- There already exists the validation `validates_billable_slot_available` which checks there is open slot available otherwise prevents the declaration from getting through
- This should be enough for our needs to my understanding
- none
> [CPDLP-1770] Remove different declaration date validation

- app/forms/challenge_partnership_form.rb
- app/models/induction_programme.rb
- app/models/induction_record.rb
- app/models/partnership.rb
- app/services/induction/change_cohort_induction_programme.rb
- app/services/induction/set_cohort_induction_programme.rb
- app/services/partnerships/challenge.rb
- app/views/admin/participants/_induction_records.html.erb
- spec/forms/challenge_partnership_form_spec.rb
- spec/models/induction_programme_spec.rb
- spec/models/partnership_spec.rb
- spec/requests/admin/schools/cohorts/challenge_partnership_spec.rb
- spec/services/partnerships/challenge_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1001)
Ensure changes to partnership are reflected in the service.
* When a partnership is challenged: do not display provider/partner names in the UI
* When a new partnership is added: add new programme and move users in existing cohort default programme to it.
* Removed the `Partnership#challenge!` method and moved functionality to the existing `Partnerships::Challenge` service
> [CST-1001] ensure programme changes are added correctly

- app/services/transfers/npq_participants.rb
- spec/services/transfers/npq_participants_spec.rb
A task to move an NPQ participant between lead providers prompted creating a service to wrap the logic and test it 
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1772
Using the external identifier of the participant and the ID of the new NPQ lead provider, the participant's application should move to the new NPQ lead provider. The new provider can now make declarations to this participant
I think(?) this isn't the right place to add this service, as this hierarchy is used differently for inheritance purposes. Happy to move to `services/npq` or as a standalone service class, any thoughts welcome
> [CPDLP-1772] Add new service to transfer an NPQ participant between lead providers

- app/middlewares/api_request_middleware.rb
- spec/middlewares/api_request_middleware_spec.rb
We currently only create `ApiRequests` if the API version is 1. However we now support v2 and will be supporting v3 soon. 
- Ticket: N/A
Allow multiple versions to create `ApiRequest`s
I went with only `\d{1}` could go with `\d+` so we don't have to worry about this anymore, thoughts?
> Allow creating `ApiRequest`s on API versions past v1

- app/models/user.rb
- spec/models/user_spec.rb
- Ticket: n/a
- Remove `User#cohort`
- this conceptually no longer makes sense. as someone could be in multiple cohorts via different enrolments. eg. ECT in 2021 then 2022 for an NPQ
- also does not appear to be used anywhere
- This is some legwork as I try to hammer in `ParticipantProfile#cohort` to become the source of truth for the cohort
> Remove User#cohort

- app/models/participant_identity.rb
- app/services/participant_profile_resolver.rb
- spec/services/participant_profile_resolver_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1797
- this bug is when a user has both ECF and NPQ profiles
- when selecting the NPQ profile it would return the ECF profile
- when attempting to resolve an NPQ profile should now return correct profile
- none
> [CPDLP-1797] bugfix when ECT and NPQ resolve profile correctly

- app/services/data_stage/update_staged_schools.rb
- spec/services/data_stage/update_staged_schools_spec.rb
- Ticket: [CST-1051](https://dfedigital.atlassian.net/browse/CST-1051)
We are not updating all schools coming from GIAS.
We ignore non-eligible schools.
However we need to extend the definition of eligible-schools to include those whose field `Section41-approval` has changed to `"Approved"` (the are eligible now)
Do not ignore school changes coming from GIAS when the school `Section41-approval` is now `"Approved"`
> CST-1051: update schools S41 approved from GIAS

- app/services/admin/npq_applications/csv_generator.rb
- spec/jobs/admin/npq_applications/export_job_spec.rb
The NPQ Application Exports allowed you to set the end date for exports. The export was wrongly ending at the start of that day rather than the end, entirely missing out a day of data.
Set the end date to midnight of the end_date.
> Fix bug that excluded data on final day of export

- app/validators/course_validator.rb
- spec/validators/course_validator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1811
- There are validation issues when attempting to change schedule for users with more than one identity with regards to the `CourseValidator`
- This handles cases where there may be more than one participant identity for a user
- none
> [CPDLP-1811] CourseValidator now uses user for profiles

- spec/jobs/admin/npq_applications/export_job_spec.rb
- spec/requests/admin/participants/change_cohort_spec.rb
When inserting records into the CSV, we are using `find_each` which adheres to the asc ID order. This means that the UIID of the first record could end up coming in later in the CSV.
This is causing the test to be flakey due to the order of the records. Ensure order is respected by sorting by the ID in the expected CSV.
- Ticket: n/a
- Sort expected records before inserting into the CSV by ascending ID.
example of failure
https://github.com/DFE-Digital/early-careers-framework/actions/runs/3144801621/jobs/5111482559#step:8:1528
Ran multiple times locally and hasn't failed yet
> Sort applications by id to ensure order matches CSV

- app/services/participants/change_schedule/ecf.rb
- app/services/participants/change_schedule/npq.rb
- spec/services/participants/change_schedule/ecf_spec.rb
- spec/services/participants/change_schedule/npq_spec.rb
If the wrong cohort is passed in on change schedule, make sure validation completes successfully rather than raising a 500 error due to the schedule not being found
https://sentry.io/organizations/dfe-teacher-services/issues/3491823308/?environment=sandbox&project=5748989&query=is%3Aunresolved
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1810?focusedCommentId=49783&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-49783
Return early in validation if schedule not present to avoid hitting a 500
> [CPDLP-1810] Return validation error if wrong cohort passed in

- app/services/npq/amend_participant_cohort.rb
- config/locales/en.yml
- spec/services/npq/amend_participant_cohort_spec.rb
NPQ applications might have been moved incorrectly to cohort 2022, add a service to amend that fixes that, with the correct validations in place.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1804
Add a service which could later be plugged into the FE to amend an NPQ participant's cohort
> [CPDLP-1804] Add service to amend an NPQ application cohort

- app/services/finance/ecf/statement_calculator.rb
- app/services/finance/npq/course_statement_calculator.rb
- db/migrate/20220929102011_add_monthly_service_fee_to_contracts.rb
- db/migrate/20220929104505_add_npq_monthly_service_fee.rb
- db/schema.rb
- spec/factories/call_off_contract.rb
- spec/factories/npq_contracts.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
- spec/services/finance/npq/course_statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1798
- Stakeholders wish to be able to specify ad-hoc monthly service fees that are not derived from other numbers such as recruitment targets
- On a contract one can now set `monthly_service_fee`
- If this is not set it uses the previous mechanism for calculating this value
- If set we use this figure instead when presenting thru statements
- This feature is available to both ECF and NPQ
- none
> [CPDLP-1798] Inject monthly service fee into contracts

- app/helpers/finance_helper.rb
- app/services/finance/ecf/statement_calculator.rb
- app/views/finance/ecf/statements/show.html.erb
- spec/helpers/finance_helper_spec.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
- spec/support/features/pages/finance/finance_payment_breakdown_report.rb
- spec/support/features/sections/uplifts_finance_panel.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1613
- Uplift fees are not considered adjustments
- Uplift fees has it's own row in the summary breakdown
- Uplift fees no longer in the adjustments table and now lives in it's own table
- none
> [CPDLP-1613] ECF statements: uplift fees in own separate table

- app/forms/schools/add_participant_form.rb
- app/views/schools/add_participants/cannot_add.html.erb
- spec/features/schools/participants/add_participants/unhappy_path_already_on_ecf_training_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- Ticket: CST-1063
The "cannot add" logic checks whether the existing participant is in the same school of the new participant.
The message shown changes based on whether the above condition is true or not.
> [CST-1063] Cannot add participant from different school message

- app/controllers/admin/participants/change_cohort_controller.rb
- app/models/participant_profile.rb
- app/services/induction/amend_participant_cohort.rb
- app/services/induction/amend_participants_cohort.rb
- app/views/admin/participants/_declarations_history.erb
- app/views/admin/participants/_induction_records.html.erb
- config/locales/en.yml
- spec/requests/admin/participants/change_cohort_spec.rb
- spec/services/induction/amend_participant_cohort_spec.rb
- spec/services/induction/amend_participants_cohort_spec.rb
Some participants can't be moved to another cohort when it should. 
Admin console displays error messages in this cases.
Ticket:  [1067](https://dfedigital.atlassian.net/browse/CST-1067)
- Refactor amend participant cohort feature to depend on participant_profile rather than one of their emails. 
That was causing some cases to be failing when the email provided is not the participant_profile's email.
- Display cohort if induction records in admin console
- Reorder some fields displayed in admin console.
> CST-1067: refactor AmendParticipantCohort

- app/services/feature_flag.rb
- config/routes.rb
Hide API V3 endpoints behind a feature flag
- Ticket: n/a
Add a new feature flag `v3_api` to allow development of API v3
Will add tests later when we have endpoints
> Add feature flag for API v3 endpoints

- Gemfile
- Gemfile.lock
- Ticket: n/a
- Remove `aasm` and related gem as does not appear to be used anywhere
- none
> remove aasm gem

- app/controllers/api/v3/finance/statements_controller.rb
- app/models/finance/statement.rb
- app/models/finance/statement/ecf.rb
- app/models/finance/statement/ecf/paid.rb
- app/models/finance/statement/npq.rb
- app/models/finance/statement/npq/paid.rb
- app/serializers/api/v3/finance/statement_serializer.rb
- app/services/api/v3/finance/statements/index.rb
- config/routes.rb
- spec/factories/finance/statements.rb
- spec/models/finance/statement/ecf/paid_spec.rb
- spec/models/finance/statement/npq/paid_spec.rb
- spec/models/finance/statement_spec.rb
- spec/requests/api/v3/statements_spec.rb
- spec/serializers/api/v3/finance/statement_serializer_spec.rb
- spec/services/api/v3/finance/statements/index_spec.rb
Add API V3 statements endpoint
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1692
- Add Statements serialiser
- Add `paid?` methods to subclasses to make it easier to calculate paid statements
- Add Statements query service to parse params and return correct statements
- Add API v3 statements route and controller
To test:
enable the feature flag: `FeatureFlag.activate("api_v3")`
GET the following endpoint: `/api/v3/statements`
To use different filters: `/api/v3/statements?filter[type]=npq&filter[cohort]=2021,2022`
> [CPDLP-1692] Add API V3 Statements endpoint

- app/controllers/admin/delivery_partners/users_controller.rb
- app/controllers/appropriate_bodies/base_controller.rb
- app/controllers/appropriate_bodies/participants_controller.rb
- app/controllers/delivery_partners/delivery_partners_controller.rb
- app/controllers/delivery_partners/participants_controller.rb
- app/forms/choose_role_form.rb
- app/forms/delivery_partners/choose_organisation_form.rb
- app/forms/delivery_partners/create_user_form.rb
- app/forms/delivery_partners/update_user_form.rb
- app/mailers/delivery_partner_profile_mailer.rb
- app/models/user.rb
- app/views/admin/delivery_partners/users/delete.html.erb
- app/views/admin/delivery_partners/users/edit.html.erb
- app/views/admin/delivery_partners/users/index.html.erb
- app/views/admin/delivery_partners/users/new.html.erb
- app/views/delivery_partners/delivery_partners/index.html.erb
- app/views/delivery_partners/participants/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/factories/delivery_partners.rb
- spec/factories/users.rb
- spec/features/delivery_partners/delivery_partners_spec.rb
- spec/features/delivery_partners/participants_spec.rb
- spec/forms/choose_role_form_spec.rb
- spec/forms/delivery_partners/choose_organisation_form_spec.rb
- spec/forms/delivery_partners/update_user_form_spec.rb
- spec/models/user_spec.rb
- spec/requests/delivery_partners/participants_spec.rb
- spec/serializers/delivery_partners/participants_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1580
* DP participants page updated to allow for multiple organisations and switching between them
* DP choose organisation page
* Login as `delivery-partner@example.com`
* If the user only has one DP partner role, it will redirect to the participants
* If more than one, will redirect to choose organisation page
> [CPDLP-1580] Access management - Switch between deliver partners

- spec/features/scenarios/changes_of_circumstance_scenario.rb
- spec/features/scenarios/onboarding_a_deferred_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_fip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_same_provider_spec.rb
- spec/support/features/steps/changes_of_circumstance_steps.rb
Scenarios started failing as we've passed the deadline date on one of the statements (30 September)
Although we are time travelling in the scenarios, we aren't time travelling when creating the statements, which means we are still attaching the declaration to the latest statement which keeps shifting as we go forward.
We fixed that by changing the statement name and pushed it forward.
However, we need to fix this permanently to avoid those failures again after we pass another deadline.
- Ticket: n/a
Create statements when time travelling, and change expected statement to the past, so it never changes again.
Also shift the timestamp we travel to by 2 months to avoid declarations being attached to two statements, and to adhere to the current test setup and expectations.
> Ensure we time travel when setting up test scenarios

- app/components/admin/participants/table.html.erb
- app/components/admin/participants/table_row.html.erb
- app/components/admin/participants/table_row.rb
- app/controllers/admin/participants_controller.rb
- app/models/induction_record.rb
- app/models/participant_identity.rb
- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
- app/models/teacher_profile.rb
- app/models/user.rb
- app/services/admin/participants/search.rb
- app/views/admin/participants/index.html.erb
- spec/cypress/integration/admin/ParticipantManagment.feature
- spec/models/induction_record_spec.rb
- spec/models/participant_identity_spec.rb
- spec/models/user_spec.rb
- spec/services/admin/participants/search_spec.rb
The search/index page wasn't eager loading the results causing a large number of queries. These have been optimised into a couple and some of the scope logic reworked. Participants can now be found by email address too.
- Add scopes for sorting induction records by create
- Eager load relations used in participants table
- Extend the search so it covers email addresses
> Improve the admin participant search

- app/helpers/admin_helper.rb
- app/views/admin/schools/show.html.erb
- spec/helpers/admin_helper_spec.rb
- spec/requests/admin/schools_spec.rb
This was created in direct collaboration with the support team. The following fields have been added to school overview:
* URN
* Address
* A direct link to the corresponding page on GIAS
> Improve the admin school overview

- app/components/admin/npq/participants/details.html.erb
- spec/components/admin/npq/participants/details_spec.rb
Small fix where the national insurance number was displayed instead of the date of birth.
> Fix listing of date of birth for NPQ participants

- app/services/api/v3/finance/statements/index.rb
- spec/services/api/v3/finance/statements/index_spec.rb
We only need to surface output statements to providers
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1692
Add `output` scope to statements endpoint query service
> [CPDLP-1692] Only surface output statements

- spec/requests/admin/participants/npq/change_email_spec.rb
- spec/requests/admin/participants/npq/change_full_name_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
Flakey specs: 
- `spec/requests/admin/participants/npq/change_full_name_spec.rb`: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3205886126/jobs/5238956665
- ` spec/requests/api/v2/ecf_participants_spec.rb`: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3203146889/jobs/5232896436
- Ticket: n/a
- Use explicit name to avoid failure in regex expectation in spec
- Explicitly set ECT profile user with mentor in spec
> Fix Change full name and ECF API flaky tests

- app/controllers/admin/schools_controller.rb
- app/views/admin/schools/index.html.erb
- spec/cypress/integration/admin/SchoolManagment.feature
- spec/requests/admin/schools_spec.rb
Allow admins to filter schools by postcode. This helps support agents find schools that share their name with lots of other schools
> Add postcode to filterable school fields

- app/views/admin/participants/_school.html.erb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1072)
In the transfer services we were missing setting/correcting the mentors `SchoolMentor` records which enable them to appear in the mentor selection form shown to SITs. This has been fixed previously but there were still instances of mentors at schools without a `SchoolMentor` record.  I have updated the data in prod to ensure all active mentors have a `SchoolMentor` record for their school.
This PR adds a list of schools the mentor is mentoring at to the schools tab in the admin UI to enable support to diagnose mentoring availability questions more easily.
Adds a list of "Mentoring at" schools to the School tab as links to those schools
> [CST-1072] Ensure school mentors are available at the right school

- app/controllers/admin/participants/change_induction_start_date_controller.rb
- app/forms/admin/participants/change_induction_start_date_form.rb
- app/policies/induction_record_policy.rb
- app/services/admin/participants/change_induction_start_date.rb
- app/views/admin/participants/_details.html.erb
- app/views/admin/participants/change_cohort/edit.html.erb
- app/views/admin/participants/change_induction_start_date/edit.html.erb
- app/views/admin/participants/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/forms/admin/participants/change_induction_start_date_form_spec.rb
- spec/requests/admin/participants/change_cohort_spec.rb
- spec/requests/admin/participants/change_induction_start_date_spec.rb
- spec/services/admin/participants/change_induction_start_date_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5e1dba26b5771b0ca44142ee&selectedIssue=CST-871
* Add a 'change' link to the details tab so the induction start date can be changed
* Add a form object to validate the change and a regular service object
* Create a form based on the designs in the ticket to update the induction start date
| Details tab | Change induction date form | Success |
| ----------- | -------------------------- | ------------------- |
| ![Screenshot from 2022-09-27 11-35-43](https://user-images.githubusercontent.com/128088/192559292-3a916f05-e191-48ac-9d9c-30ddceecbebc.png) |  ![image](https://user-images.githubusercontent.com/128088/192570720-37d14896-8b9e-41c8-8f8e-276683e86d08.png) | …
> Allow admins to change induction start date

- app/components/admin/schools/cohorts/cip_info.html.erb
- app/components/admin/schools/cohorts/cohort.html.erb
- app/components/admin/schools/cohorts/cohort.rb
- app/components/admin/schools/cohorts/fip_info.html.erb
- app/components/admin/schools/cohorts/other_info.html.erb
- app/controllers/admin/schools/cohorts/challenge_partnership_controller.rb
- app/controllers/admin/schools/cohorts_controller.rb
- app/views/admin/participants/_school.html.erb
- app/views/admin/schools/cohorts/challenge_partnership/confirm.html.erb
- app/views/admin/schools/cohorts/challenge_partnership/new.html.erb
- app/views/admin/schools/cohorts/index.html.erb
- config/routes.rb
- spec/components/admin/schools/cohorts/cip_info_spec.rb
- spec/components/admin/schools/cohorts/fip_info_spec.rb
- spec/components/admin/schools/cohorts/other_info_spec.rb
- spec/requests/admin/schools/cohorts/challenge_partnership_spec.rb
- Ticket: 
* make the existing partnership challenging functionality partner-centric
* display the partnership details on the form (so it's clear what we're challening)
* display all the partnerships for each cohort beneath the listing with a 'challenge' link
The partnership challenging controller appeared to be written in a way that assumes there's only one partnership per cohort per school. I don't think this is necessarily always the case (it certainly isn't in the seed data).
Now instead of grabbing the partnership based on the school and cohort, the partnership id is a URL param.
Because multiple partnerships might be available to edit I've added the relevant details to the top of the challenge form too.
| Parterships list | Challenge form | Confirmation screen | Notification |
| …
> Add partnership challenging to the admin pages

- app/models/participant_profile/ecf.rb
- spec/models/participant_profile/ecf_spec.rb
ECF Action participant endpoints such as defer/resume/withdraw, find the relevant induction record for a lead provider to serialise a response in the API: https://github.com/DFE-Digital/early-careers-framework/blob/7ab4cbc54985cbcdcb85e0736c1bd11bc56a71f5/app/controllers/concerns/api/v1/participant_actions.rb#L32
When we lookup those induction records we are currently only scoping them to the current cohort i.e. 2022. So if an action is attempted for participants with induction record in older cohorts they get an empty body in the API response as no induction record is returned
- Ticket: n/a
We should return induction records for all cohorts, and not just the current cohort for a lead provider.
> Fix relevant induction record lookup

- app/controllers/admin/participants/school_transfer_controller.rb
- app/forms/admin/school_transfer_form.rb
- app/models/induction_programme.rb
- app/services/induction/create_relationship.rb
- app/services/induction/transfer_and_continue_existing_programme.rb
- app/views/admin/participants/school_transfer/transfer_options.html.erb
- spec/forms/admin/school_transfer_form_spec.rb
- spec/services/induction/create_relationship_spec.rb
- spec/services/induction/transfer_and_continue_existing_programme_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1078)
Extra functionality for the admin school transfers when there is no school cohort at the destination school or the school has chosen "no ECTs" for the cohort.
In these cases the transfer will add a school cohort and set it up the same as the transferring in participants programme.
Also remove the transfer choice page when there is no choice available (no programmes at destination or only 1 that matches the participants current programme).
> [CST-1078] additional functionality for admin transfer

- app/services/finance/ecf/assurance_report/query.rb
- app/services/finance/npq/assurance_report/query.rb
- spec/services/finance/ecf/assurance_report/query_spec.rb
- spec/services/finance/npq/assurance_report/query_spec.rb
Some participant profiles are incorrectly attached to new participant identities where the user.id does not equate to the external identifier of the identity.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1860
User the `user_id` to make sure we always find the user
> [CPLD-1860] Amend Participant Identity lookup in assurance reports

- app/controllers/api/api_controller.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/npq.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/models/participant_profile/npq_spec.rb
This is an unblocker PR as we are refactoring multiple endpoints at the same time
- Ticket: n/a
- Add shared methods for both NPQ and ECF profiles to be used in action endpoints refactor
based off https://github.com/DFE-Digital/early-careers-framework/pull/2610
> Expose shared interface for Participant profiles

- app/forms/nominate_induction_tutor_form.rb
- app/forms/schools/add_participant_form.rb
- app/forms/schools/transferring_participant_form.rb
- app/views/nominations/nominate_induction_coordinator/email.html.erb
- app/views/schools/transfer_out/complete.html.erb
- app/views/schools/transferring_participants/cannot_find_their_details.html.erb
- app/views/schools/transferring_participants/check_answers.html.erb
- app/views/schools/transferring_participants/choose_mentor.html.erb
- app/views/schools/transferring_participants/complete.html.erb
- app/views/schools/transferring_participants/dob.html.erb
- app/views/schools/transferring_participants/email.html.erb
- app/views/schools/transferring_participants/teacher_start_date.html.erb
- app/views/schools/transferring_participants/trn.html.erb
- Ticket: 
Follows on from #2616. Didn't pick these up on the first sweep asI only looked in views.
I also removed a couple of overlapping apostrophe-adding methods, everything now uses the `#possessive_name` helper.
> Remove any remaining calls to #titleize names

- app/services/induction/change_partnership.rb
- app/services/partnerships/report.rb
- spec/services/induction/change_partnership_spec.rb
- spec/services/partnerships/report_spec.rb
- Ticket: [JIRA](https://dfedigital.atlassian.net/browse/CPDLP-1827)
Update `Induction::ChangePartnership` to call `Induction::SetCohortInductionProgramme` service when existing cohort programme is not a FIP.
No longer use `pending` for partnerships, reporting a partnership should immediately switch cohort default to FIP and migrate participants to the new FIP programme.
Remove call to queue `PartnershipActivationJob` which is outdated (we should remove the job code once deployed and queues empty)
> [CPDLP-1827] - Ensure partnership report sets cohort to FIP and migrates participants

- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- spec/requests/admin/schools/cohort_2020_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/identity/create_spec.rb
- spec/services/mentors/create_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CPDLP-1744) 
This change aims at preventing creation of duplicate profile whilst we resolve and soft delete the existing duplicate profiles
> [CPDLP-1744] - add guard clauses so that double profile can not be created

- app/views/admin/participants/_details.html.erb
The ParticipantProfile#induction_start_date is a column belonging to a piece of work yet to be finished. It will store the first starting date of an induction, but before it's used we need to backfill the existing profiles and surface the date in various places in the UI.
Until those things are done this 'Change' link is likely to cause confusion, so we'll temporarily hide it.
This change was requested by Nicola.
> Comment out 'change' link for induction start date in the admin console

- spec/serializers/api/v3/ecf/partnership_serializer_spec.rb
Noticed that a intermittently failing spec was due to a timing inconsistency where the wrong object `created_at` and `updated_at` were being compared in this spec.
> Fix flaky serializer spec

- bin/rspec_ci
- spec/docs/v3/ecf_delivery_partners_spec.rb
- spec/docs/v3/ecf_partnerships_spec.rb
- spec/docs/v3/npq_applications_spec.rb
- spec/docs/v3/npq_outcomes_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/docs/v3/participant_declarations_spec.rb
- spec/docs/v3/participants_ecf_spec.rb
- spec/docs/v3/statements_spec.rb
- spec/spec_helper.rb
V3 API tests are excluded in our CI runs, however locally they fail unless manually excluded
- Ticket: n/a
- Add filter to config
- Add this new filter to all specs to ignore
- Remove exclusion from rspec ci now its no longer needed
When we add endpoints we will start removing those filters one by one, whilst also setting the API feature flag to true
This is based off @leoapost work in https://github.com/DFE-Digital/early-careers-framework/pull/2640
> Add RSpec filter to avoid running API v3 specs

- spec/components/admin/npq/applications/analysis/table_row_spec.rb
- spec/factories/users.rb
- spec/requests/admin/participants/change_induction_start_date_spec.rb
When checking for the following in the page:
```
/What is #{ect_profile.user.full_name}.*/
```
Names such as: Elza O'Reilly will fail that regex because they are formatted differently on the page. 
- Ticket: n/a
Set the user name explicitly to avoid failures on random names.
example of failure: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3295940164/jobs/5435027414
> Use explicit name to avoid failure in regex expectation

- app/services/npq/build_application.rb
When we can't find a teacher_catchment_iso_country_code we log a message to Sentry with the country we can't find's name in it. Here the call to Sentry is the final thing in the method so when we can't find one, the return value of `Sentry#capture_message` (a `Sentry::ErrorEvent`) is set.
This causes an error when writing to the database as the string is longer than 3 characters.
> Stop writing Sentry object to country code field

- .github/workflows/destroy.yml
Review apps are not created for dependabot prs.
When a pr is merged or closed we attempt to destroy that review app. The actor performing the closing or merging of a PR is never going to be dependabot. This means the check fails, and we are attempting to destroy review apps when they don't exist.
Look for the label and skip if it is a dependency instead.
- Ticket: n/a
Check PR labels before destroying review app, and skip if it includes "dependencies"
Example of failures where check passed: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3297527233/jobs/5438449015
> Ignore pull requests with label "dependencies" when destroying a review app

- terraform/app/modules/paas/main.tf
- terraform/app/modules/paas/variables.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
- terraform/workspace-variables/dev.tfvars
- terraform/workspace-variables/review.tfvars
When deploying to Dev and Review envs, the deployment fails with health timeouts, which I assume is due to the long setup. We will be fixing our reseeding scripts however until that happens, increase our health timeout to 2 minutes to give the setup enough time to complete, and avoid having to rerun deploys.
- Ticket: n/a
- Add a new variables `health_check_timeout` and `paas_health_check_timeout`
- Set those variables to the default value of 60s (as it was hardcoded before for all web apps)
- Override this in dev and review setup to 120s
- 
Failure examples on dev and review:
https://github.com/DFE-Digital/early-careers-framework/actions/runs/3296708732/jobs/5436680363
https://github.com/DFE-Digital/early-careers-framework/actions/runs/3296239479/jobs/5435672041
> Double health check timeout

- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
Failing specs due to us selecting a date that passed (beginning of day today)
- Ticket: n/a
Time travel to a date before to avoid failures
> Add `travel_to` to specs where we are selecting the same date as today

- app/serializers/api/v3/delivery_partner_serializer.rb
- spec/docs/v3/ecf_delivery_partners_spec.rb
- spec/docs/v3/statements_spec.rb
- spec/serializers/api/v3/delivery_partner_serializer_spec.rb
- swagger/v3/component_schemas/DeliveryPartnerAttributes.yml
- swagger/v3/component_schemas/StatementAttributes.yml
We added endpoints for V3, enable schema tests for those
- Ticket: n/a
- Enable and fix statements and delivery partner tests
- Remove erroneous required name in schema
- Fix delivery partner serializer to return string for cohort start year
> Enable API V3 added specs

- app/services/npq/build_application.rb
- lib/tasks/one_offs.rake
- spec/services/npq/build_application_spec.rb
The default [error level is :error](https://docs.sentry.io/platforms/ruby/usage/set-level/), which triggers an alert. In this case we do want to know about the missing/wrong countries because it'll show a mismatch between our countries lists in the NPQ and ECF apps, but it's not important enough to be considered an error.
The originally selected value will still be saved in `teacher_catchment_country` making the problem rows easy to identify and fix later if needed.
> Reduce unfound country Sentry messages from `:error` to `:warning`

- app/components/admin/participants/identities.rb
- app/controllers/concerns/current_user.rb
- app/models/participant_identity.rb
- spec/components/admin/participants/identities_spec.rb
- spec/factories/participant_identity.rb
- spec/models/participant_identity_spec.rb
The ParticipantIdentity model has two scopes to retrieve the 
1. original identity which is the one created with the user 
2. transferred identities which can be either 
2.1. just more identities of the same user
2.2. transferred identities from other user records of the same participant, caused by the de-dupping process
The transferred identities returning two different things, confuses things and can lead to more issues. 
So, this is a follow up from my previous PR #2628 as an attempt to identify the non original identities correctly and display them in the participants admin profile for easier troubleshooting. 
ps. it is inspired by the [discussion](https://github.com/DFE-Digital/early-careers-framework/pull/2628#discussion_r1000412139) with Tony on how the origin of the identities can …
> Add methods in ParticipantIdentity to determine its origin

- app/services/exporters/manual_validation.rb
Manual validation exporter can fail if the validation data is `nil`.  This prevents it from generating an error.
> Fix manual validation exporter

- app/views/finance/ecf/duplicates/compare/_details.html.erb
- app/views/finance/ecf/duplicates/compare/_induction_record_summary_list.html.erb
- app/views/finance/ecf/duplicates/compare/_induction_records.html.erb
- app/views/finance/ecf/duplicates/compare/_participant_declaration_summary_list.html.erb
- app/views/finance/ecf/duplicates/show.html.erb
- db/migrate/20221026073938_update_ecf_duplicates_to_version_3.rb
- db/schema.rb
- db/views/ecf_duplicates_v03.sql
We were surfacing NPQ profiles in duplicates.
- Ticket: n/a
- Ignore none ECF profiles when calculating duplicates
- Show normal `govuk` date format instead of short as we want to see the year
- Account for missing identities when showing preferred email
> Ignore NPQ profiles in duplicate query

- app/views/lead_providers/report_schools/confirm/show.html.erb
> Table header elements should have visible text that describes the purpose of the row or column to both sighted users and screen reader users.
https://dequeuniversity.com/rules/axe/4.1/empty-table-header
This is currently blocking
#2656
> Fix Axe failure on having empty table headers

- spec/features/schools/participants/add_participants/add_ect_with_appropriate_body_spec.rb
- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- spec/features/schools/participants/transferring_participants/already_enrolled_at_school_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/active_cohort_speedbump_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/support/features/interaction_helper.rb
The `#fill_in_date` helper allows us to provide a bit more context in specs than individually calling `fill_in "{Date,Month,Year}:"` because:
* we need to reference the legend text, so it's more obvious by reading the spec _what_ we're filling in
* dates are easier to find by grepping if they're in a ISO 8601 style (eg. 2022-10-24) than they would be as separate numbers across three lines
- Add a fill_in_date helper for use in features
- Update date steps to use fill_in_date method
> Add helper to fill in date fields in one go

- spec/support/features/steps/changes_of_circumstance_steps.rb
When rendering the finance statements page we rely on this scope:
https://github.com/DFE-Digital/early-careers-framework/blob/develop/app/models/finance/statement.rb#L34
Which uses a Postgres `DATE(NOW())` timestamp. This supersedes time traveling in the specs and returns the latest statement according the time now.
We extract the cohort param from the latest statement, which meant we were defaulting to 2022. This means we didn't find our `November 2021` with that cohort which is why the scenarios fail
- Ticket: n/a
Use method stubs for the scope?
Rethink tomorrow
> Use method stubs to avoid relying on Postgres `Date(now())`

- app/controllers/admin/participants/validation_data_controller.rb
- spec/requests/admin/participants/change_validation_data_spec.rb
We allow admins to revalidate participants but if an errant TRN is present on the teacher profile we end up with a "manual check"/"different TRN" status.  This removes any existing TRN from the `TeacherProfile` __unless__ there are any NPQ profiles present (as they would've set the TRN).
Remove TRN from `TeacherProfile` prior to admin (re)validation
> Remove TRN prior to validation unless NPQ present

- app/controllers/schools/setup_school_cohort_controller.rb
The following errror [is reported by Sentry](https://sentry.io/organizations/dfe-teacher-services/issues/3698544696/?project=5748989) when trying to notify about fip programme changes:
```
undefined method `lead_provider' for nil:NilClass
```
It happens when no partnership is found on the default_induciton_programme. I think in these cases we should emit a warning that the partnership isn't present and not try to send the email
> Check prev partnership exists before traversing

- app/models/finance/ecf/deleted_duplicate.rb
- app/models/participant_profile.rb
- app/serializers/finance/ecf/duplicate_serializer.rb
- db/migrate/20221102132300_create_deleted_duplicates.rb
- db/schema.rb
- spec/serializers/finance/ecf/duplicate_serializer_spec.rb
To make sure we have a record of deleted duplicate participant profiles, add a new table which stores a serialised record of the deleted profile and any related records. Also a link to the primary participant profile.
- Ticket: n/a
- Add new table for deleted duplicates
- Add new serialiser for profiles to be deleted, including all relevant attributes of related models
- 
> Add new Deleted Duplicate table to store serialised profiles

- app/models/user.rb
- spec/models/user_spec.rb
Recently the sync between `User.email` and the original `ParticipantIdentity.email` was removed to facilitate easier changes to emails typically for CIP users when multiple identities are in play.  However this is causing issues when the `User` only has a single `ParticipantIdentity` and there is an expectation that they will be in sync.
Reintroduce the sync when there is only a single identity
> Allow sync of email when only 1 identity

- app/services/importers/ecf_manual_validation.rb
- spec/fixtures/files/example_ecf_manual_validation.csv
- spec/services/importers/ecf_manual_validation_spec.rb
ECF manual validation importer had issues with using `current_ecf_profile`, passing a wrong param name and not handling `nil` dates, so refactored to correct these.
> Fix manual validation importer

- db/analytics_migrate/20221103153412_add_cohort_id_to_analytics_ecf_induction.rb
- db/analytics_schema.rb
The `cohort_id` is useful to analysts and currently tricky to get at/deduce on the analytics side. Adding it will remove several steps from their workings.
This is part 1/2. In part two (#2705) we are populating the field we're adding here. It is important that **this PR is released before that oen is merged**, because it looks like the analytics migration needs to be manually run and we don't want to start trying to populate the field before it exists.
> Add `cohort_id` column to analytics inductions table

- app/controllers/api/v1/ecf_participants_controller.rb
- app/services/api/v1/ecf/participants_query.rb
- app/services/api/v3/ecf/participants_query.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
Getting ECF participants in V1 and V2 might not adhere to the new patterns we are using in V3.
- Ticket: [CPDLP-1841](https://dfedigital.atlassian.net/browse/CPDLP-1841)
- Ticket: [CPDLP-1842](https://dfedigital.atlassian.net/browse/CPDLP-1842)
Revisit GET ECF participants endpoint and restructure to match V3 patterns in the query service as well as serialisers etc
[API-v3-Reference](https://ecf-dev.london.cloudapps.digital/api-reference/reference-v3.html#api-v3-delivery-partners-get)
[API v3 changes](https://docs.google.com/document/d/1AfOoSCCZKIdvFL6sijbi7vmsfZNu7RLHejdAWEUTmqo)
> [CPDLP-1841] Refactor GET ECF participants endpoint

- Gemfile
- lib/tasks/compare/ecf_users_and_induction_records.rake
Also make it `require: false` and explicitly require it in the comparison script as that's the only place it'll be used for the time being.
> Move json-diff gem out of development/test group

- app/controllers/api/v1/users_controller.rb
- app/services/api/v1/users_query.rb
- spec/requests/api/v1/users_spec.rb
- spec/services/api/v1/users_query_spec.rb
- spec/services/change_schedule_spec.rb
- spec/services/defer_participant_spec.rb
- spec/services/resume_participants_spec.rb
Fix inconsistent email usage detection in users API
- Ticket: [CPDLP-1866](https://dfedigital.atlassian.net/browse/CPDLP-1866)
There is a disconnect between the user lookup and user creation API endpoints. When attempting to sync a user from NPQ to the CPD database an “Email already in use” error occurred during user creation after a user lookup via that email returned no user. 
This is happening because GET /api/v1/users (Api::V1::UsersController#index) is using .where(email:) to find the relevant users instead of looking up via Identity. This is causing issues when a user is looked up via an email that isn’t in the direct email field on the User record but is attached to it elsewhere.
> [CPDLP-1866] Fix inconsistent email usage detection in users API

- Dockerfile
- Dockerfile.dev
We currently have to include the full path to run /usr/local/bin/bundle exec when sshing into the container
- Ticket: n/a
> Export path in Dockerfile to avoid having to type full path

- spec/services/change_schedule_spec.rb
Explicitly set participant profile schedule to avoid validation failures if they are the same with the new schedule
- Ticket:
> Fix flakey change schedule spec

- app/mailers/school_mailer.rb
- app/models/partnership.rb
- spec/models/partnership_spec.rb
Currently when sending a fip_provider_has_withdrawn_a_participant email we try to access the partnership's delivery partner. This is an optional value so not all partnerships are guaranteed to have one.
Currently it fails when one is missing, here I'm proposing that we instead display a string of text that says 'No delivery partner' instead.
> Show 'No delivery partner' in email when missing

- app/forms/schools/add_participant_form.rb
- spec/forms/schools/add_participant_form_spec.rb
The validation for adding a participant prevented having a `start_date` more than 1 year ago. This should allow dates back to 1st September 2021.
Change validation to permit start dates from 1/9/2021
> [Bug-fix] Allow participant start date back to 1st Sept 2021

- spec/services/npq/application/accept_spec.rb
With the `with_default_schedules` we create all necessary schedules. When creating the extra schedule the test is flakey as there are two similar default schedules and we can return either one, which fails on equality expectation
- Ticket: n/a
Remove creation of default as its done here: https://github.com/DFE-Digital/early-careers-framework/blob/develop/spec/support/with_default_schedules.rb
example failure: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3419197516/jobs/5692417259
> Remove unnecessary creation of NPQ default schedule

- app/services/analytics/ecf_induction_service.rb
- spec/services/analytics/ecf_induction_service_spec.rb
This is part 2/2. In part one (#2704) we added a new field to the `Analytics::ECFInductions` table. This change updates the job which populates it.
The reason we're splitting this over two parts is that I can't see any automatic running of the `db:migrate:analytics` task. We don't want to start trying to populate the table before the migrations have run.
> Populate `cohort_id` column in analytics inductions table

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
This follows on from f57fdc6e422d9 which didn't entirely solve the problem. Sometimes there is no partnership which means the second step, setting the `partnership.lead_provider.name` also fails.
I also fixed the spec, the expectations were wrapped in the `let` block meaning they were never run.
> Make the withdrawal email more robust when there's no partnership

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
This is a bit of investigation in to why the babel/preset-env Dependabot PR isn't building.
To make this build succeed I had to explicitly depend on `@babel/plugin-proposal-object-rest-spread`. Without it (even when it's an indirect dependency) the build wouldn't pass.
Fixes #2729, #2719
> Update babel, shakapacker

- lib/tasks/compare/ecf_users_and_induction_records.rake
The ECF User query and the IR Query use different UUIDs for the id of the records. It is chance that ids match
This now uses a map of user_id to external_identifier to find matched records which should mean we see actual differences.
> Attempt at finding correct record in both responses

- app/serializers/api/v1/ecf_induction_record_serializer.rb
- lib/tasks/compare/ecf_users_and_induction_records.rake
Small change to ensure we return the same id in the API as Support for ECTs uses that to find the record for a user and if we did not then some people would get emailed another invite but some would not get one at all.
> Support ECT user endpoint reports

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
This upgrades `govuk-frontend` to [version 4.4.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.4.0).
We need to update the components and form builder libraries in sync because there are some markup changes to the [error summary component](https://design-system.service.gov.uk/components/error-summary/).
Fixes #2750, #2742, #2751
We still have a few hardcoded error summaries sprinkled throughout the templates. I haven't amended them as we're not using the pattern correctly anyway (it's essentially used like a red [notification banner](https://design-system.service.gov.uk/components/notification-banner/) instead of a error summary). I'll add a separate ticket for them to be removed.
> Upgrade to `govuk-frontend` 4.4.0

- app/serializers/api/v1/ecf_induction_record_serializer.rb
- app/services/api/v1/ecf/induction_records_query.rb
- lib/tasks/compare/ecf_users_and_induction_records.rake
- spec/services/api/v1/ecf/induction_records_query_spec.rb
Changes a few selection rules:
- group by clause - so it is participant_profiles not preferred_identities
- ordering - as current API does not filter out leaving and withdrawn
- fallback to participant_profile to try and get core_induction_programme name if it is not copied to the induction_record
> Minor changes to Support ECTs User Query by Induction Record

- app/controllers/admin/participants/validation_data_controller.rb
Currently we auto-validate a participant when any of their manual validation data is changed. Once validated it's _fixed_ can no longer be amended by support staff.
> ...we've noticed when trying to manually validate participants on the service as soon as you update the TRN it automatically validates their record before you update their NIN. So we now have a few ECT/Mentors with the correct DOB/TRN but someone else's NINO
This is usually fine but we occasionally have a problem where two fields need to be amended. After the first one is changed the autovalidation runs and the second one can no longer be.
To prevent this from happening this change removes the auto-validation. Now agents will need to click the 'Validate details' button to trigger it. This way they can be sure all data is …
> Stop autovalidation on manual validation details change

- app/services/finance/ecf/assurance_report/query.rb
- app/services/finance/npq/assurance_report/query.rb
- spec/requests/finance/ecf/assurance_reports_spec.rb
- spec/requests/finance/npq/assurance_reports_spec.rb
The counts of declarations in particular states in the statement csv extracts may not match the statement on the service due to a couple of bugs. First, the csv extract may duplicate a declaration where the participant’s training_status has changed since the declaration was submitted (see Capita November 2022, cohort 2, ECF statement). Second, the query extract may not count a declaration as paid where it has been clawed_back, as the query pulls the latest state for a declaration, rather than state via statement_line_items (See Ambition October 2022, Cohort 2021, ECF statement).
- Ticket: [CPDLP-1900](https://dfedigital.atlassian.net/browse/CPDLP-1900)
Fix csv extract query to account for the two bugs reported above (line items and duplicates)
> [CPDLP-1900] Fix csv extract query to account for two bugs (line items and duplicates)

- app/components/finance/npq/payment_overviews/course.html.erb
- app/views/finance/ecf/statements/show.html.erb
- config/locales/en.yml
- Ticket:  https://dfedigital.atlassian.net/browse/CPDLP-1703
* Quick fix for NPQ+ECF finance statement page
* "Trainee" replaced with "Participant"
* See NPQ finance statement
* See ECF finance statement
> [CPDLP-1703] Financial Statements - Replace word 'trainee' with 'participant'

- spec/features/finance/npq/course_payment_breakdown_spec.rb
We are getting flakey tests on `spec/features/finance/npq/course_payment_breakdown_spec.rb:77` where the statement cannot be found when attempting to create a declaration
- Ticket: n/a
When attempting to find the `next_output_fee_statement` for a provider, we are attempting to get the statement where the `deadline_date` is more than or equal to the current date. This current date is being set to the first milestone on the
schedule in the test. It seems picking the first one does not respect the start date order, explicitly set the order to the first date to avoid flakey failures where the statement cannot be found.
Failure example: https://github.com/DFE-Digital/early-careers-framework/actions/runs/3559650405/jobs/5979146937
> Fix Course payment breakdown flakey test

- app/components/admin/npq/participants/details.html.erb
- app/components/admin/npq/participants/details.rb
- app/views/admin/participants/show.html.erb
- spec/components/admin/npq/participants/details_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-717
The first iteration of the NPQ details component accepted the profile object and traversed along its relationships to get the school, npq_application and user.
This made testing:
* tricky as more complex setup is needed
* slower as objects need to be persisted by the factory
This refactor changes the component's behaviour so we need to pass in the school, npq_application and user separately, allowing us to simplify the component and access values via a single level of delegation.
The `#last_updated` method wsa also tweaked to show the most recent `#updated_at` from either the participant profile or the user record.
> Refactor NPQ details component, fix `#last_updated`

- app/serializers/api/v1/ecf_induction_record_serializer.rb
- app/serializers/api/v1/ecf_user_serializer.rb
- app/services/api/v1/ecf/induction_records_query.rb
- spec/serializers/api/v1/ecf_induction_record_serializer_spec.rb
- spec/serializers/api/v1/ecf_user_serializer_spec.rb
- spec/serializers/api/v1/ecf_user_vs_induction_record_serializer_spec.rb
- spec/services/api/v1/ecf/induction_records_query_spec.rb
- spec/services/api/v1/ecf/users_query_spec.rb
- spec/support/with_support_for_ect_examples.rb
Does
------
- add shared examples file to add user record scenarios that have caused issues in migration to IRs
- add tests that check both the queries and the serialisers for consistency for the provided scenarios
- amend the user serialiser to remove flip-flopping on user type in ECT/Mentor scenario - chooses oldest profile for consistency
- build in fallbacks within IR serialiser for badly formed records
- add comments and tests to prove that it is not possible to use `InductionRecord.current` or `InductionRecord.latest` to identify correct records
- use SQL window query to order and group InductionRecords by user id and select the single relevant record to work with for performance
Does not
----------
- add support for more than one email address per user in Support ECTs - requires …
> scenarios tests for comparing support ECTs query and serialiser

- analytics_queries/Makefile
- analytics_queries/induction_tutors.sql
- analytics_queries/partnerships.sql
- analytics_queries/schools.sql
Written under Nathan's supervision! 😅
Main changes:
* we split up the complicated schools query by removing  the induction tutor specific bits
* added a cohort identifier to the partnerships table
* made the schools query combine data from the 2021/2022 cohorts and display them side-by-side
These scripts aren't used by the app in any way, they power an ad hoc export that's used for reporting purposes.
> Rejig the analytics queries for multiple cohorts

- app/models/npq_application.rb
- app/services/npq/funding_eligibility.rb
- spec/factories/services/npq/npq_application.rb
- spec/services/npq/funding_eligibility_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-723
api/v1/npq-funding/:id wil now return previously_received_targeted_funding_support in its response. This will be true if the user has any accepted applications where targeted_delivery_funding_eligibility is true
> [CPDNPQ-723] Expand NPQ Funding API call to include targeted funding

- app/components/participant_status_tag_component.rb
- app/models/ecf_participant_eligibility.rb
- app/services/participant_profile_status.rb
- app/services/participants/determine_eligibility_status.rb
- app/services/store_participant_eligibility.rb
- spec/components/appropriate_bodies/participants/table_row_spec.rb
- spec/components/delivery_partners/participants/table_row_spec.rb
- spec/components/participant_status_tag_component_spec.rb
- spec/components/schools/participants/status_spec.rb
- spec/factories/ecf_participant_eligibility.rb
- spec/factories/participant_profiles.rb
- spec/forms/participants/participant_validation_form_spec.rb
- spec/jobs/check_participants_induction_job_spec.rb
- spec/models/ecf_participant_eligibility_spec.rb
- spec/services/coc_set_participant_categories_spec.rb
- spec/services/manually_update_participant_eligibility_spec.rb
- spec/services/participants/determine_eligibility_status_spec.rb
- spec/services/set_participant_categories_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1151)
Refactor the `determine_status` method of `ECFParticipantEligibility` into a service object.
- Service object to determine eligibility status
- Remove model callback that determined status
- Add presence validations for `status` and `reason`
- Sanitise the factory with traits for the various validation states and reason combos
- Fix code that checked for invalid combinations of status and reason
- Fix specs.
> [CST-1151] - Move determine eligibility status into a service object

- app/controllers/api/v1/participant_outcomes_controller.rb
- app/controllers/api/v2/participant_outcomes_controller.rb
- app/serializers/api/v1/participant_outcome_serializer.rb
- app/services/api/participant_outcomes/index.rb
- app/services/api/v1/participant_outcomes_query.rb
- config/routes.rb
- spec/docs/v1/participant_outcomes_spec.rb
- spec/docs/v2/participant_outcomes_spec.rb
- spec/factories/participant_outcome_npq.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/participant_outcome_spec.rb
- spec/requests/api/v2/participant_outcome_spec.rb
- spec/serializers/api/v1/participant_outcome_serializer_spec.rb
- spec/services/api/participant_outcomes/index_spec.rb
- spec/services/api/v1/participant_outcomes_query_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NPQOutcome.yml
- swagger/v1/component_schemas/NPQOutcomeAttributes.yml
- swagger/v1/component_schemas/NPQOutcomesResponse.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/NPQOutcome.yml
- swagger/v2/component_schemas/NPQOutcomeAttributes.yml
- swagger/v2/component_schemas/NPQOutcomesResponse.yml
- Ticket: [CPDLP-1899](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1899)
- Introduce endpoint at `api/v1/participants/npq/outcomes` to return all outcomes - across all `ParticipantDeclaration`
for the authenticated provider.
- includes pagination
- Add the same endpoints to `/api/v2`
> Add API endpoint to View all NPQ participant outcomes per provider

- app/controllers/schools/participants_controller.rb
- app/models/induction_record.rb
- app/views/schools/participants/show.html.erb
Shows the oldest start_date for the participant representing the date that the induction training history began.
Adds an `oldest` scope for induction records which is the opposite of `latest`
> Correct school UI induction start date

- .github/workflows/deploy_to_dev.yml
- .github/workflows/deploy_to_production.yml
- .github/workflows/deploy_to_sandbox.yml
- .github/workflows/deploy_to_staging.yml
- .github/workflows/destroy.yml
- .github/workflows/force_destroy.yml
- .github/workflows/review.yml
- terraform/app/modules/statuscake/main.tf
- terraform/app/modules/statuscake/providers.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
- terraform/app/versions.tf
Deploys have started failing as we are using a deprecated API version of statuscake
- Update statuscake version in terraform
- Use API token instead of API key and username
- update statuscake required resource variables
> Update Statuscake version to 2.0.5

- db/migrate/20221201161925_set_appropriate_body_on_induction_records.rb
Remove code for now as it's breaking the migration in production, and will recreate to run as a one off task
> Remove data migration data

- lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake
We've had a few instances where they've occurred and nobody's noticed.
> Ensure concurrent migration errors are logged

- app/controllers/api/v1/participant_outcomes_controller.rb
- app/controllers/api/v1/provider_outcomes_controller.rb
- app/controllers/api/v2/provider_outcomes_controller.rb
- app/services/api/v1/participant_outcomes_query.rb
- config/routes.rb
- spec/docs/v1/participant_outcomes_spec.rb
- spec/docs/v2/participant_outcomes_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/participant_outcome_spec.rb
- spec/requests/api/v1/provider_outcomes_spec.rb
- spec/requests/api/v2/participant_outcome_spec.rb
- spec/requests/api/v2/provider_outcomes_spec.rb
- spec/services/api/v1/participant_outcomes_query_spec.rb
- swagger/v1/api_spec.json
- swagger/v2/api_spec.json
Re-opening as a new PR because the review app would not deploy against the old one - take 2.
A provider can view all a single  participant’s NPQ outcomes if they GET  /api/v3/participants/npq/{participant_id}/outcomes
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1685
- Allow `participant_external_id` to be filtered in `Api::V1::ParticipantOutcomesQuery`
- Add endpoint at `/api/v1/participants/npq/[participant_external_identifier]/outcomes`
> Single participant outcomes endpoint

- app/services/record_declaration.rb
- spec/services/record_declaration_spec.rb
If the participant external ID does not match a user with the same ID we are failing to create record declarations as it fails the validation for creating a declaration attempt which requires a user to exist.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1936
Do not depend on the user having the same ID as the external ID, look up the user and check they exist before attempting to create the declaration attempt to avoid unnecessary failures.
> [CPDLP-1936] Check that user exists before creating declaration attempt

- app/validators/participant_not_withdrawn_validator.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- spec/validators/participant_not_withdrawn_validator_spec.rb
A participant can be reinstated after being withdrawn. However the validation does not take that into account and finds any withdrawn participant state for a profile and raises a validation error.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1937
Change the validation to look for the most recent participant state scoped to provider, and then check if it has been withdrawn and the declaration is after the profile has been withdrawn.
Also add tests, we like tests.
Open to suggestions for a nicer implementation as always
> [CPDLP-1937] Amend Participant not withdrawn validator

- app/controllers/finance/base_controller.rb
When taking actions from the finance user admin dashboard (ie: changing participant training status).. we currently don't set the whodunnit ID on the papertrail versions table. Ideally we need to track who's done the changes for debug purposes.
- Ticket: [CPDLP-1909](https://dfedigital.atlassian.net/browse/CPDLP-1909)
Set paper_trail whodunnit from the finance base controller
> [CPDLP-1909] Set paper_trail whodunnit on the finance base controller

- analytics_queries/declarations.sql
A request from David, it would be helpful to see the delivery partner alongside declarations.
> Add delivery partner to declarations analytics

- .github/workflows/lint.yml
When setting up the app from fresh we get this error because we try and write to the mail.log file without the log directory existing.
```
No such file or directory @ rb_sysopen - log/mail.log
```
The log directory being present will stop it from tripping people up in the future.
> Add a .keep file to logs directory

- app/models/cohort.rb
- app/models/participant_profile/npq.rb
- app/policies/participant_profile/ecf_policy.rb
- app/serializers/finance/ecf/duplicate_serializer.rb
- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- config/locales/en.yml
- config/locales/schools/participants.yml
- db/migrate/20221212162506_remove_start_term_from_participant_profiles.rb
- db/schema.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/policies/participant_profile/ecf_policy_spec.rb
First PR of several as part of this big [ticket](https://dfedigital.atlassian.net/browse/CST-1184).
- Remove legacy field `start_term` from ParticipantProfile.
> CST-1184: remove :start_term field from ParticipantProfile

- app/controllers/api/v1/participant_declarations_controller.rb
- app/models/participant_declaration.rb
- app/models/participant_declaration/ecf.rb
- app/models/participant_declaration/npq.rb
- app/models/participant_outcome/npq.rb
- app/serializers/api/v1/participant_declaration_serializer.rb
- app/serializers/api/v2/participant_declaration_serializer.rb
- app/serializers/finance/ecf/assurance_report/csv_serializer.rb
- app/serializers/finance/npq/assurance_report/csv_serializer.rb
- app/services/feature_flag.rb
- app/services/importers/seed_statements.rb
- app/services/record_declaration.rb
- config/application.rb
- config/locales/en.yml
- spec/factories/participant_declaration.rb
- spec/features/finance/banding_tracker_spec.rb
- spec/models/participant_outcome/npq_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/serializers/api/v1/participant_declaration_serializer_spec.rb
- spec/serializers/api/v2/participant_declaration_serializer_spec.rb
- spec/services/record_declaration_spec.rb
- spec/spec_helper.rb
- swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v2/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v3/component_schemas/NPQParticipantDeclarationCompletedAttributesRequest.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1898
- Depends on PR: https://github.com/DFE-Digital/early-careers-framework/pull/2809
* Added feature flag `participant_outcomes_feature`
* Updated POST `/api/v1/participant-declarations` to include `has_passed`
* Updated POST `/api/v2/participant-declarations` to include `has_passed`
* `ParticipantOutcome::NPQ` is created when `has_passed` is true
* Updated API doc
* Enable feature
* Add `completed` declaration with `has_passed` set to `true`
[CPDLP-1898]: https://dfedigital.atlassian.net/browse/CPDLP-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-1898] amend existing api post declarations endpoint to support outcomes

- app/services/importers/seed_schedule.rb
Deployment to dev has failed because we need to require "csv" where needed. Add it to seed file
- Ticket: n/a
Maybe we should move the requirement higher up so we don't need to worry about it anymore
> Require CSV for db seeding to complete successfully

- app/services/npq/create_participant_outcome.rb
- app/services/npq/void_participant_outcome.rb
- app/services/record_declaration.rb
- app/services/void_participant_declaration.rb
- config/locales/en.yml
- spec/services/npq/void_participant_outcome_spec.rb
- spec/services/void_participant_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1934
* Updated void participant declaration endpoint service to create void participant outcome
* Created `NPQ::VoidParticipantOutcome` service to action void outcome creation.
> [CPDLP-1934] Void an outcome when a provider voids a completion declaration which has an outcome

- app/models/finance/schedule/npq_ehco.rb
- app/models/npq_course.rb
- app/services/finance/npq/course_statement_calculator.rb
- app/services/importers/npq_contracts.rb
- spec/models/finance/schedule/npq_ehco_spec.rb
- spec/models/npq_course_spec.rb
- spec/services/importers/npq_contracts_spec.rb
- spec/support/with_default_schedules.rb
NPQ EHCO schedules currently differ in cohorts:
- Cohort 2021: we had only one schedule: `npq-ehco-june` which all NPQ applications with the EHCO course were set to.
- Cohort 2022: we can have multiple schedules: [`npq-ehco-november`, `npq-ehco-december`, `npq-ehco-march`, `npq-ehco-june`]. 
NPQ applications are set the schedule relevant to the date range when an application is to be created. 
Since we need to support both 2021 and 2022 cohorts, we need to maintain the previous logic and support setting the new schedules. Also since we are still receiving applications for 2021 NPQ EHCO course, and have not started receiving EHCO applications for 2022.
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1924
- Maintain previous logic schedule for 2021 cohort
- Add new date range logic …
> CPDLP-1924 Change default cohort and schedule selection on NPQ EHCO applications

- db/new_seeds/base/add_schools_and_local_authorities.rb
The naming was used in the legacy seeds to make schools with participants easier to find in the dev environment.
```
early_careers_framework_development=# select name from schools where name like 'ZZ%' order by name;
┌──────────────────┐
│       name       │
╞══════════════════╡
│ ZZ Test School 1 │
│ ZZ Test School 2 │
│ ZZ Test School 3 │
│ ZZ Test School 4 │
│ ZZ Test School 5 │
│ ZZ Test School 6 │
│ ZZ Test School 7 │
│ ZZ Test School 8 │
└──────────────────┘
```
> Add some schools prefixed with 'ZZ' to seed

- db/new_seeds/base/add_npq_courses.rb
- db/new_seeds/run.rb
- db/new_seeds/scenarios/npq.rb
- spec/factories/seeds/npq_course_factory.rb
We need NPQ courses when integrating with the NPQ registration application to create new applications and sync users successfully. We also need to add NPQ courses to NPQ applications when setting up scenarios and declarations as well.
- Ticket: n/a
- Add new seeds to set up the previous ids and NPQ courses that sync up with the NPQ registration application in dec
- Add an identifier to the NPQ course factory as that's required for declarations and validity across the app
- Add an option to pass in an NPQ course when creating NPQ applications and declarations
Does this follow the new seed format?
> Add NPQ Course seeds

- app/services/admin/participants/search.rb
- app/views/admin/participants/index.html.erb
- spec/cypress/integration/admin/ParticipantManagment.feature
- spec/services/admin/participants/search_spec.rb
Sometimes we have a participant's profile ID and need to find their record. The search didn't support doing this so admins had to make a round trip to the participant drill down (finance) to get the other details and then back to the admin console.
> Support participant profile id in admin search

- terraform/workspace-variables/dev.tfvars
Resetting the data on dev causes issues with our NPQ registration app, as we lose synced user ids which prevents users from creating NPQ applications to existing users. It also removes important test data that might have been accumulated from previous testing done by the team. 
- Ticket: n/a
- Stop resetting and reseeding DB on dev on each deploy
- Stop flushing Redis on dev on each deploy
Does this break anything else?
> Remove database and Redis reset on Dev environment

- app/services/record_declaration.rb
- config/locales/en.yml
- spec/services/record_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1965
* Added validation for declarations endpoint to validate `has_passed` when unsupported values are provided.
> [CPDLP-1965] Add validation to has_passed field for npq completed declarations

- docs/source/_npq_usage_participant_actions.html.erb
- docs/source/release-notes.html.erb
View npq outcomes endpoint actions in the release notes is wrong. It should be "GET" instead of "POST".
- Ticket: [CPDLP-1945](https://dfedigital.atlassian.net/browse/CPDLP-1945)
Small fix on npq outcomes endpoint actions in the release notes.
https://ecf-sandbox.london.cloudapps.digital/api-reference/release-notes.html#16-1-2023
[CPDLP-1945]: https://dfedigital.atlassian.net/browse/CPDLP-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-1945] Fix npq outcomes endpoint actions in the release notes

- app/components/schools/participants/coc_status_table.html.erb
- app/components/schools/participants/coc_status_table_row.html.erb
- app/components/schools/participants/status_table.html.erb
- app/components/schools/participants/status_table_row.html.erb
- app/views/schools/participants/_ects.html.erb
- app/views/schools/participants/_mentors.html.erb
- spec/features/schools/participant_dashboard/manage_fip_partnered_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-1055)
- Add Manage link to each participant row in the participant lists of the SIT dashboard as an alternative way for the user to get and manage a user details 
Before
After
> CST-1055: add Manage link to participants SIT view

- app/forms/schools/add_participant_form.rb
We see the odd `undefined method 'call' for nil:NilClass error` in production where there's a participant_type of neither `:ect` or `mentor`.
Looking at the code it appears participant_type can also be `:self` but the error sent to sentry doesn't give us a clue what's going on or what's being looked for (:self, nil, something else?)
Instead, we can improve the error message reported to Sentry by using `#fetch` instead of `:[]`
> Use fetch when selecting a creator

- app/services/data_stage/process_school_changes.rb
- app/services/rectify_participant_school.rb
- spec/services/rectify_participant_school_spec.rb
When a school gets closed their participants are moved to its successor but the mentor pools are left unchanged.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-1207)
Rectify the mentor pools of the school and its successor so the entries are moved from one to the other.
> CST-1207: rectify mentor pools when a participant is rectified

- .github/workflows/deploy_to_dev.yml
- .github/workflows/review.yml
Builds were failing with the error:
> OCI index found, but Accept header does not support OCI indexes
The suggested fix is to temporarily disable provenance until better
support for OCI indexes arrives.
https://github.com/docker/buildx/issues/1533
> Set provenance to false on docker/build-push-action

- app/services/api/v1/ecf/participants_query.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1913
This endpoint is currently timing out in production for certain providers. One possible way to speed it up is by reducing the amount of columns returned to only the necessary ones.
Restrict the fields being returned by the query underlying the `/api/v1/participants/ecf` endpoint.
Before we merge this, it would be best to test it if possible to see if it has the expected effect of speeding up the endpoint when dealing with a prod-like data load.
This can be done locally, if we can get a prod-like database running with a similar amount of data, or it can be done on a prod-like env.
It's lacking a test, partly because I want to try it out first to see if it improves performance before I invest further, but also because testing for …
> [CPDLP-1913] Restrict participants endpoint fields

- db/new_seeds/scenarios/participants/mentors/mentoring_multiple_ects_with_same_provider.rb
- spec/factories/seeds/ecf_participant_validation_data_factory.rb
- spec/seeds/seed_factories/ecf_participant_validation_data_factory_spec.rb
We're taking an extra step here and making the seeded validation data closely resemble the user by adding an initial to their name via the transient user attribute.
> Add some validation data to the seeds

- app/helpers/admin_helper.rb
- spec/helpers/admin_helper_spec.rb
This is closer to the original design while keeping the distinct section name available for screen reader users.
| Header | HTML |
|------|-------|
|  ![image](https://user-images.githubusercontent.com/128088/212878168-9ea3aade-9ec2-467f-9c19-d0165e5edc83.png) |  ![image](https://user-images.githubusercontent.com/128088/212878351-0e3ca2ff-c914-40db-a383-cd334704f8f9.png) |
> Switch around the header and hide the section

- spec/features/finance/banding_tracker_spec.rb
`rspec ./spec/features/finance/banding_tracker_spec.rb:72` is failing.
``` 
1) Banding tracker displays the distribution of declaration by band, retention type and declaration state
Failure/Error: raise ArgumentError, service.errors.full_messages unless service.valid?
ArgumentError:
["Declaration date The property '#/declaration_date' can not declare a future date", "Declaration date The property '#/declaration_date' can not be after milestone end"]
```
Fix flaky test setting up test data correctly.
> Fix banding tracker flaky test

- app/services/record_declaration.rb
- app/validators/declaration_date_validator.rb
- config/locales/en.yml
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- spec/validators/declaration_date_validator_spec.rb
The API expects year-month-day, whereas TDT have swapped month and day.. so the API sent a response back to the lead provider: `Declaration date can't be blank` when lead provider posted for example `declaration_date`: `"2023-19-01T10:00:00Z"`.. which is a invalid year-month-day date.
- Ticket: [CPDLP-1994](https://dfedigital.atlassian.net/browse/CPDLP-1994)
Improve declaration date format validation and error message when an invalid date is posted to the service.
[CPDLP-1994]: https://dfedigital.atlassian.net/browse/CPDLP-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-1994] Validate declaration date format when creating a participant declaration via the api

- app/services/record_declaration.rb
- spec/services/record_declaration_spec.rb
We are not allowing ASO/EHCO completed declarations through if they've not defined the `has_passed` param
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2003
Allow those declarations through as those courses don't require outcomes
> [CPDLP-2003] Allow ASO/EHCO completed declarations without `has_passed` param

- .gitignore
[gitmailmap](https://git-scm.com/docs/gitmailmap) lets you locally override the names of people who committed to a project. I find it easier to work with names than a combination of name and GitHub handles, so adding this to the `.gitignore`.
> Ignore the .mailmap file

- analytics_queries/participants.sql
- app/components/appropriate_bodies/participants/table_row.rb
- app/components/delivery_partners/participants/table_row.rb
- app/controllers/appropriate_bodies/participants_controller.rb
- app/controllers/delivery_partners/participants_controller.rb
- app/models/participant_profile/ecf.rb
- app/serializers/appropriate_bodies/induction_records_serializer.rb
- app/serializers/delivery_partners/participants_serializer.rb
- app/services/analytics/ecf_validation_service.rb
- app/services/appropriate_bodies/participants_filter.rb
- app/services/delivery_partners/participants_filter.rb
- app/services/participant_profile_status.rb
- spec/components/appropriate_bodies/participants/table_row_spec.rb
- spec/components/delivery_partners/participants/table_row_spec.rb
- spec/features/appropriate_bodies/participants_spec.rb
- spec/features/delivery_partners/participants_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/services/participant_profile_status_spec.rb
There's a participant that has transferred where the API shows the correct value for training_status but the check data service shows something wrong.
This is the participant in question: 55485a55-c6ec-49c5-b9b6-ccb68d05cea0 https://manage-training-for-early-career-teachers.education.gov.uk/admin/participants/b8fdaffa-da1c-418b-9ad8-ae31a32120fd/induction_recordsThe lead provider (Ambition) sees active while the DP (3 rivers) sees the equivalent of withdrawn. It appears to be a 'botched transfer' and the participant has changed cohort too
- Ticket: [CPDLP-1989](https://dfedigital.atlassian.net/browse/CPDLP-1989)
The `training_status` on the `participants.sql` query is being fetched from `participant_profiles` (profile level) and not from the latest induction record as we’re doing in the …
> [CPDLP-1989] Fix big data participants query to fetch the training status from latest induction record

- spec/services/npq/amend_participant_cohort_spec.rb
We amended the schedule defaults recently, meaning that the schedule can be selected depending on the time of year. When factories create the profile and link it to a schedule, that is based on the `schedule_for` method for an NPQ course, which will select one out of two schedules. In the spec since we're using `find_by` we are selecting any of those to test our expectation causing the test to be flakey.
- Ticket: N/A
- Use previous/current cohorts to avoid hardcoding
- Create the default schedules for the previous cohort, as that's not done in our default schedules set up. We've considered adding those there but this added time to the test suite and caused failures
- Use `schedule_for` to select schedules for the expectation to avoid flakiness and match the factory
> Fix NPQ amend cohort flakey spec

- app/services/analytics/ecf_induction_service.rb
- db/analytics_migrate/20230131103200_add_created_at_to_inductions.rb
- db/analytics_schema.rb
- spec/services/analytics/ecf_induction_service_spec.rb
The creation timestamp for induction records is useful for the analytics team. The existing `created_at` timestamp on the analytics table is the creation date of the analytics record, not the induction record itself.
> Add induction record created_at to analytics data

- app/views/admin/participants/history/show.html.erb
- app/views/admin/participants/induction_records/show.html.erb
- spec/features/admin/participants/participant_steps.rb
Instead of showing an empty page or an error display a message that tells the user there is no data.
Would recommend disabling whitespace when reviewing this PR, only a handful of lines have actually changed.
> Show informative messages on empty admin pages

- db/new_seeds/base/add_schools_and_local_authorities.rb
- db/new_seeds/scenarios/participants/mentors/mentoring_multiple_ects_with_same_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip.rb
- spec/factories/seeds/school_cohort_factory.rb
- spec/factories/seeds/school_factory.rb
- spec/factories/seeds/user_factory.rb
Previously schools were built without an induction coordinator. So we can test various journies more easily the following changes have been made:
* make user emails end in @example.com by default (allowing us to log in with any account in dev)
* ensure we generate induction coordinator profiles for schools when seeding
The process for testing out a school journey as an IC would be to log in with admin@example.com, choose a school, copy the email address and either log out and back in with it or to log in in a private browser window.
> Build induction coordinators when seeding data

- app/views/admin/participants/history/show.html.erb
We're checking for the presence of plural `@latest_induction_records` but the instance variable is singular `@latest_induction_record`.
> Fix bug on history tab

- app/controllers/api/v1/ecf_participants_controller.rb
- app/controllers/concerns/api/v1/participant_actions.rb
- app/serializers/api/v1/participant_from_query_serializer.rb
- app/services/api/v1/ecf/participants_query.rb
- spec/serializers/api/v1/participant_from_query_serializer_spec.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
The participant query is the worst performing query in the API. We've seen frequent timeouts even when providers use filters and pagination: https://sentry.io/organizations/dfe-teacher-services/issues/3739447110/?project=5748989&query=is%3Aunresolved&referrer=issue-stream
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1913
- Use left joins instead of `includes` to allow the selection of specific fields from models, which `includes` does not allow
- Specify some left joins to avoid obscurity around some fields we need for the serialiser 
- Eager load schedules as some fields are delegated in the model
- specify a different `schools_urn` field name to avoid n+1 queries due to delegation in the model
- Add a new serialiser which reads …
> [CPLD-1913] Improve participant query performance

- db/new_seeds/base/add_sit_nominations.rb
- db/new_seeds/run.rb
- db/new_seeds/scenarios/schools/invite_school.rb
This change should make it possible for people to test out the SIT journey from the beginning. We do it by seeding some blank schools and generating a notification email. This is usually where it gets complex because we need to pick that email up from Notify.
~~We need an easier way for non-devs to see paths/tokens they can use to start the SIT journey from the beginning, writing them to `public/seed_log.txt` seems like a good solution, but in the longer term being able to sign into the admin panel and click a button would probably be better.~~
The logging functionality was removed as @tonyheadford has a better solution on the way!
> Add seeding step for SIT nominations

- db/new_seeds/base/add_users.rb
- db/new_seeds/scenarios/users/lead_provider_user.rb
- spec/factories/seeds/provider_relationship_factory.rb
- spec/seeds/seed_factories/provider_relationship_factory_spec.rb
This change adds provider relationships to the seeding process for the `lead-provider@example.com` user. Now when they log in there will be a list under 'Your schools' - before there was blank space.
- Add factory for provider relationships
- Add provider relationship building to seed
> Seed provider relationships

- app/mailers/school_mailer.rb
- app/queries/schools/with_ects_with_no_mentor_query.rb
- lib/tasks/no_mentor_reminders.rake
- spec/queries/with_ects_with_no_mentor_query_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-1246)
- New rake task to print a list of schools with at least one ECT with no mentor associated.
- New rake task to send a reminder to any school with at least one ECT with no mentor associated.
> CST-1246: add rake task to remind SITs to add mentors to their ECTs

- app/services/admin/participants/search.rb
We appear to be running many queries to pull details from the teacher profile table that are used in the participants table on the index view. We can fetch these using the main query by joining using `participant_profile.teacher_profile_id`.
| ------ | ------- |
| ![Screenshot from 2023-02-07 15-25-02](https://user-images.githubusercontent.com/128088/217287602-a1766292-3d57-48dd-9b6c-5df60f6d9f1b.png) | ![Screenshot from 2023-02-07 15-24-47](https://user-images.githubusercontent.com/128088/217287634-7b4a8011-c47d-4e77-9d43-8acf07d4d3f0.png) |
These benchmarks are local so won't be representative of what we'll see in prod where network traversal per query is factored in. This should make a decent impact.
> Stop the n+1 query on admin participants index

- app/jobs/participant_outcomes/send_to_qualified_teachers_api_job.rb
- config/sidekiq.yml
- spec/jobs/participant_outcomes/send_to_qualified_teachers_api_job_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1957
* Sidekiq config setup and empty job `ParticipantOutcomes::SendToQualifiedTeachersApiJob` created
> [CPDLP-1957] Add Sidekiq job for sending a participant outcome to TRA

- app/controllers/api/notify_callbacks_controller.rb
- app/jobs/handle_notify_callback_job.rb
- spec/jobs/handle_notify_callback_job_spec.rb
- spec/requests/api/notify_callback_spec.rb
We don't need to deal with the notify callbacks immediately, instead create jobs and let them be picked up in due course.
> Create job to handle notify callbacks offline

- .github/workflows/brakeman-analysis.yml
- .github/workflows/deploy_to_dev.yml
- .github/workflows/deploy_to_staging.yml
- .github/workflows/destroy.yml
- .github/workflows/review.yml
Conventionally we use `main` for the default branch. When working on multiple projects having to remember ECF uses `develop` is a bit of a hassle.
- switch `develop` for `main` in the workflows that are triggered by activity on a branch or clone the repo
> Change target branch across all workflows

- app/models/participant_outcome/npq.rb
- app/models/participant_outcome_api_request.rb
- db/migrate/20230210115830_add_qualified_teachers_api_status_and_sent_to_qualified_teachers_api_at_to_participant_outcomes.rb
- db/migrate/20230210120533_create_participant_outcome_api_requests.rb
- db/schema.rb
- spec/models/participant_outcome/npq_spec.rb
- spec/models/participant_outcome_api_request_spec.rb
Some new required models/fields are required for TRA outcome integration.
- Ticket: [CPDLP-1955](https://dfedigital.atlassian.net/browse/CPDLP-1955)
- Add the new fields qualifications_api_status and sent_to_qualifications_api_at  to the outcomes table; (think of better names that indicate which API). This will help us re-queue jobs and capture the timestamp of a successful request to TRA. 
- Add the following new model: ParticipantOutcomeAPIRequest;
[CPDLP-1955]: https://dfedigital.atlassian.net/browse/CPDLP-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-1955] Create participant outcome api request model

- app/jobs/npq/stream_big_query_participant_outcome_job.rb
- app/models/participant_outcome/npq.rb
- spec/jobs/npq/stream_big_query_participant_outcome_job_spec.rb
- spec/models/participant_outcome/npq_spec.rb
- We need to be able to report the participant outcomes
- Ticket: [CPDLP-2009](https://dfedigital.atlassian.net/browse/CPDLP-2009)
- Add the ability to push/stream data into BigQuery
- On npq outcomes creation and updating of state, stream this data to BigQuery asynchronously.
[CPDLP-2009]: https://dfedigital.atlassian.net/browse/CPDLP-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2009] Push participant outcome data to big query

- app/controllers/api/v1/npq/users_controller.rb
- spec/requests/api/v1/npq/users/update_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-910
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-788
- Add `email` and `full_name` as params to `PATCH /api/v1/npq/users/:user_id`
> [CPDNPQ-788] [CPDNPQ-910] Update PATCH /api/v1/npq/users/:user_id to accept full_name and email as params

- app/controllers/admin/participants/event_history_controller.rb
- app/services/participants/history_builder.rb
- app/views/admin/participants/event_history/show.html.erb
- app/views/schools/participants/show.html.erb
- config/routes.rb
- db/schema.rb
- lib/tasks/compare/critical_data_changed_checker.rake
- lib/tasks/compare/event_history_analyser.rake
- spec/services/participants/history_builder_spec.rb
- spec/support/with_support_for_ect_examples.rb
It should be possible to see the historical events or changes to a CPD record over time in order to help determine why a record is in the state is is and where we might go to correct or undo any actions that misreported information.
Rake task creates a lists of CPD record change events that can be used to build up metrics of frequency and type of changes made over time
Add an events tab to the Admin Participants UI to allow Admin Users to view the event history of the record.
Provide a model within the application that understands how to traverse the relevant parts of the data model and papertrails in order to identify significant events in the record making process and transform them into an event list.
a rake task that can be run in small batches to process user profiles into event …
> Critical stats task

- app/jobs/participant_outcomes/stream_big_query_job.rb
- app/models/participant_outcome/npq.rb
- spec/jobs/participant_outcomes/send_to_qualified_teachers_api_job_spec.rb
- spec/jobs/participant_outcomes/stream_big_query_job_spec.rb
- spec/models/participant_outcome/npq_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2019
* Renamed `StreamBigQueryParticipantOutcomeJob` to `ParticipantOutcomes::StreamBigQueryJob`
* Job using `participant_outcomes` queue
* Moved job to the `apps/jobs/participant_outcomes` folder, to keep all outcome jobs in one place
> [CPDLP-2019] Change job queue to use participant_outcomes

- app/views/admin/schools/show.html.erb
This was made after a direct request from the support team. Opening it in the same window often makes them lose their place.
> Open links to a school's GIAS page in new tab

- db/new_seeds/base/add_npq_registrations.rb
- db/new_seeds/scenarios/npq.rb
- spec/factories/seeds/npq_application_factory.rb
When testing NPQ applications we found some gaps in our seed data.
It's been requested we add the following scenarios to help with testing:
- Accepted applications with profiles
- Pending applications with no profiles
- Rejected applications
- ASO/EHCO applications to test certain journeys
- Ticket: n/a
- Change NPQ scenarios to create a pending NPQ application, and if only accepted an NPQ participant profile
- Extend NPQ scenarios with rejected applications
- Add cohort to NPQ application seed
- Add multiple scenarios in our seed file to accommodate different states and courses
> Extend NPQ seed scenarios

- .github/common_environment.yml
- .github/workflows/brakeman-analysis.yml
- .github/workflows/deploy_monitoring.yml
- .github/workflows/deploy_monitoring_dev.yml
- .github/workflows/deploy_monitoring_production.yml
- .github/workflows/deploy_monitoring_staging.yml
- .github/workflows/deploy_to_dev.yml
- .github/workflows/deploy_to_production.yml
- .github/workflows/deploy_to_sandbox.yml
- .github/workflows/deploy_to_staging.yml
- .github/workflows/destroy.yml
- .github/workflows/force_destroy.yml
- .github/workflows/lint.yml
- .github/workflows/review.yml
- .github/workflows/run_task_dev.yml
- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- update Github Action versions
- rename jobs
- break out steps in to separate jobs for readability
- branch builds and deploys
- once the branch is merged into the main branch the events `lint` and `deploy` will need to be removed as those jobs no longer exist,
- either two new status events can be added for `ruby-linting` and `deploy-to-review-pr` or "Run Linter" can be "required" and "Create Review App" can be required on PR branches
> Update GitHub actions to remove warnings about node 12

- app/services/api/v1/ecf/participants_query.rb
- db/migrate/20230222142649_add_timestamp_indices_to_induction_records.rb
- db/schema.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
Induction records might not be in the correct `created_at` order, due to possible transfers and further amendments done in admin interface or console. This is causing the wrong induction record to be surfaced in the API, where providers might see a status as `withdrawn`
- Ticket: N/A
To ensure sure we prioritise the latest induction record correctly order by:
- End date being `nil`
- latest start date
- latest created at timestamp
This aligns with our `latest` scope fixed recently by @tonyheadford 
> Amend participant query to prioritise absence of end date

- app/views/layouts/_application.html.erb
- Ticket: https://trello.com/c/sADGOBFA/11-phase-banner
Remove phase banner from admin section.
> Hide phase banner on admin pages

- app/helpers/admin_helper.rb
- app/models/participant_profile/npq.rb
- app/views/admin/participants/cohorts/show.html.erb
- app/views/admin/participants/declaration_history/show.html.erb
- app/views/admin/participants/details/show.html.erb
- app/views/admin/participants/history/show.html.erb
- app/views/admin/participants/identities/show.html.erb
- app/views/admin/participants/induction_records/show.html.erb
- app/views/admin/participants/school/show.html.erb
- app/views/admin/participants/validation_data/show.html.erb
- spec/helpers/admin_helper_spec.rb
TRN is Teacher Reference Number. It's a unique number given to all qualified teachers
Cohort is the year the person began their ECF.
We already show the data in the admin pages.
This PR surfaces them so they're visible from everywhere.
> Add TRN and Cohort to admin participant page header

- .github/CODEOWNERS
- db/schema.rb
We had a odd situation where running `rails db:migrate` on `main` caused the `db/schema.rb` to be updated. The updates were innocuous and just added extra parenthesis but then mean other devs need to be concious not to re-commit their version, causing the file to flip flop unnecessarily.
I've set myself as codeowner just to keep an eye on it.
- Re-run db:migrate to reset schema.rb
- Set myself as codeowner of schema.rb
> Remove extra parens from schema.rb

- app/helpers/admin_helper.rb
The regular paragraphs had too much whitespace and looked a little funny.
| --------- | -----------|
| ![Screenshot from 2023-02-24 17-00-28](https://user-images.githubusercontent.com/128088/221241133-26a5a12f-f854-4fd6-b675-c8e61531ce1a.png) |  ![Screenshot from 2023-02-24 16-57-03](https://user-images.githubusercontent.com/128088/221241156-9ec06b2b-707c-40a0-8bc7-9e69baadc3ba.png) |
> Manually adjust margins on participant view

- app/services/qualified_teachers_api_sender.rb
- spec/services/qualified_teachers_api_sender_spec.rb
When an outcome is voided or failed to unset the certificate we need to send a request to the API with no completion date
- Ticket: n/a
Amend logic to not send completion date if an outcome is not passed
> Amend qualified API teacher logic to send empty completion date on failure/voided

- .github/workflows/lint.yml
It's handy to be able to see the results of rubocop runs in the GitHub actions log as well as the JSON artefact. Rubocop [allows multiple `--format` params to be passed in](https://docs.rubocop.org/rubocop/formatters.html) so we can do both.
> Run rubocop with progress formatter too

- db/new_seeds/base/add_mentor_scenarios.rb
- db/new_seeds/base/add_schools_and_local_authorities.rb
- db/new_seeds/scenarios/participants/ects/ect.rb
- db/new_seeds/scenarios/participants/mentors/mentor_with_no_ects.rb
- db/new_seeds/scenarios/participants/mentors/mentoring_multiple_ects_with_same_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip_changing_training_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip_keeping_original_training_provider.rb
- db/new_seeds/util/seed_utils.rb
- spec/factories/seeds/ecf_participant_eligibility_factory.rb
- spec/queries/with_ects_with_no_mentor_query_spec.rb
- spec/seeds/seed_factories/ecf_participant_eligibility_factory_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-1297):  add validation data to ECTs/Mentors seeded so they can be displayed properly in the participants dashboard.
> CST-1297: add validation data to participant profiles seeded

- app/models/participant_declaration/npq.rb
When we can't find an NPQ Outcome qualification type, we are logging this to Sentry. Since this is the final step in the method, the return value from the capture method is set to the qualification type and is attempted to be sent to the qualification API.
- Ticket: n/a
Send an empty qualification type to log the correct error from the API instead.
> Stop returning a Sentry object when calculating missing qualification type

- spec/support/with_default_schedules.rb
When selecting default schedules we are assuming all those are in the setup, as they are selected according to time ranges. 
- Ticket: N/A
Ensure all those schedules are available in our test set up, to avoid any future failures
> Add all expected default schedules for NPQ EHCO

- app/mailers/ineligible_participant_mailer.rb
We're seeing some crashes in prod when processing the reminder email jobs that contain `NQT+1_materials_link`.
`NQT+1_materials_link` placeholder has now been removed from the templates in Notify so removing the corresponding calls from the mailer should prevent the crashes we're still seeing while building the `start_schools_year_2020_url` path.
> Remove NQT+1 materials link path from reminders

- app/services/analytics/ecf_induction_service.rb
- db/analytics_migrate/20230227161000_add_partnership_id_to_inductions.rb
- db/analytics_schema.rb
- spec/services/analytics/ecf_induction_service_spec.rb
Nathan requested that the `partnership_id` field be added to `ecf_inductions` in the anaytics database as it would make downstream querying much easier.
- Add `partnership_id` column to analytics ecf_inductions
- Set `partnership_id` for induction records analysis
> Add partnership_id to analytics ecf_inductions table

- app/controllers/api/v1/npq/previous_fundings_controller.rb
- app/services/npq/funding_eligibility.rb
- config/routes.rb
- spec/factories/users.rb
- spec/requests/api/v1/npq/previous_funding/show_spec.rb
- spec/services/npq/funding_eligibility_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-883
This API is built as a replacement for api/v1/npq-funding/:trn.
The primary goal of building this replacement is to introduce an API that doesn’t depend on the existence of a TRN for it to function.
The existing API embedded the TRN being queried against into the URL itself. The new API doesn’t include any identifiers in the URL, instead receiving the user identifier data in the same way as course identifier information via query parameters.
This allows us to break out from a model where you have to have a TRN to where you can use multiple different kind of identifiers.
Old API formatting example:
`/api/v1/npq-funding/1234567?npq_course_identifier=npq-senior-leadership`
New API formatting example: …
> [CPDNPQ-883] Add api/v1/npq/previous_funding#show

- db/analytics_schema.rb
- db/new_seeds/base/add_mentor_scenarios.rb
- db/new_seeds/scenarios/induction_programmes/cip.rb
- db/new_seeds/scenarios/induction_programmes/fip.rb
- db/new_seeds/scenarios/participants/ects/ect.rb
- db/new_seeds/scenarios/participants/mentors/mentor_with_no_ects.rb
- db/new_seeds/scenarios/participants/mentors/mentoring_multiple_ects_with_same_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip_changing_training_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip_keeping_original_training_provider.rb
- db/new_seeds/scenarios/school_cohorts/cip.rb
- db/new_seeds/scenarios/school_cohorts/fip.rb
- db/new_seeds/scenarios/schools/school.rb
- db/schema.rb
- spec/factories/seeds/induction_programme_factory.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-1301): Ensure `SchoolCohort.default_induction_programme` is set when we're seeding schools/induction programmes
- Added new scenarios to create flexible school_cohorts and induction programmes that also set default programmes
> CST-1301: add default induction programme to school cohorts in seeds

- app/services/npq/change_to_pending.rb
- spec/services/npq/change_to_pending_spec.rb
When attempting to move an NPQ applicaton back to pending we are getting an error as we aren't destroying all associated 
records to the profile
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2063
When changing a schedule we create a `ParticipantProfileSchedule`. Ensure we delete those records when deleting the profile.
> [CPDLP-2063] Delete participant schedules when moving an npq application to pending

- app/controllers/lead_providers/report_schools/csv_controller.rb
- app/jobs/sync_partnership_csv_upload_job.rb
- app/models/partnership_csv_upload.rb
- db/migrate/20230304184644_add_urns_array_to_partnership_csv_upload.rb
- db/schema.rb
- spec/jobs/sync_partnership_csv_upload_job_spec.rb
- spec/models/partnership_csv_upload_spec.rb
- spec/requests/lead_providers/report_schools/csv_spec.rb
We will soon be migrating the ECF app from GOV.UK PaaS to Azure. The application's data is currently spread across four places:
- Production database (PostgreSQL)
- analytics database (PostgreSQL)
- Sidekiq database (Redis)
- File storage (S3 via PaaS)
The first three are easy to migrate and will involve a restore of the database in the new environment.
The file storage move is difficult because S3 and Azure Blob Storage aren't identical. We'd need to use ActiveStorage mirrors and rely on a syncing process before switching the 'master' copy.
The uploaded CSVs only contain a single column of URNs. We can easily use PostgreSQL's array functionality to save the provided list of URNs. This will make the migration considerably easier and remove a unnecessary infrastrucutre component in the …
> Move CSV uploads from ActiveStorage to an array of URNs

- app/controllers/admin/schools/participants_controller.rb
- app/forms/admin/validation_data_form.rb
- app/forms/schools/add_participant_form.rb
- app/models/ecf_participant_validation_data.rb
- spec/components/admin/participants/table_spec.rb
- spec/components/participant_status_tag_component_spec.rb
- spec/components/schools/participants/coc_status_table_spec.rb
- spec/cypress/app_commands/scenarios/school_participants.rb
- spec/factories/ecf_participant_eligibility.rb
- spec/factories/ecf_participant_validation_data.rb
- spec/factories/induction_record.rb
- spec/factories/participant_profiles.rb
- spec/factories/seeds/finance_milestone_factory.rb
- spec/lib/mail/delivery_recorder_spec.rb
- spec/models/ecf_participant_validation_data_spec.rb
- spec/models/induction_record_spec.rb
- spec/models/participant_identity_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/requests/schools/add_participants_spec.rb
- spec/seeds/seed_factories/finance_milestone_factory_spec.rb
- spec/services/admin/participants/search_spec.rb
- spec/services/analytics/ecf_induction_service_spec.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
- spec/services/data_stage/process_school_changes_spec.rb
- spec/services/identity/transfer_spec.rb
- spec/services/participant_profile_status_spec.rb
`ParticipantProfile` is inherited by a (almost) abstract model, `ParticipantProfile::ECF`. No `ParticipantProfile::ECF` records can exist in prod but we did use them in a few places for testing.
When trying to upgrade to Rails 7 #3004 this caused problems as Rails complains about the [STI structure](https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html). Removing the references to `ParticipantProfile::ECF` should allow us to restructure the STI and make it work with newer versions of Active Record
The longer term goal is to flatten the STI structure but to do that we first need to remove references to `ParticipantProfile::ECF`.
| What we have now | What we're aiming for (not in this PR!) |
| --------------------- | ---------------------|
| ![Screenshot from 2023-02-15 …
> Remove references to ParticipantProfile::ECF

- app/services/coc_set_participant_categories.rb
- app/views/schools/participants/index.html.erb
Attempt to fix the `TypeError: Cannot read properties of undefined (reading 'setAttribute')` errors that have been appearing in Sentry recently. I believe it is down to us rendering the `govuk_tabs` container but then not adding any tabs to it in the participants view when there are no participants in the cohort, however I couldn't recreate the JS error locally.  This fix just adds a guard around the container creation.
> [Bug-fix] Prevent rendering tabs container when no categories present

- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFPartnershipAttributes.yml
The definitions were reported to be flipped for created and updated at.
- Ticket: n/a
Amend the field definitions to be correct for `updated_at` and `created_at` for partnerships in API v3
> Fix updated_at/created_at partnership definitions in API v3

- spec/services/admin/npq_applications/applications_search_spec.rb
We are getting a flakey test failure https://github.com/DFE-Digital/early-careers-framework/actions/runs/4353661772/jobs/7607987362 
This is due to the school names being set up randomly and can be similar, causing both records to be returned when searching by partial names of the first school
- Ticket: n/a
Set explicit names on the school setup, so searching by name won't return both results.
> Set explicit school names to avoid flakey test when looking up by partial name

- app/controllers/admin/npq/applications_controller.rb
- app/services/admin/npq_applications/applications_search.rb
We had poor performance on the NPQ applications list page because we were loading all the applications into memory before paginating. Pagy should run the query so it can apply the pagination in SQL.
- Switch from pagy_array to pagy
- Squash a couple of n+1s on the npq applications list
> Stop loading all the NPQ applications at once

- app/models/partnership_csv_upload.rb
Just a small tweak, some of the CSVs uploaded have formats other than UTF-8. Makes it easier to force them to be UTF-8 before extracting the contents.
> Convert any uploads to UTF-8 before using them

- app/views/admin/participants/school/show.html.erb
in the admin pages.
Schools can have multiple `School` records, but only one active. In such cases, the mentors may still be in the Mentor Pools of the inactive school records with no clear indication in the Admin pages -> Mentor profile -> School tab. That can mislead us to think everything is OK when SITs will be actually blocked from assigning mentors to ECTs.
- Ticket: N/A
We don't see this issue very often, so it  should help for now to visually identify such issues by displaying both the school URN and the school name in the `Mentoring at` list.
| before | after
|-|-|
|![before](https://user-images.githubusercontent.com/951947/223752197-3855ab10-2eec-4de1-89ec-8894fa1fa402.png)|![after](https://user-images.githubusercontent.com/951947/223756185-d04af10a-66d0-49bf-be33-815cb42d7c05.pn …
> Make it clearer in which schools a mentor is mentoring at

- app/controllers/api/v1/npq_applications_controller.rb
- app/serializers/api/v1/npq_application_serializer.rb
- spec/serializers/api/v1/npq_application_serializer_spec.rb
If a user's email is updated, we aren't surfacing that correctly in the updated at timestamp of the NPQ application in the API which is causing issues for providers when polling for changes
- Ticket: n/a
Use the user, identity, profile and npq application `updated_at` timestamps to surface the latest change to ensure that anything updated will be shown to providers.
Add profile to includes list for n+1s.
I noticed that although we have includes we are getting n+1s on the query `previously_funded?` on NPQ applications, will look into that separately.
> Update NPQ serialiser updated_at attribute to poll multiple records

- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/services/admin/npq_applications/applications_search_spec.rb
https://github.com/DFE-Digital/early-careers-framework/actions/runs/4378534706/jobs/7663398663
To avoid flakey tests with `updated_at` field, freeze time to avoid different times. This is because we now have multiple values to choose from when calculating the NPQ application `updated_at` field.
https://github.com/DFE-Digital/early-careers-framework/actions/runs/4374663161/jobs/7654373465
Explicitly set user name when setting up applications, to avoid flakey tests when users have similar names
- Ticket: N/A
- Freeze time when setting up NPQ applications to avoid different times
- Set exact names on users to avoid accidentally looking up multiple records
> Fix flakey NPQ application request and search specs

- spec/docs/v1/npq_applications_spec.rb
- spec/docs/v1/participant_declarations_spec.rb
- spec/docs/v1/participants_ecf_spec.rb
- spec/docs/v2/npq_applications_spec.rb
- spec/docs/v2/npq_enrolments_spec.rb
- spec/docs/v2/participant_declarations_spec.rb
- spec/docs/v2/participants_ecf_spec.rb
- spec/swagger_helper.rb
When testing our API spec, if schema was incorrect, the tests weren't failing. We can use the original schema method to ensure we test our API spec and it fails as expected, and also use the expected syntax "produces" to what the expected content type is.
- Ticket: n/a
- Remove schema helper
- use `produces` to test expected content type
- swap out instances using old helper syntax
Did I miss anything
rswag docs: https://github.com/rswag/rswag
> Remove schema Rswag helper

- app/serializers/api/v3/ecf/partnership_serializer.rb
- spec/serializers/api/v3/ecf/partnership_serializer_spec.rb
While having a rethink of tests for v3 stumbled upon a few things we can improve in partnership testing
- Ticket: n/a
- Return cohort as string (as set in docs)
- Always return status, default is active unless challenged
- Separate tests for each field, and add contexts for status field
> Improve Partnership serialiser testing

- app/views/admin/participants/_nav.html.erb
> ‘If you click the 'Back’ button on the admin console page it forgets the search you'd done/school page you were on etc so you had to re-search for where you were before (this came up a lot when I was on a really specific participant trying to figure out what had gone wrong)' (highlighted afterwards that this issue was probably the most frustrating)
*Current behaviour*: When investigating issue with participant, and searching via their school, the _Back_ button does not follow expected behaviour i.e. go back a step in the user journey.
This PR removes the back button until we can implement a more useful solution, e.g. breadcrumbs.
- Ticket: https://trello.com/c/xorlDVRo/18-back-button
> Remove back link from admin console page

- app/models/cohort.rb
- db/migrate/20230314120416_add_npq_registration_start_date_to_cohorts.rb
- db/schema.rb
- spec/models/cohort_spec.rb
- Ticket: [CPDLP-2086](https://dfedigital.atlassian.net/browse/CPDLP-2086)
We need to add a new field for NPQ registration_start_date as the current one is more for ECF related stuff.
If we were to add a new cohort and use registration_start_date to determine the next cohort for NPQ registration this would impact ECF which is not ready for the new cohort.
We have agreed adding a new field to the cohorts table will help resolve the issue.
[CPDLP-2086]: https://dfedigital.atlassian.net/browse/CPDLP-2086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2086] Add new registration start date field to cohorts table for NPQ

- app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: N/A
I want an easy way for us to find and distinct the Profile id from the User id and External id in the Admin->Participant pages.
Currently we use it in the url params, but is not obvious which id is it and can be easily confused with the user id or external id.
- Rename the `ID` label to `User ID` to be more explicit
- Display the Profile ID in the Admin->Participant->Details page.
> Display the Profile id in the admin participant details

- db/new_seeds/scenarios/npq.rb
When accepting applications NPQ course is empty on profiles, make sure to set it to the NPQ application
- Ticket: n/a
Set NPQ course when building a profile to the application's NPQ course
> Set NPQ course when accepting NPQ application in seeds

- .devcontainer/Dockerfile
- .devcontainer/boot.sh
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- Procfile.dev
- README.md
- config/initializers/sidekiq.rb
- docs/Makefile
This change enables Codespaces for the ECF app. This will help less technical colleagues make direct changes.
The only change that has any risk of affecting the app is the one to the initializer that lets us easily specify the `REDIS_URI` using a environment variable instead of letting it default to `localhost`.
Note, in its current form this PR adds `entr` as a dependency for running `bin/dev` - not ideal but I can't find a way of making Middleman continuously monitor for changes (like `middleman serve`) but actually output built files (like middleman build`). @DFE-Digital/teacher-cpd - any ideas?
| Preview |
| ------- |
| ![image](https://user-images.githubusercontent.com/128088/224399792-00bfad04-c6f2-4068-bfe1-885a71d7ba88.png) |
> Codespaces

- db/new_seeds/scenarios/participants/mentors/mentor_with_no_ects.rb
- spec/factories/seeds/school_mentor_factory.rb
- spec/seeds/seed_factories/school_mentor_factory_spec.rb
Following on from the tech debt chat this morning, this change ensures that the link table between schools and mentors is populated. Previously only the induction record link was set (saying the mentor is mentoring someone at a school) but this one marks the mentor as _being_ at that school.
- Add seed factory for the school_mentors link table
- Add school mentor to mentor with no ects scenario
> Ensure school/mentor relationships are seeded

- app/models/ecf_participant_validation_data.rb
- app/models/npq_application.rb
- app/models/participant_identity.rb
- app/models/teacher_profile.rb
- app/models/user.rb
To avoid PII bubbling up in exception errors us the `filter_attributes` on select models
- Ticket: n/a
- `filter_attributes` filters selected columns when calling #inspect, add to models with PII
> Filter PII attributes from models

- app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: N/A
The profile's training status is still in use, but we don't display it anywhere. That's causing confusions with withdrawn profiles that have active training status in their Induction Records.
Display the profile training status in the Admin -> Participant -> Details page.
> Display the profile training status in the Admin participant page

- app/services/change_schedule.rb
- spec/services/change_schedule_spec.rb
There are some cases where the profile schedule will be the same as the new schedule we are attempting to change to, however the induction record has a different schedule.
This can happen in transfers, when a profile is amended after a participant has transferred, leaving the induction record with an incorrect schedule, but the profile with the correct one.
Allow the change to happen to align all schedules without raising a validation error
- Ticket: n/a
Add extra check for ECF profiles on induction record schedules to ensure they aren't equal to allow schedules to change
> Check induction record schedule before raising validation error when changing schedule

- spec/services/admin/npq_applications/applications_search_spec.rb
When emails are similar in test setup, spec will fail as it will find the second application.
- Ticket: n/a
Explicitly set different emails to avoid flakey spec
Hopefully I got it this time :)
> Attempt 2: Ensure user emails are different to avoid flakey tests in application search spec

- config/seed_quantities.yml
- db/new_seeds/base/add_npq_registrations.rb
- db/new_seeds/base/add_schools_and_local_authorities.rb
- db/new_seeds/base/add_sit_nominations.rb
- db/new_seeds/base/add_transfer_scenarios.rb
- db/new_seeds/run.rb
The quantity of seeded records was hard coded. This worked well but it:
- didn't account for personal preference
- isn't environment specific
- doesn't make it easy to get an overview of what's being created
This change adds some config and an method that pulls values from it. It also allows those values to be overridden locally with environment variables.
The configuration key will be overridden by a matching environment variable that's uppercase and prefixed with `SEED_`, so to override `local_authorities: 3` we can set `SEED_LOCAL_AUTHORITIES=10`.
> Enable configuration of seed quantities per env

- app/mailers/participant_transfer_mailer.rb
- app/models/participant_identity.rb
- app/serializers/api/v1/npq_application_csv_serializer.rb
- app/serializers/api/v1/npq_application_serializer.rb
- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- app/serializers/api/v1/participant_from_query_serializer.rb
- app/serializers/api/v1/participant_outcome_serializer.rb
- app/serializers/api/v2/npq_application_csv_serializer.rb
- app/services/api/v1/ecf/participants_query.rb
- app/services/api/v1/participant_outcomes_query.rb
- app/services/feature_flag.rb
- app/services/finance/ecf/assurance_report/query.rb
- app/services/finance/npq/assurance_report/query.rb
- app/services/participant_identity_resolver.rb
- app/services/record_declaration.rb
- spec/serializers/api/v1/npq_application_csv_serializer_spec.rb
- spec/serializers/api/v1/npq_application_serializer_spec.rb
- spec/serializers/api/v1/participant_from_query_serializer_spec.rb
- spec/serializers/api/v2/npq_application_csv_serializer_spec.rb
- spec/serializers/api/v2/npq_application_serializer_spec.rb
- spec/services/change_schedule_spec.rb
- spec/services/defer_participant_spec.rb
- spec/services/finance/ecf/assurance_report/query_spec.rb
- spec/services/finance/npq/assurance_report/query_spec.rb
- spec/services/participant_identity_resolver_spec.rb
- spec/services/record_declaration_spec.rb
- spec/services/resume_participant_spec.rb
- spec/services/withdraw_participant_spec.rb
- Ticket: n/a
We would like to fully enable this feature in production
- Fully switch to using `user_id` in the API
- remove feature flag and any instances it's used
- Switch back to one place in testing
This is based off @leandroalemao's excellent work in: https://github.com/DFE-Digital/early-careers-framework/pull/3075
> Remove `external_identifier_to_user_id_lookup` feature flag

- app/forms/admin/school_transfer_form.rb
- config/locales/en.yml
- spec/forms/admin/school_transfer_form_spec.rb
- Ticket: CST-1352
The transfer school form in the Admin pages accepts URNs from any existing schools and raises an exception, which results to a 404 page when submitting it with the participant's current school urn.
Add an ActiveModel validation to display a meaningful error message when the submitted URN is not from a new school
1. visit the to Admin pages
2. pick a participant
3. visit the School tab
4. click Transfer to another school
5. type in the the URN of the school the participant is already at
6. the form should display a validation error message instead of letting you continue
> Validate Admins are moving participants to new school

- app/forms/finance/ecf/change_training_status_form.rb
- app/forms/finance/npq/change_training_status_form.rb
- app/services/api/v1/ecf/participants_query.rb
- spec/forms/finance/ecf/change_training_status_form_spec.rb
- spec/forms/finance/npq/change_training_status_form_spec.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
If a profile user is different than the participant identity changing training status is failing due to us switching services to use `user_id`
- Ticket: n/a
Switch forms to use `user_id` instead of `external_id`
> Pass in `user_id` instead of `external_id` to change participant status

- app/models/school_cohort.rb
- config/locales/en.yml
- db/migrate/20221012103024_add_unique_index_to_school_cohorts.rb
- db/schema.rb
- spec/models/school_cohort_spec.rb
- spec/requests/admin/schools/cohorts_spec.rb
This PR is an update of [this one](https://github.com/DFE-Digital/early-careers-framework/pull/2606) created by @peteryates a few months ago. All credits must go to him.
We had a case recently where a school had two 2021 cohort records. This should never happen. This change enforces it both at the database and model level.
* add a unique index to `school_cohorts` on `school_id` and `cohort_id`
* add a unique constraint to the `SchoolCohort` model
**Don't merge this until we have no more duplicates.**
This query should return no results in prod.
```
with dupes as (
select school_id, cohort_id
from school_cohorts
group by school_id, cohort_id
having count(*) > 1
)
select urn, name, postcode
from schools
join dupes on schools.id = dupes.school_id;
```
> Ensure school cohort combinations are unique 2

- app/models/partnership_csv_upload.rb
- spec/models/partnership_csv_upload_spec.rb
Some records contain unwanted characters that cause Ruby to error with "invalid byte sequence in UTF-8". The unwanted characters can appear anywhere in the line.
This approach adds a bit of safety, we're now scrubbing the file to remove invalid byte sequences and then only selecting word characters - this should leave us with only what we want.
> Remove any unwanted characters from CSV uploads

- app/forms/finance/npq/change_lead_provider_form.rb
- spec/features/finance/change_lead_provider_spec.rb
- spec/forms/finance/npq/change_lead_provider_form_spec.rb
- Ticket: [CPDLP-2121](https://dfedigital.atlassian.net/browse/CPDLP-2121)
Currently, the transfer functionality only shows when there are declarations that are submitted, eligible, payable or paid.
We will need to add `awaiting_clawback` and `clawed_back` to the list of states that should surface the transfer functionality.
[CPDLP-2121]: https://dfedigital.atlassian.net/browse/CPDLP-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2121] Add in additional states to the NPQ transfer service functionality

- app/controllers/admin/participants/add_to_school_mentor_pool_controller.rb
- app/forms/admin/participants/add_mentor_to_school_form.rb
- app/views/admin/participants/add_to_school_mentor_pool/new.html.erb
- app/views/admin/participants/school/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/forms/admin/participants/add_mentor_to_school_form_spec.rb
- Ticket: CST-1360
We need an admin page to enable Admins to assign Mentors to mentor in other schools.
- Add a button in the Admin -> Participants -> Schools page to add the mentor to another school
- Add a new page asking for the school urn of the new school
- Add a form obj to validate
- the form input
- the school urn corresponds to an existing school
- the mentor is not already mentoring in the school
The form obj uses the `Mentor::AddToSchool` service obj to add the mentor to the school's mentor pool.
1. go to the admin pages
2. pick a mentor
3. click to school tab
4. click the `add to a school mentor pool` button
5. type in a urn from an new school and submit the form or
To see the validation errors:  Follow steps 1-4 from above and in step 5 type in incorrect urns or urns from …
> Add an Admin page for assigning mentors to other schools

- app/controllers/admin/impersonates_controller.rb
- spec/cypress/integration/admin/SchoolManagment.feature
- spec/requests/admin/impersonates_spec.rb
When impersonating an induction tutor, clicking "stop impersonating" takes the impersonator back to the original home page rather than to the admin view of the impersonated user's school.
When the admin user begins impersonating, we store the impersonation start location. When ending the impersonation, the admin user is sent back to the stored impersonation start location.
- Ticket: https://trello.com/c/r7QYqHjS/9-sit-impersonation
> Send impersonator back to starting point when done impersonating

- app/models/finance/schedule/npq_leadership.rb
- app/models/finance/schedule/npq_specialist.rb
- spec/models/finance/schedule/npq_leadership_spec.rb
- spec/models/finance/schedule/npq_specialist_spec.rb
NPQ registration is opening on 3/4/2023, we need to ensure candidates are on the Autumn schedule
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2124
Amend both NPQ leadership and Specialist schedules to shift to Autumn earlier:
Given today’s date is betweeen 1 June 2022 and 25 December 2022, then the schedule will be npq-specialist-autumn or npq-leadership-autumn
Given today’s date is betweeen 26 December 2022 and 2 April 2023, then the schedule will be npq-specialist-spring or npq-leadership-spring
Given today’s date is between 3 April 2023 and 25 December 2023, then the schedule will be npq-specialist-autumn or npq-leadership-autumn
Given today’s date is betweeen 25 December 2023 ad 15 April 2024, then the schedule will be npq-specialist-spring or npq-leadership-spring
Did I …
> Shift NPQ default schedules to match new NPQ registration opening

- spec/features/finance/change_lead_provider_approval_status_spec.rb
- spec/features/finance/npq/view_contract_spec.rb
- spec/models/npq_application_spec.rb
- spec/models/npq_course_spec.rb
- spec/serializers/api/v1/npq_participant_serializer_spec.rb
- spec/services/npq/application/accept_spec.rb
- spec/support/with_default_schedules.rb
There are failures on main due to the switch in default NPQ schedules. The failures are because we are using default schedule lookups rather than the new `schedule_for` method. Also we are creating all schedules across multiple cohorts
- Ticket: 
- With default schedules creates schedules across cohorts
- Add helper in tests to avoid creating schedules in the setup
- Remove use of default schedule for schedule for to avoid future failures
I will spend more time with this after to try to ensure we cleanup all tests so this doesn't happen again
> Use default NPQ schedule helper in specs

- app/components/admin/schools/cohorts/cip_info.html.erb
- app/components/admin/schools/cohorts/fip_info.html.erb
- app/components/admin/schools/cohorts/other_info.html.erb
- spec/components/admin/schools/cohorts/cohort_spec.rb
- spec/components/admin/schools/cohorts/other_info_spec.rb
The AB is now displayed per cohort on the cohorts index page.
> Show school's appropriate body in admin interface

- app/services/importers/npq_manual_validation.rb
- spec/services/importers/npq_manual_validation_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-970
We dont update the TRN on the teacher profile during the manual validation process and this has had to be done manually for a lot of users. This will ensure future users get updated.
> Update teacher_profile trn when using the manual script

- config/seed_quantities.yml
- db/new_seeds/base/add_npq_registrations.rb
- db/new_seeds/scenarios/npq.rb
- spec/factories/seeds/npq_application_factory.rb
- spec/factories/seeds/participant_profile_state_factory.rb
- spec/seeds/seed_factories/participant_profile_state_factory_spec.rb
- Ticket: [CPDLP-2106](https://dfedigital.atlassian.net/browse/CPDLP-2106)
We currently have two sets of seeds:
Legacy seeds: used in tests and used to populate review apps before being deprecated
New seeds: populate review apps
The new seeds do not have as much data as the old seeds, where we are missing some key data.
In order for Tom/Shahad to test single endpoints and then whole journeys, also for us to later prep some seed data for providers on sandbox, we need to ensure that our seed data is adequate.
"New seeds" checked for NPQ participants (npq application and profiles) and if they are adequate for testing our endpoints and journeys.
[CPDLP-2106]: https://dfedigital.atlassian.net/browse/CPDLP-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> [CPDLP-2106] Improve NPQ participant seeds

- README.md
- bin/dev
Running bin/dev is really noisy, mainly with failed email sending and background data sync. I don't usually want it.
With this change, passing in a `-j` argument to bin/dev (`bin/dev -j`) now only runs the web, css and js portions of Procfile.dev, which allows for a noise free experience when jobs aren't needed.
Tested on Linux. I assume this will work on macOS, definitely needs testing before merge!
> Allow bin/dev to run without jobs

- db/new_seeds/scenarios/induction_programmes/fip.rb
- db/new_seeds/scenarios/schools/school.rb
In order for a partnership to be valid, a relationship needs to exist between the lead provider/cohort/delivery partner. Create those in the seeds
- Ticket: n/a
Add provider relationships everywhere we create partnerships.
This is required for the partnership testing endpoints
> Create provider relationships for partnerships in seeds

- app/serializers/api/v3/ecf/partnership_serializer.rb
- spec/docs/v3/ecf_partnerships_spec.rb
- spec/requests/api/v3/ecf/partnerships_spec.rb
- spec/serializers/api/v3/ecf/partnership_serializer_spec.rb
- swagger/v3/api_spec.json
@hazelyule has pointed out some incorrect API responses for POST and PUT partnership endpoints
- Ticket: n/a
- Add manual examples to the v3 API spec for POST and PUT partnership endpoints which are not challenged to avoid confusion 
- Amend partnership response type to match API spec
> Update partnership API spec

- app/jobs/create_new_fake_sandbox_data_job.rb
- app/serializers/api/v1/participant_from_induction_record_serializer.rb
- app/serializers/api/v1/participant_from_query_serializer.rb
- app/services/api/v1/ecf/participants_query.rb
- config/seed_quantities.yml
- config/sidekiq_cron_schedule.yml
- db/new_seeds/base/add_ects_becoming_mentors.rb
- db/new_seeds/run.rb
- db/new_seeds/scenarios/participants/ects/ect.rb
- db/new_seeds/scenarios/participants/mentors/mentor_with_no_ects.rb
- db/new_seeds/scenarios/schools/school.rb
- docs/source/release-notes.html.md
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/requests/api/v2/ecf_participants_spec.rb
- spec/serializers/api/v1/participant_from_induction_record_serializer_spec.rb
- spec/serializers/api/v1/participant_from_query_serializer_spec.rb
- spec/services/api/v1/ecf/participants_query_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
- swagger/v1/component_schemas/ECFParticipantCsvRow.yml
- swagger/v1/component_schemas/MultipleECFParticipantsCsvResponse.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/ECFParticipantAttributes.yml
- swagger/v2/component_schemas/ECFParticipantCsvRow.yml
- swagger/v2/component_schemas/MultipleECFParticipantsCsvResponse.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2078
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2119
* Exposes the participant profile ID as `training_record_id` on API V1/V2 endpoints.
* Allow the user to query by participant profile ID
This relies on the `external_identifier_to_user_id_lookup` feature flag to avoid duplication with redundant functionality. This flag (and the redundant code) is due to be removed soon.
Otherwise, please check whether I've understood the intent correctly! 🤞
> Prefer participant profile ID on V1/V2 API participant endpoints

- app/services/api/v3/delivery_partners_query.rb
- spec/services/api/v3/delivery_partners_query_spec.rb
Avoid duplicate records from delivery partner query if delivery partner is in a relationship across multiple cohorts.
- Ticket: n/a
Add `distinct` to delivery partner query for API v3
> Return distinct delivery partners in API response

- app/services/importers/add_cohort_to_lead_provider.rb
- spec/services/importers/add_cohort_to_lead_provider_spec.rb
We need to populate Cohort 2023 for ECF. To allow this we need to append the new cohort to existing lead providers 
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2137
Add script which receives a csv with cohort start year to lead a provider's name. This will append the cohort to the lead provider, both the cohort and lead provider need to exist
I did not add this to the seeds as it didn't feel right to since we are creating new lead providers dynamically.
> [CPDLP-2137] Add lead provider to cohort script

- app/services/finance/ecf/statement_calculator.rb
- app/views/finance/ecf/statements/show.html.erb
- spec/services/finance/ecf/statement_calculator_spec.rb
- Ticket: [CPDLP-2132](https://dfedigital.atlassian.net/browse/CPDLP-2132)
Assurance made Digital aware that the adjustment section in the statements was not adding up the figures between uplift clawback and clawback adjustments in the adjustments table for ECF financial statements.
As this information is processed and passed to providers, we must ensure that our data is accurate.
When the statement has both uplift clawback and clawback from a declaration.. they should be aggregated to the total value in the adjustment table and in the summary table under the adjustments line item.
[CPDLP-2132]: https://dfedigital.atlassian.net/browse/CPDLP-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2132] Add uplift clawbacks in adjustments totals on financial statements page

- app/controllers/api/v1/npq_participants_controller.rb
- app/controllers/api/v3/npq_participants_controller.rb
- app/models/participant_profile_state.rb
- app/serializers/api/v3/npq_participant_serializer.rb
- app/services/api/v3/npq_participants_query.rb
- app/validators/participant_not_withdrawn_validator.rb
- config/routes.rb
- db/migrate/20230414123726_add_index_to_participant_profile_states.rb
- db/schema.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/factories/participant_profiles.rb
- spec/models/participant_profile_state_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/serializers/api/v3/npq_participant_serializer_spec.rb
- spec/services/api/v3/npq_participants_query_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/NPQEnrolment.yml
- swagger/v3/component_schemas/NPQParticipantAttributes.yml
- swagger/v3/component_schemas/NPQParticipantsSort.yml
We’d like to surface NPQ participants as well as all related actions in V3.
- Ticket: [CPDLP-2110](https://dfedigital.atlassian.net/browse/CPDLP-2110)
Add a new GET endpoint `/api/v3/participants/npq endpoint` to fetch NPQ participants and their NPQ enrolments.
[CPDLP-2110]: https://dfedigital.atlassian.net/browse/CPDLP-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2110] Add GET /api/v3/participants/npq endpoint

- app/assets/stylesheets/search_box.scss
- app/controllers/admin/delivery_partners/users_controller.rb
- app/controllers/admin/suppliers/supplier_users_controller.rb
- app/controllers/admin/suppliers/suppliers_controller.rb
- app/queries/delivery_partner_profiles/search_query.rb
- app/queries/delivery_partners/search_query.rb
- app/queries/lead_provider_profiles/search_query.rb
- app/queries/lead_providers/search_query.rb
- app/views/admin/delivery_partners/users/index.html.erb
- app/views/admin/suppliers/supplier_users/index.html.erb
- app/views/admin/suppliers/suppliers/index.html.erb
'being able to search supplier / delivery partners would be useful. 'Cause at the moment you can't search and it's just alphabetical and you have to guess what page suppliers starting with the letter T would be on'
- Ticket: https://trello.com/c/Ae4uONdB/10-add-search-bar-on-supplier-and-dp-page
> Add search bar to admin suppliers and delivery partners pages

- app/assets/stylesheets/schools/dashboard.scss
No visual changes here. The original CSS didn't use the provided GOV.UK frontend utilities and helpers and contained some repetition that can be removed thanks to Sass.
| -------  | ---------- |
| ![Screenshot from 2023-04-18 15-52-47](https://user-images.githubusercontent.com/128088/232816909-e016d967-aad9-42ff-bc83-d11d147b1e7d.png) | ![Screenshot from 2023-04-18 15-52-38](https://user-images.githubusercontent.com/128088/232816941-1cecdd69-159e-4b3d-bd16-ad99776266f6.png) |
> Refactor and tighten up CSS

- app/services/importers/create_cohort.rb
- app/services/importers/create_new_ecf_cohort.rb
- spec/services/importers/create_cohort_spec.rb
- spec/services/importers/create_new_ecf_cohort_spec.rb
The script receives all csvs for other scripts and creates a standalone ECF cohort
To support cohort 2023 for ECF, records relating to the cohort need to be populated. This includes ECF contracts, schedules, statements and cohort.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2139
- Add new script that consumes CSVs and runs all required services to create an ECF cohort
- Update Cohort script to create or update existing cohorts, as we need to update fields on existing cohort 2023 in prod
> Add new script to create ECF cohort

- db/migrate/20230419084407_amend_unique_index_participant_declaration.rb
- db/schema.rb
Whilst attempting to mark statements as paid, I got the following error:
```
ERROR:  duplicate key value violates unique constraint "unique_declaration_index" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (cpd_lead_provider_id, participant_profile_id, declaration_type, course_identifier, state)=(xxxx, xxxx, started, ecf-mentor, clawed_back) already exists.
```
A unique index was added to prevent double posting, but we should allow the a declaration belonging to the same profile/lead provider/state be clawed back more than once if necessary
- Ticket: n/a
Remove clawed back from the unique index but keep the rest the same
> Remove clawed back from uniq declaration index

- app/controllers/admin/npq/applications/change_email_controller.rb
- app/controllers/admin/npq/applications/change_name_controller.rb
- app/views/admin/npq/applications/_application_details.html.erb
- app/views/admin/npq/applications/change_email/edit.html.erb
- app/views/admin/npq/applications/change_name/edit.html.erb
- config/routes.rb
- spec/requests/admin/npq/applications/change_email_spec.rb
- spec/requests/admin/npq/applications/change_name_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-789
Allow name and email change to non-GAI users through the application tab
> allow name and email change through the npq application tab

- app/views/dashboard/show.html.erb
- spec/features/lead_providers/dashboard_page_spec.rb
If the next cohort registration isn't open do not surface ability to create partnerships
- Ticket: n/a
Only show cohorts up to the Cohort open for registration
> Limit providers from adding partnerships unless cohort registration open

- app/mailers/school_mailer.rb
- app/services/update_induction_tutor_reminder.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/update_induction_tutor_reminder_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-1422
We want to send reminders to GIAS contacts at schools so they can update their induction tutor if required. This change adds a service class that allows us to perform that using the console.
Suggested way to use it is:
```ruby
schools = School.where(urn: SOME_LIST_OF_URNS_FROM_SPREADSHEET)
schools.each { |s| UpdateInductionTutorReminder.new(s).send! }
```
- Add method to trigger induction tutor update email
- Add service class for sending update reminders
> Add reminder for updating induction tutor

- app/controllers/admin/impersonates_controller.rb
- spec/requests/admin/impersonates_spec.rb
- Ticket: https://trello.com/c/r7QYqHjS/9-sit-impersonation
Store impersonation start path in cookies rather than ActiveRecord::SessionStore::Session.
> Store impersonation start path in cookies rather than ActiveRecord::SessionStore::Session

- app/jobs/update_induction_tutor_reminder_job.rb
- app/mailers/school_mailer.rb
- app/services/update_induction_tutor_reminder.rb
- spec/jobs/update_induction_tutor_reminder_job_spec.rb
- spec/services/update_induction_tutor_reminder_spec.rb
This will allow us to send lots of reminder emails using the queues without taking up resources on the web instances.
- Deliver the update induction tutor reminder later
- Remove duplicate contact email before sending
- Don't send reminders if school has contact emails
Probably makes sense to go through commit-by-commit
> Create job for sending many induction tutor reminders

- app/views/admin/schools/show.html.erb
It will probably be useful for admins to know whether schools are inside the cohortless dashboard pilot.
This change adds a tag beneath the school's name to indicate if they are. Nothing will be added to schools that aren't in it.
There's some visually hidden text to provide extra context for the tag text.
> Add pilot indicator to admin school overview 🧑‍✈️ 

- app/services/finance/ecf/statement_calculator.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
In ‘fixing’ the adjustments table on one part of the statement, we’ve neglected to remove a calculation elsewhere which accounts for clawback uplift payments. In effect, netting out ‘adjustments’ as the sum of declaration and uplift clawbacks, we’ve created a bug where uplift clawbacks are double counted.
- Ticket: [CPDLP-2158](https://dfedigital.atlassian.net/browse/CPDLP-2158)
- We only count ‘uplift clawbacks’ once 
- The ‘adjustments total’ should be the same at the bottom of the statement as in the summary
[CPDLP-2158]: https://dfedigital.atlassian.net/browse/CPDLP-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2158] Fix double counting uplift clawbacks bug within the uplift fee summary calculation

- app/services/induction/enrol.rb
- spec/components/participant_status_tag_component_spec.rb
- spec/services/induction/enrol_spec.rb
Ticket: [CST-1468](https://dfedigital.atlassian.net/browse/CST-1468)
Enrolling participants or changing them induction programmes does not updates the training_status in the participant's profile record.
Set the participant_profile.training_status to active in the Enrol service class
[CST-1468]: https://dfedigital.atlassian.net/browse/CST-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CST-1468] Activate participant's profile training when enrolling participants

- app/presenters/admin/participant_presenter.rb
- app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: N/A
I want to know the participant's profile status in their admin details page.
This will make it clearer why the service complains when the participant is not active.
- Display the status in the details page
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/951947/234036849-8ce3334b-4f09-4332-b484-e01d870efba7.png)|![image](https://user-images.githubusercontent.com/951947/234036131-eab155df-f4f2-46ea-9c18-dcbe127bbea2.png)|
> Display the participant profile status in the admin pages

- app/views/layouts/_width_container.html.erb
- config/initializers/secure_headers.rb
We lost access to our support inbox which forwards queries to Zendesk. This should provide an alternative route for users.
This PR adds the zendesk widget which appears in the bottom corner of the screen. It also adds some CSP rules to allow us to load Zendesk resources externally.
[Screencast from 2023-04-25 12-11-34.webm](https://user-images.githubusercontent.com/128088/234260514-30a4f549-114d-4eed-bcc9-23534509f432.webm)
> Add Zendesk help widget

- app/controllers/admin/super_users_controller.rb
- app/policies/application_policy.rb
- app/policies/super_user_policy.rb
- app/views/admin/super_users/show.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/migrate/20230228162958_add_super_user_flag_to_admin_profile.rb
- db/new_seeds/base/add_users.rb
- db/new_seeds/scenarios/users/admin_user.rb
- db/schema.rb
- spec/rails_helper.rb
- spec/requests/admin/super_users_spec.rb
It's likely that in the upcoming registration window we'll need to add some _dangerous_ operations that only a subset of administrators can access. This access will be controlled using the `super_user` flag on `AdminProfile`.
- Add super_user flag to admin_profiles
- Add the superuser link to the nav
- Add super users policy and basic controller
> Super users

- app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: N/A
The `@user` is no longer available in the Admin details page of the participants, so the associated emails list is always empty.
- Get the user from the @participant_profile
|![image](https://user-images.githubusercontent.com/951947/234309571-329a2ff4-3d85-43d3-a5b1-0dca13d45cf9.png)|![image](https://user-images.githubusercontent.com/951947/234309617-25847f8f-571e-4605-bc75-5902aa129adf.png)|
> Fix the user associated emails in the participant's admin page

- app/services/induction/amend_participant_cohort.rb
- app/views/admin/participants/change_cohort/edit.html.erb
- config/locales/en.yml
- spec/services/induction/amend_participant_cohort_spec.rb
The current service `Induction::AmendParticipantCohort` to move a participant to one cohort to another on admin only changes the `current_induction_record` of the participant. 
- Ticket: 
- Amend not only the latest induction record but all historical records of the participant, so all of them must be consistently in the same right cohort.
> amend cohort also in historical induction records

- db/legacy_seeds/test_data.rb
- db/new_seeds/base/add_schools_and_local_authorities.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip_keeping_original_training_provider.rb
Fix (most of) the occurrences in seeds where a school cohort with a CIP or FIP choice is created but is missing either or both:
- An `InductionProgramme` for the programme
- The programme set as the `SchoolCohort.default_induction_programme`
> Set default induction programme when creating school cohorts

- app/views/layouts/admin.html.erb
Despite this controller needing an admin profile to see it, [we're seeing crashes in Sentry](https://dfe-teacher-services.sentry.io/issues/4127717407/?project=5748989&referrer=slack) where `current_user.admin_profile` is nil. We should ensure the crash doesn't originate in the template and let the controller handle the permissions accordingly.
> Safely traverse from user to admin profile

- config/routes.rb
Now the office migration has happened the feedback form link is no longer accessible by our UR colleagues. This updates the link to the new Microsoft form for feedback.
> Update feedback form link

- app/forms/schools/add_participants/base_wizard.rb
- Ticket: [CST-1428](https://dfedigital.atlassian.net/browse/CST-1428)
This PR fixes a bug that was recently introduced by the "add and transfer" journey, which prevents NPQs from being added as mentors.
Impersonate a SIT and add a new mentor in a school by providing the email of a NPQ user with no ECF profiles.
[CST-1428]: https://dfedigital.atlassian.net/browse/CST-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix bug preventing NPQs from being added as mentors

- app/forms/schools/add_participants/add_wizard.rb
To upgrade to ruby 3.2.2 we moved to using a new way to call mailers.
We amended this method [here](https://github.com/DFE-Digital/early-careers-framework/pull/2922/commits/728e07431b21158ae37c78bc742cc0e255bfbda2#diff-9956855e8bd74673f70598353bb7c3c2e1cc938a17c2867c670cc6ec969aa13fR333) but looks like its been moved
To resolve https://dfe-teacher-services.sentry.io/issues/4154032056/?project=5748989&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
- Ticket: n/a
Use `with` and deliver later to ensure we are sending mail correctly to avoid errors
Did I miss anything
> Use new way to call mailers using "with" and deliver later

- app/controllers/schools/transfer_out_controller.rb
- app/mailers/admin_mailer.rb
- app/mailers/appropriate_body_profile_mailer.rb
- app/mailers/delivery_partner_profile_mailer.rb
- app/mailers/school_mailer.rb
- app/models/admin_profile.rb
- app/models/appropriate_body_profile.rb
- app/models/delivery_partner_profile.rb
- app/services/induction/send_transfer_notification_emails.rb
- app/services/invite_schools.rb
- app/services/update_induction_tutor_reminder.rb
- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/mailers/admin_mailer_spec.rb
- spec/mailers/appropriate_body_profile_spec.rb
- spec/mailers/delivery_partner_profile_spec.rb
- spec/models/admin_profile_spec.rb
- spec/models/appropriate_body_profile_spec.rb
- spec/models/delivery_partner_profile_spec.rb
- spec/requests/admin/administrators/administrators_spec.rb
- spec/services/induction/send_transfer_notification_emails_spec.rb
- spec/services/invite_schools_spec.rb
- spec/services/update_induction_tutor_reminder_spec.rb
To resolve errors in sentry, use correct way to call mailers and fix tests
- Ticket: n/a
- Use with instead of mailer name, and move name to be called before delivering later
- Access attributes using params in mailer methods themselves
- Fix tests with use `with` or call enqueued with.
I think in some cases we are now missing exact mailer methods to test, esp in feature tests where it's hard to expect a subject to enqueue the mailer. Open to suggestions
> Fix failing mailers

- spec/factories/cohorts.rb
- spec/features/schools/choose_programme/choose_programme_invalid_provider_relationship_spec.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/training_dashboard/manage_schools_spec.rb
- spec/models/cohort_spec.rb
This is a temp fix to unblock failures on main. We need to amend the tests to be cohort agnostic
Today is the 10th of May, and we rolled into next cohort. Until we fix the cypress scenarios push the date to the future to avoid failures
- Ticket: n/a
Amend factory to avoid rolling into cohort 2023.
This is a temp fix and we need to properly fix this soon
Don't judge
> Push cohort rolling into next year to avoid failures

- db/new_seeds/scenarios/participants/mentors/mentor_with_no_ects.rb
- db/new_seeds/scenarios/participants/mentors/mentoring_multiple_ects_with_same_provider.rb
Minor change, add mentor validation data to seed
- Make all the scenario attributes public
- Add with_validation_data call in mentor scenario
> Ensure seeded mentors have validation data

- app/views/admin/participants/details/_show_ecf.html.erb
In response to [this Sentry report](https://dfe-teacher-services.sentry.io/issues/4135058711/?project=5748989&referrer=slack), use policy instead of chaining `#super_user?`
> Switch super_user? check over to policy

- app/controllers/admin/participants/induction_records_controller.rb
- app/policies/induction_record_policy.rb
- app/views/admin/participants/induction_records/edit_preferred_email.html.erb
- app/views/admin/participants/induction_records/show.html.erb
- config/routes.rb
- spec/features/admin/participants/participant_induction_records_spec.rb
- spec/features/admin/participants/participant_steps.rb
- spec/policies/induction_record_policy_spec.rb
- spec/support/features/user_helper.rb
- Ticket: N/A
This PR adds a new Admin page for super users only, to change the preferred identity of induction records.
- Display a link in each Induction Record to change the preferred email
- Add a page to select the new email. All the emails listed are taken from the user's participant identities
1. Visit a ECF participant as a super user
2. Go to Induction Records tab
3. Click the `Change` link in the preferred email row
4. Confirm all the email in the dropdown emails are from the User's participant identities
5. Pick a new email and click `Submit`
6. Confirm the Induction Record's new preferred email
| Screenshots  |
|--------|
| ![image](https://user-images.githubusercontent.com/951947/234601039-8ab9e66b-75b3-45e5-88a6-1f149c4357d4.png ) |
| …
> Change preferred identity

- app/views/schools/choose_programme/show.html.erb
- app/views/schools/cohorts/change_programme.html.erb
- app/views/schools/setup_school_cohort/_change_delivery_partner_submitted.html.erb
- app/views/schools/setup_school_cohort/_change_lead_provider_submitted.html.erb
- app/views/schools/setup_school_cohort/change_provider.html.erb
- app/views/schools/setup_school_cohort/how_will_you_run_training.html.erb
- app/views/start/index.html.erb
- config/routes.rb
Remove references to step by step guidance and update link text where needed
Update links to old gov.uk guidance with new links and link text where needed
> Remove-references-to-step-by-step

- db/migrate/20210302031858_add_cohorts_to_partnerships.rb
Adding papertrail to cohorts caused failures in migrations where versions table was expected but didn't exist
- Ticket: n/a
Ignore papertrail in the particular migration to avoid failures when creating review apps
> Fix failing version table creation in review app

- app/services/dqt_record_check.rb
To allow creating data in sandbox and other envs allow magic dates
- Ticket: n/a
Change check to not run in prod or test
> Allow magic date range everywhere except prod and test

- app/forms/schools/add_participants/add_wizard.rb
- app/mailers/participant_mailer.rb
Seen issues in Sentry regarding a blank template id in a mailer. It appears this is down to a data-driven lookup that doesn't consider a SIT Mentor, so have added guards to prevent it happening.
> Fix blank mailer template issue

- app/services/importers/create_provider_relationships.rb
- spec/services/importers/create_provider_relationships_sepc.rb
- Ticket: CST-1421
We have an Admin page to manually add/edit/remove Provider Relationships, but sometimes we need to create them in bulk.
- Add a Service class to import provider relationships from a CSV file. If a relationship already exists, then it will ignore it to avoid creating duplicates.
> Add a CSV importer to create provider relationships

- spec/services/determine_training_record_state_spec.rb
The spec takes 15 minutes to run. This is causing long integration test times
- Ticket: n/a
Combine expectations in one block to cut times from 15 minutes to around 2 minutes
We might need to revisit later for more improvement
> Improve training record spec run time

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
- Tickets:  CST-1502, CST-1503, CST-1504, CST-1505, CST-1506
This PR implements the mailers for the pilot and launch comms that will be sent out to the schools to ask them to report their training details.
- Add the mailers
- Update the SIT nomination mailer
- Check the mailers are using the correct templates
- Check the mailers are passing all the required placeholders to the templates
- The one off mailers can be sent only via the console
> Add the pilot and launch mailers

- app/services/api/v3/ecf/partnerships_query.rb
- spec/docs/v3/ecf_schools_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/docs/v3/participant_declarations_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/NPQOutcomeAttributes.yml
- Ticket: [CPDLP-2210](https://dfedigital.atlassian.net/browse/CPDLP-2210)
There are some inconsistencies in the API v3 spec that requires improvement, summary.
- add id parameter to schools endpoint
- fix completion date format in docs to match response in outcomes 
- change 2 endpoints docs  from updated_since to filter[updated_since] and any other params requiring filter
- add distinct to partnership endpoint
[CPDLP-2210]: https://dfedigital.atlassian.net/browse/CPDLP-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2210] Make API v3 spec improvements

- app/controllers/schools/participants_controller.rb
- app/forms/schools/add_participants/base_wizard.rb
- app/models/cohort.rb
- app/services/dashboard/mentor.rb
- app/services/dashboard/participants.rb
The service returns an error when the cohort calculated based on the induction start date of a participant is < 2021 due to lack of default Schedule instance for those cohorts.
Place these participants in Cohort.current instead.
> Bug fix: ECT-register an NPQ+1

- app/controllers/api/v1/npq_applications_controller.rb
- app/services/api/v3/delivery_partners_query.rb
- app/services/api/v3/ecf/participants_query.rb
- app/services/api/v3/ecf/partnerships_query.rb
- app/services/api/v3/ecf/schools_query.rb
- app/services/api/v3/ecf/unfunded_mentors_query.rb
- app/services/api/v3/npq_participants_query.rb
- spec/requests/api/v3/delivery_partners_spec.rb
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/requests/api/v3/ecf/partnerships_spec.rb
- spec/requests/api/v3/ecf/schools_spec.rb
- spec/requests/api/v3/ecf/unfunded_mentors_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/services/api/v3/delivery_partners_query_spec.rb
- spec/services/api/v3/ecf/participants_query_spec.rb
- spec/services/api/v3/ecf/partnerships_query_spec.rb
- spec/services/api/v3/ecf/schools_query_spec.rb
- spec/services/api/v3/ecf/unfunded_mentors_query_spec.rb
- spec/services/api/v3/npq_participants_query_spec.rb
- Ticket: [CPDLP-2203](https://dfedigital.atlassian.net/browse/CPDLP-2203)
We would like to sort all endpoints consistently in v3 as currently they are different
Make sorting consistent across v3 endpoints sorting it by created_at: :asc
[CPDLP-2203]: https://dfedigital.atlassian.net/browse/CPDLP-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2203] Update the order on v3 endpoints to created_at asc

- app/forms/participants/participant_validation_form.rb
Exception seen on Sentry.
Do not try and setup permanent cohort when there is no response from dqt
> Do not try and setup permanent cohort when there is no response from dqt

- app/controllers/api/v3/ecf/participants_controller.rb
- app/serializers/api/v3/ecf/participant_serializer.rb
- app/services/api/v3/ecf/participants_query.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- spec/services/api/v3/ecf/participants_query_spec.rb
We currently calculate the latest induction record on each profile which has significant performance implications
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2205
- Paginate users on a small query first to get the user ids
- After pagination is done we join on the resulting query and calculate the users, we also group by user to surface an array of the latest induction record
- After that is calculated we finally perform the outer query for ordering the users
- I couldn't get this to work with the `sort` filter which sorts on further fields
I compared the records from the previous and current query on prod data and they are the same records to make sure we aren't missing anythign
> [CPLD-2205] Improve participant query performance

- app/controllers/admin/participants/change_cohort_controller.rb
- app/policies/participant_profile_policy.rb
- app/views/admin/participants/_cohorts.html.erb
- app/views/admin/participants/cohorts/show.html.erb
- spec/features/admin/participants/participant_steps.rb
- spec/policies/participant_profile_policy_spec.rb
- spec/requests/admin/participants/change_cohort_spec.rb
- Ticket: CST-1520
We want only admins with super user permissions to be able to change the participant's cohort in the admin pages.
- Update the participant_profile_policy
- Update the controller and the views to check if the current user is authorised to edit/update the participant's cohort
Check the
1.  `change cohort` action in the admin -> participant -> cohorts is visible only to admins with super user permissions.
2. non super user admins can't visit the edit cohort path
> Restrict cohort changes to super user admins

- app/controllers/api/api_controller.rb
- config/locales/en.yml
- spec/controllers/concerns/api_pagination_spec.rb
We accept pagination params in the API: `page[page]=1&page[per_page]100`
If an empty value is raised or an invalid value (a string "pageNum" as seen in this [error](https://dfe-teacher-services.sentry.io/issues/4010440797/?referrer=slack)) this is set to zero using `to_i` [here](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/controllers/concerns/api_pagination.rb#L31) and then passed on to set pagination which raises an error: 
```
expected :page >= 1; got 0
```
- Ticket: n/a
To resolve this I was in two minds, either we return page 1 if anyone sets the wrong values using: `[params.dig(:page, :page).to_i, 1].max` or catch this  error and return 422  with an appropriate message
Return bad request when wrong pagination param errors raised, error message has been …
> Fix Invalid pagination error

- app/serializers/api/v3/ecf/participant_serializer.rb
- app/serializers/api/v3/npq_participant_serializer.rb
We are adding extra queries when calculating withdrawals/deferrals per profile
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2211
Calculate the states in memory to avoid too many extra queries. Those are a small number and shouldn't cause any overhead
> [CPLD-2211] Small improvement to NPQ participant endpoints

- app/serializers/api/v3/participant_declaration_serializer.rb
- spec/serializers/api/v3/participant_declaration_serializer_spec.rb
Bad data in sandbox causing API declarations endpoint to fail
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2221
Bad data in test and prod profiles where either the CPD lead provider does not match on induction records, or missing induction records will cause mentor id not to be calculated correctly. Fallback to latest IR and ensure we handle empty induction records just incase
> Account for bad data when retrieving mentor id in declarations

- app/forms/participants/participant_validation_form.rb
- app/forms/schools/add_participants/add_wizard.rb
- app/forms/schools/add_participants/base_wizard.rb
- app/forms/schools/add_participants/wizard_steps/who_to_add_participant_checks.rb
- app/models/participant_profile/npq.rb
- app/services/form_data/add_participant_store.rb
- app/services/mentors/add_profile_to_ect.rb
- app/views/schools/participants/show.html.erb
- spec/factories/school.rb
- spec/factories/seeds/induction_programme_factory.rb
- spec/factories/seeds/pupil_premium_factory.rb
- spec/factories/seeds/school_factory.rb
- spec/forms/schools/add_participants/add_wizard_spec.rb
- spec/forms/schools/add_participants/wizard_steps/date_of_birth_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/nino_step_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/mentors/add_profile_to_ect_spec.rb
- Current Tickets:
- [CST-1486](https://dfedigital.atlassian.net/browse/CST-1486)
- [CST-1485](https://dfedigital.atlassian.net/browse/CST-1485)
- [CST-1487](https://dfedigital.atlassian.net/browse/CST-1487)
- Original Ticket: [CST-1016](https://dfedigital.atlassian.net/browse/CST-1016)
Enable an ECT to become a mentor.  The mentor profile should be exposed to providers with the same ID as the ECT profile.
This means that there will be 2 participants with the same ID in the participants API endpoint, they will however be different types and (presumably) be in a different cohort year.
There are a small number of requests for this coming through support so this is the initial step to help us get those mentors in and available for training (and iron out any issues that we may not have …
> [CST-1486] Add mentors who are ECTs

- db/migrate/20230601102239_update_training_record_states_to_version_2.rb
- db/migrate/20230601102942_add_unique_index_to_training_record_states.rb
- db/schema.rb
- db/views/training_record_states_v02.sql
When creating the training_record_states view the fact that some participants had received multiple 'request_for_details' emails meant there were multiple entries.
This change means we're only selecting the latest 'request_for_details' email for each participant and using that as the basis for working out their overall status.
It will allow us to do [concurrent updates to the materialized view](https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html), meaning queries shouldn't be blocked while it's running.
> Make the id field combinations in `training_record_states` unique

- app/controllers/api/v3/participant_declarations_controller.rb
- app/serializers/api/v3/participant_declaration_serializer.rb
- app/services/api/v3/participant_declarations_query.rb
- spec/serializers/api/v3/participant_declaration_serializer_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
We aren't returning all declarations as in v1/v2 due to an extra `INNER JOIN on induction records`. We would like to also select the correct mentor profile id from declarations from the latest induction record only.
- Ticket: n/a
- Paginate on smaller query for Declarations and then perform further joins on paginated subset
- Change induction record joins to outer joins to paginate correctly, and to include exact number of declarations from v1/v2
- Only get the latest induction record mentor id, and remove `nil` values in the final array
- to allow running distinct use a subquery for the `group_by` and finally select the correct fields and sort in final query
I've run the numbers on the prob backup and declaration number equals v1/v2. We are also slightly faster when returning …
> Fix Participant Declaration V3 query

- app/mailers/school_mailer.rb
- lib/tasks/comms.rake
- spec/mailers/school_mailer_spec.rb
- Ticket: CST-1551
We need a one off task to send the comms to the pilot schools.
- Refactor the mailers to simplify them and associate them with the correct objects
- Add a rake task to send the pilot comms. It reads a list of schools from a CSV file, adds them in the pilot and sends the comms either to the school's SIT or GIAS primary contact.
> Add a rake task to send the comms to the pilot schools

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1531)
Both of these templates in Notify are hard-coded for the 2022-23 academic year. This PR makes these a placeholder provided by the mailer.
I have duplicated the 2 templates in Notify for the emails and referenced them from the existing code to prevent out-of-sync issues happening before the code is deployed [here](https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/bfc43b20-922f-4323-8775-a6e05f06e24a) and [here](https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/123eb3e6-401f-4c1d-b81e-113cb6580fc9)
Added `academic_year` placeholders to the duplicate Notify templates
Derived the correct `academic_year` in the mailers
Tests from …
> [CST-1531] Update emails that might get trigger during the pilot

- app/controllers/schools/cohort_setup_controller.rb
- app/forms/schools/cohorts/setup_wizard/success.rb
- app/forms/wizard.rb
- app/mailers/school_mailer.rb
- spec/forms/schools/cohorts/setup_wizard_spec.rb
- spec/mailers/school_mailer_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1550)
Send out an email once a SIT has made their choice for 2023 cohort for pilot schools.  The email is delayed for 3 hours to give the SIT the opportunity to use the service once their choice has been made.
Add a new mailer
Trigger mailer in the cohort setup wizard once the cohort choice is made. Does not trigger if No ECTs is chosen.
Example test email from Notify
> [CST-1550] setup survey comms

- app/models/training_record_state.rb
Concurrently refresh view to avoid locking tables
- Ticket: n/a
Add concurrent to refresh command on view
> Add concurrently to refresh state view to avoid locking tables

- app/serializers/api/v3/participant_declaration_serializer.rb
- app/services/api/participant_declarations/index.rb
- app/services/api/v3/participant_declarations_query.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
Participant declaration queries are causing db load, improve them in all versions of the API
- Ticket: n/a
- Use OR instead of union
- Only select IDs in v3 to improve performance
- Eager load NPQ associations to avoid n+1s in v3
Tested before and after numbers for v1/v2/v3 and they match up
also tested filters for all endpoints
> Improve Participant declaration queries

- app/controllers/schools/base_controller.rb
Schools that didn't have 2022 setup get an error in the redirection to set it up, now that 2023 registration is open for pilot schools and we have become cohortless (so the cohort year is not being specified by the params)
- Ticket: 
- determine the cohort to setup based in the latest manageable cohort of the school if not cohort_id is specified by the params in the request.
> redirect schools that didn't set the previous cohort to set it up

- db/new_seeds/scenarios/participants/induction_coordinator.rb
There were 2 schools still being created via the scenario seeds that had a school cohort with a choice of FIP or CIP, but no induction programme. This PR fixes this.
`bundle exec rails db:seed:replant`
Then enter this in the `rails console`
`SchoolCohort.full_induction_programme.where(default_induction_programme: nil).count`
It should return `0`
`SchoolCohort.core_induction_programme.where(default_induction_programme: nil).count`
It should also return `0`
> [BugFix] Fix last of the missing induction programmes in scenarios

- app/services/api/v3/ecf/participants_query.rb
- spec/services/api/v3/ecf/participants_query_spec.rb
If we don't order on the initial pagination query, we will get any random first 100 users, and then order them. This avoids getting random users first and then sorting
- Ticket: n/a
Add ordering on the pagination query using users
> Order V3 Participant query pagination by user

- app/presenters/admin/participant_presenter.rb
- app/views/admin/participants/details/_show_ecf.html.erb
- app/views/admin/participants/statuses/show.html.erb
Moves participant status and training status to the statuses page so that it is easier to see all statuses on one page
> Patch show relevant training status

- app/services/induction/amend_participant_cohort.rb
- config/locales/en.yml
- spec/services/induction/amend_participant_cohort_spec.rb
[Jira-CPDLP-1996](https://dfedigital.atlassian.net/browse/CPDLP-1996)
We currently allow a participant to transfer to another cohort as long as they don't have any billable/submitted declarations **in the current cohort window**. This means a participant can transfer if they have billable/submitted declarations in another cohort, and this has caused issues.
Prevent participant cohort transfer if billable/submitted declarations exist regardless of date/cohort the declarations apply for.
We have similar logic around transferring a participant between schools. I'm unsure if this should also be updated to prevent transferring between schools if billable/submitted declarations exist in another cohort:
https://github.com/DFE-Digital/early-careers-framework/blob/508c00536d170b60644a3fa0869c662247 …
> Prevent cohort transfer if any billable/submitted declarations exist

- app/components/admin/participants/audit_trail_component.html.erb
- app/components/admin/participants/audit_trail_component.rb
- app/components/admin/participants/audit_trail_item_component.html.erb
- app/components/admin/participants/audit_trail_item_component.rb
- app/services/participants/history_builder.rb
- app/views/admin/participants/change_log/show.html.erb
- spec/services/participants/history_builder_spec.rb
- spec/support/with_support_for_ect_examples.rb
- Ticket: fix change log page broken due to missing user entities
use find_by when looking for entities from history rather than find which raises exceptions
> Handle deleted record entities in participant change log

- app/services/api/v3/delivery_partners_query.rb
- app/services/api/v3/ecf/partnerships_query.rb
- spec/services/api/v3/delivery_partners_query_spec.rb
- spec/services/api/v3/ecf/partnerships_query_spec.rb
If a `cohort` filter is not supplied we should default to filtering out cohorts earlier than 2021. Due to a bug in these query models if `cohort` was not specified we would return all models irrespective of cohort.
Default cohort filtering to exclude pre-2021 cohorts and add test coverage.
> Default cohort filtering to exclude pre-2021 cohorts

- app/controllers/api/v1/npq_applications_controller.rb
- app/controllers/api/v3/npq_applications_controller.rb
- app/services/api/v3/npq_applications_query.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/services/api/v3/npq_applications_query_spec.rb
[Jira-CPDLP-2209](https://dfedigital.atlassian.net/browse/CPDLP-2209)
The API v3 schema surfaces the ability to filter NPQ applications by `participant_id`, however we have not yet implemented the functionality.
We also want to always default the sorting of NPQ applications in the v1 API as the `sort` parameter is not supported.
- Always sort v1 applications by created_at
- Allow filtering of applications by participant_id
Test added to v1 request specs to cover default sorting.
Migrates to a query model for consistency with other v3 endpoints.
Request test added for `participant_id` filtering, but we may want to clean up these controller tests at a later date so we're not over-testing the query models. It looks like there's also scope to DRY up the query models with a concern similar to …
> Allow filtering of NPQ applications on participant_id

- terraform/app/modules/statuscake/main.tf
- terraform/app/modules/statuscake/variables.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
- terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_production.tfvars.json
- terraform/workspace-variables/production.tfvars
Apex domains are not automatically renewed by Azure front door. We should monitor them via statuscake.
- Ticket: https://trello.com/c/2pEuVuNa/773-monitor-front-door-apex-domain-expiration-dates
Add a new check for statuscake to monitor SSL expiry.
> add Statuscake alert for SSL expiry date

- app/components/admin/schools/cohorts/cip_info.html.erb
- app/components/admin/schools/cohorts/fip_info.html.erb
- app/components/admin/schools/cohorts/other_info.html.erb
- app/components/admin/schools/cohorts/other_info.rb
- config/locales/admin/induction_choice_form.yml
- spec/components/admin/schools/cohorts/cip_info_spec.rb
- spec/components/admin/schools/cohorts/cohort_spec.rb
- spec/components/admin/schools/cohorts/fip_info_spec.rb
- spec/components/admin/schools/cohorts/other_info_spec.rb
- Ticket: https://trello.com/c/kbbNZm8w/44-improve-induction-programme-row-copy-on-cohort-tab-schools-page
Update the copy for the ‘Induction programme’ row, on the cohorts tab to change to "Training programme".
Update values to:
* Working with a DfE-funded provider
* Using DfE-accredited materials
* Designing their own training
* Not assigned
> Improve row copy on cohort tab, schools page

- app/services/induction/change_programme.rb
- spec/services/induction/change_programme_spec.rb
- Ticket: CST-1622
There are a few bugs when using the `Induction::ChangeProgramme` with mentors:
1. When mentors are moving schools, it will remove them from the new school's mentor pool
2. When the mentors are not moving schools, it will remove them from the school's mentor pool and will also remove them from their mentees by updating their induction records.
1. Store the participant_profile.current_induction_record before reuse it, so it always returns the correct induction record
2. Create an additional check to determine if the mentor is actually moving school
> [CST-1622] Fix moving mentors with Induction::ChangeProgramme

- app/components/admin/participants/audit_trail_item_component.rb
We saw a crash on Sentry caused by the wrong accessor, `#email_address` being called on a `User`. It should be `#email`.
> Call email on user instead of email_address

- app/models/participant_declaration.rb
- app/models/user.rb
- app/serializers/api/v3/participant_declaration_serializer.rb
- app/services/api/v3/participant_declarations_query.rb
- db/migrate/20230612140808_add_mentor_user_id_to_participant_declarations.rb
- db/migrate/20230613072254_validate_foreign_key_on_participant_declarations_to_mentor_users.rb
- db/schema.rb
- spec/models/participant_declaration_spec.rb
- spec/models/participant_profile/mentor_spec.rb
- spec/models/user_spec.rb
- spec/serializers/api/v3/participant_declaration_serializer_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
[Jira-2253](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2253)
In order to optimise and simplify queries that reference a declaration `mentor_id` we are going to store the value on the
model directly. We will be populating this when the declaration is created and backfill existing declarations.
- Add `mentor_user_id` to `ParticipantDeclaration`
In the `ParticipantDeclarationQuery` we compute the `mentor_user_id` as an optimisation; to avoid a clash with the
new attribute name (as both `ParticipantDeclaration` and query results can filter through the serializer) the computed
attribute has been renamed `transient_mentor_user_id` and will be removed in a future commit.
Also adds test coverage to the `Mentor` model.
> Add mentor_user_id to ParticipantDeclaration

- db/new_seeds/scenarios/participants/training_record_states.rb
- spec/cypress/app_commands/scenarios/lead_provider_with_delivery_partners.rb
- spec/factories/cohorts.rb
- spec/features/schools/add_appropriate_body_spec.rb
- spec/features/schools/choose_programme/choose_programme_invalid_provider_relationship_spec.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/training_dashboard/manage_schools_spec.rb
When the next cohort rolls in, we get failures in the specs. Fix those not to rely on the current cohort start date
- Ticket: n/a
- Amend existing cohort factory to be in the past and set specific specs to that date
- Amend feature setup to always point at specific cohort to avoid failures, as the cohort year is set up in the query param
- Amend training state scenarios to look into the future rather than the cohort start to avoid failures
Need to merge before tomorrow when the cohort year rolls again 😅
> Fix rolling into next cohort year failures

- app/forms/admin/school_transfer_form.rb
- spec/forms/admin/school_transfer_form_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-1626
When attempting to complete the form without an induction record the user will encounter an unhandled error.
This adds that requirement as a validation check so the user is informed why they are not able to complete the form.
1. Visit /admin/participants/:participant_id/school for a participant without an induction record
2. Click Transfer to Another School
3. Proceed and attempt to complete the Start Date form.
4. The app will encounter an error due to a missing induction record (currently suppressed by CST-1625)
The user is shown an error message that explains why the user cannot be transferred.
Here's a screenshot from the seed data triggering the error page now that it's been fixed:
> [CST-1626] Handle lack of induction record in school transfer form gracefully

- app/controllers/admin/participants/school_transfer_controller.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-1625
When attempting to complete the School Transfer form in a way that triggers an unhandled error in the validation the controller attempts to redirect/render twice, triggering a 500 error that suppresses the actual error from being reported to Sentry and is not handled gracefully for the user.
Move the error handling onto the methods calling `step_valid?` so that the error handling properly takes over flow control.
1. Visit /admin/participants/:participant_id/school for a participant where validation will encounter an unhandled error, the best way to do this is to visit for a participant without an induction record
2. Click Transfer to Another School
3. Proceed and attempt to complete the form.
4. The app will encounter a …
> [CST-1625] Handle errors in school transfer gracefully

- app/controllers/admin/participants_controller.rb
- app/controllers/concerns/admin/participants/find_induction_records.rb
- app/presenters/admin/participant_presenter.rb
- app/views/admin/participants/statuses/show.html.erb
- spec/presenters/admin/participant_presenter_spec.rb
- spec/requests/admin/participants/school_spec.rb
- spec/requests/admin/participants/statuses_spec.rb
- Ticket:  https://dfedigital.atlassian.net/browse/CST-1624
In several places there is the assumption of at least one induction record for a participant profile and even when safe navigation is used it is assumed that a nil value is acceptable.
Removes the assumption that one-to-many induction_record relations will always return at least one value and return an empty array if the result would be nil.
Sends fallback text to `govuk_tag` when induction records are missing.
1. Visit /admin/participants/:participant_id/school for a participant without an induction record
2. The above page will produce a 500 error
1. Visit /admin/participants/:participant_id/statuses for a participant without an induction record
2. The above page will produce a 500 error
The above pages render correctly for …
> [CST-1624] Ensure safe induction record navigation

- app/jobs/participant_outcomes/stream_big_query_job.rb
- spec/jobs/participant_outcomes/stream_big_query_job_spec.rb
- Ticket: [CPDLP-2260](https://dfedigital.atlassian.net/browse/CPDLP-2260)
We’d like to also monitor any errors that could stem from TRNs being missing or errors returned from the TRA API.
Add two new fields to the existing Big query streaming job ParticipantOutcomes::StreamBigQueryJob
- qualified_teachers_api_request_successful: boolean
- sent_to_qualified_teachers_api_at: timestamp
**These new fields need to be created in Big query tables first.**
[CPDLP-2260]: https://dfedigital.atlassian.net/browse/CPDLP-2260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2260] Add fields to participant outcomes big query stream job

- app/models/induction_record.rb
- app/services/record_declaration.rb
- spec/models/induction_record_spec.rb
- spec/services/induction/find_by_spec.rb
- spec/services/record_declaration_spec.rb
[Jira-2253](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2253)
The `ParticipantDeclaration` has a new foreign key `mentor_user_id` that is currently unpopulated. We want to
populate this with the induction record relative to the `declaration_date` at the time of creation.
- Populate mentor_user_id for new declarations
- Clarify induction record date edge cases
The field is not yet referenced/read anywhere. We will backfill the existing declarations in a separate PR.
We have induction records in the database that are in an invalid/unexpected state. Until we are able to clean up the
data and ensure consistency we need to make sure the latest induction record logic is expected/documented.
Update `InductionRecord` scopes to prioritise records …
> Populate mentor_user_id for new ParticipantDeclarations

- lib/backfill_mentor_user_id.rb
- lib/tasks/backfill_mentor_user_id.rake
- spec/lib/backfill_mentor_user_id_spec.rb
[Jira-2253](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2253)
We have a new `mentor_user_id` attribute on `ParticipantDeclaration` that is currently only being populated for new declarations. We want to backfill all the ECF declarations so that we can start referencing the `mentor_user_id` field.
- Add rake task to backfill mentor_user_id on ParticipantDeclaration
I thought about doing a rake task that spawns jobs for each of the update operations, but assuming there aren't _loads_ of declarations and updating them is a relatively short operation then doing it from the dev console should be fine/less complex.
Example usage:
Dry run: `rake backfill:mentor_user_id`
Run (updates records): `rake 'backfill:mentor_user_id[false]'`
> Backfill mentor_user_id on ParticipantDeclaration

- app/services/qualified_teachers_api_sender.rb
- Ticket: 
We need to trigger the outcomes callbacks when updating those records in order to sync those with big query correctly.
Trigger outcomes callbacks when sending it to TRA.. so use `update` instead of `update_column` which will trigger callbacks.
> Trigger outcomes callbacks when sending it to TRA

- app/services/feature_flag.rb
- config/routes.rb
- spec/docs/v3/ecf_delivery_partners_spec.rb
- spec/docs/v3/ecf_participant_transfers_spec.rb
- spec/docs/v3/ecf_participants_spec.rb
- spec/docs/v3/ecf_partnerships_spec.rb
- spec/docs/v3/ecf_schools_spec.rb
- spec/docs/v3/ecf_unfunded_mentors_spec.rb
- spec/docs/v3/npq_applications_spec.rb
- spec/docs/v3/npq_participant_outcomes_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/docs/v3/participant_declarations_spec.rb
- spec/docs/v3/statements_spec.rb
- spec/requests/api/v3/delivery_partners_spec.rb
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/requests/api/v3/ecf/partnerships_spec.rb
- spec/requests/api/v3/ecf/schools_spec.rb
- spec/requests/api/v3/ecf/transfers_spec.rb
- spec/requests/api/v3/ecf/unfunded_mentors_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/requests/api/v3/participant_outcome_spec.rb
- spec/requests/api/v3/provider_outcomes_spec.rb
- spec/requests/api/v3/statements_spec.rb
- spec/spec_helper.rb
API v3 has been released, we no longer need the API v3 flag
- Ticket: n/a
- Remove feature flag
- Remove tag to disable api v3 specs
- Remove feature flag from specs
🎉
> Remove API v3 feature flag

- app/jobs/npq/stream_big_query_enrollment_job.rb
- app/jobs/npq/stream_big_query_profile_job.rb
- app/jobs/participant_outcomes/stream_api_requests_to_big_query_job.rb
- app/jobs/participant_outcomes/stream_big_query_job.rb
- spec/jobs/npq/stream_big_query_enrollment_job_spec.rb
- spec/jobs/npq/stream_big_query_profile_job_spec.rb
- spec/jobs/participant_outcomes/stream_api_requests_to_big_query_job_spec.rb
- spec/jobs/participant_outcomes/stream_big_query_job_spec.rb
We are attempting to send outcomes to BQ in other environments where no table or dataset are setup, as we only have tables in sandbox and production. This is causing large logs of errors in dev as the cron job runs every ten minutes.
- Ticket: n/a
- Allow table lookup when setting BQ table
- Only stream BQ updates if the BQ table exists
I've checked manually in sandbox and dev if this will work and results were good
> Only send Big Query updates if table exists for environment

- app/services/record_declaration.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- Ticket: [CPDLP-2222](https://dfedigital.atlassian.net/browse/CPDLP-2222)
For some reason we're not recording `evidence_held` value submitted in request body for ECF retained and completed declarations.
Forward fix so future ECF declarations record `evidence_held` in declarations table.
[CPDLP-2222]: https://dfedigital.atlassian.net/browse/CPDLP-2222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2222] Record given evidence_held in declarations table

- app/helpers/school_breadcrumbs_helper.rb
- spec/helpers/school_breadcrumbs_helper_spec.rb
The '>' is added by the component and not needed in the markup.
> Remove '<' from Manage your schools breadcrumb

- app/controllers/admin/administrators/administrators_controller.rb
- app/controllers/admin/induction_coordinators_controller.rb
- app/controllers/admin/suppliers/lead_provider_users_controller.rb
- spec/requests/admin/administrators/administrators_spec.rb
- spec/requests/admin/induction_coordinators_spec.rb
- spec/requests/admin/lead_providers/lead_provider_users_spec.rb
We encountered a bug when updating admin profiles because the success message was set inconsistently. We used two approaches, adding the `:notice` param onto `redirect_to`, and setting the flash manually via `set_success_message`.
We use `set_success_message` in more places and it's a bit more flexible, so this change switches the remaining notice variants over.
> Replace flash notice with flash success

- app/mailers/school_mailer.rb
- lib/tasks/comms.rake
- Ticket: CST-1654
The launch comms have been scheduled to be sent to schools with SITs and to schools without SITs individually and in batches.
The average batch is 5,000 schools.
- Add a rake tasks for each launch comms
> [CST-1654] Add the launch comms tasks

- app/services/change_schedule.rb
- config/locales/en.yml
- spec/services/change_schedule_spec.rb
[Jira-2095](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2095)
We currently allow NPQ providers to change cohort. Going forward we want to restrict this action so that they can only change cohort if:
- They are changing to an earlier cohort year
- There are no submitted/eigible/payable/paid declarations
- Prevent cohort change for NPQ providers
> Prevent cohort change for NPQ providers

- app/views/start/index.html.erb
- app/views/users/sessions/new.html.erb
Conversations with the support team have revealed that users are getting in touch with them to request access, without realising that they can get access by requesting an link be sent to their school email address.
This is possibly because the link to request access was only available on the Sign in page, and wasn't signposted from the service start page.
This PR adds the link to the service start page.
A missing back link is also added to the Sign in page, and the link text made consistent with the new link on the start page.
| Before | After|
|---|---|
| ![before](https://github.com/DFE-Digital/early-careers-framework/assets/30665/c6baed96-d0dc-4eaf-b5da-a11bc69aea9a) | ![after](https://github.com/DFE-Digital/early-careers-framework/assets/30665/1e338283-dc69-47a7-a4d6-e75ef0abfc8e) |
| …
> Add request access link to the start page

- app/views/schools/dashboard/_school_cohort_details.html.erb
- app/views/schools/participants/show.html.erb
- spec/features/schools/participant_dashboard/manage_cip_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
* Lead provider and delivery partner hidden for CIP
- Ticket: CST-1673, CST-1674
* When CIP:
* Added **Programme** detail line to the participant dashboard
* Removed **Lead provider** and **Delivery partner** detail lines
* **Material supplier** detail line moved above the **appropriate body** one
> Display CIP materials on the participant dashboard

- app/services/api/v3/concerns/filter_cohorts.rb
- app/services/api/v3/concerns/filter_updated_since.rb
- app/services/api/v3/delivery_partners_query.rb
- app/services/api/v3/ecf/participants_query.rb
- app/services/api/v3/ecf/partnerships_query.rb
- app/services/api/v3/ecf/schools_query.rb
- app/services/api/v3/ecf/transfers_query.rb
- app/services/api/v3/ecf/unfunded_mentors_query.rb
- app/services/api/v3/finance/statements_query.rb
- app/services/api/v3/npq_applications_query.rb
- app/services/api/v3/npq_participants_query.rb
- app/services/api/v3/participant_declarations_query.rb
[Jira-2302](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2302)
The v3 query classes duplicate some common logic around filtering. We want to remove the duplication to make the code easier to maintain.
- DRY up v3 query classes
> DRY up v3 query classes

- app/controllers/admin/home_controller.rb
- app/views/admin/home/show.html.erb
This adds a second table to the Admin overview page, which gives the numbers of participants registered for the 2023-2024 academic year, broken down by participant type (early career teachers and mentors).
- Ticket: [Add the numbers of ECTs and mentors registered for 2023-2024 to the admin overview page](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?selectedIssue=CST-1713)
> Add table for participants to Admin overview page

- db/migrate/20230705152210_remove_accidental_columns_from_versions.rb
This migration is failing in envs the column does not exist in. Add exists true to ensure migration passes if column doesn't exist
- Ticket: n/a
Check if column exists before running remove column migration
> Check if accidental column exists before removing

- app/models/user.rb
- db/migrate/20230627093843_add_archived_email_to_users.rb
- db/migrate/20230704120942_add_archived_at_to_user.rb
- db/schema.rb
- spec/models/user_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDNPQ-1181
Part 1 of the dedup proposal - only for single user, but it would allow us to deduplicate currently affected users. The part 2 will be rake task to deduplicate user a nightly basis.
> Deduplicate single user

- app/models/email.rb
- spec/models/email_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1731)
Prevent error being raised when the association object is `nil`. This could happen if a school changed their SIT between the mail being queued and receiving the Notify callback and the Email was associated with the `SchoolInductionCoordinatorProfile` for example.
> [CST-1731] - Prevent error in Notify callback when association object is now nil

- app/models/partnership_csv_upload.rb
- spec/models/partnership_csv_upload_spec.rb
Some of the PartnershipCsvUpload records in production have malformed data in the uploaded_urns array. There are strange unicode sequences, leading and trailing spaces and values with commas.
This change attempts to clean them up and improve the test coverage for the process.
> Make setting uploaded_urns more robust

- app/views/schools/cohort_setup/_change_delivery_partner_submitted.html.erb
- app/views/schools/cohort_setup/_change_lead_provider_submitted.html.erb
- Ticket: CST-1724
Hardcoded academic year replaced by `cohort.description`
> Show the correct academic year in confirmation pages when changing lead provider or delivery partner

- app/views/pages/what_each_person_does.html.erb
- spec/requests/pages_spec.rb
- Ticket: N/A
The "What each person does" page tries to render the `shared/roles` partial and fails with 500 error.
- Update the partial name
- Add spec
Visit the `/pages/what-each-person-does`
> Fix the What each person does page

- app/mailers/school_mailer.rb
- lib/tasks/comms.rake
- spec/mailers/school_mailer_spec.rb
The GIAS contact should is now sent to the `Choose how to continue` page, where they can opt out, without having to nominate an SIT.
> Change the GIAS nomination link in the launch comms

- config/initializers/cypress_on_rails.rb
- Ticket: N/A
We get warning messages about the deprecated cypress config `cypress_folder`. 
- Replace `cypress_folder` with `install_folder`
> Update deprecated cypress config

- app/forms/finance/npq/change_training_status_form.rb
- app/services/defer_participant.rb
- config/locales/en.yml
- docs/source/release-notes.html.md
- spec/forms/finance/npq/change_training_status_form_spec.rb
- spec/services/defer_participant_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1928
* Added validation to `DeferParticipant` service.
* Added validation to `Finance::NPQ::ChangeTrainingStatusForm`
* Updated release notes.
> [CPDLP-1928] Ensure NPQ users cannot defer an NPQ participant that has no declarations

- lib/tasks/comms.rake
- Ticket: N/A
This PR will allow us to resend comms that fail.
Some of the reasons we would need to do that are:
- We hit Rate Limit on the Notify service which will return "failed" status
- Notify was temp unable to send an email
- Skip only schools that the emails are pending or delivered
> Allow to resend failed comms

- app/controllers/api/v1/provider_outcomes_controller.rb
- app/services/api/v1/participant_outcomes_query.rb
- config/locales/en.yml
- docs/source/release-notes.html.md
- spec/docs/v1/participant_outcomes_spec.rb
- spec/docs/v2/participant_outcomes_spec.rb
- spec/docs/v3/npq_participant_outcomes_spec.rb
- spec/requests/api/v1/provider_outcomes_spec.rb
- spec/requests/api/v2/provider_outcomes_spec.rb
- spec/requests/api/v3/provider_outcomes_spec.rb
- spec/services/api/v1/participant_outcomes_query_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NPQOutcomeFilter.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/NPQOutcomeFilter.yml
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/NPQOutcomeFilter.yml
[Jira-2145](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2145)
We want to allow providers to filter NPQ outcomes by the `created_at` date.
- Allow filtering NPW outcomes by `created_at`
Update query to support filtering by `created_since` and permit filter parameters in controller.
> Allow filtering NPQ outcomes by created_at

- app/controllers/api/api_controller.rb
- app/controllers/api/errors/invalid_training_status_error.rb
- app/controllers/api/v3/ecf/participants_controller.rb
- app/controllers/api/v3/npq_participants_controller.rb
- app/services/api/v3/concerns/filter_training_status.rb
- app/services/api/v3/ecf/participants_query.rb
- app/services/api/v3/npq_participants_query.rb
- config/locales/en.yml
- docs/source/release-notes.html.md
- spec/docs/v3/ecf_participants_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/services/api/v3/ecf/participants_query_spec.rb
- spec/services/api/v3/npq_participants_query_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFParticipantFilter.yml
- swagger/v3/component_schemas/NPQParticipantFilter.yml
[Jira-2298](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2298)
We want to allow filtering of NPQ and ECF participants by `training_status` in the v3 API.
- Allow filtering NPQ/ECF participants by training_status
Add concern to support `training_status` filtering. Update query models to filter when present and accept `training_status` param in controller.
Update documentation with new filter usage.
> Allow filtering NPQ/ECF participants by training_status

- db/schema.rb
This line flip flops depending on who runs the migration. For most of the team, this is the version that's output by running `rails db:migrate` on a clean repo.
> Change the `cpd_lead_provider_id` index format back to default

- app/controllers/schools/dashboard_controller.rb
A participant in user research had 37 schools listed across 4 pages.
Having more schools per page would make it faster for them to locate a specific school.
> Increase number of schools shown per page

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1763)
Adds new mailer for chaser email to SIT to remind them to add participants
Adds new mailer for chaser to SIT to remind them to assign mentors to ECTs
> [CST-1763] Add new chaser emails for SITs

- app/forms/choose_role_form.rb
- spec/forms/choose_role_form_spec.rb
- spec/requests/users/sessions_spec.rb
- spec/support/features/pages/admin_support/admin_support_portal.rb
When signing in as an admin, it now makes sense to start on the Overview page.
> Redirect to admin overview path when signing in
