DFE-Digital/early-careers-framework

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/schools_controller.rb, app/models/school.rb, app/views/schools/new.html.erb, app/views/schools/show.html.erb, config/routes.rb, db/migrate/20201116191346_create_schools.rb, db/schema.rb, spec/requests/schools_request_spec.rb
Not one to be merged in, but just learning how the formbuilder works.
Added a toy model and controller, just to be able to play with the form. The validation isn't quite right (if the date is invalid, the other fields are blanked), but that wasn't what I was focussing on here.
The view for new is the big interest here, as that's where all the formbuilder goodness is.
=> ECF-NONE: Add govuk-design-system-formbuilder and try it out

Dockerfile, Gemfile, Gemfile.lock, README.md, config/database.yml, config/webpacker.yml, docker-compose.override.yml, docker-compose.yml, package.json, yarn.lock
We want to be able to put our project in a docker container so that it's easier to set up locally and deploy. 
I copy-pasted a lot of setup (`Dockerfile` and `docker-compose`) from a much more mature repo (https://github.com/DFE-Digital/apply-for-teacher-training). Renamed a few things, removed a few things (worker? clock? might want to add them later when we have workers and jobs). 
And then I spent a while getting the build to pass and everything to work locally and prints fewer warnings. Changes around `gemfile` and `package.json` are for that purpose. 
I kept Redis image in, but if we want it out for now I'm happy to remove it. Other than that, I am not too happy about moving `listen` gem, might have a go at bringing it back to dev dependencies tomorrow. 
I would not (if you were …
=> ECF-28: Dockerise project

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
Adding some dependencies from #5. We don't want to merge that, so splitting out the useful bits here
Add:
- govuk_design_system_formbuilder
- rails-controller-testing
- wdm
None, really
=> ECF-30: Add formbuilder

.github/workflows/lint.yml, .rubocop.yml, Gemfile, Gemfile.lock, README.md, Rakefile, app/models/lead_provider.rb, app/models/network.rb, app/models/partnership.rb, app/models/school.rb, db/migrate/20201125151816_create_schools.rb, db/migrate/20201125153432_create_networks.rb, db/migrate/20201125154423_add_network_to_schools.rb, db/migrate/20201125155711_create_lead_providers.rb, db/migrate/20201125155842_create_partnerships.rb, db/schema.rb, db/seeds.rb, spec/factories/lead_provider.rb, spec/factories/network.rb, spec/factories/partnership.rb, spec/factories/school.rb, spec/models/lead_provider_spec.rb, spec/models/network_spec.rb, spec/models/partnership_spec.rb, spec/models/school_spec.rb, spec/rails_helper.rb, spec/support/factory_bot.rb
We want a simple data model to be able to do more work on it. In particular we need schools, lead providers and partnerships. We also added networks just because it is easy. 
Add migrations and models for the objects mentioned above.
Add factory bot.
Add tests for the models and relations between them.
Feel free to go commit by commit.
I'm not quite sure what the convention is for naming boolean methods (`confirmed?` vs `is_confirmed?`) and methods changing state of an object (`confirm` vs `confirm!`). Feel free to offer advice :)
=> Add migrations and data model

.dockerignore, .gitignore, app/controllers/application_controller.rb, config/routes.rb, documentation/debugging_in_govpaas.md, documentation/terraform.md, lib/tasks/cloudfoundry.rake, lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake, manifest.yml, terraform/app/modules/paas/data.tf, terraform/app/modules/paas/main.tf, terraform/app/modules/paas/outputs.tf, terraform/app/modules/paas/variables.tf, terraform/app/modules/paas/versions.tf, terraform/app/output.tf, terraform/app/terraform.tf, terraform/app/variables.tf, terraform/app/versions.tf, terraform/workspace-variables/dev.tfvars, terraform/workspace-variables/dev_app_env.yml, yarn.lock
We are using terraform for infrastructure management, using the cloudfoundry provider to deploy to GovPaaS.
Mostly setting up terraform to deploy a container image from dockerhub. Also set up a backing DB. A few extra tasks around this, like rake tasks and a healthcheck endpoint.
A lot of this was "borrowed" from teaching vacancies
=> ECF-TECH-19: terraform deploy to dev

.dockerignore, .github/workflows/deploy.yml, .github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_staging.yml, .github/workflows/destroy.yml, .github/workflows/lint.yml, .github/workflows/review.yml, README.md, config/environments/deployed_development.rb, config/environments/staging.rb, terraform/workspace-variables/review.tfvars, terraform/workspace-variables/review_app_env.yml
A lot of this was inspired by teaching vacancies...
- Add a new set of terraform config for review apps
- Add a workflow to create pr review apps
- Add a workflow to destroy pr review apps
Quite a lot here, shout if you have any questions
=> ECF-TECH-35: review apps

.env.template, .github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_staging.yml, .github/workflows/review.yml, Dockerfile, Gemfile.lock, terraform/app/modules/paas/variables.tf
Now we have child jobs for deployment, we don't get a red cross when something fails. Bring back the red cross!
Check the outcome of the child jobs, fail unless they are successful
=> ECF-TECH-35: Make it obvious if a child job fails

app/views/layouts/application.html.erb, config/initializers/devise.rb, spec/rails_helper.rb, spec/requests/users/logout_spec.rb
Implement user logout
Code changes to enable users to log out
=> ECF-78 Implement logout

config/initializers/add_frozen_string_literal_comment.rb
If we're going to add the comment to the top of every file, lets have rails do it for us when generating files
=> Automatically add frozen string literal comment at top of generated files

app/controllers/admin_dashboard_controller.rb, app/controllers/users/sessions_controller.rb, app/helpers/application_helper.rb, app/models/admin_profile.rb, app/models/user.rb, app/views/admin_dashboard/show.html.erb, config/routes.rb, db/migrate/20210105230905_create_admin_profiles.rb, db/schema.rb, db/seeds.rb, spec/factories/admin_profiles.rb, spec/helpers/application_helper_spec.rb, spec/models/admin_profile_spec.rb, spec/models/user_spec.rb, spec/requests/users/sessions_spec.rb
A DfE administrator can log in with their email address
They can see an administrator dashboard on successful login
=> ECF-97 DFE admin login

terraform/app/modules/paas/versions.tf, terraform/app/versions.tf
=> ECF-tech-41: Upgrade terraform cloudfoundry provider

.rubocop.yml, app/views/core_induction_programme/years/show.html.erb, app/webpacker/styles/app_task_list.scss, db/migrate/20210122115553_add_version_to_cip_content.rb, db/schema.rb, db/seeds.rb, db/seeds/cip_ambition.rb, db/seeds/cip_edt.rb, db/seeds/cip_teachfirst.rb, db/seeds/cip_ucl.rb, db/seeds/dummy_structures.rb
We got a go-ahead from important people to put the content on github, so it's time to commit and load it.
Split the seeding file into several - one per CIP provider.
Add version to the year-module-lesson models - so that we can have an easier time modifying the content. When we make changes to the content, we would simply bump the version and next time seed is run it will update them. Not sure how that will work (if at all) on the dev app, but on review app it should work just fine.
I would not bother too much with reading through the seeding files - one thing they are not is pretty. Playing around with review app might be a better idea. There are some issues (like titles of some years not being what is expected), but I imagine we will fix them in due time through content review and …
=> ECF-EL-73: Add cip content

Dockerfile, Dockerfile.dev, README.md, docker-compose.override.yml, docker-compose.yml
Docker had a couple errors when ran locally.
Adding a log file that was missing and causing an error, and make sure all dependencies are installed.
=> Fix docker installation for local development

app/models/local_authority.rb, app/models/local_authority_district.rb, app/models/school.rb, app/models/school_data_importer.rb, app/views/school_search/show.html.erb, db/migrate/20210128134938_add_gias_fields_to_schools.rb, db/migrate/20210129094019_remove_dummy_schools.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/local_authority.rb, spec/factories/local_authority_district.rb, spec/factories/school.rb, spec/models/school_spec.rb, spec/services/school_data_importer_spec.rb
We want more GIAS fields. 
Add Local Authority and Local Authority District models, add more school fields.
Need to add some tests, probably remove some old schools from seeds. Also, the school group data doesn't seem to be in the public extract we are getting :( I commented the fields out, might remove that, or find a better way to deal with it.
=> Add more fields to schools from GIAS extract

app/controllers/core_induction_programme/lessons_controller.rb, app/controllers/core_induction_programme/modules_controller.rb, app/controllers/core_induction_programme/years_controller.rb, app/policies/course_module_policy.rb, app/views/core_induction_programme/lessons/edit.html.erb, app/views/core_induction_programme/lessons/show.html.erb, app/views/core_induction_programme/modules/edit.html.erb, app/views/core_induction_programme/modules/show.html.erb, app/views/core_induction_programme/show.html.erb, app/views/core_induction_programme/years/show.html.erb, config/routes.rb, spec/policies/course_module_policy_spec.rb, spec/requests/core_induction_programme/course_lesson_spec.rb, spec/requests/core_induction_programme/course_module_spec.rb, spec/requests/core_induction_programme/course_year_spec.rb
We need to include functionality for editing module content. The changes included in the PR enable DfE admin to do this. 
- enable editing of module content
- including request and policy tests for being able to edit module content
- refactoring of cip routes to improve readability and minimise duplication.
- amending cip request tests to reflect updates made in the routes. 
- amending cip views to reflect changes made in the routes
Much of what has been used has been replicated from what is done editing lessons.
=> Add editing module content

app/models/local_authority.rb, app/models/local_authority_district.rb, app/models/school.rb, app/models/school_local_authority.rb, app/models/school_local_authority_district.rb, app/services/school_data_importer.rb, db/migrate/20210208173154_create_school_local_authorities.rb, db/migrate/20210208173205_create_school_local_authority_districts.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/school.rb, spec/factories/school_local_authorities.rb, spec/factories/school_local_authority_districts.rb, spec/models/local_authority_district_spec.rb, spec/models/local_authority_spec.rb, spec/models/school_local_authority_district_spec.rb, spec/models/school_local_authority_spec.rb, spec/models/school_spec.rb, spec/services/school_data_importer_spec.rb
This is work in preparation for adding sparsity data. Splitting this ticket up into several PRs, lots to change
Add new models to link schools to local authorities and local authority districts
Update the school data import to match 
I've updated the unit tests, but there's nothing much new here. Just moving the same data to new places
=> ECF-RP-129: Handle schools changing local authorities and lads

Gemfile, Gemfile.lock, app/controllers/api/api_controller.rb, app/controllers/api/school_search_controller.rb, app/decorators/school_decorator.rb, app/models/school.rb, app/serializers/school_serializer.rb, app/views/school_search/show.html.erb, app/webpacker/packs/application.js, app/webpacker/packs/school_search.js, app/webpacker/styles/school_search.scss, config/application.rb, config/routes.rb, package.json, spec/decorators/school_decorator_spec.rb, spec/models/school_spec.rb, spec/requests/api/school_search_spec.rb, spec/serializers/school_serializer_spec.rb, yarn.lock
This is to bring autocomplete functionality to school search
Using accessible autocomplete we can now search character by character.
This pull request does not implement any authentication protocol for our API endpoint.
For serialization I used blueprinter 
Dont burn me too much 
I used unit tests for testing serialization and model
=> Adds api for returning list of schools

app/controllers/demo/school_search_controller.rb, app/models/school.rb, app/views/demo/school_search/index.html.erb, config/routes.rb
Adds Demo page for school search
=> Adds Demo page for school search

app/views/users/sessions/login_email_sent.html.erb, app/views/users/sessions/new.html.erb, app/views/users/sessions/redirect_from_magic_link.html.erb, package.json, spec/cypress/integration/a11y.js, spec/cypress/support/axe.js, spec/cypress/support/index.js, yarn.lock
=> Add automated accessibility tests for some pages

app/controllers/admin/induction_coordinators_controller.rb, app/models/user.rb, app/views/admin/induction_coordinators/edit.html.erb, app/views/admin/induction_coordinators/index.html.erb, config/routes.rb, spec/requests/admin/induction_coordinators_spec.rb
Added index, edit and update actions for induction coordinators
=> [ECF-1-307] Index, edit and update induction coordinators

app/controllers/admin/administrators/administrators_controller.rb, app/controllers/admin/induction_coordinators_controller.rb, app/controllers/admin/lead_providers/lead_provider_users_controller.rb, app/views/admin/administrators/administrators/edit.html.erb, app/views/admin/administrators/administrators/index.html.erb, app/views/layouts/admin/base.html.erb, config/routes.rb, spec/requests/admin/administrators/administrators_spec.rb
=> [ECF-1-307] Admins edit admins

app/controllers/admin/suppliers/lead_provider_users_controller.rb, app/views/admin/administrators/administrators/edit.html.erb, app/views/admin/induction_coordinators/edit.html.erb, app/views/admin/induction_coordinators/index.html.erb, app/views/admin/suppliers/lead_provider_users/edit.html.erb, config/routes.rb, spec/helpers/admin_helper_spec.rb, spec/requests/admin/lead_providers/lead_provider_users_spec.rb
This one has no ticket, just some very minor changes to the frontend
- Move lead provider users under suppliers so nav bar works
- Add back links, closing div tags, and school names
=> Frontend refactor

app/webpacker/packs/cookie-banner.js, spec/cypress/integration/cookies.js
This was a bit of a nightmare to test due to differences between local and the dev environment, but I think I've got it!
I've also changed the tests so that they're more likely to catch failures—although it still doesn't catch the original problem.
This bug didn't happen on a PR environment last time either, so it's probably a code review only on this one…
=> Fix cookie banner

app/components/primary_nav_component.html.erb, app/components/primary_nav_component/nav_item_component.html.erb, app/views/layouts/admin/base.html.erb, app/views/layouts/application.html.erb, app/views/registrations/school_profile/show.html.erb, app/webpacker/styles/application.scss, app/webpacker/styles/header_overrides.scss, app/webpacker/styles/primary-nav.scss
Draft PR but comments welcome - if something isn't an improvement feel free to let me know before review stage.
This work isn't particularly structured, I'm just going through and changing stuff as I find it.
=> Visual improvements

app/controllers/admin/suppliers/suppliers_controller.rb, app/helpers/supplier_helper.rb, app/views/admin/administrators/administrators/index.html.erb, app/views/admin/suppliers/suppliers/index.html.erb, spec/cypress/integration/aaa-meta.js, spec/helpers/supplier_helper_spec.rb
Just some frontend tweaks for consistency
- Only link delivery partners
- Remove edit links
- Move lead providers to top of table
=> Admin suppliers layout

app/models/cohort.rb, app/views/admin/suppliers/delivery_partners/delete.html.erb, app/views/admin/suppliers/delivery_partners/edit.html.erb, spec/cypress/integration/admin/suppliers/create-delivery-partner.js, spec/cypress/integration/admin/suppliers/delete-delivery-partner.js, spec/cypress/integration/admin/suppliers/edit-delivery-partner.js, spec/models/cohort_spec.rb
=> Frontend tweaks from review session

spec/cypress/integration/admin/administrators/create-administrator.js, spec/cypress/integration/admin/administrators/delete-administrator-user.js, spec/cypress/integration/admin/suppliers/create-delivery-partner.js, spec/cypress/integration/admin/suppliers/create-lead-provider-user.js, spec/cypress/integration/admin/suppliers/delete-delivery-partner.js, spec/cypress/integration/admin/suppliers/delete-lead-provider-user.js, spec/cypress/integration/admin/suppliers/edit-delivery-partner.js, spec/cypress/integration/cookies.js
=> Cypress changes

.rubocop.yml, db/seeds.rb, db/seeds/dummy_structures.rb, db/seeds/initial_seed.rb, spec/cypress/app_commands/scenarios/admin/suppliers/manage_delivery_partner.rb, spec/requests/admin/suppliers/delivery_partners_spec.rb
CIPs, Cohorts, and LPs are to be seeded for initial release
- Check against details on ticket
- Make sure it's idempotent
=> ECF-RP-379: Initial seed data

terraform/workspace-variables/staging.tfvars
We want staging to be as similar to prod as possible. These are the values we will start with in prod. It is especially important to change the DB now, since it is hard to upgrade from an unencrypted db to an encrypted one
=> ECF-RP-370: Update app and db params for staging

README.md, app/controllers/admin/administrators/administrators_controller.rb, app/models/admin_profile.rb, config/environments/test.rb, lib/tasks/manage_admins.rake, spec/models/admin_profile_spec.rb, spec/rails_helper.rb, spec/requests/users/sessions_spec.rb, spec/support/tasks.rb, spec/tasks/manage_admins_spec.rb
When we first release, we need to create the first user
- rake task to create first user
- update docs
- make rspec use configured domain in tests
Unit test
=> ECF-RP-372: Add first user

.github/workflows/deploy_to_staging.yml
Shame. Shame
Pretty sure this was the issue
=> ECF-RP-370: Add brackets to fix deploy

Gemfile, Gemfile.lock, config/initializers/health_check.rb, spec/requests/health_check_spec.rb
Adds configuration for database, migration, and email
We would like to get a health check for our application at a minimum for email, database, and migrations
Adds configuration for health_check gem that allows us to see if there are any errors/issues
Added basic unit test
=> Adds health check functionality to the application

app/controllers/admin/administrators/administrators_controller.rb, app/views/layouts/application.html.erb
Little things that don't quite look right on staging
- Sort admins alphabetically
- Update phase banner tag
=> Small changes

.githooks/pre-commit
=> Remove precommit hook debugging code that someone accidentally committed

app/controllers/admin/suppliers/delivery_partners_controller.rb, app/forms/delivery_partner_form.rb, app/views/admin/suppliers/delivery_partners/choose_cohorts.html.erb, app/views/admin/suppliers/delivery_partners/choose_lead_providers.html.erb, config/routes.rb, spec/cypress/integration/admin/suppliers/create-delivery-partner.js, spec/cypress/support/admin/suppliers/commands.js, spec/requests/admin/suppliers/delivery_partners_spec.rb, spec/support/new_supplier_helper.rb
Nested checkboxes are not very accessible
1. Move to 2-page flow (https://miro.com/app/board/o9J_ldVNkCY=/?moveToWidget=3074457353981408802&cot=14)
2. Update a bunch of tests
3. Refactor our controller and form
Pretty sure the edit part of this will come on Monday / Tuesday - cause I need to ask Al about what he wants it to look like. 
I need to add a few tests.
1. Need to make sure both pages have their validation tested
2. Need to add a test for edit page showing validation errors - it didn't :/
=> Redesign checkboxes on delivery partner creation

.github/workflows/deploy_monitoring_production.yml, .github/workflows/deploy_monitoring_staging.yml, terraform/workspace-variables/monitoring/production.tfvars, terraform/workspace-variables/monitoring/staging.tfvars
Extend monitoring stacks to staging and production
=> Add staging and production monitoring stacks

app/views/layouts/application.html.erb, app/webpacker/packs/cookie-banner.js
https://trello.com/c/2D8PyMn9/377-google-analytics-set-up
Do we think this needs tests? Cypress catches it if it completely blows up and throws an error, but doesn't check whether the script is actually present (and I'm not sure whether it should)
=> Add google analytics

app/views/cookies/_banner.html.erb, app/views/cookies/show.html.erb, app/views/layouts/application.html.erb, app/views/registrations/start/index.html.erb, spec/cypress/support/commands.js
Two small changes here: start page copy, and we now have a service name 🎉 
I haven't updated the service name in notify yet, so there's still a couple of references to that. Apart from that, let me know if you think I've missed anything
=> ECF-RP-335: start page and service name

.github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_production.yml, .github/workflows/deploy_to_staging.yml, .github/workflows/review.yml, Dockerfile, terraform/app/modules/paas/data.tf, terraform/app/modules/paas/main.tf, terraform/app/modules/paas/variables.tf, terraform/app/terraform.tf, terraform/app/variables.tf, terraform/workspace-variables/production.tfvars, terraform/workspace-variables/staging.tfvars
We have domains, we need to link them up to the apps for staging and prod
Draw inspiration from teaching vacancies
ran a `terraform plan` for staging locally and it looked good
=> ECF-RP-411: Map routes to apps

.github/workflows/deploy_to_dev.yml
=> Fix spacing

app/components/auto_tag_component.rb, spec/components/auto_tag_component_spec.rb
For the induction tutor onboarding stuff
Small wrapper around the govuk-components tag component which handles the colour for us
we need percy!
=> Add auto tag component

lib/tasks/schools.rake
Instantiate service in send_invites rake task
=> [Bugfix] Instantiate service in send_invites rake task

app/mailers/school_mailer.rb, spec/mailers/school_mailer_spec.rb
Induction coordinator email notifying them they have been nominated as the induction tutor at a school.
https://trello.com/c/fAKWBldv/405-induction-coordinator-receives-an-email-notifying-them-they-have-been-nominated
=> [ECF-1-405] Nomination confirmation email

app/controllers/schools/base_controller.rb, app/controllers/schools/cohorts_controller.rb
I already did this but I think it got lost in a rebase or something!
=> Move school_cohorts logic to a private method to make it reusable.

README.md, lib/tasks/schools.rake
Fixes an issue where command line arguments to the rake task were being run as a new rake task and causing an error as a result.
Updates to readme on how to run the task
A fix for the issue
=> Fix school-invites rake task

app/controllers/privacy_policies_controller.rb, app/views/layouts/_support_links.html.erb, app/views/layouts/application.html.erb, app/views/privacy_policies/show.html.erb, config/environments/deployed_development.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/routes.rb, spec/cypress/integration/Privacy.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/requests/privacy_policy_spec.rb
trello #443 and #456. Update support email and add privacy policy page and footer links to privacy and cookies
As above
=> added privacy policy and updated support email

app/views/layouts/application.html.erb, app/webpacker/styles/app_task_list.scss, app/webpacker/styles/application.scss, app/webpacker/styles/page-tabs.scss
Tested the admin and induction coordinator flows on mobile, and it's mostly fine but a few changes needed to be made!
=> Small improvements to mobile appearance

lib/tasks/safe_reset.rake
I just broke dev because it is subtly different to review apps - there is another important table there :/
=> Exclude more tables from deletion

db/seeds.rb, db/seeds/dummy_structures.rb, db/seeds/test_data.rb
Create scenarios for end to end testing. I have also written up corresponding instructions on some tickets, and added these emails to notify
Manually ran through scenarios
=> Seeds for testing

.github/workflows/test.yml, app/views/layouts/application.html.erb, package.json, spec/cypress/integration/Cookies.feature, spec/cypress/plugins/index.js, spec/cypress/support/commands.js, spec/cypress/support/step_definitions/common-interaction.js, yarn.lock
👀
Currently blocked by percy not reporting its status to github :(
=> Add percy setup + initial test

.github/workflows/run_task_dev.yml
DevOps never works on the first go...
=> Apparently you can't start your command with cf

spec/cypress/support/commands.js, spec/cypress/support/step_definitions/common-navigation.js, spec/cypress/support/step_definitions/factory-bot.js
=> Update cucumber step definitions from other repo

app/forms/induction_choice_form.rb, app/views/check_account/show.html.erb, app/views/nominations/nominate_induction_coordinator/new.html.erb, app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb, app/views/nominations/nominate_induction_coordinator/start.html.erb, app/views/nominations/request_nomination_invite/already_nominated.html.erb, app/views/nominations/request_nomination_invite/choose_location.html.erb, app/views/nominations/request_nomination_invite/choose_school.html.erb, app/views/nominations/request_nomination_invite/limit_reached.html.erb, app/views/nominations/request_nomination_invite/not_eligible.html.erb, app/views/privacy_policies/show.html.erb, app/views/schools/choose_programme/advisory.html.erb, app/views/schools/choose_programme/show.html.erb, app/views/schools/cohorts/programme_choice.html.erb, app/views/schools/core_programme/materials/show.html.erb, app/views/schools/core_programme/materials/success.html.erb, app/views/schools/dashboard/show.html.erb, app/views/start/index.html.erb, app/views/users/sessions/login_email_sent.html.erb, app/webpacker/styles/application.scss, spec/cypress/integration/accessibility.js, spec/cypress/integration/nominations/NominateInductionCoordinator.feature, spec/cypress/integration/schools/core_induction_programme/ChooseMaterials.feature, spec/forms/induction_choice_form_spec.rb, spec/requests/schools/choose_programme_spec.rb
Checklist on ticket. Copy updates after review with Shani and Mehmet
=> ECF-RP-521: Copy updates

app/views/layouts/application.html.erb
The wrong ID was provided before, this is the correct one.
You can't!
=> Correct google analytics ID

.github/PULL_REQUEST_TEMPLATE.md, spec/cypress/integration/AccessibilityStatement.feature, spec/cypress/integration/CheckAccount.feature, spec/cypress/integration/Privacy.feature, spec/cypress/integration/Start.feature, spec/cypress/integration/accessibility.js, spec/cypress/integration/admin/AdminManagement.feature, spec/cypress/integration/admin/DeliveryPartnerManagement.feature, spec/cypress/integration/admin/LeadProviderUserManagement.feature, spec/cypress/integration/admin/SchoolManagment.feature, spec/cypress/integration/nominations/NominateInductionCoordinator.feature, spec/cypress/integration/nominations/ResendNominations.feature, spec/cypress/integration/schools/ChooseProgramme.feature, spec/cypress/integration/schools/ViewPartnerships.feature, spec/cypress/integration/schools/core_induction_programme/ChooseMaterials.feature
=> Add percy everywhere

spec/cypress/app_commands/scenarios/admin/schools.rb, spec/cypress/app_commands/scenarios/school_with_local_authority.rb, spec/factories/induction_coordinator_profiles.rb, spec/factories/nomination_email.rb
Will fix the percy errors in every PR 😬
=> Remove all non-deterministic data from visual tests

app/forms/induction_choice_form.rb, app/forms/nominate_induction_tutor_form.rb, app/forms/supplier_user_form.rb, app/mailers/user_mailer.rb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb, app/views/nominations/nominate_induction_coordinator/start.html.erb, app/views/nominations/request_nomination_invite/choose_location.html.erb, app/views/nominations/request_nomination_invite/choose_school.html.erb, app/views/nominations/request_nomination_invite/not_eligible.html.erb, app/views/nominations/request_nomination_invite/review.html.erb, app/views/nominations/request_nomination_invite/success.html.erb, app/views/schools/choose_programme/show.html.erb, app/views/schools/cohorts/show.html.erb, app/views/schools/core_programme/materials/edit.html.erb, app/views/schools/partnerships/_confirm_with_provider.html.erb, app/views/schools/partnerships/_signed_up_with_provider.html.erb, app/views/start/index.html.erb, app/views/users/sessions/login_email_sent.html.erb, lib/devise/strategies/passwordless_authenticatable.rb, spec/cypress/integration/schools/ViewPartnerships.feature, spec/mailers/user_mailer_spec.rb, spec/requests/schools/partnerships_spec.rb, spec/requests/users/sessions_spec.rb
Another round of copy updates. Sat down with Shani, went through the changes, and made them live.
Lots of copy updates. Most significant changes are extra params to emails. This will need to be updated on notify after this has made it to staging
Do your best? Any obvious typos or horriblness, but Shani has confirmed the correctness of this copy
Updated relevant tests
Follow existing scenarios. These are wide ranging changes, touching most pages
=> Copy updates

app/views/layouts/application.html.erb
https://trello.com/c/lZ4dkHgM/531-add-link-to-user-feedback
Not sure how we feel about `target="_blank"`?
=> Change feedback link to office form

app/forms/nomination_request_form.rb, app/views/nominations/nominate_induction_coordinator/start.html.erb, app/views/start/index.html.erb, lib/devise/strategies/passwordless_authenticatable.rb, spec/cypress/integration/nominations/NominateInductionCoordinator.feature, spec/forms/nomination_request_form_spec.rb, spec/requests/nominations/request_nomination_invite_spec.rb
More copy updates. Biggest change here is adding `.localtime` to a time to deal with daylight savings
=> More copy updates

app/views/schools/core_programme/materials/info.html.erb
=> Update Ambition -> Ambition Institute

app/views/schools/cohorts/programme_choice.html.erb, app/views/schools/partnerships/_confirm_with_provider.html.erb
Some copy changes to the guidance for changing provision
Sign in as
- cpd-test+tutor-1@digital.education.gov.uk for CIP
- cpd-test+tutor-2@digital.education.gov.uk for FIP
=> ECF-RP-561: Copy updates for choosing and changing programme

app/controllers/admin/schools/induction_coordinators_controller.rb, app/views/admin/schools/induction_coordinators/email_used.html.erb, app/views/admin/schools/induction_coordinators/new.html.erb, spec/cypress/integration/admin/InductionCoordinatorManagment.feature, spec/requests/admin/schools/induction_coordinators_spec.rb
Update to #494
Additional content and notification banner test
Sign in as Admin, add induction tutor to school
=> Add more tests

app/views/check_account/show.html.erb
=> Update copy on check account screen

Gemfile, Gemfile.lock
=> Correction to gem path for health_check

app/views/schools/partnerships/_confirm_with_provider.html.erb
Copy changes made during a live session with Shani, requested from above and marked as urgent.
=> Copy changes to 'Have you signed up with a training provider' page

app/views/start/index.html.erb
Superseding PR https://github.com/DFE-Digital/early-careers-framework/pull/352
=> Update 'do you have account'

app/views/users/sessions/login_email_sent.html.erb
Superseding the PR https://github.com/DFE-Digital/early-careers-framework/pull/346
=> Updated copy to email sent

app/views/nominations/request_nomination_invite/review.html.erb
Superseding PR https://github.com/DFE-Digital/early-careers-framework/pull/350
=> Updated intro text

.github/workflows/deploy_to_sandbox.yml
I think we need to check out the code to be able to have a directory:
```
/home/runner/work/_temp/bab1baba-8884-4f86-91f3-c55f00f9b81d.sh: line 2: cd: terraform/app: No such file or directory
```
=> Add checkout step to sandbox environment

config/webpacker.yml
=> Add sandbox section to webpacker

.rubocop.yml, app/controllers/sandbox_controller.rb, app/views/layouts/_application.html.erb, app/views/sandbox/show.html.erb, config/routes.rb, spec/routing/sandbox_controller_spec.rb, terraform/workspace-variables/sandbox_app_env.yml
Add root for sandbox environment
At the moment there is no content, but will be added once we have it
=> Add a dummy landing page for sandbox

app/views/schools/cohorts/show.html.erb
Updated the H1 text with relevant copy and code
Removed the paragraph underneath about use of materials/provider
=> Updated Header + caption

app/views/nominations/request_nomination_invite/success.html.erb
Superseding old PR https://github.com/DFE-Digital/early-careers-framework/pull/351
=> Updated 'what happens next'

app/controllers/application_controller.rb, app/controllers/users/sessions_controller.rb, app/views/users/sessions/signed_out.html.erb, config/locales/devise.en.yml, config/routes.rb, spec/cypress/integration/aaa-meta/cypress.js, spec/cypress/integration/accessibility.js, spec/cypress/support/commands.js, spec/requests/users/logout_spec.rb
Add a sign out page
Sign in as admin@example.com
Sign out
=> CPDRP-308: sign out page

app/views/users/sessions/new.html.erb, spec/cypress/integration/CheckAccount.feature
I walked through this change with @shanirogers this morning as a demonstration of editing content directly on GitHub.com.
Card: https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-307
=> Update copy on sign in page

spec/requests/admin/schools_spec.rb
Missing html escape on generated data
=> Fix flakey test

swagger/v1/api_spec.json
Updated it using the following command:
```
rails rswag
```
=> Add updated swagger api spec

app/views/sandbox/show.html.erb
https://dfedigital.atlassian.net/browse/CPDTP-170
=> CPDTP-170 Update API Sandbox landing page content

Gemfile, db/seeds.rb, db/seeds/sandbox_data.rb
The following command in sandbox environment will generate the list of dummy user UUIDs and lead provider API tokens:
```
RAILS_ENV=sandbox rails db:seed 
```
Output
```
Token for Capita is 9ba4A-dtTpHyxWHxCBAZ, user uuids: 29fa3e26-6d24-4045-8fa5-6189592ae2c7,...
```
https://dfedigital.atlassian.net/browse/CPDTP-175
=> CPDTP-175 Add sandbox seed file to generate users UUIDs and lead provider tokens

app/jobs/session_trim_job.rb
As discussed on slack, this corrects the cron schedule to run daily instead of monthly
=> Update session trim job to run daily instead of monthly

package.json, yarn.lock
To get the fix for https://github.com/cypress-io/cypress/issues/15101 which is causing the cypress tests to flap in CI.
=> Upgrade cypress to 7.4.0

app/jobs/school_email_update_job.rb, app/services/school_data_importer.rb, lib/tasks/cron.rake, spec/jobs/school_email_update_job_spec.rb, spec/services/school_data_importer_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-296
Schools are updating their contact emails on GIAS (we're telling them to) but at the moment we're not listening to that change.
We can't update all details of the school yet because that's complicated, but we want the latest emails.
Daily task to update school emails
Tested locally, unit tests
Not sure...
=> CPDRP-296: GIAS email updates

spec/components/lead_providers/your_schools/table_spec.rb
This component test had a false-negative edge case which is now fixed.
=> Fixed 1/22 random test failure

app/models/api_token.rb, terraform/workspace-variables/dev.tfvars, terraform/workspace-variables/review.tfvars
1. I really should have made `ApiToken` an abstract class when I made it, it's not obvious that it shouldn't be instantiated by itself. 
2. Are we running any cron jobs on dev or review envs? If not, is it intentional? If yes, how do they get scheduled? @BroiSatse?
1. Make ApiToken an abstract class
2. Add cron scheduling to review and dev app commands
N/A
I guess I will ssh into review app and see if it has any jobs scheduled...
You can't.
=> Sneaky fixes

app/forms/delivery_partner_form.rb, spec/forms/delivery_partner_form_spec.rb
second attempt at fixing the issue
=> CPDRP-394: Bugfix - issue with pairing LPs and DPs

app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb, spec/cypress/integration/nominations/NominateInductionCoordinator.feature
Updated as per: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.f4n6q8721l6f
=> CPDRP-305: removed lead

app/views/nominations/nominate_induction_coordinator/start.html.erb, spec/cypress/integration/nominations/NominateInductionCoordinator.feature
Added start button as per screen: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.ppucoxvc27q#445
=> CPDRP-305: added start

app/views/nominations/nominate_induction_coordinator/start.html.erb
Updated copy before the button as per this screen: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.ppucoxvc27q
=> CPDRP-305 - updated copy

app/views/nominations/nominate_induction_coordinator/new.html.erb
Updated page title and copy under 'Who' as per: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.tr6kpmds064h
=> CPDRP-305: page title and hint text

app/views/nominations/request_nomination_invite/review.html.erb
Updated intro as per: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.hzx63utxkzzv
=> CPDRP-305: Copy updates to request nomination email - check answers

app/views/nominations/request_nomination_invite/cip_only.html.erb
See: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.hzx63utxkzzv
=> Updated page title

app/views/nominations/request_nomination_invite/success.html.erb
Updated as per: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.aocozmos0srb
=> CPDRP-350 -Updated what happens next

app/views/start/index.html.erb
See: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.yq54l05qxs6e
=> CPDRP-350 - updated copyyy

app/views/nominations/request_nomination_invite/limit_reached.html.erb
See: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.8c36aco9b9rk
=> CPDRP-350 - copy updated

app/forms/induction_choice_form.rb, app/views/schools/choose_programme/advisory.html.erb, app/views/schools/choose_programme/confirm_programme.html.erb, app/views/schools/choose_programme/show.html.erb, app/views/schools/cohorts/add_participants.html.erb, app/views/schools/cohorts/programme_choice.html.erb, app/views/schools/partnerships/_confirm_with_provider.html.erb, app/views/schools/partnerships/_signed_up_with_provider.html.erb, spec/cypress/integration/ChallengePartnership.feature, spec/cypress/integration/schools/ViewPartnerships.feature, spec/requests/schools/partnerships_spec.rb
=> Cpdrp 305 dashboard copy updates

db/seeds/sandbox_data.rb
And attach cohort to early career teacher profile
=> Fix school urn to be in the correct format in sandbox seed data

spec/cypress/app_commands/scenarios/admin/schools.rb, spec/cypress/integration/Privacy.feature, spec/cypress/integration/admin/SchoolManagment.feature, spec/cypress/support/step_definitions/factory-bot.js, spec/factories/privacy_policy.rb
it was annoying and bad
percy will error in this PR, but once merged to develop should start working!
you can't
=> Remove randomness from percy snapshots

terraform/workspace-variables/dev.tfvars
Getting fairly frequent OOMs on dev. Prod looks good still, really low usage
=> Increase dev memory to 1GB 

spec/cypress/app_commands/scenarios/confirm_cip.rb
This one snuck through because I only tested on the same day!
You can't
=> Remove another bit of randomness from percy

app/controllers/admin/participants_controller.rb, app/controllers/admin/schools/participants_controller.rb, app/models/user.rb, app/policies/participant_policy.rb, app/views/admin/participants/show.html.erb, app/views/admin/schools/participants/index.html.erb, app/views/admin/schools/shared/_navigation.html.erb, config/routes.rb, spec/cypress/app_commands/scenarios/admin/school_participants.rb, spec/cypress/integration/admin/ViewSchoolParticipants.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/models/user_spec.rb, spec/requests/admin/participants_request_spec.rb, spec/requests/admin/schools/participants_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-357
yes
- Sign in as admin
- Find a school with participants
- Click onto "Participants" tab
=> Give admins the ability to monitor single school participants

spec/requests/lead_providers/report_schools/csv_spec.rb
Use existing cohort, LP and DP to speed up test and prevent failure
caused by duplicate cohorts
=> Improve flaky test

app/views/lead_providers/your_schools/index.html.erb
Updated 'report schools' button I think that's from the MIRO.
See: https://docs.google.com/document/d/1XiQQtWYOGcrGo8SGM1mapgSyzQGUcnTa4ECizkIusSI/edit#heading=h.qaccgv71jt4z
=> Top button text dif from doc.

app/views/lead_providers/report_schools/base/success.html.erb
Page title to match doc: https://docs.google.com/document/d/1XiQQtWYOGcrGo8SGM1mapgSyzQGUcnTa4ECizkIusSI/edit#heading=h.guecwoeot95e
=> Page title update to match content doc

app/views/lead_providers/report_schools/confirm/no_schools.html.erb
Just updated the link copy. Low priority.
=> Updated link text: not urgent

app/controllers/admin/participants_controller.rb, app/controllers/schools/base_controller.rb, app/controllers/schools/cohorts_controller.rb, app/controllers/schools/participants_controller.rb, app/forms/participant_mentor_form.rb, app/models/school.rb, app/models/user.rb, app/policies/participant_policy.rb, app/services/feature_flag.rb, app/views/schools/cohorts/show.html.erb, app/views/schools/participants/edit_details.html.erb, app/views/schools/participants/edit_mentor.html.erb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb, config/routes.rb, db/seeds/dummy_structures.rb, spec/cypress/app_commands/scenarios/school_participants.rb, spec/cypress/integration/schools/ManageParticipants.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/cypress/support/step_definitions/database.js, spec/requests/schools/add_participants_spec.rb, spec/requests/schools/participants_request_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-360
=> School induction tutor managing/viewing participants in a cohort

app/controllers/schools/add_participants/base_controller.rb, app/controllers/schools/add_participants/details_controller.rb, app/controllers/schools/add_participants/types_controller.rb, app/forms/schools/add_participant_form.rb, app/models/school_cohort.rb, app/services/feature_flag.rb, app/views/schools/add_participants/details/show.html.erb, app/views/schools/add_participants/types/show.html.erb, app/views/schools/participants/index.html.erb, config/routes.rb, spec/cypress/integration/schools/AddParticipants.feature, spec/cypress/support/step_definitions/common-interaction.js, spec/forms/schools/add_participant_form_spec.rb, spec/services/feature_flag_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-356
This PR contains the seed for the entire InductorCoordinator journey of adding a new participant.
=> First step of adding participant journey

app/views/schools/partnerships/_confirm_with_provider.html.erb
Minsisterial folks have requested this updated be made asap. (I am ambivalent ;)
=> Ministerial update: sentence about 'ease'

README.md
Make it easier for design folks to find the latest screenshots
=> Add Percy badge to README

app/forms/schools/add_participant_form.rb, app/views/schools/add_participants/complete.html.erb, app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/details.html.erb, app/views/schools/add_participants/email_taken.html.erb, app/views/schools/add_participants/type.html.erb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb, spec/cypress/integration/schools/AddParticipants.feature
Made these changes with Shani earlier!
click link in comment below
=> Copy changes for participants flow

app/views/schools/cohorts/show.html.erb
Removed 'approved' from title even though it technically won't apply to this page.
=> Updated 'use a training provider in code'

app/controllers/schools/choose_programme_controller.rb, app/views/schools/choose_programme/advisory.html.erb
Updated as per: https://docs.google.com/document/d/19V47mPazGIMeqCAlIy0eqLbPhbI6UuFf_UJ2g3caldo/edit#heading=h.6qc0t8c7utsx
=> Added CIP and FIP message

app/mailers/school_mailer.rb, app/services/feature_flag.rb, app/services/invite_schools.rb, app/services/utm_service.rb, lib/tasks/schools.rake, spec/services/invite_schools_spec.rb
We want to invite schools to join a private beta for adding participant details
- Rake task to invite schools
- Send welcome email to induction tutor
- Turn on the feature flag for the school
=> CPDRP-474: Private Beta

app/controllers/admin/schools/cohorts_controller.rb, app/controllers/admin/schools/induction_coordinators_controller.rb, app/controllers/admin/schools/participants_controller.rb, app/controllers/admin/schools/replace_or_update_induction_tutor_controller.rb, app/controllers/admin/schools_controller.rb, app/models/school.rb, spec/cypress/app_commands/scenarios/admin/school_participants.rb, spec/cypress/integration/admin/ViewSchoolParticipants.feature, spec/cypress/support/step_definitions/common-navigation.js
Part one: https://github.com/DFE-Digital/early-careers-framework/pull/517
=> Part two of "Nicer URLs for cohorts + schools"

lib/payment_calculator/ecf/payment_calculation.rb
Working on uplift payment calculations so was in the area.
* Change a variable name to be consistent with the class name
:ship:
=> Refactor - rename variable in test to match class name

spec/lib/payment_calculator/ecf/contract/output_payment_calculations_spec.rb
Minor refactor to get both tests use the same test objects
=> Refactor rspec test for output payments

app/forms/induction_choice_form.rb
Content request: https://docs.google.com/document/d/19V47mPazGIMeqCAlIy0eqLbPhbI6UuFf_UJ2g3caldo/edit#heading=h.t1w0iwt1a7wd
=> Added CIP and FIP to choices

app/views/schools/choose_programme/confirm_programme.html.erb, spec/requests/schools/choose_programme_spec.rb
Copy updated: https://docs.google.com/document/d/19V47mPazGIMeqCAlIy0eqLbPhbI6UuFf_UJ2g3caldo/edit#heading=h.7ckcdzlpw194
=> Updates choices

app/controllers/schools/add_participants_controller.rb, app/forms/schools/add_participant_form.rb, app/lib/multistep/form.rb, app/views/schools/add_participants/complete.html.erb, app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/type.html.erb, config/locales/schools/add_participant.yml, spec/cypress/integration/schools/AddParticipants.feature, spec/forms/schools/add_participant_form_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-496
This PR adds an option for IC to add themselves as a mentor to a selected cohort.
=> IC self-nominating as a mentor

app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/type.html.erb, app/views/schools/participants/index.html.erb, config/locales/schools/participants.yml
https://dfedigital.atlassian.net/browse/CPDRP-496 - issue mentioned in the comments section.
I might have said this already `user.user_description` should be burnt with fire :P
=> Replacing user description with participant type on participant list page

app/views/schools/add_participants/type.html.erb
Updated details component text: https://docs.google.com/document/d/1MGn-XbmD2K10qw1Jp98XmkMyuvNwZUf8cq429YqF0Yg/edit#heading=h.ppucoxvc27q
=> Updated details text

package.json, yarn.lock
=> Bump Cypress version

.percy.yml
=> Run percy config:migrate

app/views/start/index.html.erb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-316)
Fix start button styling
Use correct `govuk_start_now_button` method to generate button
Change button text from "Start" to "Start now" in line with latest govuk guidance
Visit the start page, start button should be correctly styled.
=> CPDRP-316 Fix start button

app/views/users/sessions/new.html.erb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-317)
Fix styles on list on sign-in page
Add correct govuk styles to list on sign-in page 
Go to sign-in page, the list should be correctly formatted with the right styles
=> CPDRP-317 fix missing list classes

app/controllers/pages_controller.rb, app/views/pages/induction_tutor_materials/_course_year_sub_nav.html.erb, app/views/pages/induction_tutor_materials/ambition/_handbooks_and_outlines.html.erb, app/views/pages/induction_tutor_materials/ambition/year_one.html.erb, app/views/pages/induction_tutor_materials/ambition/year_two.html.erb, app/views/pages/induction_tutor_materials/educational_development_trust/_handbooks_and_outlines.html.erb, app/views/pages/induction_tutor_materials/educational_development_trust/year_one.html.erb, app/views/pages/induction_tutor_materials/educational_development_trust/year_two.html.erb, app/views/pages/induction_tutor_materials/teach_first/year_one_and_two.html.erb, app/views/pages/induction_tutor_materials/ucl/_handbooks_and_outlines.html.erb, app/views/pages/induction_tutor_materials/ucl/year_one.html.erb, app/views/pages/induction_tutor_materials/ucl/year_two.html.erb, config/routes.rb, spec/cypress/integration/InductionTutorMaterials.feature, spec/cypress/support/step_definitions/common-navigation.js
[461 - Ambition](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-461)
[462 - EDT](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-462)
[463 - Teach First](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-463)
[464 - UCL](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-464)
Adding Induction Tutor materials for Ambition and Teach First
Routing for the materials
I've only done Ambition and Teach First to make sure that we're happy with how they're being displayed. 
Ambition, EDT and UCL all have subnavs for Year 1 and Year 2. Teach First doesn't. 
If we're happy with the views for Ambition i'll do the same for EDT and …
=> Induction tutor materials pages

app/controllers/schools/choose_programme_controller.rb, app/forms/induction_choice_form.rb, app/views/schools/choose_programme/confirm_programme.html.erb, config/locales/schools/induction_choice_form.yml, spec/cypress/integration/schools/ChooseProgramme.feature, spec/forms/induction_choice_form_spec.rb, spec/requests/schools/choose_programme_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-446
=> Displaying cohort opt-out confirmation before saving the choice

.github/workflows/deploy_monitoring_dev.yml, .github/workflows/deploy_monitoring_production.yml, .github/workflows/deploy_monitoring_staging.yml, terraform/monitoring/config/alert.rules.yml, terraform/monitoring/resources.tf, terraform/monitoring/variables.tf, terraform/workspace-variables/monitoring/dev.tfvars, terraform/workspace-variables/monitoring/production.tfvars, terraform/workspace-variables/monitoring/staging.tfvars
The monitoring stack is all set up to do this already. I've taken some alert definitions from teaching vacancies, we can fine tune and extend this these if needed
=> Add metrics monitoring with alertmanager

spec/cypress/app_commands/scenarios/schools/multiple_schools.rb
=> Remove random data from visual tests

app/views/nominations/nominate_induction_coordinator/start_nomination.html.erb
Merge/deploy this when the MAT journey has gone live.
Updated copy as per: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.ppucoxvc27q
Please make sure I've coded the 'Or's in the middle of bullet points correctly :)
=> CPDRP-345: new section.

app/services/partnership_notification_service.rb
Support need to follow up with these schools
Resolves https://sentry.io/organizations/dfe-bat/issues/2447441719/?project=5748989&query=is%3Aunresolved
=> Send partnership notification emails to support where the is no school email

app/views/nominations/request_nomination_invite/resend_email.html.erb
This is a key change: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.ytreh5s1wasn
This is to match/compliment the other CPD345 change on Nominate an induction tutor.
=> CPDRP-345: updated copy

app/mailers/school_mailer.rb, app/services/invite_schools.rb, lib/tasks/schools.rake, spec/services/invite_schools_spec.rb
I've been given a list of URNs and told to send the schools an email with a nomination link
=> Send emails to MAT schools

spec/cypress/integration/schools/SeeChallengeBanners.feature
=> Fix failing cypress test

app/services/invite_schools.rb, lib/tasks/schools.rake, spec/services/invite_schools_spec.rb
Email beta schools without participants again
=> Send beta chaser emails

app/services/record_participant_event.rb, spec/requests/api/v1/provider_events_spec.rb, spec/services/record_participant_service_spec.rb
The issue appeared when making call to the API for declarations
```
undefined local variable or method `lead_provider'
```
Fixed rspec test to catch this error
=> CPDTP-204 Fix issue with undefined local variable RecordParticipantEvent

app/mailers/school_mailer.rb, app/services/invite_schools.rb, app/services/utm_service.rb, lib/tasks/schools.rake
CPDRP-537
Send an email to induction tutors who have yet to sign in
=> CPDRP-537: Task to send emails to induction coordinators yet to sign in

app/models/local_authority_district.rb
I think I got this info from a discussion with Ethan as word of mouth and thought it worth recording here for future readers. The lack of foreign key is a little surprising if you don't know the context.
Add a code comment
=> Document the local authority to district missing link

documentation/cypress_cucumber.md
Figured it would be a good idea to get this info out of my head and into a markdown document before i leave :)
=> Add docs for cypress + cucumber

app/controllers/schools/participants_controller.rb, app/views/schools/participants/edit_email.html.erb, app/views/schools/participants/edit_name.html.erb, spec/cypress/integration/schools/ManageParticipants.feature
https://ukgovernmentdfe.slack.com/archives/C01J1J4FM50/p1625482060356600
- Add back links
- Change title to show participant type
=> Updates to change name and email pages for SIT managing participants

app/views/users/sessions/login_email_sent.html.erb
Updates, as requested by Ana: https://docs.google.com/document/d/1ZlLkR7kkq_JnH88a9fru57BRfiyO17UlH8XbL7zl4pA/edit#heading=h.sl8rgqh322yt
=> CPDRP-500: flagging DfE sign in

app/views/schools/add_participants/complete.html.erb, app/views/schools/add_participants/details.html.erb, app/views/schools/add_participants/type.html.erb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb
CPDRP-533
Just a whole load of copy changes
=> CPDRP-533: Copy updates

terraform/workspace-variables/staging.tfvars
We need to scale to two instances for availability. Make this change on
staging first
=> Bump staging to two instances

app/controllers/api/v1/data_studio/school_rollout_controller.rb, spec/requests/api/v1/data_studio/school_rollout_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-260)
The last query was outdated and did not perform. This builds the JSON at the database and attempts to minimise re-processing the data by Rails
Use PostgreSQL JSON features to build the data and minimise ActiveRecord/JSON processing in the Rails app
=> CPDRP-260 DataStudio API (again)

lib/payment_calculator/ecf/contract/output_payment_calculations.rb
The bands are all passed in via method parameters.
Remove unused code - delegate of bands to contract
:ship:
=> Remove unused code - delegate of bands to contract

db/seeds/dummy_structures.rb
- Ensure in sandbox env NPQ can talk to this app
- Add to seeding for sandbox hardcoded api token
- none
- Run sandbox seeds
- Should see newly added token
- not possible
=> add sandbox api token for NPQ

lib/tasks/payment_breakdown.rake
Update the task to look up the aggregation on the lead provider supplied if numbers are not also supplied.
Change the default values for the arguments to perform calls to the aggregator rather than having hard coded numbers.
=> CPDTP-324 Update the rake task to look up the aggregation

app/controllers/schools/participants_controller.rb, app/forms/participant_mentor_form.rb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb, spec/requests/schools/participants_request_spec.rb
- Handle no mentor selected gracefully
- Do not show options to assign mentors when no mentors available
=> BUGFIX: assigning mentors

app/controllers/admin/schools/participants_controller.rb, app/models/user.rb
Two in one here (terrible I know)
- Only show ECF participants in admin schools view (NPQ participant don't have the correct methods/attributes and things break)
- Fix scope to work for NPQ participants - this has been breaking the /users API, and was also the direct cause of the above issue
=> Bugfix npq ppts in admin views

swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml, swagger/v1/component_schemas/NPQParticipantStartedDeclaration.yml
Minor changes to correct and extend descriptions in two of the API files
=> Made NPQ participant declaration description lines correct.

db/schema.rb, spec/components/api_docs/operation_component_spec.rb, spec/docs/npq_applications_spec.rb, spec/docs/participant_declarations_spec.rb, spec/docs/participants_spec.rb, spec/presenters/api_docs/api_operation_spec.rb, spec/presenters/api_docs/api_reference_spec.rb, spec/support/open_api_example_specification.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/EcfParticipant.yml, swagger/v1/component_schemas/EcfParticipantAttributes.yml, swagger/v1/component_schemas/EcfParticipantCsvRow.yml, swagger/v1/component_schemas/ListFilter.yml, swagger/v1/component_schemas/MultipleEcfParticipantsCsvResponse.yml, swagger/v1/component_schemas/MultipleEcfParticipantsResponse.yml, swagger/v1/component_schemas/MultipleNpqApplicationsCsvResponse.yml, swagger/v1/component_schemas/MultipleNpqApplicationsResponse.yml, swagger/v1/component_schemas/NpqApplication.yml, swagger/v1/component_schemas/NpqApplicationAttributes.yml, swagger/v1/component_schemas/NpqApplicationCsvRow.yml, swagger/v1/component_schemas/ParticipantDeclarationRecordedResponse.yml, swagger/v1/component_schemas/ParticipantFilter.yml, swagger/v1/template.yml
NPQ openapi doc needed restructuring to give examples and descriptions
rework component templates to document NPQ application properties and models
View https://ecf-review-pr-708.london.cloudapps.digital/lead-providers/guidance/reference, check examples and descriptions
=> NPQ API reference docs

config/environments/production.rb
Taken from papertrail docs. We are doing lots of console work at the moment, we should keep track of it
=> Record whodunnit for console users in production

app/controllers/lead_providers/guidance_controller.rb, app/views/layouts/guidance_markdown.html.erb, app/views/lead_providers/content/index.html.erb, app/views/lead_providers/content/partnership_guide.html.erb, app/views/lead_providers/guidance/ecf_usage.html.erb, app/views/lead_providers/guidance/index.html.erb, app/views/lead_providers/guidance/npq_usage.html.erb, app/views/lead_providers/guidance/reference.html.erb, app/views/lead_providers/guidance/release_notes.html.erb, app/views/sandbox/show.html.erb, config/routes.rb, spec/cypress/integration/Sandbox.feature, spec/cypress/integration/lead_providers/Guidance.feature, spec/cypress/integration/lead_providers/PartnershipGuidance.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/docs/npq_applications_spec.rb, spec/docs/participants_spec.rb, spec/requests/lead_providers/ecf_usage_spec.rb, spec/requests/lead_providers/npq_usage_spec.rb, spec/requests/lead_providers/partnership_guide_spec.rb, spec/requests/sandbox_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/MultipleEcfParticipantsCsvResponse.yml, swagger/v1/component_schemas/MultipleEcfParticipantsResponse.yml, swagger/v1/component_schemas/Pagination.yml
Need more guidance to differentiate NPQ tasks from ECF tasks
Add NPQ register to sandbox page
Add guidance on getting NPQ applications
Add guidance on sending NPQ start declarations
/lead-providers/guidance/home
=> NPQ sandbox guidance

app/serializers/participant_serializer.rb, spec/serializers/participant_serializer_spec.rb
We shouldn't share PII of withdrawn participants
=> Remove name from withdrawn participants in API response

app/models/participant_profile.rb
The participants API uses updated_at on the User model
=> Touch User on update to participant profile

app/models/participant_profile.rb, app/models/participant_profile/npq.rb, app/models/teacher_profile.rb, app/models/user.rb, db/migrate/20210727092329_create_teacher_profiles.rb, db/migrate/20210727095604_add_teacher_profile_id_to_participant_profiles.rb, db/migrate/20210727100720_add_participant_profile_to_teacher_profile_fk.rb, db/schema.rb, lib/tasks/data.rake
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-759
This PR creates TeacherProfile and automatically creates them on each ParticipantProfile save. This way we can safely switch to the new TeacherProfile without any downtime.
Once this is deplyed we will run `data:populate_teacher_profiles` after which we can switch to use the teacher profile and break participant_profile->user association in the next PR.
=> Shadow TeacherProfile

app/serializers/dqt_record_serializer.rb, app/serializers/ecf_user_serializer.rb, app/serializers/npq_application_serializer.rb, app/serializers/participant_serializer.rb, app/serializers/participant_validation_serializer.rb, app/serializers/user_serializer.rb
There's something slow on the API, and I think it might be this
=> Instrument the JSONAPI::Serializer s

app/views/lead_providers/guidance/npq_usage.html.erb, app/views/sandbox/show.html.erb, spec/requests/lead_providers/npq_usage_spec.rb
This updates the documentation to support the NPQ started event declarations.
HTML documentation only changes.
- Update NPQ usage pages to reflect changes to the document source
- Fix a typo on the sandbox home page
=> CPDTP-372 Update sandbox documentation for NPQ started event

config/initializers/filter_parameter_logging.rb
- Add more things to filter in logs
- See diff
- none
- none
- none
=> Add to parameter filtering for logging

db/seeds/test_data.rb
=> change test SIT emails to @example.com to bypass sign in

app/controllers/schools/participants_controller.rb, app/policies/participant_profile_policy.rb, app/views/schools/participants/index.html.erb, spec/rails_helper.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-598
Admin part has been tackled with manual admin validation journey
=> Switched school participant list to load participant profiles instead of users

app/services/admin/change_induction_service.rb, spec/services/admin/change_induction_choice_service_spec.rb
A series of compounded errors lead to this one getting though 😞
=> CPDRP-806: BUGFIX: do not withdraw participants when changing between CIP and FIP

db/seeds/dummy_structures.rb, db/seeds/initial_seed.rb
Is there any reason we shouldn't do this? Would make testing things much easier
=> Additionally set test API keys on deployed_development

app/services/feature_flag.rb, app/views/pages/_user_research_fully_booked.html.erb, app/views/pages/_user_research_sign_up.html.erb, app/views/pages/user_research.html.erb, spec/features/user_research_pages_spec.rb, spec/support/features/feature_flag_helper.rb
CPDRP-769
We want a page we can change the content of when UR sessions fill up. Control with feature flag
=> CPDRP-769: Add pages for participants user research

app/views/lead_providers/guidance/npq_usage.html.erb, spec/requests/lead_providers/npq_usage_spec.rb
- Add accept/reject guidance to NPQ usage guide
=> Add accept/reject guidance to NPQ usage guide

app/views/pages/_user_research_sign_up.html.erb
Minor content changes for better readability:
- line break added
- extraneous words removed
- link text updated to avoid duplication
=> Ur content 090821

app/forms/schools/add_participant_form.rb, spec/cypress/integration/schools/AddParticipants.feature, spec/forms/schools/add_participant_form_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-788
=> Updated error messages on AddParticipant form

config/locales/en.yml
We should use QQ, per advice
https://design-system.service.gov.uk/patterns/national-insurance-numbers
=> CPDRP-830: Change example nino

config/environments/deployed_development.rb, config/environments/development.rb, config/environments/sandbox.rb
Following https://github.com/DFE-Digital/early-careers-framework/pull/849 I'd like to rule out the time traveler as well.
=> Temporarily disable time traveler

app/models/npq_validation_data.rb, spec/models/npq_validation_data_spec.rb
Follow up of https://github.com/DFE-Digital/early-careers-framework/pull/812
=> Fixing data synchronisation on NPQValidationData updates

app/views/pages/_user_research_sign_up.html.erb
=> Update user research sign up links

.github/workflows/deploy_to_dev.yml, .github/workflows/review.yml, terraform/app/modules/paas/main.tf, terraform/app/modules/paas/variables.tf, terraform/app/terraform.tf, terraform/app/variables.tf
=> Set dockerhub credentials for review and dev

.github/workflows/deploy_to_production.yml, .github/workflows/deploy_to_sandbox.yml, .github/workflows/deploy_to_staging.yml, terraform/app/modules/paas/main.tf
=> Set dockerhub credentials for sandbox, staging and prod

db/seeds/test_data.rb
Exactly the same as we did for FIP schools
=> Add participant validation test data for CIP schools

.github/workflows/review.yml, .github/workflows/smoke_test.yml, README.md, db/seeds/test_data.rb, spec/smoke_tests/participant_declarations_spec.rb, spec/turnip_helper.rb
We want some smoke tests. As in, tests running against something that is not a test environment. For starters I will put it against a review app.
=> CPDTP-421: Add a smoke test to participant declaration endpoints

app/controllers/participants/validations_controller.rb, app/views/participants/validations/complete_cip.html.erb, app/views/participants/validations/complete_fip.html.erb, app/views/participants/validations/manual_details_check_cip.html.erb, spec/features/participants/happy_validation_journeys_for_ect_cip_spec.rb, spec/features/participants/happy_validation_journeys_for_ect_fip_spec.rb, spec/features/participants/happy_validation_journeys_for_mentor_cip_spec.rb, spec/features/participants/participant_validation_steps.rb, spec/features/participants/sit_mentor_fip_validation_journeys_spec.rb, spec/features/participants/unhappy_validation_journeys_for_cip_spec.rb, spec/features/participants/unhappy_validation_journeys_for_ect_fip_spec.rb
Some temporary copy changes for the validation journey. I've added tickets to revert when we can
=> Update validation success messages

app/views/admin/schools/participants/index.html.erb
Sadly there are no tests for this view, but Percy did catch this change.
I'll return to the tests.
=> Add new participant status tag to school participants page

app/views/schools/participants/show.html.erb
Remove some copy from participant details page, as requested in https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-842
=> Remove participant detail copy

swagger/v1/api_spec.json, swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
Small change to the wording in the swagger doc
=> Tweak swagger doc wording for eligible_for_payment

lib/tasks/valid_test_data_generator.rb
One of our providers has asked for different data as a replacement in the sandbox. This adds in a script to safely remove the old data.
Remove the participants and schools added as part of the old data population script before adding in the new data.
=> CPDTP-437 update ambition institute on the sandbox

app/views/schools/cohorts/show.html.erb
CPDRP-910
Want to show different link text if induction tutor has added some participants
=> CPDRP-910: Make participants link text conditional

swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantCsvRow.yml, swagger/v1/component_schemas/MultipleECFParticipantsCsvResponse.yml, swagger/v1/component_schemas/MultipleECFParticipantsResponse.yml
I hate writing api documentation 😭
=> Add training status to some more places in docs

app/controllers/schools/participants_controller.rb, app/mailers/participant_mailer.rb, spec/requests/schools/participants_request_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-879
=> Cpdrp 879 partticipant deleted notification

app/views/check_account/show.html.erb, app/views/nominations/request_nomination_invite/choose_location.html.erb, app/views/nominations/request_nomination_invite/choose_school.html.erb, app/views/nominations/request_nomination_invite/resend_email.html.erb, app/views/nominations/request_nomination_invite/review.html.erb, app/views/nominations/request_nomination_invite/success.html.erb, app/views/start/index.html.erb, app/views/users/sessions/link_invalid.html.erb, app/views/users/sessions/login_email_sent.html.erb, app/views/users/sessions/new.html.erb, app/views/users/sessions/redirect_from_magic_link.html.erb, app/views/users/sessions/signed_out.html.erb, spec/cypress/integration/CheckAccount.feature, spec/cypress/integration/aaa-meta/cypress.js, spec/cypress/support/step_definitions/notifications.js, spec/support/features/interaction_helper.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-815?atlOrigin=eyJpIjoiYjNkYmQ5ZjM1MWZmNDAzODk5ZDRmYTc5ZjhlZmI4MmYiLCJwIjoiaiJ9
=> Cpdrp 815 content

app/mailers/school_mailer.rb, app/services/utm_service.rb, app/services/validation_beta_service.rb, db/migrate/20210909154906_add_reminder_email_sent_at_to_induction_coordinator_profiles.rb, db/schema.rb
https://dfedigital.atlassian.net/browse/CPDRP-931
https://docs.google.com/spreadsheets/d/1612Jquh5GhCuvcESfiVIBjBp42ZJmA8p2Bkg8SXc0Jk/edit#gid=0
=> Service to send reminders to STIs

app/services/validation_beta_service.rb
https://docs.google.com/spreadsheets/d/1612Jquh5GhCuvcESfiVIBjBp42ZJmA8p2Bkg8SXc0Jk/edit#gid=0
We do not want to ask withdrawn participants to add their details. Since SIT mentors will reaceive the separate email, sending generic mentor emails to them would be just a duplication.
=> Minor correctio to validation reminder emails

app/services/validation_beta_service.rb, spec/services/validation_beta_service_spec.rb
https://docs.google.com/spreadsheets/d/1612Jquh5GhCuvcESfiVIBjBp42ZJmA8p2Bkg8SXc0Jk/edit#gid=0
1. We ensure we only notifies SIT about us notifying their participants that they've added after 7th of September
2. We ensure we do not notify SIT of opt-out cohorts
=> Preparing Sit's participants notified emails

app/services/validation_beta_service.rb
Please don't judge me - you missed that as well... :D:D:D
=> Fixed a silly bug in 'we have asked your participants' email

app/views/lead_providers/guidance/release_notes.html.erb
Add release notes for https://github.com/DFE-Digital/early-careers-framework/pull/1041
=> Add pupil_premium_uplift and sparsity_uplift sharing to release notes

README.md, app/jobs/school_analytics_job.rb, app/models/analytics/ecf_school.rb, app/models/school.rb, app/services/analytics/ecf_school_service.rb, db/analytics_migrate/20210915160357_create_ecf_school.rb, db/analytics_schema.rb
I  have been dumping CSV files with this information far too regularly. It's time that stopped.
None
=> Export school analytics data to analytics database every hour

config/database.yml
Ticket: n/a
- Fixes parallel rspec test suite
- n/a
- none
=> fix parallel rspec suite

lib/tasks/cron.rake
Turns out cron jobs only run if you schedule them... I've scheduled this one manually, but it should be here too
=> Schedule analytics job

app/services/analytics/ecf_school_service.rb
Based on https://github.com/rails/rails/issues/7112#issuecomment-30514153
=> Experiment with reducing retained memory

app/jobs/participant_details_reminder_job.rb
As mentioned on sprint review, increase chaser delay from 3 to 7 days
=> Increase chaser delay to 7 days

spec/features/participants/participant_validation_steps.rb, spec/features/schools/dashboard/manage_training_steps.rb
I'm really hoping this is going to stop the constant Percy changes
=> Prevent changes in visual tests

.github/workflows/deploy_to_staging.yml
https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#multiline-strings
=> Use correct syntax for multiline strings

.github/workflows/brakeman-analysis.yml
> Brakeman is a static analysis tool which checks Ruby on Rails applications for security vulnerabilities.
https://github.com/presidentbeef/brakeman
=> Add Brakeman

app/services/analytics/ecf_school_service.rb
It's not perfect and will need revisiting when we have more cohorts we're interested in, but 2020 school cohort are breaking analytics
=> Use current cohort for analytics

config/initializers/rswag_ui.rb, spec/features/swagger_page_spec.rb
Swagger docs are broken.
My best guess is one of our upgrades changed something - I don't quite know what, and I don't really feel like digging.
Tests to follow tomorrow :P
=> Fix swagger

app/mailers/school_mailer.rb, app/mailers/user_mailer.rb, app/services/create_induction_tutor.rb, spec/features_helper.rb, spec/mailers/school_mailer_spec.rb, spec/services/create_induction_tutor_spec.rb
Ticket: CPDRP-928
Kate asked for some changes to variables in notify templates
=> CPDRP-928: template updates

db/seeds/schedules.rb
Because we finally agreed that people who are on a january schedule should not be declared as started until january.
I will need to run an update in sandbox and prod for it to work.
=> Set start date of january schedules to january

app/views/step_by_step/show.html.erb
Update to clarify that schools should contact teaching school hubs for guidance in step-by-step guide.
[CPDRP-982](https://dfedigital.atlassian.net/browse/CPDRP-982)
Changes:
- Copy updates (as per ticket)
- Removed whitespaces in class names
=> CPDRP-982 Update to step-by-step copy

app/components/participant_status_tag_component.rb, app/models/email.rb, spec/components/participant_status_tag_component_spec.rb, spec/factories/email.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-873
=> Added request_for_details email status to participant_status_tag component

app/components/participant_status_tag_component.rb, spec/components/participant_status_tag_component_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-873
=> Updated email-bounced tag text

app/mailers/school_mailer.rb, app/services/validation_beta_service.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-994
I don't think warrants tests, but some keen eyes would be appreciated. Plan is send tomorrow morning and then revert this PR.
=> Remind FIP SITs to add ECTs and mentors

app/services/analytics/ecf_school_service.rb
We've got all we need from this, looks like the enhanced GC helped a bit
=> Remove sentry object reporting

db/seeds/initial_seed.rb, etc/schema/0.3/npq/participant_declarations/retained/create/request_schema.json, etc/schema/0.3/npq/participant_declarations/started/create/request_schema.json, etc/schema/0.3/npq/participants/actions/request_schema.json, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQApplicationAttributes.yml, swagger/v1/component_schemas/NPQApplicationCsvRow.yml, swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml, swagger/v1/component_schemas/NPQParticipantStartedDeclaration.yml, swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml, swagger/v1/component_schemas/ParticipantDeclarationCsvRow.yml
Ticket: https://trello.com/c/yOJFfO9p/555-build-aso-journey
- Adds new ASO `NPQCourse` to the seeds
- I'm not sure how safe it is to run this seeds file in production and production like environments so I will do this by hand after deployment. Review apps seem to pick up on it
- The guids are hard coded so they will be the same across all environments.
- `cf ssh ecf-review-pr-1184`
- `NPQCourse.all`
- Should now see 7 courses with the new ASO course present
- Adds new `NPQCourse`
- I've updated swagger docs
=> Seed ASO NPQCourse

app/services/participants/defer/ecf.rb, app/services/participants/defer/npq.rb, app/services/participants/withdraw/ecf.rb, app/services/participants/withdraw/npq.rb, docs/source/release-notes.html.erb, spec/docs/participants_spec.rb, spec/features/participant-declarations/participant_declaration_steps.rb, spec/requests/api/v1/participants_spec.rb, spec/services/participants/defer/early_career_teacher_spec.rb, spec/services/participants/defer/mentor_spec.rb, spec/services/participants/defer/npq_spec.rb, spec/services/participants/withdraw/early_career_teacher_spec.rb, spec/services/participants/withdraw/mentor_spec.rb, spec/services/participants/withdraw/npq_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantChangeSchedule.yml, swagger/v1/component_schemas/ECFParticipantDefer.yml, swagger/v1/component_schemas/ECFParticipantWithdraw.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-523
=> CPDTP-523: Update deferral and withdrawal reasons

spec/features/schools/dashboard/manage_training_steps.rb
https://percy.io/c72bbcf6/early-careers-framework/builds/13118595/changed/740978777?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=1280
=> Remove randomness from percy snapshot

app/models/api_token.rb
Because deleting or updating them by accident can lead to some fun conversations.
=> Add papertrail to api tokens

db/seeds/test_data.rb, lib/tasks/sandbox_data.rake, lib/tasks/valid_test_data_generator.rb
As we move towards testing with NPQ providers, I think we will find this pretty useful.
=> Add npq dumy data seeding

app/components/schools/participants/remove_from_cohort_component.rb, spec/factories/ecf_participant_eligibility.rb, spec/features/schools/participants/remove_from_cohort_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-1021
=> Allowing deletion of the ineligible participant

app/views/nominations/request_nomination_invite/resend_email.html.erb, app/views/step_by_step/show.html.erb
Ticket: [934](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-934) - Back link on resend email page
[1025](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-1025) - Link to roles page from step by step guidance
3. To see get to the roles guidance page you'll need to log in.
=> CPDRP 1025 update links on step by step guidance

app/services/analytics/ecf_validation_service.rb
As we start to mark participants as ineligible, record this in analytics data for dashboard
=> Show ineligible participants in analytics

app/controllers/schools/base_controller.rb, spec/requests/schools/cohort_spec.rb
Fixes https://sentry.io/organizations/dfe-bat/issues/2721505226/?project=5748989&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
=> Correct redirect when no programme is chosen

app/controllers/schools/cohorts_controller.rb, app/views/pages/what_each_person_does.html.erb, app/views/schools/cohorts/roles.html.erb, app/views/shared/_roles.html.erb, app/views/step_by_step/show.html.erb
Fixes https://sentry.io/organizations/dfe-bat/issues/2714281077
Ticket: CPDRP-883
Make the roles page publicly accessible
=> CPDRP-883: make roles page accessible to all

app/controllers/concerns/api_auditable.rb, app/jobs/api_request_job.rb, app/middlewares/api_request_middleware.rb, app/models/api_request.rb, app/models/api_request_audit.rb, app/models/data_studio_api_token.rb, app/models/engage_and_learn_api_token.rb, app/models/lead_provider_api_token.rb, app/models/npq_registration_api_token.rb, config/environments/deployed_development.rb, config/environments/development.rb, config/environments/production.rb, config/environments/sandbox.rb, config/environments/staging.rb, config/environments/test.rb, db/migrate/20211019142759_create_api_request.rb, db/schema.rb, spec/jobs/api_request_job_spec.rb, spec/middlewares/api_request_middleware_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-562
Apply fire off a background job to store the api requests. I can look into doing that as well, if we think it would cause a noticable hit in performance.
This stores significantly more than `ApiRequestAudit`, so I intend to remove that in a later PR.
=> CPDTP-562: Add Apply setup for tracing requests

config/initializers/secure_headers.rb
=> Add new swagger domain to csp

app/webpacker/packs/application.js, package.json, yarn.lock
Ticket: none
- Fixes IE issues and promises
- Should resolve sentry errors titled `'Promise' is undefined`
- Tested on IE11
- Use IE11
- Visit https://ecf-review-pr-1386.london.cloudapps.digital
- open developer tools
- reject cookies
- there should be no errors in console
- clear cookies
- Visit https://ecf-review-pr-1386.london.cloudapps.digital
- accept cookies
- there should no no errors in console
- There are no external api changes
=> fix js promise for IE

terraform/workspace-variables/production.tfvars, terraform/workspace-variables/staging.tfvars
As promised in retro. Memory for everyone!
=> Double worker memory

app/mailers/participant_validation_mailer.rb, app/mailers/school_mailer.rb, app/services/utm_service.rb, app/services/validation_beta_service.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CPDRP-1090)
Add FIP SIT and participant mailers for validation deadline
No specs added yet but this is an urgent one!
=> CPDRP-1090:  Mailers for SITs and participants for validation deadline

app/serializers/npq_application_csv_serializer.rb, app/serializers/npq_application_serializer.rb, app/serializers/npq_participant_serializer.rb, app/serializers/participant_declaration_serializer.rb, app/serializers/participant_serializer.rb, docs/source/release-notes.html.erb, spec/requests/api/v1/ecf_participants_spec.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/requests/api/v1/npq_participants_spec.rb, spec/requests/api/v1/participant_declarations_spec.rb, spec/requests/api/v1/participants_spec.rb, spec/serializers/npq_participant_serializer_spec.rb, spec/serializers/participant_serializer_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantAttributes.yml, swagger/v1/component_schemas/MultipleECFParticipantsCsvResponse.yml, swagger/v1/component_schemas/MultipleNPQApplicationsCsvResponse.yml, swagger/v1/component_schemas/NPQApplicationAttributes.yml, swagger/v1/component_schemas/NPQApplicationCsvRow.yml, swagger/v1/component_schemas/NPQParticipantAttributes.yml, swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml, swagger/v1/component_schemas/ParticipantDeclarationCsvRow.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-595
=> CPDLP-595 add updated at to participants, applications, declarations endpoints

app/models/school_cohort.rb, app/views/schools/choose_programme/confirm_programme.html.erb, app/views/schools/choose_programme/success.html.erb, app/views/schools/cohorts/change_programme.html.erb, app/views/schools/cohorts/programme_choice.html.erb, app/views/schools/dashboard/show.html.erb, config/locales/schools/induction_choice_form.yml, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/models/school_cohort_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-995
Changes copy for school funded fip
=> [CPDRP-995] Change copy for school_funded_fip

db/migrate/20211109123017_add_user_declaration_integrity.rb, db/migrate/20211109123940_validate_user_declaration_integrity.rb, db/schema.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-622
- so users cannot be deleted if they have participant_declarations
- this must be resolved by hand first
- ssh in the review app
- find or create a user with a participant declaration
- attempt to `destroy` the user
- should fail to destroy due to foreign key constraint
=> CPDLP-622 add foreign key constraint between users and participant_declarations

app/mailers/school_mailer.rb, app/services/invite_schools.rb, spec/services/invite_schools_spec.rb
Email to unpartnered schools who chose FIP
=> CPDRP-1107: Setup unpartnered fip chaser emails

app/services/finance/ecf/participant_payable_aggregator.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-624
- Fixes not paid row in payable payment breakdown
- This was due to expected duck type that was not followed through
- Previously blank, will now show zero or correct value
- I tried to implement a test for this but requires quite a lot of layer to setup a component test I did not consider it worthwhile in this scenario
- https://ecf-review-pr-1415.london.cloudapps.digital
- login as a finance user
- view a provider payment breakdown
- look at payable view
- should see figure for `Total not paid` rather than a blank
=> CPDLP-624 Fixes not paid row in payable payment breakdown

README.md
[Ticket: https://dfedigital.atlassian.net/browse/CPDLP-653](https://dfedigital.atlassian.net/browse/CPDLP-613)
Update Readme to include instructions on importing JSON spec
=> CPDLP-613 Update Readme to include instructions on how to import JSON spec into Postman

app/services/invite_schools.rb, config/initializers/delayed_job.rb, lib/devise/strategies/passwordless_authenticatable.rb, spec/cypress/cypress_helper.rb, terraform/workspace-variables/dev.tfvars, terraform/workspace-variables/production.tfvars, terraform/workspace-variables/review.tfvars, terraform/workspace-variables/sandbox.tfvars, terraform/workspace-variables/staging.tfvars
We can deliver these out of out-of-band. This will automatically give us [redelivery](https://sentry.io/organizations/dfe-bat/issues/2756441853/?environment=production&project=5748989&query=is%3Aunresolved) were Notify be down.
=> Enqueue sign in emails to be delivered

app/services/analytics/ecf_school_service.rb, db/analytics_migrate/20211112150638_add_sparsity_premium_to_ecf_schools.rb, db/analytics_schema.rb
Add data to schools' table in analytics
=> Add sparsity and premium to schools

db/seeds/schedules.rb, docs/source/_ecf_usage_participant_actions.html.erb, spec/factories/finance/schedules.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-667
- Started milestone has been updated
- These changes ensure seed data matches
- see updated content at https://ecf-review-pr-1429.london.cloudapps.digital/api-reference/ecf-usage.html#notifying-of-schedule-change-standard-induction-september
- docs have been updated with new milestone date
=> CPDLP-667 update milestone dates

spec/requests/api/v1/participant_declarations_spec.rb
(ticket)[]
https://dfedigital.atlassian.net/browse/CPDLP-683
=> [CPDLP-683] - fix partiticant declarations CSV index ignoring page params spec

app/controllers/finance/ecf/payment_breakdowns_controller.rb, app/models/finance/invoice.rb, app/services/finance/calculation_orchestrator.rb, app/services/finance/ecf/participant_eligible_aggregator.rb, app/services/finance/npq/calculation_orchestrator.rb, app/services/finance/npq/participant_eligible_aggregator.rb, app/services/finance/participant_aggregator.rb, app/views/finance/ecf/payment_breakdowns/show.html.erb, config/routes.rb, spec/services/finance/ecf/participant_eligible_aggregator_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-624
- Introduces an invoices concept
- Invoices are merely a collection of intervals
- Where interval is a start timestamp and end timestamp
- Later maybe `payment_breakdown` could be moved into `Invoice` for convenience
- I've hard coded Invoices for now, later if we want we can move these into the database
- not realistically possible given our state of dummy data
=> CPDLP-624 Introduce invoices concept

lib/sti_preload.rb
fixes this sentry error: https://sentry.io/organizations/dfe-bat/issues/2807870432/?project=5748989&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
=> Fix Single Table inheritence preloader

app/mailers/participant_mailer.rb, app/services/utm_service.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-1165
=> [CPDRP-1165] Update automated ppt validation invitations and reminders

app/mailers/participant_mailer.rb
Wrong type in ParticipantMailer
=> Cast string to symbol in ParticipantMailer

docs/source/_ecf_usage_participant_actions.html.erb, docs/source/_npq_usage_participant_actions.html.erb, swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantChangeSchedule.yml, swagger/v1/component_schemas/ECFParticipantChangeScheduleAttributes.yml, swagger/v1/component_schemas/ECFParticipantDefer.yml, swagger/v1/component_schemas/ECFParticipantDeferAttributes.yml, swagger/v1/component_schemas/ECFParticipantResume.yml, swagger/v1/component_schemas/ECFParticipantResumeAttributes.yml, swagger/v1/component_schemas/ECFParticipantWithdraw.yml, swagger/v1/component_schemas/ECFParticipantWithdrawAttributes.yml, swagger/v1/component_schemas/NPQParticipantDefer.yml, swagger/v1/component_schemas/NPQParticipantDeferAttributes.yml, swagger/v1/component_schemas/NPQParticipantResume.yml, swagger/v1/component_schemas/NPQParticipantResumeAttributes.yml, swagger/v1/component_schemas/NPQParticipantWithdraw.yml, swagger/v1/component_schemas/NPQParticipantWithdrawAttributes.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-720
Double checks that all the links are pointing to the correct location in the docs
=> [CPDLP-720] - fix api documentation for withdraw defer resume and change schedule

app/views/lead_providers/partnerships/show.html.erb, app/views/nominations/request_nomination_invite/resend_email.html.erb, app/views/schools/choose_programme/success.html.erb, app/views/schools/year2020/remove_teacher.html.erb
- Add missing govuk-link classes
- Add missing punctuation
=> Small design fixes

spec/models/ecf_participant_eligibility_spec.rb
Mentory factory changed, now all factories are created correctly
=> Change mentor factory to new one

.github/workflows/destroy.yml
https://dfedigital.atlassian.net/browse/CST-128
=> Action to delete S3 bucket

app/controllers/api/v1/ecf_participants_controller.rb
Continuing the iterative improvments to the ECF participants API endpoint. Will monitor how this performs in production, looks good locally.
=> Further performance tweaks to ECF participants endpoint

analytics_queries/participants.sql, analytics_queries/schools.sql
Added some more fields to the data
=> Add status to participants query and metor_id to schools query

app/components/finance/npq/output_fee_row.html.erb, app/components/finance/npq/output_fee_row.rb, app/components/finance/npq/total_payment_row.html.erb, app/components/finance/npq/total_payment_row.rb, app/controllers/finance/npq/course_payment_breakdowns_controller.rb, app/views/finance/npq/course_payment_breakdowns/show.html.erb, spec/features/finance/npq/course_payment_breakdown_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CPDLP-379)
2. login as a `finance@example.com` select type of course you wish to login as, select a lead provider and inspect each individual, NPQ course to see the detailed payment breakdown.
=> [CPDLP-379] - calculate output fees

app/helpers/application_helper.rb, spec/requests/users/sessions_spec.rb
https://sentry.io/organizations/dfe-bat/issues/2830540380/?environment=production&project=5748989&query=is%3Aunresolved
=> Fixed incorrect url helper when signed in as non-validated SIT/mentor

app/views/finance/landing_page/show.html.erb, app/views/layouts/_application.html.erb
Fixes: https://sentry.io/organizations/dfe-bat/issues/2484519794/?environment=production&project=5748989&query=is%3Aunresolved
=> Fix class name spacing

app/controllers/concerns/api_token_authenticatable.rb, config/locales/en.yml, docs/README.md, docs/source/release-notes.html.erb, spec/requests/api/v1/error_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/UnauthorisedResponse.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-753
Also updates the readme in the docs folder to tell you exactly how to view the changes locally, the existing instructions don't work.
=> CPDLP-753 fix 401 content type

app/forms/participants/participant_validation_form.rb
This argument has been left out.
=> Added missing argument to validation call

app/mailers/school_mailer.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-138
=> Review SIT nomination email

terraform/monitoring/config/development/alert.rules.yml, terraform/monitoring/config/production/alert.rules.yml, terraform/monitoring/config/staging/alert.rules.yml
- Adjust alerting rules to inspect new Sidekiq worker name
- Remove dev worker alerting rules and increase memory utilization thresholds
=> Sidekiq alert rules

swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantDeferRequest.yml, swagger/v1/component_schemas/ECFParticipantResumeRequest.yml, swagger/v1/component_schemas/ECFParticipantWithdrawRequest.yml, swagger/v1/component_schemas/NPQParticipantDeferRequest.yml, swagger/v1/component_schemas/NPQParticipantResumeRequest.yml, swagger/v1/component_schemas/NPQParticipantWithdrawRequest.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-662
Add request examples to api docs
Example:
=> CPDLP-662 Add request examples to api docs

app/models/finance/schedule/npq_support.rb, db/seeds/schedules.rb, db/seeds/schedules/npq_aso.csv, db/seeds/schedules/npq_leadership.csv, db/seeds/schedules/npq_specialist.csv, spec/models/finance/schedule_spec.rb
Ticket: CPDLP-735
- Add schedules for NPQ
- `cf ssh ecf-review-pr-1486`
- confirm seeded schedules are present
- e.g. `Finance::Schedule::NPQSupport.all`
- There are no external api changes
=> CPDLP-735 add NPQ schedules

app/forms/participants/participant_validation_form.rb, app/services/importers/ecf_manual_validation.rb, lib/tasks/manual_validation.rake
Replaces #1491 
This captures some of the things I have been doing around manual validation
=> Add services and tasks for manual validation tasks

app/models/participant_declaration/npq.rb, db/seeds/test_data.rb, lib/tasks/one_off.rake
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-772
=> CDPLP-772 Add one-off task for transitioning eligible npq declarations

app/components/finance/npq/breakdown_summary.html.erb, app/components/finance/npq/contract.html.erb, app/components/finance/npq/payment_overviews/payment_courses_row.html.erb, app/components/finance/npq/payment_overviews/references.html.erb, app/components/finance/npq/total_payment_row.html.erb, app/views/finance/npq/course_payment_breakdowns/show.html.erb, spec/features/finance/npq/course_payment_breakdown_spec.rb
https://dfedigital.atlassian.net/browse/CPDLP-813
Some updates to layout of NPQ payment breakdown to make it consistent with ECF payment breakdown
Updates include
- Changing summary lists to be tables 
- Adding bold values/headers
=> CPDLP-813 fix alignment issues with NPQ payment breakdown

app/forms/participants/participant_validation_form.rb
=> Update doc comment

app/controllers/schools/participants_controller.rb, app/forms/schools/add_participant_form.rb, app/models/participant_profile.rb, app/models/participant_profile/npq.rb, app/policies/participant_profile/ecf_policy.rb, app/services/early_career_teachers/create.rb, app/services/mentors/create.rb, app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/start_term.html.erb, app/views/schools/participants/edit_start_term.html.erb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb, config/locales/en.yml, config/locales/schools/participants.yml, config/routes.rb, db/migrate/20211207115304_add_start_term_to_participant_profiles.rb, db/schema.rb, spec/features/schools/participants/add_participants_spec.rb, spec/features/schools/participants/update_participants_details_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/forms/schools/add_participant_form_spec.rb, spec/policies/participant_profile/ecf_policy_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-101
=> Select term page

spec/features/finance/npq/course_payment_breakdown_spec.rb, spec/services/finance/npq/calculation_orchestrator_spec.rb
Ticket: n/a
- the current test suite is failing due to time related tests
- the NPQ payment breakdown controller not able to display declarations for a given interval
- once this functionality is added the commented tests can be uncommented
- no user facing changes
- none
=> fix and comment NPQ tests

app/services/importers/seed_npq_schedules.rb, db/seeds/schedules.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-794
- Extract inline code to service class so it can be called from the console easily
- Should already be covered by existing tests
- should be no change
- npq seeds should be added as before
- none
=> CPDLP-794 extract seed npq mechanism to service class

app/components/finance/npq/contracts.html.erb, app/components/finance/npq/contracts.rb, app/controllers/finance/npq/contracts_controller.rb, app/views/finance/npq/contracts/show.html.erb
Feedback from https://github.com/DFE-Digital/early-careers-framework/pull/1560 that was only seen after merging
There are a few things in the codebase where the ECF version is named Thing and the npq version will be NPQThing so it is probably better to have explicit variable naming that is more closely resembling the type of the variable.
=> CPDLP-793 Be more explicit in contract variable naming

Gemfile, Gemfile.lock, app/controllers/healthcheck_controller.rb, config/initializers/delayed_job.rb, config/initializers/sentry.rb, db/migrate/20220104162036_drop_delayed_jobs.rb, db/schema.rb, terraform/app/modules/paas/main.tf, terraform/app/modules/paas/variables.tf, terraform/app/terraform.tf, terraform/app/variables.tf, terraform/workspace-variables/production.tfvars, terraform/workspace-variables/sandbox.tfvars, terraform/workspace-variables/staging.tfvars
There are no more delayed jobs left to process on production so we can eradicate it from our codebase
=> Remove delayed job

app/mailers/participant_mailer.rb, app/mailers/school_mailer.rb, app/services/invite_ects.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-172
=> Pre-term comms

app/services/record_declarations/base.rb, db/migrate/20220110103832_milestone_date_optional.rb, db/schema.rb, db/seeds/schedules.rb, db/seeds/schedules/ecf_extended.csv, db/seeds/schedules/ecf_reduced.csv, db/seeds/schedules/ecf_replacement.csv, spec/models/finance/schedule_spec.rb, spec/services/record_declarations/base_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-841
- Add new ECF schedules
- These are considered soft schedules
- This means that there is no milestone#milestone_date
- Which means declarations are not bound by a certain timeframe and can be submitted anytime after milestone 1 has started
- start a rails console in review app
- should see the presence of new schedules and milestones
- Documentation about the schedules and milestones will be added after the data has been seeded
=> [CPDLP-841] New ECF schedules

app/forms/schools/add_participant_form.rb, spec/features/schools/participants/update_participants_details_spec.rb, spec/forms/schools/add_participant_form_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-266
=> Fixed conditional logic of the participant start term header

swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantCsvRow.yml, swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml, swagger/v1/component_schemas/ParticipantDeclarationCsvRow.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-810
=> [CPDLP-810] API docs fixes

app/models/finance/schedule/npq_leadership.rb, app/models/finance/schedule/npq_specialist.rb, app/models/finance/schedule/npq_support.rb, app/models/npq_course.rb, db/seeds/schedules/npq_aso.csv, db/seeds/schedules/npq_leadership.csv, db/seeds/schedules/npq_specialist.csv, spec/factories/finance/schedules.rb, spec/models/finance/schedule_spec.rb, spec/models/npq_course_spec.rb, spec/support/with_default_schedules.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-733
- When now accepting an NPQ application it is assigned one of the "newer" schedules
- After this has been deployed, the existing applications can then be moved to the correct schedules.
- The seed changes are to fix schedules to correct dates. These data changes have already been applied by hand to deployed environments. Otherwise review app deployment fails due to the way the data is shaped
- Accept an NPQ application
- Should now be one of the new schedules
- Not really
=> [CPDLP-733] update default NPQ schedules

app/components/schools/participants/remove_from_cohort_component.html.erb, app/components/schools/participants/remove_from_cohort_component.rb, spec/components/schools/participants/remove_from_cohort_component_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-136
=> [CST-136] update content for fip sits to contact provider

app/services/record_declarations/actions/make_declarations_payable.rb, spec/services/record_declarations/actions/make_declarations_payable_spec.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CPDLP-825) 
Adapt make declaration payable to be able to handle both ECF and NPQ declarations
=> [CPDLP-825] - adapt script to transition NPQ declarations

app/services/finance/npq/calculation_overview_orchestrator.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-903
- NPQ Statements take interval into consideration
- Not sure review apps have enough data to test this scenario
- None
=> [CPDLP-903] Add missing interval to NPQ statements

app/models/participant_profile.rb, app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/start_term.html.erb, app/views/schools/participants/index.html.erb, app/views/schools/participants/show.html.erb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/requests/schools/add_participants_spec.rb
=> Post-merge cleanup: removed obsolote method ParticipantProfile.humanize_start_term

db/analytics_migrate/20220120103423_change_schedule_identifier_type.rb, db/analytics_schema.rb
I made schedule_identifier a boolean field in the analytics db but instead it should be string
I've tried rolling back and the migration seems happy, no error
=> CPDLP-878 Update schedule_identifier type

app/helpers/school_breadcrumbs_helper.rb, app/views/schools/dashboard/index.html.erb, db/schema.rb, spec/helpers/school_breadcrumbs_helper_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CST-221
=> Update 'manage schools' page content

docs/source/_ecf_usage_participant_actions.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-877
=> [CPDLP-877] Update api docs to include details for new schedule enumerators

docs/source/_ecf_usage_participant_actions.html.erb
=> Fix Febuary typo

app/views/schools/dashboard/index.html.erb
Missed right alignment for the header
=> table header should align right

app/controllers/application_controller.rb, app/controllers/concerns/current_user.rb, app/services/npq/accept.rb, app/services/store_validation_result.rb, spec/forms/participants/participant_validation_form_spec.rb, spec/models/participant_declaration_spec.rb, spec/services/npq/accept_spec.rb, spec/services/store_validation_result_spec.rb
https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?selectedIssue=CST-109
=> Cst 109 auto dedup

app/models/induction_programme.rb, app/models/induction_record.rb, app/models/participant_profile.rb, app/models/school_cohort.rb, app/services/induction/enrol.rb, db/migrate/20220127134717_create_induction_programmes.rb, db/migrate/20220127162726_create_induction_record.rb, db/migrate/20220131152926_add_default_induction_programme_to_school_cohorts.rb, db/migrate/20220131155855_add_foreign_key_to_induction_programme_on_school_cohorts.rb, db/schema.rb, spec/factories/induction_programme.rb, spec/factories/induction_record.rb, spec/models/induction_programme_spec.rb, spec/models/induction_record_spec.rb, spec/models/participant_profile_spec.rb, spec/services/induction/enrol_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CST-226)
Implement the initial changes to the data model to handle change of circumstances (i.e. different induction programme choices, different participation, moving schools).
This PR adds the `InductionProgramme` and `InductionRecord` migrations and models and add a `default_induction_programme` reference to `SchoolCohort` to allow a default programme to be set for the academic year.
These are non-breaking changes and should not impact anything currently.
The next steps will populate this data and keep it in sync and will follow in separate PR(s).
Does this change anything in our external APIs? If so, did you remember to update …
=> Data model changes (Part 1)

app/controllers/participants/validations_controller.rb, app/forms/participants/participant_validation_form.rb, app/views/participants/start_registrations/show.html.erb, app/views/participants/validations/_what_happens_next.html.erb, app/views/participants/validations/eligible.html.erb, app/views/participants/validations/ineligible.html.erb, app/views/participants/validations/previous_participation.html.erb, app/views/participants/validations/secondary_fip_mentor_eligible.html.erb, spec/features/participants/starting_registration_spec.rb, spec/forms/participants/participant_validation_form_spec.rb
Ticket: [CST-231](https://dfedigital.atlassian.net/browse/CST-231)
=> CST-231 mentor specific content updates for validation results

spec/features/finance/payment_breakdown_spec.rb
- There is a reference to a constant that has now been removed
- Swap out for hard-coded string
Ticket: n/a
- Test suite should pass
- None
=> [fix build] Removed constantized declaration type

spec/features/finance/payment_breakdown_spec.rb
A percy screenshot was taken on a page that display randomly generated UUID
causing the specs to not pass.
Added a couple more expectations to render the test a bit more robust
=> Fix ECF voided declaration in payment breakdown feature

swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQParticipantChangeScheduleAttributes.yml
Missing schedule identifier in the enums
[Ticket:](https://dfedigital.atlassian.net/browse/CPDLP-729)
=> [CPDLP-729] - Add missing schedules to enumerator - add default cohort in the docs

app/services/exporters/manual_validation.rb
A simple exporter for manual validation tasks that outputs csv data to the console.  Ensures that we're consistent in producing the data for manual validation.
=> Add exporter for manual validation tasks

bin/rspec_ci
We've got a group of tests that is taking 90+ minutes, it's slowing tests running locally as well (when run in its entirety). This should help us find what's taking the test suite so long to complete.
=> Print test name and top 10 slowest tests

app/components/schools/participants/status_table.html.erb, app/components/schools/participants/status_table.rb, app/components/schools/participants/status_table_row.html.erb, app/components/schools/participants/status_table_row.rb, app/controllers/schools/participants_controller.rb, app/helpers/dashboard_helper.rb, app/services/set_participant_categories.rb, app/views/schools/participants/_ects.html.erb, app/views/schools/participants/_mentors.html.erb, app/views/schools/participants/_not_training.html.erb, app/views/schools/participants/index.html.erb, spec/components/schools/participants/status_table_row_spec.rb, spec/components/schools/participants/status_table_spec.rb, spec/features/schools/participant_dashboard/manage_cip_participants_spec.rb, spec/features/schools/participant_dashboard/manage_fip_partnered_participants_spec.rb, spec/features/schools/participant_dashboard/manage_fip_unpartnered_participants_spec.rb, spec/features/schools/participants/remove_from_cohort_spec.rb, spec/features/schools/participants/update_participants_details_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/services/set_participant_categories_spec.rb
Ticket: [376](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-376)
[prototype](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-376#:~:text=https%3A//dfe%2Decf%2Dregister%2Dpartner.herokuapp.com/admin/preload)
Select all the participant dashboard options and either FIP or CIP when checking against prototype. Both have slightly different views. 
2. Log in as `cpd-test+tutor-10@example.com` and `school-leader@example.com`
***CIP***
***FIP***
=> Schools dashboard update

app/views/accessibility_statements/show.html.erb
A minor copy update to indicate our intention to have an accessibility audit this year.
=> Update accessibility audit copy

app/controllers/api/v1/npq_profiles_controller.rb, app/serializers/npq_application_csv_serializer.rb, app/serializers/npq_application_serializer.rb, db/migrate/20220224164934_add_employment_fields_to_npq_applications.rb, db/schema.rb, spec/factories/npq_application.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/services/npq/build_application_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/MultipleNPQApplicationsResponse.yml, swagger/v1/component_schemas/NPQApplicationAttributes.yml
npq-application is now also sending us employment details which we need to store: https://github.com/DFE-Digital/npq-registration/pull/330
=> Storing NPQApplication employment answers

spec/cypress/integration/CheckAccount.feature
I managed to merge the [PR](https://github.com/DFE-Digital/early-careers-framework/pull/1752) despite CI failing.
=> Fix check account feature

Gemfile, Gemfile.lock
Ticket: n/a
- this is no longer used
- it was used to auth with dqt server
- auth mechanism now no longer has jwt in the flow
- Not really
- App should behave as it did before
- None
=> remove jwt gem

docs/source/_ecf_usage_participant_actions.html.erb, docs/source/_npq_usage_participant_actions.html.erb, docs/source/_usage_participant_declarations.html.erb, docs/source/ecf-usage.html.erb, docs/source/index.html.erb, docs/source/npq-usage.html.erb
Ticket: n/a
- Fixes broken links in docs due to renaming of files to prepare for v2 api
- Visit docs in review apps
- Should no longer see broken links in usage guides
- None
=> fix broken links in docs

analytics_queries/declarations.sql, analytics_queries/participants.sql
- Added `state` to Declarations
- Added `trn_validated_reason` to Participants
=> Update analytics queries

terraform/monitoring/config/development/alert.rules.yml, terraform/monitoring/config/production/alert.rules.yml, terraform/monitoring/config/staging/alert.rules.yml
Ticket: n/a
- Set CPU alerting threshold to 90%
- This should remove alerts for when the app is just a bit warm
- n/a
- None
=> high CPU alerts threshold now 90%

docs/source/_npq_usage_participant_actions.html.erb, docs/source/npq-usage.html.erb
=> [CPDLP-1047] - add additional docs for NPQ change participant schedule

app/jobs/npq/stream_big_query_enrollment_job.rb, spec/jobs/npq/stream_big_query_enrollment_job_spec.rb
[Ticket](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1080)
=> [CPDLP-1080] - Stream employer name and employemt role

app/views/schools/add_participants/email.html.erb
=> removed paragraph copy that is no longer required

app/jobs/npq/stream_big_query_enrollment_job.rb, app/jobs/npq/stream_big_query_profile_job.rb, app/models/npq_application.rb, spec/jobs/npq/stream_big_query_enrollment_job_spec.rb, spec/jobs/npq/stream_big_query_profile_job_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1135
- otherwise when new columns are added here but not the schema
- BigQuery will reject the stream
- also change to use `after_commit` to prevent race condition
- n/a
- None
=> [CPDLP-1135] fix ensure new columns reach BigQuery for NPQ

app/services/store_validation_result.rb, spec/services/store_validation_result_spec.rb
We don't want to send these emails to limit the impact on support
=> Fix bug where no_induction participants were marked as being exempt from induction

app/models/call_off_contract.rb, app/models/finance/statement.rb, app/models/npq_contract.rb, db/migrate/20220323153648_add_cohort_to_contracts.rb, db/migrate/20220323155658_add_belongs_to_cohort_to_statements.rb, db/schema.rb, lib/tasks/one_offs.rake, spec/models/call_off_contract_spec.rb, spec/models/finance/statement_spec.rb, spec/models/npq_contract_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CPDLP-1149)
TODO: remove optionals and foreign_key constraints in a subsequent PR **to be deployed separately**
=> [CPDLP-1149] - Make statements cohort sensitive

config/initializers/sentry.rb
Ticket: n/a
- Working on replacement endpoint which is super slow for csv
- Need this to debug why, probably missing an n+1
- n/a
- None
=> force sentry to log peformance for test endpoint

app/services/record_declarations/base.rb, spec/features/participant_declarations/participant_declaration_steps.rb, spec/services/record_declarations/retained/npq_spec.rb, spec/services/record_declarations/started/npq_spec.rb, spec/services/record_participant_declaration_spec.rb, spec/shared/context/service_record_declaration_params.rb
Ticket: n/a
- Inline tests from shared test setup
- Also fixed non-deterministic tests. These have now been pinned
=> Fix tests + localize test setup for npq start declarations

lib/tasks/one_offs.rake, terraform/workspace-variables/dev.tfvars, terraform/workspace-variables/review.tfvars
run backfill rake tasks upon deployment before running migrations
=> [CPDLP-1150] - Add data migration task to web app start command

app/serializers/api/v1/participant_from_induction_record_serializer.rb, spec/requests/api/v1/test_ecf_participants_spec.rb
- Nullify email in more cases to match existing behaviour
- n/a
- None
=> [CPDLP-1159] nullify email in more circumstances

db/seeds/dummy_structures.rb
Adds induction programmes and enrols participants into the programmes in the seed data so that the change of circumstances data is in place.
=> Change of circumstances: Add induction records to seeds

app/controllers/admin/suppliers/supplier_users_controller.rb, app/views/admin/suppliers/supplier_users/index.html.erb
=> Kaminary replaced by Pagy for Suppliers Users admin

app/controllers/admin/schools_controller.rb, app/views/admin/schools/index.html.erb
=> Kaminari replaced by Pagy for Schools admin

app/controllers/schools/dashboard_controller.rb, app/views/schools/dashboard/index.html.erb
=> Kaminari replaced by Pagy for Schools dashboard

app/services/partnerships/report.rb, spec/services/partnerships/report_spec.rb
When a FIP induction programme is chosen for a cohort the partnership may not have been reported so the `InductionProgramme` will not have an associated partnership.
This PR add the partnership to the induction programme when the partnership is reported given that the programme is FIP and no partnership has already been set on the programme.
The other scenarios such as changing provider will be handled via front-end journeys to be added later.
=> Change of Circumstances: Add partnership to fip programme when reported

app/controllers/admin/participants_controller.rb, db/seeds/dummy_structures.rb, spec/requests/admin/participants_spec.rb
Changes the query on the admin participants view to remove `school_cohort->participant_profile` dependency
=> Change of Circumstances: Update admin participants list

app/controllers/api/v1/participants_controller.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1222
- this is the last remaining v1 endpoint still using the old serializer
- n/a
- Changes are transparent
=> [CPDLP-1222] Endpoint uses induction record serializer

app/controllers/api/v1/ecf_participants_controller.rb, app/serializers/api/v1/participant_from_induction_record_serializer.rb, spec/requests/api/v1/ecf_participants_spec.rb, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v1/test_ecf_participants_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1223
- Serialize more things from the induction record: school, mentor, cohort
- Also fixed eager loading
- n/a
- Change should be transparent
=> [CPDLP-1223] Serialize more things from induction record

Gemfile, Gemfile.lock, app/components/admin/participants/table.html.erb, app/components/admin/participants/table.rb, app/components/lead_providers/your_schools/table.html.erb, app/components/lead_providers/your_schools/table.rb, spec/components/lead_providers/your_schools/table_spec.rb
Ticket: CTS-587
Final PR to remove Kaminari and replace it with Pagy.
=> Replace Kaminari with Pagy

app/views/admin/participants/_history.html.erb, app/views/schools/dashboard/show.html.erb, bin/scenarios_ci, spec/features/scenarios/changes_of_circumstance/onboarding_a_deferred_participant_spec.rb, spec/features/scenarios/changes_of_circumstance/onboarding_a_withdrawn_participant_spec.rb, spec/features/scenarios/changes_of_circumstance/transferring_a_participant_spec.rb, spec/support/features/apis/ecf_participants_endpoint.rb, spec/support/features/pages/sit_participants_dashboard.rb, spec/support/features/pages/sit_transfer_participant_wizard.rb, spec/support/features/steps/changes_of_circumstance_steps.rb, spec/support/matchers/lead_provider_api/find_participant_details_in_ecf_participants_endpoint.rb, spec/support/matchers/school_induction_portal/find_participant_details_in_school_induction_portal.rb
E2E scenarios should pass for FIP 2 FIP transfers
=> E2e scenario fixes

app/views/finance/participants/_declaration.html.erb, app/views/finance/participants/show.html.erb, spec/views/finance/participants/show.html.erb_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1132
- Add name to participant drill down
- Also adds declaration ID
- Login as finance user
- Visit participant drill down
- Find a user with a declaration
- Should now see their name
- Also the ID of declarations they have made
- None
=> [CPDLP-1132] Drill down tweaks

lib/tasks/valid_test_data_generator.rb
Ticket: n/a
- do not create declarations for new NPQ courses
- as the schedules for these are in the future
- therefore you cannot post declarations (yet) for these courses
=> fix seeding for new NPQ courses

app/views/check_account/show.html.erb, app/views/nominations/_school_details.html.erb, app/views/nominations/request_nomination_invite/choose_location.html.erb, app/views/nominations/request_nomination_invite/choose_school.html.erb, app/views/nominations/request_nomination_invite/limit_reached.html.erb, app/views/nominations/request_nomination_invite/resend_email.html.erb, app/views/nominations/request_nomination_invite/review.html.erb, app/views/nominations/request_nomination_invite/success.html.erb, app/views/start/index.html.erb, app/views/users/sessions/login_email_sent.html.erb, app/views/users/sessions/new.html.erb, db/schema.rb
=> [Design updates] - start page, sign in, check email, and how to get access journey

terraform/workspace-variables/dev.tfvars
Delete those rake tasks but forgot to remove them from the deploy pipeline
=> remove discard 

app/controllers/schools/participants_controller.rb, app/views/schools/participants/show.html.erb
Ticket: [670](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-670)
3. Login in as a SIT
4. Go to participants dashboard and select any teacher
=> [CST-670] Add start date to schools/participants/show view

db/seeds/schedules/ecf_standard.csv, spec/features/finance/schedules_spec.rb, spec/models/participant_declaration_spec.rb, spec/support/shared_examples/participant_actions_change_schedule_support.rb
Ticket: [1266](https://dfedigital.atlassian.net/browse/CPDLP-1266)
=> CPDLP 1266 - Add new ECF standard schedules for 2022 cohort

app/views/nominations/request_nomination_invite/success.html.erb
=> [ Design updates ] - Content change to sign up flow on 1 page.

app/controllers/schools/participants_controller.rb, app/forms/participant_start_term_form.rb, app/forms/schools/add_participant_form.rb, app/models/cohort.rb, app/models/participant_profile/ecf.rb, app/services/early_career_teachers/create.rb, app/services/mentors/create.rb, app/views/schools/add_participants/start_term.html.erb, app/views/schools/participants/edit_start_term.html.erb, spec/requests/schools/participants_request_spec.rb
Ticket: [683](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-683)
3 Login as a SIT
4. Go through the add participant journey
=> [CST-683] Add autumn 2022 start term

app/views/privacy_policies/show.html.erb, app/views/schools/choose_programme/confirm_programme.html.erb, app/views/schools/choose_programme/show.html.erb, app/views/schools/choose_programme/success.html.erb, config/locales/schools/induction_choice_form.yml, db/schema.rb, spec/features/schools/training_dashboard/manage_cip_training_spec.rb, spec/features/schools/training_dashboard/manage_design_our_own_training_spec.rb, spec/features/schools/training_dashboard/manage_fip_training_spec.rb, spec/features/schools/training_dashboard/manage_no_ect_training_spec.rb, spec/support/features/pages/sit_choose_programme_wizard.rb
Screens to follow. 
Includes, correct styling, headers, changed content.
=> [Design updates] -  confirm which programme first time through service

app/views/nominations/choose_how_to_continue/new.html.erb, app/views/nominations/nominate_induction_coordinator/check.html.erb, app/views/nominations/nominate_induction_coordinator/email.html.erb, app/views/nominations/nominate_induction_coordinator/email_used.html.erb, app/views/nominations/nominate_induction_coordinator/full_name.html.erb, app/views/nominations/nominate_induction_coordinator/link_expired.html.erb, app/views/nominations/nominate_induction_coordinator/link_invalid.html.erb, app/views/nominations/nominate_induction_coordinator/name_different.html.erb, app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb, app/views/nominations/nominate_induction_coordinator/start_nomination.html.erb, app/views/shared/choice_saved_no_early_career_teachers.html.erb, spec/features/nominations/nominate_induction_tutor_steps.rb
=> [Design updates] - nomination induction tutor flow

spec/features/schools/training_dashboard/manage_cip_training_spec.rb
The labels in the change induction programme were changed and one of the scenarios is failing on develop.
Update the scenario to look for the correct label.
=> Update the failing scenario to look for the correct label

app/views/users/sessions/redirect_from_magic_link.html.erb
=> Heading seems to have reverted back to wrong size - so fixed

app/views/schools/participants/index.html.erb
We no longer need this content - with go live of Multi cohort
=> [582] - removed content no longer needed as multi cohort going live

app/views/step_by_step/show.html.erb
Content updated for the new academic year, and to reflect new functionality. Please note, release is blocked until updates to the add participant journey are live (https://dfedigital.atlassian.net/browse/CST-448?atlOrigin=eyJpIjoiZjlkODE1YWUyOTE3NDViNzhiNGE5YzJjODAyYTMxZjYiLCJwIjoiaiJ9).
Ticket: https://dfedigital.atlassian.net/browse/CST-520?atlOrigin=eyJpIjoiNDU5NjczMWVkMzFjNGI2M2IxZDI1YWJmZjZiYTk4OGEiLCJwIjoiaiJ9
Please check coding is correct.
=> Update step-by-step guide

lib/tasks/exports.rake
Ticket:
https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1229
* Added rake task to export CSV `exports:ecf_m3_assurance_extract`
=> [CPDLP-1229] Create ECF M3 assurance extract

app/models/npq_application.rb, docs/source/release-notes.html.erb, spec/models/npq_application_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQApplicationAttributes.yml, swagger/v1/component_schemas/NPQApplicationCsvRow.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/NPQApplicationAttributes.yml, swagger/v2/component_schemas/NPQApplicationCsvRow.yml
- https://dfedigital.atlassian.net/browse/CN-132
- https://dfedigital.atlassian.net/browse/CPDLP-1307
- There are now new possible values for headteacher status
- Added new possible values for headteacher status for NPQ applications
- No real direct change as this change is an enablement for a later change where it can be tested
- View api docs
- Should see new possible values for headteacher status
=> add new possible values for NPQ headteacher status

app/views/schools/add_participants/_no_eligibility_record.html.erb, app/views/schools/add_participants/choose_mentor.html.erb, app/views/schools/add_participants/complete.html.erb, app/views/schools/add_participants/confirm.html.erb, app/views/schools/add_participants/do_you_know_teachers_trn.html.erb, app/views/schools/add_participants/email.html.erb, app/views/schools/add_participants/email_taken.html.erb, app/views/schools/add_participants/name.html.erb, app/views/schools/add_participants/start_date.html.erb, app/views/schools/add_participants/start_term.html.erb, app/views/schools/add_participants/who.html.erb, spec/features/schools/training_dashboard/manage_training_steps.rb
This is styling, content check, captions, and removal of anything we no longer use on the ADD ECT - TRN not known journey. 
Legend spacing will be fixed site-wide once I've removed any non-required margins etc when using the legend as a H1.
=> [Design update] -  Add ECT flow TRN not known

app/mailers/lead_provider_mailer.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-680?focusedCommentId=42140
These variables are required so that we can update the relevant templates to include this information.
=> Add lead provider name and cohort to challenge emails

app/services/npq/accept.rb, spec/services/npq/accept_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1333
- When accepting an application before this PR it rejects all other applications for the same course
- We want to limit this by cohort to scope them
- So prevent them bleeding from one another
- When accepting an NPQ application add extra scope so it only rejects those that are on the same cohort
- Create 2 pending NPQ applications from a user, for the same course but different cohorts 
- Accept one of them
- The other one should remain as pending and should not be rejected
=> [CPDLP-1333] NPQ acceptance, rejects scoped to same cohort

app/views/schools/dashboard/_setup_school_cohort.html.erb, app/views/schools/setup_school_cohort/expect_any_ects.html.erb, db/schema.rb, spec/features/schools/choose_programme/choose_programme_steps.rb, spec/features/schools/training_dashboard/manage_training_steps.rb
Change to content to give a better understanding to users to try and avoid the risk of confusion that could occur without. All based off user research feedback the last few days.
=> [Design updates] -  Multi cohort confusion fix

spec/requests/api/v1/participants_spec.rb
- Fixes flaky test
- remove superfluous induction record which has already been created in another test setup
- none
=> fix flaky tests

app/controllers/lead_providers/report_schools/delivery_partners_controller.rb, spec/cypress/app_commands/scenarios/lead_provider_with_delivery_partners.rb
=> CST-734 - duplicated delivery partners

app/helpers/application_helper.rb, app/views/schools/add_participants/cannot_find_their_details.html.erb
=> Fix participant login router so that 21/22 participants can validate

app/controllers/api/v1/npq_profiles_controller.rb, app/views/finance/participants/_npq_application.html.erb, db/migrate/20220512140603_dupe_targeted_eligibility_flag.rb, db/schema.rb, spec/requests/api/v1/npq_profiles_spec.rb, spec/views/finance/participants/show.html.erb_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1340
- eligibility flag was not correctly named
- part 1 of 2 for ECF
- will also require an NPQ change
- this duplicates a column to use
- second change will delete the old column
- none
=> [CPDLP-1340] Rename targeted funding flag

app/controllers/delivery_partners/base_controller.rb, app/controllers/delivery_partners/participants_controller.rb, app/helpers/application_helper.rb, app/mailers/delivery_partner_profile_mailer.rb, app/models/delivery_partner.rb, app/models/delivery_partner_profile.rb, app/models/user.rb, app/policies/delivery_partner_profile_policy.rb, app/views/delivery_partners/participants/index.html.erb, app/views/layouts/delivery_partners.html.erb, config/routes.rb, db/migrate/20220512133622_create_delivery_partner_profiles2.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/delivery_partner_profiles.rb, spec/factories/users.rb, spec/helpers/application_helper_spec.rb, spec/mailers/delivery_partner_profile_spec.rb, spec/models/delivery_partner_profile_spec.rb, spec/models/delivery_partner_spec.rb, spec/models/user_spec.rb, spec/policies/delivery_partner_profile_policy_spec.rb, spec/requests/delivery_partners/participants_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1254
* Created `DeliveryPartnerProfile` for users
* Added seed user `delivery-partner@example.com` for testing
* New welcome email for delivery partner users
=> [CPDLP-1254] Delivery partner role and associations added

app/components/schools/participants/remove_from_cohort_component.html.erb, app/views/schools/participants/edit_email.html.erb, app/views/schools/participants/edit_mentor.html.erb, app/views/schools/participants/edit_name.html.erb, app/views/schools/participants/edit_start_term.html.erb, app/views/schools/participants/show.html.erb, app/views/schools/transferring_participants/cannot_find_their_details.html.erb, spec/features/schools/participants/add_participants/unhappy_path_cannot_validate_spec.rb, spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb
Screens to follow. 
Removed participants details h2 as we dont need it. Added grid columns to one page and put others in correct place. Placed styling around link not just content and changed the content on some of the keys.
=> [Design updates] - Participants details page and links

.github/workflows/force_destroy.yml
=> Add workflow to force destroy review apps

app/components/delivery_partners/participants/table_row.html.erb, app/components/delivery_partners/participants/table_row.rb, app/controllers/delivery_partners/participants_controller.rb, app/views/delivery_partners/participants/index.html.erb, app/views/layouts/delivery_partners.html.erb, config/locales/en.yml, spec/components/delivery_partners/participants/table_row_spec.rb, spec/features/delivery_partners/participants_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1256
* New component added for the participants row
* Logic added to component for status column
* Pagination
=> [CPDLP-1256] Table of records with sorting logic & pagination

spec/serializers/api/v2/participant_serializer_spec.rb
=> Fix flaky spec

app/services/identity/transfer.rb, spec/services/identity/transfer_spec.rb
- Ticket: [JIRA](https://dfedigital.atlassian.net/browse/CST-679)
When de-duping has occurred and the subject was also an induction coordinator (SIT), the transfer process did not move any `InductionCoordinatorProfile`s to the new user record, meaning the SIT could no longer access the schools on their de-duped profile.
Check for and move the SIT profile/school relations to the new user.
=> Transfer SIT profile during identity transfer

app/components/delivery_partners/participants/table_row.html.erb, app/components/delivery_partners/participants/table_row.rb, app/components/search_box.html.erb, app/controllers/delivery_partners/participants_controller.rb, app/services/delivery_partners/participant_profile_status.rb, app/services/delivery_partners/participants_filter.rb, app/views/delivery_partners/participants/index.html.erb, spec/features/delivery_partners/participants_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?issueParent=39631&selectedIssue=CPDLP-1258
* Add search and filter by role, academic year and status
* Login as `delivery-partner@example.com` user
=> [CPDLP-1258] DP participants filters/search feature

app/forms/schools/add_participant_form.rb, app/views/schools/add_participants/confirm.html.erb, spec/features/schools/participants/add_participants/happy_path_with_trn_spec.rb, spec/features/schools/participants/add_participants/happy_path_without_trn_spec.rb, spec/features/schools/participants/add_participants/unhappy_path_cannot_validate_spec.rb, spec/features/schools/participants/add_participants/unhappy_path_sit_error_entering_validation_info_spec.rb, spec/features/schools/participants/update_participants_details_spec.rb, spec/forms/schools/add_participant_form_spec.rb, spec/requests/schools/add_participants_spec.rb
- Ticket: CST-702
When adding participants the start term page has been removed as not more needed having multiple cohorts.
=> CST-702 Remove start term step from add participant form

app/mailers/delivery_partner_profile_mailer.rb, app/views/delivery_partners/participants/index.html.erb, app/views/start/delivery_partners.html.erb, config/routes.rb
- Ticket:  https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?assignee=602cf8957b23f400685d969d&selectedIssue=CPDLP-1374
* Added content to DP participants page
=> [CPDLP-1374] Add warning text to DP main page

app/jobs/analytics/upsert_ecf_partnership_job.rb, app/models/analytics/ecf_partnership.rb, app/models/partnership.rb, app/services/analytics/ecf_partnership_service.rb, db/analytics_migrate/20220526112409_create_analytics_ecf_partnership.rb, db/analytics_schema.rb, spec/models/partnership_spec.rb
- Ticket: No ticket
Partnership model added to the analytics database
=> Partnership analytics

app/services/analytics/ecf_partnership_service.rb, db/analytics_migrate/20220526112409_create_analytics_ecf_partnership.rb, db/analytics_migrate/20220527123630_delete_ecf_partnership_analytics_table.rb, db/analytics_migrate/20220527124140_create_ecf_partnerships_table.rb, db/analytics_schema.rb, spec/services/analytics/ecf_partnership_service_spec.rb
=> Partnership analytics bug fixes

app/controllers/admin/delivery_partners/users_controller.rb, app/forms/delivery_partners/user_form.rb, app/models/delivery_partner.rb, app/models/user.rb, app/views/admin/delivery_partners/_heading.html.erb, app/views/admin/delivery_partners/users/index.html.erb, app/views/admin/delivery_partners/users/new.html.erb, app/views/layouts/admin/base.html.erb, config/routes.rb, spec/forms/delivery_partners/user_form_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1259
* New "Delivery partner" admin section
* List of all delivery partner users
* Add new delivery partner user
* Login as admin, go to "Delivery partner" section
=> [CPDLP-1259] Set up UI for dfe support to manage users

app/serializers/api/v1/npq_application_serializer.rb, app/serializers/api/v2/npq_application_serializer.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/requests/api/v2/npq_applications_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQApplicationAttributes.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/NPQApplicationAttributes.yml
- [CPDLP-1377](https://dfedigital.atlassian.net/browse/CPDLP-1377)
=> [CPDLP-1377] - Expose private child care URN for NPQ application response

spec/docs/v1/participants_spec.rb
The swagger docs spec/docs/v1/participants_spec.rb spec were mistakenly erased by spec/requests/api/v1/participants_spec.rb
=> reinstate swagger doc spec

db/migrate/20220530141418_add_national_institute_of_teaching_npq_lead_provider.rb, db/schema.rb, db/seeds/initial_seed.rb
- Ticket: https://dfedigital.atlassian.net/browse/CN-92
Add NIoT to list of NPQLeadProviders and CPDLeadProviders. Blocked pending confirmation of VAT status.
=> [CN-92] Add NIoT to list of NPQLeadProviders

app/models/participant_declaration/ecf.rb, spec/factories/delivery_partners.rb, spec/features/finance/payment_breakdown_spec.rb
- Ticket:  n/a
Some fixes:
1. Error message was repeating "Declaration date"
2. Delivery partner in factory was being randomised and causing Percy to create new pages
3. Syntax in spec file was incorrect
=> Fixes for test syntax and copy

app/serializers/api/v1/npq_application_csv_serializer.rb, app/serializers/api/v1/npq_application_serializer.rb, docs/source/release-notes.html.erb, spec/factories/npq_application.rb, spec/requests/api/v1/npq_applications_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQApplicationAttributes.yml, swagger/v1/component_schemas/NPQApplicationCsvRow.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1388
- Added `cohort` to NPQ applications for lead provider API
- Updated documentation accordingly
- Updated release notes for upcoming release
- n/a
=> [CPDLP-1388] Expose Cohort on NPQ applications

app/serializers/api/v1/npq_application_csv_serializer.rb, app/serializers/api/v2/npq_application_csv_serializer.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/requests/api/v2/npq_applications_spec.rb
- Ticket: [CPDLP-1389 ](https://dfedigital.atlassian.net/browse/CPDLP-1389)
Add private_childcare_provider_urn to csv (v1 & v2)
=> CPDLP-1389 Add private_childcare_provider_urn to csv

app/models/participant_profile/npq.rb
- Ticket: n/a
- Incorrect funding flag shown in finance interface
- Finance interface exposes correct funding flag for NPQ applications
- None
=> npq funding checks previous acceptances

app/models/npq_course.rb, app/services/finance/npq/course_statement_calculator.rb, app/services/npq/accept.rb, lib/tasks/valid_test_data_generator.rb, spec/factories/participant_profiles.rb, spec/features/finance/npq/course_payment_breakdown_spec.rb, spec/models/npq_course_spec.rb, spec/services/npq/accept_spec.rb
- Ticket: n/a
- When accepting a 2022 NPQ application it was assigning a 2021 schedule
- Accepting a 2022 NPQ application now assigns a 2022 schedule
- none
=> NPQ 2022 acceptance and schedule

db/seeds/schedules/npq_leadership.csv, db/seeds/schedules/npq_specialist.csv
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1394
- Add missing 2022 NPQ schedules
- n/a
=> [CPDLP-1394] add 2022 NPQ schedules

app/controllers/admin/delivery_partners/users_controller.rb, app/forms/delivery_partners/create_user_form.rb, app/forms/delivery_partners/update_user_form.rb, app/models/delivery_partner_profile.rb, app/views/admin/delivery_partners/users/delete.html.erb, app/views/admin/delivery_partners/users/edit.html.erb, app/views/admin/delivery_partners/users/index.html.erb, config/routes.rb, spec/features/admin/delivery_partners/users_spec.rb, spec/forms/delivery_partners/create_user_form_spec.rb, spec/forms/delivery_partners/update_user_form_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1386
* Edit DP user
* Delete DP user
* Login as admin user and go to DP from top menu
=> [CPDLP-1386] Enable support user to manage (edit name/email and remove) existing DP users

app/components/delivery_partners/participants/table_row.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1403
* Fix for DP participants email and school
=> [CPDLP-1403] DP participants fix for email and school

app/services/participants/withdraw/ecf.rb, app/services/participants/withdraw/npq.rb
[CPDLP-1380](https://dfedigital.atlassian.net/browse/CPDLP-1380)
Add an extra reason to be able to delete with an admin only reason.
=> [CPDLP-1380] - add started in error withdrawal reason

app/controllers/admin/schools_controller.rb, app/policies/school_policy.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1411
* Updated `SchoolPolicy` to not filter when in `sandbox` environment as admin.
=> [CPDLP-1411] Do not filter schools in admin for sandbox

app/jobs/import_gias_data_job.rb
Having manually run the `DataStage::ProcessSchoolChanges` service successfully several times now, this PR updates the GIAS import job to call this service once it has imported any changes.
=> Update and GIAS importer job to process updates

app/serializers/api/v2/npq_application_serializer.rb, app/serializers/api/v2/npq_participant_serializer.rb, spec/serializers/api/v2/npq_application_serializer_spec.rb, spec/serializers/api/v2/npq_participant_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1412
* Added `targeted_delivery_funding_eligibility` to `V2::NPQParticipantResponse` and `V2::NPQApplicationResponse`
=> [CPDLP-1412] Add targeted delivery eligibility to npq participant response

app/views/schools/transferring_participants/schools_current_programme.html.erb
Fixes https://sentry.io/organizations/dfe-teacher-services/issues/3330423358/?environment=production&project=5748989&query=is%3Aunresolved&sort=freq&statsPeriod=14d
=> Fix nil checks on schools current programme page

app/services/induction/transfer_and_continue_existing_fip.rb
Fixes: https://sentry.io/organizations/dfe-teacher-services/issues/3348612691/?environment=production&project=5748989&query=is%3Aunresolved
=> Fix raise with ArgumentError syntax

app/controllers/schools/add_participants_controller.rb, app/lib/multistep/controller.rb, app/views/schools/add_participants/name.html.erb, app/views/schools/add_participants/what_we_need.html.erb, app/views/schools/add_participants/who.html.erb, app/views/schools/transferring_participants/what_we_need.html.erb, config/routes.rb, spec/features/schools/participants/add_participants/unhappy_path_already_on_ecf_training_spec.rb, spec/features/schools/participants/add_participants/unhappy_path_cannot_validate_spec.rb, spec/features/schools/participants/add_participants/unhappy_path_email_taken_spec.rb, spec/features/schools/participants/add_participants/unhappy_path_sit_error_entering_validation_info_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/requests/schools/add_participants_spec.rb, spec/support/features/pages/schools/school_add_participant_wizard.rb
- Ticket: CST-785
- The step "What we need" has been added to the add/transfer participant form.
- The GDPR info have been added for FIP and CIP
=> GDPR message for add/transfer participants

app/controllers/finance/ecf/participant_declarations/voided_controller.rb, app/views/finance/ecf/statements/show.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1055
- Fix voids not showing up as incorrect statement is found
- Fix statement output payments table to only show applicable bands according to the contract on the statement
- none
=> [CPDLP-1055] New statement fixes

app/components/finance/npq/payment_overviews/course.html.erb, app/models/declaration_state.rb, app/services/finance/npq/course_statement_calculator.rb, app/services/finance/npq/statement_calculator.rb, app/views/finance/npq/statements/show.html.erb, spec/services/finance/npq/course_statement_calculator_spec.rb, spec/services/finance/npq/statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1055
- NPQ statements handle clawbacks
- Should probably review/merge/ship https://github.com/DFE-Digital/early-careers-framework/pull/2209 first
=> [CPDLP-1055] NPQ Statements handle clawbacks

spec/services/finance/ecf/output_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1465
- Add a failing test case is marked as pending
- This test case shows we a have bug in our system which needs to be fixed
- none
=> [CPDLP-1465] add pending test case for bug in ECF statements

app/serializers/api/v1/participant_declaration_serializer.rb, docs/Gemfile.lock, docs/source/release-notes.html.erb, spec/serializers/api/v1/participant_declaration_serializer_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1463
- Update docs with new clawback states
- Ensure values are hyphenate to keep inline with other API values
- See new states at https://ecf-review-pr-2277.london.cloudapps.digital/api-reference/reference-v1.html#schema-participantdeclarationattributes
=> [CPDLP-1463] update docs with clawback states on declaration

app/models/induction_programme.rb, app/models/induction_record.rb, app/models/participant_identity.rb, spec/models/induction_programme_spec.rb, spec/models/induction_record_spec.rb, spec/models/participant_identity_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CPDLP-1429)
Track changes to induction records, induction programmes and participant identities.
See also #2287
=> [CPDLP-1429] Track changes using touch and updated_at

.rubocop.yml, app/services/finance/extract_report.rb, spec/services/finance/extract_report_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1491
- There is a block of SQL that gets passed around to run "extracts"
- Make a home for this SQL but sticking it in a class for future reference and use
- none
=> [CPDLP-1491] Add class to encapsulate declaration extracts

app/controllers/delivery_partners/participants_controller.rb, app/serializers/delivery_partners/participants_serializer.rb, app/views/delivery_partners/participants/index.html.erb, spec/features/delivery_partners/participants_spec.rb, spec/serializers/delivery_partners/participants_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1452
* Added new CSV export link to DP participants page
* Login as "delivery-partner@example.com" user, go to participants page, click "Download (csv)"
=> [CPDLP-1452] DP extract download

spec/docs/v2/npq_participants_spec.rb, spec/requests/api/v2/ecf_participants_spec.rb, spec/requests/api/v2/npq_participants_spec.rb, spec/support/shared_examples/participant_actions_defer_support.rb
- Ticket: n/a
- Fixes tests around NPQ and withdrawal
- This is due to a started declaration must exist now in order to withdraw
- none
=> Fix tests around NPQ and withdrawal

app/services/finance/ecf/statement_calculator2.rb, spec/services/finance/ecf/statement_calculator2_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1469
- In my haste I forgot to wire up the test output calculator
- Wire up test output calculator
- This is throwaway code to test and will be integrated once everything works as expected
- none
=> [CPDLP-1469] Wire up test output calculator

app/controllers/concerns/appropriate_body_selection/controller.rb, app/controllers/schools/choose_programme_controller.rb, app/views/schools/choose_programme/success.html.erb, config/routes.rb, spec/cypress/integration/schools/ChooseProgramme.feature, spec/cypress/integration/schools/ChooseProgrammeCIPOnly.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/features/schools/choose_programme/new_schools_spec.rb, spec/features/schools/choose_programme/new_schools_steps.rb, spec/features/schools/training_dashboard/manage_cip_training_spec.rb, spec/features/schools/training_dashboard/manage_design_our_own_training_spec.rb, spec/features/schools/training_dashboard/manage_fip_training_spec.rb, spec/features/schools/training_dashboard/manage_no_ect_training_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/requests/schools/choose_programme_spec.rb, spec/support/features/pages/schools/school_report_programme_wizard.rb
- Ticket: CST-798
The appropriate body selection has been added to the new school cohort setup journey.
=> CST-798 - Choose AB for new schools

docs/source/release-notes.html.erb
- Ticket: n/a
- Tweak a release note for additional clarity of the change
- none
=> Tweak release note

documentation/debugging_in_govpaas.md
Ticket: N/A
This is a documentation update.
=> Include information on how to change space in GovPaaS docs

app/serializers/api/v1/npq_application_csv_serializer.rb, app/serializers/api/v1/npq_application_serializer.rb, app/serializers/api/v2/npq_application_serializer.rb, docs/source/release-notes.html.erb, spec/factories/npq_application.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/serializers/api/v1/npq_application_csv_serializer_spec.rb, spec/serializers/api/v1/npq_application_serializer_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQApplicationAttributes.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1326
* Updated v1/v2 `NPQParticipantSerializer` to include `targeted_delivery_funding_eligibility`
* Updated docs
=> [CPDLP-1326] API: surface targeted_delivery_funding_eligibility

config/locales/en.yml, spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb, spec/forms/participants/participant_validation_form_spec.rb, spec/forms/schools/transferring_participant_form_spec.rb
Content tweaks to TRN validation error messages.
=> Content updates for TRN error messages 

app/views/accessibility_statements/show.html.erb
Some minor text changes on the back of the recent accessibility test.
=> Update accessibility statement after August's test

app/controllers/finance/change_lead_provider_approval_statuses_controller.rb, app/views/finance/change_lead_provider_approval_statuses/new.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1656
* Fixed back link to use correct user id
=> [CPDLP-1656] Switch an NPQ application from rejected to pending fix

app/controllers/api/v1/participant_declarations_controller.rb, app/services/void_participant_declaration.rb, docs/source/release-notes.html.erb, spec/requests/api/v1/participant_declarations_spec.rb, spec/services/record_declarations/base_spec.rb, spec/services/void_participant_declaration_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1534
* Added extension to `Finance::ClawbackDeclaration` to make clawback when the declaration is paid.
=> [CPDLP-1534] Providers can trigger a clawback via the API

app/jobs/analytics/upsert_ecf_appropriate_body_job.rb, app/jobs/analytics/upsert_ecf_induction_job.rb, app/models/analytics/ecf_appropriate_body.rb, app/models/analytics/ecf_induction.rb, app/models/appropriate_body.rb, app/models/induction_record.rb, app/services/analytics/ecf_appropriate_body_service.rb, app/services/analytics/ecf_induction_service.rb, app/services/analytics/ecf_school_cohort_service.rb, db/analytics_migrate/20220808093344_create_ecf_inductions.rb, db/analytics_migrate/20220819095953_create_ecf_appropriate_bodies.rb, db/analytics_migrate/20220819102312_add_appropriate_bodies_to_ecf_school_cohorts.rb, db/analytics_schema.rb, spec/models/appropriate_body_spec.rb, spec/models/induction_record_spec.rb, spec/services/analytics/ecf_appropriate_body_service_spec.rb, spec/services/analytics/ecf_induction_service_spec.rb, spec/services/analytics/ecf_school_cohort_service_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-937)
Add induction records to analytics DB
New `ecf_inductions` table for analytics db
New `ecf_appropriate_bodies` table for analytics db
Additional appropriate body fields added to `ecf_school_cohorts` analytics table
Add models/service/job to support pushing data to analytics
=> [CST-937] add induction to analytics

app/services/record_declaration.rb, db/seeds.rb, db/seeds/appropriate_bodies.rb, db/seeds/dummy_structures.rb, db/seeds/schedules.rb, db/seeds/test_data.rb, spec/services/record_declaration_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CPDLP-1768):
=> [CPDLP-1768] - Fix NPQ retain declaration no needing to validate evidence held 

docs/source/release-notes.html.erb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1541
Add release note for course identifier error change
=> Add API release note for 14th September

docs/source/release-notes.html.erb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1541
Amend release note to have enough space between paragraphs to match other notes
=> Add breaks to paragraphs in release note

app/forms/schools/add_participant_form.rb, app/services/induction/amend_participant_cohort.rb, app/services/induction/amend_participants_cohort.rb, app/services/induction/change_cohort_induction_programme.rb, spec/forms/schools/add_participant_form_spec.rb, spec/services/induction/amend_participant_cohort_spec.rb, spec/smoke_tests/participant_declarations_spec.rb
Fix bug when changing a participant's AB
- Ticket:  [1029](https://dfedigital.atlassian.net/browse/CST-1029)
Remove security check before saving new participant form after making TRN mandatory
=> CST-1029: fix bug when assigning AB to a participant

db/seeds/npq_applications.rb, spec/db/seeds/npq_applications_spec.rb
- Ticket: n/a
- NPQ Applications now require a cohort
- Update seeding mechanism to attach next cohort to new NPQ applications
- none
=> NPQ application seeder attaches a cohort

app/views/schools/participants/_ects.html.erb, app/views/schools/participants/_mentors.html.erb, app/views/schools/participants/index.html.erb, config/locales/en.yml, config/locales/schools/participants.yml, spec/features/schools/training_dashboard/manage_training_steps.rb
- Ticket: CST-1054
Copy changes as per Jira ticket
=> copy change for eligibility checking page

app/services/induction/amend_participant_cohort.rb
Induction::AmendParticipantCohort: ignore voided participant declarations.
- Ticket:
=> little refactor to Induction::AmendParticipantCohort

app/controllers/admin/participants/change_cohort_controller.rb, app/views/admin/participants/_cohorts.html.erb, app/views/admin/participants/_details.html.erb, app/views/admin/participants/change_cohort/edit.html.erb, app/views/admin/participants/show.html.erb, config/routes.rb, spec/requests/admin/participants/change_cohort_spec.rb
- Ticket:
- Add admin screen for changing participant's cohort
- Add some specs covering cohort changing screen
=> Add an admin page for editing a participant's cohort

lib/tasks/one_offs.rake, spec/jobs/admin/npq_applications/export_job_spec.rb
This will allow to backfill correctly the record with a teacher_catchment_country for NPQApplication within a UK catchment area
=> [CPDLP-1539] - fix rake task to populate teacher catchemnt country

app/controllers/admin/participants_controller.rb, app/models/induction_record.rb, app/views/admin/participants/_declarations_history.erb, app/views/admin/participants/_induction_records.html.erb, app/views/admin/participants/show.html.erb
- Ticket: [1062](https://dfedigital.atlassian.net/browse/CST-1062)
=> CST-1062: add tab to display participant declarations to admins

db/seeds/npq_contracts/fake-2022.csv
- Ticket: n/a
- Add fake NIoT contracts for seeding purposes
- none
=> add fake niot seed contracts

spec/features/scenarios/changes_of_circumstance_scenario.rb
- Ticket: n/a
This is a temp fix to unblock develop, working on a permanent fix here: https://github.com/DFE-Digital/early-careers-framework/pull/2554
Hopefully after the perm fix is in we won't have to worry about this again
=> Change the hardcoded statement name to latest 2023 Feb

app/controllers/finance/npq/statements_controller.rb, spec/features/finance/npq/course_payment_breakdown_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1831
* Quick fix, filter `NPQContract` for statement by `statement.cohort`
=> [CPDLP-1831] Duplicate tables in NPQ statement

app/mailers/appropriate_body_profile_mailer.rb, app/models/appropriate_body_profile.rb, app/models/delivery_partner_profile.rb, app/views/start/appropriate_bodies.html.erb, config/routes.rb, spec/mailers/appropriate_body_profile_spec.rb, spec/models/appropriate_body_profile_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1807
* Added new mailer with Notifier template
* New start page: `/appropriate-bodies/start`
=> [CPDLP-1807] Start screen and email for Appropriate bodies

app/controllers/admin/appropriate_bodies/users_controller.rb, app/controllers/admin/delivery_partners/users_controller.rb, app/forms/appropriate_bodies/create_user_form.rb, app/forms/appropriate_bodies/update_user_form.rb, app/models/appropriate_body.rb, app/policies/appropriate_body_profile_policy.rb, app/services/feature_flag.rb, app/views/admin/appropriate_bodies/_heading.html.erb, app/views/admin/appropriate_bodies/users/delete.html.erb, app/views/admin/appropriate_bodies/users/edit.html.erb, app/views/admin/appropriate_bodies/users/index.html.erb, app/views/admin/appropriate_bodies/users/new.html.erb, app/views/layouts/admin.html.erb, config/locales/en.yml, config/routes.rb, spec/features/admin/appropriate_bodies/users_spec.rb, spec/features/admin/delivery_partners/users_spec.rb, spec/forms/appropriate_bodies/create_user_form_spec.rb, spec/forms/appropriate_bodies/update_user_form_spec.rb, spec/policies/appropriate_body_profile_policy_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1723
* New admin section "Appropriate bodies" to manage AB users
* Login with "admin@example.com"
* AB admin console hidden behind feature flag `appropriate_bodies`
=> [CPDLP-1723] Enable admin users to manage AB users on the service

.github/workflows/destroy.yml
- Ticket: n/a
Remove extra "("
Job is failing https://github.com/DFE-Digital/early-careers-framework/actions/runs/3299412351
=> Remove extra bracket on destroy job

db/migrate/20221027113219_update_ecf_duplicates_to_version_4.rb, db/schema.rb, db/views/ecf_duplicates_v03.sql, db/views/ecf_duplicates_v04.sql
=> Cpdlp 1728 2 delete duplicate profiles add validation preferably a database unique index to prevent multiple ecf profile being created

app/presenters/eligibility_presenter.rb, spec/presenters/eligibility_presenter_spec.rb
- Ticket: [JIRA](https://dfedigital.atlassian.net/browse/CST-1084)
Admins had noticed that often the "Exempt from induction" flag was showing "Yes", this was a logic/cut-n-paste error.
Fix logic in presenter and add specs for the presenter methods.
=> [CST-1084] Fix validation data presenter and add specs

app/views/finance/landing_page/show.html.erb
- [Ticket](https://dfedigital.atlassian.net/browse/CPDLP-1482): 
Since this fix won't have any visual impact until another link is added, please refer to the screenshot for _visual_ clues
=> [CPDLP-1482] - Fix finance landing page layout

app/serializers/finance/npq/assurance_report/csv_serializer.rb, app/services/finance/npq/assurance_report/query.rb, spec/requests/finance/npq/assurance_reports_spec.rb
We are adding targeted delivery funding to our NPQ statement, we need to update the query when downloading CSV to include the relevant fields.
- Ticket: [CPDLP-1893](https://dfedigital.atlassian.net/browse/CPDLP-1893)
Add a new column (Targeted Delivery Funding) to NPQ statements CSV report.
=> [CPDLP-1893] Add a new column to NPQ statements CSV report

app/services/analytics/ecf_induction_service.rb, db/analytics_migrate/20221115103803_add_user_id_and_participant_type_to_analytics_ecf_induction.rb, db/analytics_schema.rb
The new columns are:
* `user_id`
* `participant_type`
These columns will make the lives of the analysts easier as they'll need to do less manipulation of the data once extracted.
=> Add extra columns to analytics induction table

lib/tasks/compare/ecf_users_and_induction_records.rake
Generate useful reports for analysis due to 10K records getting new external IDs and so comparison has been made difficult. need to be able to examine the records to work out how they can be eliminated as not requiring approval.
- Ticket: https://dfedigital.atlassian.net/browse/CST-616
write records that are not present in both service responses or have differences so we can analyse them.
=> Pull out the differences in endpoint service responses for analysis

config/database.yml
Our queries are performing really badly, while we improve performance bump timeout as it's already too low.
- Ticket: n/a
Double timeout to 20s
We'll monitor once deployed to see what impact this has on the DB and frequency of timeouts.
=> Double DB statement timeout

app/controllers/schools/dashboard_controller.rb, app/controllers/schools/partnerships_controller.rb, app/mailers/school_mailer.rb, app/services/invite_schools.rb, app/views/schools/dashboard/_school_cohort_details.html.erb, spec/services/invite_schools_spec.rb
Some legacy code still displays dates in the wrong format. 
Change these dates to agreed govuk format
- Ticket: [Iterate challenging partnership copy](https://dfedigital.atlassian.net/browse/CST-882)
=> CST-882: display some dates in govuk format

app/components/finance/npq/payment_overviews/course.html.erb, app/models/finance/statement/npq.rb, app/services/finance/npq/course_statement_calculator.rb, app/services/finance/npq/statement_calculator.rb, app/views/finance/npq/statements/show.html.erb, config/locales/en.yml, db/migrate/20221117145209_add_targeted_delivery_funding_per_participant_to_npq_contracts.rb, db/schema.rb, spec/factories/npq_contracts.rb, spec/factories/services/npq/npq_application.rb, spec/features/finance/npq/course_payment_breakdown_spec.rb, spec/models/finance/statement/npq_spec.rb, spec/requests/finance/npq/assurance_reports_spec.rb, spec/services/finance/npq/course_statement_calculator_spec.rb, spec/services/finance/npq/statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1592
* Updated NPQ financial statement
* Added targeted delivery funding total
* Added targeted delivery funding" line item to course
* Login as financial admin user
* Go to NPQ financial statement.
=> [CPDLP-1592] Implementation of (positive) npq uplifts

app/components/finance/npq/payment_overviews/course.html.erb, app/services/finance/npq/course_statement_calculator.rb, app/services/finance/npq/statement_calculator.rb, spec/services/finance/npq/course_statement_calculator_spec.rb, spec/services/finance/npq/statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1598
* Updated NPQ financial statement
* Added clawbacks for targeted delivery funding for each course
* Total clawbacks include targeted delivery funding clawbacks.
* Login as financial admin user
* Go to NPQ financial statement.
=> [CPDLP-1598] Implementation of (clawback) npq uplifts

app/components/finance/npq/payment_overviews/contract_info.html.erb, app/components/finance/npq/payment_overviews/course.html.erb, app/views/finance/ecf/statements/show.html.erb, app/views/layouts/_application.html.erb, app/webpacker/styles/application.scss, app/webpacker/styles/components/statement_selector.scss, app/webpacker/styles/lead_providers/statements.scss
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1912
* Updated overall finance layout for mobile, added correct margin
* Updated ECF/NPQ statements page table layout
* Fixed filter selector width for mobile
* Login as finance user and visit finance sections
=> [CPDLP-1912] Financial statements UI updates - CSS and HTML tweaks for ECF and NPQ

lib/tasks/compare/critical_data_changed_checker.rake
Adds 
- mentor change analysis into output
- records start date
- last updated date
- assumed registration cohort
- monthly change analysis files
- fixes report window input variables
=> monthly analysis files within a period with additional info

public/.well-known/security.txt
> Assuming the contact details are still relevant, we should be able to bump this forward by one year.
Replacing @tvararu's [PR](#2808) so it'll build properly.
Fixes #2808
=> Bump the expires in security.txt

.github/workflows/lint.yml, Dockerfile.dev, README.md
Sorry @cwrw I set automerge on the previous PR 🤦🏽 
Here's the commit I meant to add.
> The mail log is instantiated with `Logger.new("log/mail.log", ...)` so will automatically create the file should it be missing, providing the log directory is present.
=> Remove references to touch `log/mail.log`

app/services/npq/application/accept.rb, spec/services/npq/application/accept_spec.rb
Following the investigation done on [CPDLP-1877](https://dfedigital.atlassian.net/browse/CPDLP-1877) .. where a participant had at one point two accepted applications for the same course.. it was detected that there’s a validation to prevent that scenario from happening, however the validation relies on both applications being linked to the same user. In this case we had two users, which means the validation did not pick up that those were both accepted, and then accepted the second application. However as part of acceptance we then dedup by trn, which then linked up the applications together. This is a bug in the accept application endpoint.
- Ticket: [CPDLP-1910](https://dfedigital.atlassian.net/browse/CPDLP-1910)
We’ll change the way the lookup happens on …
=> [CPDLP-1910] Validate other accepted applications for the same course by users with the same teacher profile TRN when accepting a npq application

docs/source/_ecf_usage_participant_actions.html.erb, docs/source/_npq_usage_participant_actions.html.erb, docs/source/_usage_participant_declarations.html.erb, docs/source/npq-usage.html.erb, docs/source/release-notes.html.erb, spec/requests/api/v3/participant_outcome_spec.rb, spec/requests/api/v3/provider_outcomes_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQOutcome.yml, swagger/v1/component_schemas/NPQOutcomeAttributesRequest.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/NPQOutcomeAttributesRequest.yml, swagger/v3/api_spec.json, swagger/v3/component_schemas/NPQOutcomeAttributesRequest.yml
We'll be adding new endpoints for NPQ outcomes into the API.. so we need to update the API guidance and release notes as well.
- Ticket: [CPDLP-1945](https://dfedigital.atlassian.net/browse/CPDLP-1945)
Update NPQ guidance for outcomes and add a release note to the API docs according to the drafted material below:
[https://docs.google.com/document/d/1E-0sArwlJ64ZACwuLKI8M3dNdNru6uaMIZuK6cEW_EE/edit](https://docs.google.com/document/d/1E-0sArwlJ64ZACwuLKI8M3dNdNru6uaMIZuK6cEW_EE/edit)
[CPDLP-1910]: https://dfedigital.atlassian.net/browse/CPDLP-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CPDLP-1945]: https://dfedigital.atlassian.net/browse/CPDLP-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> [CPDLP-1945] Update NPQ guidance for outcomes and add a release note to API docs

app/validators/future_date_validator.rb, config/locales/en.yml, spec/models/participant_outcome/npq_spec.rb, spec/requests/api/v1/participant_declarations_spec.rb, spec/requests/api/v2/participant_declarations_spec.rb, spec/services/npq/create_participant_outcome_spec.rb, spec/services/record_declaration_spec.rb
Updates to error messages for NPQ
- Ticket: [CPDLP-1952](https://dfedigital.atlassian.net/browse/CPDLP-1952)
It’s done when:
error messages shown for various scenarios match those on the google doc in the comments below.
https://docs.google.com/document/d/1MT4ZKIBYg9covad2ITA_f_u4ypLVWZtu0kE881Tt34k/edit#heading=h.6jsnsb4e9e
[CPDLP-1952]: https://dfedigital.atlassian.net/browse/CPDLP-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-1952] Improve error messages for NPQ outcomes

docs/source/release-notes.html.erb
Outcomes is alive!
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1992
Update release note 26/1/2023
=> Update API release note for NPQ outcomes 26/1/2023

app/models/finance/schedule/npq_leadership.rb, app/models/finance/schedule/npq_specialist.rb, app/models/npq_course.rb, app/services/importers/npq_contracts.rb, spec/cypress/app_commands/scenarios/admin/school_participants.rb, spec/models/finance/schedule/npq_leadership_spec.rb, spec/models/finance/schedule/npq_specialist_spec.rb, spec/models/npq_course_spec.rb, spec/services/importers/npq_contracts_spec.rb, spec/services/npq/application/accept_spec.rb, spec/services/record_declaration_spec.rb, spec/services/record_declarations/actions/make_declarations_payable_spec.rb, spec/support/with_default_schedules.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1968
* Updated NPQ specialist and leadership schedules to be dynamic
=> [CPDLP-1968] Update defaults schedules for NPQ specialist and leadership courses on acceptance

app/controllers/api/v1/npq_profiles_controller.rb, app/services/admin/npq_applications/csv_generator.rb, db/migrate/20230125182955_add_lead_mentor_and_itt_provider_to_npq_applications.rb, db/schema.rb, spec/jobs/admin/application_export_job_spec.rb, spec/jobs/admin/npq_applications/export_job_spec.rb, spec/requests/api/v1/npq_profiles_spec.rb
We now have two new fields in the NPQ reg, these need to be stored for the lead providers
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-834
=> Add lead_mentor and itt_provider to api and app table

app/services/data_stage/process_school_changes.rb, spec/services/data_stage/process_school_changes_spec.rb
- In our GIAS import processing, we don't auto handle closures when there isn't a "Successor" school link to avoid trying to handle complex changes that need eyes. However there is another case when a school doesn't have any school links where we could auto close the school if there are no induction tutors or school cohorts set up.
Enable closing schools without school links, school cohort and induction tutors when processing a closed status change from GIAS.
=> Process simple closure cases for schools without cohorts or successors

Gemfile, Gemfile.lock, package.json, yarn.lock
- Upgrade Shakapacker gem to 6.5.6
- Upgrade shakapacker npm package to 6.5.6
Fixes #2985
=> Upgrade to shakapacker 6.5.6

app/serializers/api/v1/participant_declaration_serializer.rb, app/serializers/api/v2/participant_declaration_serializer.rb, app/services/feature_flag.rb, app/services/npq/void_participant_outcome.rb, app/services/record_declaration.rb, spec/requests/api/v1/participant_declarations_spec.rb, spec/requests/api/v2/participant_declarations_spec.rb, spec/serializers/api/v1/participant_declaration_serializer_spec.rb, spec/serializers/api/v2/participant_declaration_serializer_spec.rb, spec/services/npq/void_participant_outcome_spec.rb, spec/services/record_declaration_spec.rb, spec/services/void_participant_declaration_spec.rb
This feature is now in production and can be safely removed
- Ticket: n/a
Remove feature flag implementation as well as test setup
Did I miss anything? (I'll double check with Tom as well)
=> Remove `participant_outcomes_feature` feature flag

docs/Gemfile.lock
This is preventing api docs from loading correctly
- Ticket: n/a
Update Gemfile ruby version in docs/
=> Update Gemfile with new Ruby Version in docs

.github/workflows/deploy_to_staging.yml
Actions have been updated but spotted this while deploying
- Ticket: n/a
Bump to v2 to avoid deprecation NodeJS warnings
=> Update workflow login due to deprecation warning for Node.js

.github/CODEOWNERS
This is just to double check we don't accidentally introduce unnecessary changes (probably) caused by a variety of versions of PostgreSQL in use.
=> Add some other devs to CODEOWNERS for schema.rb

app/views/start/index.html.erb
Spotted in dev https://ecf-dev.london.cloudapps.digital/
- Ticket: n/a
- Wrap links in GOV UK stylining
- Add  noreferre/noopener on outside links
=> Wrap links in Gov UK styling in landing page

app/models/cohort.rb, app/models/school_cohort.rb, spec/models/cohort_spec.rb
Minor change to remove some hardcoded SQL.
- Add between years scope for cohorts
- Replace SQL scope with active record conditions
=> Replace SQL scope with ActiveRecord one

app/controllers/api/notify_callbacks_controller.rb, app/jobs/handle_notify_callback_job.rb, spec/jobs/handle_notify_callback_job_spec.rb, spec/requests/api/notify_callback_spec.rb
Jobs are failing due to emails missing. We'd like more information on which templates are failing, log this as a warning to allow us to investigate further, and avoid the jobs failing and retrying
- Ticket: n/a
If email doesn't exist log it as a warning with the template
=> Update Handle notify callback job to log missing emails.

db/schema.rb
This is the version that matches production, it's occasionally
overwritten by a 'equal but not exact' version that must be set by a
slightly different PostgreSQL config
- Ticket:
=> Reset the db:schema again

app/serializers/api/v1/npq_application_csv_serializer.rb, app/serializers/api/v2/npq_application_csv_serializer.rb, spec/serializers/api/v1/npq_application_csv_serializer_spec.rb, spec/serializers/api/v2/npq_application_csv_serializer_spec.rb, spec/serializers/api/v2/npq_application_serializer_spec.rb
This is a continuation of https://github.com/DFE-Digital/early-careers-framework/pull/3083 where a comment was missed (thanks @leandroalemao )
- Ticket: n/a
- Add tests for NPQ serialiser v2
- Add change to CSV serialisers v1 and v2
=> Update NPQ application Csv serialiser `updated_at` field

app/views/admin/npq/applications/_application_details.html.erb, app/views/admin/npq/applications/_employment_details.html.erb, app/views/admin/npq/applications/_funding_eligibility.html.erb, app/views/admin/npq/applications/show.html.erb, spec/features/schools/add_appropriate_body_spec.rb, spec/requests/admin/npq/applications_controller_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-574
- Add more fields to the applications table for each user.
- Improve the testing for the pagination on the index page
Review app:
=> [CPDNPQ-574] Improve the application page and data available

db/new_seeds/base/add_npq_registrations.rb
- Ticket: 
Add more seeded data because previously we only had 20 users and doesnt show up issues with pagination. This change would allow that to be seen more easily and provide better feedback when testing.
=> Add more seeded data for better feedback when testing

app/components/finance/npq/participant_outcomes/table.html.erb, app/components/finance/npq/participant_outcomes/table.rb, spec/components/finance/npq/participant_outcomes/table_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2064
* Updated outcomes table on participants page
* Login as finance user and visit NPQ participant page
=> [CPDLP-2064] Outcome table update

app/controllers/finance/npq/change_lead_providers_controller.rb, app/forms/finance/npq/change_lead_provider_form.rb, app/models/npq_lead_provider.rb, app/views/finance/npq/change_lead_providers/confirm.html.erb, app/views/finance/npq/change_lead_providers/new.html.erb, app/views/finance/participants/_npq_profile.html.erb, config/locales/en.yml, config/routes.rb, spec/features/finance/change_lead_provider_spec.rb, spec/forms/finance/npq/change_lead_provider_form_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1796
* Added form to change lead provider
* Added link to NPQ participants page if declarations exist
* Login as a finance user
* Go to NPQ participant page which includes a declaration
=> [CPDLP-1796] NPQ Transfers Journey

app/services/importers/npq_contracts.rb, db/data/npq_contracts/fake-2021.csv, db/data/npq_contracts/fake-2022.csv, spec/services/importers/npq_contracts_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2072
* Updated seed script to use for production
* Change `course_name` to `course_identifier` in csv file.
* CSV columns:
* provider_name
* cohort_year
* course_identifier
* recruitment_target
* per_participant
* service_fee_installments
=> [CPDLP-2072] Add or amend scripts to develop NPQ Contract information for 2023 Cohort

spec/models/npq_application_spec.rb, spec/requests/admin/test_data_spec.rb
https://github.com/DFE-Digital/early-careers-framework/actions/runs/4492527810/jobs/7902536598
https://github.com/DFE-Digital/early-careers-framework/actions/runs/4482598839/jobs/7880839932
- Ticket: n/a
- `spec/requests/admin/test_data_spec.rb:55`: set explicit names to avoid names such as "O'Really" which are rendered with different characters on the page and will fail when attempting to match in the spec
- `spec/models/npq_application_spec.rb:39`: set explicit year on cohort which won't happen to match the current year to avoid unique index failures
=> NPQ Application and Test data flakey test fixes

docs/source/help.html.md
=> Fixed typo

app/views/admin/npq/applications/index.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-993
=> Add search text for search box and fix alignment

app/views/admin/npq/applications/_teacher_profile_details.html.erb, app/views/admin/npq/applications/show.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1001
To enable checking the teacher identity profile easier the trn field has been added to the npq application tab
=> Display teacher profile TRN in admin panel

app/controllers/admin/impersonates_controller.rb, spec/cypress/integration/admin/SchoolManagment.feature, spec/requests/admin/impersonates_spec.rb
Reverts DFE-Digital/early-careers-framework#3192
=> Revert "Send impersonator back to starting point when done impersonating"

app/controllers/api/api_controller.rb, app/controllers/api/errors/invalid_datetime_error.rb, app/controllers/concerns/api_filter.rb, app/services/api/v1/ecf/participants_query.rb, app/services/api/v3/ecf/partnerships_query.rb, config/locales/en.yml, spec/controllers/concerns/api_filter_spec.rb, spec/requests/api/v1/ecf_participants_spec.rb, spec/requests/api/v1/npq_applications_spec.rb, spec/requests/api/v1/participants_spec.rb, spec/requests/api/v2/ecf_participants_spec.rb, spec/requests/api/v2/npq_applications_spec.rb, spec/services/api/v1/users_query_spec.rb, spec/services/participants/history_builder_spec.rb
- Ticket: N/A
Surface a meaningful error message when filter[:updated_since] has a unexpected format.
=> Add a meaningful api updated_since filter parsing error message

app/components/admin/schools/cohorts/other_info.html.erb
This is a total hack, the proper solution will follow!
=> Quickly prevent 2023 cohort from being chosen

app/controllers/api/v3/ecf/schools_controller.rb, config/routes.rb, spec/docs/v3/ecf_schools_spec.rb, spec/requests/api/v3/ecf/schools_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2102
* Created new v3 endpoint for a single school.
=> [CPDLP-2102] Add  GET /api/v3/schools/ecf/:id endpoint

db/new_seeds/base/add_schools_and_local_authorities.rb, spec/factories/seeds/school_cohort_factory.rb, spec/factories/seeds/school_factory.rb, spec/factories/seeds/school_local_authority_factory.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2103
- Added some improvements to the school seeds; previously only full induction programme cohorts were created for 21/22. Now it will randomly assign all types of induction programme for all cohorts up to the current year.
=> [CPDLP-2103] Improve school, delivery partner and partnership seeds

app/presenters/dqt_record_presenter.rb, app/services/dqt_record_check.rb, spec/services/dqt_record_check_spec.rb
Add some specs covering the behaviour of `DqtRecordCheck`.
=> Add specs covering the DqtRecordCheck service

app/controllers/api/v3/ecf/partnerships_controller.rb, app/services/partnerships/create.rb, app/services/partnerships/update.rb, config/locales/en.yml, config/routes.rb, spec/docs/v3/ecf_partnerships_spec.rb, spec/requests/api/v3/ecf/partnerships_spec.rb, spec/services/partnerships/create_spec.rb, spec/services/partnerships/update_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2105
* New update partnership endpoint
* New service class `Partnerships::Update`
=> [CPDLP-2105] Add PUT /api/v3/partnerships/ecf/{partnership_id}

app/controllers/admin/participants/cohorts_controller.rb, app/controllers/admin/participants/declaration_history_controller.rb, app/controllers/admin/participants/details_controller.rb, app/controllers/admin/participants/history_controller.rb, app/controllers/admin/participants/identities_controller.rb, app/controllers/admin/participants/induction_records_controller.rb, app/controllers/admin/participants/school_controller.rb, app/controllers/admin/participants/validation_data_controller.rb, app/controllers/admin/participants_controller.rb, app/controllers/concerns/admin/participants/find_induction_records.rb, app/presenters/admin/participant_presenter.rb, app/views/admin/participants/cohorts/show.html.erb, app/views/admin/participants/declaration_history/show.html.erb, app/views/admin/participants/details/_show_ecf.html.erb, app/views/admin/participants/history/show.html.erb, app/views/admin/participants/identities/show.html.erb, app/views/admin/participants/induction_records/show.html.erb, app/views/admin/participants/school/show.html.erb, app/views/admin/participants/validation_data/show.html.erb, db/new_seeds/scenarios/participants/ects/ect.rb, spec/factories/seeds/induction_programme_factory.rb, spec/presenters/admin/participant_presenter_spec.rb, spec/rails_helper.rb, spec/services/induction/find_by_spec.rb
Create a single presenter to share presentation functionality across the admin participant pages
The one visual change is that [the appropriate body is shown for participants in the schools tab of the admin interface](https://github.com/DFE-Digital/early-careers-framework/pull/3207/commits/684519f35d5c7a8ec2f65359dd7160158199fa56).
=> Admin participant presenter

app/presenters/admin/participant_presenter.rb, app/views/admin/participants/school/show.html.erb, spec/presenters/admin/participant_presenter_spec.rb
This should be useful for everyone. Now it looks like this:
=> Show the appropriate body for school participants

.github/CODEOWNERS
=> Amend code owners as team has changed

app/services/importers/create_call_off_contract.rb, spec/services/importers/create_call_off_contract_spec.rb, spec/services/importers/create_new_ecf_cohort_spec.rb
This was accidentally missed on previous pr
- Ticket: n/a
Add monthly service fee to call off contracts
Im updating docs as well
=> Add monthly service fee to call off contracts script

app/mailers/school_mailer.rb
=> Remove the old 2020 add participant confirm email

app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: N/A
This is a small bug fix.
=> Fix the user id in the participant profile details

app/controllers/admin/impersonates_controller.rb
- Ticket: https://trello.com/c/r7QYqHjS/9-sit-impersonation
This PR adds simple Rails logging around saving impersonation start path to cookies, in order to debug SIT impersonation.
=> Add logging around saving impersonation start path to cookies

app/views/admin/npq/applications/edge_cases/show.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1016
Add email address to the NPQ edge case page
=> Add email field to the edge case npq page

data/appropriate_bodies.csv
- Ticket: CST-1419
The CSV data has been updated with the latest changes.
A script has been run in production with the updates.
=> [CST-1419] Update appropriate bodies names

app/controllers/api/v3/participant_declarations_controller.rb, app/models/participant_declaration.rb, app/models/participant_declaration/ecf.rb, app/models/participant_declaration/npq.rb, app/serializers/api/v3/participant_declaration_serializer.rb, app/services/api/v3/participant_declarations_query.rb, config/routes.rb, spec/docs/v3/participant_declarations_spec.rb, spec/factories/services/npq/npq_application.rb, spec/models/participant_declaration/ecf_spec.rb, spec/models/participant_declaration/npq_spec.rb, spec/requests/api/v3/participant_declarations_spec.rb, spec/serializers/api/v3/participant_declaration_serializer_spec.rb, spec/services/api/v3/participant_declarations_query_spec.rb, swagger/v3/api_spec.json, swagger/v3/component_schemas/ECFParticipantDeclarationAttributes.yml, swagger/v3/component_schemas/NPQParticipantCompletedDeclarationAttributes.yml, swagger/v3/component_schemas/NPQParticipantRetainedDeclarationAttributes.yml, swagger/v3/component_schemas/NPQParticipantStartedDeclarationAttributes.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2130
* GET `/api/v3/participant-declarations` endpoint added
=> [CPDLP-2130] Add GET /api/v3/participant-declarations

docs/source/ecf.html.md, docs/source/ecf/guidance.html.md, docs/source/ecf/schedules-and-milestone-dates.html.md, docs/source/npq.html.md, docs/source/npq/definitions-and-states.html.md, docs/source/npq/guidance.html.md
Corrected all broken links in API guidance
=> Api guidance link corrections

Makefile, global_config/development_aks.sh, terraform/aks/development_aks.tfvars.json, terraform/aks/development_ask.tfvars
This PR contains the first steps towards being able to deploy to AKS.
=> AKS - set up a keyvault and storage account

docs/source/get-started.html.md
Suggest copy for YAML spec and postman links
=> Suggested YAML copy

terraform/aks/development_ask.tfvars
These were pasted in and not switched in #3394 :(
=> Rename the resources from qfqts to cpdecf

config/environments/deployed_development.rb
Debug mode is logging too much in logir
- Ticket: n/a
Update log level to info as on other envs.
This is sending too many unnecessary logs in logit
=> Update log level to info on deployed dev

app/views/lead_providers/content/index.html.erb, app/views/lead_providers/content/partnership_guide.html.erb, app/views/sandbox/show.html.erb, docs/source/npq/schedules-and-milestone-dates.html.md, spec/cypress/integration/lead_providers/PartnershipGuidance.feature, spec/requests/lead_providers/landing_page_spec.rb, spec/requests/lead_providers/partnership_guide_spec.rb, spec/requests/sandbox_spec.rb, spec/support/features/pages/lead_provider/lead_provider_landing_page.rb, spec/support/features/pages/sandbox_landing_page.rb
Updated Sandbox landing page copy for improved usability.
=> Copy edits for the sandbox landing page

app/forms/schools/cohorts/setup_wizard/success.rb
=> Upgrade LP email enqueue to the new Rails way

app/models/training_record_state.rb, db/migrate/20230420082729_create_training_record_states.rb, db/migrate/20230517101855_add_indexes_to_training_record_states.rb, db/schema.rb, db/views/training_record_states_v01.sql, lib/tasks/refresh.rake
Training record state model and materialised view refresh task for performance testing
- Add Training Record State Model
- Add Materialised view and indexes
- Add refresh rake task
`bundle exec rake refresh:training_record_states`
=> Training record state performance testing

app/controllers/nominations/choose_how_to_continue_controller.rb, app/forms/nominate_how_to_continue_form.rb, app/views/nominations/choose_how_to_continue/new.html.erb, app/views/shared/choice_saved_no_early_career_teachers.html.erb, spec/features/nominations/choose_how_to_continue_spec.rb, spec/features/nominations/nominate_induction_tutor_steps.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1466)
Update the content and consider the pilot/non-pilot schools
Content changes to view and form
Additional specs
- Sign in as admin@example.com.
- Use the "Test data" link and navigate to the "Unclaimed schools" tab
- Generate a link for a school or use one that has already been generated to access the journey
=> [CST-1466] Update content for GIAS contact school setup journey

app/serializers/api/v3/participant_declaration_serializer.rb, app/services/api/v3/participant_declarations_query.rb, spec/serializers/api/v3/participant_declaration_serializer_spec.rb, spec/services/api/v3/participant_declarations_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2212
* `mentor_id` returned correct in a non-N+1 way
=> [CPDLP-2212] Improve performance on participant declarations in v3

docs/source/ecf/definitions-and-states.html.md, docs/source/ecf/guidance.html.md, docs/source/npq/guidance.html.md
Small content updates 
* corrected typos 
* added application id endpoint 
* updated application endpoint response bodies 
NB these updates had been in Brian's acccordion branch but pulling out here so as to release independently.
=> Small content amends in guidance

docs/source/release-notes.html.md
- Ticket: [CPDLP-2231](https://dfedigital.atlassian.net/browse/CPDLP-2231)
Add a release note available in sandbox and production on ECT-Mentor same school.
[CPDLP-2231]: https://dfedigital.atlassian.net/browse/CPDLP-2231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2231] Add ECT-Mentor same school release note

docs/source/ecf/guidance.html.md, docs/source/npq/guidance.html.md, docs/source/release-notes.html.md, swagger/v3/api_spec.json, swagger/v3/template.yml
- Ticket: [CPDLP-2215](https://dfedigital.atlassian.net/browse/CPDLP-2215)
Add release note and updated specs for prod api v3
Pls checkout the changes on the review app
[CPDLP-2215]: https://dfedigital.atlassian.net/browse/CPDLP-2215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2215] Add release note and updated specs for prod api v3

app/services/api/participant_declarations/index.rb, app/services/api/v3/participant_declarations_query.rb, db/views/training_record_states_v01.sql, db/views/training_record_states_v02.sql
Using OR is performing worse in prod database than a union, revert back to union
- Ticket: n/a
original pr: https://github.com/DFE-Digital/early-careers-framework/pull/3486/files
=> Keep union as it uses less cpu when in prod

app/controllers/schools/base_controller.rb
Amend cohort_id argument passed to cohort-setup redirection logic in schools base controller.
- Ticket:
=> fix bug on cohort setup redirection

app/components/search_box_with_date_range.html.erb, app/components/search_box_with_date_range.rb, app/controllers/admin/npq/applications/edge_cases_controller.rb, app/models/npq_application.rb, app/services/admin/npq_applications/edge_case_search.rb, app/views/admin/npq/applications/edge_cases/index.html.erb, db/legacy_seeds/npq_applications.rb, db/new_seeds/scenarios/npq.rb, spec/services/admin/npq_applications/edge_case_search_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1008
- added data filters for fundingEligibilityStatusCode
- added data filters for employmentType
- added specs for new data filters
=> [CPDNPQ 1008] Add data filters to edge case page

docs/source/ecf/definitions-and-states.html.md, docs/source/ecf/guidance.html.md, docs/source/get-started.html.md, docs/source/npq/guidance.html.md
Added line of content to NPQ API guidance around withdrawal `date`.
=> Amend to NPQ withdrawal guidance.

app/views/admin/npq/applications/_application_details.html.erb, app/views/admin/npq/applications/_funding_eligibility.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1160
Added following fields in NPQ and ECF admin consoles
- primary_establishment
- number_of_pupils
- targeted_support_funding_primary_plus_eligibility
=> Surface New Targeted Support Funding Columns in the NPQ Application Data

app/forms/admin/school_transfer_form.rb
This code was from an earlier fix and shouldn't have been included in the final PR.
Remove it.
=> Remove unused code

app/views/schools/transfer_out/check_transfer.html.erb, spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb, spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- Ticket: CST-1604
Update the transfer-out journey with new content
=> [CST-1604] Check transfer copy change

app/views/schools/transfer_out/check_transfer.html.erb, spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb, spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
Reverts DFE-Digital/early-careers-framework#3544
=> Revert "[CST-1604] Check transfer copy change"

app/jobs/participant_outcomes/stream_api_requests_to_big_query_job.rb, app/models/participant_outcome_api_request.rb, spec/factories/participant_outcome_api_request.rb, spec/jobs/participant_outcomes/stream_api_requests_to_big_query_job_spec.rb, spec/models/participant_outcome_api_request_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2261
* Created job `ParticipantOutcomes::StreamApiRequestsToBigQueryJob`
* Job scheduled on every change to `ParticipantOutcomeApiRequest`
=> [CPDLP-2261] Stream Outcome API responses to Big query

app/components/admin/participants/audit_trail_component.html.erb, app/components/admin/participants/audit_trail_component.rb, app/components/admin/participants/audit_trail_item_component.rb, app/services/participants/history_builder.rb, spec/components/admin/participants/audit_trail_component_spec.rb
- Ticket: https://dfe-teacher-services.sentry.io/issues/4245051022/?environment=production&project=5748989&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
- make sure we use the User object rather than the Audit object
- Add specs to test the components render the changes correctly
=> Handle user types without error in change log

app/views/schools/participants/reason_to_edit_name.html.erb
Quick fix to remove a spurious 's' from a view
=> [Bug-fix] Remove spurious letter from view

terraform/aks/cluster_data.tf, terraform/aks/databases.tf, terraform/aks/providers.tf, terraform/aks/variables.tf
Add Redis in the AKS infrastructure
=> Add Redis in AKS

terraform/aks/cluster_data.tf, terraform/aks/databases.tf, terraform/aks/providers.tf, terraform/aks/variables.tf
=> Add PostgreSQL in AKS

terraform/aks/providers.tf
=> Add Azure Resource Mananger to AKS Proiders

app/policies/appropriate_body_profile_policy.rb, app/services/feature_flag.rb, app/views/layouts/admin.html.erb, spec/features/admin/appropriate_bodies/users_spec.rb, spec/policies/appropriate_body_profile_policy_spec.rb
Remove feature flag as its been set to true in prod, a long time ago and caused confusion when not appearing in sandbox
- Ticket: n/a
Remove all feature flag checks from app and specs
=> Remove appropriate bodies feature flag

lib/tasks/comms.rake
- Ticket: N/A
This updates the pilot chaser task to add schools to the pilot if not already.
=> Add school to pilot when sending the chaser email

app/views/schools/transfer_out/check_transfer.html.erb, spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb, spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- Ticket: CST-1604
Update the transfer-out journey with new content
=> Cst 1604 update transfer out content 3

app/views/schools/add_participants/eligibility_confirmation/_no_qts_reason.html.erb
Found (by searching the code) the same typo on another page.
=> Same typo on another page

app/forms/schools/cohorts/setup_wizard/success.rb
=> Bug fix: rename Rails.logger.warning to Rails.logger.warn

app/models/participant_profile/npq.rb, docs/source/release-notes.html.md, spec/requests/api/v1/npq_participants_spec.rb, spec/requests/api/v2/npq_participants_spec.rb, spec/requests/api/v3/npq_participants_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/NPQParticipantWithdrawAttributes.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/NPQParticipantWithdrawAttributes.yml, swagger/v3/api_spec.json, swagger/v3/component_schemas/NPQParticipantWithdrawAttributes.yml, swagger/v3/component_schemas/NPQWithdrawal.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1788
* New withdrawal reason added for NPQ participant withdraw endpoint for v1, v2 and v3.
* Updated release notes.
=> 1788 add an extra withdrawal reason for npq participants

docs/source/ecf/guidance.html.md
- Ticket: 
Added text to clarify re-partnering info.
=> Re-partnering info update

app/controllers/admin/home_controller.rb
Updates the query used on the admin "Overview" page that displays the registration stats to only consider "active" records.
=> Update participant query

app/views/layouts/_width_container.html.erb, config/initializers/secure_headers.rb
Reverts DFE-Digital/early-careers-framework#3316
=> Revert "Revert "Add Zendesk help widget""

spec/models/user_spec.rb
Fix intermittent time comparison issue in spec
=> Fix intermittent issue in spec with time comparison

app/views/admin/npq/applications/_funding_eligibility.html.erb
It was displaying the created_at instead of updated_at 🤦
=> Fix updated_at timestamp for NPQ

app/assets/stylesheets/lead_providers/statements.scss, app/components/finance/additional_adjustments/table.html.erb, app/components/finance/additional_adjustments/table.rb, app/models/finance/adjustment.rb, app/models/finance/statement.rb, app/services/finance/ecf/statement_calculator.rb, app/views/finance/ecf/statements/show.html.erb, db/migrate/20230712152849_create_finance_adjustments.rb, db/schema.rb, spec/components/finance/additional_adjustments/table_spec.rb, spec/factories/finance/adjustments.rb, spec/features/finance/ecf/statement_spec.rb, spec/models/finance/adjustment_spec.rb, spec/services/finance/ecf/statement_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1921
* New model `Finance::Adjustment`
* New component `Finance::ECF::AdditionalAdjustments`
* Updated ECF statement page to include additional adjustments table.
* Login as finance role
* Go to ECF statements page.
=> [CPDLP-1921] Create tables in the statements and create an adjustment model

.github/workflows/review.yml
Just testing out the process of pushing to multiple Docker registries at once.
=> Try pushing to GitHub docker registry in parallel

app/views/schools/cohort_setup/appropriate_body_type.html.erb
See https://dfedigital.atlassian.net/browse/CST-1666?atlOrigin=eyJpIjoiYzBkMTk5ZDc4NjY0NDIxOGEzNTQ2MjlhNDY2YmEwMGUiLCJwIjoiaiJ9 for information.
=> Reword appropriate body type text in school cohort setup

Dockerfile, Dockerfile.dev
Trying to fix some problems with the build.
=> Upgrade from Alpine 3.17 to 3.18

app/views/schools/transfer_out/complete.html.erb
See https://dfedigital.atlassian.net/browse/CST-1739?atlOrigin=eyJpIjoiODJkNmVhMjk3MTU3NDUwYWI3NGNjMDc4ZDdkMWU2NjQiLCJwIjoiaiJ9 for context.
=> [CST-1739] Remove content that refers to the old dashboard design

.github/workflows/aks_deploy_review.yml
Add a sticky comment to PRs with a link to the AKS review app
=> Add comment to PR with link to review app

app/components/finance/additional_adjustments/table.html.erb, app/components/finance/additional_adjustments/table.rb, app/controllers/finance/adjustments_controller.rb, app/forms/finance/add_another_adjustment_form.rb, app/forms/finance/create_adjustment_form.rb, app/models/finance/adjustment.rb, app/models/finance/statement.rb, app/models/finance/statement/ecf.rb, app/models/finance/statement/npq.rb, app/views/finance/adjustments/index.html.erb, app/views/finance/adjustments/new.html.erb, app/views/layouts/_width_container_wide.html.erb, config/locales/en.yml, config/routes.rb, spec/components/finance/additional_adjustments/table_spec.rb, spec/features/finance/adjustments/create_adjustment_spec.rb, spec/forms/finance/add_another_adjustment_form_spec.rb, spec/forms/finance/create_adjustment_form_spec.rb, spec/models/finance/adjustment_spec.rb, spec/models/finance/statement_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1659
* ECF statement page add new additional adjustment flow
* Login as a finance user
* Go to ECF financial statement that is not payable or paid
* Scroll down to additional adjustments section
=> [CPDLP-1659] Add adjustment flow

app/components/finance/additional_adjustments/table.html.erb, app/controllers/finance/adjustments_controller.rb, app/forms/finance/update_adjustment_form.rb, app/models/finance/statement.rb, app/views/finance/adjustments/delete.html.erb, app/views/finance/adjustments/edit.html.erb, app/views/finance/adjustments/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/finance/adjustments/create_adjustment_spec.rb, spec/features/finance/adjustments/delete_adjustment_spec.rb, spec/features/finance/adjustments/update_adjustment_spec.rb, spec/forms/finance/update_adjustment_form_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-1805
- Depends on: https://github.com/DFE-Digital/early-careers-framework/pull/3715
* Added delete flow for adjustmemts
* Added edit flow for adjustmemts
* Login as finance user
* Go to ECF statement
=> [CPDLP-1805] change or remove adjustment flow

config/locales/admin/participants/change_relationship.yml
- Ticket: CST-1804
This PR updates the content in the admin change relationship page
=> [CST-1804] Update the content in the admin change relationship page

app/models/npq_application.rb, app/views/admin/npq/applications/eligible_for_funding/edit.html.erb, spec/models/npq_application_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1240
=> Display message to admins regarding voiding declarations

.github/workflows/aks_deploy.yml
Reverts DFE-Digital/early-careers-framework#3770
=> Revert "Remove continue-on-error from staging deploy step"

.github/workflows/aks_deploy.yml
Reverts DFE-Digital/early-careers-framework#3774
@RMcVelia has now added the credentials for staging so this step works.
=> Revert "Revert "Remove continue-on-error from staging deploy step""

app/mailers/school_mailer.rb, spec/mailers/school_mailer_spec.rb
- Ticket: CST-1811
SIT nomination mailer template changed
=> Update mailer template: SIT nomination notification

.github/workflows/aks_deploy.yml, .github/workflows/cypress.yml, .github/workflows/rspec.yml
- Improve the rspec workflow description
- Add Cypress workflow
- Integrate new Cypress workflow with deployment
=> Add Cypress to the review workflow

docs/source/release-notes.html.md
Fixing issues such as:
* date suffixes (nd, rd, th and st)
* use of bold text in bullets
- Ticket:
=> Govifying release notes

.github/workflows/aks_deploy.yml, .gitignore, Makefile, app/models/analytics/base_record.rb, config/database.yml, config/environments/production.rb, config/environments/sandbox.rb, global_config/production_aks.sh, global_config/sandbox_aks.sh, global_config/staging_aks.sh, terraform/aks/application.tf, terraform/aks/databases.tf, terraform/aks/workspace_variables/production_aks.tfvars.json, terraform/aks/workspace_variables/production_aks_backend.tfvars, terraform/aks/workspace_variables/sandbox_aks.tfvars.json, terraform/aks/workspace_variables/sandbox_aks_backend.tfvars
Follows #3781 which went weird due to having two review apps 🤷
The one area of doubt: we're adding `url: <%= ENV["ANALYTICS_DATABASE_URL"] %>` to the analytics database config for `staging`, `sandbox` and `production`. The `ANALYTICS_DATABASE_URL` variable will only be present on Azure so, we're assuming `url: nil` will be ignored.
We can test that by deploying manually and checking the Analytics database is connected:
=> Add sandbox and production envs

documentation/maintenance_mode.html.md
Move docs into documentation folder
=> Move maintenance mode docs

.github/workflows/aks_destroy_review.yml
I renamed `review_aks` to `review` a while ago but missed this one 🤦
=> Fix the terraform-destroy step

app/components/finance/banding_tracker/band_per_declaration_type_row.html.erb, app/components/finance/banding_tracker/band_per_declaration_type_row.rb, app/components/finance/banding_tracker/table.html.erb, app/models/participant_declaration.rb, app/services/finance/ecf/output_calculator.rb, app/services/finance/ecf/statement_calculator.rb, app/views/finance/ecf/statements/show.html.erb, config/locales/en.yml, lib/finance/banding_tracker/participant_per_declaration_type_per_band_aggregator.rb, lib/payment_calculator/ecf/output_payment_calculator.rb, spec/factories/finance/schedules.rb, spec/factories/participant_declaration.rb, spec/factories/services/early_career_teachers/create.rb, spec/factories/services/mentors/create.rb, spec/features/finance/payment_breakdown_spec.rb, spec/services/finance/ecf/output_calculator_spec.rb, spec/services/finance/ecf/statement_calculator_spec.rb
- Ticket: [CPDLP-2326](https://dfedigital.atlassian.net/browse/CPDLP-2326)
Add new extended declarations types to ECF statements
[CPDLP-2326]: https://dfedigital.atlassian.net/browse/CPDLP-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2326] Add extended declarations to ECF statements

docs/source/ecf/schedules-and-milestone-dates.html.md
Added info to explain how and when lead providers can make extended declarations.
- Ticket:
=> Update extended schedules guidance

.github/workflows/backup-paas-database.yml, .github/workflows/restore-backup-to-aks.yml
Backs up a PaaS database and uploads the backup as a GitHub artefact.
=> Add workflow to backup PaaS database

.github/workflows/aks_deploy.yml
failures.... FAILURES
- Ticket: n/a
Deploy to review only on pull requests and not on main
=> Only attempt review app deploy on pull requests

docs/source/release-notes.html.md
- Ticket: [CPDLP-2328](https://dfedigital.atlassian.net/browse/CPDLP-2328)
Add extended declarations release note for production release.
[CPDLP-2328]: https://dfedigital.atlassian.net/browse/CPDLP-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2328] Add extended declarations release note for production

config/routes.rb
We’re redesigned the feedback survey, and it's now on a new Microsoft Office url.
🗂️ [Jira ticket](https://dfedigital.atlassian.net/browse/CST-1733)
=> Update feedback survey URL

app/components/banners/maintenance_component.rb
set dates for maintenance banners on app
- Ticket: n/a
=> Set dates for banner for staging migration

app/mailers/school_mailer.rb
=> [CST-1890] Build auto mailers for end of Aug/start Sept

app/mailers/school_mailer.rb
=> Build auto mailers for end of Aug/start Sept

app/components/banners/maintenance_component.rb
We no longer need this banner for dev/staging. Reset times to hide banner
- Ticket: n/a
=> Reset banner maintenance times

app/services/store_participant_eligibility.rb, app/views/schools/add_participants/eligibility_confirmation/_previous_induction.html.erb, spec/services/store_participant_eligibility_spec.rb
- Ticket: [(Dev) Replace _previous_induction.html.erb screen with new completed induction version](https://dfedigital.atlassian.net/browse/CST-1910)
-  Replace the content displayed to SITs for participants who have completed their induction.
- Do not email the SIT when registering a participant that has completed induction
=> CST-1910: dev replace previous induction html erb screen with new completed induction version

app/mailers/participant_mailer.rb
- Ticket:  [Send comms to post-transitional ECTs who have just been registered](https://dfedigital.atlassian.net/browse/CST-1881)
=> CST-1881: send comm to post-transitional ECTs after registration

Makefile
To run the make maintenance command 
- Ticket: n/a
This is required for the maintenance command, to ensure it picks the right PaaS space
=> Update env setup to include paas space

README.md, docs/source/release-notes.html.md
- Ticket: n/a
Update new Azure URLs to point to external routes rather than internal
=> Update new AKS urls to point to external routes

terraform/aks/workspace_variables/production_aks.tfvars.json
Deployments are failing due to this value
- Ticket: n/a
Change capacity to 1 for successful Redis creation
=> Change queue capacity to 1 for prod Redis

app/jobs/finance/statements/mark_as_paid_job.rb, app/models/finance/statement.rb, app/models/finance/statement/ecf/payable.rb, app/models/finance/statement/npq/payable.rb, db/migrate/20230905155638_add_marked_as_paid_at_to_statements.rb, db/schema.rb, spec/factories/finance/statements.rb, spec/jobs/finance/statements/mark_as_paid_job_spec.rb, spec/models/finance/statement_spec.rb
- Ticket: [CPDLP-2415](https://dfedigital.atlassian.net/browse/CPDLP-2415)
We will be adding the ability to mark a statement as paid from the finance statement dashboards. 
Add a job for freezing statements.
[CPDLP-2415]: https://dfedigital.atlassian.net/browse/CPDLP-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2415] Add a job for freezing statements

.github/actions/backup-paas-database/action.yml
I accidentally deleted the bit that uploads the backup.
=> Reinstate the database backup upload

docs/source/release-notes.html.md
Formatting edit - added space between the first and second sentences.
=> Edit 13-september-release-note.html.md

app/views/admin/npq/applications/_application_details.html.erb
https://dfedigital.atlassian.net/browse/CPDNPQ-1289
Minor: fixes typo in Admin console (NPQ section)
Changes: `Proflie` into `Profile`
=> Fixes typo in Admin console for NPQ application

app/services/create_induction_tutor.rb, app/services/support/school_induction_tutors/replace.rb, app/services/support/school_induction_tutors/update.rb, lib/tasks/support/sit_update.rake
- Ticket: https://dfedigital.atlassian.net/browse/CST-1961
There's a blocker on the form that prevents users from being updated. This allows you to do that via a rake task
=> [CST-1961] Add rake tasks to easily update/create SITs for schools

app/mailers/school_mailer.rb, lib/tasks/finance_errors_emails.rake, spec/mailers/school_mailer_spec.rb
- Ticket: CST-1949
This PR adds four mails to inform Schools and Local Authorities of grant corrections.
We are going to send three emails to Schools and one to Local Authorities.
- Add the mailers
- Add rake tasks to trigger the emails
=> [CST-1949] Add mailers for the finance amendments

terraform/aks/application.tf, terraform/aks/variables.tf, terraform/aks/workspace_variables/production_aks.tfvars.json
Increase replicas in production
=> Increase the webapp/worker replicas in production

Makefile, terraform/aks/application.tf
I missed this first time as it's not clear whether `=-` is an operator or the `-` is part of the value being assigned.
=> Move suffix dash to environment assignment

Makefile, terraform/aks/application.tf
Reverts DFE-Digital/early-careers-framework#3992
=> Revert "Move suffix dash to environment assignment"

app/components/appropriate_bodies/participants/table_row.html.erb, app/components/appropriate_bodies/participants/table_row.rb, app/controllers/appropriate_bodies/participants_controller.rb, app/serializers/appropriate_bodies/induction_records_serializer.rb, app/services/appropriate_bodies/participants_filter.rb, app/views/appropriate_bodies/participants/index.html.erb, config/locales/status_tags/appropriate_body_participant_status.yml, spec/components/appropriate_bodies/participants/table_row_spec.rb, spec/features/appropriate_bodies/participants_spec.rb, spec/serializers/appropriate_bodies/induction_records_serializer_spec.rb, spec/services/appropriate_bodies/participants_filter_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2431
* Updated AB participants page to new table layout
* Updated CSV export to match new table
* Updated status name and description to excel matrix
=> [CPDLP-2431] Appropriate body dashboard view updates

app/forms/edit_induction_tutor_form.rb, app/services/support/school_induction_tutors/replace.rb, app/services/support/school_induction_tutors/update.rb
=> adjust Support job classes to call the new SIT services

config/initializers/rack_attack.rb, spec/requests/api/v3/rate_limiting_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2427
* API rate limiting now uses token instead of IP
* Added tests to make sure rate limiting is working
=> [CPDLP-2427] Implement token-based rate limiting

config/locales/status_tags/appropriate_body_participant_status.yml, spec/components/appropriate_bodies/participants/table_row_spec.rb, spec/features/appropriate_bodies/participants_spec.rb, spec/serializers/appropriate_bodies/induction_records_serializer_spec.rb
- Ticket: [CPDLP-2464](https://dfedigital.atlassian.net/browse/CPDLP-2464)
Update AB content for "No longer being trained".
[CPDLP-2464]: https://dfedigital.atlassian.net/browse/CPDLP-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2464] Update AB content for "No longer being trained"

app/views/schools/dashboard/_school_cohort_details.html.erb, spec/features/schools/choose_programme/choose_programme_steps.rb, spec/support/features/pages/schools/school_dashboard_page.rb
Following some support requests, I've made the guidance on how to challenge a partnership clearer.
See ticket for more information: https://dfedigital.atlassian.net/browse/CST-2011
=> Make the guidance on how to challenge a partnership clearer

docs/source/release-notes.html.md
Release note: new maths NPQ added to the production environment. 
I've also taken the opportunity to delete a 'rogue' date suffix: '10th August 2023' changed to '10 August 2023'
- Ticket:
=> 2 October release-notes.html.md

app/forms/schools/add_participants/transfer_wizard.rb
- Ticket: CST-1799
The logic branch has been changed to check whether the SIT is adding himself as mentor first.
=> [CST-1799] SITs becoming mentors (bugfix)

app/controllers/api/api_controller.rb, spec/requests/dfe_analytics_spec.rb
Reverts DFE-Digital/early-careers-framework#4080
=> Revert "Add DFE analytics to API controller"

Makefile
I had to download a specific file from AKS to my local folder.
Add make command for copying a file from AKS to local.
* couldn't make it work with `kubectl cp` or using `tar`.
=> Add make command for copying a file from AKS to local

app/views/admin/gias/home/index.html.erb, app/views/admin/gias/schools/show.html.erb, app/views/admin/npq/applications/eligibility_imports/show.html.erb, app/views/finance/banding_tracker/providers/show.html.erb, app/views/finance/ecf/statements/show.html.erb, app/views/finance/npq/statements/show.html.erb, app/views/lead_providers/content/index.html.erb, app/views/lead_providers/content/partnership_guide.html.erb, app/views/pages/_user_research_sign_up.html.erb, app/views/pages/core_materials_info.html.erb, app/views/sandbox/show.html.erb, app/views/schools/participants/show.html.erb
Opps, missed a few of these when dropping the h1 font size from XL to L. 🤦
=> Drop h2 heading size from L to M

app/controllers/schools/add_participants/add_controller.rb, app/controllers/schools/add_participants/transfer_controller.rb
=> [CST-1799] Logging improvements

app/forms/choose_role_form.rb, app/forms/supplier_user_form.rb, app/models/lead_provider_profile.rb, spec/forms/choose_role_form_spec.rb, spec/forms/supplier_user_form_spec.rb, spec/models/lead_provider_profile_spec.rb, spec/requests/admin/suppliers/supplier_users_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2445
* Updated lead provider user creation to allow existing users
* Updated choose role page to include lead provider
=> [CPDLP-2445] Fix bugs around DP/LP user access management

docs/source/release-notes.html.md
Small edits such as changing the use of 'the DfE' to the more friendly pronoun 'we'.
=> CPDLP-2484 release notes edits.html.md

docs/source/release-notes.html.md
Small edits such as changing the use of 'the DfE' to the more friendly pronoun 'we'.
=> CPDLP-2484 deduping release note edit.html.md

docs/source/ecf/schedules-and-milestone-dates.html.md
Reduced schedules section: replaced first par with new intro and 2 bullets.
=> 6 October 2023 update schedules-and-milestone-dates.html.md

docs/source/ecf/guidance.html.md
Dedupe functionality guidance update in the 'View a single participant's data' section.
=> Update guidance-view a single participant’s data.html.md

app/models/participant_profile.rb
This scope name caused me a lot of trouble when I first got onto the project, it was hard to really figure out where it was coming from since the name lead me to believe if wasn't custom.
This comment should hopefully make it easier for future people searching for where the scope/methods come from.
=> Add a comment explaining where the active_record scope comes from

app/services/admin/participants/search.rb
- Ticket: CST-1609
- Reverse the order in the Admin->Participants page
=> [CST-1609] List the newest users first in the admin participants page

app/views/admin/participants/validate_details/new.html.erb
- Ticket: https://dfedigital.atlassian.net/browse/CST-1912
The link doesn't properly use post
=> Fix button on validation page

app/components/admin/schools/cohort_component.html.erb
- Ticket: N/A
This PR fixes a typo
=> Fix a typo

app/controllers/api/v1/participant_declarations_controller.rb, app/controllers/api/v3/participant_declarations_controller.rb, app/services/api/v3/participant_declarations_query.rb, spec/requests/api/v1/participant_declarations_spec.rb, spec/requests/api/v2/participant_declarations_spec.rb, spec/requests/api/v3/participant_declarations_spec.rb, spec/services/api/v3/participant_declarations_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2523
* Updated controller and query service classes to use the collection when returning single participant declaration.
=> [CPDLP-2523] Investigate if there is a data and/or logic bug for EDT GET declarations calls

spec/fixtures/files/importers/cohort_csv_data.csv, spec/fixtures/files/importers/cohort_lead_provider_csv_data.csv, spec/fixtures/files/importers/contract_csv_data.csv, spec/fixtures/files/importers/schedule_csv_data.csv, spec/fixtures/files/importers/statement_csv_data.csv, spec/serializers/api/v3/ecf/participant_serializer_spec.rb, spec/services/importers/create_new_ecf_cohort_spec.rb, spec/services/npq/amend_participant_cohort_spec.rb
- Ticket: N/A
Some tests are failing randomly.
Fix those flaky specs.
=> [CPDLP-2560] Fix flakey specs

app/services/importers/create_npq_contract.rb, app/services/oneoffs/npq/set_special_course_for_npq_contracts.rb, config/analytics_blocklist.yml, db/data/npq_contracts/fake-2021.csv, db/data/npq_contracts/fake-2022.csv, db/data/npq_contracts/fake-2023.csv, db/migrate/20231024151523_add_special_course_to_npq_contracts.rb, db/schema.rb, spec/services/importers/create_new_npq_cohort_spec.rb, spec/services/importers/create_new_npq_course_spec.rb, spec/services/importers/create_npq_contract_spec.rb, spec/services/oneoffs/npq/set_special_course_for_npq_contracts_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2513
* Added new column `special_course` to `NPQContract`
* Updated seed files to enable `special_course` for Maths courses
* Created `Oneoffs::NPQ::SetSpecialCourseForNPQContracts` to allow setting `special_course` value for NPQ contracts.
=> [CPDLP-2513] NPQ Maths - Add new field to NPQ contracts

app/serializers/api/v3/ecf/participant_serializer.rb, app/serializers/api/v3/npq_participant_serializer.rb, app/services/feature_flag.rb, docs/source/release-notes.html.md, spec/docs/v3/ecf_participants_spec.rb, spec/docs/v3/npq_participants_spec.rb, spec/requests/api/v3/ecf/participants_spec.rb, spec/requests/api/v3/npq_participants_spec.rb, spec/serializers/api/v3/ecf/participant_serializer_spec.rb, spec/serializers/api/v3/npq_participant_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2537
* Removed feature flag for `participant_id_changes `
* Added release notes entry
=> [CPDLP-2537] Turn on dedupe / participant_id_changes in production (and remove flag)

spec/requests/api/v3/npq_applications_spec.rb
Flakey failure:
```
Failures:
1) NPQ Applications API GET /api/v3/npq-applications/:id when authorized returns correct data
Failure/Error: expect(parsed_response).to eq(expected_response)
expected: {"data"=>{"attributes"=>{"cohort"=>"2023", "course_identifier"=>"npq-headship", "created_at"=>"2023-1... "works_in_school"=>true}, "id"=>"7043846a-d278-4b07-8fa6-a53aec69747d", "type"=>"npq_application"}}
got: {"data"=>{"attributes"=>{"cohort"=>"2023", "course_identifier"=>"npq-headship", "created_at"=>"2023-1... "works_in_school"=>true}, "id"=>"7043846a-d278-4b07-8fa6-a53aec69747d", "type"=>"npq_application"}}
(compared using ==)
Diff:
@@ -1 +1 @@
-"data" => {"attributes"=>{"cohort"=>"2023", "course_identifier"=>"npq-headship", "created_at"=>"2023-11-15T11:05:17Z", …
```
=> Fix NPQ request spec flakey test

app/controllers/api/v1/npq/application_synchronizations_controller.rb, spec/requests/api/v1/npq/application_synchronization/index_spec.rb
Reverts DFE-Digital/early-careers-framework#4136
=> Revert "update provider application status logic to cater to historic applications"

app/controllers/nominations/choose_how_to_continue_controller.rb, app/forms/schools/add_participants/who_to_add_wizard.rb, app/forms/schools/add_participants/wizard_steps/start_term_step.rb, app/forms/schools/cohorts/setup_wizard/success.rb
=> [CST-1874] Decommission cohortless_dashboard feature flag - 02

app/services/feature_flag.rb, spec/rails_helper.rb
=> [CST-1874] Decommission cohortless_dashboard feature flag - 05

config/initializers/rack_attack.rb, spec/requests/rate_limiting_spec.rb, spec/support/shared_examples/rate_limiting_support.rb
[Jira-2596](https://dfedigital.atlassian.net/browse/CPDLP-2596)
We want to ensure web requests that are rate limited by Rack::Attack still get sent to BigQuery as a web request.
- Send rate limited requests to BigQuery
Web requests are sent to BigQuery via a concern in the ApplicationController. If Rack intercepts the request it won't reach the controller, so we need to manually send web requests that are rate limited to BigQuery.
You can check 429s come through correctly in BigQuery:
```
SELECT * FROM `ecf-bq.ecf_events_review.events` WHERE response_status = "429" AND TIMESTAMP_TRUNC(occurred_at, DAY) = TIMESTAMP("2023-11-22") LIMIT 1000
```
You can generate more using something like `wrk`:
```
wrk -t5 -c5 -d5s https://cpd-ecf-review-4272-web.test.teacherservices.cloud
```
I tested by …
=> Send rate limited requests to BigQuery

app/views/schools/dashboard/_school_cohort_details.html.erb
…career-teachers.education.gov.uk/`
- Ticket: CST-2126
=> [CST-2126] core-materials-info page redirect

app/views/schools/choose_programme/success.html.erb, app/views/schools/cohort_setup/_change_to_core_induction_programme_submitted.html.erb, app/views/schools/cohort_setup/_training_confirmation_cip.html.erb, app/views/schools/core_programme/materials/show.html.erb
Content has been updated to reflect the changes to the Support for early career teacher service:
* no need to sign in
* no progress tracking
- Ticket: 
https://dfedigital.atlassian.net/browse/CST-2111?atlOrigin=eyJpIjoiZTdjYTI0ZTkxMDg0NGJlNmIzYzdmZjMxMWNkZjcwN2MiLCJwIjoiaiJ9
=> Update content to reflect the changes to the Support for early career teacher service

app/forms/schools/add_participants/base_wizard.rb, app/forms/schools/add_participants/wizard_steps/participant_type_step.rb, app/forms/schools/add_participants/wizard_steps/yourself_step.rb, app/views/schools/add_participants/confirm_transfer.html.erb, spec/features/schools/participants/add_participants/sit_add_ect_spec.rb, spec/features/schools/participants/add_participants/sit_add_mentor_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2134): Fix bug when adding a SIT as mentor
=> Register a SIT as mentor

Gemfile, Gemfile.lock, app/components/support_form_component.html.erb, app/components/support_form_component.rb, app/controllers/support_controller.rb, app/forms/support_form.rb, app/jobs/support_query_sync_job.rb, app/models/support_query.rb, app/views/schools/participants/show.html.erb, app/views/support/new.html.erb, app/views/support/show.html.erb, config/analytics.yml, config/analytics_blocklist.yml, config/environments/development.rb, config/environments/production.rb, config/environments/sandbox.rb, config/environments/staging.rb, config/environments/test.rb, config/initializers/zendesk.rb, config/locales/en.yml, config/routes.rb, db/migrate/20231113161634_create_support_queries.rb, db/schema.rb, spec/factories/support_queries.rb, spec/features/support_forms/change_participant_lead_provider_spec.rb, spec/features/support_forms/unspecified_spec.rb, spec/models/support_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-2091
- Adds framework for support query forms and sending queries to Zendesk
- Adds "change lead provider for participant profile" support form
=> [CST-2091] Add support query form system

config/environments/development.rb, config/environments/production.rb, config/environments/sandbox.rb, config/environments/staging.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-2091
- Update default zendesk URl
This will also trigger a review app deploy which will allow me to test the swapped over env variables.
=> Update default Zendesk URL

app/models/support_query.rb, app/views/schools/participants/show.html.erb, config/locales/en.yml, spec/features/support_forms/change_participant_date_of_birth_spec.rb, spec/features/support_forms/change_participant_trn_spec.rb
- Add Support Form: change-participant-date-of-birth
- Add Support Form: change-participant-trn
=> [CST-2166] Add support forms

docs/source/npq/guidance.html.md, docs/source/release-notes.html.md
- Ticket: 
Add very minor edits to a release note and some API guidance
[Review app](https://cpd-ecf-review-4356-web.test.teacherservices.cloud/api-reference)
=> Add very minor edits to a release note and some API guidance

app/controllers/admin/npq/applications/edge_cases_controller.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1548
FundingEligibiltyStatusCode and EmplymentType filters on edge cases page were not working properly.
=> Fixed FundingEligibiltyStatusCode and EmplymentType filters on edge cases page

config/analytics.yml, db/migrate/20231218115100_re_add_analytics_schools_table.rb, db/schema.rb
I thought this was no longer used but it is, and it being missing has caused some errors in queues following the nightly data sync.
=> Re-add the analytics_schools table

app/forms/schools/add_participants/transfer_wizard.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2229)
=> CST-2229: fix bug when choosing current LP/DP in a transfer

app/services/participants/sync_dqt_induction_start_date.rb, spec/services/participants/sync_dqt_induction_start_date_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2198):
=> CST-2198: always save the induction start date coming from DQT

app/controllers/finance/npq/statements_controller.rb, app/views/finance/npq/statements/show.html.erb, spec/factories/npq_contracts.rb, spec/features/finance/npq/view_contract_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2699
Add NPQ special courses into the contract information for the relevant providers.
=> [CPDLP-2699] Add npq special courses into the contract information on statements page

app/components/support_form_component.html.erb, app/controllers/schools/cohorts_controller.rb, app/models/support_query.rb, app/views/schools/cohorts/change_programme.html.erb, config/locales/en.yml, spec/features/schools/training_dashboard/manage_cip_training_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb, spec/features/support_forms/change_cohort_induction_programme_choice_spec.rb
- Add Support Form: change-cohort-induction-programme-choice
=> [CST-2166] Add Support Form: change-cohort-induction-programme-choice

app/jobs/delete_completed_induction_records_job.rb
- Ticket: CST-2110
Fix missing local var in delete_completed_induction_records_job.rb
=> [CST-2110] Fix missing local var error

app/jobs/delete_completed_induction_records_job.rb
- Ticket: CST-2110
Change the log level to info for the failing records to be included in the prod logs
=> [CST-2110] Change the log level to info

terraform/aks/databases.tf, terraform/aks/variables.tf, terraform/aks/workspace_variables/production_aks.tfvars.json
- Ticket: 
Increase prod postgres storage from 32G to 64G
make env terraform-plan
=> Increase prod postgres storage to 64G

config/database.yml
- Ticket: n/a
Use database URL in migration environment database
=> Amend database access to migration environment

app/services/change_schedule.rb, spec/services/change_schedule_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2567
* Added changes to `ChangeSchedule` and tests
=> [CPDLP-2567] Is there a bug around changing schedule where the participant is a non-partnership cohort via a relationship?

app/services/deduplication_service.rb, spec/services/deduplication_service_spec.rb
Extensive tests done with @cwrw. At some point we will move Declarations to proper users.
=> Allow deduplication of records with ParticipantDeclaration

app/services/oneoffs/npq/migrate_declarations_between_statements.rb, spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Trello-2714](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2714&text=2714)
During the one off statement migration we occasionally want to be able to set attributes on the statements we are migrating to.
- Add ability to change to statement attributes during migration
Add option to pass attribute values that will be applied to the statements we are migrating to.
I've tested this locally against a snapshot DB, example output:
```
["~~~ DRY RUN ~~~",
"Migrating declarations from December 2023 to January 2024 for 9 providers",
"Migrating *** declarations for ***",
...
"Statement January 2024 updated with {:deadline_date=>Fri, 22 Dec 2023, :payment_date=>Thu, 25 Jan 2024}",
"Statement January 2024 updated with {:deadline_date=>Fri, 22 Dec …
```
=> Add ability to change statement attributes during migration

docs/source/release-notes.html.md
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2567
* New release note
* https://cpd-ecf-review-4449-web.test.teacherservices.cloud/api-reference/release-notes.html
=> [CPDLP-2567] updated release notes

app/views/admin/participants/details/_show_ecf.html.erb, spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb, spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb, spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb, spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb, spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb, spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb, spec/support/features/pages/admin_support/admin_support_participant_detail.rb
Reverts DFE-Digital/early-careers-framework#4469
=> Revert "[CST-2165] Bring back user ID"

app/mailers/school_mailer.rb, spec/mailers/school_mailer_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2265)
Adds new mailer for SITs to chase AB to register an ECT
Adds new mailer for SITs to engage an AB for an unregistered ECT
=> [CST-2265] Add new mailers for SITs regarding ABs not registering ECTs

app/controllers/admin/performance/support_queries_controller.rb, app/views/admin/performance/_nav.html.erb, app/views/admin/performance/support_queries/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20240125143240_add_index_to_support_queries.rb, db/schema.rb, spec/features/admin/performance/support_form_stats_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-2180
Add stats page for support forms
=> [CST-2180] Add support form stats page

.github/actions/backup-and-restore-snapshot-database/action.yml, .github/actions/backup-and-upload-database/action.yml, .github/actions/deploy-environment-to-aks/action.yml, .github/actions/refresh-migration-database/action.yml, .github/actions/sanitise-and-upload-database/action.yml, .github/workflows/aks_destroy_review.yml, Makefile, terraform/aks/providers.tf
Not to be deployed until terraform modules has been updated on Monday Jan 29th.
- [Checklist](https://hedgedoc.teacherservices.cloud/FZWIycYoTDq_RwKLNg0kRg?view#Prepare-PRs-for-each-deployed-app-to-update-the-authentication)
Enable azure rbac on deployment (for when it is enabled in the cluster)
Update Makefile, terraform and workflows to use rbac if configured for the cluster.
There is a lot of hardcoding, so following a similar pattern
=> Enable azure rbac on deployment

Makefile
[Jira-2754](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2754)
We currently have a command that will download a file from a pod in a given AKS cluster, however we have no way of uploading a file to a pod.
The current method of downloading a file will also choose a pod in the cluster at random; ideally we want to download a file from each pod in the cluster (in case we create the file in one pod and the command tries to download it from a different pod in the same cluster).
In order to add a new cohort we need to be able to upload the various CSVs used by the scripts to the pods.
- Add Make command to upload files from AKS pods
Add make command to upload files and modify the command to download files to pull from each pod in the …
=> Add Make command to upload files from AKS pods

app/lib/mail/delivery_recorder.rb, app/lib/mail/redirector.rb, config/initializers/mail.rb, config/initializers/sidekiq.rb, lib/tasks/cloudfoundry.rake, lib/tasks/flush_redis.rake, spec/lib/mail/delivery_recorder_spec.rb
Reverts DFE-Digital/early-careers-framework#4354
=> Revert "Remove references to VCAP/PaaS"

spec/support/shared_examples/rate_limiting_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2700
* Fixes flaky issue with ordering of BQ event queue.
=> [CPDLP-2700] fix flaky test

Gemfile, Gemfile.lock, package.json, spec/cypress/support/step_definitions/common-interaction.js, yarn.lock
The headline change here is the new crown graphic.
|-------|------------|
| ![Screenshot from 2024-02-19 17-00-30](https://github.com/DFE-Digital/early-careers-framework/assets/128088/422e19ae-4734-47d8-9046-1ad54ca6c470) | ![Screenshot from 2024-02-19 17-00-38](https://github.com/DFE-Digital/early-careers-framework/assets/128088/c2370892-45d1-43e7-ac65-fc50bdb62c5d) |
=> Upgrade to govuk-frontend 5.1.0

app/services/induction/amend_participant_cohort.rb, spec/services/induction/amend_participant_cohort_spec.rb
It has been decided to allow multi-cohort participants.
When a participant needs a permanent cohort setup, we will add a new induction record to the chain linked to the new school cohort default providers and the term equivalent schedule.
Historical records will be left untouched. 
The Induction::AmendParticipantCohort used to change the cohort of a participant will now stick to the rules above.
=> CST-2217: allow multi-cohort participants

app/services/oneoffs/flipflop_users_cleanup.rb, docs/source/release-notes.html.md, spec/services/oneoffs/flipflop_users_cleanup_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2796
* One off script to find all flip flopped users and transfer them to primary user.
* Updated release notes
=> [CPDLP-2796] Clean up flipflopping users

app/services/oneoffs/npq/migrate_declarations_between_statements.rb, spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Jira-2876](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2876)
When migrating declarations we want to ensure the statement we are migrating to has a `deadline_date` in the past. This way, the `MarkAsPayable` job will run and correctly transition the declarations.
- Only migrate to future dated statements
=> Only migrate to future dated statements

app/views/schools/mentors/_mentor_training.html.erb, spec/features/schools/participant_dashboard/mentor_training_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb
=> View mentor training completion for ERO mentors and mentors who have a completed declaration on mentor profile

spec/features/schools/participant_dashboard/mentor_training_spec.rb, spec/features/schools/training_dashboard/manage_training_steps.rb
Fix some spec issues spotted during deployment
=> Fix errors in specs

Gemfile, Gemfile.lock
Reverts DFE-Digital/early-careers-framework#4616
=> Revert "Bump strong_migrations from 1.7.0 to 1.8.0"

config/sidekiq_cron_schedule.yml
- Ticket: N/A
Fix typo in the cron schedule
=> Fix the email schedules cron

Gemfile.lock
- Ticket: N/A
Add the arm darwin platform in the bundle for arm based macs
=> Bundle for arm-darwin-22

app/services/feature_flag.rb
- Ticket: [CPDLP-2937](https://dfedigital.atlassian.net/browse/CPDLP-2937)
Ongoing work on NPQ capping needs to be flagged to avoid any changes being viewed in sandbox or prod.
Add feature flag for NPQ capping.
Dev testing
[CPDLP-2937]: https://dfedigital.atlassian.net/browse/CPDLP-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2937] Add feature flag for NPQ capping

app/models/npq_contract.rb, app/services/importers/create_npq_contract.rb, config/analytics_blocklist.yml, db/data/npq_contracts/fake-2021.csv, db/data/npq_contracts/fake-2022.csv, db/data/npq_contracts/fake-2023.csv, db/migrate/20240411160127_add_funding_cap_to_npq_contracts.rb, db/schema.rb, spec/models/npq_contract_spec.rb
- Ticket: [CPDLP-2936](https://dfedigital.atlassian.net/browse/CPDLP-2936)
We need to capture if a specific cohort for NPQ supports capping. We also would like to capture limits on funded spaces for providers.
Add `funding_cap` field to NPQ contract.
Documentation has been updated as well https://dfedigital.atlassian.net/wiki/x/BwCT6
[CPDLP-2936]: https://dfedigital.atlassian.net/browse/CPDLP-2936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-2936] Add funding_cap field to NPQ contracts

spec/support/features/axe_helper.rb
Several items came through from the accessibility audit that should have been picked up by automation. Turns out we have been testing against WCAG 2.0 so this updates the ruleset requirements.
- Update ruleset to WCAG 2.2 AA
- Fix issues that arise
=> Update accessibility checks to WCAG 2.2 AA

terraform/aks/monitoring.tf
https://trello.com/c/Z6eliKhq/1654-review-statuscake-contact-groups
added infra team contact group
added infra team contact group
make production terraform-plan
=> Added infra team group to statuscake

terraform/aks/workspace_variables/migration_aks.tfvars.json
* remove the flexible PostgreSQL SKU so it reverts to the default specified in app's variables
* set the storage size to 64GB
=> Increase migration env azure_storage_mb to 64GB

docs/source/ecf/guidance.html.md, docs/source/npq/guidance.html.md, spec/docs/v3/ecf_participants_spec.rb, swagger/v3/api_spec.json, swagger/v3/component_schemas/ECFParticipant.yml, swagger/v3/component_schemas/ParticipantIdChange.yml
To avoid confusion swap from/to participant ids to be closer to reality and inline with the current participant ID
- Ticket: n/a
- Update NPQ/ECF guidance
- Update API spec v3
=> Swap participant id changes to show real behaviour

Gemfile, Gemfile.lock, app/assets/stylesheets/application.sass.scss, package.json, yarn.lock
=> Update govuk-frontend and associated libs to 5.4.0

.github/workflows/brakeman.yml, .github/workflows/cypress.yml, .github/workflows/lint.yml, spec/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step_spec.rb
Reverts DFE-Digital/early-careers-framework#4814
=> Revert "Bump ruby/setup-ruby from 1.176.0 to 1.177.0"

app/models/cohort.rb, config/analytics.yml, db/migrate/20240517214659_add_payments_closed_at_to_cohorts.rb, db/schema.rb, spec/models/cohort_spec.rb
Add new field to Cohort model to mark cohorts that freeze payments
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2556):
=> Cst 2556 closing 2021 add payments closed at field to cohort model 2

docs/source/release-notes.html.md
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2977
Add release note for cohort 2024
=> Add cohort release note 2024 for sandbox

config/environments/review.rb
- Ticket: n/a
To test declarations in the future, allow time travel to set the header `X-With-Server-Date` with future dates
=> Add Time travel to review app for testing the API

app/controllers/admin/npq/applications/eligible_for_funding_controller.rb, app/models/npq_application.rb, config/locales/en.yml, spec/features/admin/npq_applications/edge_cases_spec.rb, spec/models/npq_application_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3078
Update the admin tool in the NPQ tab so it allows updating the eligible for funding value, where we should return an error if the funded place is true and we attempt to set the eligible for funding to false.
=> Validate eligibility value for funded places

spec/features/schools/participants/add_participants/sit_add_ect_when_cohort_payments_frozen_spec.rb
This covers the journey of a participant who would be added to a Cohort where payments are frozen.
- Ticket:
=> Add scenario for Cohort payments frozen

app/serializers/api/v1/npq_participant_serializer.rb, spec/serializers/api/v1/npq_participant_serializer_spec.rb
A bit embarrassing 😊 , but I made a double mistake on the Serializer and in the test.
Issue spotted when working on https://github.com/DFE-Digital/early-careers-framework/pull/4873
I have not created the commit in https://github.com/DFE-Digital/early-careers-framework/pull/4873 as we are not going to merge it until we are ready for Sandbox testing.
=> Fix NPQ Participant Serialzier: funded places

docs/source/release-notes.html.md, spec/docs/v3/ecf_participants_spec.rb, swagger/v3/api_spec.json, swagger/v3/component_schemas/ECFEnrolment.yml
> ⚠️ Do not merge until we're ready to enable in sandbox
Follow on from #4858 to enable this feature in sandbox (the feature flag will still need to be toggled for the sandbox environment after shipping).
=> Flag multi cohort participants to providers (swagger/release note)

docs/source/release-notes.html.md
Multicohort release note has changed.
- Ticket: n/a
Update release note for multicohort release to sandbox
content innit
=> Update release note for multicohort release

app/views/nominations/request_nomination_invite/resend_email.html.erb, app/views/start/index.html.erb, spec/features/request_access_spec.rb
- Ticket: CST-2581
- Updated the Start page
- Updated the Request access page
| <img width="629" alt="Screenshot 2024-06-12 at 11 43 45" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/38ce3636-f5e1-40b1-9956-87298ea2dd99"> | <img width="617" alt="Screenshot 2024-06-12 at 11 44 17" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/3b0284db-5d1a-48cf-acbc-aebc532c2fbe">|
|<img width="613" alt="Screenshot 2024-06-12 at 11 46 51" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/8235ada2-f5c7-4469-964f-8b58d20282a6">|<img width="644" alt="Screenshot 2024-06-12 at 11 47 00" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/bef481b7-291d-4d86-aea2-26ddaaf69453 …
=> [CST-2581] Content changes

docs/source/npq/definitions-and-states.html.md, docs/source/npq/guidance.html.md
Update NPQ guidance to include NPQ capping
- Ticket: n/a
- Update response bodies for NPQ applications and participants
- Add explanation for change funding cap endpoint
- Add funded place and funding cap to NPQ key concepts
This pr has a link to another pr which will go in shortly as well
=> Add funded place to NPQ API guidance

docs/source/ecf/guidance.html.md
- Ticket: n/a
Add `cohort_changed_after_payments_frozen` field to guidance ECF responses
=> Add new frozen field to ECF guidance

spec/docs/v1/npq_applications_spec.rb, spec/docs/v2/npq_applications_spec.rb, spec/docs/v3/npq_applications_spec.rb, swagger/v1/api_spec.json, swagger/v2/api_spec.json, swagger/v3/api_spec.json
We need the application ID instead of the participant ID
- Ticket: n/a
Amend typo in API spec for change schedule
=> Amend change funded place description in API spec

app/mailers/school_mailer.rb, lib/tasks/comms.rake, spec/mailers/school_mailer_spec.rb
- Ticket: CST-2605
We are preparing the school communications for the new registration year.
- Added the pilot communications mailer
- Added a rake task to process a list of school URNs provided in a CSV file and send the communications.
- Fixed minor bugs in the chaser and launch communications
=> [CST-2605] School comms for the new registration year

app/mailers/school_mailer.rb, lib/tasks/comms.rake
- Ticket: CST-2613
A few more minor updates in the school comms required for this year.
- Update a few checks for 2024
- Add additional personalisation param to the launch email for the SITs
=> [CST-2613] Update the school comms

swagger/v3/api_spec.json, swagger/v3/component_schemas/NPQApplicationAcceptAttributesRequest.yml
This field is optional in v3 on NPQ accept
- Ticket: n/a
=> Remove required schedule identifier from accept in v3 spec

spec/models/induction_record_spec.rb, swagger/v1/api_spec.json, swagger/v1/component_schemas/MultipleNPQParticipantsResponse.yml, swagger/v1/component_schemas/NPQParticipantAttributes.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/MultipleNPQParticipantsResponse.yml, swagger/v2/component_schemas/NPQEnrolment.yml, swagger/v2/component_schemas/NPQParticipantAttributes.yml, swagger/v3/api_spec.json, swagger/v3/component_schemas/NPQEnrolment.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3082
During PO testing the ticket above, we found some discrepancies between the npq participant serializer and the api docs.
Fix those discrepancies in api v1/v2/v3 docs for npq participant endpoints.
=> Tweak npq participant endpoints api docs

docs/source/release-notes.html.md
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3179
Add release note for ECF cohort 2024
Going out today
=> Add release note for ECF 2024 cohort

documentation/handling_participants_moving_from_a_frozen_cohort.md
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2626)
Added a doc based on notes from @ltello to help devs understand what is required to handle changes to participants in a cohort frozen for payments.
Please add any suggestions that would be helpful for devs dealing with these participants especially if dealing with support requests involving 2021 participants
=> [CST-2626] Dev guidance for participants in frozen cohorts

app/services/change_schedule.rb, spec/services/change_schedule_spec.rb
[Jira-3187](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3187)
For participants that have been migrated out of a payments frozen cohort, we want to ignore any declarations made in a frozen cohort when determining if they can change schedule.
This will allow providers to migrate participants to an extended schedule after they have migrated from the 2021 payments frozen cohort to the 2024 active registration cohort, even if they have billable declarations in the 2021 cohort.
- Ignore declarations in frozen cohort on ChangeSchedule
The `RecordDeclaration` service will ensure these declarations are still taken into account when a declaration is created; so if we have a `started` …
=> Ignore declarations in frozen cohort on ChangeSchedule

docs/source/release-notes.html.md
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2957
Add NPQ funding cap/Senco/2024 cohort release note
To be merged on Friday or Monday
=> Add NPQ 2024 release note

terraform/application/workspace_variables/production.tfvars.json
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio
Enabled logiio to push logs to logit.
All production logs should go to logitio
=> Logitio enabled for production

app/views/layouts/_phase_banner.erb, app/views/layouts/_width_container.html.erb, app/views/layouts/_width_container_wide.html.erb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2665)
Add ARIA landmarks around phase banner and back links / breadcrumbs
Add ARIA role to phase banner and back link so that content is correctly contained in landmarked regions.
=> [CST-2665] A11y fixes - add page region landmarks

app/queries/schools/that_have_not_added_participants_query.rb, app/services/bulk_mailers/school_reminder_comms.rb, spec/queries/schools/that_have_not_added_participants_query_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2687)
Refactor query to require cohort and also try to make dry run counts more accurate in the other bulk mailers
Make cohort a required param for the query.
Add the join clauses before calling `.count` in the bulk mailer methods.
=> [CST-2657] Fix timeout in mailer query

app/services/induction/amend_participant_cohort.rb, spec/services/induction/amend_participant_cohort_spec.rb
`Induction::AmendParticipantCohort` should not add errors on participants sitting already in the target cohort.
This is causing the errors table `SyncDQTInductionStartDateError` to have entries that should not be there.
The job `CheckEligibleEctsThatFailedPermanentCohortSetupJob` that retry these cohort change errors is processing loads of unnecessary entries that will never succeed and will be processed on every run
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2696)
Split validations into 2 groups. Those previously required to check if the participant is in the right cohort and those that need to be met to change the cohort of the participant.
=> CST-2696: participants already in the target cohort should succeed cohort changes.

app/views/layouts/_application.html.erb
- Ticket: CST-2668
The main content link has been skipped from the tab.
=> [CST-2668] Tab order when cookie visible

app/models/npq_application.rb, app/services/admin/npq_applications/edge_case_search.rb, app/views/admin/npq/applications/edge_cases/show.html.erb, config/analytics.yml, db/migrate/20240715080739_add_referred_by_return_to_teaching_adviser_to_npq_applications.rb, db/schema.rb, spec/requests/api/v1/npq_profiles_spec.rb, spec/services/admin/npq_applications/edge_case_search_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-1984
=> Add referred by return to teaching adviser to edge cases

config/initializers/dfe_analytics.rb
Reverts DFE-Digital/early-careers-framework#5108
> [!WARNING]  
> Not to be merged until 2024-08-09.
=> Remove BigQuery maintenance window for DfE Analytics

documentation/service-rules/appropriate-body-users.md, documentation/service-rules/delivery-partner-users.md, documentation/service-rules/dfe-users.md, documentation/service-rules/grant-funding-summary.md, documentation/service-rules/lead-provider-users.md, documentation/service-rules/school-admins.md
These rules cover the ECF service as it currently stands. We're about to start incrementing these towards how ECF2 will work so it makes sense to keep a copy of them here.
=> Copy service rules from ECF2

.github/workflows/deploy.yml
Our standard practice is to run SNYK scanning against build images
Add snyk to build step
Check build workflow log
https://trello.com/c/9g2RL16e/1996-add-snyk-scan-to-cicd
=> Add snyk scan to build workflow

app/services/oneoffs/ecf/update_contracts.rb, spec/services/oneoffs/ecf/update_contracts_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3362
* Service class `Oneoffs::ECF::UpdateContracts` creates contracts with new values for ECF based on the provided CSV
=> [CPDLP-3362] Update ECF contracts to align with final ECF contract data

app/services/change_milestone_date.rb, config/locales/en.yml, lib/tasks/change_milestone_date.rake, spec/services/change_milestone_date_spec.rb
To amend a new milestone milestone date and payment date we need to amend the existing script
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3407
- Add payment as a new attribute
- Add validations for payment date
- Include payment date in updates
- Include payment date in rake task
=> [CPLD-3407] Add payment date to change milestone service

spec/factories/cohorts.rb, spec/fixtures/files/importers/cohort_csv_data.csv, spec/fixtures/files/importers/cohort_lead_provider_csv_data.csv, spec/fixtures/files/importers/contract_csv_data.csv, spec/fixtures/files/importers/schedule_csv_data.csv, spec/fixtures/files/importers/statement_csv_data.csv, spec/models/cohort_spec.rb, spec/requests/schools/dashboard_spec.rb, spec/serializers/finance/ecf/duplicate_serializer_spec.rb, spec/services/importers/create_new_ecf_cohort_spec.rb, spec/services/partnerships/report_spec.rb, spec/services/record_declaration_spec.rb
- Ticket: n/a
There are many failures in the pipeline that need to be fixed, however to unblock the pipeline push the cohort rollover to October until we fix those properly
We will fix those during this month :(
=> Unblock pipeline by pushing cohort rollover into October

terraform/application/workspace_variables/migration.tfvars.json
Ticket: [CPDLP-3481](https://dfedigital.atlassian.net/browse/CPDLP-3481)
The current migration environment is not scaled up and not performant when migrations run
Scale up migration env.
[CPDLP-3481]: https://dfedigital.atlassian.net/browse/CPDLP-3481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-3481] Scale up migration env

.github/actions/backup-and-restore-snapshot-database/action.yml, .github/actions/backup-and-upload-database/action.yml, .github/actions/refresh-migration-database/action.yml, .github/actions/sanitise-and-upload-database/action.yml
Updated actions to use shared kubectl action
Updated actions to use shared kubectl action
=> Updated pipeline to use shared action

.github/actions/refresh-migration-database/action.yml, .github/workflows/refresh_migration_database.yml
Move schedule to the workflow instead of the action.
=> Fix nightly migration cron

data/appropriate_bodies.csv
- Ticket: [CST-2765]
Several AB names have changed, and we need to update the Appropriate Bodies data file to reflect these changes.
[CST-2765]: https://dfedigital.atlassian.net/browse/CST-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CST-2765] Update outdated names in the AB csv

app/services/api/participant_declarations/index.rb, app/services/api/v3/finance/statements_query.rb, app/services/api/v3/participant_declarations_query.rb, app/services/feature_flag.rb, app/services/record_declaration.rb, app/services/void_participant_declaration.rb, config/environments/separation.rb, lib/npq_api_endpoint.rb, spec/lib/npq_api_endpoint_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/participant_declarations_spec.rb, spec/requests/api/v2/participant_declarations_spec.rb, spec/requests/api/v3/participant_declarations_spec.rb, spec/services/api/participant_declarations/index_spec.rb, spec/services/api/v3/finance/statements_query_spec.rb, spec/services/api/v3/participant_declarations_query_spec.rb, spec/services/feature_flag_spec.rb, spec/services/record_declaration_spec.rb, spec/services/void_participant_declaration_spec.rb, spec/support/shared_examples/feature_enabled_npq_api_endpoint_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3588
* Updated `NpqApiEndpoint` service class to use feature flag
* Replaced all `env` config with the feature flag `FeatureFlag.active?(:disable_npq)`
=> [CPDLP-3588] Turn off NPQ in ECF - Swap out app config for feature flag

.github/workflows/refresh_migration_database.yml
This isn't executing because it asks for a Papertrail user; we need to set it before running.
=> Set user for PaperTrail on CI command

.github/workflows/refresh_migration_database.yml
=> Fix typo in DB refresh action

app/forms/finance/choose_payment_breakdown_form.rb, app/models/finance/schedule.rb, app/models/finance/schedule/npq.rb, app/services/feature_flag.rb, app/views/finance/participants/show.html.erb, app/views/finance/schedules/index.html.erb, config/routes.rb, spec/features/finance/participant_drilldown_spec.rb, spec/features/finance/payment_breakdown_spec.rb, spec/features/finance/schedules_spec.rb, spec/models/finance/schedule/ecf_spec.rb, spec/models/finance/schedule/npq_ehco_spec.rb, spec/models/finance/schedule/npq_leadership_spec.rb, spec/models/finance/schedule/npq_specialist_spec.rb, spec/models/finance/schedule/npq_support_spec.rb, spec/requests/finance/npq_finance_routes_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3590
* Updated finance dashboard to hide any NPQ related stuff for:
* participant drill down
* statements
* schedules
* Hidden all NPQ finance routes
* Some FIXME's as I forgot to branch off 🤦‍♂️ https://github.com/DFE-Digital/early-careers-framework/pull/5233
=> [CPDLP-3590] Turn off NPQ in ECF - Disable NPQ in finance view

app/models/appropriate_body.rb, app/services/participants/check_and_set_completion_date.rb, spec/factories/appropriate_bodies.rb, spec/services/participants/check_and_set_completion_date_spec.rb
[Ticket](https://dfedigital.atlassian.net/browse/CST-2800)
=> CST-2800: do not move from frozen cohort participants with ESP or ISTIP appropriate body

Gemfile, Gemfile.lock, app/forms/finance/choose_payment_breakdown_form.rb
- Ticket: N/A
Linked to https://github.com/rswag/rswag/issues/789
=> Add ostruct gem

docs/source/get-started.html.md, docs/source/index.html.md, docs/source/release-notes.html.md
⚠️ This is blocked until we perform separation in production ECF/NPQ
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3529
Add release note in ECF for NPQ separation. 
This will be merged on the 27th of November after separation is complete and successful in ECF/NPQ
=> [CPDLP-3529] Add NPQ separation release note for ECF

app/services/api/v3/participant_declarations_query.rb, spec/services/api/v3/participant_declarations_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3804
* Issue happens when querying NPQ only provider
* Fix in `Api::V3::ParticipantDeclarationsQuery`
* Added test
=> [CPDLP-3804] ECF v3 declaration query bug

app/views/schools/change_request_support_query/lead_provider_participant_intro.html.erb
- Ticket: CST-2811
The current page incorrectly states that the new provider will report the changes to us.
This update revises the content to reflect what is actually happening.
=> [CST-2811] Update content in the change LP support form

.github/actions/backup-and-restore-snapshot-database/action.yml, .github/workflows/restore_snapshot_database.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3916
* Updated refresh snapshot workflow to include two boolean options to exclude "versions" and "api_requests" tables
=> [CPDLP-3916] Add options to restore snapshot workflow

app/services/importers/create_cohort.rb, config/analytics.yml, db/data/cohorts/cohorts.csv, db/migrate/20250106145039_add_mentor_funding_to_cohorts.rb, db/schema.rb, spec/factories/cohorts.rb, spec/services/importers/create_cohort_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3898
* New migration to add `mentor_funding` to `Cohort`
* Updated `Importers::CreateCohort`
=> [CPDLP-3898] Mentor Funding - Add new field to cohort to indicate Mentor funding

.github/actions/deploy-environment-to-aks/action.yml, .github/workflows/deploy.yml, .github/workflows/destroy_review.yml, config/initializers/dfe_analytics.rb, terraform/application/application.tf, terraform/application/dfe_analytics.tf, terraform/application/variables.tf, terraform/application/workspace_variables/production.tfvars.json, terraform/application/workspace_variables/review.tfvars.json, terraform/application/workspace_variables/sandbox.tfvars.json, terraform/application/workspace_variables/staging.tfvars.json
- Ticket: https://trello.com/c/sIkKBrl0
Enable google federated auth
Data should be visible in the events table
=> Migrate gcp-wif

terraform/application/workspace_variables/staging.tfvars.json
- Ticket: https://trello.com/c/sIkKBrl0
Enable google federated auth
Data should be visible in the events table
=> Enable federated auth for bq for test

terraform/application/workspace_variables/production.tfvars.json, terraform/application/workspace_variables/sandbox.tfvars.json
- Ticket: https://trello.com/c/sIkKBrl0
Enable google federated auth
Data should be visible in the events table
=> Add gcp wif cpd sandbox prod

.github/workflows/brakeman.yml
- Ticket: N/A
Bump brakeman version.
=> Bump brakeman version

Gemfile.lock
- Ticket: N/A
- Bump rdoc to 6.11.0
=> Bump rdoc to 6.11.0

app/models/participant_declaration/ecf.rb, app/models/participant_profile/ecf.rb, spec/models/participant_declaration/ecf_spec.rb, spec/models/participant_profile/ecf_spec.rb
We no longer use this and it will be removed in a following commit.
- Stop writing to `temp_type`
=> Stop writing to `temp_type`

config/environments/production.rb
- Ticket: [CPDLP-4052](https://dfedigital.atlassian.net/browse/CPDLP-4052)
Our services currently send a large amount of `DfE::Analytics::SendEvents` log messages to our Logit stacks.
They are a large proportion of total messages sent, sometimes exceeding 50% of the daily total.
- Drop sending DfE::Analytics::SendEvents info events to Logit;
[CPDLP-4052]: https://dfedigital.atlassian.net/browse/CPDLP-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-4052] Reduce logging from DfE::Analytics::SendEvent

.github/actions/backup-and-restore-snapshot-database/action.yml, .github/actions/backup-and-upload-database/action.yml, .github/actions/refresh-migration-database/action.yml, .github/workflows/restore_snapshot_database.yml
Fix to add permissions for restoring Snapshot DB
Adding write and contents permission, this will fix the workflow
=> fix: Adding permissions for restoring snapshot DB

docs/source/changes-for-the-2025-2026-academic-year.html.md
- Ticket: n/a
we haven't released evidence types yet to sandbox, update the date to ensure it reflects reality
n/a
=> Update evidence types release to mid march

spec/services/finance/ecf/ect/uplift_calculator_spec.rb, spec/services/finance/ecf/uplift_calculator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4020
* Fix for `Finance::ClawbackDeclaration` service changes requiring `voided_by_user` parameter
=> [CPDLP-4020] fixes to tests for recent voided_by_user change

Makefile
- Ticket: https://trello.com/c/qyXB3RQA/1972-implement-ci-cd-for-domains-on-all-services
Correcting AZ login process to deploy domains via CICD
https://github.com/DFE-Digital/early-careers-framework/actions/runs/13706617546
=> Correction for domains AZ login

app/models/cohort.rb, app/models/induction_record.rb, app/models/participant_declaration.rb, app/models/participant_profile/ecf.rb, app/models/participant_profile/mentor.rb
- Ticket: https://github.com/DFE-Digital/early-careers-framework/compare/4098-cleanup-ignored-fields?expand=1
* Removed unneeded `ignored_columns`
=> [CPDLP-4098] Tech debt - cleanup ignored fields

app/services/importers/create_call_off_contract.rb, app/services/importers/create_mentor_call_off_contract.rb, spec/services/importers/create_call_off_contract_spec.rb, spec/services/importers/create_mentor_call_off_contract_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4103
* Updated `Importers::CreateCallOffContract` to create contracts for cohorts 2022 onwards.
* Updated `Importers::CreateMentorCallOffContract` to create contracts for cohorts 2025 onwards.
=> [CPDLP-4103] fix seed data to create contracts for all the statements

docs/source/2022-cohort-closure-information-for-lead-providers.html.md
- Ticket: n/a
Add guidance for closure of 2022 cohort for lead providers
=> Add 2022 cohort closure guidance for lead providers

docs/source/2022-cohort-closure-information-for-lead-providers.html.md
Hey @leandroalemao, I've made some minor tweaks to the copy. Can you do the deployment honours?
=> Minor edits

docs/source/changes-for-the-2025-2026-academic-year.html.md
I've added the published date at the top of the page.
=> Added publication date

app/controllers/schools/dashboard_controller.rb, config/initializers/content_security_policy.rb
- Ticket: N/A
Fix ECF CSP violations (reports)
- Relax CSP for schools controller
- Add google fonts to style src content security policy
=> Relax CSP for schools controller

docs/source/index.html.md
- Ticket: CPDLP-3993
Tightening up the copy so that it's clear and more concise.
=> Update the 'About the API' guidance

docs/lib/markdown_renderer.rb, docs/source/release-notes.html.md
- Ticket: [CPDLP-4132](https://dfedigital.atlassian.net/browse/CPDLP-4132)
We issue a release note notifying providers of the upcoming changes for cohort 22 closure in sandbox.
- Add release note on closing 22 cohort to sandbox
[Review app](https://cpd-ecf-review-5661-web.test.teacherservices.cloud/api-reference/release-notes.html)
[CPDLP-4132]: https://dfedigital.atlassian.net/browse/CPDLP-4132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CPDLP-4132] Add release note on closing 22 cohort to sandbox

docs/source/ecf/definitions-and-states.html.md
- Ticket: [CPDLP-4142](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-4142)
Add 'IDs explained' section
**Don't merge and deploy until @cwrw has reviewed the content**
[CPDLP-4142]: https://dfedigital.atlassian.net/browse/CPDLP-4142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add 'IDs explained' section

docs/source/release-notes.html.md, swagger/v1/api_spec.json, swagger/v1/component_schemas/ECFParticipantWithdrawAttributes.yml, swagger/v2/api_spec.json, swagger/v2/component_schemas/ECFParticipantWithdrawAttributes.yml, swagger/v3/api_spec.json, swagger/v3/component_schemas/ECFParticipantWithdrawAttributes.yml, swagger/v3/component_schemas/ECFSchoolAttributes.yml, swagger/v3/component_schemas/ECFWithdrawal.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4160
* Updated endpoints:
* `/api/v3/schools/ecf`
* `/api/v{n}/participant/ecf/{ID}/withdraw`
* `/api/v3/participant/ecf`
* Added release notes
=> [CPDLP-4160] Release note and spec docs updates for new programme types

docs/source/release-notes.html.md
Release note has incorrect API urls
- Ticket: n/a
Update URLs in release note to include correct API urls
=> Update release note for programme type changes with correct urls

docs/source/ecf/schedules-and-milestone-dates.html.md
Made the copy more active and added line about access to training materials not being tied to a cohort.
- Ticket: [CPDLP-4145
](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-4145)
=> Updated the intro

docs/source/ecf/guidance.html.md
Overhaul of the 'Confirm, view and update partnerships' guidance section, including the addition of a new troubleshooting sub-section.
- Ticket: [CPDLP-4144](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-4144)
[CPDLP-4144]: https://dfedigital.atlassian.net/browse/CPDLP-4144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update partnerships API guidance

db/new_seeds/base/add_declarations.rb
[Jira-4268](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4268)
We occasionally have seed failures when deploying review apps due to declarations being created that already exist or when the declaration date is not after the milestone date.
Skip creating declarations that already exist for the user (matching on type).
Ensure declaration date is always after the milestone date.
- Fix flakey review app seeds
I've ran the seeds locally and in the review apps a number of times and can't seem to replicate the errors any longer.
=> Fix flakey review app seeds

.github/workflows/postgres-ptr.yml, terraform/application/workspace_variables/staging.tfvars.json
- Ticket: https://trello.com/c/xzhTdSFq/2234-ecf-plan-for-dr-test-may-2025?completedInviteSignup=1
- allow staging to create its own storage account for backups
- add new workflow for PTR recovery based on DFE workflow
- test a successful PTR restore in staging envt
https://github.com/DFE-Digital/early-careers-framework/actions/runs/15047913790
=> feat(2234):  added tested PTR restore workflow to ECF

docs/source/ecf/guidance.html.md
- Ticket: [CPDLP-4234](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-4234)
Updates to the declarations guidance, including a new sub-section about how to deal with declarations getting stuck in a submitted state.
[CPDLP-4234]: https://dfedigital.atlassian.net/browse/CPDLP-4234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update declarations guidance

.github/workflows/maintenance.yml, maintenance_page/Dockerfile, maintenance_page/manifests/staging/ingress_internal_to_main.yml, maintenance_page/manifests/staging/ingress_internal_to_maintenance.yml, maintenance_page/manifests/staging/ingress_maintenance.yml, maintenance_page/manifests/staging/ingress_temp_to_main.yml
- Ticket: https://trello.com/c/QJnC0E8h/2324-ecf-dr-test
add staging to maintenance workflow
https://github.com/DFE-Digital/early-careers-framework/actions/workflows/maintenance.yml
=> feat(2324): add staging to maintenance workflow

.github/workflows/restore-deleted-postgres.yml
[Ticket: feat(2477): ECF - add recover deleted postgres db workflow](https://trello.com/c/QANXFMhR/2447-add-recover-deleted-postgres-workflow)
1. add new workflow to allow new functionality - restore a deleted postgres db
https://github.com.mcas.ms/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/17242013345/job/48921566651
=> feat(2477): ECF - add recover deleted postgres db workflow

.devcontainer/docker-compose.yml, app/jobs/set_participant_completion_date_job.rb, app/models/riab/application_record.rb, app/models/riab/induction_period.rb, app/models/riab/teacher.rb, app/services/participants/check_and_set_completion_date.rb, config/database.yml, config/initializers/dfe_analytics.rb, config/initializers/inflections.rb, config/sidekiq_cron_schedule.yml, db/riab_test_schema.rb, spec/factories/riab/induction_periods.rb, spec/factories/riab/teachers.rb, spec/rails_helper.rb, spec/services/participants/check_and_set_completion_date_spec.rb
=> 1401 in progress trs two
