DFE-Digital/early-careers-framework

- app/controllers/appropriate_bodies/participants_controller.rb
- app/services/appropriate_bodies/induction_records_query.rb
- spec/features/appropriate_bodies/participants_spec.rb
- spec/services/appropriate_bodies/induction_records_query_spec.rb
- Ticket: [CPDLP-2293](https://dfedigital.atlassian.net/browse/CPDLP-2293)
As an AB I need the latest data about any ECF training/s a participant registered for their induction with me is doing.
The AB service ‘picks’ the most accurate/timely record for a given participant for a given training.
[CPDLP-2293]: https://dfedigital.atlassian.net/browse/CPDLP-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2293] Fix appropriate bodies service duplicates

- app/services/api/concerns/fetch_latest_induction_records.rb
- app/services/api/concerns/filter_cohorts.rb
- app/services/api/concerns/filter_training_status.rb
- app/services/api/concerns/filter_updated_since.rb
- app/services/api/v1/ecf/participants_query.rb
- app/services/api/v3/concerns/fetch_latest_induction_records.rb
- app/services/api/v3/ecf/participants_query.rb
- app/services/api/v3/ecf/unfunded_mentors_query.rb
- Ticket: [CPDLP-2312](https://dfedigital.atlassian.net/browse/CPDLP-2312)
In API queries, we are calculating the latest induction records to extract relevant data. However this logic is duplicated across most queries in different versions.
Consolidate where possible the induction record latest queries in the API.
[CPDLP-2312]: https://dfedigital.atlassian.net/browse/CPDLP-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2312] Remove duplication for api latest induction record queries

- app/controllers/schools/cohort_setup_controller.rb
- app/forms/schools/cohorts/setup_wizard/success.rb
- app/models/lead_provider.rb
- spec/forms/schools/cohorts/setup_wizard_spec.rb
- spec/models/lead_provider_spec.rb
- [Ticket: ](https://dfedigital.atlassian.net/browse/CST-1710)
Do not notify school programme changes to providers not training in the related cohort.
> CST-1710: stop sending emails to capita when a capita school chooses a different training provider for 2023

- app/models/participant_declaration.rb
- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
`NameError: Rails couldn't find a valid model for ParticipantDeclaration::NPQ association. `
We're getting some exceptions like the above one in dev due to how Ruby loads classes and constants... (top-level constant lookup rule).. there's more context in the website below:
https://blog.jetbrains.com/ruby/2017/03/why-you-should-not-use-a-class-as-a-namespace-in-rails-applications/
https://ukgovernmentdfe.slack.com/archives/G01F7SE8TLY/p1689329822799979
This is only a workaround.. in reality we should rename the modules to be in the plural to be more "Rails" way and prevent issues when ruby is loading classes & constants. But there's a high risk of doing that.
`class ParticipantProfile::ECT < ParticipantProfile::ECF`
to
`class ParticipantProfiles::ECT < ParticipantProfiles::ECF`
`class …
> Add participant declaration & profile requires back to get around top-level constant lookup rule

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
Launch chaser comms. Add a new email that is sent to a schools GIAS contact that requests they verify their SIT details.
This will be sent to schools that have not yet responded to requests to setup 2023 and have a SIT in place.
> Add new email to the ask a school's GIAS contact to verify the SIT details

- app/forms/schools/cohorts/wizard_steps/what_changes_step.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- Ticket: CST-1740
The first radio button in the `what-changes` page should be `Form a new partnership`.
- Update the label
|![image](https://github.com/DFE-Digital/early-careers-framework/assets/951947/339839f2-de85-4424-9d32-e3e8071b3062)|![image](https://github.com/DFE-Digital/early-careers-framework/assets/951947/0e9e45c3-290b-4f52-8d4b-ec92d895021f)|
> [CST-1740] Fix content in the what-changes page

- app/controllers/admin/npq/applications/eligible_for_funding_controller.rb
- app/models/npq_application.rb
- app/models/participant_declaration.rb
- app/services/admin/npq_applications/eligibility_import/application_updater.rb
- app/views/admin/npq/applications/edge_cases/show.html.erb
- config/locales/en.yml
- spec/models/npq_application_spec.rb
- spec/requests/admin/npq/applications/edge_case_controller_spec.rb
- spec/requests/admin/npq/applications/eligible_for_funding_controller_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1224
To prevent financial mismatch, disable ability for admin to turn `eligible` application to `ineligible` when there are declarations that are payble against application.
> Add contidional validation to npq application eligibility status

- spec/requests/schools/partnerships_spec.rb
The spec `spec/requests/schools/partnerships_spec.rb:85` is currently failing due to us approaching the next cohort in the factories.
The test is checking that partnership cannot be challenged after it passes the challenge deadline.
- Ticket: n/a
To avoid failures when approaching the next cohort, set the challenge deadline to current academic year with extra days, and travel to after the deadline explicitly.
> Set explicit challenge deadline on partnership request spec

- .github/actions/deploy-environment-to-aks/action.yml
- .github/actions/prepare-app-env/action.yml
- .github/workflows/aks_deploy_review.yml
- terraform/aks/outputs.tf
This change adds automatic review app deployment to AKS. There is a generic action, `deploy-environment-to-aks` that will deploy any docker image to any environment, and a new workflow, `aks_deploy_review` that builds a docker image for the current PR and calls the action.
We will be able to deploy other environments using the same process.
> Add deploy env to AKS step

- app/views/nominations/choose_how_to_continue/new.html.erb
- app/views/schools/cohort_setup/expect_any_ects.html.erb
- config/locales/en.yml
- spec/features/nominations/nominate_induction_tutor_journey_spec.rb
- spec/features/nominations/nominate_induction_tutor_steps.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/forms/nominate_how_to_continue_form_spec.rb
See Jira ticket for context: https://dfedigital.atlassian.net/browse/CST-1738?atlOrigin=eyJpIjoiYWRhZmJjY2NlNTk1NDdjMjhkZDE3NDQ5MjEyOTc1ZWIiLCJwIjoiaiJ9
Can a developer confirm these content changes do not impact any tests please? I've removed a wizard that was pulling in the academic year.
This updates the content of the 2 screens asking schools if they expecting any early career teachers in the upcoming year. Previously we’ve had feedback from school users that they’re confused by the reference to ‘ECTs who started training before September 2023’ – they were conflating ITT with ECF-based training.
We’ve also:
* made the question and guidance on the 2 screens consistent
* dropped the question font size down from extra-large to large (following the [heading …
> Update content on pages asking if schools expect any ECTs or not

- app/forms/schools/cohorts/setup_wizard.rb
- app/forms/schools/cohorts/wizard_steps/expect_any_ects_step.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/forms/schools/cohorts/setup_wizard_spec.rb
- spec/forms/schools/cohorts/wizard_steps/expect_any_ects_step_spec.rb
- Ticket: CST-1732
School that don't have a partnership recorded for last year and trying to report their next year training programme are being told the relationship between their Lead Provider and Delivery Partner has changed. The journey should ask the schools to report what changes instead.
- Add missing specs
- Update the wizard to redirect SITs to the `what-changes` page when their school has no partnership recorded for last year
> [CST-1732] Ask schools to report their next year programme when there is no last year partnership

- config/environments/review.rb
Creating the review apps generates _lots_ of log messages when the call-off contracts and statements are seeded.
> Change the review env's log level to warn

- app/models/npq_application.rb
- spec/models/npq_application_spec.rb
For some applications, profile is empty resulting in `NoMethodError` exception.
> Fix undefined method bug when application profile is empty

- Gemfile
- Gemfile.lock
- app/models/additional_school_email.rb
- app/models/data_stage/school.rb
- app/models/network.rb
- app/models/participant_identity.rb
- app/models/school.rb
- app/models/user.rb
- spec/factories/additional_school_emails.rb
- spec/models/additional_school_email_spec.rb
- spec/models/data_stage/school_spec.rb
- spec/models/network_spec.rb
- spec/models/participant_identity_spec.rb
- spec/models/school_spec.rb
- spec/models/user_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-1727
- Adds auto_strip_attributes gem
- Adds squish on save to email/name columns on: 
- additional_school_emails
- data_stage_schools
- networks
- participant_identities
- schools
- users
> Autostrip whitespace on email/name columns

- spec/features_helper.rb
We are getting failures in the specs: https://github.com/DFE-Digital/early-careers-framework/actions/runs/5660570693/job/15336566031
Having a look at this issue https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1648154088
The recommendation is to pin the required version to a known version and and disable build check
- Pin Chromedriver version to 114
- Disable build check in Selenium 
Hopefully this solves the issue
> Set required chromedriver version to 114 and disable build check

- .github/workflows/aks_destroy_review.yml
Destroy review apps when the PR is closed/merged.
This PR was closed and opened to demonstrate, [this screengrab](https://github.com/DFE-Digital/early-careers-framework/assets/128088/76237c07-32c0-4e44-9f87-1146eb520b6f) shows the before and after states.
> Destroy review apps in AKS after their branch has been merged

- lib/devise/strategies/passwordless_authenticatable.rb
- spec/requests/users/sessions_spec.rb
- Ticket: CST-1779, CST-1790
We want to increase the expiration time of the login magic links to 24 hours and update the sign in email to display both the date and the time the link expires.
- Update the token expiry in the `Devise::Strategies::PasswordlessAuthenticatable` to 24h
- Update the format of the `token_expiry` that is passed to the sign in mailer
1. Trigger the sign in email
2. Confirm the email says `This link will expire at 28 July 2023, 12:04 PM.`
> Increase the login magic links lifetime to 24 hours

- app/helpers/schools/dashboard_helper.rb
- app/views/schools/participants/index.html.erb
- spec/features/schools/participant_dashboard/manage_fip_partnered_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- Ticket: CST-1801
We want to display a banner to the `Manage mentors and ECTs` screen to reassure SITs in schools with participants that they do not need to withdraw, transfer or request deletion for their completed participants.
- Use the Notification banner component to display the banner
- Add helper method to count all the school's active participants
Schools with participants:
1. Visit the `Manage your training` page of a school
2. Click to `Manage mentors and ECTs` button
3. The banner should be displayed at the top of the page
Schools with no participants:
1. Visit the `Manage your training` page of a school
2. Click to `Manage mentors and ECTs` button
3. The banner should not be displayed
| …
> Add notification banner for SITs about their completed participants

- app/controllers/concerns/journey_wizard/controller.rb
Error spotted by admin user and in Sentry.  As a protection against jumping around in the wizards we perform some checks at initialisation and raise errors if we spot something wrong. These are rescued in the controller and the wizard data is reset and the journey starts over. However a refactor that renamed the module missed the exception class names rescued so that when an initialisation error happens we're not catching the correct error (in fact it generates a different error trying to rescue a class that doesn't exist).
Fix the module name in the rescue clause
> [Bug-fix] Fix missed module name change

- app/forms/choose_role_form.rb
- app/models/user.rb
- spec/forms/choose_role_form_spec.rb
- spec/models/user_spec.rb
- spec/requests/users/sessions_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1206)
School users (SITs) can be confused by the options presented to them if they have more than 1 type of profile e.g. SIT/mentor or SIT who's also doing a NPQ
This PR tries to ensure school users ie. SITs, are never presented with these options in general.
Treat "school" roles more logically:
- A SIT with a mentor profile will be treated as a single role SIT
- A SIT with a `TeacherProfile` will be treated as a single role SIT
> [CST-1206] Treat school based roles as one role to avoid seeing options at sign in

- app/helpers/phase_banner_helper.rb
- app/views/layouts/_phase_banner.erb
- spec/helpers/phase_banner_helper_spec.rb
Now they will have a colour per environment and tests cover the env-specific text
| Environment | Preview |
| ------------ | ------- |
| Development | ![Screenshot from 2023-07-28 11-05-39](https://github.com/DFE-Digital/early-careers-framework/assets/128088/51a95c42-5689-4146-98c8-2108899ab967) |
| Review | ![image](https://github.com/DFE-Digital/early-careers-framework/assets/128088/6265f7ce-7077-4b28-93f5-cf7b59dedfcc) |
| Staging | ![Screenshot from 2023-07-28 11-05-16](https://github.com/DFE-Digital/early-careers-framework/assets/128088/52fe797f-099b-473a-bace-ac789bb83d33) |
| Sandbox 🏖️ | ![Screenshot from 2023-07-28 11-04-52](https://github.com/DFE-Digital/early-careers-framework/assets/128088/26b71682-c752-4b86-97a3-6faf4a8ad95b) |
| Production | ![Screenshot from 2023-07-28 …
> Improve the environment specific phase banners

- .github/workflows/aks_deploy.yml
The pipeline isn't currently running the docker build step on `main`. We always want it to run **unless the branch was created by dependabot**. Now the if statement checks the `github.actor`.
The if statement logic was lifted and amended from [this documentation page](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#common-dependabot-automations).
> Always build the branch unless it's dependabot

- .github/workflows/aks_deploy.yml
We need to iron out the AZURE_CREDENTIALS and currently it's blocking any deploys.
> Allow deploy-staging to fail for the moment

- app/forms/admin/school_transfer_form.rb
- spec/forms/admin/school_transfer_form_spec.rb
- Ticket: CST-1780
The transfer in admin console is creating a default partnership when a school hasn't got a cohort set up, when the expected behaviour is to prevent the transfer.
- Update the condition in the `Admin::SchoolTransferForm#no_programmes_to_transfer_into_or_continue?` to only check if the new school has a cohort with a programme the participant can transfer into
1. Start transferring a participant in the admin console from school A to school B, where school B doesn’t have a training programme set up for the participant’s cohort
2. You should be redirected to the "cannot transfer" page
> [CST-1780] Fix admin transferring participants to schools without programmes

- app/services/induction/change_partnership.rb
- spec/services/induction/change_partnership_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1802)
When a new partnership is reported, we want to move any participants in FIP programmes with relationships that have been challenged to the new default programme.
> [CST-1802] Move un-partnered participants to new partnership programme when reported

- terraform/aks/databases.tf
We matched the prod schema, but didn't add the new extensions to Azure
- Ticket: n/a
Add `fuzzystrmatch` and `uuid-ossp` to Azure extensions
> Add missing database extensions to Azure

- .github/actions/deploy-environment-to-aks/action.yml
- .github/workflows/aks_destroy_review.yml
- Gemfile
- Makefile
- app/controllers/users/sessions_controller.rb
- app/middlewares/time_traveler.rb
- config/environments/staging.rb
- config/seed_quantities.yml
- db/new_seeds/base/add_api_tokens.rb
- db/new_seeds/base/add_environment_specific_data.rb
- db/new_seeds/base/add_feature_flags.rb
- db/seeds.rb
- global_config/staging_aks.sh
- lib/tasks/safe_reset.rake
- terraform/aks/terraform.tf
- terraform/aks/workspace_variables/README.md
- terraform/aks/workspace_variables/staging_aks.tfvars.json
- terraform/aks/workspace_variables/staging_aks_backend.tfvars
Staging is an environment we'll deploy to before production/sandbox. It will be used to ensure existing databases can be migrated before attempting in prod/sandbox.
- Add configuration for staging env in AKS
- Add README with breakdown of naming conventions
> Add config for staging env in AKS

- .github/workflows/aks_deploy.yml
Now staging deploys are working properly we no longer need this. Add it back later if necessary.
> Remove continue-on-error from staging deploy step

- app/forms/admin/school_transfer_form.rb
- config/locales/en.yml
- spec/forms/admin/school_transfer_form_spec.rb
- Ticket: CST-1856
The validation is retrieving the participant's current school and checks if it's not the same with the one moving into. Problem is that it's not retrieving the participant's school from their induction record.
- Update the validation to use the participant's latest induction record to retrieve their current school
> Fix validation in the admin school transfer form

- app/services/admin/delivery_partners/exporter.rb
- lib/tasks/delivery_partners.rake
- spec/services/admin/delivery_partners/exporter_spec.rb
[Jira-2334](https://dfedigital.atlassian.net/browse/CPDLP-2334)
We want to be able to export delivery partners easily and periodically; adding a service to perform this action and a rake task so that it can be ran in production. We may want to expose the functionality via the admin interface in the future.
- Add service/rake task to export delivery partners
Output to a CSV file:
```
bundle exec rake 'delivery_partners:export[./out.csv]'
```
Output to the console:
```
bundle exec rake delivery_partners:export
```
> Add service/rake task to export delivery partners

- app/services/finance/ecf/assurance_report/query.rb
- spec/services/finance/ecf/assurance_report/query_spec.rb
[Jira-2169](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2169)
The assurance report query currently takes the delivery partner from the latest induction record. This may not be correct in all scenarios and is inconsistent with how we select the delivery partner in other areas of the application.
Instead, we want to use the delivery partner associated with the declaration and only fallback to the latest induction record if it is not set (which it may not be on some historical records).
- Export correct delivery partner in assurance report
Also has a general tidy-up to the query specs.
> Export correct delivery partner in assurance report

- app/views/privacy_policies/show.html.erb
The privacy policy is displaying with HTML tags, the output needs to be sanitized. I introduced this on Friday while fixing the Brakeman warnings 🤦
> Sanitize the privacy policy

- db/data/schedules/schedules.csv
- spec/models/finance/schedule/ecf_spec.rb
- Ticket: [CPDLP-2325](https://dfedigital.atlassian.net/browse/CPDLP-2325)
Add new milestone seed data for ECF extended schedules.
go to review app url /finance/schedules to check whether the new milestones have been added to the ecf-extended schedules.
[CPDLP-2325]: https://dfedigital.atlassian.net/browse/CPDLP-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2325] Add seed data for ECF extended schedules

- app/components/admin/schools/cohorts/cip_info.html.erb
- app/components/admin/schools/cohorts/cip_info.rb
- app/components/admin/schools/cohorts/cohort.html.erb
- app/components/admin/schools/cohorts/cohort.rb
- app/components/admin/schools/cohorts/fip_info.html.erb
- app/components/admin/schools/cohorts/fip_info.rb
- app/components/admin/schools/cohorts/other_info.html.erb
- app/components/admin/schools/cohorts/other_info.rb
- app/controllers/admin/schools/cohorts/challenge_partnership_controller.rb
- app/controllers/admin/schools/cohorts_controller.rb
- app/models/partnership.rb
- app/policies/partnership_policy.rb
- app/views/admin/schools/cohorts/index.html.erb
- spec/components/admin/schools/cohorts/cohort_spec.rb
- spec/components/admin/schools/cohorts/fip_info_spec.rb
- spec/components/admin/schools/cohorts/other_info_spec.rb
- spec/factories/admin_profiles.rb
- spec/factories/users.rb
- spec/features/admin/schools/changing_provision_spec.rb
- spec/requests/admin/schools/cohorts/challenge_partnership_spec.rb
This is an attempt to make the school cohorts tab easier to understand. The default partnership is now displayed more prominently and the other relationships are clearly labelled and the participant information is listed.
- Order the cohorts latest first
- Switch ordering of lead provider/delivery partner
- Reorganise the admin school cohorts page
Current on the left, proposed on the right:
The 'Challenge' buttons are now only visible when the logged in user is a super user.
> Admin cohort redesign

- docs/source/ecf/guidance.html.md
Replaced: 
Providers can view the names and email addresses of ‘unfunded mentors’ assigned to ECTs, and give these mentors appropriate access to learning platforms.
With:
A participant will have the same participant_id throughout the API. 
If a participant is a mentor and linked to an ECT, then the mentor_id that appears on the response for their ECT will be the mentor’s participant_id. 
If the mentor is an unfunded mentor, then the identifier will be their participant_id.
And...
Added: 
Using the unfunded mentors endpoints, 
At the start of the following par: 
Providers can view the names and email addresses of ‘unfunded mentors’ assigned to ECTs, and give these mentors appropriate access to learning platforms.
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2324
> Update unfunded mentor information

- .github/workflows/aks_deploy.yml
This will keep the builds green while we finalise how our production env looks.
> Make prod deploy continue-on-error

- app/models/induction_record.rb
- app/services/determine_training_record_state.rb
- app/services/induction/complete.rb
- db/new_seeds/scenarios/participants/ects/ect.rb
- spec/services/induction/complete_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1851)
Set the `induction_completion_date` and add a new induction record with the `completed` induction status.
Adds a service to mark a participant as completed and set the completion date.
The actual induction completion date will be retrieved in a subsequent PR
> [CST-1851] Set induction completion date and induction status

- Makefile
- global_config/development_aks.sh
- terraform/aks/workspace_variables/development_aks.tfvars.json
- terraform/aks/workspace_variables/development_aks_backend.tfvars
We aren't using development any more because we want a 1:1 mapping between AKS environments and Rails environments. We use development for local dev, so having a `deployed_development` is a unnecessary complication. Staging is the new development.
> Remove the development env from AKS

- .github/workflows/aks_deploy.yml
We should no longer need it now that production is fully configured.
> Remove continue-on-error from prod deploy on AKS

- Makefile
Setting `SKIP_CONFIRM` in the ci step means we can bypass the check without setting `CONFIRM_PRODUCTION=1` for non-production environments
Fixes #3826, #3827
> Add `SKIP_CONFIRM` variable to help automate deployments

- .github/workflows/aks_deploy.yml
Add [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) so that we can automatically cancel runs when one part fails.
We've tested this by force pushing and it appears to work, the first run was correctly cancelled.
> Add concurrency group and enable cancel-in-progress

- app/components/admin/schools/cohorts/cohort.html.erb
The ability to challenge partnerships was incorrectly hidden behind the superuser check, which should only have been added to challenging relationships in #3261
> Reenable partnership challenging in admin console

- terraform/aks/databases.tf
This is failiing as `postgres_enable_high_availability` doesn't exist in the terraform module
- Ticket: n/a
Change to `azure_enable_high_availability`
> Use `azure_enable_high_availability` instead of `postgres_enable_high_availability`

- docs/source/release-notes.html.md
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFParticipantDeclarationAttributes.yml
- swagger/v3/component_schemas/ECFParticipantDeclarationExtendedAttributesRequest copy.yml
- swagger/v3/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v3/component_schemas/ParticipantDeclarationDataRequest.yml
- Ticket: [CPDLP-2327](https://dfedigital.atlassian.net/browse/CPDLP-2327)
Following changes from https://github.com/DFE-Digital/early-careers-framework/pull/3780, we need to add the new extended declarations types to API spec and a release note for sandbox.
Add extended declarations to API spec with release note for sandbox
[CPDLP-2327]: https://dfedigital.atlassian.net/browse/CPDLP-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://ecf-review-pr-3809.london.cloudapps.digital/api-reference
> [CPDLP-2327] Add extended declarations to API spec with release note for sandbox

- db/migrate/20230816132809_update_ecf_duplicates_to_version_5.rb
- db/schema.rb
- db/views/ecf_duplicates_v05.sql
[Jira-1728](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1728)
Previously we were selecting the school via the `partnership` relationship, however we should go through `induction_programme.school_cohort` instead.
- Update duplicates view to select correct school
The db schema got a bunch of unnecessary changes when I ran the migration; I've manually cleaned them up so only the applicable changes are in this PR but worth paying close attention to that file.
> Update duplicates view to select correct school

- swagger/v3/api_spec.json
The doc description for transfer ID is incorrect, and doesn't match component schema
- Ticket: n/a
Fix content for ID in transfers in API spec
> Match id description to component schema for transfer ID

- app/components/finance/npq/participant_outcomes/table.html.erb
- app/components/finance/npq/participant_outcomes/table.rb
- app/models/participant_outcome/npq.rb
- config/locales/en.yml
- spec/components/finance/npq/participant_outcomes/table_spec.rb
- spec/features/finance/npq/participant_outcomes_spec.rb
- spec/models/participant_outcome/npq_spec.rb
- Ticket: [CPDLP-2317](https://dfedigital.atlassian.net/browse/CPDLP-2317)
Update NPQ outcomes table in the finance application view to show details of an successful/unsuccessful request to the TRA.
[CPDLP-2317]: https://dfedigital.atlassian.net/browse/CPDLP-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2317] Update NPQ outcomes table in the finance application to show details of an successful/unsuccessful request to the TRA

- app/components/admin/schools/cohorts/cohort.rb
Fix a bug where partnerships aren't properly found, causing the challenge bug to be hidden.
No tests here, going to rewrite this whole set of components instead.
> Fix a bug when finding partnerships

- db/new_seeds/scenarios/cohorts/cohort.rb
This is breaking in review apps when generating seeds, and is not required
- Ticket: n/a
Remove redundant require
> Remove mocks from seeds as not required

- .github/workflows/aks_deploy.yml
Sometimes changes to things like seed files/factories can cause apps not to deploy properly. Deploying to review apps helps mitigate this risk.
> Always build review apps unless dependabot

- app/services/change_schedule_on_duplicate.rb
- lib/participant_profile_deduplicator.rb
- spec/lib/participant_profile_deduplicator_spec.rb
[Jira-1728](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-1728)
The deduplication tool is currently unable to reconcile profiles that have different schedules. We now have a set of rules to follow when merging these records:
- Work out which schedule to retain (the earliest non-voidable declaration will belong to this schedule)
- Void all declarations on the profile not associated with the schedule we are retaining
- If the primary profile has the relevant schedule we can carry on as normal
- If the duplicate profile has the relevant schedule we need to update the primary profile to use this schedule/cohort (without creating a new induction record)
- Handle schedule changes for duplicate records
I haven't added explicit tests for the …
> Handle schedule changes for duplicate profiles

- app/views/finance/ecf/duplicates/compare/_details.html.erb
Previously the headings were inferred from the profile records, however to work with the 'swap' button on the deduplication tool we need to hard-code the headings.
We can revert this change when we're done with the deduplication tool. This change was in production but appears to have been accidentally reverted in a merge:
https://github.com/DFE-Digital/early-careers-framework/pull/3835/commits/838bbe1ec04eb5a54301e2591085433e5fc91d02#diff-1630548633cfb9cc618d3eef61aa3be488aaea3c24da5e75cdb169f98f8585caL6-L7
> Hard-code primary/duplicate headings

- .github/workflows/backup-paas-database.yml
- .github/workflows/backup-paas-schedule.yml
~~**Note, this follows on from #3842, rebase once that's merged. We just care about teh final commit ([fa26a72](https://github.com/DFE-Digital/early-careers-framework/pull/3864/commits/fa26a728402745630f08f4123bc7d5714ee507aa)) here**~~
This new workflow schedules the copying of data from PaaS to Azure every night at 04:30. The jobs are run simultaneously and should take approximately half an hour to finish.
> Schedule backups from PaaS to Azure

- app/controllers/finance/ecf/duplicates/compare_controller.rb
- app/views/finance/ecf/duplicates/compare/_deduplicate.html.erb
The dedupe path was configured to be the opposite of the compare path, which meant the ids were getting swapped in the URL on the dry-run/dedupe. Whilst functionally this is fine and was working it makes it confusing as I often copy/paste paths when I'm working through the duplicates and it meant I was manually swapping them by accident.
Update dedupe paths to use the same duplicate/primary profile ID ordering as the compare path.
> Prevent primary/duplicate ids swapping in path on dedupe

- config/sidekiq_cron_schedule.yml
Remove the `SetParticipantStartDateJob` from the schedule as it has now updated all that it can in the given criteria.  Not removing the actual job now as that may be still required (perhaps with a tweak to the query) in the near future.
Remove the cron job from the schedule
> Remove induction start date job from the cron schedule

- app/services/importers/create_new_npq_course.rb
- app/services/importers/create_npq_contract.rb
- app/services/importers/create_npq_course.rb
- spec/services/importers/create_new_npq_course_spec.rb
- spec/services/importers/create_npq_contract_spec.rb
- spec/services/importers/create_npq_course_spec.rb
Add new service classes in importers for create new course
https://dfedigital.atlassian.net/browse/CPDNPQ-1257
Introduced new service classes in importers for create new courses through csv and update `create_npq_contract` service for update or create new contract with specified version. The version is **Finance::Statement** latest version.
Looked into create `new_npq_course`, `create_npq_course` as they are inspire from old code and reviewed the private method named `get_latest_version` in **app/services/importers/create_npq_contract.rb** because this method use to get latest version.
> Add new service classes in importers for create new course

- app/controllers/schools/participants_controller.rb
- app/views/schools/participants/show.html.erb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
This helps with transferred participants that are associated to an Appropriate  Body and want to keep it.
- Ticket: CST-1803
Remove the school cohort AB check from the `can_appropriate_body_be_changed?` helper method
- Find a school with participants in a cohort without an Appropriate Body
- Visit the page of one of those participants
- The Appropriate Body row should be displayed
> Display the AB in participant's profile even when schools don't have any

- .github/workflows/aks_destroy_review.yml
We loosened the criteria for review apps to be generated from having to have the 'review-app' label to simply not being generated by Dependabot to prevent problems where the app won't boot.
This change sets the same critera in the destory action.
Refs #3857
> Make destroy review app action run for all PRs

- lib/participant_profile_deduplicator.rb
- spec/lib/participant_profile_deduplicator_spec.rb
We can now handle duplicates with a different lead provider but the same school - providing there are no declarations on the duplicate - by destroying the duplicate profile _without_ reconciling it with the primary.
After working through a change in training programme with Nathan on a call we've decided we can probably handle these but they need a warning to ensure we double check the ordering and scrutinise them more closely.
- Update deduplicator to handle additional scenarios
> Update deduplicator to handle additional scenarios

- .github/workflows/deploy_to_dev.yml
We need to push the image as latest to docker so we can still deploy to PaaS
- Ticket: n/a
Add all steps back except deploying to old dev Paas
> Reinstate image building/pushing to allow deployment to paas

- app/components/admin/schools/cohort_component.html.erb
- app/components/admin/schools/cohort_component.rb
- app/components/admin/schools/partnership_component.html.erb
- app/components/admin/schools/partnership_component.rb
- spec/components/admin/schools/cohort_component_spec.rb
- spec/components/admin/schools/partnership_component_spec.rb
In my previous attempt to rewrite these components (#3846) I misunderstood the role of partnerships/relationships in CIP/FIP. Only FIP schools have partnerships and relationships; CIP schools instead have materials provided by their core induction programme.
As a result I've had to move some of the functionality previosuly in `Schools::PartnershipComponent` into `Schools::CohortComponent`.
Hopefully this makes more sense 😅
> Adjust the cohort component behaviour

- .github/workflows/backup-paas-schedule.yml
We don't need it any more, staging on PaaS is gone.
> Remove the staging sync step from backup flow

- spec/components/admin/schools/cohort_component_spec.rb
We are getting failures on the following spec: https://github.com/DFE-Digital/early-careers-framework/actions/runs/6027756337/job/16374067146
When testing cohort component, logic for showing empty changed to school cohorts rather than partnerships: https://github.com/DFE-Digital/early-careers-framework/pull/3908/files#diff-988e63f8e759873f86e923baaf3f38be6c211e14a75dc1067f84cf82cbffd0daR43
- Ticket: n/a
Amend spec to unset school cohort rather than partnership to match new logic
> Amend spec to nullify school cohort as opposed to partnerships

- spec/components/admin/schools/cohort_component_spec.rb
We are now checking there are no school cohorts rather than partnerships, amend spec expectation to reflect that
- Ticket: n/a
Thanks for flagging @ethax-ross !
> Amend empty spec expectation content

- spec/cypress/app_commands/scenarios/admin/schools.rb
- spec/factories/cohorts.rb
- spec/factories/seeds/cohort_factory.rb
- spec/features/schools/training_dashboard/manage_fip_training_spec.rb
- spec/models/cohort_spec.rb
- spec/requests/schools/dashboard_spec.rb
- spec/serializers/finance/ecf/duplicate_serializer_spec.rb
- spec/services/induction/amend_participant_cohort_spec.rb
- spec/services/partnerships/report_spec.rb
- spec/services/record_declaration_spec.rb
- spec/spec_helper.rb
After the cohort rolled over in academic start date 1/9, many specs failed, which means main and deployment is blocked. To fix those we need time. For now to unblock deployment temporarily push the problem to one month from now, to allow fixing the failures properly once and for all.
- Ticket: n/a
- Set academic cohort to 1/10 in factories and setup
- Set specific specs to 1/9 to match very specific dates in partnership specs
- Set all other specs to 1/10 for now temp until this is fixed properly
> Set cohort change to one month until properly fixed

- app/components/banners/maintenance_component.rb
Set banner for production azure migration. Which will happen on the 14th of September between 6pm - 9pm
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2424
Add banner times for prod only. Sandbox will have a release note and comms sent out
I went with 3 hours to be cautious just incase, let me know your thoughts
> Set time for azure migration in production

- docs/source/ecf/guidance.html.md
* added a table in the 'View data for all participants who have transferred' section to show what happens and when in the API
* added bullet point to make clear that 'id' refers to a participant's unique ID
* added line highlighting that it's possible for the new school's induction tutor to report a joiner before the old school's induction has reported that the participant has left them
- Ticket:
> Update transfers info

- app/components/admin/schools/cohort_component.html.erb
- app/components/admin/schools/relationship_component.rb
- spec/components/admin/schools/cohort_component_spec.rb
- spec/components/admin/schools/relationship_component_spec.rb
The choose induction programme button was lost when rewriting the cohort component. The loss wasn't noticed as there were no tests. Now it's back and there are tests ensuring it remains.
> Reinstate the choose induction programme button

- app/jobs/set_participant_completion_date_job.rb
- app/services/induction/complete.rb
- config/sidekiq_cron_schedule.yml
- spec/services/induction/complete_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1828)
Pull in the induction completion dates for pre-2023 ECTs as a one time job.  The job is scheduled to run every 2 minutes from midnight to 9am and pull in 200 participants at a time so that we don't have/cause issues with the DQT API 300 requests per minute limit.
Add a job to read the induction records from DQT and use the `Induction::Complete` service to update the participants records.
> [CST-1828] Add job and schedule to pull in completion dates from DQT

- app/forms/schools/add_participants/wizard_steps/participant_type_step.rb
- app/views/schools/add_participants/participant_type.html.erb
- config/locales/en.yml
See Jira ticket https://dfedigital.atlassian.net/browse/CST-1636?atlOrigin=eyJpIjoiZGY1YTUwYWU5MDBhNDQzZDljYWVjZmU1NDI3OGRlOWQiLCJwIjoiaiJ9 for more information
I've updated the error message content for participant_type. This error should be applied to the /participants/who/participant-type screen as part of this PR.
> Fix error message on participant type form

- config/initializers/sidekiq.rb
Noticed on production that we had old cron jobs still in the list of jobs with sidekiq `Sidekiq::Cron::Job.all` even though these had been removed from the schedule.
After a bit of research it appears that the docs tell you to use `Sidekiq::Cron::Job.load_from_hash` in the initializer but this doesn't remove jobs from the list only adds new ones. Using `.load_from_hash!` instead should do what we want.
Switch the initializer to load the schedule using `.load_from_hash!`
> Fix to ensure old cron jobs are purged from schedule

- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production_aks.tfvars.json
We can't make use of the current cache Redis in AKS in production as it's for Sidekiq and not caching purposes
- Ticket: n/a
Bump our Redis instance to standard in other ENVs and premium in prod. I named it queue to allow us to add caching later as we need a separate instance as well similar to Apply
DId I miss anything?
> Update our Redis instance to standard/premium in AKS

- app/models/finance/statement.rb
- db/migrate/20230905155638_add_marked_as_paid_at_to_statements.rb
- db/schema.rb
- Ticket: [CPDLP-2414](https://dfedigital.atlassian.net/browse/CPDLP-2414)
We will be adding the ability to track when a statement was marked as paid in the new finance dashboard workflow.
- Add a new field which captures the timestamp when a statement has been marked as paid
- Add papertrail to the statement model to ensure we also have further auditing
[CPDLP-2414]: https://dfedigital.atlassian.net/browse/CPDLP-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2414] Add a new field to statements table to capture marked as paid timestamp

- app/controllers/admin/participants/change_log_controller.rb
- spec/requests/admin/participants/change_log_spec.rb
https://dfe-teacher-services.sentry.io/issues/4414607011/?alert_rule_id=7310304&alert_type=issue&project=5748989&referrer=slack
The change log tabs in the admin console fail to load because the header now requires the ParticipantPresenter to correctly find the cohort start_year to display.
- Add ParticipantPresenter to the view model of the change log controller
> Add participant presenter to change_log_controller

- app/mailers/user_mailer.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- spec/mailers/user_mailer_spec.rb
- Ticket: CST-1924
Unregistered users try to sign into the service and they get confused. We want to send them an email about what they should do to gain access.
- Add a new user mailer
- Update the passwordless strategy to send the email when the user is not found
- Try to sign-in with a random email address
- Verify that the email is sent by checking on `Notify -> API integration`
- Confirm the email body is correct (mainly the URLs passed to the Notify template)
> [CST-1924] Send access info when unregistered users are trying to login

- lib/devise/strategies/passwordless_authenticatable.rb
The `UserMailer#access_info_email` is causing some issues on prod and we need to temp stop it.
> Pause the access_info_email

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
We want to include the school details in the Notify template for future comms.
- Ticket: 
Pass a `School` as a param to the mailer
Provide a `school_name` param to the template
> Update mailer to take a school param

- .github/actions/backup-paas-database/action.yml
Previously we'd used our backup database to test with so we didn't add unnecessary load to the real production database while testing. We're getting closer to the actual migration date now so it makes sense to ensure it _actually works_ 😄
> Make prod restore target the actual prod database

- app/models/participant_band.rb
- app/services/importers/create_call_off_contract.rb
- db/migrate/20230911115906_rename_participant_bands_output_payment_percantage.rb
- db/schema.rb
- spec/services/importers/create_call_off_contract_spec.rb
- Ticket: [CPDLP-2398](https://dfedigital.atlassian.net/browse/CPDLP-2398)
Rename `participant_bands` `output_payment_percantage` column to `output_payment_percentage`.
[CPDLP-2398]: https://dfedigital.atlassian.net/browse/CPDLP-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2398] Rename participant_bands output_payment_percantage

- app/mailers/user_mailer.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- Ticket: CST-1924
This PR fixes the issue introduced in the #3939 and re-enables the email.
The issue:
Calling the `. associate_with (recipient) ` in the mailer with a String param raised an exception after Notify sent the email, which failed and re-queued the job. That created a loop that was sending the emails multiple times to the unregistered users who were trying to login.
- There's no real need to associate the email with the recipient's email, so I'm removing the`.associate_with(recipient)` call
- Re-enabling the mailer
- Try to sign-in with a random email address
- Verify on `Notify -> API integration` page that the email was sent only once
- Check the mailer job in not re-queued on sidekiq
> [CST-1924] Fix the unregistered users mailer

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
Update the reminder to add mentors to ECTs mailer to include the school name.
Add school as a parameter to the mailer
Add school_name as an additional personalisation to the template
> Update mailer to take a school param and supply a school_name to template

- app/views/schools/add_participants/what_we_need.html.erb
- spec/features/schools/participants/add_participants/add_ect_as_mentor_spec.rb
- spec/features/schools/participants/add_participants/add_ect_with_appropriate_body_spec.rb
- spec/features/schools/participants/add_participants/unhappy_path_already_on_ecf_training_spec.rb
- spec/features/schools/participants/add_participants/unhappy_path_email_taken_spec.rb
- spec/features/schools/participants/add_participants/unhappy_path_sit_error_entering_validation_info_spec.rb
- spec/features/schools/participants/transferring_participants/already_enrolled_at_school_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
🗂️ [Jira card](https://dfedigital.atlassian.net/browse/CST-1966)
We had some people contact support because they'd accidentally added an ECT as a mentor or vice versa.
We think this is partly because the page after selector "ECT" or "Mentor" is generic to both.  By updating this page to be more specific (in the page title and the note about privacy), we hope to make it more obvious to users when they’ve mis-clicked, so that they can quickly go back and select the right option.
| ECTs | Mentors |
|------|---------|
| <img width="1044" alt="Screenshot 2023-09-11 at 17 59 35" src="https://github.com/DFE-Digital/early-careers-framework/assets/30665/91cfbf54-b559-40e3-b381-cadf34584b41"> | <img width="1004" alt="Screenshot 2023-09-11 at 17 59 51" …
> Make it clearer you're adding ECT or mentor

- app/controllers/users/sessions_controller.rb
- app/forms/nomination_request_form.rb
- app/views/nominations/request_nomination_invite/resend_email.html.erb
- app/views/nominations/request_nomination_invite/review.html.erb
- app/views/nominations/request_nomination_invite/success.html.erb
- app/views/users/sessions/login_email_sent.html.erb
- config/locales/en.yml
- spec/features/request_access_spec.rb
- spec/features/sign_in_spec.rb
- spec/features/start_page_spec.rb
- spec/forms/nomination_request_form_spec.rb
- spec/requests/nominations/request_nomination_invite_spec.rb
- Ticket: CST-1923
* Display the email address we’ve sent the magic link to on sign-in
* Show a redacted email address on the GIAS renominate route
* Confirmation page in the GIAS renomination route
> [CST-1923] Iterations to the SIT sign-in journey

- terraform/aks/application.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production_aks.tfvars.json
- terraform/aks/workspace_variables/sandbox_aks.tfvars.json
- terraform/aks/workspace_variables/staging_aks.tfvars.json
We are getting errors in sandbox when attempting to send emails:
```
`full_url_for': Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true (ArgumentError)
```
We set the domain in environment config, this is required for sending emails.
- Ticket: n/a
- Add send email to ENV to allow redirect in non prod/test envs (needs amending for the vcap attribute later)
- Add domain variable and set in application to allow emails to be sent
There is a bit of cleanup still required after the migration
> Add back missing variables, these are required for sending emails

- .github/actions/deploy-environment-to-aks/action.yml
- .github/workflows/aks_deploy.yml
- Makefile
- terraform/aks/monitoring.tf
- terraform/aks/providers.tf
- terraform/aks/terraform.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production_aks.tfvars.json
- terraform/aks/workspace_variables/sandbox_aks.tfvars.json
- terraform/aks/workspace_variables/staging_aks.tfvars.json
Terraform statuscake module: https://github.com/DFE-Digital/terraform-modules/tree/main/monitoring/statuscake
- Ticket: n/a
We have statuscake monitoring in PaaS, add it to Azure since we are migrating soon
- Add external hostname variable and set in all envs 
- Amend monitoring to true in production as this is used in both db setup and statuscake
- Add monitoring and set our contact group
- Add statuscake to providers and set token in action
> Add statuscake monitoring to AKS

- .github/workflows/aks_destroy_review.yml
Review app deletion is failing. Add statuscake token as its now required
- Ticket: n/a
Add statuscake token read from Github secrets to delete review app
We need to fix this generally where not every terraform init/plan/apply/destroy needs the token, cleanup will be a bit later
> Add statuscake token to review app destroy

- config/initializers/dfe_analytics.rb
The key name in the config was BIGQUERY_DFE_ANALYTICS_JSON_API_KEY instead of BIGQUERY_DFE_ANALYTICS_API_JSON_KEY.
> Fix typo in big query API key name

- app/assets/stylesheets/lead_providers/statements.scss
- app/components/finance/statements/ecf_details_table.html.erb
- app/components/finance/statements/ecf_details_table.rb
- app/components/finance/statements/npq_details_table.html.erb
- app/components/finance/statements/npq_details_table.rb
- app/controllers/finance/ecf/statements_controller.rb
- app/controllers/finance/npq/statements_controller.rb
- app/controllers/finance/payment_authorisations_controller.rb
- app/forms/finance/create_payment_authorisation_form.rb
- app/helpers/finance_helper.rb
- app/models/finance/statement.rb
- app/views/errors/_calculation_rounding.html.erb
- app/views/finance/ecf/statements/show.html.erb
- app/views/finance/npq/statements/show.html.erb
- app/views/finance/payment_authorisations/new.html.erb
- app/views/finance/statements/_calculation_rounding_message.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/components/finance/statements/ecf_details_table_spec.rb
- spec/components/finance/statements/npq_details_table_spec.rb
- spec/factories/finance/statements.rb
- spec/features/finance/ecf/statement_spec.rb
- spec/features/finance/npq/statement_spec.rb
- spec/forms/finance/create_payment_authorisation_form_spec.rb
- spec/helpers/finance_helper_spec.rb
- spec/models/finance/statement_spec.rb
- spec/requests/integration/participant_outcomes/creation_spec.rb
- spec/support/perform_jobs.rb
- Ticket: [CPDLP-2295](https://dfedigital.atlassian.net/browse/CPDLP-2295)
Add authorise for payment button to ECF/NPQ on financial statements.
[CPDLP-2295]: https://dfedigital.atlassian.net/browse/CPDLP-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2295] Add authorise for payment button to ECF/NPQ on financial statements

- app/components/banners/maintenance_component.html.erb
- app/views/admin/notes/edit.html.erb
- app/views/admin/npq/applications/notes/edit.html.erb
- app/views/lead_providers/report_schools/confirm/show.html.erb
- app/views/privacy_policies/show.html.erb
- app/views/users/sessions/redirect_from_magic_link.html.erb
- spec/cypress/support/commands.js
- spec/cypress/support/step_definitions/common-interaction.js
- spec/cypress/support/step_definitions/database.js
The `govuk_submit` form helper ensures the relevant `data-module` attributes are set and double-click prevention is enabled too.
> Switch `f.submit` over to `f.govuk_submit` for consistent HTML

- app/controllers/lead_providers/report_schools/csv_controller.rb
- app/services/create_partnership_csv_upload.rb
- spec/services/create_partnership_csv_upload_spec.rb
An error was raised when attempting to read the csv: https://dfe-teacher-services.sentry.io/issues/4486648382/?alert_rule_id=7310304&alert_type=issue&notification_uuid=bbd2755c-cddc-421d-b5ed-a709d584f020&project=5748989&referrer=slack
- Ticket: n.a
- Add service which persists partnership upload csvs
- Reinstate cleanup logic for badly formatted csvs
> Cleanup CSV uploads before persisting uploaded urns

- app/services/record_declaration.rb
- spec/services/record_declaration_spec.rb
[Jira-2259](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2259)
We currently stamp created declarations with the delivery partner of the latest induction record. This isn't always accurate; instead, we should be using the induction record that was the latest at the time of the `declaration_date`.
- On creating declaration select correct delivery partner
> On creating declaration select correct delivery partner

- config/analytics.yml
- config/analytics_blocklist.yml
- db/migrate/20230919093921_add_primary_key_to_cohorts_lead_providers.rb
- db/schema.rb
We have a `has_and_belongs_to_many` table `cohorts_lead_providers`. By default Rails doesn't add a primary key `id` column to this table (as it as a composite of the foreign keys). The `dfe-analytics` gem, however, requires an `id` column that is a primary key on all tables it sends to
BigQuery.
- Add primary key to HABTM table
- Blocklist active_record_storage_variants
- ### Guidance to review
> Add primary key to habtm join table

- app/services/oneoffs/remove_fees_from_ecf_contracts.rb
- spec/services/oneoffs/remove_fees_from_ecf_contracts_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2224
* Created service class `Oneoffs::RemoveFeesFromECFContracts` to execute the changes
* Rails console
* Run `Oneoffs::RemoveFeesFromECFContracts.new(cohort_year: 2021, from_date: "2023-10-01").call`
> [CPDLP-2224] Remove service fees from ECF 2021 contract/cohort statements from October 2023 statement onwards

- app/models/concerns/gias_types.rb
- app/services/data_stage/process_school_changes.rb
- app/services/data_stage/update_staged_schools.rb
- spec/factories/staged_school_change.rb
- spec/services/data_stage/process_school_changes_spec.rb
Currently some simple changes are not processed automatically such as new schools without links or "unhandled" attributes which don't need to be handled in any special way. This PR removes the unhandled attribute checks and also allows the addition of new schools where possible.
> Allow GIAS importer to do more automatically

- app/forms/appropriate_body_selection_form.rb
- app/forms/schools/cohorts/wizard_steps/appropriate_body_step.rb
- app/services/importers/appropriate_bodies.rb
- spec/forms/edit_induction_tutor_form_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1981)
Remove NTA from the list of options of National ABs from 2023
Make cohort setup form respect the `AppropriateBody.disable_from_year` attribute when providing the options for selection
Set the disable_from_year to 2023 in the AB importer for NTA.
As a SIT when setting up the 2023 cohort, when choosing an AB select "National" and then the only AB option presented should be IStip. NTA should not be an option.
> [CST-1981] Remove NTA from 2023 AB options list

- docs/source/get-started.html.md
- docs/source/release-notes.html.md
- swagger/v1/api_spec.json
- swagger/v1/template.yml
- swagger/v2/api_spec.json
- swagger/v2/template.yml
- swagger/v3/api_spec.json
- swagger/v3/template.yml
There are still old sandbox URLs in our API docs
- Ticket: n/a
Swap out old PaaS sandbox URLs for new AKS URLs
> Swap old PaaS URL for new AKS URL

- app/controllers/healthcheck_controller.rb
- bin/smoke
The healthcheck is used by the smoke tests to ensure that the environments are in good shape before continuing the continuous deployment process.
This check provides some extra safety by ensuring if we make changes to resource names in terraform that result in them being deleted (#3992, #4008) and recreated, the emptiness of the tables will cause a failure.
- Add a database populated check to the healthcheck
- Alter healthcheck status based on db connectivity
- Add connected/populated checks to the smoke test
> Add database populated checks to the healthcheck and smoke test

- app/forms/finance/npq/change_lead_provider_form.rb
- app/models/participant_declaration/npq.rb
- app/services/change_schedule.rb
- app/services/npq/amend_participant_cohort.rb
- app/services/record_declaration.rb
- app/validators/npq_contract_for_cohort_and_course_validator.rb
- config/locales/en.yml
- spec/components/finance/statements/npq_details_table_spec.rb
- spec/docs/v1/npq_participants_spec.rb
- spec/docs/v2/npq_participants_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/factories/participant_declaration.rb
- spec/features/finance/change_lead_provider_spec.rb
- spec/features/participant_declarations/participant_declaration_steps.rb
- spec/forms/finance/npq/change_lead_provider_form_spec.rb
- spec/requests/api/v1/npq_participants_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/npq_participants_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/change_schedule_spec.rb
- spec/services/finance/npq/statement_calculator_spec.rb
- spec/services/npq/amend_participant_cohort_spec.rb
- spec/services/record_declaration_spec.rb
- spec/validators/npq_contract_for_cohort_and_course_validator_spec.rb
- Ticket: [CPDLP-2387](https://dfedigital.atlassian.net/browse/CPDLP-2387)
Add validation to all entry points and changes for NPQ applications and profiles to prevent provider/user changing cohort for NPQ where there is no contract for the course in the target/new cohort.
[CPDLP-2387]: https://dfedigital.atlassian.net/browse/CPDLP-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2387] Prevent provider/user changing cohort for NPQ where there is no contract for the course in the target/new cohort

- lib/participant_profile_deduplicator.rb
- spec/lib/participant_profile_deduplicator_spec.rb
[Jira-2455](https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2455)
Currently when we deduplicate two mentor profiles we are neglecting to assign the `mentee_profiles` from the duplicate to the primary, so we end up with mentees that have no mentor.
- Update mentees when deduplicating
> Update mentees when deduplicating

- app/jobs/set_participant_completion_date_job.rb
The participant induction completion date job had an issue where it was re-updating participants that already had an `induction_completion_date` set causing additional induction records to be created.
Prevent job from re-checking and updating participants with an `induction_completion_date`
> [Bug-Fix] Prevent job from rechecking/updating ECTs with a completion date

- analytics_queries/README
These are run semi-regularly for Nathan.
For some reason piping with `<` no longer works with psql, but specifying the file to run with `--file=` does.
> Update analyics instructions for Azure

- spec/docs/v3/ecf_participants_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
- swagger/v1/component_schemas/ECFParticipantChangeScheduleAttributes.yml
- swagger/v1/component_schemas/ECFParticipantCsvRow.yml
- swagger/v1/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
- swagger/v1/component_schemas/NPQParticipantChangeScheduleAttributes.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/ECFParticipantAttributes.yml
- swagger/v2/component_schemas/ECFParticipantChangeScheduleAttributes.yml
- swagger/v2/component_schemas/ECFParticipantCsvRow.yml
- swagger/v2/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v2/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v2/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
- swagger/v2/component_schemas/NPQEnrolment.yml
- swagger/v2/component_schemas/NPQEnrolmentCsvRow.yml
- swagger/v2/component_schemas/NPQParticipantChangeScheduleAttributes.yml
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFEnrolment.yml
- swagger/v3/component_schemas/ECFParticipantChangeScheduleAttributes.yml
- swagger/v3/component_schemas/NPQEnrolment.yml
- swagger/v3/component_schemas/NPQParticipantChangeScheduleAttributes.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2457
We’re missing some schedule-identifier values from the API spec.
Ensure API spec contains all possible schedule-identifier values for ECF and NPQ.
> [CPDLP-2457] Ensure API spec contains all possible schedule-identifier values for ECF and NPQ

- app/components/admin/schools/cohort_component.html.erb
- app/components/admin/schools/cohort_component.rb
- app/components/admin/schools/partnership_component.rb
- spec/components/admin/schools/cohort_component_spec.rb
- spec/components/admin/schools/partnership_component_spec.rb
This is an attempt to fix a bug in the admin console's cohorts tab where:
* a school is FIP
* the school has no partnerships/relationships
* the school does have a `school_cohort`
Previously this circumstance (which sounds invalid to me!) left a gap on the page. Now that gap is filed with a summary list that has a change link:
|-----|-----|
| ![Screenshot from 2023-09-18 16-57-05](https://github.com/DFE-Digital/early-careers-framework/assets/128088/e9e80da0-aa20-486e-afa2-3c14aa552636) | ![Screenshot from 2023-09-18 16-57-18](https://github.com/DFE-Digital/early-careers-framework/assets/128088/a0c126d2-4c8a-4b7b-9eb5-0b6d6a79db29) |
Because we're now displaying FIP details in multiple context I've moved the FIP entries from `#training_programme` up into the …
> Fix admin cohort page when school cohort present and partnerships missing

- app/forms/appropriate_body_selection_form.rb
- config/locales/devise.en.yml
- config/locales/en.yml
- spec/features/admin/npq_applications/export_spec.rb
- spec/features/finance/banding_tracker_spec.rb
- spec/requests/lead_providers/report_schools/csv_spec.rb
The [GOV.UK Design System guidance for error messages](https://design-system.service.gov.uk/components/error-message/) is:
> Be clear and concise
> Do not use ‘please’ because it implies a choice
> Drop 'please' from error messages

- app/models/induction_record.rb
- app/services/dashboard/participants.rb
- app/views/schools/participants/_completed_induction.html.erb
- app/views/schools/participants/_currently_training_sorted_by_mentor.html.erb
- app/views/schools/participants/_no_longer_training.html.erb
- config/locales/status_tags/school_participant_status.yml
- spec/features/schools/participant_dashboard/completed_induction_participants_spec.rb
- spec/features/schools/participant_dashboard/manage_cip_participants_spec.rb
- spec/features/schools/participant_dashboard/no_longer_training_participants_spec.rb
- spec/features/schools/participants/remove_from_cohort_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/services/dashboard/participants_spec.rb
We need to update the participants dashboard so that:
No longer training:
- Mentors or ECTs who have been withdrawn 
- Mentors or ECTs who have been reported as leaving the school by the CURRENT SIT 
- Mentors or ECTs who have been reported as joining a new school AND the joining date provided by the NEW SIT has passed 
Currently training:
- Mentors without ECTs who do not fit the above "No longer training" criteria 
- If the "Mentor (A-Z)" sort order is selected, then all mentors should be listed alphabetically, even if they don't currently have any ECTs associated with them
- Mentors without ECTs should have a smaller card design, with no "ECTs" header or list, and a "Not mentoring" status label
- Ticket: CST-1968
- Update the `InductionRecord.school_dashboard_relevant` scope to also …
> [CST-1968] Update the school dashboard filters

- app/views/schools/add_participants/name.html.erb
The hint for the name field should use the regular hint pattern, with dark grey text, and a smaller gap.
> Change name hint to use regular hint pattern

- app/controllers/admin/participants/validation_data_controller.rb
- spec/requests/admin/participants/change_validation_data_spec.rb
Originally, changing a participant's validation data item returned you to the validation tab. When the tab component changed to use page paths instead of anchors this was missed.  This PR returns you to the validation data tab after making a change.
Use the path instead of the anchor for validation data tab.
As an admin, select a participant that has not validated (ie. contacted for information status), go to the validation data tab and add/change one of the validation data items. You should be returned to the validation data tab not the details tab.
> [Bug-fix] Make validation changes return to validation tab

- app/components/admin/schools/cohort_component.rb
- spec/components/admin/schools/cohort_component_spec.rb
The `#has_partnerships_or_relationships?` method incorrectly required both parnerships and relationships to be present but should return true when either is 🤦
> Fix school cohort rendering bug

- app/controllers/schools/add_participants/base_controller.rb
- app/controllers/schools/add_participants/transfer_controller.rb
- app/forms/schools/add_participants/add_wizard.rb
- app/forms/schools/add_participants/base_wizard.rb
- app/forms/schools/add_participants/transfer_wizard.rb
- app/forms/schools/add_participants/who_to_add_wizard.rb
- app/forms/schools/add_participants/wizard_steps/cannot_add_yourself_as_ect_step.rb
- app/forms/schools/add_participants/wizard_steps/email_step.rb
- app/forms/schools/add_participants/wizard_steps/yourself_step.rb
- app/services/mentors/transfer_existing_mentor_to_sit.rb
- app/views/schools/add_participants/cannot_add_yourself_as_ect.html.erb
- app/views/schools/add_participants/complete.html.erb
- app/views/schools/add_participants/participant_type.html.erb
- app/views/schools/add_participants/start_term.html.erb
- config/locales/en.yml
- spec/features/schools/participants/add_participants/sit_add_ect_spec.rb
- spec/features/schools/participants/add_participants/sit_add_mentor_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/forms/schools/add_participants/wizard_steps/cannot_add_yourself_as_ect_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/email_step_spec.rb
SITs becoming mentors - remove separate journey
- Ticket: CST-1799
- SITs becoming mentors - add speedbump page (CST-1796)
- SITs can't accidentally add themselves as ECTs page (CST-1807)
- Remove "Add yourself as a mentor" option from add participant wizard (CST-1808)
- SITs becoming mentors - dedupe when registered at a previous school with a different email address (CST-1797)
> SITs becoming mentors - remove separate journey

- Gemfile
- Gemfile.lock
- config/analytics.yml
Includes bug fixes for supporting models using single table inheritance.
I'm not sure why `school_id` wasn't being picked up in earlier versions of the gem but its a field that definitely exists in the database so we can/should be sending it.
I've tested on the review app and its pulling through STI models into BigQuery correctly now.
> Update dfe-analytics to latest version

- app/views/admin/participants/induction_records/show.html.erb
On the admin UI when looking at a participant's induction record the LP/DP is always present and the CIP materials never show even if the induction record is a CIP one.  I've added a condition to only show the LP/DP details when FIP and show CIP materials when CIP instead.
Show CIP materials on CIP induction records and FIP LP/DP on FIP induction records
> [CST-2025] Show CIP materials on CIP induction records

- app/forms/admin/participants/change_relationship/change_relationship_wizard.rb
- spec/forms/admin/participants/change_relationship/change_relationship_wizard_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1960)
Intermittent problem existed where in the admin console, attempting to change a participants relationship resulted in being kicked out to the participant details when clicking "Continue" on the first wizard page.
This appears to happen only in the following scenario:
* Admin chooses the change of circumstances option
* The participant has declarations with their current provider
* There is at least one other relationship at the school
On clicking "Continue" the next step (:change_training_programme) is loaded and it checks that you should be allowed to land here. This test checks whether the partnership can be changed but does not consider that it is OK to change when the participant has declarations if the admin chose the …
> [CST-1960] - Bug Fix: allow declarations to exist with change of circumstances option

- app/controllers/api/api_controller.rb
- spec/requests/dfe_analytics_spec.rb
We aren't tracking API requests as `web_request` in DfE Analytics
- Ticket: n/a
Add dfe analytics to API controller to start tracking API requests in BQ events
thanks @ethax-ross for your help in finding this!
> Add DFE analytics to API controller

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
We want to make sure this header is set in production before we use it for rate limiting.
Taken from review app logs:
```
[2023-10-04T10:56:25.291568 #1]  INFO -- : [cb3581de6f8b1971c7875103d24411bc] x-real-ip: 94.***.***.115 (remote ip: 94.***.***.115)
```
> Log the x-real-ip header

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
Reverts DFE-Digital/early-careers-framework#4093 - the x-real-ip has been verified in production and looks good so we no longer need this.
> Revert "Log the x-real-ip header"

- app/helpers/school_breadcrumbs_helper.rb
- app/views/schools/participants/index.html.erb
- app/views/schools/participants/show.html.erb
- spec/helpers/school_breadcrumbs_helper_spec.rb
This adds a breadcrumb instead of "back" links to the "Manage mentors and ECTs" page and the participant profile pages.
Where a user has access to more than 1 school, the breadcrumb starts with the "Manage your schools" link.
All other pages which are in a flow to add or change information continue to use back links instead.
🗂️ [Jira card](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119)
| Page | Before | After (single school) | After (2+ schools)
|----|----|-----|---|
| Manage mentors and ECTs | <img width="755" alt="Screenshot 2023-10-03 at 14 39 05" src="https://github.com/DFE-Digital/early-careers-framework/assets/30665/442d4155-7f28-470c-9021-bdc2df1c3b8c"> | <img width="667" alt="Screenshot 2023-10-03 at 14 39 16" …
> Add breadcrumb to school and participant views

- app/forms/schools/add_participants/who_to_add_wizard.rb
- app/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_deferred_step.rb
- app/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_leaving_step.rb
- app/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_withdrawn_step.rb
- app/forms/schools/add_participants/wizard_steps/who_to_add_participant_checks.rb
- app/views/schools/add_participants/cannot_add_already_enrolled_at_school_but_deferred.html.erb
- app/views/schools/add_participants/cannot_add_already_enrolled_at_school_but_leaving.html.erb
- app/views/schools/add_participants/cannot_add_already_enrolled_at_school_but_withdrawn.html.erb
- spec/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_deferred_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_leaving_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/cannot_add_already_enrolled_at_school_but_withdrawn_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/date_of_birth_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/nino_step_spec.rb
- Ticket: CST-1988
We want to provide better info to SITs if they try to register somebody at the same school who is withdrawn/deferred/leaving.
- Add new wizard steps and views for enrolled participants who are withdrawn, deferred and leaving
- Update the `WhoToAddParticipantChecks#existing_participant_checks` method to route the SIT to the new views based on the participant's status
As an SIT, try to add participants (Mentors or ECTs) who are already enrolled at the same school and confirm the correct info is displayed based on their training/induction status (active, leaving, withdrawn, deferred) and their induction programme.
> [CST-1988] Give better info to SITs when adding already enrolled participants is failing

- app/forms/schools/add_participants/who_to_add_wizard.rb
- app/forms/schools/add_participants/wizard_steps/who_to_add_participant_checks.rb
- spec/forms/schools/add_participants/wizard_steps/date_of_birth_step_spec.rb
- spec/forms/schools/add_participants/wizard_steps/nino_step_spec.rb
- Ticket: CST-1988
#4083 introduced a bug redirecting the SITs who are trying to add completed participants to the wrong page. It should redirect them to `cannot-add-already-enrolled-at-school` page. 
This is a follow up fix.
- Add a method to check if the participant is completed and use it in the `existing_participant_checks` that decides what's the next step is
> [CST-1988] Display the correct page when SITs adding already enrolled participants with completed induction

- config/environments/sandbox.rb
- config/environments/staging.rb
Switching to the Redis cache in sandbox and staging so we can test it ahead of rolling out to production.
> Enable Redis for Rails.cache in sandbox/staging

- app/controllers/schools/add_participants/add_controller.rb
- app/controllers/schools/add_participants/transfer_controller.rb
Added logging information within AddController and TransferController's data check method to clarify redirecting to the abort path.
- Ticket: CST-1799
> Added logging information within add mentor wizard 

- app/controllers/application_controller.rb
- spec/requests/dfe_analytics_spec.rb
We call this endpoint frequently and it just creates noise in dfe-analytics/other monitoring platforms.
> Skip DfE analytics events for /check endpoint

- docs/source/release-notes.html.md
Release note to say we've added a new field, induction_end_date, to the participant profile ECF endpoint.
> 6 october release-note.html.md

- app/mailers/ineligible_participant_mailer.rb
Sentry error is being raised in a daily basis.
https://dfe-teacher-services.sentry.io/issues/4310296798/?referrer=slack&notification_uuid=1318e182-dab9-4bcc-8cba-681f1fa945b1&alert_rule_id=7310304&alert_type=issue
Fix undefined local variable or method `induction_tutor_email' for #<IneligibleParticipantMaile> (NameError)
> Fix undefined local variable or method induction_tutor_email error on IneligibleParticipantMailer

- app/serializers/api/v3/ecf/partnership_serializer.rb
- app/services/api/v3/ecf/partnerships_query.rb
- docs/source/release-notes.html.md
- spec/serializers/api/v3/ecf/partnership_serializer_spec.rb
- spec/services/api/v3/ecf/partnerships_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2470
* Updated `Api::V3::ECF::PartnershipSerializer`
* Updated `Api::V3::ECF::PartnershipsQuery`
* Updated release notes
> [CPDLP-2470] Change to / update of SIT does not touch updated_at field of partnership (or school response)

- app/jobs/build_completion_candidates_list_job.rb
- app/jobs/set_participant_completion_date_job.rb
- app/models/completion_candidate.rb
- app/services/participants/build_completion_candidate_list.rb
- app/services/participants/check_and_set_completion_date.rb
- config/analytics_blocklist.yml
- config/sidekiq_cron_schedule.yml
- db/migrate/20230929161148_create_completion_candidate.rb
- db/migrate/20230929170240_validate_completion_candidates.rb
- db/schema.rb
- spec/services/participants/build_completion_candidate_list_spec.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2028)
Our original "one-time" backfill job ended up being run every night to check the DQT for induction completion dates.
The `touch` method used to move records to the end of the queue resulted in phantom updates being exposed to providers.
This PR adds a table to hold list of candidates for checking that can be processed and cleared down without causing any side-effects to other parts of the service.
A future piece of work is planned that will review the candidate selection algorithm and perhaps find a more intelligent and cohort-proof method. At the moment it is the same as the previous method that includes all ECTs registered prior to the 2023 academic year that have started an induction.
Add a new `completion_candidates` …
> [CST-2028] Adopt new way to process induction completion dates

- config/environments/production.rb
- config/environments/sandbox.rb
- config/environments/staging.rb
We have this enabeld in sandbox/staging already and it appears to be behaving.
Use default Redis `pool_size`.
> Enable Redis as Rails.cache in production

- docs/source/ecf/guidance.html.md
Bullet added to the 'View and update participant data' section explaining that providers can now see when ECTs have completed their induction.
> Update guidance-completed inductions.html.md

- app/serializers/api/v3/ecf/participant_serializer.rb
- docs/source/ecf/guidance.html.md
- docs/source/release-notes.html.md
- spec/docs/v1/npq_participants_spec.rb
- spec/docs/v2/npq_participants_spec.rb
- spec/docs/v3/ecf_participants_spec.rb
- spec/docs/v3/npq_participants_spec.rb
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFEnrolment.yml
- Ticket: [CPDLP-2466](https://dfedigital.atlassian.net/browse/CPDLP-2466)
We would like to surface data to let providers know that a participant has completed their induction.
Add induction_completion_date into API v3 ecf participants endpoint
[CPDLP-2466]: https://dfedigital.atlassian.net/browse/CPDLP-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2466] Add induction_end_date into API v3 ecf participants endpoint

- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- spec/services/importers/create_new_ecf_cohort_spec.rb
- spec/services/npq/amend_participant_cohort_spec.rb
We currently have many flakey tests in our test suite, which we are ignoring. Those slow us down especially in incidents when important changes need to go out, and retrying failed tests prolongs deployment times. To first start trakcing those, we propose adding a new tag: `flakey_test` to those tests, and start tackling them slowly as we go
- Ticket: n/a
Add flakey test tag to known flakey tests, to start fixing them
What does everyone think of this approach?
> Add new tag for flakey tests

- app/services/create_partnership_csv_upload.rb
- spec/services/create_partnership_csv_upload_spec.rb
Error raised when CSV has invalid UTF-8 characters
- Ticket: n/a
If a urn CSV has invalid characters ignore them when encoding
> Ignore non utf-8 characters in CSV upload

- app/models/participant_id_change.rb
- app/services/identity/transfer.rb
- spec/models/participant_id_change_spec.rb
- spec/services/identity/transfer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2467
* Added find or create for `participant_id_changes` to avoid duplicates
* Added paper trail to `ParticipantIdChange` model
> [CPDLP-2467] Dont allow duplicate participant_id_change entries

- app/models/participant_profile/ecf.rb
- docs/source/release-notes.html.md
- spec/services/npq/amend_participant_cohort_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFWithdrawal.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2476
A provider may not include the value `started-in-error` as a withdrawal_reason for any API version as well as drilldown.
> [CPDLP-2476] Remove 'started-in-error' as a value from ecf withdraw reason options

- Gemfile
- Gemfile.lock
This release fixes a problem we encountered when using DfE-analytics with [single-table inheritance](https://guides.rubyonrails.org/association_basics.html#single-table-inheritance-sti).
> Upgrade to dfe-analytics 1.11.1

- .gitignore
Prevent the accidental committing of Terraform's state/lock files.
> Ignore Terraform lockfiles

- app/services/participant_id_changes_csv.rb
- spec/services/participant_id_changes_csv_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2469
* New service class `ParticipantIdChangesCsv` to return all `participant_id_changes` in the last 30 days
> [CPDLP-2469] UCL Deduping: Add service class to create csvs for deduped participants

- app/views/admin/administrators/administrators/index.html.erb
Useful information for providing guidance
- Add super user info to admin page
> Output super user status on admin page

- app/controllers/api/api_controller.rb
- config/initializers/dfe_analytics.rb
- spec/requests/dfe_analytics_spec.rb
Reinstate API requests as `web_request` in DfE Analytics
Adding this the first time https://github.com/DFE-Digital/early-careers-framework/pull/4080 caused issues in the NPQ reg application when querying our API due to the following https://dfe-teacher-services.sentry.io/issues/4519374530/?alert_rule_id=7310304&alert_type=issue&notification_uuid=d4ae4668-3d2a-4566-9ac2-0fe446909ca7&project=5748989&referrer=slack
Where DfE analytics expects a record as the current user, however the owner in NPQ reg APIs is a string.
We now override this check in the config to only check the user IF the user is a record.
- Ticket: n/a
- Add dfe analytics to API controller to start tracking API requests in BQ events
- Add a custom user method in the config to not return anything if the user is not a record
- …
> Reinstate DFE analytics to API controller

- config/environments/production.rb
- config/environments/sandbox.rb
- config/environments/staging.rb
We get a few timeout errors/day; it may be that the Redis cache is under heavy load, but we don't want to be alerted about it (Rails will silently treat this as a cache-miss, so not user-facing).
Looking into the metrics on our cache Redis instance the latency is higher than our queue Redis instance, but its still sub 200ms when we get these errors and our read/write timeout is set to 1s (Rails default). We can't really explain why we are seeing the timeouts but its only ~6/day. 
When we have an alerting solution in place we could look to monitor the warning and raise an alert if we hit an unexpected threshold of these.
We could also try bumping the Redis cache from Standard-C1 to Standard-C3, which would upgrade the network performance from "Low" to "Moderate" (but is 3x the cost).
> Warn on Redis::TimeoutError

- Makefile
Sometimes the terraform state locks and we need to release the lock.This can be done in the portal but good to have a make command as well
- Ticket: n/a
Add make command to unlock a terraform state.
The command unfortunately will require a docker image attached for now as the step `terraform-init` requires it, however we can add a fake string, see examples below
```
```
> Add make command to unlock terraform state

- .github/workflows/aks_deploy.yml
We used to want to deploy when the 'deploy' label was added to PRs but changed that behaviour so they were always built. As a result we can remove the 'labeled' type triggering deploys because when multiple tags are added in succession multiple builds are triggerd.
> Prevent 'labeled' events from triggering deploys

- app/forms/schools/add_participants/add_wizard.rb
- app/services/participants/withdrawn_profile_finder.rb
- spec/features/schools/participants/add_participants/add_previously_withdrawn_ect_spec.rb
- spec/features/schools/participants/add_participants/add_previously_withdrawn_mentor_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-2038
When checking for existing profiles that may be reactivated the AddWizard will now also check for withdrawn profiles on user's matching the entered email if no TRN match is found.
> [CST-2038] Check for email when attempting to reactivate a profile

- app/components/admin/schools/cohort_component.html.erb
- app/views/admin/participants/school/show.html.erb
- app/views/admin/participants/statuses/show.html.erb
- app/views/schools/participants/show.html.erb
- spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb
- spec/support/features/pages/admin_support/admin_support_participant_training.rb
- spec/support/features/pages/schools/school_participant_details_page.rb
- spec/support/features/steps/changes_of_circumstance_steps.rb
- Ticket: CST-2026
We want to display the materials supplier in the following pages for CIP participants:
- Admin Training page
- Admin Statuses page
- Schools participant page
- Update the views to display the Materials supplier or the LP/DP info based on their CIP/FIP enrollment
Check all three pages are displaying:
- the Materials supplier when participants are on CIP
- the LP/DP info when participants are on FIP
> [CST-2026] Display the materials supplier in Admin and Schools pages

- app/controllers/api/v1/npq/application_synchronizations_controller.rb
- spec/requests/api/v1/npq/application_synchronization/index_spec.rb
update provider application status logic to cater to historic applications
https://dfedigital.atlassian.net/browse/CPDNPQ-1381
Updated `app/controllers/api/v1/npq/application_synchronizations_controller.rb` to manage more then 1.week.ago applications. Added limit to safe from timeout error
> update provider application status logic to cater to historic applications

- app/controllers/admin/participants/induction_records_controller.rb
- app/helpers/admin_helper.rb
- app/policies/induction_record_policy.rb
- app/presenters/admin/participant_presenter.rb
- app/views/admin/participants/induction_records/edit_training_status.html.erb
- app/views/admin/participants/induction_records/show.html.erb
- config/routes.rb
- spec/presenters/admin/participant_presenter_spec.rb
When a FIP participant is no longer training, their provider sets training_status = withdrawn.
CIP participants, however, have no lead provider, so we have to find another way of indicating they’re no longer training.
We also use induction_status = withdrawn. However, at the moment this needs to be actioned by a dev, which is time-consuming.
We therefore want to add a facility for first line agents to change induction_status = withdrawn for CIPsters ONLY. Note that this will not affect their access to funding.
[Ticket](https://dfedigital.atlassian.net/browse/CST-2012)
> CST-2012: allow admin users to edit the training status of CIP participants

- app/views/admin/participants/school/show.html.erb
- Ticket: CST-2072
The current Participant training in the Admin pages displays the LP/DP from the default induction programme of the school cohort the participant is in. However the participant may be on one of the relationships insteadm which is reflected in their induction record.
This PR uses the relevant induction record of the participant to display the LP/DP correctly in their training admin page.
- Update the view to use the presenter's `lead_provider_name` and `delivery_partner_name` methods instead of the school ones
- Visit the admin pages
- Pick a participant who's doing a FIP programme from a relationship (not the default induction programme of the school cohort)
- Confirm the LP/DP in their Training page is the correct and also the same that's in their induction record
> [CST-2072] Display the correct providers in the Admin Participant training page

- app/jobs/api_request_job.rb
- spec/jobs/api_request_job_spec.rb
Currently we only persist the request body for POST requests. Going forward, if there is a request body in the payload we want to persist it in the `ApiRequest` model.
- Save request_body in ApiRequest for PUT requests
> Save request_body in ApiRequest for PUT requests

- app/controllers/api/api_controller.rb
- app/controllers/api/errors/invalid_participant_outcome_error.rb
- app/services/record_declaration.rb
- config/locales/en.yml
- docs/source/release-notes.html.md
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- Ticket: [CPDLP-2553](https://dfedigital.atlassian.net/browse/CPDLP-2553)
Completed declaration should error when outcome fails to create.
Raise an error when a completed declaration outcome fails to create.
[CPDLP-2553]: https://dfedigital.atlassian.net/browse/CPDLP-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2553] Raise an error when a completed declaration outcome fails to create

- app/controllers/api/v1/npq/application_synchronizations_controller.rb
- spec/requests/api/v1/npq/application_synchronization/index_spec.rb
This bug surfaced [in Sentry](https://dfe-teacher-services.sentry.io/issues/4567543977/?alert_rule_id=14507789&alert_type=issue&notification_uuid=7987324f-898d-4af6-954c-b7d87fc925c2&project=5748989&referrer=slack).
```
ERROR:  invalid input syntax for type uuid: "" (PG::InvalidTextRepresentation)
LINE 1: ...00000000','aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee','','fffff...
```
When building raw SQL 'in' clauses we bypass ActiveRecord's tidying of conditions. By default it will reject non-uuids from uuid fields:
```ruby
NPQApplication.where(id: ["", " ", "abc", "7411192c-c8a1-4306-b840-b932377db02c"]
=> "...WHERE \"npq_applications\".\"id\" IN ('7411192c-c8a1-4306-b840-b932377db02c')"
```
Rewriting this method to use the ActiveRecord directly gives us the same query but with additional safety.
> Fix bug where blank uuid causes pg adapter to crash

- app/controllers/api/v3/participant_declarations_controller.rb
- app/services/api/v3/participant_declarations_query.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
NPQ only Providers are getting 403 errors when attempting to access declaration endpoints.
- Ticket: n/a
Declarations endpoint serves both ECF and NPQ, so both providers require access. This being there means that only ECF providers have access to declarations which is not always the case.
Test with NPQ provider hitting declarations endpoint v3
> Remove access restriction to ECF providers only

- app/views/finance/ecf/statements/show.html.erb
- app/views/finance/npq/statements/show.html.erb
- spec/features/finance/ecf/statement_spec.rb
We currently display the authorised for payment date in the same timezone that we store it in the database (UTC). Instead, we want to format the date and display it in the London timezone.
- Display authorised for payment date in local timezone
This is a app-wide issue, however applying a 'fix all' solution of setting the time zone in the application config is risky (it would change it everywhere, including in our API serializers). Instead, we are going to fix this on a case-by-case basis by converting the dates into London timezone prior to formatting them.
If we find we are going to change this in lots of other places it may be be worth creating a date formatting service.
To review, check the authorised time [here](https://manage-training-for-early-career-teachers.education.gov.uk/financ …
> Display authorised for payment date in local timezone

- app/controllers/admin/participants/change_induction_status_controller.rb
- app/helpers/admin_helper.rb
- app/policies/participant_profile_policy.rb
- app/services/induction/induction_statuses_activator.rb
- app/views/admin/participants/change_induction_status/edit.html.erb
- app/views/admin/participants/statuses/show.html.erb
- config/routes.rb
- spec/features/admin/participants/participant_steps.rb
- spec/features/admin/participants/update_induction_status_to_active_spec.rb
- spec/policies/participant_profile_policy_spec.rb
- spec/services/induction/induction_statuses_activator_spec.rb
- spec/support/features/user_helper.rb
- Ticket: CST-2058
SITs withdraw participants or set them as leaving by mistake. 
We want to enable super user admins to set them back to active.
For the leaving ones, we also want the school transfer to be `true`. This will display to a provider as a transfer from school A, into school A.
- Add a new service class with the logic required to set the `ParticipantProfile@status` and `InductionRecord@induction_status` to `active`
- Add a new admin page to display the new statuses with a button to confirm the changes
- Display conditionally a `Change` link in the Participant->Statuses page that leads to the new admin page
1. Go to the Admin pages as a super user admin
2. Find an active or completed ECF participant
3. Confirm there is no "Change" link in the "induction status" row as a super …
> [CST-2058] Enable super user admins to activate the participants induction statuses

- app/views/schools/core_programme/materials/success.html.erb
This service was replaced with a static website that has no login functionality.
A potential improvement would be to link to the right provider, I guess by this point in the journey we know it. I couldn't work out how to make the leap from [core_induction_programme](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/models/core_induction_programme.rb) to it though, because the model is bare. But at least now it won't just show a 404.
> Remove sign-up path from link to support for ECTs

- app/services/api/v3/participant_declarations_query.rb
- docs/source/release-notes.html.md
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
We are only filtering by ECF cohorts in decalarations endpoint in v3. We need add support for NPQ
- Ticket: n/a
- Support NPQ cohort filter in declarations endpoint
- Support both ECF and NPQ providers together and separately
Test with NPQ provider hitting declarations endpoint v3
> Fix Cohort filter in V3 Participant declaration API

- app/views/sandbox/show.html.erb
The old link is to GOVUK PaaS which is being decomissioned, the new one is to our new environment in Azure.
> Fix link to sandbox NPQ participant login

- app/views/schools/participants/index.html.erb
- spec/features/schools/participant_dashboard/manage_fip_partnered_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
We can remove this banner, now that we are pulling the completed induction status for ECTs from the DQT database and reflecting this in our interface.
Removing this banner improve the visibility of other information in the service, and avoids users from having to read information unnecessarily. 
🗂️  [Jira ticket](https://dfedigital.atlassian.net/browse/CST-1998)  [Second Jira ticket](https://dfedigital.atlassian.net/browse/CST-2100)
> Remove the banner around completed ECTs

- app/views/schools/add_participants/_transferring_ect_or_mentor_answers.html.erb
Spotted an error occurring in Sentry related to a bad method name. Call was missing the `?` at the end of the method name
> [Bug-fix] Fix method name used in view

- app/models/induction_record.rb
- app/services/dashboard/participants.rb
- spec/features/schools/participant_dashboard/no_longer_training_participants_spec.rb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/services/dashboard/participants_spec.rb
- Ticket: CST-2067
The No longer training search view in the school pages should also include participants with withdrawn or deferred training and withdrawn induction status
- Update the `InductionRecord.school_dashboard_relevant` scope return withdrawn or deferred participants
- Update the Dashboard::Participants service to include participants with those statuses when processing the ECTs and Mentors
Find schools with participants with withdrawn training, withdrawn induction and deferred training and confirm they are displayed in the "No longer training" search view when you are in the "Manage mentors and ECTs" school page
> [CST-2067] Include more participants in the no longer training search view

- app/components/status_tags/school_participant_status_tag.rb
- config/locales/status_tags/school_participant_status.yml
- spec/components/status_tags/school_participant_status_tag_spec.rb
- spec/features/schools/participant_dashboard/completed_induction_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- Ticket: CST-2076
This PR updates the description of the completed training status tag with more context, so SITs can be confident that the ECT's induction completion has been recorded with DfE correctly.
- Update the locale
- Update the status tag component to interpolate the necessary arguments for the tag's description
Visit the profile of a participant with `Completed` induction and confirm the new description is displayed correctly including the AB's name and the induction completion date. 
In case the participant has no appropriate body linked to their induction record, the default value `Your appropriate body` should be displayed instead of the AB's name.
> [CST-2076] Update the completed training tag description

- app/assets/stylesheets/lead_providers/statements.scss
- app/controllers/finance/npq/statements_controller.rb
- app/services/finance/npq/statement_calculator.rb
- app/services/oneoffs/npq/set_special_course_for_npq_contracts.rb
- app/views/finance/npq/statements/show.html.erb
- spec/factories/participant_declaration.rb
- spec/features/finance/npq/statement_spec.rb
- spec/services/finance/npq/statement_calculator_spec.rb
- spec/services/oneoffs/npq/set_special_course_for_npq_contracts_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2545
* Updated NPQ statement page to show `special_course=false`
* Include a new section "Standalone payments" that show `special_course=true`
> [CPDLP-2545] NPQ Maths - As an SRM I want to view NPQ Maths on the NPQ statement

- app/controllers/schools/participants_controller.rb
- app/policies/participant_profile/ecf_policy.rb
- spec/policies/participant_profile/ecf_policy_spec.rb
- Ticket: CST-2094
Currently, SITs can't see profiles of mentors who are only mentoring at the school (a.k.a mentors in the school's mentor pool).
We want to enable SITs to see such profiles, but without altering them.
- Update the ECFPolicy to enable SITs to see mentor profiles that are mentoring in their schools
- Update the ParticipantsController to get the mentor's induction record
1. Find to a school with mentors in their school mentor pool
2. Impersonate the SIT of the school
3. Visit the school's "Manage mentors and ECTs" page
4. Click on the name of the mentor
5. You should be able to see their profile, but not change any info
> [CST-2094] Enable SITs to access profiles of all their school mentors

- README.md
These could potentially confuse a new joiner so get rid.
* Logging is now accessible within Azure
* DfE are working on a replacement for the old Grafana setup
* Analytics is now handled via dfe-analytics/BigQuery, the old analytics database will be removed soon
> Remove Logit, Grafrana and Analytics info from README

- app/queries/schools/that_have_not_added_participants_query.rb
- app/queries/schools/that_ran_fip_last_year_but_have_not_engaged_query.rb
- app/queries/schools/unpartnered_last_year_and_have_not_partnered_this_year_query.rb
- app/queries/schools/unpartnered_query.rb
- app/queries/schools/with_ects_with_no_mentor_query.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/factories/seeds/school_cohort_factory.rb
- spec/queries/schools/that_have_not_added_participants_query_spec.rb
- spec/queries/schools/that_ran_fip_last_year_but_have_not_engaged_query_spec.rb
- spec/queries/schools/unpartnered_last_year_and_have_not_partnered_this_year_query_spec.rb
- spec/queries/schools/unpartnered_query_spec.rb
- spec/queries/schools/with_ects_with_no_mentor_query_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: [https://dfedigital.atlassian.net/browse/CST-2037](https://dfedigital.atlassian.net/browse/CST-2037)
Add queries and service to collate and send regular chaser mails to SITs.  This should enable the main repetitive mails to be sent easily manually, the next steps will be to automate these with a schedule and UI
Add queries to support selecting the correct schools to include in bulk mailing
Add a service to collate the schools from the queries and send the emails
> [CST-2037] Add schools queries for automated comms

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Jira-2592](https://dfedigital.atlassian.net/browse/CPDLP-2592)
We occasionally need to migrate declarations between different finance statements.
When doing this, we expect both statements to be output statements and after migrating the from statement should be updated to `output_fee: false`.
We only want to allow migration of NPQ declarations between NPQ statements and only when they are of the same cohort. We need to ensure there is a to/from statement for each provider.
- Add oneoff service to migrate declarations between statements
It may be that in the future we want to allow an output fee of `false` for the to/from statements. I've hard-coded an output-fee of `true` for now and I figure we can expand the interface if we meet that use case in the future.
Dry run output of the …
> Add oneoff service to migrate declarations between statements

- app/services/oneoffs/ecf/add_band_c.rb
- spec/services/oneoffs/ecf/add_band_c_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2565
* One off service class `Oneoffs::ECF::AddBandC` to add Band C for provider (National Institute of Teaching)
To run:
```ruby
cpd_lead_provider = CpdLeadProvider.where(name: "Provider name").first
payment_date_range = Date.new(2023, 11, 1)..
cohort_year = 2023
band_c_params = {
min: 401,
max: 455,
per_participant: 100.0,
output_payment_percentage: 60,
service_fee_percentage: 40,
}
Oneoffs::ECF::AddBandC.new(cohort_year:, cpd_lead_provider:, payment_date_range:, band_c_params:).call
```
> [CPDLP-2565] add a band C for NIoT and populate its min and max on 2023 ECF statements

- app/components/status_tags/appropriate_body_participant_status_tag.rb
- config/locales/status_tags/appropriate_body_participant_status.yml
- spec/components/status_tags/appropriate_body_participant_status_tag_spec.rb
- spec/features/appropriate_bodies/participants_spec.rb
- spec/services/appropriate_bodies/participants_filter_spec.rb
[Jira-2613](https://dfedigital.atlassian.net/browse/CPDLP-2613)
We have a new set of copy for some of the record states in the appropriate body status tag.
- Update AB status tag localisations
Also removes unused code from view component and clean up the specs.
A side-effect of this is that the status filter labels will have changed.
I've updated the review app so the example AB has participants for testing.
> Update appropriate body status translations

- app/services/finance/ecf/output_calculator.rb
- spec/services/finance/ecf/output_calculator_spec.rb
In cohort 2023 all band A declarations are appearing one over the max value, see https://manage-training-for-early-career-teachers.education.gov.uk/finance/ecf/payment_breakdowns/c3bc3cee-a636-42d6-8324-c033a6c38d31/statements/084aa7ad-2545-48a9-9388-a2c963855755 as an example where it should be 2000 rather than 2001 in band A
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2654
In legacy bandings, the minimum value for band A was set to `nil`, which meant in the output calculator it defaulted to 1. Since we introduced services to accept csvs and create contracts/bandings we set the band A min to 0. This pushed started declarations in band A above the max value, for instance band A max is set to 2000, it would appear in the dashboard as 2001.
Ensure that we account for both `nil` …
> Account for minimum band A being set to 0

- .github/actions/backup-and-upload-database/action.yml
- .github/workflows/backup_nightly_database.yml
We would like to keep a daily backup of the production database in case of errors.
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2647
- Add new workflow which runs nightly at 3:00 am which backs up the production database, and uploads it to the azure storage account
- Add an alert if the job fails. A new secret has been added to the key vault which we can use in the action
- The values have been hardcoded as this is only for production
- The backup is a duplicate of an existing backup restore to the snapshot but to avoid having to upload artifacts to Github (the db dump) when splitting actions, I've gone with duplication
- The slack alert has been tested and reports correctly in cpd-dev-alerts
- The uploaded db backup can be found in …
> [CPDLP-2647] Add nightly production database backup

- app/services/appropriate_bodies/induction_records_query.rb
- spec/features/appropriate_bodies/participants_spec.rb
- spec/services/appropriate_bodies/induction_records_query_spec.rb
- spec/support/shared_examples/optimised_training_record_state_query_support.rb
[Jira-2653](https://dfedigital.atlassian.net/browse/CPDLP-2653)
Currently, we show all participants associated with an appropriate body in the participants view and CSV export. Going forward, we only want to show ECTs here.
- Exclude mentors from AB participants
I assigned all mentors/ects to [this appropriate body](https://cpd-ecf-review-4285-web.test.teacherservices.cloud/appropriate-bodies/35391f57-a881-479d-9e7e-9ce8380f77dc/participants). Only the ECTs display now.
> Exclude mentors from AB participants

- .github/workflows/backup_nightly_database.yml
The schedule should not be part of the workflow dispatch as they are separate. This prevents the cron job from running
- Ticket: n/a
Fix syntax to allow job to run nightly
meh
> Fix syntax error in cron job for backup

- .rubocop.yml
- app/jobs/api_request_job.rb
- app/middlewares/api_request_middleware.rb
- app/models/api_request.rb
- config/analytics.yml
- config/analytics_blocklist.yml
- spec/factories/api_request.rb
- spec/jobs/api_request_job_spec.rb
- spec/middlewares/api_request_middleware_spec.rb
- spec/models/api_request_spec.rb
- Ticket: [CPDLP-2646](https://dfedigital.atlassian.net/browse/CPDLP-2646)
Stream request body to events production table.
After calling any api endpoint on the review app.. analytics events should appear on [BQ](https://console.cloud.google.com/bigquery?authuser=4&project=ecf-bq&supportedpurview=project&ws=!1m5!1m4!4m3!1secf-bq!2secf_events_review!3sevents).
```SELECT * FROM `ecf-bq.ecf_events_review.events` WHERE TIMESTAMP_TRUNC(occurred_at, DAY) >= TIMESTAMP("2023-11-20") AND entity_table_name = 'api_requests' LIMIT 1000```
[CPDLP-2646]: https://dfedigital.atlassian.net/browse/CPDLP-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2646] Stream ApiRequest with request body to big query events

- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/mentor.rb
- app/models/participant_profile/npq.rb
Ignored columns in a single table inheritance hierarchy cause DataForm problems. We don't think the `ignored_columns` are actually any use, other than hinting to the developer that this model doesn't need these columns.
> Comment out ignored columns for testing

- app/components/delivery_partners/participants/table_row.html.erb
- app/components/delivery_partners/participants/table_row.rb
- app/components/status_tags/delivery_partner_participant_status_tag.rb
- app/views/delivery_partners/participants/index.html.erb
- config/locales/status_tags/delivery_partner_participant_status.yml
- spec/components/status_tags/delivery_partner_participant_status_tag_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
- spec/services/delivery_partners/participants_filter_spec.rb
- spec/support/features/pages/delivery_partner/delivery_partner_portal.rb
[Jira-2564](https://dfedigital.atlassian.net/browse/CPDLP-2564)
We have a new set of copy for some of the record states in the delivery partner status tag. We also want to remove the training status column (to leave only the status column).
- Update DP status tag localisations
We have a new set of copy for some of the record states in the delivery partner status tag.
- Remove training status column from DP participants
We no longer want to display the training status in the DP participants view.
I've added a bunch of participants to [this delivery partner](https://cpd-ecf-review-4270-web.test.teacherservices.cloud/delivery-partners/6cdcdf5c-3ab0-4759-b67c-f216490d9405/participants) for testing.
> Update DP status tag localisations

- app/models/participant_profile/ecf.rb
- app/services/induction/change_mentor.rb
- docs/source/release-notes.html.md
- spec/models/participant_profile/ecf_spec.rb
- spec/models/participant_profile/ect_spec.rb
- spec/services/induction/change_mentor_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2609
Ensure that updated_at value of unfunded mentor is touched when an unfunded mentor gets linked to an ECT.
> [CPDLP-2609] Ensure that updated_at value of unfunded mentor is touched when an unfunded mentor gets linked to an ECT

- Makefile
[Jira-2644](https://dfedigital.atlassian.net/browse/CPDLP-2644)
At the moment we have to run the `konduit` command and then manually update the `database.yml`, which can be a bit of a faff. Instead, we want to automate as much of this as possible.
- Add a `make` command to more easily create a konduit to the snapshot database.
The command will remove any existing `url` in the development section of the `database.yml` and then create a `konduit` to the snapshot DB. When its created the `url` in the development section of the `database.yml` will be updated.
When the make command exits the `url` is removed form the `database.yml` file.
Run `make ci production konduit-snapshot` to test.
> Add make cmd for konduit to snapshot DB

- app/services/api/concerns/training_record_state_optimizable.rb
- app/services/determine_training_record_state_legacy.rb
- db/new_seeds/scenarios/participants/training_record_states.rb
- spec/services/determine_training_record_state_legacy_spec.rb
- spec/support/shared_examples/optimised_training_record_state_query_support.rb
When a mentor has a mentee that has left (`induction_status = leaving` and `end_date=a_date_in_the_past`) they should not have the "mentoring" status tag and should appear as not mentoring to the school.
Add a check for the `end_date` when the mentee induction_status is `leaving` in the SQL query
> [CST-2152] Fix mentor mentoring status

- terraform/aks/workspace_variables/sandbox_aks.tfvars.json
- Ticket: https://trello.com/c/Fy5fgxAG/813-increase-sandbox-webapp-memory
Sandbox webapp keeps restarting due to OOM 
Update sandbox tfvars.json with "webapp_memory_max": "2Gi"
Currently set to 1Gi
make sandbox terraform-plan
> Increase sandbox webapp memory to 2GB

- app/models/teacher_profile.rb
- app/services/npq/application/accept.rb
- spec/models/teacher_profile_spec.rb
Inside the `#same_trn_user` we are selecting all teacher profiles that match a TRN but aren't specifying any explicit order, so there's no guarantee which `TeacherProfile` record is found and used.
This appears to have caused some problems where providers expect a user to have one ID but they have another, because the `#deduplicate_by_trn!` method picked the 'wrong' teacher profile, so the wrong user to attach the `ParticipantIdentity` to.
This change orders the TeacherProfile records by created_at, so it will consistently link to the oldest record.
> Make teacher profile selection consistent

- app/services/induction/migrate_participants_to_new_programme.rb
- spec/services/induction/migrate_participants_to_new_programme_spec.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2131)
From the latest induction record of each participant, add a new induction record to the chain instead of from each induction record
> CST-2131: only migrate active induction records to a new programme

- app/presenters/archive/relic_presenter.rb
The code to choose the correct presenter was missing the option to handle a declaration from the list of choices.
Add the condition to choose the correct presenter for a declaration
> [Bug-fix] Archive declaration presenter missing from list of presenters

- app/components/support_form_component.html.erb
- app/components/support_form_component.rb
- app/controllers/support_controller.rb
- app/forms/support_form.rb
- app/models/support_query.rb
- app/views/schools/dashboard/_school_cohort_details.html.erb
- config/analytics.yml
- config/analytics_blocklist.yml
- config/locales/en.yml
- spec/features/support_forms/change_cohort_delivery_partner_spec.rb
- spec/features/support_forms/change_cohort_lead_provider_spec.rb
- spec/models/support_query_spec.rb
- Adds support forms data back to analytics upload
- Add Support Form: change-cohort-lead-provider
- Add Support Form: change-cohort-delivery-partner
- Add additional information to support queries detailing current participant profile state (see below for seed data example)
```
Test Message
---
Ticket Created By:
User ID: b4251de1-e8b2-4060-9e3f-08ee56ad18eb
Name: John Doe 5
Email: carlton@prosacco.io
School:
URN: 0019392
Name: Ruecker College
Participant Profile:
User ID: bf67f111-6c0d-483f-b6f2-37def8d7e377
Participant Profile ID: 37367df3-fad3-4e41-be0e-2212b77a9dc7
Current Name: Aldo Padberg
Current Email: aldo-padberg.splir@example.com
Current Lead Provider: Lead Provider
Current Delivery Partner: Delivery Partner 1
Current …
```
> [CST-2166] Add additional support forms

- .github/CODEOWNERS
This is no longer needed now we've stopped flip flopping on the index syntax in db/schema.rb
> Remove codeowners entry for `db/schema.rb`

- Makefile
- Ticket: N/A
The `konduit-snapshot` rule in the makefile injects the postgres url of the snapshot db in the database.yml with four spaces which nests it incorrectly.
Use two spaces indentation
> Fix the indentation when injecting the snapshot postgres url

- app/services/induction/amend_participant_cohort.rb
- spec/services/induction/amend_participant_cohort_spec.rb
Fix a bug in `Induction::AmendParticipantCohort` when the target year provided is a string instead of an integer.
> Fix bug when :target_cohort_start_year param given as string to Induction::AmendParticipantCohort

- Gemfile
- config/database.yml
- config/environments/migration.rb
- config/seed_quantities.yml
- db/seeds.rb
This environment will be used in the upcoming `migration` environment in Azure, and used to test the NPQ separation work.
- Add database config
- Add migration env config
- Add migration env to Gemfile, seeds and seed quantities
> Add migration rails env

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.sass.scss
- app/helpers/phase_banner_helper.rb
- app/views/admin/participants/statuses/show.html.erb
- app/views/finance/ecf/duplicates/index.html.erb
- app/views/layouts/_application.html.erb
- app/views/lead_providers/report_schools/base/success.html.erb
- app/views/nominations/nominate_induction_coordinator/check.html.erb
- app/views/nominations/nominate_induction_coordinator/start_nomination.html.erb
- app/views/participants/validations/no_match.html.erb
- app/views/participants/validations/trn.html.erb
- app/views/schools/add_participants/confirm_appropriate_body.html.erb
- app/views/schools/change_sit/check_details.html.erb
- app/views/schools/core_programme/materials/info.html.erb
- app/views/schools/participants/show.html.erb
- config/initializers/assets.rb
- config/routes.rb
- package.json
- spec/features/admin/participants/participant_steps.rb
- spec/features/finance/ecf/statement_spec.rb
- spec/features/finance/npq/statement_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/phase_banner_helper_spec.rb
- yarn.lock
This updates both `govuk-frontend` (node package) and `govuk-components` (Ruby gem) to version5.
Both have to be updated at the same time, as they are co-dependent on each other.
The main changes affecting this service are:
* the paths for the frontend assets have changed, now within a `dist/` folder in `govuk-frontend`
* the tag component no longer uses uppercase via CSS - so instead the tag text is capitalised within code
* the locations and sizes of the govuk icons has changed
* the javascript snippet adding class names to the `<body>` tag has changed
* the `govuk_link_to` ruby helper syntax has changed slightly
Thanks to @peteryates for helping with this.
> Update to govuk-frontend v5 (node) and govuk-components v5 (ruby)

- .github/workflows/aks_deploy.yml
- Makefile
- config/credentials/migration.yml.enc
- global_config/migration_aks.sh
- terraform/aks/workspace_variables/migration_aks.tfvars.json
- terraform/aks/workspace_variables/migration_aks_backend.tfvars
This environment, and the corresponding one in NPQ, will be used to repeatedly test the migration process.
It's a copy of `sandbox`.
The long name will be `migration` and the short name `mg`
The tfvars are copied from sandbox but we don't need domains/external hostnames. This is just for internal use.
> Add migration environment config for Azure

- app/services/induction/enrol.rb
- spec/services/induction/enrol_spec.rb
- Ticket: CST-2195
The Enrol class doesn't check if a participant_profile_state already exists before creating a new one, which may result in creating duplicate records.
- Check if the latest participant_profile_state of the participant is already active with the same CPD Lead Provider, before create a new one.
> [CST-2195] Avoid duplicating participant profile states when enrolling participants

- app/services/induction/induction_statuses_activator.rb
- spec/features/admin/participants/update_induction_status_to_active_spec.rb
- spec/services/induction/induction_statuses_activator_spec.rb
- Ticket: CST-2191
The InductionStatusesActivator wrongly sets the school transfer flag to true when the current induction status is leaving. It should just let the `ChangeInductionRecord` handle it.
- Remove the logic from the InductionStatusesActivator
> [CST-2191] Remove duplicate school transfer flag logic

- app/jobs/delete_completed_induction_records_job.rb
- app/services/induction/delete_dup_record.rb
- lib/tasks/deduping.rake
- Ticket: CST-2110
This changes the code a bit to process the records by participant and add a limit to run the deletion in a smaller scale.
> [CST-2110] Delete the dup completed induction records by participant

- .github/actions/refresh-migration-database/action.yml
- .github/workflows/refresh_migration_database.yml
- Makefile
We have a migration environment that we will be using for the ECF -> NPQ migration testing. Prior to running this in production we want to test it in a production-like environment.
- Add task to refresh migration DB from production
Add a GitHub action to allow us to populate the migration database from the production database. Update `Makefile` to include command to connect to the migration DB.
I've ran the GitHub action manually as part of this PR so the migration DB is populated. You can connect to it with the new make commands:
```
make migration konduit
```
You can also connect to the snapshot DB:
```
make ci production konduit-snapshot
```
> Add task to refresh migration DB from production

- app/components/support_form_component.html.erb
- app/components/support_form_component.rb
- app/views/layouts/_support_links.html.erb
- When logged in user will now see a link to the support form page in the footer instead of seeing the contact us email address.
> [CST-2166] Add support form link to the footer

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1875)
- We want to send comms to SITs and providers when we archive a participant (as part of the cleaning up of unvalidated, undeclared participants task).
- This PR adds the mailer for sending comms to the SIT.
New mailer for notifying SITs that we've archived a participant.
> [CST-1875] Comms relating to archiving participants

- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production_aks.tfvars.json
We know providers are using the API heavily, until the behaviour changes, we are ok to bump to 70% for now
- Ticket: https://trello.com/c/HAxSWYMT/889-stop-ecf-db-alerts
Add new variable to set cpu threshold and set to 70% on prod
> Bump up azure CPU threshold for alerting from 60 to 70%

- app/services/oneoffs/npq/cleanup_participant_declaration.rb
- spec/services/oneoffs/npq/cleanup_participant_declaration_spec.rb
Participant declarations have 2 different ways to determine its user (which in general is denormalization we don't need). 
User of `ParticipantDeclaration` might be accessed in 2 ways:
`participant_declaration.user` (via `user_id` field in participant declaration)
or via
`participant_declaration.participant_profile.participant_identity.user` - this is correct way.
During deduping some of them become incorrect. This code fixes any denormalization.
> Cleanup participant declarations for NPQ users

- app/assets/stylesheets/application.sass.scss
- config/locales/status_tags/school_participant_status.yml
- spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
- spec/features/schools/participant_dashboard/manage_cip_participants_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/support/shared_examples/manage_fip_partnered_participants.rb
With the update to GOV.UK Frontend version5, the [Tag component](https://design-system.service.gov.uk/components/tag/) is now recommended to use capitalised phrases rather than UPPERCASE.
> Make tags lowercase

- Gemfile
- Gemfile.lock
- config/initializers/dfe_analytics.rb
- config/sidekiq_cron_schedule.yml
EntityTableCheckJob sends a row_count, a checksum and a timestamp for each entity table sent to Big Query so that we can identify where database tables match Big Query tables and then help to debug where they don’t
- Ticket: n/a
The EntityTableCheckJob is enabled and scheduled to run every day at 00:30
Check scheduling is a reasonable time for job to run
N.B. Worth testing in staging/ review app prior to deploying - I can help!
> Enable and schedule entity table check job

- app/services/participant_identity_resolver.rb
- spec/services/participant_identity_resolver_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2684
We can have multiple NPQ applications to the same course with the same provider, but only one is accepted. If there are multiple identities linked to the user, the resolver will sometimes pick the wrong identity if there is another profile attached to that identity. 
To ensure we account for multiple identities and multiple NPQ applications to the same course, ensure the application is accepted.
I will test this on the snapshot with the failing id in the ticket to ensure it works for the provider
> [CPDLP-2684] Amend `ParticipantIdentityResolver` to fetch accepted NPQ applications only

- app/controllers/schools/transfer_out_controller.rb
- app/mailers/participant_transfer_mailer.rb
- app/services/induction/send_transfer_notification_emails.rb
- spec/features/schools/participants/transfer_out/ppt_transferred_in_and_transferred_out_spec.rb
- spec/features/schools/participants/transfer_out/transfer_out_only_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/forms/admin/school_transfer_form_spec.rb
- spec/mailers/participant_transfer_mailer_spec.rb
- spec/services/induction/send_transfer_notification_emails_spec.rb
- Ticket: CST-2163
We want to stop sending the transferring in and out emails to participants.
- Remove the `participant_transfer_in_notification` mailer
- Remove the `participant_transfer_out_notification` mailer
> [CST-2163] Stop sending transferring in and out emails to participants

- app/controllers/admin/performance/overview_controller.rb
- app/views/admin/performance/_nav.html.erb
- app/views/admin/performance/overview/show.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- Ticket: CST-2263
We want to build multiple new stat pages and group them together, rather than continually adding to the main nav.
The new design replaces the Admin homepage with a multinav page that hosts all the new stat pages we want to build, including the current Overview page.
This PR refactors the admin default page and lays the groundwork for the new stat pages.
- Move the Admin Overview page in the Performance namespace 
- Remove the old admin home route and make the `/admin/performance/overview` the new default admin page
- Create a subnav to be used in all the Performance stat pages
- Update the main menu
|before|after|
|-|-|
|![image](https://github.com/DFE-Digital/early-careers-framework/assets/951947/a7c79f4a-07f4-49c7-a27b-7a4b9fcd35ae)|![image](https://github.com/DFE-Digi …
> [CST-2263] Replace the Admin Home page with the Performance pages

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
To make it possible to differentiate the statements we're adding the NPQ lead provider name.
> Add NPQ lead provider name to logs

- app/services/bulk_mailers/school_reminder_comms.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2201)
When reviewing comms schedule we realised that the query used for unpartnered FIP schools was only applicable for the start of the academic year comms. The in-year chasers should not consider whether the school was partnered or not in the previous year.
Refactored so we have 2 methods, one for year start , one for in year usage.
> [CST-2201] add additional mailer for start of year comms

- app/models/email_schedule.rb
- config/analytics_blocklist.yml
- db/migrate/20240123152026_create_email_schedules.rb
- db/schema.rb
- spec/factories/seeds/email_schedule_factory.rb
- spec/models/email_schedule_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2291)
This is the first part of the ticket to add a new model that can be used to schedule the chaser comms
New DB table `email_schedules`
New model `EmailSchedule`
Not much to see yet, a separate story is handling the admin UI changes that will create/edit the schedules.
> [CST-2291] Add new model to support scheduling chaser comms emails

- .github/workflows/aks_deploy.yml
This is an attempt to reduce the number of duplicate workflow runs that happen on Dependabot PRs. My hunch is that the flow is kicked off at least twice, once when the PR is opened, once when the `dependencies` label is added and once when the `ruby` label is added, [giving us 3 runs](https://github.com/DFE-Digital/early-careers-framework/pull/4439/checks).
The [default types](https://github.com/DFE-Digital/early-careers-framework/pull/4439/checks) are `opened`, `synchronize`, or `reopened` so we're only really removing `labeled` here.
> Remove types from `pull_request` config on deployment flow

- app/components/support_form_component.html.erb
- app/components/support_form_component.rb
- app/controllers/challenge_partnerships_controller.rb
- app/forms/support_form.rb
- app/models/support_query.rb
- app/views/challenge_partnerships/already_challenged.html.erb
- app/views/layouts/_support_links.html.erb
- app/views/nominations/nominate_induction_coordinator/email.html.erb
- app/views/schools/add_participants/cannot_add_manual_transfer.html.erb
- app/views/schools/add_participants/cannot_add_mismatch.html.erb
- app/views/schools/change_sit/email.html.erb
- app/views/schools/partnerships/_signed_up_with_provider.html.erb
- config/locales/en.yml
- spec/requests/challenge_partnership_spec.rb
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
- spec/requests/schools/partnerships_spec.rb
Add support forms for the following situations:
(1) The nominate induction coordinator flow has a link to contact us via email if a tutor has already been nominated with a given email address with a different name.
(2) The add participants flow has multiple points where the user is directed to contact us via email where the SIT reaches a point where a user cannot be added. For example:
When they need manually transferring.
When there's a mismatch.
When there is a data mismatch with TRA.
(3) Viewing partnership details page displays a link to contact us via email if the partnership has been created and is outside the challenge window.
(4) On a couple pages related to challenging partnerships there is a link to contact us via email. …
> [CST-2166] Add support forms

- app/services/identity/transfer.rb
- docs/source/release-notes.html.md
- spec/services/identity/transfer_spec.rb
- Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2748
To ensure participant declarations are consistent with profile users when transferring identities, update the user id on any declarations attached to transferred profiles.
For each profile attached to a transferred identity, update participant declaration user id as well
> CPLD-2748 Update declarations when transferring identities

- Gemfile
- Gemfile.lock
Nothing really changed form builder wise between 4.7 and 5.0.
> Upgrade govuk_design_system_formbuilder to 5.0.0

- app/models/induction_record.rb
- app/queries/ects/with_an_appropriate_body_and_unregistered_query.rb
- app/queries/ects/without_an_appropriate_body_and_unregistered_query.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/queries/ects/with_an_appropriate_body_and_unregistered_query_spec.rb
- spec/queries/ects/without_an_appropriate_body_and_unregistered_query_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2265)
Second part of this to add the queries and methods to the `BulkMailer::SchoolReminderComms` service to support the mailers to SITs for participants without a registered induction
Adds new query objects
Updates the bulk mailer to add methods for sending the AB related comms to SITs.
> [CST-2265] (part 2) Add services and queries to support bulk mailer for AB comms

- app/models/npq_application.rb
- spec/models/npq_application_spec.rb
[Jira-2750](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2750)
The NPQ registration application calls an internal API in ECF that will create an application. At the moment, the `NPQApplication` is persisted and then the user is deduped. Its possible for the deduping process to raise an
exception; if this happens the application will have been persisted but the API will return a non-200 response. This causes the NPQ registration app to retry the application creation and results in a duplicate record.
Instead, we want to wrap this operation in a transaction so that if any part of the application creation or dedupe process fails the changes made will not be persisted and the NPQ registration service can safely retry the
operation.
- …
> Prevent duplicate NPQ applications from being created

- app/presenters/archive/participant_identity_presenter.rb
- app/views/admin/archive/relics/show.html.erb
- spec/presenters/archive/participant_identity_presenter_spec.rb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-1878)
- This ticket was left to mop up a few tweaks to the view of an archived participant.  It surfaces the archive reason in the details view and also fixes an issue where email addresses for identity records weren't being displayed correctly.
Add archive reason
Fix issue with displaying email addresses on archived participant identity records
> [CST-1878] - Display archived records

- app/services/api/v3/ecf/participants_query.rb
- docs/source/release-notes.html.md
- spec/services/api/v3/ecf/participants_query_spec.rb
Currently, if we filter by cohort the participants query will return a user if _any_ of their induction records have a schedule with that cohort.
Instead, we only want to return a user if their **latest** induction record schedule has the matching cohort.
- Fix participant query filtering by cohort
Remove `where` clause from `latest_induction_record_query` and apply it in the `participants_for_pagination` (after joining on the latest induction record). 
Remove cohort filtering from `participants_from` method as this always receives the `participants_for_pagination` result as its argument and so the filtering is already applied.
- Switch specs to use ChangeSchedule service
The setup for this is way more verbose, but its probably a better solution in case that service ever changes …
> Fix participant query filtering by cohort

- app/services/oneoffs/npq/backfill_trn_to_teacher_profile.rb
- spec/services/oneoffs/npq/backfill_trn_to_teacher_profile_spec.rb
Currently, the `BackfillTrnToTeacherProfile` service will populate unverified trns from applications. Instead, we want to ignore these and only populate verified trns. Adds missing test coverage.
> Only backfill verified TRNs

- app/services/induction/amend_participant_cohort.rb
Bug fix in Induction::AmendParticipantCohort: Now that historical records are set a LP/DP in a different way to the latest induction record, we can't include the latest induction record in the list of historical records.
> do not include the latest record in the list of historical records

- app/models/user.rb
- spec/models/user_spec.rb
[Jira-2798](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2798)
When we archive a user we want to nullify the `TeacherProfile.trn` so that the user isn't picked up in any future `Identity::Transfer` calls. This currently happens as we find the oldest `UserProfile` by matching the `trn` when transferring a user.
- Clear the TeacherProfile trn on archiving a user
Archiving users happens as part of the [DeduplicationService](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/services/deduplication_service.rb).
> Clear the TeacherProfile trn on archiving a user

- app/services/identity/primary_user.rb
- app/services/identity/transfer.rb
- app/services/npq/dedupe_participant.rb
- app/services/store_validation_result.rb
- config/locales/en.yml
- spec/services/identity/primary_user_spec.rb
- spec/services/identity/transfer_spec.rb
- spec/services/npq/dedupe_participant_spec.rb
- spec/services/store_validation_result_spec.rb
[Jira-2793](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2793)
There are two places where users can flip/flop via the `Identity::Transfer` service; `NPQ::DedupeParticipant` and `StoreValidationResult`. This happens because we exclude the 'current' user in each of these services from the query to find the primary user for the TRN. If the current user _is_ the primary user for the TRN, we will always select a newer `TeacherProfile` and transfer the primary user to that.
- Prevent flip/flop when deduping NPQ participants
Currently, if we call `NPQP::DedupeParticipant` with an `NPQApplication` that is associated with the oldest `TeacherProfile` it will always transfer this user onto a more recent `TeacherProfile` (as we exclude the …
> Fix flip/flopping of users in Identity::Transfer

- app/components/admin/participants/audit_trail_item_component.rb
- app/services/participants/history_builder.rb
Little fix to look up to see if a `whodunnit` from a version record is a `CpdLeadProvider` if it is not a `User` for the changes log
Look up `CpdLeadProvider` if `User` look up fails
> Fix change log so that CPD lead providers show up by name instead of ID

- app/views/admin/participants/induction_records/_show.html.erb
- app/views/admin/participants/school/show.html.erb
- Ticket: N/A
This PR addresses the issue of poor visual separation between different sections on the Admin->Participant->Training page, which currently makes it challenging to distinguish between sections at a glance.
Increase spacing below each section
|before|after|
|-|-|
|![before](https://github.com/DFE-Digital/early-careers-framework/assets/951947/ae1d3e84-8823-4061-9ed5-4305592ccec7)|![after](https://github.com/DFE-Digital/early-careers-framework/assets/951947/dc3d3de4-7af1-463f-ba06-be9170ba12eb)|
> Add spacing between page elements for improved section visibility

- config/initializers/rack_attack.rb
- spec/requests/rate_limiting_spec.rb
- spec/support/shared_examples/rate_limiting_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2700
* Updated rack attack initializer to include correct `user_id` (from API token)
* Added test
> [CPDLP-2700] Send provider id to BigQuery when api rate limited

- app/forms/nominate_induction_tutor_form.rb
- spec/forms/nominate_induction_tutor_form_spec.rb
- spec/requests/schools/change_sit_spec.rb
- Ticket: CST-2321
When nominating a new SIT the previous one won't be deleted but just removed from the school.
> Fix the Change Induction Tutor action

- app/serializers/archive/participant_profile_serializer.rb
- app/services/archive/destroy_ecf_profile_data.rb
- app/services/archive/unvalidated_profile.rb
- app/services/archive/unvalidated_user.rb
- spec/serializers/archive/participant_profile_serializer_spec.rb
- spec/services/archive/destroy_ecf_profile_data_spec.rb
- spec/services/archive/unvalidated_profile_spec.rb
As part of finishing off archiving unvalidated/undeclared participants, some of the remaining participants have deleted duplicate records. It was decided that we will include the serialised data from the deleted duplicate record in the archive for the "primary" profile and enable us to continue archiving and removing these users/profiles.
**Note**: I have refactored duplication of the destruction of the participant_profile and associated records into it's own service in the `Archive` module. This also allows it to tested in one place but it may not be desirable to be so accessible that the routine could be misused. I have added a warning message in the service code but would appreciate some comments/feedback/opinions on this.
- Include deleted duplicates in participant profile archive
- …
> Include deleted duplicate data when archiving unvalidated/undeclared profiles

- .github/workflows/aks_deploy.yml
Queuing PRs should help keep the log linear, tidy and prevent statefile locking issues in deploys.
> Configure merge queues

- .github/workflows/aks_deploy.yml
The concurrency setting in GitHub workflows will cancel a run when another run in the same group occurs. The group was set to `github.ref` but this appears to cancel the deployment on main before it finishes when queues are enabled.
This is because while the first branch is being deployed, the second branch's tests are running and then when they complete *it* is deployed. But, because the second branch's build is shorter (it runs the tests/lint but doesn't deploy anything) - it's merged _before_ the first branch has reached `production`/`migration`/`sandbox` and cancels their deploy 🤦🏽‍♂️  
Instead if we use `github.head_ref || github.run_id` the cancellation [should only happen within the context of pull requests or retries](https://docs.github.com/en/actions/learn-github-actions/contexts …
> Change concurrency group to head_ref then run_id

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Jira-2811](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2811)
We have a use case where we only want to migrate declarations from one statement to another for a particular lead provider.
- Allow restricting by provider on declaration migration
Screenshots of migration ran on snapshot DB are in the Jira ticket.
> Allow restricting by provider on declaration migration

- app/jobs/set_participant_completion_date_job.rb
- app/services/participants/build_completion_candidate_list.rb
- config/sidekiq_cron_schedule.yml
- spec/services/participants/build_completion_candidate_list_spec.rb
We currently have a job that runs daily overnight to check DQT for new ECT completion dates. This checks all ECTs registered before 2023 who don't already have a completion date (c. 36,000 ECTs).
There is a limit on the DQT API, which means it has to be run several times throughout the night, and with such a long list of people to check, there is a risk that we aren't getting through everyone each time. We also need to add in 2023 ppts which will increase the list further (c. 60,000).
For checking new induction starts, we currently have a weekly job that runs on a Monday morning.
We wanted to consider ways to improve the approach to checking for ECT completions, to ensure the full list is checked and up to date without risking the job being shut down for taking too long.
We considered …
> CST-2300: re-schedule jobs to update induction completion dates

- app/services/archive/destroy_ecf_profile_data.rb
For some data I'm attempting to archive the code is failing to remove the `User` record because `ParticipantDeclaration` records exist and it causes a foreign key exception. Having checked the data on some of those, this should not be happening as we are destroying those records. I think it is quietly failing in the `.destroy_all` for some reason so am switching to iterating over the collections and using `.destroy!` instead to try and get to the bottom of it. 
Replace `.destroy_all` with `.each(&:destroy!)` in the profile destruction service
> Archiving cleanup - Using destroy_all does not always seem to work so switching to destroy!

- app/models/ecf_participant_eligibility.rb
- app/models/participant_profile/ect.rb
- app/queries/ects/with_an_appropriate_body_and_unregistered_query.rb
- app/queries/ects/without_an_appropriate_body_and_unregistered_query.rb
- spec/factories/seeds/ecf_participant_eligibility_factory.rb
- spec/models/ecf_participant_eligibility_spec.rb
- spec/queries/ects/with_an_appropriate_body_and_unregistered_query_spec.rb
- spec/queries/ects/without_an_appropriate_body_and_unregistered_query_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
In a recent chaser email to schools it was noticed in support that some participants did not have QTS. This fixes the queries so that they do not include participants that have other eligibility issues.
Check the `ECFParticipantEligibility` record for other flags and only include those that have no induction
> [Bug-Fix] Modify queries to exclude ineligible ppts from chaser email

- app/forms/admin/schools/cohorts/appropriate_bodies/update_form.rb
- app/models/concerns/gias_types.rb
- config/analytics.yml
- db/migrate/20240226135601_add_listed_for_school_type_codes_to_appropriate_bodies.rb
- db/schema.rb
- spec/factories/appropriate_bodies.rb
- spec/factories/school.rb
- spec/features/admin/schools/changing_appropriate_bodies_spec.rb
- Ticket: CST-2360
Given that not every Appropriate Body (AB) supports all school type codes, it's essential to tailor the AB options displayed to School Induction Tutors (SITs) or Admins during the AB selection process for a school's induction programme.
IStip is an example that only supports independent schools.
- Introduce a new attribute in the Appropriate Body model to specify the supported school type codes, with a default setting of an empty array.
- Ensure only ABs compatible with a school's type code are shown as options when an SIT or Admin selects an AB for an induction programme.
> [CST-2360] Enhance AB selection based on School Type Codes

- app/services/archive/destroy_ecf_profile_data.rb
Still trying to fix issues deleting child records of participant profile during archiving. Attempting to wrap those in a `no_touching` block to prevent callbacks or analytics being triggered as these may be the issue. 
Prevent analytics and callbacks to try and avoid fkey errors when deleting the user record.
> [Archiving] Use no_touching for the bulk of the destruction

- app/services/archive/destroy_ecf_profile_data.rb
- app/services/archive/unvalidated_user.rb
- spec/services/archive/unvalidated_user_spec.rb
Got to the bottom of the issues with deleting users during the archival. When the user has a mentor profile it is possible that that may be associated with declarations belonging to ECTs.  This PR adds a check for this in the `Archive::UnvalidatedUser` service and also destroys the child records of declarations explicitly.
> [Archiving] Check for presence of declarations where user is mentor_user

- app/models/user.rb
- app/services/identity/primary_user.rb
- app/services/oneoffs/transfer_away_from_archived_users.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/services/identity/primary_user_spec.rb
- spec/services/oneoffs/transfer_away_from_archived_users_spec.rb
[Jira-2797](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-2797)
Due to a bug where the `TeacherProfile.trn` was not being cleared on archiving the associated user (#4524) we now have a number of archived users with associated participant profiles.
As of #4524 we now nullify the `TeacherProfile.trn` on archiving, so all that remains is to archived users onto the correct primary user record.
- Add script to transfer away from archived users
The dry-run output of the script running against the snapshot DB is on the Jira ticket; all but 5 users can be fixed.
Branches off #4522
> Add script to transfer away from archived users

- app/services/oneoffs/fix_participant_declaration_user.rb
- spec/services/oneoffs/fix_participant_declaration_user_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2799
* Created `Oneoffs::FixParticipantDeclarationUser` with tests
* There are total 7208 declarations
* 81 declarations have a `declaration.participant_identities.size > 1`
* 47 declarations have `declaration.user.id` that does not match `declaration.participant_profile.user.participant_identities.user_id`
> [CPDLP-2799] Fix declarations to point to correct user

- app/serializers/api/v3/ecf/participant_serializer.rb
- docs/source/ecf/guidance.html.md
- docs/source/release-notes.html.md
- spec/docs/v3/ecf_participants_spec.rb
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFEnrolment.yml
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2836
We would like to start capturing completion of mentor training, and surfacing this data in the API for providers.
Add new field called `mentor_funding_end_date` in the participant ECF endpoint in API v3 only.
> [CPDLP-2836] Surface mentor completed field in ECF participants API v3 endpoint

- Gemfile
- Gemfile.lock
This reverts commit 61a3faa5a7fa658fd834c53ed93fdcef950e1dc2.
The dfe-analytics started failing after upgrading to the latest version. 
I'm reverting it back to the prev version until we figure out the issue.
> Revert "Bump dfe-analytics from v1.11.7 to v1.12.0"

- app/serializers/api/v3/ecf/participant_serializer.rb
- docs/source/release-notes.html.md
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
[Jira-2874](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-2874)
Release the `mentor_funding_end_date` field in the `ParticipantSerializer` to production and add a release note.
> Release mentor_funding_end_date to production

- app/mailers/school_mailer.rb
- app/queries/schools/pre_term_reminder_to_report_any_changes_query.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/mailers/school_mailer_spec.rb
- spec/queries/schools/pre_term_reminder_to_report_any_changes_query_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: CST-2366
We want to send pre-term comms to SITs in eligible schools that are running FIP or CIP programmes in 2023/24 cohort, to remind them to report any changes.
- Add the mailer for the Notify template that will be sent
- Add a query class to return all the schools that need to be contacted
- Add a bulk mailer to trigger the emails
> [CST-2366] Add pre-term reminder comms

- Gemfile
- Gemfile.lock
- db/migrate/20230919093921_add_primary_key_to_cohorts_lead_providers.rb
Reverts DFE-Digital/early-careers-framework#4624
Disables new [strong migration check](https://github.com/ankane/strong_migrations/tree/537c5543feb5c7ecbf57075167a90e7992a1def9?tab=readme-ov-file#adding-an-auto-incrementing-column) for old migrations introducing a primary key to an existing table.
> Bump strong_migrations from 1.7.0 to 1.8.0

- app/views/schools/participants/edit_mentor.html.erb
Fix a recurring sentry error, looks like this was introduced recently during the split into ECT and Mentor "tabs"
Look up the `ParticipantProfile` to pass in to the helper instead of passing the `id`
> [Bug-fix] Look up from_mentor object to pass to helper not the id

- Makefile
- Ticket: N/A
Use new namespace option when connecting to konduit
- Request PIM for group `s189 CPD production PIM`
- Run: `rm -f bin/konduit.sh && make install-konduit`
- Edit `bin/konduit.sh` and add back `echo "$DB_URL"` into `run_psql()` function as per below:
```
run_psql() {
if [ "$Inputfile" = "" ]; then
echo "$DB_URL"
psql -d "$DB_URL" --no-password "${OTHERARGS}"
elif [ "$CompressedInput" = "" ]; then
echo "$DB_URL"
psql -d "$DB_URL" --no-password <"$Inputfile"
else
echo "$DB_URL"
gzip -d --to-stdout "${Inputfile}" | psql -d "$DB_URL" --no-password
fi
}
```
- Connect as usual to snapshot db `make ci production konduit-snapshot`
- Spin up `rails s`
> Use new namespace option when connecting to konduit

- app/controllers/schools/participants_controller.rb
The feature to change the mentor of an ECT is creating useless induction records similar to the previous one when the SIT decides to assign the same mentor again.
- Ticket:
> Changing an ECT mentor: do not add induction record when the mentor profile remains the same

- app/views/schools/mentors/_mentoring.html.erb
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2439): 
Mentor profile page: check if the mentor is induction-withdrawn and if so, do not show the link to add them ECTs.
> CST-2439: adding an ECT to a withdrawn mentor is not allowed to SITs

- app/services/npq/application/accept.rb
- spec/services/npq/application/accept_spec.rb
- Ticket: [CPDLP-2849](https://dfedigital.atlassian.net/browse/CPDLP-2849)
TDT have flagged that they were not able to submit a start declaration for this participant. The user has two accepted applications for the same course with different lead providers. Our service should not allow this to happen.
Fix bug when accepting a NPQ application where another for the same course has already been accepted.
[CPDLP-2849]: https://dfedigital.atlassian.net/browse/CPDLP-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2849] Fix bug when accepting a NPQ application where another for the same course has already been accepted

- app/models/npq_applications/eligibility_import.rb
We're already checking for the presence of users elsewhere and this validation crashes when the user is `nil`.
> Make the user is admin validation more robust

- app/models/induction_record.rb
- app/models/school.rb
- app/presenters/admin/participant_presenter.rb
- app/services/dashboard/participants.rb
- spec/services/dashboard/participants_spec.rb
The current participants dashboard is not listing properly all the participants.
For instance, when a participant has been moved from one provider to another in the same school and the first provider training-withdraw that participant, the dashboard is displaying it as no longer training when actually the participant is actively training with the new provider.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2450)
Fix the query that retrieves the latest induction record of the school participants.
> CST-2450: pick the latest induction records to display the dashboard

- app/services/support/base_service.rb
- app/services/support/participants/reactivate.rb
- lib/tasks/support/participants.rake
- spec/services/support/participants/reactivate_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CST-2383
- Adds rake task for reactivating profiles
```
rails "support:participants:reactivate:run[12345]"
I, []  INFO -- : Updating training_status and induction_status for ParticipantProfile#12345 to active
I, []  INFO -- : Induction Record - training_status: active
I, []  INFO -- : Induction Record - induction_status: active
I, []  INFO -- : Participant Profile - status: active
I, []  INFO -- : Participant Profile - training_status: active
```
> [CST-2383] Add rake task to reactivate a participant profile

- app/services/importers/create_cohort.rb
- app/services/importers/create_npq_contract.rb
- db/data/npq_contracts/fake-2021.csv
- db/data/npq_contracts/fake-2022.csv
- db/data/npq_contracts/fake-2023.csv
- spec/fixtures/files/importers/cohort_csv_data.csv
- spec/services/importers/create_cohort_spec.rb
- spec/services/importers/create_new_npq_cohort_spec.rb
- spec/services/importers/create_npq_contract_spec.rb
We have a new field `automatic_assignment_period_end_date` on Cohort that we want to allow in the CSV and default to the 31st March of the following year (relative to the `start_year` of the Cohort).
The NPQ Contract also has a new `monthly_service_fee` field; this was already defaulting to `0.0` in the import script, but this will also allow it to be added as part of the CSV.
- Update import scripts for cohort/npq contract
> Update import scripts for cohort/npq contract

- app/controllers/api/v1/npq_profiles_controller.rb
Permit the following fields in the ecf app
- primary_establishment
- number_of_pupils
- tsf_primary_plus_eligibility
https://dfedigital.atlassian.net/browse/CPDNPQ-1735
By allowing to update these fields, we will be able to populate additional info. Also, we would need to backfill data for historic records and there will be a job to carry out that part.
> CPDNPQ-1735 Permit fields in the ecf app

- app/models/participant_profile/mentor.rb
When discussion feasibility of implementing rule 3 for completed mentors, Nathan requested that we amend the reason name to "started not completed" for rule 3 and removed rule 4 as it was not going to be implemented.
Update the `mentor_completion_reason` enum to reflect the requested changes.
> Update mentor completion reason values

- Gemfile.lock
- app/mailers/school_mailer.rb
Minor change to be able to pass gias contacts to the mailer.
- Ticket: [Send comms to GIAS contacts for schools we failed to contact in March](https://dfedigital.atlassian.net/browse/CST-2467)
> CST-2467: add gias contact params to mailer

- db/seeds.rb
We appear to be needlessly seeding the test database and then ignoring and generating new data when we run the tests. This came to light when we noticed tests failing when the test database had been populated via `rails db:setup` but passing when it'd just been created with `rails db:create`.
This change just skips seeding when the Rails environment is `test`.
> Don't seed the test database

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
Upgrade to [latest version of govuk-frontend](https://github.com/alphagov/govuk-frontend/releases/tag/v5.3.1) and bump components and form builder gems.
Fixes #4725, #4729, #4730
- **Upgrade to govuk-frontend 5.3.1**
- **Upgrade to latest form builder and components**
> Upgrade to govuk-frontend 5.3.1

- app/controllers/api/v3/npq_applications_controller.rb
- app/serializers/api/v3/npq_application_serializer.rb
- app/services/feature_flag.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/serializers/api/v3/npq_application_serializer_spec.rb
- spec/services/npq/application/accept_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3013
We added a feature flag accept_npq_application_can_change_schedule to allow providers to change schedule when accepting applications. This feature is/will be permanently turned on now. So there's no need for the feature flag.
- Remove `accept_npq_application_can_change_schedule` feature flag
- Remove feature flag from serializer
- Remove feature flag from specs
Note:
- Run `Feature.find_by_name(:accept_npq_application_can_change_schedule).destroy` in every env after this is merged/deployed.
> [CPDLP-3013] Remove `accept_npq_application_can_change_schedule` feature flag

- Dockerfile
Recent changes (maybe Rails 7.1) have resulted in issues with paging in the rails console. The output is paged but not syntax coloured and multi-page output history is lost once the pager is exited.
If we specify `more` as the pager, sanity is restored.
Set the shell history "helper" with the environment var `PAGER=more` before invoking the rails console
> Specify more as the PAGER

- app/queries/schools/that_have_not_added_participants_query.rb
- spec/queries/schools/that_have_not_added_participants_query_spec.rb
- Ticket: [CST-2547](https://dfedigital.atlassian.net/browse/CST-2547)
Query that support the mailer was using `.missing` to find school cohorts that did not have induction records, however the hidden left joins underneath this with `induction_programmes` led to the inclusion of schools that had both empty and induction programmes with participants
Change the query to be more explicit in not selecting school cohorts that have induction programmes with induction records.
[CST-2547]: https://dfedigital.atlassian.net/browse/CST-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CST-2547] Fix query for schools that have not registered participants

- app/presenters/dqt_record_presenter.rb
- app/services/dqt_record_check.rb
- app/services/participants/check_and_set_completion_date.rb
- db/migrate/20240502102913_add_unique_index_to_participant_profile_start_date_inconsistencies.rb
- db/schema.rb
- spec/features/schools/participants/add_participants/add_ect_with_appropriate_body_spec.rb
- spec/features/schools/participants/add_participants/add_previously_withdrawn_ect_spec.rb
- spec/features/schools/participants/add_participants/add_previously_withdrawn_mentor_spec.rb
- spec/features/schools/participants/add_participants/reporting_participants_with_trn_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/allow_withdrawn_participant_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/ect_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_different_partner_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/mentor_no_change_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/requests/admin/participants/validate_details_spec.rb
- spec/services/participant_validation_service_spec.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
- spec/support/features/pages/participant/participant_registration_wizard.rb
- spec/support/features/steps/changes_of_circumstance_steps.rb
DQT records provide 2 ways to extract the induction start date of a participant:
“startDate” field in the “induction” section of the record
minimum “startDate” of the “periods” section in the “induction” section of the record.
Our service always has gone for 1. It seems the most accurate date is provided by 2. 
This ticket is about changing our code from 1. to 2. whenever we check DQT for a participant induction start date throughout the whole codebase.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2540)
- Update `Participants::CheckAndSetCompletionDate` to get the DQT induction start date of a participant from the earliest `startDate` of the `induction` `periods` 
- Temporary workround (until we migrate this SO to DQT::V3) on `DQTRecordPresenter` to call V3 to pick the induction …
> CST-2540: get induction start date from DQT induction periods

- config/initializers/paper_trail.rb
- Ticket: N/A
We are currently generating numerous unnecessary version records with `object_changes: nil`, which do not provide any real value. 
By excluding records on `:touch` events, we will enhance the visibility of significant changes and reduce the overall number of version records.
- Add global config in the PaperTrail initializer to exclude :touch events
> Avoid creating papertrail records on touch

- .rubocop.yml
- app/controllers/healthcheck_controller.rb
- spec/requests/healthcheck_spec.rb
To allow the migraiton environment database to be restored from production there will be a certain amount of time the database is empty. Keeping the healthcheck happy means we can keep the refresh going as otherwise the pipeline will be broken since we rely on the migration web container to be up and healthy.
This work is similar to NPQ thanks @ethax-ross 
https://github.com/DFE-Digital/npq-registration/pull/1283
- Ticket: n/a
- Amend healthcheck to ignore migration environment on db populated check
- Add specs for healthcheck
> Amend healthcheck to not fail if database not populated

- app/controllers/healthcheck_controller.rb
- spec/requests/healthcheck_spec.rb
- Ticket: n/a
Previous fix allowed the health check to return healthy if database not populated in the migration env. However this means the smoke test fails.
- Allow the database populated check to return true in the migration env to avoid smoke test failure
- Beef up specs for all of healthcheck and stop being lazy
> Show database as populated in migration regardless of check

- .github/actions/refresh-migration-database/action.yml
- terraform/aks/workspace_variables/migration_aks.tfvars.json
Our migration env db refresh is hitting 100% CPU due to large tables, exclude largest tables from `pg_dump` to avoid this
- Ticket: n/a
Exclude versions and api request tables from pg dump on migration db refresh from prod
This is a theory we would like to test
> Exclude large tables from migration snapshot refresh

- README.md
- app/services/dqt_record_check.rb
- Ticket: [CPDLP-3000](https://dfedigital.atlassian.net/browse/CPDLP-3000)
We'd like to create a magic date that providers and DfE users can create validated, eligible for funding mentors and ECT’s in the 2024 cohort.
Create magic dates to create validated ECT's and mentors in the 2024 cohort.
[CPDLP-3000]: https://dfedigital.atlassian.net/browse/CPDLP-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3000] Create magic dates to create validated ECTs and mentors in the 2024 cohort

- app/assets/stylesheets/primary-nav.scss
Standard GOVUK focus styles are yellow background with dark text.
- Ticket:  https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CST/boards/119?selectedIssue=CST-2516
The primary nav styles specify white text but no modifier for focus so add these.
> Add focus styles to enhance contrast

- app/services/record_declaration.rb
- spec/factories/participant_declaration.rb
- spec/services/record_declaration_spec.rb
[Jira-3057](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3057)
We now have a `cohort` field on `ParticipantDeclaration`. We want to ensure all new declarations are stamped with the relevant cohort at the time of creation.
- Populate cohort on recording a declaration
We take the `participant_profile.schedule.cohort` as this is the one we use for validation.
We stamp the cohort _after_ find/creating the declaration so as not to break the existing find/create logic (for declarations already in the system that do not yet have the cohort set).
> Populate cohort on recording declaration

- app/models/concerns/gias_types.rb
A new school type code `57` has been added. It represents `Academy secure 16 to 19` and this type is eligible for funded FIP training.  We need to add them to the list of eligible type codes in order to allow these to be imported into the service from GIAS.
Add school type code `57` to the list of eligible type codes.
> Add new school type code to eligible code types

- config/locales/schools/cohorts/setup_wizard.yml
When a user submits the cohort setup wizard step "How will you run training..." without selecting a choice the error message is the default Rails _is not included in the list_ text.
- Ticket:  https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CST/boards/119?selectedIssue=CST-2515
Add a custom error message for the setup wizard.
> Add a custom error for cohort setup wizard

- app/forms/admin/school_transfer_form.rb
- config/locales/en.yml
- spec/forms/admin/school_transfer_form_spec.rb
Entering an invalid value into the school transfer start date results in an ArgumentError being raised to the controller level and a redirect with a generic flash error message. We should be handling this as a validation error.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CST/boards/119?selectedIssue=CST-2514
Handle ArgumentError gracefully
Provide an example date in the error message
> Handle school transfer start date ArgumentError gracefully

- app/views/schools/dashboard/_school_cohort_details.html.erb
- spec/features/schools/add_appropriate_body_spec.rb
On the "Manage your training," page the _add_ link to add an **Appropriate body** lacks detail in visual or hidden link text. Adding hidden text _appropriate body_ would provide more context to the user.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CST/boards/119?selectedIssue=CST-2515
Add _appropriate body_ hidden text to _Add_ link on AB summary list.
> Add visually hidden text to AB summary list actions

- app/services/mentors/check_training_completion.rb
- spec/services/mentors/check_training_completion_spec.rb
- Ticket: Part of [Jira](https://dfedigital.atlassian.net/browse/CST-2554) which has been merged.
- This updates the `Mentors::CheckTrainingCompletion` service to prevent overwriting a manually added "started not completed" completion when a `completed` declaration is received after 31st July.  Until that date a completed declaration should override the completion date and reason if it has been marked as a "started not completed" completion.
Adds logic to the completion check service.
> [CST-2554] (part 2) Allow completed declarations to overwrite started not completed declarations until 31st July.

- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- spec/factories/services/mentors/create.rb
- spec/models/participant_profile/ect_spec.rb
- spec/models/participant_profile/mentor_spec.rb
- spec/support/shared_examples/archivable_support.rb
[Jira-3061](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3061)
As part of the multi cohort work we want to archive participants in a 'closed' cohort (identified by being 3 years prior to the current cohort or earlier). They must have either no declarations or only unbillable (ineligible/voided/submitted) declarations.
- Add methods to identify archivable participants
Add a scope find archivable participant profiles and a method to check if a single profile can be archived.
Here are the numbers from production; just waiting on Nathan verifying these look correct and checking a few samples:
```
ECTs: 203
Mentors: 1,087
```
> Add methods to identify archivable participants

- config/environments/staging.rb
to help with testing declarations
- Ticket: n/a
To allow testing cohort 2024 in staging we need to allow setting the `X-With-Server-Date`. This allows creating declarations in the future
> Enable time travelling in the API in staging

- app/services/dqt_record_check.rb
Recently we changed the source where to pick induction start dates from DQT records from "induction", "start_date" to "induction", "periods", "startDate"
Magic dates need to get updated to the camelCase syntax coming from DQT V3.
- Ticket:
> faked induction periods on magic dates needs to stick to DQT V3 syntax

- terraform/application/terraform.tf
- terraform/custom_domains/environment_domains/terraform.tf
- terraform/custom_domains/infrastructure/terraform.tf
We're fetching the latest version of `azurerm 3.105.0` which is now defaulting `public_network_access_enabled` from false to true.
`public_network_access_enabled = false -> true`
https://github.com/DFE-Digital/early-careers-framework/actions/runs/9222398909/job/25374325095
We need to pin/fix the version to the previous version `3.104.2` for now.
Ideally we'd need to set the variable as false in module https://github.com/DFE-Digital/terraform-modules/blob/main/aks/postgres/resources.tf#L39 but that'd cause many projects to get upgraded.
> Pin azurerm version to 3.104.2 as the latest 3.105.0 version made the build to fail

- app/models/cohort.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- spec/models/participant_profile/ect_spec.rb
- spec/models/participant_profile/mentor_spec.rb
- spec/support/shared_examples/archivable_support.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
When these methods were initially written we assumed that if a cohort was 3 years older than the current/latest cohort it could be considered 'closed'.
The schools team have since added a dedicated flag to `Cohort` to indicate that it is closed/has had payments frozen that we want to utilise instead.
- Update cohort change logic to use payments_frozen_at field
Update the `eligible_to_change_cohort_and_continue_training` and `archivable` methods to use this flag instead of the 3 years previous logic.
Re-tested on snapshot DB:
```
Cohort.find_by(start_year: 2021).update!(payments_frozen_at: Time.zone.now)
ParticipantProfile::ECT.eligible_to_change_cohort_and_continue_training.count
=> 3176
ParticipantProfile::Mentor.eligible_to_change_cohort_and_continue_training.count
=> 10248 …
```
> Update cohort change logic to use payments_frozen_at field

- app/serializers/finance/npq/assurance_report/csv_serializer.rb
- app/services/finance/npq/assurance_report/query.rb
- spec/serializers/finance/npq/assurance_report/csv_serializer_spec.rb
- spec/services/finance/npq/assurance_report/query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2955
Within the financial statements, we have the functionality for assurance to ‘download declarations’. The download declarations query pulls together multiple bits of information regarding the participants declarations. 
This PR adds ‘funded_place’ added as an additional field to the query.
> Finance app: add funded_place to assurance CSV report

- app/helpers/admin_helper.rb
- app/presenters/admin/participant_presenter.rb
- spec/presenters/admin/participant_presenter_spec.rb
[Jira-3140](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3140)
We want it to be clear in the admin dashboard participants view when a participant has migrated from a cohort due to the payments being frozen.
- Expose multi cohort in admin dashboard
| No cohort change    | Cohort change | Cohort change (edge case) |
| -------- | ------- | --------- |
| <img width="1202" alt="Screenshot 2024-05-29 at 09 38 14" src="https://github.com/DFE-Digital/early-careers-framework/assets/29867726/b07cd535-15c4-406c-a97f-1efce768ce5b"> | <img width="1202" alt="Screenshot 2024-05-29 at 09 39 00" src="https://github.com/DFE-Digital/early-careers-framework/assets/29867726/8d182363-04c3-4150-82b4-ca1e …
> Flag multi cohort participants in admin dashboard

- spec/rails_helper.rb
- spec/support/features/steps/generic_page_object_steps.rb
We get a lot of `puts` messages about calls to missing page object methods which write to stdout.
- Ticket: 
Instead of filling stdout with messages about these missing page object method calls, log them in a file per RSpec suite run.
> Write use of `method_missing` in page objects helper to file

- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- app/services/change_schedule.rb
- spec/services/change_schedule_spec.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
We want to allow ECTs and mentors to change schedule/cohort even if they have billable declarations under certain scenarios.
The participants eligible are identified by `eligible_to_change_cohort_and_continue_training`.
Participants that change cohort using this mechanism should be able to change back to their original cohort providing no billable declarations were created against the new cohort.
- Relax validation on ChangeSchedule service for certain participants 
By default the service will not allow eligible participants to transfer; it needs to be called explicitly with `attempt_to_transfer_leaving_billable_declarations` set to `true`. This is to prevent lead providers performing these changes for now.
A participant will be able to transfer if:
- …
> Relax validation on ChangeSchedule service for certain participants 

- spec/services/change_schedule_spec.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
The `change_cohort_and_continue_training_support` specs were failing due to the milestone date and start date being set to the same value when we're at the end of the month. Updating the spec to use the `start_date` rather than adding `1.day` fixes it (as its greater than or equal to).
The cohort changed error message had changed in `main` since the change schedule for multi cohorts PR was raised and it was failing after being merged; this updates the error message to match.
> Fix broken specs in main

- app/forms/schools/add_participants/wizard_steps/start_date_step.rb
- app/models/cohort.rb
- app/models/participant_profile/ecf.rb
- app/services/participant_validation_service.rb
- app/services/participants/sync_dqt_induction_start_date.rb
We (re)declare this significant date throughout the codebase, it refers to the start date of the initial cohort. Using a constant would clarify that.
- Ticket: 
Use a constant instead of repeatedly re-declaring this date.
> Make initial cohort start date a constant

- app/presenters/dqt_record_presenter.rb
- app/services/dqt/get_induction_record.rb
- app/services/dqt_record_check.rb
- config/initializers/dqt.rb
- lib/dqt.rb
- lib/dqt/v1/client.rb
- lib/dqt/v3/client.rb
- lib/full_dqt.rb
- spec/lib/dqt/v1/client_spec.rb
- spec/lib/dqt/v3/client_spec.rb
- spec/services/dqt/get_induction_record_spec.rb
- spec/services/dqt_record_check_spec.rb
- spec/services/participant_validation_service_spec.rb
[We've removed the old `DQT` module code](https://github.com/DFE-Digital/early-careers-framework/pull/4791), so `FullDQT` can be renamed `DQT`
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CST/boards/119?selectedIssue=CST-2546
Rename `FullDQT` to `DQT` and update references.
> Rename `FullDQT` to `DQT`

- app/serializers/api/v1/npq_application_csv_serializer.rb
- app/serializers/api/v2/npq_application_csv_serializer.rb
- app/serializers/api/v2/npq_enrolments_csv_serializer.rb
- spec/factories/services/npq/npq_application.rb
- spec/serializers/api/v1/npq_application_csv_serializer_spec.rb
- spec/serializers/api/v2/npq_application_csv_serializer_spec.rb
- spec/serializers/api/v2/npq_enrolments_csv_serializer_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3128
The new funded place field has been added to the NPQ application serialiser but needs adding to the csv NPQ application serialiser
> NPQ capping update the npq csv serialiser to surface funded place

- app/components/admin/npq/participants/details.html.erb
- app/components/admin/npq/participants/details.rb
- app/helpers/application_helper.rb
- app/views/admin/npq/applications/_funding_eligibility.html.erb
- app/views/admin/npq/applications/edge_cases/show.html.erb
- app/views/finance/participants/_npq_application.html.erb
- spec/components/admin/npq/participants/details_spec.rb
- spec/factories/services/npq/npq_application.rb
- spec/features/admin/npq_applications/change_logs_spec.rb
- spec/features/admin/npq_applications/npq_applications_spec.rb
- spec/features/admin/npq_applications/participant_details_spec.rb
- spec/features/finance/npq/participant_details_spec.rb
- spec/helpers/application_helper_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-2954
To help internal users identify if a participant is allocated to a funded place after an application is accepted we need to introduce funded place to the UI for both the admin and finance app.
> Add npq capping to Admin and Finance

- app/forms/schools/add_participants/base_wizard.rb
- app/models/participant_profile/ecf.rb
- app/services/induction/enrol.rb
- app/services/induction/transfer_and_continue_existing_fip.rb
- app/services/induction/transfer_to_schools_programme.rb
- spec/services/induction/enrol_spec.rb
As part of the journey that allows a SIT to transfer an (already registered at a different school) ECT to their school there is some logic behind the scenes that keeps the ECT in the cohort they are already sitting.
We need to extend that logic to sit in 2024/25 cohort a transferring ECT currently sitting in 2021/22 cohort and not having completed induction.
Those with completed induction will be transferred school (not cohort) but there status should not be set to active but completed.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2559):
> CST-2559: closing 2021 - transfer ect journey - take into account 2021 closing in cohort determination logic

- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
A declaration creation will fail if the milestone date is in the past due to validations. Set the milestone date in the future
- Ticket: n/a
Set milestone date to always be in the future to avoid failures on dates changing and massing May
> Set milestone date in the future

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/environments/sandbox.rb
- config/environments/staging.rb
We're about to start shipping logs to logit.io again so want to change the log format to JSON with the Rails semantic Logger.
To ease development this PR also introduces amazing_print which colourises the logs in development.
- **Remove logstash/lograge and associated config**
- **Add rails_semantic_logger and amazing_print gems**
- **Configure semantic logging in production**
Running ECF in production with `RAILS_LOG_TO_STDOUT=1 RAILS_ENV=production`
```
~/p/d/c/ecf (enable-semantic-logging) (✚4)
❯ RAILS_LOG_TO_STDOUT=1 RAILS_ENV=production be rails s
=> Booting Puma
=> Rails 7.1.3.2 application starting in production
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.8 (ruby 3.2.2-p53) ("Birdie's Version")
*  Min threads: 5
* …
```
> Add and configure `rails_semantic_logger`

- app/models/npq_application.rb
- app/models/participant_profile/npq.rb
- app/services/api/v3/npq_applications_query.rb
- app/services/npq/funding_eligibility.rb
- spec/models/npq_application_spec.rb
- spec/models/participant_profile/npq_spec.rb
- spec/services/api/v3/npq_applications_query_spec.rb
- spec/services/npq/funding_eligibility_spec.rb
- spec/services/record_declaration_spec.rb
We've introduced funded place to funding eligibility for NPQ from 2024 going forward. Previously we only calculated eligibility for declarations using `eligible_for_funding`. This looked into previously funded applications with the field set to true or the field itself.
We now have to account for `funded_place` as well. If it's not set we default to the `eligible_for_funding`. If it's set, then it is the deciding factor if the application is eligible for funding.
`eligible_for_dfe_funding` is used in the API and the record declaration logic, so we have to distinguish when we want to factor in the funded place logic as well. However previously funded is always included.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3077
- …
> [CPLD-3077] Update Eligibility logic to include funded place

- db/data/npq_contracts/fake-2024.csv
Senco contract data was added in https://github.com/DFE-Digital/early-careers-framework/pull/4779/ but was removed from db/data/npq_contracts/fake-2024.csv during a rebase and merge. This PR re-adds it again.
> Re-added senco data to npq contracts

- spec/rails_helper.rb
The singular fixture_path is now deprecated, use `#fixture_paths` and set an array instead.
https://github.com/rspec/rspec-rails/blob/main/lib/rspec/rails/configuration.rb#L167
> Set `config.fixture_paths` instead of `config.fixture_path`

- app/services/admin/participants/change_induction_start_date.rb
- spec/services/admin/participants/change_induction_start_date_spec.rb
There is an admin functionality to change induction start date of a participant.
We need to review this code to accomodate it to the closing 21 cohort scenario.
Similar to what we do for the re-validation in admin console.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2571):
> CST-2571: closing 2021 - change induction start date - include 2021 closing logic to sit the participant in 2024 cohort

- app/services/change_schedule.rb
- spec/services/change_schedule_spec.rb
The validation rule calls `npq_applications`, which doesn't exist for ECF participants; we only want to apply it to NPQ participants.
> Disable NPQ capping validation for ECF in ChangeSchedule

- app/controllers/admin/performance/overview_controller.rb
- app/views/admin/performance/overview/show.html.erb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2438)
- Update admin summary stats so we can see registration process for the 2024 cohort.
- Make the code use the `Cohort.active_registration_cohort` instead of a hard coded year.
Update to summary and views to use `Cohort.active_registration_cohort`
> [CST-2438] Update admin registration summary for 2024

- app/models/cohort.rb
- app/models/participant_profile/ecf.rb
- app/presenters/admin/participant_presenter.rb
- app/serializers/api/v3/ecf/participant_serializer.rb
- app/services/feature_flag.rb
- spec/factories/cohorts.rb
- spec/models/cohort_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/presenters/admin/participant_presenter_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- spec/support/shared_examples/archivable_support.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
[Jira-3145](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3145)
When a participant is migrated from a payments frozen cohort, we want to expose this to lead providers in the participant response so that they can identify them.
- Expose previous, frozen cohort to lead providers
Add `previous_payments_frozen_cohort` field to participant serializers that will be `nil` if the participant has not migrated cohort due to payments being frozen and will be the cohort start year of the frozen cohort if they have been migrated.
- Update ParticipantPresenter to use previous_payments_frozen_cohort
This was added for the serializers and we may as well use it here as well. It also contains an …
> Flag multi cohort participants to providers

- app/forms/admin/participants/change_relationship/change_relationship_wizard.rb
- app/views/admin/participants/change_relationship/relationship_already_exists.html.erb
- Ticket: N/A
Enhance context for displaying the "This relationship already exists" page when Admins attempt to change participants' LP/DP in an already existing and challenged partnership.
- Added the challenged date and challenge reason to the view
|![Screenshot from 2024-06-05 13-42-46](https://github.com/DFE-Digital/early-careers-framework/assets/951947/1faa48c9-4f36-4656-b7e9-611c92618832)|![Screenshot from 2024-06-05 14-21-04](https://github.com/DFE-Digital/early-careers-framework/assets/951947/0e50eb06-3930-4038-baec-1fa5f7700c1e)|
> Show reason for challenge to admins when partnership already exists

- config/environments/production.rb
- lib/semantic_logger/formatters/json_with_api_metadata.rb
This may or may not be entirely correct, but I _think_ it's doing the right thing. Need help from an @lead-provider-cpd person to make sure.
```ruby
config.active_record.logger = nil # Don't log SQL in production
```
> Add the custom API related fields to log output

- config/environments/migration.rb
We need this to be able to test some of the declaration scenarios.
> Add X-With-Server-Date header support to migration env

- .github/workflows/deploy.yml
We want to manually deploy a specific branch to the migration environment so that we can perform testing ahead of the multi cohort rollout.
> Disable deployments to migration environment

- app/services/finance/clawback_declaration.rb
- app/services/record_declaration.rb
- config/locales/en.yml
- spec/factories/participant_declaration.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/finance/clawback_declaration_spec.rb
- spec/services/record_declaration_spec.rb
[Jira-3142](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3142)
Currently, if we attempt to attach a declaration when there are no output fee statements available it will result in a 500 error. Instead, we want to surface a helpful error message to lead providers encountering this scenario.
- Ensure next output fee statement exists when attaching declaration
Update `RecordDeclaration` and `ClawbackDeclaration` to ensure the next output fee statement exists. 
Originally I tried to add this validation to the `StatementAttacher` and bubble it up from there, but we can't do that without a substantial refactoring due it being called _after_ the `RecordDeclaration` validation as part of …
> Ensure next output fee statement exists when attaching declaration

- app/services/finance/clawback_declaration.rb
- app/services/finance/declaration_statement_attacher.rb
- spec/services/finance/clawback_declaration_spec.rb
- spec/services/finance/declaration_statement_attacher_spec.rb
- spec/services/finance/npq/statement_calculator_spec.rb
- spec/services/void_participant_declaration_spec.rb
[Jira-3171](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3171)
Currently, we look to the latest induction record for the lead provider to find the cohort when attaching a declaration to a statement. This is no longer correct for participants that have declarations in 2021 and have since been moved to 2024. It would result in the declaration being voided against a 2024 statement instead of the original 2021 statement.
To correct this behaviour we can take the `declaration.cohort` when attaching to a statement, which will always be the cohort that the declaration was initially created in.
- Use declaration cohort when attaching to statement
We have made changes to ensure we retain …
> Use declaration cohort when attaching to statement

- app/models/cohort.rb
- spec/models/cohort_spec.rb
To avoid manually doing it the day we open a new registration year, we are going to determine if a Cohort has been frozen or not based on the date store in the database.
So when the time setup comes, the service will automatically detect the new status of the cohort and enable all the dependant features.
Redefine the logic in `Cohort#payments_frozen?`
> New way to determine when a cohort has been frozen

- app/views/schools/add_participants/complete.html.erb
- app/views/schools/add_participants/eligibility_confirmation/_appropriate_body_guidance.html.erb
- app/views/schools/add_participants/eligibility_confirmation/_post_transitional.html.erb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CST-2611
Add panel body text and a paragraph with link to guidance on appointing an appropriate body.
> Add new content to ECT confirmation screen

- app/services/api/v3/npq_participants_query.rb
- docs/source/release-notes.html.md
- spec/requests/api/v3/npq_participants_spec.rb
- spec/services/api/v3/npq_participants_query_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3182
Currently the default sorting looks into the nested `npq_profiles` created at timestamp. Without pagination this works ok, however with pagination, pagy includes the timestamp on the profiles in the limit/offset distinct query, which means that if a user has multiple profiles with different timestamps we return duplicate ids instead of the real ids for users.
Instead sort by user created at to avoid any timestamps being included in the pagy queries when calculating which ids to offset and return.
The test fails with the previous sorting but doesn't with the current one.
Amend the sorting on the participants npq query to look at users rather than npq profiles nested model. This ensures that we do not include the timestamp …
> Amend sorting in NPQ participants query

- app/views/nominations/nominate_induction_coordinator/check.html.erb
- app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb
- app/views/nominations/nominate_induction_coordinator/start_nomination.html.erb
- spec/features/induction_nomination_spec.rb
- spec/features/nominations/nominate_induction_tutor_journey_spec.rb
- spec/features/nominations/nominate_induction_tutor_steps.rb
- Ticket: CST-2582
A few content changes in the nomination journey.
- Updated the content according to the provided designs
|<img width="651" alt="Screenshot 2024-06-13 at 15 12 44" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/965c65ef-c155-4e3f-974a-71e6aeaf4293">|<img width="645" alt="Screenshot 2024-06-13 at 15 12 33" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/a426b977-547d-4028-8869-3393bbce7e52">|
|<img width="653" alt="Screenshot 2024-06-13 at 15 13 30" src="https://github.com/DFE-Digital/early-careers-framework/assets/951947/ac9165c6-c6ea-4968-b3da-85dfeaa34f42">|<img width="653" alt="Screenshot 2024-06-13 at 15 13 40" src="https://github.com/DFE-Digital/early-careers-framework/assets/ …
> [CST-2582] Update the content on the nomination pages

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Jira-3169](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3169)
We want to migrate a number of declarations `awaiting_clawback` for SLN from one statement to another (payable) statement.
The current declaration migrator service does not support this as it:
- Is restricted to migrating only to future dated statements
- Will change the `output_fee` to `false` for all from statements
- Does not support migrating to paid/payable statements
We want to update the migration service to support the new scenario.
- Support filtering by states in MigrateDeclarationsBetweenStatements
We want the ability to only migrate a subset of declarations with a particular state or states.
- Relax …
> Support migrating declarations to paid/payable statements

- app/forms/admin/schools/cohorts/appropriate_bodies/update_form.rb
- app/views/admin/appropriate_bodies/users/edit.html.erb
- app/views/admin/appropriate_bodies/users/new.html.erb
- Spotted 2 places in the Admin UI that don't use the new `AppropriateBody.selectable_by_schools` scope to constrain the list of available ABs
Add `.selectable_by_schools` scope to AB queries
> Use selectable_by_schools scope for AB selection

- app/serializers/api/v3/ecf/participant_serializer.rb
- app/services/feature_flag.rb
- docs/source/release-notes.html.md
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
> ⚠️ Do not merge until 18th June.
[Jira-3146](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3146)
We have added the `cohort_changed_after_payments_frozen ` attribute to the participants API and it is currently enabled in the sandbox environment.
We want to enable this in production.
- Enable the multi cohort flag in production
Remove the feature flag to enable this attribute in production and include a new release note.
> Enable multi cohort flag in production API

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
They can at least see they don't have an association to any schools as the index page will be empty.
We are currently raising a Sentry error and not catching this case.
- Ticket:  https://dfedigital.atlassian.net.mcas.ms/browse/CST-2621
- Sentry error: https://dfe-teacher-services.sentry.io/issues/4486911502 there are currently ~550 errors like this
Check that the induction coordinator is associated to a school before attempting to return a school dashboard path. If they aren't redirect to the schools index.
> Redirect induction coordinator to schools index when they are not associated to any schools

- app/services/withdraw_participant.rb
- spec/services/withdraw_participant_spec.rb
We attempt to mail the induction coordinator for the participant's school when withdrawing them but in some instances this IC profile is nil.
We have around 50 errors in Sentry relating to this.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CST-2621
- Sentry error: https://dfe-teacher-services.sentry.io/issues/3023857336 
Don't attempt to send email when the induction coordinator (ie. the email recipient) is nil.
> Don't attempt to send mail to nil induction coordinator

- terraform/application/application.tf
- terraform/application/variables.tf
- terraform/application/workspace_variables/review.tfvars.json
- terraform/application/workspace_variables/staging.tfvars.json
Ticket: https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio
Enabling logit.io on non-prod environment , logs will appear on logitio.
Logitio logs for review apps : 
https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'8ac115c0-aac1-11e8-88ea-0383c11b333a',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8ac115c0-aac1-11e8-88ea-0383c11b333a',key:kubernetes.deployment.name,negate:!f,params:(query:cpd-ecf-review-4969-worker),type:phrase),query:(match_phrase:(kubernetes.deployment.name:cpd-ecf-review-4969-worker)))),query:(language:kuery,query:'' …
> logit.io enabled on non-prod environment

- config/initializers/devise.rb
- Ticket: N/A
```
`Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.
```
Fix deprecation message above.
Checked all credentials files all have `secret_key_base` set correctly.
> Fix `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` message

- spec/features/schools/participants/add_participants/payments_frozen/common_steps.rb
- spec/features/schools/participants/add_participants/payments_frozen/transfer_ect_to_another_school_spec.rb
- spec/features/schools/participants/add_participants/payments_frozen/transfer_mentor_to_another_school_spec.rb
Removes the need to [stub the `ParticipantProfile#eligible_to_*` method](https://github.com/DFE-Digital/early-careers-framework/pull/4955/files#diff-1e85d4c555e66843a491433bde0eb9f9ac33940f39aad02f5216f2ba9c3a9f0cL66) in payments frozen feature specs.
Supersedes https://github.com/DFE-Digital/early-careers-framework/pull/4913
- Ticket: 
Uses factory methods to create valid records for `ParticipantProfile#eligible_to_*` methods.
> Create a valid ParticipantDeclaration via factory methods

- config/initializers/sentry.rb
We have gtag related fetch errors in production which we can't really action.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CST-2621
- Sentry errors: https://dfe-teacher-services.sentry.io/issues/5506745977
Filter out failed JS fetch errors from Sentry.
See https://github.com/DFE-Digital/apply-for-qualified-teacher-status/commit/1dd0190309c326118ca017b1606b261e66f80105 for working implementation of how we access Sentry error descriptions to filter errors.
> Filter Sentry gtag errors

- spec/features/cookies_policy_page_spec.rb
- spec/support/features/steps/cookies_policy_steps.rb
- Ticket: CST-2519
This is part of the effort to move away from the GenericPageObjectSteps.
- Create explicit methods for each magic step in the cookies policy specs
> [CST-2519] Make the steps explicit in the cookies policy specs

- swagger/v3/api_spec.json
Providers got confused by this in v3, and used strings instead. Another fix for the types coming in shortly
- Ticket: n/a
> Change string to boolean for funded type in API spec

- app/services/npq/application/accept.rb
- app/services/npq/application/change_funded_place.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/services/npq/application/accept_spec.rb
- spec/services/npq/application/change_funded_place_spec.rb
We currently validate against the funded place attribute regardless of type. So if a string is passed in we compute it as true.
This confused providers as they were passing values such as `"false"` and `"null"` and this was computed as `true`
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3205
Amend the validations in both services to only accept boolean values otherwise returns a validation error, even if it's a string.
Maybe we should allow strings and compute those values, but felt better to lock it down to just booleans
> Amend accept and change funding service to only accept funded place booleans only

- app/controllers/concerns/api/v1/participant_actions.rb
- spec/support/shared_examples/participant_actions_change_schedule_support.rb
[Jira-3200](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3200)
The `ChangeSchedule` service already has this functionality, however it was locked down so that providers could not perform the action. It has been decided we want to open up this functionality to LPs going forward, so we can do this by passing `allow_change_to_from_frozen_cohort: true` into the `ChangeSchedule` service.
- Allow providers to migrate participants from 2021 to 2024
> Allow providers to migrate participants from 2021 to 2024

- docs/source/release-notes.html.md
We are releasing changes to change schedule endpoint to allow providers to move participants across regardless of declarations in 2021. This is explains all the things
- Ticket: 
Amend release notes to include change schedule message
Content innit
> Add release note for multi-cohort schedules changes

- app/services/npq/ehco/targeted_delivery_funding_eligibility_updater.rb
- app/services/support/base_service.rb
- lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb
- lib/tasks/oneoff/cleanup_itt_providers_npq_06_02_2023.rake
- spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/serializers/api/v3/npq_participant_serializer_spec.rb
- spec/support/features/pages/base_page.rb
- spec/support/features/pages/finance/finance_portal.rb
- spec/support/features/steps/changes_of_circumstance_steps.rb
- spec/support/matchers/lead_provider_api/make_duplicate_training_declaration.rb
- spec/swagger_helper.rb
- Ticket: N/A
The specs output is polluted with various debugging messages from puts statements or the logger.
This PR is an attempt to clean up the output.
- Remove puts from specs
- Fix deprecation messages
- Change the logger in test env to nil
> Clean up the specs output

- spec/features/schools/participants/add_participants/add_previously_withdrawn_ect_spec.rb
- spec/features/schools/participants/add_participants/reporting_participants_with_trn_spec.rb
- Fix time based error in specs related to cohort setup by using `mid_cohort: true`
> [Bug-Fix] move specs into mid_cohort to prevent issues with cohort setup in journey

- app/services/appropriate_bodies/participants_filter.rb
- app/views/appropriate_bodies/participants/index.html.erb
- spec/features/appropriate_bodies/participants_spec.rb
- spec/services/appropriate_bodies/participants_filter_spec.rb
Currently we show the current cohort which is calculated from the `academic_year_start_date` which is in September. We would like to change that to be from the `active_registration_cohort ` which is in June instead.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3214
Amend the Appropriate bodies filter as well as view to read from the Cohort `active_registration_cohort`
Tests setup for the filter isn't great but amending it to always pass to avoid using time freezing, and setting an extra cohort in the past rather than next
> Change appropriate body view to show active registration cohort

- app/views/schools/cohort_setup/_change_lead_provider_confirmation.html.erb
- app/views/schools/cohort_setup/what_changes.html.erb
- Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2656)
- It was noticed that 2 links to guidance pointed to the wrong information, this PR updates them to use the correct links.
You need a school that was doing FIP last year and has not yet set up their latest cohort. The LP/DP pairing from the previous year should also not exist - in the test data "FIP School for Training Record States" is such a school.
Impersonate the SIT
Choose FIP
and go through
The link "delivery options for ECF-based training (opens in new tab)" should link to https://www.gov.uk/guidance/how-to-set-up-training-for-early-career-teachers
The link "Find out more about partnering with a lead provider (opens in new tab)." should link to https://www.gov.uk/guidance/how-to-set-up-training-for-early-career-teach …
> [CST-2656] Change links to correct guidance page

- app/mailers/school_mailer.rb
- app/services/withdraw_participant.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/withdraw_participant_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3185
* Updated `SchoolMailer.fip_provider_has_withdrawn_a_participant` to include `partnership` params.
* Updated `WithdrawParticipant` to pass in `partnership`
> [CPDLP-3185] Legacy school mailer - Not looking up partnerships correctly

- app/models/email.rb
- app/models/nomination_email.rb
- config/initializers/filter_parameter_logging.rb
We've had a few instances where email addresses have shown up in logs. This should filter any personal ones out.
- **Filter email addresses from other email models**
- **Add email to the list of filtered parameters**
> Filtering sensitive data

- config/environments/production.rb
These create lots of noise in our logs and aren't much use.
Implementation lifted from [Teaching Vacancies](https://github.com/DFE-Digital/teaching-vacancies/pull/6946) ❤️
> Stop `DfE::Analytics::SendEvents` from filling logs

- config/initializers/sidekiq.rb
This was highlighted as a possible cause for our over-logging DfE-Analytics messages to Logit.io.
- **Simpilfy and deduplicate Redis initialization**
- **Set Redis's server logger level to WARN**
> Change Sidekiq log level to `WARN`

- app/models/finance/schedule/npq_leadership.rb
- app/models/finance/schedule/npq_specialist.rb
Senco is not a specialist course but a leadership course
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3276
Move course identifier to Leadership. 
Since this is already in production there is another ticket to cleanup the existing data for schedules, which will come after this
> Move Senco to leadership course as it is not specialist

- .rubocop.yml
- config/environments/production.rb
This should reduce the number of entries we're sending on to Logit.io and stop us from going over the limit!
Approach lifted from [this PR](https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2283/files).
- **When Sidekiq running in prod set log level to warn**
- **Disable incorrect Rubocop rules**
> Set log level to `:warn` when Sidekiq running in server mode

- terraform/application/databases.tf
- terraform/application/variables.tf
- terraform/application/workspace_variables/production.tfvars.json
ECF postgres database don’t have a maintenance window set, so they are upgraded alongside nonprod at a random time
- Ticket: https://trello.com/c/4NPqv8MF/1903-add-prod-postgres-maintenance-window
Add maintenance window to terraform
Maintenance window set in terraform
> Add postgres maintenance window

- app/views/layouts/admin.html.erb
- Ticket: N/A
The NPQ link in the admin menu takes you to the NPQ Edge Case page, which causes confusions. Admins use the Edge Cases search bar to search for normal NPQ applications, which returns no results.
- Update the link to the npq applications index page
> Change the default NPQ admin page to the npq applications index page

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
- Ticket: [CPDLP-3279](https://dfedigital.atlassian.net/browse/CPDLP-3279)
LLSE has put a request to move 5 declarations for a specific course to a different statement.
Add course identifier as a filter to MigrateDeclarationsBetweenStatements service.
```
cohort = Cohort.find_by_start_year!(2023)
cpd_lead_provider = CpdLeadProvider.find_by!(name: "LLSE")
from_statement_name = Finance::Statement::NPQ.find_by!(cpd_lead_provider:, name: "July 2024", cohort:).name
to_statement_name = Finance::Statement::NPQ.find_by!(cpd_lead_provider:, name: "November 2024", cohort:).name
restrict_to_lead_providers = [cpd_lead_provider.npq_lead_provider]
restrict_to_course_identifiers = ["npq-early-headship-coaching-offer"]
Oneoffs::NPQ::MigrateDeclarationsBetweenStatements.new(cohort:, from_statement_name:, …
```
> [CPDLP-3279] Add course identifier as a filter to MigrateDeclarationsBetweenStatements service

- app/models/participant_profile_start_date_inconsistency.rb
- app/services/admin/participants/change_induction_start_date.rb
- app/services/participants/check_and_set_completion_date.rb
- db/migrate/20240717111257_remove_participant_profile_start_date_inconsistencies_table.rb
- db/schema.rb
- spec/services/admin/participants/change_induction_start_date_spec.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
Automatically put participants in their permanent cohort on Daily DQT date checks.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2629)
> DQT synced participants cannot be placed in 2021 cohort in daily checks

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3272
* removed `output` to allow running command for this ticket.
Will run the following command:
```ruby
cohort = Cohort.where(start_year: 2022).first!
from_statement_name = "August 2024"
from_statement_updates = {
output_fee: false,
}
to_statement_name = "September 2024"
to_statement_updates = {
output_fee: true,
deadline_date: "2024-08-25",
}
service = Oneoffs::NPQ::MigrateDeclarationsBetweenStatements.new(
cohort:,
from_statement_name:,
to_statement_name:,
from_statement_updates:,
to_statement_updates:,
restrict_to_lead_providers: nil,
restrict_to_declaration_types: nil,
restrict_to_declaration_states: nil,
)
service.migrate(dry_run: true)
```
> [CPDLP-3272] NPQ - Update cohort 2022 output from FALSE to TRUE and move declarations

- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
- Ticket: N/A
Flakey spec `spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb:198`
Fix the given flakey test above.
> Fix flakey test in migrate_declarations_between_statements_spec

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/npq_applications_controller.rb
- config/locales/en.yml
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-2764
* Added `rescue_from Identity::TransferError` to npq_applications controllers to return errors
> [CPDLP-2764] Introduce 422 errors on NPQ accept application endpoint when there are errors with GAI ID/Conflict

- app/forms/nominate_induction_tutor_form.rb
- spec/forms/nominate_induction_tutor_form_spec.rb
- Ticket: N/A
This PR fixes the case-insensitive name matching validation in the Nominate SIT form that prevents adding SITs.
- Downcase the names before comparing them
> Fix case-insensitive name matching in nominate SIT form

- .gitignore
- Dockerfile
- config/initializers/api_reference.rb
- docs/config.rb
- docs/lib/govuk_tech_docs/open_api/renderer.rb
- docs/lib/govuk_tech_docs/open_api/templates/responses.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
- docs/spec/govuk_tech_docs/open_api/renderer_spec.rb
- swagger/v1/api_spec.json
- swagger/v2/api_spec.json
- swagger/v3/api_spec.json
[Jira-3275](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3275)
We want to remove all references to the NPQ endpoints from the swagger docs in the `separation` environment for providers to test.
- Fix references to NPQ in ECF
These references to NPQ participants should be ECF participants as they are in the context of an ECF path/schema.
- Conditionally remove NPQ references from swagger docs
We want to be able to conditionally remove the references to NPQ from the swagger docs. This includes stripping out paths, schemas and links to schemas as well as NPQ-specific pages.
- Dynamically replace API reference on boot
We want to serve two versions of the API reference depending on the …
> Remove NPQ references from swagger docs on separation env

- docs/lib/govuk_tech_docs/open_api/renderer.rb
The method was returning `nil` instead of the original text when the flag to remove NPQ references was `false`.
These methods don't have test coverage as they're `private` and called directly from the view. It's not a great solution but the code is to be short-lived, so I haven't tried to improve it.
> Fix API docs removing response text

- spec/services/participants/check_and_set_completion_date_spec.rb
- Ticket: n/a
To avoid dates and cohorts shifting, set the DQT record to always be inside the registration period.
will this fail again later?
> Set the DQT record to inside the registration period

- app/services/create_change_request_support_query.rb
- config/locales/schools/change_request_support_query.yml
- spec/services/create_change_request_support_query_spec.rb
We've recently changed how change LP/DP support forms are submitted. The additional information provided in the footer of the Zendesk ticket has also changed, we'd like to retain the same information as we submitted previously
- Ticket: https://dfedigital.atlassian.net/browse/CST-2706
Provides a hash of additional information in the same format as before, this will be used by [`SupportQuery#sync_to_support_queue`](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/models/support_query.rb#L31) to format the footer information as we did previously.
This will need deployment to test from test/staging.
> Provide correct additional information to Support Query when changing LP/DP

- config/initializers/dfe_analytics.rb
The analytics team are adding some encryption to to tables in BigQuery so we need to stop sending events for a few minutes and have arranged this Wednesday between 18:00 and 18:30 UTC.
You can check this is correctly set by running:
```ruby
DfE::Analytics.parse_maintenance_window
#=> [Wed, 07 Aug 2024 18:00:00.000000000 UTC +00:00, Wed, 07 Aug 2024 18:30:00.000000000 UTC +00:00]
```
> Add BigQuery maintenance window for DfE Analytics

- app/views/lead_providers/content/index.html.erb
- app/views/lead_providers/content/partnership_guide.html.erb
It has been flagged that these images don't provide any additional information for visually impared users and should be set to `null`, which is `alt=""`.
- Remove alt text from screenshots in API docs
> Remove alt text from screenshots in API docs

- app/views/schools/dashboard/_school_cohort_details.html.erb
- spec/features/schools/change_request_support_query/sit_requests_delivery_partner_change_for_academic_year_spec.rb
- spec/features/schools/change_request_support_query/sit_requests_lead_provider_change_for_academic_year_spec.rb
Undo this https://github.com/DFE-Digital/early-careers-framework/pull/4986 as we want these links for the active registration cohort now.
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CST-2698
Re-enable change LP/DP links for active registration cohort
> Re-enable change LP/DP links on schools dashboard

- docs/config.rb
- docs/config/tech-docs.yml
- docs/source/layouts/_custom_footer.erb
- docs/source/layouts/custom.erb
- docs/source/layouts/custom_core.erb
[Jira-3365](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3365)
We want to make the footer on the API docs consistent with that on the rest of the website.
- Add support and links to API docs footer
The links are supported by the tech docs gem, however the support paragraph required overriding the footer from the template. Usually in a Middleman template you can just specify a partial in the correct place and it will use it/override for you, however for some reason this doesn't work with the tech docs template. I think because of the way it builds/pulls from the tech docs gem. Instead, I've had to copy the layouts to our repository, rename them and update all pages to use them by …
> Add support and links to API docs footer

- docs/source/api-reference/stylesheets/screen.css.scss
[Jira-3368](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3368)
In order to improve accessibility, we are adding spacing around bulleted links in the API documentation.
- Add spacing on API doc bullet links
| Before    | After |
| -------- | ------- |
| ![before](https://github.com/user-attachments/assets/27369506-f2c1-4c06-950c-b6bdd9759e34)  | ![after](https://github.com/user-attachments/assets/b6283549-2784-42d5-8df3-6e12664acd12)    |
> Add spacing on API doc bullet links

- app/views/lead_providers/report_schools/csv/show.html.erb
[Jira-3369](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3369)
On iOS using VoiceOver when selecting a file on the school report CSV upload page the focus resets to the first item on the page (skip to main content).
I can't find anything specific to our web app that would cause this, so I think its default iOS behaviour after a file picker modal appears and then Safari re-gains focus.
To make it more intuitive for the user I've added an `onchange` that will focus on the form submit button once a file has been selected (I tried to refocus on the file input but this doesn't work for some reason).
A side-effect is that this will change for all users; so on desktop the file input …
> Focus on continue button after selecting file

- app/views/appropriate_bodies/participants/index.html.erb
- app/views/delivery_partners/delivery_partners/index.html.erb
- Ticket:[CPDLP-3367]( https://dfedigital.atlassian.net/browse/CPDLP-3367)
We would like to investigate and where we are able to address accessibility issues flagged by the accessibility testing done on ECF.
Add missing page titles.
Other pages quoted in the ticket have been already fixed on https://github.com/DFE-Digital/early-careers-framework/commit/1a1a376b3d9326b4ba04a9d9158f66a28f208d54
Login using delivery partner and appropriate body logins and browse to the participants and show a participant pages to see the updated titles on the page.
[CPDLP-3367]: https://dfedigital.atlassian.net/browse/CPDLP-3367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3367] Add missing page titles

- app/services/oneoffs/ecf/change_service_fees.rb
- spec/services/oneoffs/ecf/change_service_fees_spec.rb
[Jira-3346](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3346)
Improve the logging so we can see the statement ids being changed and their current contract versions/service fees. Call out `nil` explicitly as this is different to `0.0` (when `nil` it will fallback to a calculated service fee determined by the bandings).
- Minor updates to `ChangeServiceFees` script
> Minor updates to `ChangeServiceFees` script

- app/controllers/api/api_controller.rb
- app/controllers/api/errors/missing_npq_contract_or_statement_error.rb
- app/services/change_schedule.rb
- app/services/npq/application/accept.rb
- app/services/npq/application/change_funded_place.rb
- config/locales/en.yml
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v1/npq_participants_spec.rb
- spec/requests/api/v2/npq_applications_spec.rb
- spec/requests/api/v2/npq_participants_spec.rb
- spec/requests/api/v3/npq_applications_spec.rb
- spec/requests/api/v3/npq_participants_spec.rb
- spec/services/change_schedule_spec.rb
- spec/services/npq/application/accept_spec.rb
- spec/services/npq/application/change_funded_place_spec.rb
[Jira-3223](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3223)
In the accept, change schedule and change funded place actions we want to ensure the NPQContract and (for some) the Statement is present when the `npq_capping` feature is enabled.
- Add validation to ensure NPQContract/Statement is present
Add validation that raises a `Api::Errors::MissingNPQContractOrStatementError`, to be rescued in the API controller and an error message returned.
The error is raised so that it can be returned as a `400 bad request` instead of a `422 unprocessable entity`, which would happen if we performed the check as a validation rule in the model.
> Add validation to ensure NPQContract/Statement is present

- app/controllers/api/v1/participant_validation_controller.rb
- app/services/importers/npq_manual_validation.rb
- spec/services/importers/npq_manual_validation_spec.rb
https://dfedigital.atlassian.net/browse/CPDNPQ-2004
Excel strips leading zeros from TRNs. This PR adds them back if they are missing.
TRNs must be 7 digits. If the importer receives a validated TRN that is less then it will assume excel has stripped a leading zero. This PR therefore add 0's until the TRN is 7 digits.
> [CPDNPQ-2004] Add leading zeros to TRN validation import

- docs/source/release-notes.html.md
> ⚠️ WIP pending date
We want to add the release note for the ECF standalone API test environments.
- Add release note for ECF standalone service
I'm not sure the links to the environments make sense here as we're linking to `/api` and it'll just 404 in a browser 🤔
> Add release note for ECF standalone service

- app/services/importers/create_statement.rb
- spec/services/importers/create_statement_spec.rb
[Jira-3395](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3395)
Currently, when we import statements we take the latest contract version across all other statements. Instead, we should be selecting the latest (by `payment_date`) scoped to cohort and lead provider.
- Select correct contract version for statement importer
> Select correct contract version for statement importer

- terraform/application/terraform.tf
Avoid unexpected provider updates. In https://github.com/DFE-Digital/early-careers-framework/pull/5132 we notived the kubernetes provider definition was missing.
- Ticket: https://trello.com/c/moH45K2M
Pin terraform kubernetes provider to 2.32.0
Run: make production terraform-plan
> [1839] Pin terraform kubernetes provider to 2.32.0

- app/serializers/api/v3/ecf/participant_serializer.rb
- docs/source/release-notes.html.md
- spec/docs/v3/ecf_participants_spec.rb
- spec/fixtures/files/api_reference/api_spec.json
- spec/fixtures/files/api_reference/api_spec_no_npq.json
- spec/requests/api/v3/ecf/participants_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ECFEnrolment.yml
[Jira-2971](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-2971)
We want to add a new field `mentor_ineligible_for_funding_reason` to the v3 participant serializer, which is populated using the mentor `mentor_completion_reason` attribute. We only want to populate this in non-production environments to begin with.
Add release note describing the change.
- Add `mentor_ineligible_for_funding_reason` to v3 participant serializer
> Add `mentor_ineligible_for_funding_reason` to v3 participant serializer

- lib/tasks/separation_data.rake
- lib/tasks/valid_test_data_generator/completed_mentor_generator.rb
- spec/lib/tasks/completed_mentor_generator_spec.rb
- Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3466
* New service to add completed mentors `ValidTestDataGenerator::CompletedMentorGenerator`
* Updated separation rake task to run the service
> [CPDLP-3466] Create seed data on separation and sandbox

- docs/source/release-notes.html.md
- Ticket: n/a
The name was amended later to `mentor_funding_end_date_reason` and should be `mentor_ineligible_for_funding_reason`.
> Amend field name to correct `mentor_ineligible_for_funding_reason`

- app/serializers/api/v3/ecf/participant_serializer.rb
- docs/source/release-notes.html.md
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- Ticket: [CPDLP-2970](https://dfedigital.atlassian.net/browse/CPDLP-2970)
The mentor completion reason field has now been released to sandbox. We need to release it to production with a release note.
Release `mentor_ineligible_for_funding_reason` and release note into production.
https://cpd-ecf-review-5155-web.test.teacherservices.cloud/api-reference/release-notes.html#release-notes
[CPDLP-2970]: https://dfedigital.atlassian.net/browse/CPDLP-2970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-2970] Release `mentor_ineligible_for_funding_reason` and release note into production

- app/services/oneoffs/npq/bulk_change_applications_to_pending.rb
- lib/tasks/npq/bulk_change_applications_to_pending.rake
- spec/services/oneoffs/npq/bulk_change_applications_to_pending_spec.rb
[Jira-3274](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3274)
We want to add a rake task that will take a CSV of application IDs as an input and move all the applications to a `pending` state.
- Add rake task to bulk mark applications as pending
Add a new one off service to make a group of applications `pending`. Add rake task so that we can call the service with a CSV of application ids and log out the updates (changed to pending, already pending or an error preventing it from moving to a pending state).
```
bundle exec rake 'npq_applications:bulk_change_to_pending[applications.csv,true]'
INFO -- : Bulk changing 4 NPQ applications to pending (dry run)...
INFO -- : { …
```
> Add rake task to bulk mark applications as pending

- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
[Jira-3600](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3600)
We have a bug when migrating declarations to a `Payable` statement whereby we will put the declaration through the `MarkAsPayable` service regardless of its current state. This results in `awaiting_clawback` declarations being made `payable`.
Instead, we want to follow the logic in the rest of the service and only make `eligible` declarations `payable` when moving to a `Payable` statement.
- Don't make `awaiting_clawback` line items `payable` on migrating declarations
As it stands, the following behaviour will apply for declarations moving to a `Payable` statement:
- eligible -> payable
- awaiting_clawback -> awaiting clawback
- payable -> payable
- submitted/voided/ineligible (ignored - no line items)
- …
> Don't make `awaiting_clawback` line items `payable` on migrating declarations

- terraform/application/databases.tf
We need to update the postgres version to the latest stable one - however before this we need to make sure all services pin the postgres version so it’s not updated unexpectedly
Set Postgres server version to 14
https://trello.com/c/4PBO6Miu/834-change-default-postgres-version-to-16
> Pin postgres version

- config/analytics_hidden_pii.yml
- config/analytics_pii.yml
This config change allows us to restrict access to sensitive data in BigQuery.
Note, on the night this is merged, log in and kick off [this job](https://github.com/DFE-Digital/dfe-analytics?tab=readme-ov-file#7-import-existing-data) to resync everything.
```
$ bundle exec rails dfe:analytics:import_all_entities
```
> Move analytics_pii config to analytics_hidden_pii

- .github/actions/backup-and-restore-snapshot-database/action.yml
- app/services/oneoffs/npq/data_cleanup/fix_applications_in_ecf_not_in_npq.rb
- lib/tasks/oneoff/data_cleanup/cleanup_applications.rake
- spec/services/oneoffs/npq/data_cleanup/fix_applications_in_ecf_not_in_npq_spec.rb
- Ticket: [CPDLP-3500](https://dfedigital.atlassian.net/browse/CPDLP-3500)
We've found applications that are duplicated in both ECF and NPQ that need to be deleted in ECF.
Add data cleanup script to fix applications that exist in ECF not NPQ.
[CPDLP-3500]: https://dfedigital.atlassian.net/browse/CPDLP-3500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3500] Add data cleanup script to fix applications that exist in ECF not NPQ

- app/mailers/school_mailer.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: CST-2766
The Notify template was updated to include the SIT nomination link
- Add nomination_link as a new parameter to the mailer
- Update the bulk mailer to pass the nomination_link when calling the mailer
> [CST-2766] Add nomination_link param to sit pre term comms mailer

- app/models/npq_application.rb
- app/services/api/v1/npq/application_status_query.rb
- spec/models/npq_application_spec.rb
- spec/requests/api/v1/npq/application_synchronization/index_spec.rb
- spec/serializers/api/v1/npq/application_synchronization_serializer_spec.rb
- spec/services/api/v1/npq/application_status_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3514
`NPQApplication` `participant_declaration_finder` is not scoped by completed declarations. It should be as the outcomes belongs to only completed declarations, not to started declarations, which are the first type of declaration for a participant profile, and it's the one that's being fetched using `find_by_participant_profile_id`.
Scope `participant_declaration_finder` by completed declarations as well, so we make sure we select the correct and completed declaration for the participant profile, and then after that the possible outcomes linked to those completed declarations.
Before: 
```
Api::V1::NPQ::ApplicationStatusQuery.new(NPQApplication.find("06787ded-3102-4647-ad15-d0d56b70139b").call
-> nil
```
After:
``` …
```
> [CPDLP-3514] Scope `participant_declaration_finder` to completed declaration

- lib/tasks/valid_test_data_generator.rb
- lib/tasks/valid_test_data_generator/completed_mentor_generator.rb
We were getting duplicates in pagination due to data having similar `created_at` timestamps across all test data. This makes the test data more random
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3609
Add a random time to the schedule time selected
-
> Amend test data to generate random `created_at`

- app/models/continue_training_cohort_change_error.rb
- app/services/induction/amend_participant_cohort.rb
- app/services/participants/check_and_set_completion_date.rb
- config/analytics_blocklist.yml
- db/migrate/20240718153716_create_continue_training_cohort_change_errors.rb
- db/schema.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
Every day we check DQT to get updates of induction dates (start and completion) for all the participants resulting in updates in their induction start dates or induction completion dates or even participants placed in a cohort different to their current one.
From mid September’24 (when we expect that DQT has finished receiving induction completion dates for all the participants that completed induction in 2023/24 or earlier) we need to extend the logic that amends participant cohorts as part of this daily check to move to 2024/25 cohort incomplete participants that according to their existing/updated induction start date are/should be put in 21/22 cohort but have an induction status of “In Progress”.
- [Ticket](https://dfedigital.atlassian.net/browse/CST-2577): 
- Move eligible …
> CST-2577: daily DQT checks. Move unfinished ECTs in progress to the reg-active cohort.

- spec/services/valid_test_data_generators/npq_lead_provider_populater_spec.rb
- Ticket: N/A
A spec is flakey because the populater skips creating declarations for some type of npq courses.
https://github.com/DFE-Digital/early-careers-framework/blob/main/app/services/valid_test_data_generators/npq_lead_provider_populater.rb#L44
Fix `spec/services/valid_test_data_generators/npq_lead_provider_populater_spec.rb:80` flakey test.
> Fix flakey test

- .github/workflows/refresh_migration_database.yml
- app/services/migration/parity_check/token_provider.rb
- spec/services/migration/parity_check/token_provider_spec.rb
[Jira-3650](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3650)
We hit an issue when running the original token provider whereby the keys would generate but not work in the migration environment. This was due to the keys being generated using the NPQ reg migration environment secret_key_base but verified in ECF using a different secret_key_base.
To get around this, we are going to use known tokens; each migration keyvault has the same set of tokens indexed by the lead provider `ecf_id`. After restoring the migration database we will create the known-tokens for the parity check service to use.
- Generate known tokens for parity check on migration DB restore
The …
> Generate known tokens for parity check on migration DB restore

- config/analytics.yml
- config/analytics_blocklist.yml
This is no longer wanted in BigQuery by the CPD data team.
> Move `analytics_appropriate_bodies` to the analytics blocklist

- app/jobs/update_participant_appropriate_body_dqt_check_job.rb
- app/models/participant_appropriate_body_dqt_check.rb
- config/analytics_blocklist.yml
- db/migrate/20241021071942_create_participant_appropriate_body_dqt_checks.rb
- db/schema.rb
- lib/tasks/participant_appropriate_body_dqt_checks.rake
- spec/models/participant_appropriate_body_dqt_check_spec.rb
- Ticket: CST-2765
This PR enables cross-checking our records for 20,000 active 2024 ECTs against DQT records to identify any participants whose Appropriate Body does not match the DQT record.
Since the DQT API has a rate limit of 1000 requests per minute, it’s crucial to ensure we don't exceed this quota and cause bottlenecks to the service.
We’ve also noticed that the DQT returns the name of the leading school for the Appropriate Bodies, whereas in our records, we typically include it in parentheses as part of the Appropriate Body name. For example, for an Appropriate Body named `London TSH` with a leading school `Astro Primary School`, our records show it as `London TSH (Astro Primary School)`, while the DQT response simply lists `Astro Primary School`.
- Add a temporary table to store …
> [CST-2765] Cross-Check 2024 ECT Appropriate Body Records Against DQT

- app/controllers/concerns/admin/participants/retrieve_profile.rb
- app/services/admin/participants/search.rb
- app/views/admin/participants/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/data/schedules/schedules.csv
- spec/controllers/concerns/admin/participants/retrieve_profile_spec.rb
- spec/controllers/concerns/api_filter_spec.rb
- spec/controllers/concerns/api_filter_validation_spec.rb
- spec/controllers/concerns/api_pagination_spec.rb
- spec/features/admin/notes/participant_note_spec.rb
- spec/features/admin/npq_applications/npq_applications_spec.rb
- spec/features/admin/npq_applications/participant_details_spec.rb
- spec/features/admin/participants/participant_induction_records_spec.rb
- spec/features/admin/participants/participant_steps.rb
- spec/features/admin/participants/participants_details_spec.rb
- spec/features/admin/participants/participants_spec.rb
- spec/models/finance/schedule/ecf_spec.rb
- spec/requests/admin/npq_admin_routes_spec.rb
- spec/services/admin/participants/search_spec.rb
We need to disable any NPQ logic and services in the admin interface.
- Ticket: [CPDLP-3589](https://dfedigital.atlassian.net/browse/CPDLP-3589)
- Disable any NPQ tools in the admin interface
- Disable any tabs/routes that show NPQ data
- Add the feature flag to any services that show both, so when disabled will only show ECF
[CPDLP-3589]: https://dfedigital.atlassian.net/browse/CPDLP-3589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3589] Disable NPQ in admin

- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v3/participant_declarations_controller.rb
- app/services/api/participant_declarations/index.rb
- app/services/api/v3/participant_declarations_query.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/api/participant_declarations/index_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
In the migration environment we are running a comparison between NPQ and ECF responses; in order to do this for the declarations endpoint we need to be able to return only NPQ declarations.
Add `type` filter support to declaration endpoints, only for the migration environment.
> Support filtering by declaration type in migration environment

- app/jobs/create_new_fake_sandbox_data_job.rb
- app/jobs/npq/stream_big_query_enrollment_job.rb
- app/jobs/npq/stream_big_query_profile_job.rb
- app/jobs/participant_outcomes/batch_send_latest_outcomes_job.rb
- app/jobs/participant_outcomes/send_to_qualified_teachers_api_job.rb
- app/jobs/participant_outcomes/stream_api_requests_to_big_query_job.rb
- app/jobs/participant_outcomes/stream_big_query_job.rb
- app/jobs/stream_big_query_participant_declarations_job.rb
- app/services/statements/mark_as_paid.rb
- app/services/statements/mark_as_payable.rb
- spec/jobs/create_new_fake_sandbox_data_job_spec.rb
- spec/jobs/npq/stream_big_query_enrollment_job_spec.rb
- spec/jobs/npq/stream_big_query_profile_job_spec.rb
- spec/jobs/participant_outcomes/batch_send_latest_outcomes_job_spec.rb
- spec/jobs/participant_outcomes/send_to_qualified_teachers_api_job_spec.rb
- spec/jobs/participant_outcomes/stream_api_requests_to_big_query_job_spec.rb
- spec/jobs/participant_outcomes/stream_big_query_job_spec.rb
- spec/jobs/stream_big_query_participant_declarations_job_spec.rb
- spec/services/statements/mark_as_paid_spec.rb
- spec/services/statements/mark_as_payable_spec.rb
- Ticket: [CPDLP-3517](https://dfedigital.atlassian.net/browse/CPDLP-3517)
- Add the existing turning off NPQ feature flag to the following jobs:
- BatchSendLatestOutcomesJob
- CreateNewFakeSandboxDataJob
- StreamBigQueryEnrollmentJob
- StreamBigQueryProfileJob
- StreamApiRequestsToBigQueryJob
- StreamBigQueryJob
- Update the following jobs to not include NPQ if the same feature flag is on:
- StreamBigQueryParticipantDeclarationsJob
- MarkAsPayable
- MarkAsPaidJob
[CPDLP-3517]: https://dfedigital.atlassian.net/browse/CPDLP-3517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3517] Add NPQ feature flag to turn off ECF jobs

- app/mailers/school_mailer.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: CST-2788 
We need to send reminders to SITs from schools that ran FIP programs in 23/24 but haven’t yet engaged this year to set up their training.
Should exclude:
- CIP and DIY schools 
- independent or independent special schools (even if in receipt of Section-41 funding)
- children's centres
- British Schools Overseas
- Welsh schools
- Add the mailer for the Notify template
- Add the bulk mailer to trigger the emails
> [CST-2788] Add mailer to remind SITs to set up training for the current year

- app/mailers/school_mailer.rb
- spec/mailers/school_mailer_spec.rb
- Ticket: CST-2788
- Pass the school_name to the notify template
- Change the `name` to `sit_name` placeholder to match the template
> [CST-2788] Update placeholders for the remind_sit_to_report_school_training_details school mailer

- terraform/application/workspace_variables/migration.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_migration.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_migration_backend.tfvars
To add the maintenance page templates we need to ensure migration has an internal and external domain
- Ticket: n/a
Setup environment domain for migration environment for an external domain
We trust in @saliceti
> Add external domain to migration env

- app/components/banners/maintenance_component.html.erb
- app/components/banners/maintenance_component.rb
- app/controllers/maintenance_banners_controller.rb
- app/helpers/phase_banner_helper.rb
- app/views/layouts/_maintenance_notification_banner.erb
- config/routes.rb
- spec/components/banners/maintenance_component_spec.rb
- spec/features/maintenance_banner_spec.rb
- spec/helpers/phase_banner_helper_spec.rb
- spec/requests/maintenance_banner_spec.rb
[Jira-3531](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3531)
We want to fix and clean up the maintenance banner in ECF so that we can use it for the upcoming downtime when we transition the lead provider APIs to NPQ reg.
- Clean up maintenance banner
Clean up the maintenance banner to match the latest design.
Fix broken `Dismiss` button; swap to a link to be consistent with the GOV.UK banner component usage.
Change route to GET so we can use it from a regular link in the GOV.UK components helpers (not ideal but allows us to use the component to render the banner).
Add missing test coverage.
> Clean up maintenance banner

- spec/services/participants/check_and_set_completion_date_spec.rb
It looks like this spec has started failing today as the `induction_completion_date` happens to align with the DQT induction record:
```
(byebug) dqt_induction_record
{"endDate"=>Sun, 12 May 2024, "periods"=>[{"startDate"=>Thu, 01 Sep 2022, "endDate"=>Sat, 01 Jun 2024}, {"startDate"=>Sat, 01 Jun 2024, "endDate"=>Sat, 31 Aug 2024}], "status"=>"active"}
(byebug) induction_completion_date
Sat, 31 Aug 2024
```
By using a future date it should ensure its always different to the IR.
> Fix failing spec on completion date match checking

- spec/requests/maintenance_banner_spec.rb
Sometimes this test takes longer than 1s to run; making it 5s should give it enough wiggle room.
> Fix flakey banner dismiss spec

- app/queries/schools/that_have_not_engaged_query.rb
- app/services/bulk_mailers/school_reminder_comms.rb
- spec/queries/schools/that_have_not_engaged_query_spec.rb
- spec/services/bulk_mailers/school_reminder_comms_spec.rb
- Ticket: CST-2732
We emailed SITs to report their school training information for the current year, but many still haven't responded. We'd like to send a follow-up email to the schools' GIAS contacts, asking them to review their SIT information and required actions.
- Add query to pull all the unengaged schools
- Add bulk school mailer to trigger the emails
- Please check the Notify template to confirm that all required placeholders are included
> [CST-2732] Add bulk mailer to chase unengaged schools

- app/jobs/api_request_job.rb
- app/models/api_request.rb
- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_custom_events.yml
- config/initializers/dfe_analytics.rb
- spec/jobs/api_request_job_spec.rb
- spec/models/api_request_spec.rb
- Ticket: n/a
API requests are huge and we need to stop sending them via BQ dfe analytics, but via a custom event
- remove API request from BQ dfe analytics
- add custom event to send this data
commit by commit
> Move API Requests in DFE Analytics to custom events

- app/jobs/update_participant_appropriate_body_dqt_check_job.rb
- config/analytics_blocklist.yml
- db/migrate/20241101133851_add_dqt_induction_status_to_participant_appropriate_body_dqt_checks.rb
- db/schema.rb
- lib/tasks/participant_appropriate_body_dqt_checks.rake
- Ticket: CST-2765
The crosscheck needs to be updated to: 
1. Skip any mismatches that don't have `InProgress` dqt induction status
2. Compare the ids of the Appropriate Bodies, instead of their names. Since the DQT responses includes only AB names, a csv is provided to us that maps them to their corresponding records in ECF Manage service.
- Store the dqt induction status in the check records
- Update the extract to skip mismatches that don't have `InProgress` dqt induction status
> [CST-2765] Update the participant AB name crosscheck

- app/controllers/admin/participants/change_cohort_controller.rb
- app/forms/schools/add_participants/base_wizard.rb
- app/models/participant_declaration.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- app/services/change_schedule.rb
- app/services/early_career_teachers/create.rb
- app/services/early_career_teachers/reactivate.rb
- app/services/induction/amend_cohort_after_eligibility_checks.rb
- app/services/induction/amend_participant_cohort.rb
- app/services/induction/change_mentor.rb
- app/services/induction/schedule_for_new_cohort.rb
- app/services/induction/transfer_and_continue_existing_fip.rb
- app/services/induction/transfer_to_schools_programme.rb
- app/services/participants/check_and_set_completion_date.rb
- documentation/handling_participants_moving_from_a_frozen_cohort.md
- spec/features/schools/participants/add_participants/payments_frozen/assign_ect_to_mentor_spec.rb
- spec/requests/admin/participants/change_cohort_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/induction/amend_cohort_after_eligibility_checks_spec.rb
- spec/services/induction/amend_participant_cohort_spec.rb
- spec/services/induction/change_mentor_spec.rb
- spec/services/induction/schedule_for_new_cohort_spec.rb
- spec/services/induction/transfer_and_continue_existing_fip_spec.rb
- spec/services/induction/transfer_to_schools_programme_spec.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
We have 3 triggers to automatically move participants in 2021 to 2024 due to 2021 cohort being frozen and no more lead provider declarations/payments can be accepted.
Until now only those participants complying with some requirements (unfinished participants) were picked and moved by the triggers implemented in June.
This PR extends those triggers to include any remaining participant in 2021 (not completed induction). 
The treatment will be similar to those unfinished participants but the flag that mark them to the LP won’t be setup for this new group.
- [Ticket: ](https://dfedigital.atlassian.net/browse/CST-2790)
> CST-2790: frozen cohort triggers must also include unfinished participants with no billable declarations

- docs/source/ecf/schedules-and-milestone-dates.html.md
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3720
Added the 2024/25 academic year standard schedules dates for September, January and April starts.
From the following pr: https://github.com/DFE-Digital/early-careers-framework/pull/5312
> Added 2024 cohort dates API guidance

- app/lib/lead_provider_api_specification/preprocessor.rb
- config/initializers/api_reference.rb
- spec/lib/lead_provider_api_specification/preprocessor_spec.rb
[Jira-3768](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3768)
Currently we remove NPQ references on the separation environment; going forward we want to remove all references when the `disable_npq` feature is enabled.
- Switch API doc NPQ removal to feature flag
Currently we remove NPQ references on the separation environment; going forward we want to remove all references when the disable_npq feature is enabled.
We will need to reboot the app instance to get the correct API docs as we determine this in an initializer on boot.
Only run initializer when ran in the context of a `rails server` so that wedon't get database connection errors when pre-compiling assets. …
> Switch API doc NPQ removal to feature flag

- app/presenters/admin/participant_presenter.rb
- app/views/admin/participants/details/_show_ecf.html.erb
- Ticket: CST-2805
Currently, the Admin page displays the induction completion date for both ECT and Mentor profiles. However, the induction completion date is specific to ECTs, while mentors have a separate mentor completion date. This PR addresses that inconsistency by ensuring the appropriate completion date is shown for each profile type.
- Update the participant details view page to display the appropriate completion date based on the profile type
|<img width="1117" alt="Screenshot 2024-11-19 at 13 42 06" src="https://github.com/user-attachments/assets/5d877922-2874-427a-abe2-340ed880e524">|<img width="1112" alt="Screenshot 2024-11-19 at 13 39 35" src="https://github.com/user-attachments/assets/517e3c58-7b4b-412d-92f1-caa5e9841578">|
> [CST-2805] Display correct completion date on Admin participant details page

- Gemfile.lock
- app/services/oneoffs/npq/migrate_declarations_between_statements.rb
- spec/services/oneoffs/npq/migrate_declarations_between_statements_spec.rb
- Ticket: [CPDLP-3738](https://dfedigital.atlassian.net/browse/CPDLP-3738)
Some payable declarations might be moved to an eligible statement (not payable nor paid) via the `MigrateDeclarationsBetweenStatements` service.
To accommodate this scenario, we're making payable `declarations` and linked `statement_line_items` back to eligible state when moving to an eligible statement when using `MigrateDeclarationsBetweenStatements` service.
[CPDLP-3738]: https://dfedigital.atlassian.net/browse/CPDLP-3738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3738] Make declarations back to eligible when moving to an eligible statement

- .github/actions/test-performance/action.yml
v3 [is soon going away](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/), we should be using v4. None of the breaking changes look like they'll affect us.
> Upgrade GitHub actions/upload-artifact to v4

- app/forms/finance/choose_payment_breakdown_form.rb
- spec/forms/finance/choose_payment_breakdown_form_spec.rb
We are getting an error in production with the following: `uninitialized constant Finance::ChoosePaymentBreakdownForm::OpenStruct`
- Ticket: n/a
Ensure that OpenStruct is not loaded under the finance class, but separately.
> Ensure OpenStruct is loaded outside the finance class

- config/initializers/sentry.rb
There is a bug in the JS event filtering; we get an error that `Error` is not defined. I expect this maybe should be a `TypeError` as in the other JS-related before-send method, but I'm not certain.
Removing for now so that we start getting Sentry events through again.
Reverts #4968
> Fix Sentry not sending events

- config/initializers/sentry.rb
It should have two arguments; we need the `_hint` param.
> Fix lambda args on Sentry before_send

- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v3/participant_declarations_controller.rb
- app/services/api/participant_declarations/index.rb
- app/services/api/v3/participant_declarations_query.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/api/participant_declarations/index_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
[Jira-3791](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3791)
Reverts DFE-Digital/early-careers-framework#5261 - we no longer need this as the parity checking has finished.
> Revert "Support filtering by declaration type in migration environment"

- .github/workflows/deploy.yml
We want to run CI on all pull requests, not just those than branch off main. This is going to be useful during the NPQ removal tasks as we're often branching off other branches.
> Run CI on all pull requests

- app/services/api/v3/ecf/unfunded_mentors_query.rb
- docs/source/release-notes.html.md
- spec/services/api/v3/ecf/unfunded_mentors_query_spec.rb
[Jira-3788](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3788)
Ambition flagged 3 separate cases of the unfunded mentors query returning incorrect/old emails, instead of the lates ones from the induction record. We want to update the query to use the induction records so that we surface the correct email.
- Fix UnfundedMentorsQuery email
We are currently surfacing the email from the `ParticipantProfile`, however we instead should be looking it up from the `InductionRecord`.
Update query to join `ParticipantIdentity` on `InductionRecord` and surface `email` from there. Note we need to join on the mentor's latest induction records (the base induction records are …
> Fix `UnfundedMentorsQuery` to surface correct email

- config/locales/status_tags/school_participant_status.yml
- Ticket: CST-2774
This PR enhances clarity for schools about scenarios where the Appropriate Body (AB) has not yet updated a participant’s status with the TRA.
- Update the description of the tag displayed in these scenarios
> [CST-2774] Update the no induction start description

- docs/source/release-notes.html.md
- spec/services/api/v3/participant_declarations_query_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3804
* Query service should not return any records that don't belong to the provider
> [CPDLP-3804] changes after NPQ cleanup for declarations query fix

- app/views/schools/add_participants/cannot_find_their_details.html.erb
- spec/features/schools/participants/add_participants/unhappy_path_can_validate_with_nino_spec.rb
- spec/features/schools/participants/add_participants/unhappy_path_cannot_validate_with_nino_spec.rb
- spec/features/schools/participants/transferring_participants/fip_to_fip/unhappy_path_cannot_validate_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/support/features/pages/schools/school_add_participant_wizard.rb
- Ticket: CST-2775
The content displayed in the Add ECT and Mentor journeys when a record can’t be found was misleading. It has now been revised for clarity.
- Updated the view page with the new content
|<img width="591" alt="Screenshot 2024-12-13 at 16 13 22" src="https://github.com/user-attachments/assets/7b89a05f-ab00-45ab-9d4d-7e539ef03928" />|<img width="587" alt="Screenshot 2024-12-13 at 16 13 07" src="https://github.com/user-attachments/assets/02566c52-2a5a-4d26-8162-573e869cfa07" />|
> [CST-2775] Revisit misleading content in the add participant journey

- .github/workflows/deploy.yml
Ahead of removing the environment to prevent other deploys causing issues while we tear down the environment.
> Disable deployment to separation

- Gemfile.lock
Reverts DFE-Digital/early-careers-framework#5391
> Revert "Bump nokogiri from 1.17.2 to 1.18.0"

- terraform/application/variables.tf
- Ticket: n/a
The db size is 32gb, prod is 64gb. We are maxing out the storage on the snapshot and it is not completing the restore.
Bump up the storage to match production to enable the restore to complete successfully.
>  Bump up snapshot database to match production 

- app/services/oneoffs/add_band_c.rb
- app/services/oneoffs/change_service_fees.rb
- app/services/oneoffs/migrate_declarations_between_statements.rb
- app/services/oneoffs/remove_fees_from_contracts.rb
- app/services/oneoffs/update_contracts.rb
- spec/services/oneoffs/add_band_c_spec.rb
- spec/services/oneoffs/change_service_fees_spec.rb
- spec/services/oneoffs/migrate_declarations_between_statements_spec.rb
- spec/services/oneoffs/remove_fees_from_contracts_spec.rb
- spec/services/oneoffs/update_contracts_spec.rb
- Ticket: [CPDLP-3894](https://dfedigital.atlassian.net/browse/CPDLP-3894)
Cohort 2022 is expected extended and late declarations from lead providers as part of the January 2025 statement.
During the assurance checks, they noticed that no declarations are attached to the cohort 2022 Jan 25 statement. Further investigation found that they are instead linked to the April 2025 statements.
- Put former NPQ service `MigrateDeclarationsBetweenStatements` back;
- Tweak it to make it valid for ECF declarations;
- Add `restrict_to_created_on_or_before` so we can filter declarations to be moved by created at date
Script to be run (tested in snapshot db - dry run true)
```
cohort = Cohort.find_by!(start_year: 2022)
migrator = Oneoffs::MigrateDeclarationsBetweenStatements
.new(
cohort:, …
```
> [CPDLP-3894] Add `MigrateDeclarationsBetweenStatements` service

- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v3/participant_declarations_controller.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3899
As part of our clean up of NPQ in ECF, we are scoping all endpoints and queries to ECF only. We need to also scope void/show declaration to ECF as well.
- For voiding declarations in v1/v2/v3 scope the queries to only allow voiding ECF declarations only and not NPQ;
- Tried to replace `participant_declaration_for_lead_provider` by `participant_declaration_query_scope` but the queries of the second are slightly different taking in consideration `induction records` & `partnerships` as well. That would allow past lead providers to void declarations currently with other lead providers;
- Single declaration endpoints are already scoped by ECF;
> [CPDLP-3899] Ensure Void/Show declarations are scoped to ECF declarations

- app/services/api/participant_declarations/index.rb
- app/services/api/v3/participant_declarations_query.rb
- docs/source/release-notes.html.md
- spec/services/api/participant_declarations/index_spec.rb
- spec/services/api/v3/participant_declarations_query_spec.rb
[Jira-3880](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345%2Cunassigned&selectedIssue=CPDLP-3880)
Currently, the `ParticipantDeclarationsQuery` filters declarations based only on an `active` induction_status. This prevents declarations from being surfaced for participants with a `completed` induction status.
- Update `ParticipantDeclarationsQuery` to include `completed` previous declarations
Update the `ParticipantDeclarationsQuery` to include `completed` declarations for a previous provider in addition to `active`.
TODO: testing
> Update `ParticipantDeclarationsQuery` to include `completed` previous

- .github/workflows/brakeman.yml
- Ticket: n/a
Brakeman is failing due to deprecated github action
Update `github/codeql-action/upload-sarif@v3` to v3 to avoid failures
> Update codeql action to v3 as v2 has been deprecated

- .github/workflows/deploy.yml
- Ticket: n/a
On merging to main brakeman fails due to permissions being added. We need to define a specific permission for it to run on staging
Add `  security-events: write` permission to allow breakman to run on staging
I ran this manually this will pass on staging [here](https://github.com/DFE-Digital/early-careers-framework/actions/runs/12688019924) as it passes on review
> Allow brakeman contents permission to upload file to github

- app/models/participant_declaration/ecf.rb
- app/models/participant_profile/ecf.rb
- config/analytics_blocklist.yml
- db/migrate/20250110125608_add_temp_type_to_participant_declarations.rb
- db/schema.rb
- spec/models/participant_declaration/ecf_spec.rb
- spec/models/participant_profile/ecf_spec.rb
We are splitting `ECF` declarations into `ECT` and `Mentor` declarations. As calculating the declaration type takes a few minutes, in order to do it without downtime or data errors we are going to add a `temp_type` column that we can populate and maintain ahead of the switch.
The original/complete PR is #5404.
- Add and maintain `temp_type` on `ParticipantDeclaration::ECF`
Once shipped, we can then switch the data of `new_type` to `type` quickly and start referencing the new column.
These changes introduce the the `temp_type` field with correct subtype of declaration (ECT/Mentor). We backfill existing and set on new declarations. If a profile changes type we will update the declaration for consistency.
The next steps …
> Add and maintain `temp_type` on `ParticipantDeclaration::ECF`

- app/models/participant_profile/npq.rb
- Session restore errors:
- https://dfe-teacher-services.sentry.io/issues/6220712622/?alert_rule_id=7310304&alert_type=issue&environment=production&notification_uuid=c37d10d9-b6f2-47cf-a1ce-9715b8b0922b&project=5748989&referrer=slack
- https://dfe-teacher-services.sentry.io/issues/6220727360/?alert_rule_id=14507789&alert_type=issue&environment=production&notification_uuid=63ac6e10-d39a-48fe-8f78-6008de1ad4b8&project=5748989&referrer=slack
* To avoid these errors, reverting `ParticipantProfile::NPQ`
> Revert ParticipantProfile::NPQ to avoid session restore errors

- app/models/finance/statement/ecf.rb
- app/models/lead_provider.rb
- app/models/mentor_call_off_contract.rb
- app/services/importers/create_mentor_call_off_contract.rb
- app/services/importers/create_new_ecf_cohort.rb
- config/analytics_blocklist.yml
- db/legacy_seeds/test_data.rb
- db/migrate/20250114144917_create_mentor_call_off_contracts.rb
- db/new_seeds/base/add_contracts.rb
- db/schema.rb
- spec/factories/mentor_call_off_contracts.rb
- spec/fixtures/files/importers/mentor_contract_csv_data.csv
- spec/models/call_off_contract_spec.rb
- spec/models/finance/statement/ecf_spec.rb
- spec/models/lead_provider_spec.rb
- spec/models/mentor_call_off_contract_spec.rb
- spec/services/importers/create_mentor_call_off_contract_spec.rb
- spec/services/importers/create_new_ecf_cohort_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3933
- recreated from: https://github.com/DFE-Digital/early-careers-framework/pull/5437
* Created `MentorCallOffContract` model
* Created `Importers::CreateMentorCallOffContract` service
* Spec
> [CPDLP-3933] Add Mentor call off contract to ECF

- .github/CODEOWNERS
- .github/workflows/refresh_knapsack_manifest.yml
[Jira-3946](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3946)
As we add/remove tests the manifest becomes gradually outdated and as a result Knapsack can't distribute the test suite across workers as efficiently.
We want to add a workflow to recompute the Knapsack manifest and raise a pull request with the changes. This can be triggered manually and will also run on a weekly schedule.
- Add workflow for refreshing the Knapsack manifest
The action to create a pull request also supports assigning a team, but in order to do this you need to generate a personal access token. To avoid coupling the action to a user account I haven't done this, but if we have access to a generic 'dfe user' we could do this in the future.
Example pull request: …
> Add workflow for refreshing the Knapsack manifest

- app/models/participant_declaration/ecf.rb
- app/models/participant_profile/ecf.rb
- db/migrate/20250110134507_populate_type_from_temp_type_on_participant_declarations.rb
- spec/models/participant_declaration/ecf_spec.rb
- spec/models/participant_profile/ecf_spec.rb
- spec/services/record_declaration_spec.rb
The original/complete PR is #5404.
Depends on #5429.
Now that we are using the `temp_type` field, we can backfill the `type` field and maintain it ahead of finally switching over.
- Add migration to populate type from temp_type
Add a migration to populate the `type` field from the backfilled/populated `temp_type`, which will contain the `ECT` or `Mentor` declaration type.
- Populate type when declaration changes
To ensure `type` remains up to date while we are still referencing `temp_type` we need to update it `after_commit`.
Once this has shipped we can switch back to the `type` field and remove the `temp_type` field. #5430
> Add migration to populate type from temp_type

- app/services/record_declaration.rb
- config/locales/en.yml
- spec/services/record_declaration_spec.rb
[Jira-3907](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3907)
We have a new `mentor_funding` attribute on `Cohort`. Going forward we want to prevent mentors from adding `retained-x` declarations to a `mentor_funding` cohort. We should continue to allow `retained-x` declarations for ECTs.
- Prevent retained declarations for mentors in funded cohorts
Update `RecordDeclaration` with appropriate validation.
Error message updated to Mark's copy.
> Prevent retained declarations for mentors in funded cohorts

- app/models/participant_declaration/ecf.rb
- app/serializers/archive/participant_declaration_serializer.rb
- app/serializers/finance/ecf/duplicate_serializer.rb
- app/services/api/v3/participant_declarations_query.rb
- app/services/finance/ecf/assurance_report/query.rb
- app/views/admin/participants/_declarations_history.erb
- app/views/admin/participants/declaration_history/show.html.erb
- spec/models/participant_declaration/ecf_spec.rb
- spec/serializers/archive/participant_declaration_serializer_spec.rb
- spec/services/finance/ecf/assurance_report/query_spec.rb
- spec/services/record_declaration_spec.rb
Now that the `type` field is backfilled and up to date, we can switch back to it and away from `temp_type`, which will be removed in a follow up PR.
- Revert "Switch inheritance column to temp_type for ECF declarations"
This reverts commit https://github.com/DFE-Digital/early-careers-framework/commit/3aa79f25f00998710b22b767165ac53d3f7c3ecb.
- Populate temp_type from type
In case we need to revert, we can keep `temp_type` up to date in the same way we kept `type` up to date.
> Switch inheritance column back to `type`

- config/analytics_blocklist.yml
- db/migrate/20250110135952_drop_temp_type_from_participant_declarations.rb
- db/schema.rb
This field was used to store the `type` of declarations temporarily as we migrated from `ParticipantDeclaration::ECF` to `ECT` and `Mentor` subtypes. It is no longer needed.
- Drop `temp_type` field from `ParticipantDeclaration`
This is the last step in the work to migrate to declaration subtypes.
> Drop `temp_type` field from `ParticipantDeclaration`

- app/models/participant_declaration.rb
As this is being dropped, strong migrations cancels the migration unless we ignore it.
> Ignore `temp_type` column

- config/analytics_blocklist.yml
- db/migrate/20250110135952_drop_temp_type_from_participant_declarations.rb
- db/schema.rb
Reverts DFE-Digital/early-careers-framework#5430
We need to deploy the ignored column then redeploy the migration with `safety_assured`
> Revert "Drop `temp_type` field from `ParticipantDeclaration`"

- config/analytics_blocklist.yml
- db/migrate/20250110135952_drop_temp_type_from_participant_declarations.rb
- db/schema.rb
Reverts this revert #5467 to re-roll out the migration now that the column is ignored.
> Drop `temp_type` field from `ParticipantDeclaration` take #2

- .github/actions/backup-and-restore-snapshot-database/action.yml
[Jira-3954](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3954)
We have an issue with our snapsort restore workflow whereby if the psql operation errors it will continue and the workflow will succeed, even though it was not successful.
We want to fail the workflow if the restore has errors.
- Ensure CI workflow fails when psql restore encounters an error
We can do this by passing the `ON_ERROR_STOP` flag.
I ran the restore a couple of times off this branch and it was successful, I haven't been able to trigger an error - its something I think we'll just need to keep an eye out for after its merged to ensure its behaving as expected.
> Ensure CI workflow fails when psql restore encounters an error

- .github/workflows/deploy.yml
- .github/workflows/lead_provider_openapi_check.yml
- docs/lib/govuk_tech_docs/open_api/renderer.rb
- docs/spec/govuk_tech_docs/open_api/renderer_spec.rb
- swagger/v1/api_spec.json
- swagger/v2/api_spec.json
- swagger/v3/api_spec.json
[Jira-3960](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3960)
Historically we haven't been able to auto-generate the v3 API documentation as it results in the links in the api-reference page becoming out of order.
We want to be able to auto-generate all the API documentation going forward so that we don't have to maintain it manually.
- Sort the links in the api-reference sidebar
Sort the links by a predefined order for each category of endpoints. There are minor differences with the ordering within the groups when compared to production. I opted for ordering by group and then by the length of the path, but maybe alphabetical would make more sense?
- Auto-generate swagger documentation
Now that the order of the sidebar links is fixed, we can auto-generate the API documentation. …
> Auto-generate swagger documentation

- db/migrate/20250124134039_add_type_index_to_participant_declarations.rb
- db/schema.rb
- Ticket: [CPDLP-3952](https://dfedigital.atlassian.net/browse/CPDLP-3952)
We don’t have an index on the type on participant declarations.
- Add an index to the participant declaration field type
Snapshot db:
```
== 20250124134039 AddTypeIndexToParticipantDeclarations: migrating ============
-- add_index(:participant_declarations, :type, {:algorithm=>:concurrently})
-> 0.7996s
== 20250124134039 AddTypeIndexToParticipantDeclarations: migrated (1.2468s) ===
```
[CPDLP-3952]: https://dfedigital.atlassian.net/browse/CPDLP-3952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3952] Add index to participant declaration type field

- app/services/change_schedule.rb
- spec/services/change_schedule_spec.rb
[Jira-3953](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3953)
We have noticed lead providers getting a 500 error on the `change-schedule` endpoint when they attempt to change the schedule of a participant not associated with them via their induction records (so `relevant_induction_record` is `nil`).
We want to capture this exception and raise a helpful error message instead.
- Fix 500 error on change schedule endpoint
On a normal change schedule operation one or more validators will catch this and return an error to the lead provider. If they are changing schedule due to payments being frozen, however, and the participant has no billable declarations, then the error occurs when …
> Fix 500 error on change schedule endpoint

- db/migrate/20250127140541_remove_npq_registration_start_date_from_cohorts.rb
- db/schema.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3913
- Rebasing from: https://github.com/DFE-Digital/early-careers-framework/pull/5461
* Remove column `cohorts.npq_registration_start_date`
> [CPDLP-3913] migration to remove cohorts.npq_registration_start_date

- .github/workflows/rspec.yml
- spec/features_helper.rb
We are finding that our tests hang in CI randomly on a consistent error:
```
Net::ReadTimeout:
Net::ReadTimeout with #<TCPSocket:(closed)>
```
We want to investigate why this happens and see if we can fix it to make our CI more reliable.
- Minor tweaks to Capybara/chrome settings
In an attempt to fix/reduce the impact of feature spec failures where we get a `Net:HTTP` timeout error on multiple tests, resulting in a long time until the suite fails this commit will:
```
- Add additional args to reduce flakiness (based on various GitHub issues around similar problems)
- Increase the client open/read timeout
- Remove the allowed external domain (in case its rate limiting us/causing the timeouts)
- Increase the default Capybara wait time
```
- Split feature specs in CI and fail fast
So that we …
> Attempt to fix/mitigate flakey Capybara feature specs

- .github/workflows/refresh_knapsack_manifest.yml
GitHub prevents the PRs raised from a GitHub action from triggering further CI actions by default. We need to use another authentication method than the default `GITHUB_TOKEN`.
- Fix Knapsack manifest refresh PRs
Switch to GitHub App authentication This will allow the CI checks will be ran on the PR raised by the `create-pull-request` action.
[Example PR raised by run](https://github.com/DFE-Digital/early-careers-framework/pull/5477)
> Fix Knapsack manifest refresh PRs

- app/controllers/admin/schools/participants_controller.rb
- app/models/induction_record.rb
- spec/models/induction_record_spec.rb
When an ECT has a `completed` induction status they disappear from the list of participants in a school for an admin in the admin UI.
Create a new scope to include `completed` induction status and use this for the admin school participants view.
I've set 1 participant as completed, sign in to the review app as admin and the completed participant can be seen in the list [school participants](https://cpd-ecf-review-5498-web.test.teacherservices.cloud/admin/schools/077443-samirastad-high-school/participants)
> Show completed ECTs in list of school participants in admin UI

- app/services/void_participant_declaration.rb
- spec/services/void_participant_declaration_spec.rb
- Ticket: [CPDLP-3968](https://dfedigital.atlassian.net/browse/CPDLP-3968)
Contract managers are not able to see voids for ineligible declarations in the CSV extracts.
- Amend void declarations service to include `ineligible` statement line items, so the record state is updated to `voided`;
- Removed `submitted` line items from the logic as it's not a valid state for `StatementLineItem`. Checked prod and there's no `submitted` line itens currently in the db;
- Improved tests coverage to cover all 3 states in the logic;
[CPDLP-3968]: https://dfedigital.atlassian.net/browse/CPDLP-3968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3968] Amend void declarations service to include ineligible statement line items

- app/models/participant_profile.rb
- config/analytics.yml
[Jira-4011](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4011)
This is no longer used; we are ignoring it ahead of dropping the column in a follow up PR.
- Ignore `npq_course_id` on `ParticipantProfile`
- Remove npq_course_id from dfe-analytics
Follow on PR: #5500.
> Ignore `npq_course_id` on `ParticipantProfile`

- db/migrate/20250130101804_remove_npq_course_id_from_participant_profiles.rb
- db/schema.rb
[Jira-4011](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4011)
This column is no longer referenced and is safe to drop.
- Drop `npq_course_id` from `ParticipantProfile`
Depends on #5499.
> Drop `npq_course_id` from `ParticipantProfile`

- app/models/participant_profile.rb
Now that we have dropped this column we can stop ignoring it.
- Remove npq_course_id as ignored column from ParticipantProfile
Depends on #5500.
> Remove npq_course_id as ignored column from ParticipantProfile

- .github/workflows/deploy_to_environment.yml
- Ticket: n/a
We need allow manual deployments to envs as terraform apply in the console now requires gcloud logins as well where not all developers will have gcloud accounts or access.
Add a new workflow where we can select an environment to deploy to, select the branch we wish to deploy and it will deploy manually using the github actions without any CI tests.
Review environment has not been included as it is not required.
This was tested on the maintenance workflow [here](https://github.com/DFE-Digital/early-careers-framework/actions/runs/13060359728/job/36441835650), where we were able to deploy successfully. This also required work on the DfE github [actions](https://github.com/DFE-Digital/github-actions/pull/114), thanks @saliceti
> Add manual deployment Github workflow

- app/mailers/school_mailer.rb
- app/services/withdraw_participant.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/withdraw_participant_spec.rb
[Jira-3979](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3979)
When we withdraw a participant we send an email with details of the school they were withdrawn from. Currently, however, we take the participant profile -> school, which is not always the school relevant to the withdraw action. We should instead be taking the school from the relevant induction record, in case the participant has transferred schools in the past.
- Send correct school name in withdrawn participant email
Update `WithdrawParticipant` action to take the school from the `relevant_induction_record` instead of the `participant_profile`.
There is a temp commit that adds a GOV.UK notify API key for testing to the review credentials.
There are scripts attached to the ticket to setup the test scenario.
> Send correct school name in withdrawn participant email

- docs/source/get-started.html.md
Adding a section to the 'Get started' guidance page that describes to lead providers our best practice suggestions around syncing data via the API.
> Add syncing guidance to get-started page

- app/controllers/concerns/api_pagination.rb
- app/services/api/v3/ecf/participants_query.rb
- app/services/api/v3/participant_declarations_query.rb
- config/initializers/pagy.rb
[Jira-3985](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3985)
As we don't expose the total count we can switch from `pagy` to `pagy_countless`, which should be more efficient at paginating large data sets. 
- Switch to `pagy_countless` for API pagination
Test scripts used to verify participant/declarations queries which were the two that had to change for this update:
```
ActiveRecord::Base.connection.execute("SET statement_timeout to 0")
require "pagy"
require "pagy/extras/countless"
require "pagy/extras/overflow"
require "pagy/extras/array"
include Pagy::Backend
cpd_lead_provider = CpdLeadProvider.find_by(name: "Ambition Institute")
lead_provider = cpd_lead_provider.lead_provider
paginate_countless = ->(scope, page:) do
_pagy, paginated_records = pagy_countless(scope, limit: …
```
> Switch to `pagy_countless` for API pagination

- terraform/application/databases.tf
- terraform/application/variables.tf
- terraform/application/workspace_variables/migration.tfvars.json
- terraform/application/workspace_variables/production.tfvars.json
- Ticket: https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-3984
To improve performance we'd like to bump up the IOPS on the production DB
- Add new performance tier variable `azure_storage_tier` to postgres dbs in terraform
- Set `azure_storage_tier` in production to P30 (5000 iops) to match some spikes we've seen. We'll monitor to see if this improves things
- Set `azure_storage_tier` in migration to P6 to match it's current state
- Default to P4 as that's the value on other envs
Before merging I'll ensure that nothing changes apart from production dbs. I'll also reset migration back to P6 (I can't in the next 12 hours as I've already tested P30 on it)
I've tested this on migration, and bumped the IOPS, it took around 6 minutes to apply …
> Bump IOPS of database

- app/models/lead_provider.rb
- db/new_seeds/base/add_environment_specific_data.rb
- db/new_seeds/base/add_lead_providers_and_cips.rb
- db/new_seeds/scenarios/lead_providers/lead_provider.rb
- db/new_seeds/scenarios/participants/transfers/fip_to_fip.rb
- db/new_seeds/scenarios/users/lead_provider_user.rb
- spec/factories/seeds/cpd_lead_provider_factory.rb
- spec/factories/seeds/lead_provider_factory.rb
- spec/services/induction/find_by_spec.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
- Ticket: [CPDLP-3958](https://dfedigital.atlassian.net/browse/CPDLP-3958)
We currently have a set of known providers in production, however in seeds we create many other providers unnecessarily and the data for contracts and statements is not set up properly.
Ensure all seed data and participants for both ECTs/Mentors is attached to only the known lead providers.
[CPDLP-3958]: https://dfedigital.atlassian.net/browse/CPDLP-3958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3958] Remove extra lead providers from seeds

- README.md
- app/services/dqt_record_check.rb
- app/services/importers/create_call_off_contract.rb
- app/services/importers/create_cohort.rb
- spec/fixtures/files/importers/cohort_csv_data.csv
- spec/fixtures/files/importers/contract_csv_data.csv
- spec/services/importers/create_call_off_contract_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4010
- Add magic date for cohort 25;
- So a valid participant in cohort 2025 can be created with date of birth 25/01/1900
- Include missing header to cohorts importer;
- Do not create band D when there is no band D data in call off contracts csv;
Review app
> [CPDLP-4010] Add tweaks for mentor funding creation in cohort 2025

- app/services/importers/create_cohort.rb
- config/analytics.yml
- db/data/cohorts/cohorts.csv
- db/migrate/20250211191336_add_detailed_evidence_types_to_cohort.rb
- db/schema.rb
- spec/factories/cohorts.rb
- spec/fixtures/files/importers/cohort_csv_data.csv
- spec/services/importers/create_cohort_spec.rb
- Ticket: [CPDLP-3931](https://dfedigital.atlassian.net/browse/CPDLP-3931)
- Add a new boolean field to cohort which defaults to false, which can be set to true on 2025 for evidence types
- Add this field to dfe analytics
- Add this field to the factories/seed data
- Add this field to creating a cohort logic and csv
- Add this field to the confluence new cohort [documentation](https://dfedigital.atlassian.net.mcas.ms/wiki/spaces/CPD/pages/3883663396/Create+new+ECF+cohort)
[CPDLP-3931]: https://dfedigital.atlassian.net/browse/CPDLP-3931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-3931] Add new field to cohort to drive the new evidence types logic

- config/environments/production.rb
We have two `session_store` configurations in the app; one in `production.rb` and one in `initializers/session_store.rb`. As there can be only one we need to determine which is in use and remove the unused/overridden reference.
- Remove unused cookie session store from `production.rb`
We define a `cookie_store` in `production.rb`, however this is later overridden by the `session_store.rb` initializer, which specifies an `active_record_store`.
It has been confirmed on the production rails console that the active record store is in use:
```
irb(main):001> Rails.application.config.session_store
=> ActionDispatch::Session::ActiveRecordStore
```
The cookies have also been checked in production to ensure the `_early_career_framework_session` cookie key is not present (only the `_ecf_session` …
> Remove unused cookie session store from `production.rb`

- app/controllers/appropriate_bodies/participants_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/schools/cohorts/appropriate_body_controller.rb
- app/services/pages/template_resolver.rb
- config/brakeman.ignore
- spec/features/schools/add_appropriate_body_spec.rb
- spec/rails_helper.rb
- spec/requests/pages_spec.rb
- spec/requests/schools/core_programme/induction_tutor_materials_spec.rb
- spec/services/pages/template_resolver_spec.rb
[Jira-3987](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3987)
We have a number of `brakeman` security warnings in the app that we want to review and address where appropriate.
- Fix dynamic render path brakeman warning
We have a warning due to dynamically rendering an unsanitised page parameter.
Extract template resolving to `TemplateResolver` service and only allow rendering of valid templates in the `app/views/page` directory.
- Remove unused permitted filter attributes
We only appear to filter on `query` and `status` in the `AppropriateBodies::ParticipantsFilter` service.
The `role` attribute is flagged by Brakeman (albeit as a false positive), but as its not used we can just remove it to silence the warning.
- Sanitize confirmation page rendering
We only want to allow …
> Address brakeman warnings

- .github/workflows/rspec.yml
- Ticket: [CPDLP-4023](https://dfedigital.atlassian.net/browse/CPDLP-4023)
Currently feature specs fail intermittently on CI with the failure `Net::ReadTimeout`. This is a very common error and can be seen consistently on the workflows. 
As suggested on https://github.com/teamcapybara/capybara/issues/2770, we'll pin the version of chrome to 127 in order to try and fix `Net::ReadTimeout` in specs in CI.
[CPDLP-4023]: https://dfedigital.atlassian.net/browse/CPDLP-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4023] Pin version of chrome to 127 in order to try and fix `Net::ReadTimeout` in specs in CI

- app/serializers/finance/ecf/assurance_report/csv_serializer.rb
- spec/serializers/finance/ecf/assurance_report/csv_serializer_spec.rb
[Jira-4028](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4028)
We currently expose the `pupil_premium_uplift` and `sparsity_uplift` attributes in the assurance report CSVs, however we want to add an additional `Uplift Payable` column in the CSV, which is `true` if the participant qualifies for uplift payments (if either `pupil_premium_uplift` or `sparsity_uplift` are `true`).
- Expose uplift payable in assurance report CSV
Adds test coverage for `CsvSerializer`.
> Expose uplift payable in assurance report CSV

- app/services/valid_test_data_generators/mentor_ect_generator.rb
- lib/tasks/sandbox_data.rake
- spec/services/valid_test_data_generators/mentor_ect_generator_spec.rb
[Jira-3972](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/CPDLP/boards/87?assignee=712020%3A5b5839dc-e4d6-4df5-9dd6-627cc49fe345&selectedIssue=CPDLP-3972)
In order to test the mentor funding feature in sandbox we will need ECT and mentor records to be created that are eligible for funding.
- Add ECT/mentor records to sandbox for testing
This seed is a paired down version of the `ECFLeadProviderPopulator` that aims to only create ECTs/mentors without adding additional school/partnership records.
> Add ECT/mentor records to sandbox for testing

- spec/presenters/admin/participant_presenter_spec.rb
- Ticket: N/A
Spec `spec/presenters/admin/participant_presenter_spec.rb:314` is flakey.
Fix flakey spec above.
> Fix flakey spec `spec/presenters/admin/participant_presenter_spec.rb:314`

- docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
- docs/source/release-notes.html.md
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ParticipantDeclarationPost2024ECTDataRequest.yml
- swagger/v1/component_schemas/ParticipantDeclarationPost2024MentorDataRequest.yml
- swagger/v1/component_schemas/ParticipantDeclarationPre2025DataRequest.yml
- swagger/v1/component_schemas/ParticipantDeclarationRequest.yml
- swagger/v2/api_spec.json
- swagger/v2/component_schemas/ParticipantDeclarationPost2024ECTDataRequest.yml
- swagger/v2/component_schemas/ParticipantDeclarationPost2024MentorDataRequest.yml
- swagger/v2/component_schemas/ParticipantDeclarationPre2025DataRequest.yml
- swagger/v2/component_schemas/ParticipantDeclarationRequest.yml
- swagger/v3/api_spec.json
- swagger/v3/component_schemas/ParticipantDeclarationPost2024ECTDataRequest.yml
- swagger/v3/component_schemas/ParticipantDeclarationPost2024MentorDataRequest.yml
- swagger/v3/component_schemas/ParticipantDeclarationPre2025DataRequest.yml
- swagger/v3/component_schemas/ParticipantDeclarationRequest.yml
[Jira-4013](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4013)
The new ECF framework requires providers to only submit started and completed declarations for mentors and started, retained and completed for ECT’s. This is different to how our current spec presents information. We’ll need our spec to dual run business logic from pre-2025 and 2025 onwards.
- Add release note for unfunded mentors
Add a release note to details the changes for recording declarations against unfunded mentors.
- Allow anyOf on data attributes in API docs
Currently, if you set a `data` attribute up with an `anyOf` value set it will output the "It conforms to" text as well as the "This conforms to" text. This is due to `data` being a special attribute whereby we usually link to another, single schema.
To …
> Update api docs for unfunded mentors

- app/middlewares/session_restore_error_rescue_middleware.rb
- config/application.rb
- spec/middlewares/session_restore_error_rescue_middleware_spec.rb
- spec/requests/users/sessions_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3956
* New middleware `SessionRestoreErrorRescueMiddleware`
* Added to `applications.rb`
* Rescue from `ActionDispatch::Session::SessionRestoreError` error, delete session cookie and reset
> [CPDLP-3956] Middleware to catch SessionRestoreError and clear the session

- app/services/valid_test_data_generators/ecf_lead_provider_populater.rb
- app/services/valid_test_data_generators/mentor_ect_generator.rb
- spec/services/valid_test_data_generators/mentor_ect_generator_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3943
We want to create participants linked to eligible schools as only eligible schools are visible in the admin dashboards and returned in the API responses.
- Create eligible schools when running the mentor/ect valid test data generators;
- Make sure we select the eligible school when creating the school cohort in the generator;
```
ActiveRecord::Base.transaction do
names = [
"Ambition Institute",
]
cohorts = Cohort.between_years(2021, 2025)
names.product(cohorts) do |name, cohort|
ValidTestDataGenerators::ECFLeadProviderPopulater.call(name:, cohort:, total_schools: 1, participants_per_school: 0)
ValidTestDataGenerators::MentorECTGenerator.call(name:, cohort:, number: 5)
end
end
```
> [CPDLP-3943] Create eligible schools and partnerships on the mentor/ect valid test data generators

- docs/source/changes-for-the-2025-2026-academic-year.html.md
- Ticket: n/a
Add early indicators guidance for providers in the API docs
Content has been done by Mark and can be viewed here https://cpd-ecf-review-5573-web.test.teacherservices.cloud/api-reference/changes-for-the-2025-2026-academic-year.html#changes-for-the-2025-26-academic-year
> Add early indicators for providers in 2025/2026 in API guidance

- app/components/finance/statements/payment_breakdown/ecf.html.erb
- app/services/finance/ecf/statement_calculator.rb
- spec/components/finance/statements/payment_breakdown/ecf_spec.rb
- spec/features/finance/payment_breakdown_spec.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
[Jira-4047](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4047)
Following a review of the screens with the contracts and assurance teams there are some small changes to make to the current front end for 2024 and earlier cohorts.
We want to display the clawed back declarations count in the finance statement summary. We also want to always show the extended declaration counts, even when 0.
- Add clawed back count to finance statements
The clawed back declarations are fudged due to the factory not playing ball; getting them on the November statement was turning into a lot of test setup, so I opted to manually transition submitted declarations (the count functionality is tested independently in the calculator).
> Add clawed back count to finance statements

- docs/config.rb
- docs/lib/markdown_renderer.rb
- docs/source/api-reference/stylesheets/screen.css.scss
- docs/source/layouts/custom_core.erb
- docs/source/release-notes.html.md
- docs/spec/lib/markdown_renderer_spec.rb
[Jira-4076](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4076)
We want the ability to tag release notes so that providers can easily distinguish the type of change being released.
- Support tagging in release notes
Add custom `MarkdownRenderer` that can interpret our tag syntax, for example: `[#tag-1 #tag-2]`.
Update Middleman config to use our custom markdown rendering.
Add CSS for slightly smaller govuk-style tags.
Add page title to body class so that we can easily add targetted CWSS.
Update latest release notes with tags.
Example of all tags (review app only has tags on the latest two release notes, as per the ticket):
> Support tagging in release notes

- app/services/delivery_partners/participants_filter.rb
- spec/features/delivery_partners/participants_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
- spec/services/delivery_partners/participants_filter_spec.rb
[Jira-4060](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4060)
We want to exclude participants in the 2025 cohort from the delivery partners participants view. We also want to hide the 2025 and later cohorts from the academic year dropdown.
This is intended to encourage lead providers to carry out their contractual duties and ensure there is no ownness on the DfE to share details of participants in 2025 and later cohorts.
- Exclude 2025 and later participants from delivery partners
Participant created in 2025 cohort for `Koelpin-Homenick` DP:
```
school_cohort = FactoryBot.create(:school_cohort, cohort: Cohort.find_by!(start_year: 2025))
delivery_partner = DeliveryPartner.find("8d2875ca-4727-48b7-8adf-9a47fa9debdc")
lead_provider = LeadProvider.find_by(name: "Ambition Institute") …
```
> Exclude 2025 and later participants from delivery partners

- app/controllers/api/v1/participant_declarations_controller.rb
- docs/source/release-notes.html.md
- spec/requests/api/v2/participant_declarations_spec.rb
> ⚠️ depends on #5575 being merged for the release note tag to work
[Jira-3728](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3728)
We pass an explicit v1 serializer on the create action for declarations which is inherited in the v2 controller. For other actions we override with the `serializer_class` hook. This results in the wrong data being returned for the v2 create declarations endpoint.
- Use correct serializer on v2 POST declarations endpoint
Ensure correct serializer is used in v2 create declarations action.
Add test coverage to prevent this kind of regression in the future.
> Use correct serializer on v2 POST declarations endpoint

- config/initializers/content_security_policy.rb
- Ticket: N/A
We're seeing CSP reports blocking calls to Sentry API url ie: `https://o225781.ingest.sentry.io/api`
- Relax CSP `connect_src` config including the Sentry URL;
> Add sentry url to CSP config

- app/services/finance/ecf/banding_calculator.rb
- app/services/finance/ecf/ect/banding_calculator.rb
- app/services/finance/ecf/ect/output_calculator.rb
- app/services/finance/ecf/ect/statement_calculator.rb
- app/services/finance/ecf/mentor/output_calculator.rb
- app/services/finance/ecf/mentor/statement_calculator.rb
- app/services/finance/ecf/output_calculator.rb
- app/services/finance/ecf/statement_calculator.rb
- spec/factories/finance/statements.rb
- spec/services/finance/ecf/banding_calculator_spec.rb
- spec/services/finance/ecf/ect/banding_calculator_spec.rb
- spec/services/finance/ecf/ect/output_calculator_spec.rb
- spec/services/finance/ecf/ect/statement_calculator_spec.rb
- spec/services/finance/ecf/mentor/output_calculator_spec.rb
- spec/services/finance/ecf/mentor/statement_calculator_spec.rb
- spec/services/finance/ecf/output_calculator_spec.rb
- spec/services/finance/ecf/statement_calculator_spec.rb
- spec/support/shared_examples/finance_statement_calculators_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4019
* New `BandingCalculator` for ECF and ECT
* Output calculators updated to use `BandingCalculator`
* Some refactoring to maintain consistency between ECF, ECT and Mentor output calculators
* Most of the calculation tests moved to banding calculator spec
* Output and statement calculators refactored and simplified
> [CPDLP-4019] Tech debt - Move banding logic into a banding calculator

- .github/workflows/refresh_knapsack_manifest.yml
- .github/workflows/refresh_migration_database.yml
- .github/workflows/restore_snapshot_database.yml
- .github/workflows/rspec.yml
Ubuntu 20 image has been deprecated https://github.com/actions/runner-images/issues/11101 this is causing failures on our workflows as they use a mix of latest and different versions
- Ticket: n/a
Update all workflow ubuntu images to latest to avoid failures
thanks @mooktakim for finding the issue and @leandroalemao for flagging :)
> Update to latest ubuntu image as ubuntu 20 has been deprecated

- app/models/participant_declaration.rb
- config/analytics.yml
- db/migrate/20250228133019_add_voided_by_and_voided_at_to_participant_declarations.rb
- db/migrate/20250228135355_add_voided_by_user_foreign_key_to_participant_declarations.rb
- db/migrate/20250228135429_validate_participant_declarations_voided_by_user_foreign_key.rb
- db/schema.rb
- spec/models/participant_declaration_spec.rb
[Jira-4084](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4084)
We want to maintain a record of who voided a declaration when it happens through the user interface.
- Add `voided_at` and `voided_by_user` to `ParticipantDeclaration` 
These will be `nil` when a lead provider has voided the declaration via the API.
The `voided_at` column appears to have been part of the model years ago, which is why it was later ignored - see #2320 - reversing that change here as we re-introduce it.
> Add `voided_at` and `voided_by_user` to `ParticipantDeclaration`

- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v3/participant_declarations_controller.rb
- app/services/finance/clawback_declaration.rb
- app/services/importers/clawbacks.rb
- app/services/void_participant_declaration.rb
- lib/participant_profile_deduplicator.rb
- spec/factories/participant_declaration.rb
- spec/services/finance/clawback_declaration_spec.rb
- spec/services/finance/ecf/banding_calculator_spec.rb
- spec/services/finance/ecf/ect/banding_calculator_spec.rb
- spec/services/finance/ecf/mentor/output_calculator_spec.rb
- spec/services/importers/clawbacks_spec.rb
- spec/services/record_declaration_spec.rb
- spec/services/statements/mark_as_paid_spec.rb
- spec/services/void_participant_declaration_spec.rb
> ⚠️ depends on #5580
When we void a declaration manually via the admin interface we want to track the user that performed the void and the time that it was voided. 
- Update `VoidParticipantDeclaration` to support `voided_by_user`
We have `voided_at` and `voided_by_user` as attributes on the `ParticipantDeclaration` model that we can use.
Add a `voided_by_user` required parameter to the `VoidParticipantDeclaration` service initializer and update current usage of the service to pass `nil` (to retain current behaviour).
When we come to expose this in the admin interface we can pass the currently signed in user. If a user is provided we will populated `voided_by_user` and set `voided_at` to the current time.
In the ticket and during our discussion we agreed to wrap this in a form object …
> Update `VoidParticipantDeclaration` to support `voided_by_user`

- app/models/call_off_contract.rb
- app/services/oneoffs/mark_contracts_as_unused.rb
- spec/factories/call_off_contract.rb
- spec/models/call_off_contract_spec.rb
- spec/services/oneoffs/mark_contracts_as_unused_spec.rb
[Jira-4125](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4125)
Due to historical/manual changes to contract data over the years we are in a position where we have a number of contracts that are either duplicates or are unused (i.e. not referenced by any financial statements).
- Add not_flagged_as_unused scope to CallOffContract
We will be referencing the used/unused status of call off contracts outside the oneoff service to prefix them as `unused_`, so it makes sense to keep the scope and terminology in the model itself.
I expect when we come to migrate the contract data we will add a `not_flagged_as_unused` scope to get the contracts that are applicable to migrate over.
- Add service to mark CallOffContract records as unused
Add `Oneoffs::MarkContractsAsUnused` service to find …
> Add service to mark call off contracts as unused

- app/controllers/concerns/relaxed_content_security_policy.rb
- app/controllers/finance/ecf/statements_controller.rb
- app/controllers/privacy_policies_controller.rb
- app/controllers/schools/cohort_setup_controller.rb
- app/views/layouts/_width_container.html.erb
- app/views/schools/cohort_setup/appropriate_body.html.erb
- config/initializers/content_security_policy.rb
- Ticket: [CPDLP-4054](https://dfedigital.atlassian.net/browse/CPDLP-4054)
As part of [this ticket](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4053) we updated the CSP report-only header for the API and documentation/admin pages.
Now that time has passed with this in production - assuming there are no reported violations in Sentry - we want to enforce the changes by enabling the CSP header.
- Relax CSP policy;
- The CSP header is being served and matches the report only configuration;
[CPDLP-4054]: https://dfedigital.atlassian.net/browse/CPDLP-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4054] Relax Content Security Policy in the app

- app/assets/stylesheets/application.sass.scss
- app/controllers/admin/participants/change_name_controller.rb
- app/controllers/admin/participants/induction_records_controller.rb
- app/controllers/admin/participants/school_transfer_controller.rb
- app/controllers/application_controller.rb
- app/controllers/finance/ecf/participant_declarations/void_controller.rb
- app/controllers/finance/participants_controller.rb
- app/helpers/finance_helper.rb
- app/models/participant_declaration.rb
- app/views/finance/ecf/participant_declarations/void/new.html.erb
- app/views/finance/participants/_declaration.html.erb
- app/views/layouts/_width_container.html.erb
- app/views/layouts/_width_container_wide.html.erb
- app/views/layouts/basic.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/finance/ecf/participant_declarations/void_spec.rb
- spec/helpers/finance_helper_spec.rb
- spec/requests/finance/ecf/participant_declarations/void_spec.rb
- spec/support/features/page_assertions_helper.rb
[Jira-4088](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4088)
At present declarations can only be voided directly by a Lead Provider or through a developer after a support request being made. This ends up causing lengthy lead times before a resolution can be reached, either delaying payment or creating need for further manual intervention.
To alleviate the issues we want to allow finance users to be able to void applicable declarations through the finance dashboard.
- Extract voidable states into constant
Extracting and exposing as a constant as we need to be able to reference these states externally to determine if a declaration is voidable.
- Add ability to void declarations in finance dashboard
Add `Void` link to the participant declarations if they are in a voidable state …
> Enable voiding of declarations via the finance dashboard

- app/models/participant_profile/ecf.rb
- spec/services/change_schedule_spec.rb
- spec/support/shared_examples/change_cohort_and_continue_training_support.rb
- Ticket: [CPDLP-4106](https://dfedigital.atlassian.net/browse/CPDLP-4106)
Last year when freezing cohort 2021 we moved participants to the active registration cohort which was 2024. This year freezing cohort 2022 will also move to 2024 and NOT the active registration cohort.
-  Replace `Cohort.active_registration_cohort` (currently 2024) with hardcoded 2024, so when 2025 registration period opens, we only accept 2024 cohort when moving participants to from a frozen cohort;
[CPDLP-4106]: https://dfedigital.atlassian.net/browse/CPDLP-4106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4106] Accept only 2024 cohort when moving participants to from a frozen cohort

- config/locales/en.yml
- spec/services/void_participant_declaration_spec.rb
[Jira-4091](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4091)
The error message we serve to lead providers when they try and clawback a declaration that is either `clawed_back` or `awaiting_clawback` already is not clear. We want to update it to improve the messaging to lead providers.
- Change wording of error when already clawing/clawed back
Update the error to be clearer and add test coverage.
I checked to see if any states that aren't `clawed_back` or `awaiting_clawback` could end up hitting this error message, but the only other state that gets here is `voided` and that is picked up by the earlier check and raise.
> Change wording of error when already clawing/clawed back

- app/services/delivery_partners/induction_records_query.rb
- app/services/delivery_partners/participants_filter.rb
[Jira-4129](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4129)
Since updating the `ParticipantsFilter` to filter on cohort by default (to exclude 2025 and later) we have noticed timeouts on the corresponding page in the dashboard. We want to make this query more performant so that we no longer see timeouts in Sentry.
- Optimize `ParticipantsFilter` query
It looks like when we join on `cohort` it ends up pulling in a bunch of other tables (as it has to go through induction programme -> school cohort -> cohort) and the query that active record ends up with is quite large and slow.
To avoid this, we can instead use a subquery to find the induction programmes that are associated with relevant cohorts and then filter on those, avoiding the many joins.
This appears to be more …
> Optimize `ParticipantsFilter` query

- Gemfile
- Gemfile.lock
In order to upgrade `rack` we need to also upgrade `puma` to the latest version.
Looking at the upgrade guide we shouldn't need to make any changes:
https://github.com/puma/puma/blob/master/6.0-Upgrade.md
> Upgrade Puma to v6

- app/services/participants/check_and_set_completion_date.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
because the 'InProgress' status being reported by TRS (old DQT) since a few weeks now is no longer reliable:
Old values of InProgress and NotYetCompleted (maybe some more) have been merged into InProgress, so some ECTs are being now reported as continuing their induction but they have actually paused it (NotYetCompleted).
Therefore, this trigger has moved some of them (erroneously) to 2024.
We pause it to not extend the issue to other ECTs.
> Pause the in-progress trigger run nightly that moves ECTs out of their frozen cohort due to an issue in the data provided by TRS api

- app/services/valid_test_data_generators/completed_mentor_generator.rb
- app/services/valid_test_data_generators/ecf_lead_provider_populater.rb
- app/services/valid_test_data_generators/mentor_ect_generator.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4090
When generating test data in sandbox. The participants start date is being set in the future as the service `Induction::Enrol` sets the start date as the default schedule start date.
Add `start_date: Time.zone.now` to the params, so participants start date won't be in the future.
> [CPDLP-4090] Set participants start date as now on the valid test data generators

- app/services/change_schedule.rb
- spec/services/change_schedule_spec.rb
[Jira-4130](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4130)
Currently we allow both ECTs and mentors to change schedule from a payments frozen cohort to the active registration cohort if they have billable declarations in the frozen cohort.
Going forward we will be marking these mentors as complete which will exclude them from being eligible to transfer from a payments frozen cohort, but for a belt and braces approach we also want to guard against this explicitly in the `ChangeSchedule` service.
- Prevent mentors changing cohort due to payments frozen
Add guard clause to prevent mentors from transferring due to payments being frozen. We will still allow transferring out of a payments frozen cohort if there are no billable declarations against the participant (though they won't …
> Prevent mentors changing cohort due to payments frozen

- spec/services/change_schedule_spec.rb
- spec/support/shared_examples/participant_actions_change_schedule_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4108
* The work has already been done in model scopes, this PR just adds tests.
* Added test to `ChangeSchedule` service
* Added test to v1,v2,v3 `change-schedule` endpoint
* Test for changing frozen cohort from 2022 to 2024 and stop 2022 to 2025
> [CPDLP-4108] tests added for change schedule to move frozen 2022 to 2024

- .github/workflows/rspec.yml
- spec/features_helper.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4149
A possible race condition between newer versions of chromedriver and selenium is causing some specs to fail intermittently on CI with the failure `Net::ReadTimeout` and locally with `Selenium::WebDriver::Error::UnknownError`.
Move chromeversion pin to features helper file instead, so feature specs will pass locally as well on the CI, without the errors described above.
> [CPDLP-4149] Pin chromedriver version locally

- docs/source/ecf/guidance.html.md
Guidance updates to clarify what we mean when we use the term 'unfunded mentors'.
> Unfunded mentors guidance updates

- docs/source/ecf/guidance.html.md
Created a dedicated section for transfers info and guidance. Repetitive content has been removed, the copy has been made clearer, and sub-headings added to improve navigation.
**Don't merge** to Main until Shahad has fact checked the content in the review app.
> Separated 'Participant transfers' into its own section

- app/validators/evidence_held_validator.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v2/participant_declarations_spec.rb
- spec/requests/api/v3/participant_declarations_spec.rb
- spec/services/record_declaration_spec.rb
- spec/validators/evidence_held_validator_spec.rb
[Jira-4140](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4140)
The `EvidenceHeldValidator` will only validate the evidence held if it applies to the declaration being recorded.
It applies for detailed evidence types if the declaration type is not `started` or the `evidence_held` value is provided.
It applies for normal evidence types if the declaration type is not `started`.
This means if the declaration is started and for normal evidence types and the `evidence_held` value is provided it will not be validated but it will end up being persisted against the declaration.
We want to prevent lead providers persisting bad/incorrect `evidence_held` values against declarations.
- Clear evidence_held if not applicable when recording declaration
We can avoid this by either returning a new …
> Clear evidence_held if not applicable when recording declaration

- app/forms/finance/ecf/change_training_status_form.rb
- app/serializers/api/v3/ecf/participant_serializer.rb
- app/serializers/finance/ecf/assurance_report/csv_serializer.rb
- app/services/withdraw_participant.rb
- spec/forms/finance/ecf/change_training_status_form_spec.rb
- spec/serializers/api/v3/ecf/participant_serializer_spec.rb
- spec/serializers/finance/ecf/assurance_report/csv_serializer_spec.rb
- spec/services/withdraw_participant_spec.rb
[Jira-4186](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4186)
We want to remap the withdrawl reason `school-left-fip` to `switched-to-school-led` when the `programme_type_changes_2025` feature flag is enabled. This is part of a wider renaming of programme types.
- Map withdrawl reason to new value in v3 ParticipantSerializer
As part of the programme type changes we want to map the `switched-to-school-led` withdrawl reason to `school-left-fit` when the `programme_type_changes_2025` feature flag is enabled.
Update the v3 `ParticipantSerializer` to map the withdrawl reason. The v1/2 serializers don't appear to expose the withdrawl reason.
- Update WithdrawParticipant with program type changes
When the `programme_type_changes_2025` feature is enabled we want to support sending the …
> Remap withdrawl reason when `programme_type_changes_2025` feature is enabled

- Gemfile
- Gemfile.lock
- app/jobs/analytics/upsert_ecf_appropriate_body_job.rb
- app/jobs/analytics/upsert_ecf_induction_job.rb
- app/jobs/analytics/upsert_ecf_participant_profile_job.rb
- app/jobs/analytics/upsert_ecf_partnership_job.rb
- app/jobs/analytics/upsert_ecf_school_cohort_job.rb
- app/models/application_record.rb
- app/models/appropriate_body.rb
- app/models/induction_record.rb
- app/models/participant_profile/ecf.rb
- app/models/partnership.rb
- app/models/school_cohort.rb
- app/services/store_participant_eligibility.rb
- spec/jobs/analytics/upsert_ecf_appropriate_body_job_spec.rb
- spec/jobs/analytics/upsert_ecf_induction_job_spec.rb
- spec/jobs/analytics/upsert_ecf_participant_profile_job_spec.rb
- spec/jobs/analytics/upsert_ecf_partnership_job_spec.rb
- spec/jobs/analytics/upsert_ecf_school_cohort_job_spec.rb
- spec/models/appropriate_body_spec.rb
- spec/models/induction_record_spec.rb
- spec/models/participant_profile_spec.rb
- spec/models/partnership_spec.rb
- spec/models/school_cohort_spec.rb
- spec/requests/admin/participants_spec.rb
- spec/requests/schools/participants_request_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/early_career_teachers/reactivate_spec.rb
[Jira-4196](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4196)
We see a lot of errors in logit when review apps are deployed. These are to do with jobs that are running where the data the job was serialized with no longer exists in the database. We want to fix this to prevent review deploys from spamming the logs/eating into our quota.
- Run analytics job after_commit instead of after_save
There is a race condition when the various models that have an `update_analytics` callback are persisted in a transaction (as is the case with some of the seed data).
The `after_save` will enqueue the job before the transaction is commited; if a worker picks up the job it attempts to deserialize and verify the model argument and raises an error as it hasn't been commited to the database yet. …
> Fix failing analytics upsert jobs on review deploy

- app/serializers/api/v3/ecf/school_serializer.rb
- spec/serializers/api/v3/ecf/school_serializer_spec.rb
- spec/services/programme_type_mappings_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4182
* `Api::V3::ECF::SchoolSerializer` updated to return new programme mapping when `programme_type_changes_2025` feature is enabled.
> [CPDLP-4182] Update school serializer to return the new programme type based on feature

- spec/validators/course_validator_spec.rb
[Jira-4204](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4204)
We only check active participant profiles when cross-referencing the course identifier. The `active_record` method is confusing as it is an inferred method on `ParticipantProfile` that is suffixed.
Add test coverage to protect against accidental removal of `active_record` check and also to explain what its doing.
> Add test to cover when profile is not active

- app/components/appropriate_bodies/participants/table_row.rb
- app/models/induction_record.rb
- app/serializers/appropriate_bodies/induction_records_serializer.rb
- app/services/programme_type_mappings.rb
- config/locales/en.yml
- documentation/service-rules/appropriate-body-users.md
- spec/components/appropriate_bodies/participants/table_row_spec.rb
- spec/models/induction_record_spec.rb
- spec/serializers/appropriate_bodies/induction_records_serializer_spec.rb
- spec/services/programme_type_mappings_spec.rb
- Ticket: [CPDLP-4158](https://dfedigital.atlassian.net/browse/CPDLP-4158)
We need to update a few places we mention programme types to the new values.
- `AppropriateBodies::Participants::TableRow` to show provider/school led if feature flag is on instead of CIP/FIP;
- Update `AppropriateBodies::InductionRecordsSerializer` to show provider/school led if feature flag is on instead of CIP/FIP;
- Update mentions to FIP/CIP in ABs documentation. Please see [PR#433](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/433);
Review app
[CPDLP-4158]: https://dfedigital.atlassian.net/browse/CPDLP-4158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4158] Update appropriate bodies views for the new programme types

- app/services/withdraw_participant.rb
This was used when NPQ was also part of the service, no longer needed
- Ticket: n/a
Remove unused method
@leandroalemao thanks for flagging!
> Remove unused method in withdraw service

- docs/source/api-reference/stylesheets/screen.css.scss
Columns width not extending when value is wrapped in `<code>` example [here](https://manage-training-for-early-career-teachers.education.gov.uk/api-reference/ecf/definitions-and-states.html#definitions-and-states-key-concepts)
- Ticket: n/a
Add `nowrap` to code while embedded in tables
Can view the difference in review app [here](https://cpd-ecf-review-5724-web.test.teacherservices.cloud/api-reference/ecf/definitions-and-states.html#definitions-and-states)
> Do not wrap text when column value is wrapped in code

- app/services/programme_type_mappings.rb
- app/views/finance/ecf/duplicates/compare/_induction_record_summary_list.html.erb
- app/views/finance/participants/_ecf_profile.html.erb
- app/views/lead_providers/content/partnership_guide.html.erb
- config/locales/en.yml
- documentation/service-rules/lead-provider-users.md
- spec/features/lead_providers/partnership_guidance_spec.rb
- spec/services/programme_type_mappings_spec.rb
- spec/views/finance/participants/show.html.erb_spec.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4217
* Updated `ProgrammeTypeMappings.training_programme_friendly_name` to allow short/long values
* Extended locale for all possible values
* Updated views and docs to the hyphenated values.
> [CPDLP-4217] add hyphenated values for programme type

- terraform/application/databases.tf
Deployments are failing with the following error:
```
The value: [citext,fuzzystrmatch,pg_stat_statements,pgcrypto,plpgsql,uuid-ossp] of Server Parameter: [azure.extensions] is invalid, the allowed values are: [,address_standardizer,address_standardizer_data_us,age,amcheck,anon,azure_ai,azure_local_ai,azure_storage,bloom,btree_gin,btree_gist,citext,cube,dblink,dict_int,dict_xsyn,earthdistance,fuzzystrmatch,hll,hstore,hypopg,intagg,intarray,isn,lo,login_hook,ltree,oracle_fdw,orafce,pageinspect,pg_buffercache,pg_cron,pg_diskann,pg_freespacemap,pg_hint_plan,pg_partman,pg_prewarm,pg_repack,pg_squeeze,pg_stat_statements,pg_trgm,pg_visibility,pgaudit,pgcrypto,pglogical,pgrouting,pgrowlocks,pgstattuple,plv8,postgis,postgis_raster,postgis_sfcgal,postgis_tiger_geocoder,postgis_topology,postgres_fdw …
```
> Remove `plpgsql` db extension as enabled by default in azure

- app/services/valid_test_data_generators/withdrawn_participants_generator.rb
- spec/services/valid_test_data_generators/withdrawn_participants_generator_spec.rb
- Ticket: [CPDLP-4112](https://dfedigital.atlassian.net/browse/CPDLP-4112)
- Add new valid test generator to be run in sandbox;
- Script to add ECT/Mentors participants that are already withdrawn with the value `school-left-fip` in every cohort;
```
LeadProvider.name_order.joins(:cohorts).includes(:cohorts).find_each do |lp|
Cohort.between_years((Date.current - 3.years + 1.day).year, (Date.current + 1.year).year).each do |c|
next if c.start_year == 2025 && lp.name == "Best Practice Network"
ValidTestDataGenerators::WithdrawnParticipantsGenerator.call(name: lp.name, cohort: c, count: 30)
end
end
```
[CPDLP-4112]: https://dfedigital.atlassian.net/browse/CPDLP-4112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4112] Add new valid test generator for withdrawn participants

- spec/services/finance/clawback_declaration_spec.rb
- spec/services/finance/declaration_statement_attacher_spec.rb
[Jira-4232](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4232)
When a declaration is clawed back we want to confirm that the statement it is clawed back to is in the same cohort as the original declaration (rather than using the participants cohort, which may have changed).
Improve existing test in `DeclarationStatementAttacher` spec and add coverage to `ClawbackDeclaration` spec.
> Add tests to verify clawbacks attach to correct statement cohorts

- app/assets/stylesheets/primary-nav.scss
- app/views/layouts/_application.html.erb
- Ticket: [CPDLP-4219](https://dfedigital.atlassian.net/browse/CPDLP-4219)
When tailing the logs for reviews we are getting the following warning: 
`Service name and navigation links are deprecated and will be removed in the next breaking release of GOV.UK Frontend. See https://github.com/alphagov/govuk-frontend/releases/tag/v5.9.0`
- Remove deprecation message
- Remove service name from `govuk_header`
- Move it to `govuk_service_navigation` component (please see https://govuk-components.netlify.app/components/service-navigation/)
Review app frontend & logs
Before:
After:
[CPDLP-4219]: https://dfedigital.atlassian.net/browse/CPDLP-4219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CPDLP-4219] Remove service name from govuk_header

- app/jobs/set_participant_completion_date_job.rb
- app/services/participants/check_and_set_completion_date.rb
- [Ticket](https://dfedigital.atlassian.net/browse/CPDLP-4148): 
The daily DQT checks are duplicating the induction records when the participant needs to be moved from their current cohort.
After analysing the code and trying to reproduce the issue the outcome is that the service object that actually checks DQT for a participant and apply the logic to change the cohort of the ECT, is working fine. 
I wasn't able to reproduce the bug using the snapshot database though but I was able to revert and re-submit some of these ECTs in the snapshot database and the service class `Participants::CheckAndSetCompletionDate` is doing the right thing (without duplicating induction records).
So the only thing I can think of causing this issue is the parent process that picks ECTs in batches from the …
> Fix bug that might duplicate induction records in the DQT daily checks

- .rubocop.yml
- db/new_seeds/base/add_declarations.rb
- Ticket: [CPDLP-4218](https://dfedigital.atlassian.net/browse/CPDLP-4218)
It’s been flagged a few times that seeds aren’t running to completion in review apps. Sometimes for instance API tokens aren’t created or anything after that.
- Refactor `add_declarations.rb` to improve performance.
- Batch Processing: Breaking the large transaction into smaller batches to prevent timeouts:
- Lead providers batch
- Participants batch
- Cohort batch 
- Pre-loading Data: Loading collections upfront to reduce repeated database queries
- Bulk Operations: Creating related records in groups rather than individually
- Query Reduction: Using indexing and in-memory operations to minimize database hits
- Optimized Time Handling: Reducing the number of time travel operations
Review app
[CPDLP-4218]: …
> [CPDLP-4218] Fix memory issue when seeding review apps

- app/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step.rb
- app/views/schools/cohort_setup/how_will_you_run_training.html.erb
- spec/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step_spec.rb
This is part one, split off from #5647 - refer to that PR for screen shots and more info.
> Programme type changes for 2025 - Part 1

- app/forms/induction_choice_form.rb
- app/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step.rb
- app/helpers/schools/cohort_setup_helper.rb
- app/models/concerns/training_programme_options.rb
- app/views/admin/schools/cohorts/change_programme/show.html.erb
- app/views/schools/choose_programme/show.html.erb
- app/views/schools/cohort_setup/how_will_you_run_training.html.erb
- spec/features/scenarios/onboarding_a_deferred_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_fip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/schools/choose_programme/new_schools_steps.rb
- spec/features/schools/training_dashboard/manage_cip_training_spec.rb
- spec/features/schools/training_dashboard/manage_fip_training_spec.rb
- spec/features/schools/training_dashboard/manage_no_ect_training_spec.rb
- spec/requests/admin/schools/cohorts/change_programme_spec.rb
- spec/support/features/pages/schools/school_report_programme_wizard.rb
This is part two, split off from #5647 - refer to that PR for screen shots and more info.
Majority of changes are spec …
> Programme type changes for 2025 - Part 2

- .github/workflows/refresh_migration_database.yml
The migration runs nightly to refresh the data. However we are testing with custom setup cohort 2025 e2e on the migration environment and don't want the data wiped for a few days
- Ticket: n/a
Disable the nightly migration db refresh temporarily until we finish testing. This will be enabled after
> Disable nightly migration db refresh

- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_hidden_pii.yml
Allow user ID and name to be streamed through to the ECF Voided Declaration Dashboard and added created_at and updated_at dates to users table
Fixes #5770, #5771, #5772
> Update user analytics fields

- app/forms/schools/cohorts/wizard_steps/what_changes_step.rb
- app/views/schools/cohort_setup/_change_to_core_induction_programme_confirmation.html.erb
- app/views/schools/cohort_setup/programme_confirmation.html.erb
- app/views/schools/cohorts/change_programme.html.erb
- app/views/schools/early_career_teachers/show.html.erb
- app/views/schools/mentors/_mentor_training.html.erb
- config/locales/admin/induction_choice_form.yml
- config/locales/en.yml
- config/locales/schools/induction_choice_form.yml
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
This is part four, split off from #5647 - refer to that PR for screen shots and more info.
* Make content more …
> Programme type changes for 2025 - Part 4

- spec/features/scenarios/onboarding_a_deferred_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_deferred_participant/fip_to_fip_with_same_provider_spec.rb
This is part five, split off from #5647 - refer to that PR for screen shots and more info.
* Adding loops to specs to …
> Programme type changes for 2025 - Part 5

- spec/features/scenarios/onboarding_a_withdrawn_participant/cip_to_fip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_cip_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/onboarding_a_withdrawn_participant/fip_to_fip_with_same_provider_spec.rb
This is part six, split off from #5647 - refer to that PR for screen shots and more info.
* Adding loops to specs to …
> Programme type changes for 2025 - Part 6

- app/views/participants/start_registrations/show.html.erb
- app/views/schools/add_participants/cannot_add_mentor_without_trn.html.erb
- Ticket:  https://github.com/DFE-Digital/register-ects-project-board/issues/1577
Fix the link for how to get a TRN.
Make sure the link works to the new guidance.
I don't think cleaning up the pages matters no much given we're hopefully decommissioning ECF1 relatively soon.
> Fix the link to guidance on how a mentor gets a TRN in ECF1.

- config/locales/status_tags/delivery_partner_participant_status.yml
- spec/features/delivery_partners/participants_spec.rb
- Ticket: [Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/1581)
The status for ERO mentors in the Delivery Partner view of participants was incorrectly display them as eligible for training when this is not the case.
The correct state was being calculated by the `TrainingRecordState` service but the values in the I18n file for the status were incorrect.
Change the description in the i18n files for the ERO mentor statuses.
> Change the DP status messaging for ERO mentors

- terraform/domains/environment_domains/main.tf
- terraform/domains/environment_domains/variables.tf
- terraform/domains/environment_domains/workspace_variables/cpd_ecf_production.tfvars.json
- terraform/domains/environment_domains/workspace_variables/cpd_ecf_sandbox.tfvars.json
Configure rate limiting for production & sandbox
Add global rate limit per IP for 5 minute intervals
Value for global rate set from checking ingress logs for the last 4 weeks 
make production|sandbox domains-plan
https://trello.com/c/rmljcE5W/2345-add-rate-limiting-for-services
> Add ingress rate limit

- app/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step.rb
- spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_fip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_same_provider_spec.rb
This is part seven, split off from #5647 - refer to that PR for screen shots and more info.
* Adding loops to specs to …
> Programme type changes for 2025 - Part 7

- app/forms/schools/cohorts/wizard_steps/how_will_you_run_training_step.rb
- spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
- spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/cip_to_fip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_cip_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_different_provider_spec.rb
- spec/features/scenarios/transfering_a_participant/fip_to_fip_with_same_provider_spec.rb
- spec/features/schools/choose_programme/choose_programme_invalid_provider_relationship_spec.rb
- spec/features/schools/choose_programme/choose_programme_spec.rb
- spec/features/schools/choose_programme/choose_programme_steps.rb
- spec/features/schools/choose_programme/new_schools_spec.rb
- spec/features/schools/choose_programme/new_schools_steps.rb
This is part eight, split off from #5647 - refer to that PR for screen shots and more info.
* Adding loops to specs to …
> Programme type changes for 2025 - Part 8

- .github/workflows/destroy_review.yml
This PR updates the review app cleanup process by adopting the shared delete-review-app action:
- Replace existing implementation with the standardized approach from teacher-services-cloud template
- Configure the workflow to properly handle Terraform state cleanup
- Update parameters to work with the new DFE-Digital/github-actions/delete-review-app action
- Maintain service-specific configuration for resource groups and storage accounts
- Ensure proper authentication with both Azure and Google Cloud Platform
This standardization improves maintainability across services and ensures consistent cleanup of review environments when PRs are closed.
- Ticket: https://trello.com/c/7M3ZvinR/2323-use-delete-review-app-github-action
https://github.com/DFE-Digital/early-careers-framework/actions/runs …
> Update delete workflow to use standardized action

- spec/services/appropriate_bodies/induction_records_query_spec.rb
- spec/services/induction/amend_cohort_after_eligibility_checks_spec.rb
- spec/services/induction/amend_participant_cohort_spec.rb
- spec/services/induction/change_mentor_spec.rb
- spec/services/induction/transfer_and_continue_existing_fip_spec.rb
- spec/services/induction/transfer_to_schools_programme_spec.rb
- spec/support/shared_examples/participant_actions_change_schedule_support.rb
Tests tend to fail around the time when new cohorts end/start. We have a support tag to set tests to mid cohort. We need to use that on those failing tests
We need to ensure those tests run whilst travelling to mid cohort, otherwise they start failing towards the end of the cohort.
For the AB spec, ensure not all induction records have the same date, travel to date in the future to ensure appropriate body checks pick the latest induction record
We will keep getting failures it seems on those tests, something to watch out when writing them
> Add mid cohort tag to all failing cohort tests

- app/forms/induction_choice_form.rb
- app/models/concerns/training_programme_options.rb
- app/views/schools/choose_programme/confirm_programme.html.erb
- app/views/schools/choose_programme/success.html.erb
- app/views/schools/cohort_setup/_training_confirmation_cip.html.erb
- app/views/schools/cohort_setup/programme_confirmation.html.erb
- spec/forms/induction_choice_form_spec.rb
Final tweaks for programme type changes for 2025
On the registration journey when a SIT has picked school-led the text needs revised in certain steps as still refers to DfE-accredited materials etc
- Not a requirement that they use DfE materials so needs to be removed
- Propose that is says something like 'You've chosen to design and deliver your own training programme.'
- ‘Choose the DfE-accredited materials you want to use’ - Schools don't need to tell us this anymore so can be removed
- On the 'Are you sure this is how you want to run your training' page
- Need 'You'll need to' text 
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-2857)
| current | 2025 onwards |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/fad979b1-c24b-4df5-8d66-4c276838b296) | …
> [CST-2857] Final tweaks for programme type changes

- app/mailers/school_mailer.rb
- lib/tasks/comms.rake
- spec/mailers/school_mailer_spec.rb
- Ticket: [#1725](https://github.com/DFE-Digital/register-ects-project-board/issues/1725)
As part of our soft launch we want to send emails to schools that were partnered with BPN in academic year 24/25 to allow them more time to register participants and for providers to submit partnerships for them.
A bespoke urn list will be feeded to the task that will trigger the emails.
- Add new mair
- Add rake task to trigger the comms
- The mailer is using the correct email template and placeholders
- The rake task is triggering the correct mailer with the required params
> Add comms for SITs from BPN partnered schools to report training details

- docs/source/release-notes.html.md
Add release note for registration opening
- Ticket: https://github.com/orgs/DFE-Digital/projects/48/views/1?pane=issue&itemId=110479284&issue=DFE-Digital%7Cregister-ects-project-board%7C1583
Add release note with tags
https://cpd-ecf-review-5853-web.test.teacherservices.cloud/api-reference/release-notes.html
> Add release note for registration opening 2025/2026

- spec/support/shared_examples/finance_statement_calculators_support.rb
- Ticket: n/a
In CI we are getting failures on decimal precision, due to either database or environment precision differences. We only show precision 2 in the finance dashboards, so checking up to 5 should be adequate. Those tests also pass locally and only fail on CI
example failure https://github.com/DFE-Digital/early-careers-framework/actions/runs/15610845566/job/43971124080
```
6) Finance::ECF::ECT::StatementCalculator behaves like a Finance ECF statement calculator #service_fee returns calculated calculated service fee
Failure/Error: expect(subject.service_fee).to eql(BigDecimal("0.75943068965517241379310344827586206896551e5"))
expected: 0.75943068965517241379310344827586206896551e5
got: 0.75943068965517241379310344827587e5
```
Change statement spec to check up to 5 precision in …
> Round up big decimal results in statements spec to precision 5

- app/components/support_form_component.html.erb
- app/components/support_form_component.rb
- config/locales/en.yml
- Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1724
This PR revisits the content on the support form page that a SIT sees whenever the transfer needs done manually.
- Add method in the SupportFormComponent to convert the teacher's name to possesive
- Update i18n file with the new content
- Update the support form component html
|before|after|
|-|-|
|![before](https://github.com/user-attachments/assets/1a4d4b75-9ff2-4889-a459-b0cd3c7fff8c)|![after](https://github.com/user-attachments/assets/11d718a6-302c-4159-b7e9-2688d3cec0bb)|
> Update content in the Transfer Support form

- app/mailers/school_mailer.rb
- lib/tasks/comms.rake
- Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1760
Update email tag to ensure school SITs receive only one copy of the upcoming 2025 training comms.
> Update the school sit comms tag to 2025

- app/services/training_record_state.rb
- spec/services/training_record_state_spec.rb
- Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1754
Mentor left school but is being displayed as `Training or eligible for training` on the old delivery partner dashboard.
The logic determining the displayed status appears to not considering the induction status (in this case, "leaving"). As a result, it mistakenly attributes the new school's mentee record to the previous school and returns `:active_mentoring` as the participant's status. We need to incorporate induction status more accurately.
When a `InductionRecord` has induction status = `leaving` for a delivery partner:
- Take in consideration in the logic when a mentor left a school -> `mentoring?` method will return false instead.
- Then return `:left` on `mentoring_state` when mentor is not mentoring …
> [1754] Tweak TrainingRecordState service class

- terraform/domains/environment_domains/workspace_variables/cpd_ecf_sandbox.tfvars.json
Pods are restarting as we're being scanned and going to keep lowering/monitoring
> Lower rate limit on sandbox to 1500

- app/views/schools/add_participants/cannot_add_mentor_to_providers.html.erb
Content improvements for the "dead-end" when a SIT chooses "other" option for provider when adding a mentor
Update view content
> Update content when partnership for mentor

- app/models/finance/statement/ecf.rb
- app/services/importers/create_statement.rb
- app/services/oneoffs/update_mentor_contracts.rb
- app/services/oneoffs/update_statements.rb
- config/analytics_blocklist.yml
- db/migrate/20250828003324_add_mentor_contract_version_to_statements.rb
- db/schema.rb
- spec/factories/finance/statements.rb
- spec/features/finance/payment_breakdown_spec.rb
- spec/models/finance/statement/ecf_spec.rb
- spec/services/importers/create_statement_spec.rb
- spec/services/oneoffs/update_mentor_contracts_spec.rb
- spec/services/oneoffs/update_statements_spec.rb
We need to update cohort 2025 statements, contracts and mentor contracts
- Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1586
- Add script to update statements in place, creation can be done via importers
- I realised we were missing the mentor contract version, we cannot reuse the contract version, especially if we update one and not the other it would break everything. I've added a. new mentor contract version and have linked it up
- Add script to create and update mentor contracts
I've run dry runs of this on the snapshot and all works as expected for the 2 scripts
> Add Scripts to update mentor contracts and statements

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/views/layouts/_application.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_support_links.html.erb
- config/initializers/assets.rb
- package.json
- yarn.lock
Rebrand GovUK  https://github.com/alphagov/govuk-frontend/releases/tag/v5.10.0
- Add rebrand class to layout
- use component for footer to avoid having to change svgs,
- fix footer links to use existing components
- update image assets and theme colour
- details found here https://github.com/alphagov/govuk-frontend/releases/tag/v5.10.0
I tried doing the api-reference middleman implementation, but upgrading `govuk_tech_docs` caused quite a few issues so abandoned that for now
> Rebrand Gov UK

- .devcontainer/docker-compose.yml
- .rubocop.yml
- app/jobs/set_participant_completion_date_job.rb
- app/models/riab/application_record.rb
- app/models/riab/induction_period.rb
- app/models/riab/teacher.rb
- app/services/participants/check_and_set_completion_date.rb
- config/database.yml
- config/initializers/dfe_analytics.rb
- config/initializers/inflections.rb
- config/sidekiq_cron_schedule.yml
- db/riab_test_schema.rb
- spec/factories/riab/induction_periods.rb
- spec/factories/riab/teachers.rb
- spec/rails_helper.rb
- spec/services/participants/check_and_set_completion_date_spec.rb
- [Ticket](https://github.com/DFE-Digital/register-ects-project-board/issues/1401): 
TRS do not provide fully reliable induction status for participants continuing training. RIAB does instead.
This issue will connect ECF1 to RIAB (replacing TRS) to check for that information.
- Connect ECF to RIAB via an external database definition.
- Define some RIAB models for ECF1 to query RIAB's database. Also, add RIAB database schema for the test environment including several changes to be compatible with Rails 7.1 (ECF Rails version) and the fact that IDs are uuids on ECF and integers on RIAB.
- Define their factories and clean the external test database after each test.
- Refactor SC `Participants::CheckAndSetCompletionDate` to query RIAB database so replacing API calls to TRS.
Better commit by …
> [1401] - Make ECF1 talk to RIAB (instead of TRS) to check participant's induction information

- app/services/api/v3/participant_declarations_query.rb
- docs/source/release-notes.html.md
- spec/services/api/v3/participant_declarations_query_spec.rb
- Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2064
A LP that a ppt has transferred to or trained with should be able to see historical decs made by another lead provider. This is so they can see how much engagement has taken place. 
We have identified a bug where participants with leaving and withdrawn inductions result in providers missing out declarations. Where IR are active these can be found but there's a bug in the service that does not permit this.
- Fix the bug described above.
- Add release note on the bug fix
Snapshot db api calls before/after using declaration id examples added to the ticket.
> [2064] Fix declarations api v3 query bug

- app/assets/javascripts/print.js
- app/helpers/application_helper.rb
- config/initializers/content_security_policy.rb
- spec/helpers/application_helper_spec.rb
We are seeing a number of CSP violations in our [logs](https://kibana-uk1.logit.io/s/e9b9162d-0b5e-4362-bed0-8e577f88d06e/app/visualize#/edit/e1734f20-f874-11ef-8ed9-6f343317b3e8?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2025-09-23T14:00:00.000Z',to:'2025-09-24T17:00:00.000Z'))&_a=(filters:!(),linked:!t,query:(language:kuery,query:''),uiState:(vis:(columnsWidth:!((colIndex:0,width:431.3333333333333)))),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:app.payload.csp-report.blocked-uri,size:200),schema:bucket,type:significant_terms),(enabled:!t,id:'3',params:(field:app.payload.csp-report.violated-directive,size:200),schema:bucket,type:significant_terms)),params:(perPage:10,percentageCol:'',showMetricsAtAllLevels:!f,show …
> Update CSP to fix violations
