DFE-Digital/early-careers-framework

- app/views/layouts/application.html.erb
- app/webpacker/packs/application.js
- package.json
- yarn.lock
General consensus is that we don't want the turbolinks or rails-ujs libraries in this project. They don't fit very well with our aim of progressive enhancement, and the requirement to make everything work without JS.
Remove turbolinks and rails-ujs, and everything that mentions them
Let me know if you think anything else needs stripping out
> ECF-29: Remove Turbolinks and Rails-UJS

- .eslintrc.js
- .github/workflows/lint.yml
- .rubocop.yml
- Gemfile
- Rakefile
- app/webpacker/packs/application.js
- config.ru
- config/initializers/canonical_rails.rb
- db/schema.rb
- lib/tasks/govuk_lint.rake
- package.json
- spec/spec_helper.rb
- yarn.lock
Let's use github actions to lint our code. We can use this until we have more CI set up.
Add github actions to run rubocop and eslint on every push
A lot of the changes here are just fixing the linting, probably safe to ignore
> Add automated linting

- Dockerfile
- Gemfile
- Gemfile.lock
We were setting env vars in the production container that we shouldn't be. This meant the secret key base on the deployed app was "TestKey". I have verified this is no longer the case on the review app
- clean up env vars
- clean up gemfile
Commit by commit here, details in commit messages
> Env var cleanup

- Gemfile
- Gemfile.lock
- app/controllers/govspeak_test_controller.rb
- app/views/govspeak_test/show.html.erb
One more component added to our version of govspeak, one more version bump.
Bump the govspeak version. If you are interested what it's doing you can check out https://github.com/DFE-Digital/ecf-govspeak (last commit). 
Also add some much needed changes - more rows on the text area and remembering entered value on govspeak test page.
```
$YoutubeVideo(https://www.youtube.com/watch?v=EpjSlCJtPLo&list=PL4IuMlmijgAfTwwEiZmMp28Eaf66S3a1R&index=2&t=0s)$EndYoutubeVideo
```
should produce an embedded video on the govspeak test page of our review app.
> Add youtube in govspeak

- Gemfile
- Gemfile.lock
Secondary buttons approach we used in old govspeak had annoying styling when we added govuk publishing components styles. This bumps the version to something that should work better.
The following should be grey on review app (and not white). 
```
{button secondary}[Download this module (PDF)](http://www.early-career-framework.education.gov.uk/ambition/wp-content/uploads/sites/3/2020/09/EarlyCareerTeachers_2020_TeacherHandbook_I1.pdf){/button}
```
> Secondary button fix

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/govspeak/_call-to-action.scss
- app/assets/stylesheets/govspeak/_highlights.scss
- app/assets/stylesheets/govspeak/_tables.scss
Highlights in the govspeak need some additional styling. Speaking with Mark A he said that highlight sections should be kept black and white for govifying. 
Styling of .call-to-action and information classes so that they resemble what is published on govuk. 
Having the .call-to-action change in the _highlights file didn't work and the govuk_publishing_components seemed to overwrite changes in there. I Moved them to the application.scss and it worked.
> Govuk styling

- app/controllers/school_search_controller.rb
- app/forms/school_search_form.rb
- app/forms/search_schools_form.rb
- app/views/school_search/show.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/school_search.scss
- config/routes.rb
- spec/forms/school_search_form_spec.rb
- spec/requests/school_search_spec.rb
We would like to have a page on which suppliers can search for schools with a bunch of filters.
Mostly frontend, vast majority of the things we want to search by are in GIAS, so coming up with architecture around the search is probably best done when we have some dummy data from them.
I went for 'show searches for schools based on query params of the url' and 'post redirects to show with correct parameters' - that seemed to result in nicest url that can be copy-pasted or bookmarked. `get` form was a close second in that. 
Review app is probably a good place to play around with the search form. 
I used https://ecf-beta-prototype.herokuapp.com/school-search as inspiration.
> School search page

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/school_search_controller.rb
- app/forms/school_search_form.rb
- app/models/school.rb
- app/views/dashboard/show.html.erb
- app/views/school_search/show.html.erb
- app/webpacker/styles/school_search.scss
- spec/forms/school_search_form_spec.rb
- spec/rails_helper.rb
- spec/requests/school_search_spec.rb
We expect thousands of schools in our system, and on some queries we will display a lot of them. Paginating seems a must.
Add [kaminari](https://github.com/kaminari/kaminari) - a gem that does pagination for us.
Add pagination to school search.
Add empty school search state, link to school search from dashboard if user is a lead provider admin, show the blue tag if the school is already partnered with someone else. Do we need a green tag for when it is partnered with us?
I added `paginates_per` attribute to show off pagination in test app with 4 schools, happy to get rid of it (and maybe add a bunch more schools to the seed file if we want it). 
Tests to follow.
> School search pagination

- Gemfile
- Gemfile.lock
- db/migrate/20210113155153_change_lead_provider_profiles_id_to_uuid.rb
- db/schema.rb
I left the primary key for this table as an integer by mistake. This is a migration to fix that.
I have also added [a gem](https://rubygems.org/gems/ar-uuid/versions/0.2.1) which changes the PK to be UUID by default, so this doesn't happen again
> Fix lead provider profile ID

- Gemfile
- Gemfile.lock
Figures have been added to the latest ECF-govspeak.
Bumping the ECF-govspeak version so that images will now be rendered in the app.
the below should output as shown in the picture
```
$Figure
$Alt Example of the part-whole model using the number 28. The number 20 has already been added to the lower left field, the lower right field is blank ready to be filled in. 
$EndAlt 
$URL https://www.early-career-framework.education.gov.uk/teachfirst/wp-content/uploads/sites/4/2020/08/Part-whole-model.jpg 
$EndURL 
$Caption Figure 1: Part-whole model. 
$EndCaption
$EndFigure
```
> update ecf-govspeak version

- Gemfile
- Gemfile.lock
I rebased our govspeak master on top of alphagov govspeak master - they added some useful things. And that got rid of commit we were pointing at in our Rails app. So any new PR will fail horribly when trying to bundle install it. oops.
Might make a new branch next time that happens, or a tag, to prevent that happening again.
> Bump govspeak version

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/govspeak/_accordion.scss
- app/assets/stylesheets/govspeak/_quote.scss
- app/controllers/govspeak_test_controller.rb
Quotes didn't look great, and to make it worse, they were eating up some quotes from the beginning of the in-quote statement. So I decided to fix it. 
Old:
New:
Also, links in accordions were inline, decided to change it.
Old:
New:
I used the following for the links:
```
$Accordion
$Heading
Behaviour
$EndHeading
$Summary
$EndSummary
$Content
<a href="http://www.early-career-framework.education.gov.uk/ambition/ambition-institute/self-directed-study-materials/1-behaviour/1-strand-fundamentals-and-contracting/">
B1. Strand fundamentals and contracting
</a>
<a href="http://www.early-career-framework.education.gov.uk/ambition/ambition-institute/self-directed-study-materials/1-behaviour/2-routines/">
B2. Routines
</a>
<a href="http://www.early-career-framework.education.gov.uk/ambition/ambition- …
```
> Improve styling for quotes and accordions

- app/models/course_lesson.rb
- app/models/course_module.rb
- app/models/course_year.rb
- app/models/lead_provider.rb
- db/migrate/20210118102533_add_cip_content.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/course_lesson.rb
- spec/factories/course_module.rb
- spec/factories/course_year.rb
- spec/models/course_lesson_spec.rb
- spec/models/course_module_spec.rb
- spec/models/course_year_spec.rb
We want to start the work of migrating CIP content into our Rails app. Since it will be stored in our db, the first step is to write some migrations and models. There are no routes or views, and it's by design - so more work is unblocked faster. 
Add `course_year`, `course_module` and `course_lesson` to our db, add models describing their relations, write tests for them. 
https://miro.com/app/board/o9J_kj-a9uA=/?moveToWidget=3074457353294903980&cot=14 is dev corner part describing the structure I think CIP will eventually take - and this PR is just taking care of year-module-lesson part.
> ECF-EL-73 add CIP structure

- app/controllers/application_controller.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/admin/lead_provider_users/_form_fields.html.erb
- app/views/users/registrations/new.html.erb
- db/migrate/20210115122323_add_eligible_to_schools.rb
- db/migrate/20210119070223_rename_first_name_to_full_name.rb
- db/migrate/20210119093554_remove_last_name_from_users.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/admin/lead_provider_users_spec.rb
- spec/requests/users/registrations/register_spec.rb
The design wireframes use full name when capturing user information. And following some discussions with the team it was decided that we should use full name rather than first name and last name. 
https://miro.com/app/board/o9J_lZ2k8oc=/
The main change in this pr is the migration to rename first name to full name and drop the last name column. Unfortunately this has far reaching repercussions when it comes to the tests. The tests have been updated accordingly.
> [ECF-1-138] Replace first name and last name with fullname

- app/forms/school_search_form.rb
- app/views/school_search/show.html.erb
- db/seeds.rb
- spec/factories/partnership.rb
- spec/forms/school_search_form_spec.rb
The school search form can currently only search for school group. Additional functionality is needed.  
- Adding a partnership when seeding the database.
- The 'Show schools partnered with another provider' check box is only seen if a lead provider is logged in.
- You can now search by URN
- The partnership checkbox now filters to only 'Show schools partnered with another provider'. 
To check the Partnerships filters on localhost you'll need to run the seed file again to create the partnership in the db. 
Unless you're logged in as an LP you'll need to comment out the if statement on the school_search/show.html.erb view.
The linter has failed because of line 42 on the school_search_form_spec (unused variable), unless we want to use it for any testing, i'll remove it.  I spotted this …
> Update school search

- app/assets/stylesheets/application.scss
- app/controllers/core_induction_programme/lessons_controller.rb
- app/controllers/core_induction_programme/modules_controller.rb
- app/controllers/core_induction_programme/years_controller.rb
- app/controllers/core_induction_programme_controller.rb
- app/models/course_lesson.rb
- app/models/course_module.rb
- app/models/course_year.rb
- app/views/core_induction_programme/lessons/show.html.erb
- app/views/core_induction_programme/modules/show.html.erb
- app/views/core_induction_programme/show.html.erb
- app/views/core_induction_programme/years/show.html.erb
- app/webpacker/styles/app_task_list.scss
- app/webpacker/styles/application.scss
- config/routes.rb
- spec/requests/core_induction_programme/core_induction_programme_spec.rb
- spec/requests/core_induction_programme/course_lesson_spec.rb
- spec/requests/core_induction_programme/course_module_spec.rb
- spec/requests/core_induction_programme/course_year_spec.rb
We want to display core induction programme content
Add a cip page, showing some introduction and all years.
Add a year page showing year page content and its modules.
Add a module page showing module page contents and its lessons.
Add a lesson page.
Go to `/core_induction_programme` on web app, we should have some dummy data.
Majority of content is to follow in a later massive seeding PR.
> Add cip views

- README.md
- db/seeds.rb
- db/seeds/cip_ambition.rb
- db/seeds/cip_edt.rb
- db/seeds/cip_teachfirst.rb
- db/seeds/cip_ucl.rb
This makes it so that running the seeding twice doesn't make a copy of everything, like I might have on dev environment.
Use `find_or_create` for creating cip content instead of just `create`.
Also bump the cip content version, so I can get rid of duplicates on dev, oops.
Also include the command to start a task in Readme so next person will have an easier time.
Eh, not much really :)
> Make seeding idempotent

- terraform/app/modules/paas/data.tf
It is scheduled to change on Monday, so we want to have a PR ready for when that happens.
Change `dfe-teacher-services` to `dfe` in our terraform file.
Creating review app will fail today, cause the space it's meant to point at doesn't exist yet (I think), and even if it did, I don't think the secret we are using to deploy there would work.
On Monday morning (or whenever the rename happens), rerun the deploy job and make sure it works before merging.
> Update service name in terraform

- app/controllers/users/confirmations_controller.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- db/migrate/20210128143531_add_primary_contact_email_to_school.rb
- db/schema.rb
- spec/factories/school.rb
- spec/factories/users.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/user_spec.rb
- spec/requests/users/confirmations_spec.rb
Send email to school primary contact once an induction coordinator has registered a school  and confirmed the account.
Only send an email to the primary contact if the email they registered with is different from that of the school primary contact.
> [ECF-144] Email school primary contact when school is confirmed

- app/controllers/users/registrations_controller.rb
- app/models/school.rb
- spec/models/school_spec.rb
- spec/requests/users/registrations/check_details_spec.rb
- spec/requests/users/registrations/register_spec.rb
When an induction coordinator registers a school they get a confirmation email with a confirmation link. They are given 24hrs to confirm otherwise we'll allow other users to register the school.
What should happen to the user who didn't confirm registration? That is up for discussion but my view would be to remove the induction coordinator profile as well as user profile.
> [ECF-1-131] Allow registrations if school is not confirmed within 24 hours

- app/models/cohort.rb
- app/models/core_induction_programme.rb
- app/models/early_career_teacher_profile.rb
- app/models/school.rb
- app/models/user.rb
- db/migrate/20210202093613_create_early_career_teacher_profiles.rb
- db/schema.rb
- db/seeds.rb
- db/seeds/dummy_structures.rb
- spec/factories/early_career_teacher_profiles.rb
- spec/factories/users.rb
- spec/models/cohort_spec.rb
- spec/models/core_induction_programme.rb
- spec/models/early_career_teacher_profile.rb
- spec/models/school_spec.rb
- spec/models/user_spec.rb
One of sprint goals on engage and learn this (next?) sprint is adding an ECT dashboard and tracking ECT progress through CIP. Before we can do any of that, we need to add something representing an ECT.
Add a new profile, `EarlyCareerTeacherProfile`. 
Make it link to reasonable things - like user, school, cohort and cip. One day we might rethink whether the connection to cip lives on the profile, on the school, or on the cohort (or somewhere else entirely) - but for time being I opted for the simplest solution for the upcoming work.
I moved the order of seed files loaded, because I want core induction programmes to exist by the time I generate my dummy ECT.
> Add ect profile

- app/controllers/users/confirmations_controller.rb
- app/views/users/confirmations/confirmed.html.erb
- config/initializers/devise.rb
- spec/requests/users/confirmations_spec.rb
Currently users are taken to the sign in page after confirming their registration email. However, ideally we want to automatically login the user as they have already confirmed their email. Users should be taken directly to the dashboard instead.
https://trello.com/c/Xm6zj6gY/145-automatically-login-users-after-registration-email-confirmation
https://miro.com/app/board/o9J_lZ2k8oc=/
> [ECF-145] Login user after confirmation

- app/controllers/core_induction_programme/years_controller.rb
- app/policies/course_year_policy.rb
- app/views/core_induction_programme/years/edit.html.erb
- app/views/core_induction_programme/years/show.html.erb
- config/routes.rb
- spec/policies/course_year_policy_spec.rb
- spec/requests/core_induction_programme/course_year_spec.rb
We need to be able to edit course year content. 
- Edit view to preview and save changes to year content
- Include CourseYear policy to restrict access to editing to dfe admin
- Update routes for core-induction-programme/years
- CourseYearPolicy tests
- CourseYear request tests
The changes follow the same pattern as course module editing and course lesson editing.
> add functionality to edit year content

- app/controllers/application_controller.rb
- app/controllers/users/sessions_controller.rb
- config/locales/devise.en.yml
- spec/requests/users/sessions_spec.rb
> Defect1:User able to land on sign in
> successful page with expire token
> Given I am on sign in page.
> When I entered emailId on sign in page
> And I click on Expired notification link in mail inbox.
> Then I am landing on “Sign in successful page”
> But I should land on sign in page.
- Ensure no success message is displayed when clicking an invalid link
- Ensure logged in users are redirected to the dashboard when clicking a sign-in link
- Ensure logged in users are redirected to the dashboard when clicking Start now
Now added tests
> Sign in defects

- Gemfile
- Gemfile.lock
- app/components/tabs_component.html.erb
- app/components/tabs_component.rb
- app/components/tabs_component/tab_component.html.erb
- app/controllers/admin/suppliers_controller.rb
- app/views/admin/suppliers/_layout.html.erb
I've moved the existing tabs HTML into a view_component component - mostly to test view_component and give an example of how it works.
There is a slight behaviour change - instead of the supplier and supplier user page passing a local variable in, it's using `current_page?` to check the current path against the specified one. This will break if child pages use the same layout, but nothing does that at the moment and would require other changes if desired in the future.
To test pagination without manually adding hundreds of providers, set `.per(20)` to `.per(2)` or something like that in the suppliers controller (or revert 35a22e9 where I left it in by mistake).
> Add view_component and create tabs component

- app/webpacker/packs/school_search.js
This was being thrown on every page but the school search page - wrapping it in a conditional fixes it.
> Fix bug where school search JS ran on every page, throwing an error

- app/controllers/induction_programme/base_controller.rb
- app/controllers/induction_programme/choices_controller.rb
- app/controllers/induction_programme/estimates_controller.rb
- app/forms/school_cohort_form.rb
- app/views/induction_programme/choices/show.html.erb
- app/views/induction_programme/estimates/show.html.erb
- app/views/registrations/learn_options/show.html.erb
- app/views/users/confirmations/confirmed.html.erb
- config/routes.rb
- db/migrate/20210225081103_add_estimates_to_school_cohorts.rb
- db/schema.rb
- spec/forms/school_cohort_form_spec.rb
- spec/requests/induction_programme/choices_spec.rb
- spec/requests/induction_programme/estimates_spec.rb
As a newly registered induction coordinator
Given that I have selected the full induction programme for my school
I should be able to enter estimates for the number of mentors and early career teachers in the next cohort
Refactoring choices controller. I have added an induction_programme namespace and refactored accordingly.
Added estimates controller
> [ECF-1-264] ECT mentor estimates

- app/components/school_information/details/main_info_component.html.erb
- spec/components/school_information/details/breadcrumb_component_spec.rb
- spec/components/school_information/details/head_component_spec.rb
- spec/components/school_information/details/main_info_component_spec.rb
- spec/components/school_information/your_schools/heading_component_spec.rb
- spec/components/school_information/your_schools/participants_component_spec.rb
- spec/components/school_information/your_schools/participants_school_search_component_spec.rb
- spec/factories/partnership.rb
- spec/rails_helper.rb
This pull request adds a test suite for components.
Some of the surprises and difficulties observed on content_for components as they don't render the normal way - solved but required digging deeper into the code for view components.
Overall - I think components are great - self-contained lego blocks that are very easy to test and as long as we keep views as flat as possible and not nest components - we should see plenty of benefits.
The one major benefit is the speed and simplicity of the tests - as long as we put the right variables in - we would always get predictable results.
There is much more to components and their configurability - for example using builder pattern (for example .with_header, .with_footer)
> Adds first component tests

- db/migrate/20210308161408_remove_default_cohort.rb
- db/schema.rb
Removes default value for cohorts in partnership
Removes default cohort id in partnerships table that tends to change
Be or not to be a nil Cohort - that is the question
Tests pass
> Removes default value for cohorts in partnership

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
Set up for flash success notifications. Eventually I want to go through all of our `flash` and use either a green or blue notification banner, but Al doesn't have time for this right now.
I've not used this anywhere in this PR, just set up work for the ones to follow.
[Here](https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done:~:text=Use%20the%20green%20version%20of%20the,they%E2%80%99re%20expecting%20to%20happen%20has%20happened.) is the design system component.
> ECF-RP-322: Add success flash

- app/controllers/admin/suppliers/supplier_users_controller.rb
- app/views/admin/suppliers/supplier_users/index.html.erb
- app/views/admin/suppliers/supplier_users/review.html.erb
- app/views/admin/suppliers/supplier_users/success.html.erb
- config/routes.rb
- spec/cypress/integration/admin/suppliers/create-lead-provider-user.js
- spec/requests/admin/suppliers/supplier_users_spec.rb
- Remove success page for creating LP user, replace with success banner
- "organisation" -> "supplier" everywhere
Just updated existing
> ECF-RP-333: Remove success page, copy changes

- app/services/pupil_premium_importer.rb
- app/services/school_data_importer.rb
- spec/services/pupil_premium_importer_spec.rb
- spec/services/school_data_importer_spec.rb
We should be able to update schools which are not eligible, so are excluded from the default scope
> Update school data imports to act on unscoped schools

- app/controllers/admin/administrators/administrators_controller.rb
- app/views/admin/administrators/administrators/create.html.erb
- app/views/admin/administrators/administrators/index.html.erb
- app/views/layouts/application.html.erb
- spec/cypress/integration/admin/administrators/create-administrator.js
- spec/cypress/integration/admin/suppliers/create-lead-provider-user.js
- spec/requests/admin/administrators/administrators_spec.rb
- spec/requests/admin/suppliers/supplier_users_spec.rb
We're replacing most of the success pages with notification banners. This is that for the admin creation journey
- Replace success panel with notification banner
- Make use of data-test attributes in a couple of places
Updated existing
> Remove success screen at end of admin creation journey

- app/controllers/users/confirmations_controller.rb
- app/views/users/sessions/new.html.erb
- spec/requests/registrations/user_profile_spec.rb
- spec/requests/users/confirmations_spec.rb
- spec/requests/users/sessions_spec.rb
We want more testing around emails. This PR deals with adding them to RSpec - I went through the places I expected to be sending emails and added unit tests to them. That said, devise likes sending some emails implicitly - I guess if the user is confirmed when we create them it won't send a confirmation email? I wonder if I want to test that in all the places that deal with making new users. 
1. A bunch of unit tests - checking what calls `UserMailer` received
2. A primary email notification was created, but never sent. I am not sure that's a good idea - if we don't want emails to be sent to the real world emails, well, that's what the non-live notify keys are for, right?
Keen to hear opinions about primary email notifications.
There will be another PR coming at some point, when I figure …
> Email testing - add unit tests

- app/controllers/admin/administrators/administrators_controller.rb
- app/mailers/admin_mailer.rb
- spec/mailers/admin_mailer_spec.rb
- spec/requests/admin/administrators/administrators_spec.rb
We need to send a welcome email to admins who have had their accounts created by other admins.
Added a new admin mailers and some tests.
> [ECF-1-364] Email newly created admin

- app/controllers/admin/suppliers/delivery_partners_controller.rb
- app/views/admin/administrators/administrators/delete.html.erb
- app/views/admin/administrators/administrators/edit.html.erb
- app/views/admin/suppliers/delivery_partners/delete.html.erb
- app/views/admin/suppliers/delivery_partners/edit.html.erb
- app/views/admin/suppliers/lead_provider_users/delete.html.erb
- app/views/admin/suppliers/lead_provider_users/edit.html.erb
- spec/cypress/integration/admin/suppliers/delete-delivery-partner.js
There were a couple different designs for the deletion pages before, this makes them all looks the same and (hopefully) makes them look a bit nicer
Button groups
Also, there was no flash message after deleting a delivery provider - I fixed that
Percy would help here :D
yes
> Improve deletion flow consistency

- .github/workflows/deploy_to_staging.yml
- .github/workflows/trigger_staging_deploy.yml
Process for releasing to staging:
- Manually trigger the new workflow, specify a git ref to deploy and a version number
- PR is opened automatically
- PR is approved and merged
- Tag is created from commit message
- Deploy to staging happens
- Create workflow to create pull request of correct format
- Tag release before deploying to staging (deploy fails if no tag)
> ECF-RP-370: Create github action create PR to release to staging

- .github/workflows/deploy.yml
- terraform/app/modules/paas/main.tf
- terraform/app/modules/paas/variables.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
We have a service set up in logit where we are piping our logs. Documentation. However, the configuration gets wiped out everytime the develop branch is deployed. Additionally, we need to replicate the setup for the staging and prod environments.
This pr stores the config changes in terraform so that we can automatically set up staging and prod as well as making the dev setup persistent.
I've used https://github.com/DFE-Digital/teacher-training-api/blob/7e7c91d55a18790bbb8d7fc0db6a88314441f97e/terraform/modules/paas/main.tf as a reference
> [ECF-1-248] Persist logit setup in terraform

- .githooks/pre-commit
There are loads of AWS keys in the yarn.lock file, according to the old version of this script. This stops that script from checking the yarn.lock file.
> Don't check the yarn.lock file for AWS keys

- app/models/admin_profile.rb
- spec/models/admin_profile_spec.rb
When email sending fails, you currently end up with an orphaned user with no profiles 
Confirm calls save, so this should be inside the transaction
> Call confirm inside the transaction

- .githooks/pre-commit
`gem "health_check", github: "/ianheggie/health_check", ref: "0b799ead604f900ed50685e9b2d469cd2befba5b"` does NOT contain an AWS key
> Stop the hook from thinking hashes are keys, so I can commit again

- Gemfile
- Gemfile.lock
- config/environments/deployed_development.rb
- config/environments/production.rb
- config/environments/staging.rb
Rails currently gives three separate logs per request. This makes life very difficult. Lograge makes life easier again. 
Also both Teaching Vacancies AND Apply are doing it, so it must be a good idea!
Take a look at logit if you're curious, I recommend the following filter: `cf.app:"ecf-review-pr-164" and not cf_tags.source_type:"RTR"`
I've excluded /check logs, which I think is a good idea. Do you disagree?
> Add lograge

- .github/workflows/deploy_monitoring_dev.yml
- terraform/monitoring/resources.tf
- terraform/monitoring/terraform.tf
- terraform/monitoring/variables.tf
- terraform/monitoring/versions.tf
- terraform/workspace-variables/monitoring/dev.tfvars
This is a combination of stuff from https://github.com/DFE-Digital/cf-monitoring, teaching vacancies, and Get Into Teaching, tweaked for our needs. It gives a fancy grafana monitoring dashboard. I'll like to get this in to play with before doing staging and prod
I've run this terraform locally, you should be able to sign in with google here: https://grafana-cpd-monitoring-dev.london.cloudapps.digital/?orgId=1
It lets in anyone with a digital.education.gov.uk email to view
> Set up grafana monitoring for dev

- db/migrate/20210323180540_change_item_id_type_to_uuid.rb
- db/schema.rb
Item Id / record Id in the paper-trail generated schema were generated as bigint whereas we use uuids. Everything still worked as rails was automatically casting to big int but sooner or later we were going to have a key collision. This ticket corrects the datatype to uuid.
> ECF-410 Fix paper trail audit schema datatype

- terraform/workspace-variables/production_app_env.yml
- terraform/workspace-variables/staging_app_env.yml
Our sign in emails on staging (and prod) always link to the london.cloudapps.digital domain currently. Now they always link to the proper domain, which isn't perfect, but better
> Set domains so emails etc have links to the right place

- app/mailers/school_mailer.rb
- app/models/nomination_email.rb
- app/models/school.rb
- app/services/invite_schools.rb
- config/routes.rb
- db/migrate/20210324105239_create_nomination_emails.rb
- db/schema.rb
- lib/tasks/schools.rake
- spec/mailers/school_mailer_spec.rb
- spec/models/nomination_email_spec.rb
- spec/models/school_spec.rb
- spec/services/invite_schools_spec.rb
We need to send invitation / nomination emails to school primary contacts to invite them to register on our service.
The email will contain a unique token that will be used to track the school and some fields to allow us to track when the email was opened.
> ECF-1-401 Send nomination email to schools

- app/controllers/schools/cohorts_controller.rb
- app/controllers/schools/dashboard_controller.rb
- app/models/school_cohort.rb
- app/views/schools/cohorts/show.html.erb
- app/views/schools/dashboard/show.html.erb
- app/webpacker/styles/app_task_list.scss
- config/routes.rb
- spec/cypress/app_commands/scenarios/schools/choose_programme.rb
- spec/cypress/integration/schools/ChooseProgramme.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/cypress/support/step_definitions/factory-bot.js
- spec/factories/school_cohort.rb
- spec/requests/schools/dashboard_spec.rb
Branched off ECF-RP-396_choose-programme, will point this PR at develop once that is merged.
Adds generic "Manage your training" and "Next steps" pages that are used for both CIP and FIP.
Also adds some kind of unrelated step definitions allowing us to create simple factories directly from our cucumber specs.
`SchoolCohort.first.destroy` will undo the CIP/FIP selection when testing.
Not sure there's any point adding tests until the statuses can change / the user journey is a bit more complete.
> CIP + FIP next steps pages

- app/controllers/schools/cohorts_controller.rb
- app/views/schools/cohorts/add_participants.html.erb
- app/views/schools/cohorts/legal.html.erb
- app/views/schools/cohorts/show.html.erb
- config/routes.rb
https://trello.com/c/ewjKniov/408-placeholders-for-add-participants-and-gdpr
Branched from https://github.com/DFE-Digital/early-careers-framework/pull/190
- Adds "Read and accept privacy and data policy" placeholder page
- Adds "Add teachers and mentors" placeholder page
These will need visual tests when we have them, but as they're placeholder pages for now I'm not sure anything else is necessary.
> Add placeholder pages for legal + add participants pages

- .github/PULL_REQUEST_TEMPLATE.md
- app/controllers/api/school_search_controller.rb
- app/controllers/lead_providers/school_details_controller.rb
- app/controllers/registrations/school_profile_controller.rb
- app/controllers/registrations/user_profile_controller.rb
- app/forms/nomination_request_form.rb
- app/forms/school_profile_form.rb
- app/forms/school_search_form.rb
- app/models/school.rb
- app/services/invite_schools.rb
- app/services/pupil_premium_importer.rb
- app/services/school_data_importer.rb
- spec/models/school_spec.rb
- spec/services/pupil_premium_importer_spec.rb
Default school scope that we chose a while ago, namely schools that are eligible, just isn't working for us anymore. There are many surprising places it gets in, like school import. 
1. Remove default school scope. 
2. Add `eligible` to all places making school queries without a scope. 
3. Remove `unscoped` from all school queries using it. 
If you think I missed something do let me know. 
School import won't load more than 3k schools without it, or so I think. So if there are more in review app, it probably worked.
> Remove default school scope

- .github/workflows/review.yml
Documentation on the default for this is unclear, it says:
Make it explicit to be sure
> Specify ref to checkout for PR review app

- app/views/nominations/already_nominated.html.erb
- app/views/nominations/choose_school.html.erb
- app/views/nominations/limit_reached.html.erb
- app/views/registrations/account_not_found/show.html.erb
Just looking through what happened last week and I have a few changed
- Add link to resend nomination email
- render support email component
- remove incorrect reference to URN
- Swap copy for limit_reached and already_nominated
> Minor corrections

- .github/workflows/deploy_to_dev.yml
- .github/workflows/deploy_to_production.yml
- .github/workflows/deploy_to_staging.yml
- .github/workflows/destroy.yml
- .github/workflows/review.yml
- terraform/app/modules/statuscake/main.tf
- terraform/app/modules/statuscake/providers.tf
- terraform/app/modules/statuscake/variables.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
- terraform/app/versions.tf
- terraform/workspace-variables/production.tfvars
Statuscake provides uptime monitoring by polling your site. When we have production, we want to make sure we keep production up...
This was lifted almost verbatim from Teaching Vacancies (thanks!). We're only monitoring prod, but we need to pass the API keys in for all envs to keep terraform happy. It's only uptime monitoring, so I'm not too fussed about that. 
There are a couple of steps that need to be done manually here:
- @cfq is sorting out a slack hook for alerting
- I think we will need to go in to statuscake and give the tests sensible names once this is deployed. @csutter sorry for the ping, I noticed your test names were totally different to what's in the code. Am I right in thinking you manually updated?
> Set up statuscake monitoring for production

- .github/workflows/test.yml
- config/webpacker.yml
- package.json
- spec/cypress/cypress_helper.rb
- spec/rails_helper.rb
Turns out if you run webpacker once up-front for all the tests things are faster than compiling every test. On my machine `rspec` goes from about 2min30 to around 17 seconds. Cypress will see a small improvement but less noticeable
> Only run webpacker once for tests

- app/controllers/schools/partnerships_controller.rb
- app/models/partnership.rb
- app/models/school_cohort.rb
- app/views/schools/cohorts/show.html.erb
- app/views/schools/partnerships/index.html.erb
- config/routes.rb
- db/migrate/20210406120453_add_delivery_partner_to_partnership.rb
- db/schema.rb
- db/seeds/dummy_structures.rb
- spec/components/school_information/your_schools/participants_school_search_component_spec.rb
- spec/cypress/integration/schools/ViewPartnerships.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/forms/school_search_form_spec.rb
- spec/models/partnership_spec.rb
- spec/models/school_cohort_spec.rb
- spec/requests/schools/partnerships_spec.rb
A new page that school tutors can access by going to /schools/cohort/2021/partnerships 
If the school is already in a partnership the page shows the details of the partnership else it just gives information of which lead providers to contact.
> [ECF-1-401] view partnership

- db/migrate/20210407110504_add_index_to_cohorts_on_start_year.rb
- db/schema.rb
I had an exciting time debugging locally and then realised that the cause of the weirdness was that I had 2 cohorts with start year 2021!
In addition, we are doing a lot of look ups on cohorts using the start year. Actually more than we do with the cohort id.
Add a unique index on the cohort start year.
> Add a unique index on cohorts start year

- README.md
- lib/tasks/safe_reset.rake
- terraform/workspace-variables/dev.tfvars
- terraform/workspace-variables/review.tfvars
We want a way to re-create the database for testing and re-testing purposes.
Use `db:reset` task, https://stackoverflow.com/a/10302357
Wrap it in an environment check, so the task we use won't work on staging or prod.
I went with a rake task, because the last thing I want to worry about is foreign key constraints. I sure hope our paas user lets us do that.
This PR adds a db reset on a rake task, and on deploy on dev and review apps.
I want a PR app to see it working in practice. But that might be hard to do since our dockerhub is malfunctioning atm...
> Add a db reset task for dev environments

- .github/workflows/review.yml
We need to allow reopened PR's to create review apps
Alter github workflow
try to rerun a closed PR and see if it creates a review app
> allow reopened pr to create review app

- app/controllers/nominations/notify_callbacks_controller.rb
- config/routes.rb
- spec/requests/nominations/notify_callback_spec.rb
We want to track the status of the nomination emails we send to schools.
I have explored 2 approaches. The first, https://docs.notifications.service.gov.uk/ruby.html#get-message-status, involves making API calls to Notify via the Notify client. The call would give us the latest 250 emails sent in the last 7 days. Based on the oldest of those records we would then need to fetch the next 250 records older than the oldest in the previous batch. It would be more difficult to get the status of all our nomination emails as there could be thousands of them. We would also need a rake task to run as a cron job to keep updating the statuses of our emails.
The other approach is to let Notify let us know the status of our emails via a callback and this is what has been implemented in this pr. …
> ECF-1-402 Added notify callback

- app/controllers/nominations/nominate_induction_coordinator_controller.rb
- app/controllers/nominations/request_nomination_invite_controller.rb
- app/forms/nominate_induction_tutor_form.rb
- app/mailers/school_mailer.rb
- app/models/induction_coordinator_profile.rb
- app/models/school.rb
- app/views/nominations/nominate_induction_coordinator/email_used.html.erb
- app/views/nominations/nominate_induction_coordinator/link_expired.html.erb
- app/views/nominations/nominate_induction_coordinator/link_invalid.html.erb
- app/views/nominations/nominate_induction_coordinator/new.html.erb
- app/views/nominations/nominate_induction_coordinator/nominate_school_lead_success.html.erb
- app/views/nominations/request_nomination_invite/already_nominated.html.erb
- config/routes.rb
- spec/cypress/integration/nominations/NominateInductionCoordinator.feature
- spec/cypress/support/commands.js
- spec/cypress/support/step_definitions/common-interaction.js
- spec/cypress/support/step_definitions/common-navigation.js
- spec/cypress/support/step_definitions/notifications.js
- spec/factories/nomination_email.rb
- spec/factories/school.rb
- spec/forms/nominate_induction_tutor_form_spec.rb
- spec/mailers/school_mailer_spec.rb
- spec/models/induction_coordinator_profile_spec.rb
- spec/models/school_spec.rb
- spec/rails_helper.rb
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
- spec/requests/nominations/request_nomination_invite_spec.rb
This is a rework of Seb's PR to nominate an induction coordinator
- Check the correct redirects happen
- Check the correct templates are rendered
- High level sanity checks on model creation
-Validation checks
- Detailed model creation checks
- Check model is created correctly
- Mailer checks
- Valid nomination (success journey)
- Expired link
- Already nominated
- Email in use
I'm going to write some seed data for this and other scenarios, but that will be a separate PR
> ECF-RP-404: nominate induction coordinator

- app/controllers/nominations/nominate_induction_coordinator_controller.rb
- app/models/school.rb
- app/services/invite_schools.rb
- app/views/nominations/_school_details.html.erb
- app/views/nominations/nominate_induction_coordinator/start.html.erb
- app/views/nominations/request_nomination_invite/review.html.erb
- config/routes.rb
- spec/cypress/integration/nominations/NominateInductionCoordinator.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
When school user has received an email for nomination induction coordinator for their school, we want to track the time they have started the nomination process.
When link is clicked, user will be directed to a start page with a single `start` button. Once the button is clicked, notification_email#opened_at column is updated when user is presented with the nomination form.
This PR is depending on https://github.com/DFE-Digital/early-careers-framework/pull/226
1) Receive school invite email with nomination link (via `rake schools:send_invites[school_urn]`)
1) Click on the nomination link
1) You should see a nomination start page, showing school's details
1) Check the `opened_at` field of the nomination_email record matching the token from url
1) Click on start button
1) You should see …
> Nomination email link tracking

- .github/workflows/run_task_dev.yml
This should make it easier to run tasks in the dev cf space. I see this being used mostly for resetting the database on dev and review apps.
> Run a rake task on an app in the dev space

- app/controllers/application_controller.rb
- app/controllers/cookies_controller.rb
- app/views/cookies/show.html.erb
- app/views/privacy_policies/show.html.erb
- spec/cypress/integration/Cookies.feature
- spec/requests/cookies_spec.rb
Trello #485
We need to return to the previous page after visiting the"/cookies" page and viewing/updating our preferences
Introduces an application controller method to set session[:return_to] in all get actions apart from under CookiesController. Can also be extended to privacy policy if needed ?
There are several ways of doing this...not all cover all use cases.
Noted some of the CookieFeature cypress tests are failing locally, as @consent_updated is not being set...
> back link from cookies page

- app/decorators/school_decorator.rb
- app/forms/nomination_request_form.rb
- app/views/nominations/request_nomination_invite/choose_school.html.erb
- app/webpacker/styles/school_search.scss
- spec/decorators/school_decorator_spec.rb
We need to display the address as part of the select dropdown  so that users can narrow down their school with less ambiguity.
Make the choose school dropdown look as in the attachment
> ECF-1-419 Enhance choose-school auto complete

- app/controllers/accessibility_statements_controller.rb
- app/views/accessibility_statements/show.html.erb
- app/views/layouts/_support_links.html.erb
- config/routes.rb
- spec/cypress/integration/AccessibilityStatement.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/requests/accessibility_statement_spec.rb
Trello #284
We need to add an accessibility statement page available from a link the footer
Click on Accessibility link in footer
> specs for accessibility statement page

- .github/PULL_REQUEST_TEMPLATE.md
We need to make it easy for non-developer reviewers (for example POs or URs) to
review the changes in PRs.
This last section can include a link to the exact place where the change can be
viewed and also instructions on how to get to that page with the right test
email or any other change/selection you have to do to view it.
> Adding instructions for reviewers on PR template

- app/controllers/application_controller.rb
- app/controllers/privacy_policies_controller.rb
- app/controllers/users/sessions_controller.rb
- app/views/privacy_policies/show.html.erb
- app/views/schools/core_programme/materials/success.html.erb
- config/routes.rb
- db/migrate/20210414125405_add_privacy_policy_to_users.rb
- db/schema.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- spec/cypress/support/step_definitions/common-navigation.js
- spec/factories/users.rb
- spec/requests/cookies_spec.rb
- spec/support/tasks.rb
- spec/tasks/manage_admins_spec.rb
Implements: https://trello.com/c/yZsndlKq/460-add-privacy-policy-interstitial-page-to-first-sign-in-journey-for-induction-tutor
This PR ensures user must read (or rather be presented an opportunity to read) privacy policy before accessing any of the page. This satisfies acceptance criteria of user being presented Privacy Policy after the first sign up, but also prevents user from skipping the acceptance and provides a hook for re-acceptance on policy change.
PP Acceptance data is stored on new `privacy_policy_acceptance` column. I've decided on json for now, as there is no point of creating two new columns, especially given the changes in the next PP task: https://trello.com/c/MwoYUPCi/507-store-privacypolicy-versions-in-the-database.
The check is implemented in global before_action, …
> Privacy policy on first sign in

- app/controllers/schools/base_controller.rb
- app/controllers/schools/choose_programme_controller.rb
- app/controllers/schools/dashboard_controller.rb
- app/helpers/application_helper.rb
- app/views/schools/choose_programme/advisory.html.erb
- app/views/schools/choose_programme/show.html.erb
- config/routes.rb
- spec/cypress/integration/schools/ChooseProgramme.feature
- spec/cypress/integration/schools/ViewPartnerships.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/helpers/application_helper_spec.rb
- spec/requests/schools/choose_programme_spec.rb
- spec/requests/schools/dashboard_spec.rb
- spec/requests/users/sessions_spec.rb
Trello #486
We need to have a speed bump advisory page prior to the /schools/choose-programme page 
controller method, route and view for /schools/choose-programme/advisory
Login as induction coordinator without having chosen a programme....navigate to /schools/choose-programme/advisory
> specs for choose programme advisory page

- app/views/nominations/request_nomination_invite/choose_location.html.erb
Removed back button from the Resend nomination: search location page
No new seed data needed
Go to: https://ecf-review-pr-265.london.cloudapps.digital/
/nominations/limit-reached
/nominations/choose-location
/nominations/not-eligible
and confirm these don't have a back button.
> [ECF-1-513] Remove back button from choose location

- app/views/layouts/_support_links.html.erb
https://trello.com/c/zhtQRj3L/532-add-link-support-email-address-to-footer-of-all-pages
It's in the footer of every page
> Add link to support email in footer

- spec/cypress/app_commands/scenarios/admin/schools.rb
Saw this failing on other pull requests.
> Removing missing bit of non-determinative data from percy tests

- app/controllers/lead_providers/report_schools_controller.rb
- app/views/dashboard/show.html.erb
- app/views/lead_providers/report_schools/start.html.erb
- config/routes.rb
- spec/cypress/integration/lead_providers/ReportSchools.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/factories/cohorts.rb
- spec/factories/lead_provider.rb
- spec/requests/lead_providers/report_schools_spec.rb
We want the start page to the 'report schools' lead provider journey.
Add a static page, controller, route, tests. Mostly as foundations for another multi-page flow. 
Lots of stuff is copy-pasted, so double check that naming makes sense. I'm also open to suggestions on how you would define the routes in this flow. 
Added simple request specs and cucumber tests.
Log in as `lead-provider@example.com`. Click 'Find and add schools'. You should see the start page. The button should do nothing.
> ECF-RP-523: Report schools

- app/mailers/school_mailer.rb
- app/models/nomination_email.rb
- app/services/invite_schools.rb
- app/views/nominations/request_nomination_invite/success.html.erb
- spec/factories/nomination_email.rb
- spec/mailers/school_mailer_spec.rb
- spec/models/nomination_email_spec.rb
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
- spec/services/invite_schools_spec.rb
Per call just now, nomination emails should be valid for 21 days
- Change nomination email lifetime to 21 days
- Add some extra tests around email expiry
Unit tested
We can't change the notify email template for this email to show the expiry date until this code has been promoted through to staging, else nomination emails will stop working for UR. Once that has been done, a nomination email can be triggered as follows:
- From https://ecf-dev.london.cloudapps.digital/nominations/choose-location select "ZZ Test Local Authority"
- Select "ZZ Test School 1"
- Confirm, and receive email
> Change nomination email lifespan to 21 days

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/schools/choose_programme_controller.rb
- app/controllers/users/sessions_controller.rb
- app/helpers/application_helper.rb
- app/views/cookies/show.html.erb
- config/application.rb
- config/environments/deployed_development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/initializers/rack_attack.rb
- config/initializers/session_store.rb
- spec/cypress/support/on-rails.js
- spec/helpers/application_helper_spec.rb
We want to fix some vulnerabilities. We won't get a full report until a while in the future, but these fixes are very likely to be needed.
1. Remove some `xxx_url` helpers - they create full url, as opposed to path helpers, which create relative path. We can't remove all of them, namely the ones that provide links in emails. 
2. Added rack-attack with some basic config
3. Set the session cookie to expire, be http only
4. Set all cookies on deployed envs to be secure, require https in them too
5. Sneaky cypress tests improvement - clean db after cypress run. I got some data from cypress tests interfering with rspecs :/ 
Feel free to suggest better / more sophisticated config. For some of the checks I will need the review app to be sure they work. 
I am not sure how automatically testable …
> ECF-RP-548 pentest fixes

- README.md
- app/controllers/api/notify_callbacks_controller.rb
- app/mailers/school_mailer.rb
- app/models/school.rb
- app/services/invite_schools.rb
- db/migrate/20210415163231_add_notify_fields_to_nomination_email.rb
- db/schema.rb
- spec/factories/nomination_email.rb
- spec/mailers/school_mailer_spec.rb
- spec/requests/api/notify_callback_spec.rb
- spec/services/invite_schools_spec.rb
Per this comment: https://github.com/DFE-Digital/early-careers-framework/pull/248#discussion_r615936569
- Change nomination emails callback to use notify id
- Record delivered_at for nomination emails
Unit tests
N/A
> ECF-RP-501: Use notify id for callbacks on nomination emails

- config/initializers/canonical_rails.rb
This was something we got from the boilerplate, and should have been updated when we got our domain name
Check the link tag in the head of any page
> Update canonical url host with domain name

- app/views/errors/forbidden.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- spec/cypress/integration/Errors.feature
- spec/cypress/support/step_definitions/common-navigation.js
Update the copy on the 403 page to match 404. Get rid of the double `<main>` and do some a11y tests
Go to `/403`, `/404`, `/500`
> Update error copy, check a11y

- app/controllers/schools/choose_programme_controller.rb
- app/forms/induction_choice_form.rb
- app/views/schools/choose_programme/confirm_programme.html.erb
- app/views/schools/choose_programme/success.html.erb
- config/routes.rb
- spec/cypress/integration/schools/ChooseProgramme.feature
- spec/cypress/integration/schools/ViewPartnerships.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/requests/schools/choose_programme_spec.rb
https://trello.com/c/7ZwF2Isr/512-bug-12-additional-confirmation-and-success-page-when-choosing-a-programme
We want some confirmation and success pages for selecting the type of induction a school will run.
Add a confirmation page.
Add a new 'save programme' endpoint
Add a success page
Miro suggests having different sets of pages for FIP and CIP, but Shani thinks those pages are going to be very similar, and suggested commonising them - which I did and I like. It means we need to store the choice - which I do in session.
I updated request specs and cypress tests.
Log in as `school-leader@example.com`, follow your nose:
- continue
- pick a programme + continue
- should be on the confirm page (to test)
- confirm
- should be on the success page (to test)
If you want to re-test, I guess we …
> ECF-RP-512: Add programme choice confirmation and success pages

- app/controllers/lead_providers/report_schools_controller.rb
- app/forms/lead_provider_delivery_partner_form.rb
- app/views/lead_providers/report_schools/choose_delivery_partner.html.erb
- app/views/lead_providers/report_schools/start.html.erb
- config/routes.rb
- spec/cypress/app_commands/scenarios/lead_provider_with_delivery_partners.rb
- spec/cypress/integration/lead_providers/ReportSchools.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/forms/lead_provider_delivery_partner_form_spec.rb
- spec/requests/lead_providers/report_schools_spec.rb
DfE need Lead Providers to specify which delivery partner is assigned to which school so that schools don't mistakenly challenge the partnership because they only know about the delivery partner.
A form with radio buttons that select the delivery partner for a school
Login as lead-provider@example.com. From the dashboard click on find schools
> ecf-1-524 Lead providers can choose delivery partners for a school

- app/controllers/nominations/request_nomination_invite_controller.rb
- app/models/school.rb
- app/views/nominations/request_nomination_invite/cip_only.html.erb
- config/routes.rb
- spec/cypress/integration/nominations/ResendNominations.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/models/school_spec.rb
- spec/requests/nominations/request_nomination_invite_spec.rb
Some schools are only eligible for the CIP. We'll deal with that properly later. For now, we just show them a special message when they try to trigger an email
- Add `cip_only?` to `School`
- add guidance page to resend nomination journey for cip only schools
- Edge case testing for eligibility on School
- Request specs for requesting invitation to nominate
- A11y and snapshot tests on new page
https://ecf-review-pr-297.london.cloudapps.digital/nominations/choose-location
Try to resend and email to school with LA: "City of London", name: "City of London School for Girls" (type code 11)
> ECF-RP-538: cip only schools

- terraform/app/modules/paas/main.tf
- terraform/app/modules/paas/variables.tf
- terraform/app/terraform.tf
- terraform/app/variables.tf
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/review.tfvars
- terraform/workspace-variables/staging.tfvars
This is PR 1/3 for this ticket.
Inspired by TVS, we want to run background jobs in a different instance. We do this in staging and prod. Review and dev have the background jobs running in the web container already.
Added the worker app to review in the first commit, checked it worked:
N/A
> ECF-RP-564: Worker app to run delayed jobs

- terraform/app/modules/paas/data.tf
- terraform/app/modules/paas/main.tf
- terraform/app/modules/paas/variables.tf
We need to add a store for partnership_csv_uploads
Add s3 bucket to terraform build
aws-s3-bucket config should be available in cf $VCAP_SERVICES
> add bucket for csv uploads

- Gemfile
- Gemfile.lock
- README.md
- config/initializers/rswag_api.rb
- config/initializers/rswag_ui.rb
- config/routes.rb
- lib/tasks/swaggerize.rake
- spec/swagger_helper.rb
- swagger/v1/api_spec.json
Rake task: **rswag:specs:swaggerize**
This was mainly borrowed from the [teacher-training-api](https://github.com/DFE-Digital/teacher-training-api) project
Place you spec request files into spec/docs directory
Run the task ```rswag:specs:swaggerize```
The open api spec will be written into the ```swagger``` directory
https://ecf-review-pr-306.london.cloudapps.digital/api-docs/index.html
(operation definitions will come in other PRs)
> Add swagger doc generation rake task

- app/views/nominations/request_nomination_invite/review.html.erb
- spec/cypress/integration/nominations/ResendNominations.feature
- spec/cypress/support/step_definitions/common-interaction.js
https://trello.com/c/cm5YvYr9
yes
not sure - i worked in cypress
> Clear location field when changing school in resend nomination flow

- app/webpacker/styles/subnav.scss
They were appearing always on windows - clearly, this isn't the correct behaviour!
i miss percy
> Fix subnav scrollbar issue

- app/controllers/admin/administrators/administrators_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- config/routes.rb
- spec/docs/users_spec.rb
- spec/requests/api/users_spec.rb
- swagger/v1/api_spec.json
E&L will need to know the list of users from R&P. Coupled with https://github.com/DFE-Digital/ecf-engage-and-learn/pull/79 to actually hit the client.
Add Users controller to our API. Generate docs for it. Hide it in any environments with real data.
What that list exactly is, what fields they will need, which subset of users depending on time, whether it is paginated, and so on are all great questions, but they can be tackled one by one in later PRs. 
I checked that I receive and deserialize the data correctly in E&L app, when running both things locally. Other than that, not sure how much there is to test here. I guess I should add a unit test in rspec for it. 
Hit `/api-docs` and look at our nice swagger doc.
> CPDEL-385: Add very basic users endpoint

- spec/rails_helper.rb
- spec/requests/challenge_partnership_spec.rb
Fix for intermittent test failures 
`Faker::Number.unique.clear` in 2 failing test blocks
Run spec/requests/challenge_partnership_spec.rb
> clear faker limit for failing tests

- app/forms/supplier_user_form.rb
- app/mailers/lead_provider_mailer.rb
- app/models/lead_provider_profile.rb
- spec/mailers/lead_provider_mailer_spec.rb
- spec/models/lead_provider_profile_spec.rb
Much like with the admins, when a lead provider user is created, we want to send them a welcome email.
- Copy the setup from the admin and induction coordinator profiles
- Create welcome email template in notify
Sign in as admin@example.com. On the suppliers tab, add a new user with email cpd-test+school-1@digital.education.gov.uk (any whitelisted email that doesn't have an account). Ensure you get the email
> ECF-RP-490: Lead provider welcome email

- spec/rails_helper.rb
Removes the following annoying warning message when running rspec:
```
DEPRECATION WARNING: Initialization autoloaded the constant ApplicationHelper.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.
`config.autoloader` is set to `classic`. This autoloaded constant would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.
In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:
Rails.application.reloader.to_prepare do …
```
> Add require application_helper to rails helper

- db/migrate/20210506161800_case_insensitive_user_emails.rb
- db/schema.rb
- spec/requests/users/sessions_spec.rb
User could not log in by entering their email address with any capital letter.
As devise is already down-casing all email I've decided to use citext for users email column - this way case insenstive search is now enabled on email column by default (in case we'd ever need to do sth similar in other places)
> Case insensitive user email field

- .github/workflows/lint.yml
- .github/workflows/test.yml
The versions of that action were a bit old, and inconsistent. On occasion it would cause the pre-commit hook checking for aws keys unhappy too.
Update the version to something consistent and new (copy of what I did in E&L repo)
If the actions pass it probably means it's good to go. 
N/A
You can't
> Update setup-ruby github action version

- .github/workflows/deploy_to_sandbox.yml
- config/credentials/sandbox.yml.enc
- config/environments/sandbox.rb
- terraform/workspace-variables/sandbox.tfvars
We want a sandbox environment in order to allow lead providers to develop and test their integrations against our code.
The action hasn't been tested as it has to be in `develop` to be able to run it.
The GovPaaS space and terraform state bucket have been created and configured as per https://github.com/DFE-Digital/early-careers-framework/blob/197413ab705b207d7d1ce6dafb2c00690efff415/documentation/terraform.md
https://dfedigital.atlassian.net/browse/CPDTP-168
* New Github action for deploying to new environment (mostly copied from staging/production actions)
* New terraform vars (mostly copied from staging)
:ship:
* merge it then test it by running the new action
> CPDTP-168 Add sandbox environment

- app/views/check_account/show.html.erb
Supersedes old PR https://github.com/DFE-Digital/early-careers-framework/pull/347
> Updates to page title and copy

- terraform/workspace-variables/sandbox_app_env.yml
```
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
/home/runner/work/_temp/49805c3b-c0fc-41d8-9ba1-851cf307647d/terraform-bin apply -input=false -auto-approve -var-file ../workspace-variables/sandbox.tfvars -var=secret_paas_app_env_values={"RAILS_MASTER_KEY":"***", "RELEASE_VERSION":"9531f52967214eba0081345b3cdb57783fdf77eb"} -var logstash_url=***
Error: Invalid function argument
on variables.tf line 110, in locals:
110:   paas_app_env_yml_values = yamldecode(file("${path.module}/../workspace-variables/${var.app_environment}_app_env.yml"))
|----------------
| path.module is "."
| var.app_environment is "sandbox"
Invalid …
```
> Add missing sandbox_app_env.yaml for terraform deploy step

- Gemfile
- Gemfile.lock
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/serializers/user_serializer.rb
- spec/docs/users_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1/users_spec.rb
- spec/spec_helper.rb
- swagger/v1/api_spec.json
- I gather we want to conform to jsonapi spec defined at https://jsonapi.org
- Change existing `/api/v1/users` endpoint so it conforms to jsonapi spec
- Added `jsonapi-serializer` it seems far better maintained compared to https://github.com/jsonapi-rb/jsonapi-rails and https://github.com/jsonapi-rb/jsonapi-rb despite the fact it only deals with the serialisation part I feel this is the better option
- Uncommented an rspec config so developers can focus on tests
- This is a breaking change to the API but as far as I'm aware is not in use so should be safe to change
- curl -I https://ecf-review-pr-341.london.cloudapps.digital/api/v1/users
- check `Content-Type` header
- should match spec defined at https://jsonapi.org/format/#content-negotiation-servers
- curl …
> /api/v1/users returns valid jsonapi

- .editorconfig
- README.md
Follow up to PR #333
* CPDTP-168 - Document provider token generation in readme
* Also add markdown editorconfig rules (see commit message)
:ship:
> CPDTP-168 - Document provider token generation in readme

- config/routes.rb
Bringing the routing table for the sandbox environment In line with the other outward facing services
Remove users from rails routing for sandbox and make the configuration for those environment flags slightly cleaner.
:ship:
> Remove Users controller from Sandbox

- app/views/users/sessions/redirect_from_magic_link.html.erb
- spec/cypress/support/step_definitions/notifications.js
Just a copy change on the interstitial page after following a sign in link
Sign in using email. e.g. cpd-test+tutor-1@digital....
> CPDRP-309: Update copy on sign in successful page

- app/controllers/users/sessions_controller.rb
- app/views/users/sessions/link_invalid.html.erb
- config/routes.rb
- db/schema.rb
- spec/cypress/integration/accessibility.js
- spec/requests/users/sessions_spec.rb
Replace the flash notice with a dedicated page when a sign in link is expired/invalid
http://ecf-review-pr-380.london.cloudapps.digital/users/confirm_sign_in?login_token=6b90d44386421d48e29c
> CPDRP-312: invalid sign-in link

- app/controllers/users/sessions_controller.rb
- app/views/users/sessions/new.html.erb
Replace the flash alert with some proper design system error messages when the sign in email is blank
Before:
After:
try to sign in with a blank email
> CPDRP-311: Format sign in form errors correctly

- terraform/app/variables.tf
Changed to the image of our worker app don't cause a restage, so the app isn't actually updated
> Change worker deploys to blue green

- db/seeds/dummy_structures.rb
On development (and review) apps we wipe the database each time we push - and then reseed it. This is to make testing non-reversible scenarios painless.
It has a side effect of wiping away any tokens that we might want to set up on `dev`. I would very much like to have some versions of E&L pointing at dev R&P to fetch their users, and for that I need a stable token.
Add a token with a fixed hash to the part of seed files that only get run on dev, deployed dev and in test. Fixed hash = fixed unhashed token, which I can then use to authenticate without worries of R&P db getting recreated.
I checked that the token works. Not sure how public we want to make it - it should not work in staging or prod, unless someone makes a mistake in code and then also seeds staging/prod db...
I checked that …
> CPDEL-438: Add a stable E&L token to dummy environments

- terraform/workspace-variables/sandbox.tfvars
Updated subdomain to 'sandbox' as it was taken previously so the sandbox URL will be https://ecf-sandbox.london.cloudapps.digital/
> Change sandbox subdomain from sanbdox-api to sandbox

- db/seeds/dummy_structures.rb
In my haste to get a token working I forgot that devise uses another secret to generate tokens, and that it is different for different environments. For good reasons too.
So I made a new token using rails console in our dev environment, and put that in too. I checked that that one actually works on https://github.com/DFE-Digital/ecf-engage-and-learn/pull/110. 
I wanna keep the dev one too, so when someone from E&L seeds the db they have a token they can use for development without fuss of making a new one.
> CPDEL-438: Add different token for deployed dev

- app/controllers/api/v1/early_career_teacher_participants_controller.rb
- app/services/induct_participant.rb
- spec/docs/early_career_teacher_participation_spec.rb
Shouldn't create a new ```ParticipationRecord``` on every call with the same ```id```
> Tweak creation of participation record when called more than once

- app/components/primary_nav_component.rb
- app/controllers/lead_providers/base_controller.rb
- app/controllers/lead_providers/school_details_controller.rb
- app/controllers/lead_providers/your_schools_controller.rb
- app/models/school.rb
- app/views/lead_providers/school_details/show.html.erb
- app/views/lead_providers/your_schools/index.html.erb
- config/routes.rb
- db/seeds/test_data.rb
- spec/cypress/app_commands/scenarios/lead_provider_with_schools.rb
- spec/cypress/integration/lead_providers/YourSchools.feature
- spec/models/school_spec.rb
- spec/requests/lead_providers/school_details_spec.rb
[Trello card](https://trello.com/c/oLsN0lH9/581-view-and-manage-schools-school-detail)
Builds upon the __Your schools__ functionality from PR #323 
Add school detail view
When signed-in as a lead provider, visit `/lead-providers/your-schools` (there is no direct link to the page currently) then clicking on one of the school links in the table of schools will show the school details page for that school.
> Add school detail view for Lead providers

- app/controllers/schools/partnerships_controller.rb
- app/forms/confirm_schools_form.rb
- app/jobs/partnership_activation_job.rb
- app/models/partnership.rb
- app/models/school.rb
- app/models/school_cohort.rb
- db/migrate/20210514100703_add_started_at_to_partnerships.rb
- db/schema.rb
- spec/factories/partnership.rb
- spec/forms/confirm_schools_form_spec.rb
- spec/jobs/partnership_activation_job_spec.rb
- spec/models/partnership_spec.rb
Replaces #328 as a method for having pending partnerships
When a lead provider declares a partnership with a school who has told us they are doing CIP, we wait 2 weeks before doing anything about it.
- Add pending boolean to partnerships
- Add job to convert pending partnerships
> Pending partnerships

- app/views/cookies/show.html.erb
- app/views/privacy_policies/show.html.erb
- Use two-thirds page width for privacy policy. Constrain text to 2/3rds grid to give a readable line-length. Without this the line are too long and reading the text is more difficult
- Increase font-size of title on Cookies page
Ignore whitespace when reviewing.
> Fix privacy page content width

- app/controllers/cookies_controller.rb
- app/views/accessibility_statements/show.html.erb
- app/views/layouts/_support_links.html.erb
- app/views/lead_providers/confirm_schools/show.html.erb
- app/views/nominations/request_nomination_invite/choose_location.html.erb
- db/seeds/privacy_policy_1.0.html
- spec/cypress/integration/Cookies.feature
- spec/requests/cookies_spec.rb
There are many uses of smart quotes already, but some inconsistencies in the privacy policy, accessibility statement and the cookie banner.
> Use smart quotes consistently

- app/controllers/api/v1/participant_declarations_controller.rb
- config/routes.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/provider_events_spec.rb
- swagger/v1/api_spec.json
The previous path at `/api/v1/early-career-teacher-participants` was temporary and doesn't accurately describe collecting declarations that relate to a participant. This action will be expanded later to accept a declaration type.
- Rename route `/api/v1/early-career-teacher-participants` to `/api/v1/participant-declarations`
- Rename controller `EarlyCareerTeacherParticipantsController` to `ParticipantDeclarationsController`
> Rename participant declaration endpoint

- config/routes.rb
- spec/routing/sandbox_controller_spec.rb
You can't currently preview the sandbox page without deploying to the sandbox env or configuring sandbox correctly locally.
Move sandbox landing page to `/sandbox`
* Hide sandbox page in production.
* [307 "temporary redirect"](https://httpstatusdogs.com/307-temporary-redirect) from  `/` to `/sandbox` for sandbox environment.
This change means you can preview the sandbox landing page in local development, dev, staging and in review-apps.
Go to /sandbox in preview app. https://ecf-review-pr-405.london.cloudapps.digital/sandbox
Check that / still renders normal index. https://ecf-review-pr-405.london.cloudapps.digital/
> CPDTP-170 Move sandbox landing page to /sandbox

- app/views/sandbox/show.html.erb
One that is in there belongs to a different team.
Follow up to #404 
* correction to email address
https://ecf-review-pr-412.london.cloudapps.digital/sandbox
> Switch to CPD email address on sandbox landing page

- README.md
- app/models/feature.rb
- app/services/feature_flag.rb
- db/migrate/20210525120431_create_features.rb
- db/schema.rb
- lib/tasks/safe_reset.rake
- spec/services/feature_flag_spec.rb
Extending the work in https://github.com/DFE-Digital/early-careers-framework/pull/407
Our current infrastructure set-up made it non-trivial to persist feature flag environment variables across deploys. They would be reset each time. Instead, we can store them in the database. This will allow us to create an interface to display, create and edit them in the future.
We might want a way to seed states in development, but we can figure that out later.
(This was copied from [apply-for-teacher-training](https://github.com/DFE-Digital/apply-for-teacher-training).)
> Use persisted feature flags

- db/schema.rb
This schema file is the one that is actually generated when you run
a schema:dump or migration against the current database. A previous
PR changing the induction_coordinator_profiles_schools id to not be
nullable, should have included this.
Previous PR#382 modified the schema, but it didn't include the uuid default as part of the change until you do a rails db:schema:dump. This line keeps getting added to other commits that perform migrations, so it gets it's own PR.
> Schema file correction.

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- spec/docs/users_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users_spec.rb
- swagger/v1/api_spec.json
The number of users can probably get quite big, so much so that we won't really want to fetch all of them at all times. This adds a few ways to manage that - pagination is one, sending `updated_since ` parameter being the other. Also generates some fancy api docs for params.
Add pagination gem
Add pagination params to users api
Add changed_since param to users api
Update the api docs
I have stolen almost all of it from another repo, https://github.com/DFE-Digital/teacher-training-api
I noticed they are using a `yml` file for all their schemas, which they then share between requests. We don't really do much reusing yet, but do we want this? yml is nicer to write those specs in than ruby in my personal opinion.
Added unit tests for pagination, still need to add them for the time-based …
> Add pagination and changed_since to users api

- .github/workflows/deploy_to_production.yml
- .github/workflows/deploy_to_staging.yml
We currently update `master` to reflect what we are _attempting_ to deploy to staging. If the deploy to staging failed `master` would diverge from what was deployed to staging.
This PR adjusts the deploy workflow so that master reflects what has been _deployed_ to production. I think it is more useful if we have visibility of production than staging like this.
I also needed to relax the linear history constraint default as we had previously changed this protection rule off on develop.
It's worth noting that this is not tested because it needs to be merged first.
> Adjust deploy workflow so that master reflects production

- README.md
The payment_calculator section in the readme file has been updated to reflect what is actually happening in the code.
Specifically, it now expands on usage and scope of the calculator, since that has now been updated to require a contract object to be passed in.
> updated README.md to reflect what the new payment calculator is actually doing

- app/helpers/application_helper.rb
- app/models/analytics_data_layer.rb
- app/models/user.rb
- app/views/layouts/_application.html.erb
- spec/helpers/application_helper_spec.rb
- spec/models/analytics_data_layer_spec.rb
- spec/models/user_spec.rb
[Jira](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-276)
Enable surfacing information to GA
Adds a `AnalyticsDataLayer` class to manage the information
Adds helpers to the `ApplicationHelper` to construct the basic information
Adds `user_type` to `User` model to provide a description of the user
Renders the output of the analytics into a JS variable in the application layout partial
On any page (assuming it is rendered using the application layout) if you inspect the page in a browser you will see in the `<head>` section a `<script>` tag that populates a `dataLayer` variable.  If you are signed in this will include your user "type", if not signed in it will be an empty array.
e.g. signed in as a Lead provider
```html
<script>
dataLayer = …
```
> Add data layer info for analytics

- Gemfile
- Gemfile.lock
- app/components/lead_providers/your_schools/table.html.erb
- app/components/lead_providers/your_schools/table.rb
- app/components/lead_providers/your_schools/table_row.html.erb
- app/components/lead_providers/your_schools/table_row.rb
- app/controllers/admin/schools_controller.rb
- app/controllers/api/school_search_controller.rb
- app/controllers/lead_providers/your_schools_controller.rb
- app/models/school.rb
- app/views/lead_providers/your_schools/index.html.erb
- spec/components/lead_providers/your_schools/table_row_spec.rb
- spec/components/lead_providers/your_schools/table_spec.rb
- spec/models/school_spec.rb
- spec/requests/lead_providers/your_schools_spec.rb
As written, lead_providers/your_schools queried schools that has partnership with current lead_provider only to query partnership-related data for each school later on.
This PR brings no behaviour change, but makes the controller query the partnerships instead of school. This fixes a  umber of N+1 issues as it makes all the partnership data easy to access.
I have also added ransack for more streamlined search forms. This made a number of scopes on school obsolete.
> Refactor LeadProvider/YourSchool

- app/models/additional_school_email.rb
- app/models/school.rb
- app/services/additional_email_importer.rb
- db/migrate/20210527113042_create_additional_school_emails.rb
- db/schema.rb
- lib/tasks/additional_emails.rake
- spec/fixtures/files/example_emails.csv
- spec/models/additional_school_email_spec.rb
- spec/models/school_spec.rb
- spec/services/addional_email_importer_spec.rb
CPDRP-348
Matt provided a CSV of emails scraped from school websites. This cleans and imports that list to a new table. When we come to import these emails in production we will transfer the CSV to the server via SCP and run the job there.
- Create model for additional emails for a school
- Define a ruleset for cleaning additional emails
- Add a task to import emails from a CSV
Unit testing, manually tested
This can be tested as part of CPDRP-374
> CPDRP-348: Import additional school emails from a CSV file

- app/views/lead_providers/report_schools/csv/show.html.erb
Fixes typo in "Maximum" on CSV upload page.
Minor content change to correct a typo
As a lead provider user, navigate the "Confirm your schools" journey until you get to the CSV upload page, you should see "Maximum file size" not "Maxiumum file size"
> Quick typo fix

- app/forms/delivery_partner_form.rb
- spec/forms/delivery_partner_form_spec.rb
CPDRP-394
This fixes an issue where assigning a Lead Provider to one Delivery Partner would unassign it from all others
Added new spec to prevent regression
Sign in as admin@example.com, tick the same LP for two DPs. Ensure it persists
> CPDRP-394: Bugfix - issue with pairing LPs and DPs

- app/controllers/api/v1/dqt_records_controller.rb
- lib/dqt.rb
- spec/requests/api/v1/dqt_records_spec.rb
- API endpoint currently returns data if no DQT record is found
- the client would need to parse this to figure out there is no record
- API now returns 404 if no DQT record is found
- This makes it easier for clients to handle such cases
- n/a
- Setup DQT api keys so it can call into the sandbox
- Create an api token with `NpqRegistrationApiToken.create_with_random_token!`
- Note down the unhashed token, it will be needed later
- Call endpoint with `curl -H "Authorization: Bearer UNHASHED_TOKEN" localhost:3001/api/v1/dqt-records/100`
- Should return body-less 404 response
- NOTE: not sure if review apps are hooked up to DQT sandbox? if not this won't work
- Create an api token with `NpqRegistrationApiToken.create_with_random_token!`
- Note down the unhashed token, it will be needed later …
> DQT record api returns 404 if no record is found

- app/controllers/admin/administrators/administrators_controller.rb
- app/forms/supplier_user_form.rb
- app/models/nomination_email.rb
- app/services/create_induction_tutor.rb
- app/services/partnership_notification_service.rb
- app/services/utm_service.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- lib/tasks/manage_admins.rake
- spec/requests/admin/administrators/administrators_spec.rb
- spec/tasks/manage_admins_spec.rb
Chris wants UTM params on links to the service in emails to help with GA: https://dfedigital.atlassian.net/browse/CPDRP-275
- Add a UTMService to centralise information about UTM params and campaigns
- Add UTM params to all email links
Easiest way is to sign in with one of the cpd-test email addresses and check the sign in link. 
I've added the params to:
- New admin welcome email
- New lead provider welcome email
- New induction tutor welcome email
- Initial email to school (invitation to nominate)
- Sign in email
- Partnership notification email
> CPDRP-275: Add UTM parameters to all links to the service in emails

- config/initializers/rack_attack.rb
Don't throttle Notify API callbacks, as they've been hitting the rate limit
> CPDRP-392: Safelist notify API callbacks

- app/views/schools/partnerships/_signed_up_with_provider.html.erb
- spec/cypress/app_commands/scenarios/confirm_cip.rb
- spec/cypress/integration/schools/ViewPartnerships.feature
- spec/cypress/support/step_definitions/common-interaction.js
- spec/requests/schools/partnerships_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-395
This page wasn't tested in Cypress so I added a test (and improved the existing one).
Waiting on feedback around the "This link will expire" text and whether it should stay as it isn't in the designs.
- [ x All pages have visual tests via cypress + percy
- [ x All `School` queries are correctly scoped - `eligible` when they need to be
- Sign in as induction coordinator
- Sign up to FIP
- Create partnership in database
- Navigate to page
(Or just look at it in cypress like I did)
> Ensure design of "your training provider page" matches designs

- app/models/school.rb
- app/services/invite_schools.rb
- lib/tasks/schools.rake
- spec/models/school_spec.rb
- spec/services/invite_schools_spec.rb
CPDRP-374
We want to send chaser emails to school who have not yet nominated a tutor. We send these to every email we have available for the school
Add a task to email all eligible schools with no nominated tutor
This will need updating once the opt out journey is finished to not email opted out schools
Drop me a message, we can go through this, the additional email CSV (CPDRP-348), and the GIAS email updates (CPDRP-296) all together
> CPDRP-374: send chaser emails

- README.md
- spec/docs/dqt_records_spec.rb
- spec/docs/users_spec.rb
- swagger/v1/api_spec.json
- Missing swagger docs for DQT records endpoint
- Add missing swagger docs for DQT records endpoint
- Current swagger output is not valid but is outside the context of this PR
- Fire up the rails app
- Visit http://localhost:3001/api-docs/index.html
- Should see additional documentation for endpoint 
- Visit https://ecf-review-pr-447.london.cloudapps.digital/api-docs/index.html
- Should see additional documentation for endpoint
> Add swagger docs for /api/v1/dqt-records endpoint

- db/seeds/dummy_structures.rb
- NPQ registration requires api access in the deployed dev environment
- So integration environments work with one another
- Add Npq api token to seeds so they added to the deployed dev environment
n/a
- Test on review app
- `cf login --sso`
- `cf ssh ecf-review-pr-462`
- `export PATH="/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/bin:$PATH"`
- `cd /app`
- `bundle exec rails c`
- `NpqRegistrationApiToken.find_by(hashed_token: "1dae3836ed90df4b796eff1f4a4713247ac5bc8a00352ea46eee621d74cd4fcf")`
- Should return a token
> add NpqRegistrationApiToken to seeds for dev env

- app/models/call_off_contract.rb
- app/models/participant_band.rb
- spec/models/call_off_contract_spec.rb
- spec/services/calculation_orchestrator_spec.rb
PostgreSQL orders with NULL values being compared as higher than any other numeric.
Ref: https://stackoverflow.com/questions/5826210/rails-order-with-nulls-last/7055259
Force NULLS to be treated first as a sort for band ordering
Validate in Console with the Banding model. CalloffContract model test has been updated to use unnamed bands and force the lookup.
You can't
> Banding entries with nil sort as the highest values.

- app/forms/lead_providers/report_schools_form.rb
Out LeadProviders::ReportSchoolsForm was accessing Partnerships::Report constant. It was a no-problem lookup in the PR which introduced `Partnerships::Report`, however another PR introduced `LeadProviders::Partnerships` namespace, which is now causing `Partnership` constant to resolve to `LeadProviders::Partnerships` rather than `::Partnerships`. Most likely we need a bit more thinking about the namespaces, but this will fix the issue for now.
> Fixed silent conflict causing wrong constant lookup scope

- README.md
- db/seeds/sandbox_data.rb
- lib/tasks/payment_breakdown.rake
Depends on [this branch](https://github.com/DFE-Digital/early-careers-framework/tree/CPDTP-131)
```
rake payment_calculation:breakdown Capita
```
Result:
```
{
"service_fees": {
"service_fee_per_participant": "316.67",
"service_fee_total": "633339.0",
"service_fee_monthly": "21839.28"
},
"output_payment": {
"per_participant": "587.4",
"start": {
"retained_participants": 0,
"per_participant": "117.48",
"subtotal": "0.0"
}
}
}
```
> Add rake task to run payment calculator to get payment breakdown for a lead provider

- spec/cypress/app_commands/scenarios/cip_cohort_with_school.rb
- spec/cypress/integration/schools/core_induction_programme/ChooseMaterials.feature
- spec/cypress/support/step_definitions/common-navigation.js
Oddly it worked on CI but not locally for me.
I'm getting another failure locally at the moment so don't merge till that's been investigated.
Run cypress locally as per https://github.com/DFE-Digital/early-careers-framework/#end-to-end-tests
> Fix local failure to find id in cypress

- app/models/early_career_teacher_profile.rb
- app/models/lead_provider.rb
Missing links from `ect_profiles` and `lead_provider`
Only had `belongs_to` links in `participations_declarations`. This completes the link by adding in the inverse too
> CPDTP-188 Inverse link to participation_declarations from early_career_teacher_profile and lead_provider

- app/views/lead_providers/report_schools/csv/errors.html.erb
- app/views/lead_providers/report_schools/csv/show.html.erb
- spec/requests/lead_providers/report_schools/csv_spec.rb
CPDRP-343
Our data analyst needs information on the errors displayed to users to measure the performance of new features.
- Track number and type of errors on CSV rows
- Track CSV file errors
Sign in as lead-provider@example.com, upload a CSV with errors, check the datalayer using dev tools
> CPDRP-343: Track CSV errors in GA data layer

- app/controllers/api/api_controller.rb
- app/services/induct_participant.rb
- app/services/record_participant_event.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/provider_events_spec.rb
- swagger/v1/api_spec.json
API generation for swagger had a couple of errors and omissions.
The 2nd 204 status description was being picked up so rather than successful, it was showing "Duplicate successful". 
The format for the `declaration_date` was 'date', rather than 'date-time'.
Also, as we're  not using zeitwerk, we need to be more explicit in the require locations, otherwise we get a 500 error when trying to send a new event.
Add in the correct 'date-time' and description and regenerate swagger docs.
Explicitly require 'initialize_with_config' in the RecordParticipantEvent service and InductParticipant services.
The api-docs/index.html endpoint shows the correct status for 204 in the participant-declarations API return values.
> Regenerate swagger docs and fix preloader

- db/migrate/20210608084207_change_primary_key_to_uuid_on_induction_coordinator_profiles_schools.rb
- db/schema.rb
[Jira ticket](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-393)
Fix issue with integer primary key
The `induction_coordinator_profiles_schools` is a join table that had an `id` added so that paper trail could record it. We are using a gem `ar-uuid` which is supposed to automagically make primary keys uuids but for reasons unknown it didn't pick up the `primary_key` statement in that migration and so it was created as a `bigint`.
Worth noting is that the `versions` table managed by paper trail was configured to expect `item_id` to be a `uuid` but this also has a default to automatically generate a uuid so any existing paper trails for `induction_coordinator_profiles_schools` will not be easily reconciled.
Look at the migration steps
Adds a …
> Added migration to replace integer id with uuid

- Gemfile
- Gemfile.lock
- app/forms/nominate_induction_tutor_form.rb
- app/forms/supplier_user_form.rb
- app/models/user.rb
- app/validators/notify_email_validator.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
- spec/validators/notify_email_validator_spec.rb
CPDRP-418
Users have been entering invalid emails and are presented with an error
page instead of a validation message. This is because our validation
rules do not match Notify's. This is an attempt to bring them in line.
I asked the Notify team if they'd be interested in adding the logic to the client SDKs, but they said no: https://ukgovernmentdigital.slack.com/archives/C0E1ADVPC/p1623151272077400
- Add NotifyEmailValidator
- Use the validator where we accept emails
Copied the tests from Notify, with some caveats
Try nominating someone with email "a@b,com"
> CPDRP-418: Notify email validation

- app/controllers/api/v1/dqt_records_controller.rb
- app/controllers/concerns/api_token_authenticatable.rb
- app/models/npq_registration_api_token.rb
- db/migrate/20210609094438_add_access_booleans_to_token.rb
- db/schema.rb
- spec/requests/api/v1/dqt_records_spec.rb
- We want certain api endpoint to be private. e.g. for internal use only and not for public consumption
- For example the `DqtRecordsController` api endpoint should only be accessible for internal use
- On `ApiToken` introduce `private_api_access` to determine if a token can access private api endpoints
- On api controllers one can now define `access_scope` to limit api token to a certain subset
- By default all existing endpoints will continue to be accessible to existing tokens
- The `DqtRecordsController` endpoint is now only accessible to tokens marked with `private_api_access` set to `true`
- By default new `NpqRegistrationApiToken` will have access to private api endpoints
- When adding new endpoints if developers do not want to use this feature there should be no extra burden to …
> ApiTokens and endpoints can have private access

- .github/workflows/deploy_to_production.yml
We weren't checking out the correct code when deploying to production. This had two implications:
1. We weren't updating `master` with the deployed code
2. We weren't applying Terraform scripts from the target deploy tag but instead from `develop`.
This PR checks out the correct target version before deploying.
Hat tip to @ethanmills for spotting this!
> Update master with deployed tag

- Gemfile
- Gemfile.lock
- etc/schema/0.1/ecf/participant_declarations/create/request_schema.json
- etc/schema/0.2/ecf/participant_declarations/create/request_schema.json
- lib/initialize_with_config.rb
- lib/json_schema/version_event_file_name.rb
- lib/json_schema/versioned_schema_reader.rb
- spec/lib/initialize_with_config_spec.rb
- spec/lib/json_schema/version_event_file_name_spec.rb
- spec/lib/json_schema/versioned_schema_reader_spec.rb
incoming json can be validated against a schema document to ensure that the content and format are as expected before passing bad data to the underlying code.
This puts in place the ability to use the JSON::Schema gem to validate against a set of connected json schema documents and to have those local file based and translate http uris to file uris.
In addition, it has been proposed that we allow current API version + 2 ancestors, and this will help ensure that versioning is managed correctly by comparing incoming json documents against the correctly versioned schema.
- Slight enhancement to InitializeWithConfig to allow it to raise more verbose error messages when required configuration items (Dependency Injection) are required and support for classes which include them to optionally …
> CPDTP-196 JSON Schema URI to Local Filename Converter and reader

- app/models/school.rb
- app/services/invite_schools.rb
- spec/models/school_spec.rb
- spec/services/invite_schools_spec.rb
Now that we're giving schools the ability to opt out, we need to honour that in chaser emails.
- Scope for schools that have not opted out
- Send emails using delayed job
- Only send emails to schools who have not opted out
Updated unit tests
> Cpdrp 421 use opt out decision in chaser emails

- app/controllers/application_controller.rb
- app/controllers/cookies_controller.rb
https://dfedigital.atlassian.net/browse/CPDRP-407
To replicate the original issue:
- Go to e.g. https://ecf-review-pr-493.london.cloudapps.digital/
- DON'T TOUCH the cookies
- log in as school-leader@example.com
- On priv policy page, try to accept cookies
Unsure if this needs request specs. I can't see how this would change in the future without invalidating the tests.
see pr app below
> Fix issue where cookie banner couldn't be accepted from privacy page

- config/initializers/pagy.rb
- spec/docs/participants_spec.rb
- swagger/v1/api_spec.json
Couple of related things here:
- Change Pagy to return an empty page when requesting a page with no contents
- Update the swagger docs to match the data on sandbox
Previously Pagy would throw an exception when it ran out of pages. Sandbox has 10 ppts per lead provider, so we were seeing exceptions in the swagger examples
> Handle pagy overflow

- app/components/lead_providers/your_schools/table_row.html.erb
- app/views/lead_providers/report_schools/confirm/show.html.erb
- app/webpacker/styles/lead_providers/your_schools.scss
- ~Button group was missing on the confirm CSV page~
- Table was displaying wrong as a cell had been set to display: flex
- Specificity issue was causing reported tag to have margin-top even on desktop
https://dfedigital.atlassian.net/browse/CPDRP-440
All changes should appear in percy :)
the bug appeared in percy so should be covered!
> Fix a couple styling issues for lead providers

- Gemfile
- Gemfile.lock
- app/models/call_off_contract.rb
- app/models/participant_band.rb
- db/seeds/sandbox_data.rb
- lib/payment_calculator/ecf/contract/service_fee_calculations.rb
- lib/payment_calculator/ecf/service_fees.rb
- lib/payment_calculator/ecf/service_fees_for_band.rb
- lib/tasks/payment_breakdown.rake
- spec/lib/payment_calculator/ecf/contract/service_fee_calculations_spec.rb
- spec/lib/payment_calculator/ecf/payment_calculation_spec.rb
- spec/lib/payment_calculator/turnip_steps/ecf/call_off_contract_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/service_fees_steps.rb
- spec/services/calculation_orchestrator_spec.rb
Previously only Band A was used in calculation, this change includes all the banding and generates payment breakdown as the following:
```
+----------------------------------------------------+
|                 Breakdown Payments                 |
+---------+------------------+-----------------------+
| Banding | Service fee (PP) | Service fee (monthly) |
+---------+------------------+-----------------------+
| Band A  |     £558      |         £38,448          |
| Band B  |     £520      |         £35,862          |
| Band C  |      £480     |         £8,276           |
+---------+------------------+-----------------------+
Output payment (started) £756,000
Based on 4,500 participants and £1400 per participant in Band A, £1300 per participant in Band B, £1200 per participant in Band C …
```
> CPDTP-166 Add bands to service fees and tweak payment breakdown rake task

- app/services/record_participant_event.rb
- config/locales/en.yml
- spec/docs/participant_declarations_spec.rb
- swagger/v1/api_spec.json
Error messages returned by the schema validator include "in schema <GUID_FOR_SCHEMA>" which contains more information than the caller actually needs.
Also, it has been decided to return a 422 if we don't have a valid participant_id (uuid) for the API call.
- Update errors returned by the validate_schema! to remove the superfluous part of the message.
- Change ect_profiles_params and valid_provider to ! versions and raise 422 with error messages for their failing calls.
- Use I18n to display the new participant_id error message
- Update swagger to reflect the updated 422 only messages on error and correct a mistake in the date parameter
add_ect_profile_params! and valid_provider! should now raise a 422 with the participant_id error message.
validate_schema! should iterate through all of …
> CPDTP-196 Fix error message returned by schema validator.

- app/controllers/schools/add_participants_controller.rb
When there are no participants, participant list page automatically redirects to the first step of the add-participant journey. Previously, link was fixed to return user to the participant index page, so it would be redirected back to the first step.
> Fixed back link on the first add-participant step when there are no participants

- lib/payment_calculator/ecf/contract/output_payment_calculations.rb
- lib/payment_calculator/ecf/output_payment_aggregator.rb
- lib/payment_calculator/ecf/output_payment_retention_event.rb
- lib/payment_calculator/ecf/payment_calculation.rb
- lib/tasks/payment_breakdown.rake
- spec/lib/payment_calculator/ecf/contract/output_payment_calculations_spec.rb
- spec/lib/payment_calculator/ecf/payment_calculation_spec.rb
- spec/lib/payment_calculator/turnip_features/ecf/output_payments.feature
- spec/lib/payment_calculator/turnip_steps/ecf/call_off_contract_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/service_fees_steps.rb
- spec/services/calculation_orchestrator_spec.rb
Add bands for output payment in the breakdown calculation
Run the following rake task:
```rake payment_calculation:breakdown Capita 4500```
should print out the following breakdown:
```
+--------------------------------------------------------+
|                   Breakdown Payments                   |
+---------+--------------------+-------------------------+
| Banding |  Service fee (PP)  |  Service fee (monthly)  |
+---------+--------------------+-------------------------+
| Band A  |        £558        |         £38,448         |
| Band B  |        £520        |         £35,862         |
| Band C  |        £480        |         £8,276          |
+---------+--------------------+-------------------------+
| Banding | Output price  (PP) | Output price  (monthly) | …
```
> CPDTP-110 Add output payment for banding

- app/controllers/api/v1/users_controller.rb
- config/routes.rb
- spec/requests/api/v1/users_spec.rb
- NPQ registration collects user data which must be pushed into "CPD manage"
- There will be subsequent pull requests to add attach NPQ profiles and data to these users
- Add a barebones api endpoint to create a user with name and email
- We use email as the "identifier" here
- Existing api points should not be affected
- Should required token with private api access permissions
- Should conform to jsonapi spec
- Test in the review app
- Create an api token with `NpqRegistrationApiToken.create_with_random_token!`
- Note down the token
- create a user with `curl -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer TOKEN" -X POST -d '{ "data": { "type": "user", "attributes": { "full_name": "John Doe", "email": "john.doe@example.com" } } }' …
> API endpoint to create users

- spec/cypress/support/step_definitions/common-navigation.js
- spec/cypress/support/step_definitions/database.js
Will be used to rename :id to :slug in #517 but will also be useful in the future if we ever want to specify more than one param
> Add support for named params in Cucumber

- db/seeds/dummy_structures.rb
I forgot to change a school cohort in the dummy structures back to a full induction programme when i was testing with insomnia. This is needed so i can properly test the response on Engage and Learn side so that we're not allowing full induction programme users to log in. 
Adding a third school with a cohort on a full induction programme.
Making each mentor and ect match up.
> Add full induction programme users to dummy structures

- lib/payment_calculator/ecf/contract/output_payment_calculations.rb
- lib/tasks/payment_breakdown.rake
- spec/lib/payment_calculator/ecf/contract/output_payment_calculations_spec.rb
- spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
- spec/services/calculation_orchestrator_spec.rb
The bug in the calculation when total number of participants was used for each band's subtotal
```rake payment_calculation:breakdown Capita 4500```
Should return correct result as per jira [ticket](https://dfedigital.atlassian.net/browse/CPDTP-110)
> Fix calculation of band's subtotal in output payment

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/npq_profiles_controller.rb
- app/models/npq_course.rb
- app/models/npq_lead_provider.rb
- app/models/npq_profile.rb
- app/models/user.rb
- app/resources/api/v1/npq_course_resource.rb
- app/resources/api/v1/npq_lead_provider_resource.rb
- app/resources/api/v1/npq_profile_resource.rb
- app/resources/api/v1/user_resource.rb
- config/initializers/json_api.rb
- config/routes.rb
- db/migrate/20210616103630_create_npq_lead_providers.rb
- db/migrate/20210616103631_create_npq_profiles.rb
- db/migrate/20210616144524_create_npq_courses.rb
- db/schema.rb
- db/seeds/initial_seed.rb
- spec/factories/npq_courses.rb
- spec/factories/npq_lead_providers.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- NPQ registration collects data on applications of NPQ courses
- We need to push these applications into ECF with profiles (`NpqProfile`)
- A user can have multiple applications therefore are able to have multiple `NpqProfile`s
-  add `jsonapi-resources` gem which does all the heavy lifting of ingesting and producing jsonapi compliant requests and responses
- I have been able to call this endpoint successfully with `json_api_client`
- Of all the libraries looked at, this ones seems the most mature and ticked most of the boxes I feel for our needs
- I can revisit other api endpoints I have recently created and swap out to use this framework instead at a later PR
- I did attempt load the seeds file at before the test suite ran but this cause many failures. Is this something we want to …
> add api endpoint to create npq profiles

- app/models/partnership_csv_upload.rb
- spec/models/partnership_csv_upload_spec.rb
A user reported an issue uploading a URN with a leading zero. This
should handle now, but I've added some Sentry logging to catch if I've
missed anything
> Bugfix: Ensure we don't return any nil schools after CSV upload

- db/seeds/initial_seed.rb
- database is constantly teared down so identifiers keep changing in certain environments
- which means external references to these resources will not be in sync
- hardcode ids on NPQ resources so integration environments do not break 
- Might cause dupes in staging and prod but I can resolve those by hand
- Seeding process should continue to work
- Should be able to run seeds multiple times
- Log onto box
- Seeded data should match that of seeds file
> hardcode NPQ ids for resources

- app/services/calculation_orchestrator.rb
- app/services/contract_event_payment_calculator.rb
- lib/payment_calculator/ecf/contract/service_fee_calculations.rb
- lib/payment_calculator/ecf/contract/uplift_payment_calculations.rb
- lib/payment_calculator/ecf/output_payment_retention_event.rb
- lib/payment_calculator/ecf/payment_calculation.rb
- lib/payment_calculator/ecf/uplift_calculation.rb
- lib/tasks/payment_breakdown.rake
- spec/lib/payment_calculator/ecf/contract/uplift_payment_calculations_spec.rb
- spec/lib/payment_calculator/ecf/payment_calculation_spec.rb
- spec/lib/payment_calculator/ecf/uplift_calculation_spec.rb
- spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/service_fees_steps.rb
- spec/services/calculation_orchestrator_spec.rb
The calculator requires uplift payments to be added into the display and calculation.
**Calculator**:
- Take the number of approved uplift participants and add in the uplift based on this number.
- Update the calculation orchestrator to call and retrieve this number from the aggregator (Note this is a temporary value based on the expected uplift number since there is a separate ticket to perform the actual aggregation which needs to be added to this.)
- Update the calculator to be the PaymentCalculator::Ecf::PaymentCalculation directly and switch this to take a contract rather than a lead provider, since the contract determines the calculation and the only thing that was done with the lead provider was to look this up.
- Update the PaymentCalculator to take an uplift number for …
> CPDTP-109 Display ECF uplift payments

- app/controllers/api/v1/users_controller.rb
- app/serializers/user_serializer.rb
I played with the users api for other reasons, and noticed n+1 queries
Cache school cohorts in the user serialiser. Use existing scope to get user schools alongside their profiles.
If there is a way to accomplish adding a `school_cohort` to the relevant profiles in a railsy association, I would love to know about it. We have a school, we have a cohort, but I don't know how to tell Rails 'and by the way, that defines a school_cohort'.
And that would be imo a neater solution - cause then we could just include `school_cohort` in our query for users.
> Remove n+1 queries from users api

- spec/cypress/integration/Sandbox.feature
- spec/cypress/support/step_definitions/common-navigation.js
The sandbox landing page was added a while ago. It is accessed by external parties (lead providers) so it would be good to know if the display changes before we ship to avoid accidental regressions. Also a11y checks because that's always good.
* Enable a11y and percy checks for sandbox landing page
Let's see what percy does...
> CPDTP-183 Enable a11y and percy checks for sandbox landing page

- lib/payment_calculator/ecf/service_fees.rb
This was indirectly including HasDIParameters but doesn't need the classit was actually referencing.
* change the require to be a more narrow dependency
:ship:
> Refactor - correction to PaymentCalculator require

- lib/tasks/payment_breakdown.rake
- Tweak display output to make it closer to reality
- Remove error log and exit(0) and have it display and return the actual error number
After reviewing the code with the BA and PM a couple of tweak were made to have the display headings more accurate and clean up the display a bit
Also, comments had been made about whether we needed the error catch and exit(0), so they were removed as superfluous code
- Change headings and expand acronyms
- Remove `rescue` and `ensure` to let errors display as normal
run the `rake payment_calculation:breakdown` with lead_provider, total_participants and uplift participants as parameters
e.g.
`rake payment_calculation:breakdown <lead_provider_id> 2000 400`
to run with the contract applied to the lead_provider in the database, a total participant value of …
> CPDTP-109 Update output to clean up the display

- app/serializers/user_serializer.rb
E&L wants users CIPs. For private beta users, I think we need to get them from school cohort model. Up till now we were getting it from the profile. This fixes it.
If user has no CIP on their profile, fetch it from their cohort in the serialiser.
I had a passing thought of recording user's CIP when we create them and backfilling them. Thoughts on that?
You can't
> Serialise CIP from cohorts as well as from profiles

- app/views/privacy_policies/show.html.erb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-319)
Change width of column for privacy policy text
Changes the style on the privacy policy page to use `govuk-grid-column-three-quarters` class instead of `govuk-grid-column-two-thirds`.
> CPDRP-319: change width of privacy policy area

- app/views/layouts/_application.html.erb
- spec/cypress/support/commands.js
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-321)
Change link text in nav bar from "Logout" to "Sign out"
Change link text in nav bar from "Logout" to "Sign out"
> CPDRP-321: Change 'Logout' to 'Sign out' in nav

- app/services/record_participant_event.rb
- spec/requests/api/v1/provider_events_spec.rb
The current API returns a 404 to the caller if either the participant_id is empty or the record is not found.
Design of this requires a 422 with an error body of the participant_id being bad or missing.
Update RecordParticipantEvent to return 422 with the appropriate error condition set rather than raising an ActiveRecord::RecordNotFound which the top level handler catches.
Update the spec tests to also reflect this behaviour.
This is centred around the RecordParticipantEvent returning a nil value for the `find_by()&.early_career_teacher_profile` as opposed to raising an exception. Once this is handled correctly, the expected result is returned.
API testing should allow a missing or incorrect participant_id to return the correct status and message in line with the swagger documentation. …
> CDPTP-255 Handle record not found for ParticipantEvent by returning the expected 422

- app/views/schools/dashboard/show.html.erb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-323)
Width of content should be two thirds not full width.
Wrap content in `govuk-grid-row` and `govuk-grid-column-two-thirds` containers.
> CPDRP-323: Change width of Manage your training page content

- app/views/schools/add_participants/confirm.html.erb
- spec/cypress/app_commands/scenarios/no_mentors_for_participants.rb
- spec/cypress/integration/schools/AddParticipants.feature
[Jira](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-498)
Fix wrong link action and remove link when no mentor available to select.  Also add workaround for `govuk_link_to` [issue](https://github.com/DFE-Digital/govuk-components/issues/193)
Make Change mentor link point to the mentor selection step.
Remove Change mentor link when no mentors available.
Workaround for `govuk_link_to` issue by adding `button: false` to method params so it can correctly handle `url_options`.
As an induction tutor, for a school with no mentors, add an ECT.
On the confirmation step, there should be no "Change" link for the Mentor.
Repeat once a mentor has been added and the Change link should be visible.
Clicking the Change link takes you to the mentor selection …
> CPDRP-498 Fix issue with Change link for mentor

- Gemfile
- Gemfile.lock
- config/initializers/strong_migrations.rb
As part of a previous PR review it was suggested that we add in the `strong_migrations' gem to ensure that any future migrations are checked for any dangerous activity and any preferred alternative solutions are used instead. This gem enables warnings and proposes changes to ensure that the database integrity is preserved.
Add in and initialise the `strong_migrations` gem.
> CPDTP-226 add in strong migrations gem

- app/resources/api/v1/npq_profile_resource.rb
- db/migrate/20210623082855_add_active_alert_to_npq_profiles.rb
- db/schema.rb
- spec/requests/api/v1/npq_profiles_spec.rb
The NPQ profile and respective API should accept an `active_alert` for each participant. Right now we'll just store it, but it might play into the manual validation process for NPQ participants.
> Add active_alert to NPQ profile

- app/views/schools/core_programme/materials/edit.html.erb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-324)
Fix page width and heading style on choose CIP training materials page
Add elements to make page width `govuk-grid-column-three-quarters`
Change style of `h1` heading to `govuk-heading-xl`
> Change page width and heading style

- app/services/partnerships/report.rb
- spec/services/partnerships/report_spec.rb
Using a combination of active job and delayed job syntax results in the
job being scheduled twice: once correctly, and once immediately with no
parameters.
Resolves https://sentry.io/organizations/dfe-bat/issues/2445872434/?project=5748989&query=is%3Aunresolved
> Bugfix: Prevent double scheduling of jobs

- app/models/participant_declaration.rb
- app/services/calculation_orchestrator.rb
- app/services/participant_uplift_aggregator.rb
- db/migrate/20210610090328_add_uplift_to_early_career_teacher_profile.rb
- db/schema.rb
- spec/factories/early_career_teacher_profiles.rb
- spec/factories/participant_declarations.rb
- spec/lib/payment_calculator/turnip_features/ecf/uplift_payment.feature
- spec/lib/payment_calculator/turnip_steps/ecf/uplift_payment_steps.rb
- spec/services/calculation_orchestrator_spec.rb
Aggregator to return number of participants eligible for uplift payment
- New scope for ParticipantDeclaration
- Add new columns `sparsity_uplift` and `pupil_premium_uplift` to profiles
- Update rspec and feature tests
Run calculation orchestrator i.e.
```
lead_provider = LeadProvider.find_by(name: 'Capita')
CalculationOrchestrator.call(
lead_provider: lead_provider,
contract: lead_provider.call_off_contract,
aggregator: ::ParticipantEventAggregator,
uplift_aggregator: ::ParticipantUpliftAggregator,
calculator: ::PaymentCalculator::Ecf::PaymentCalculation,
event_type: :started
)
```
> CPDTP-195 Aggregate number of participants eligible for uplift payment

- app/models/early_career_teacher_profile.rb
- db/migrate/20210621160955_change_early_career_teacher_profile_to_make_cohorts_required.rb
- db/migrate/20210623120047_run_validation_on_early_career_teacher_profile_and_switch_cohorts_column.rb
- db/schema.rb
- spec/docs/participant_declarations_spec.rb
- spec/factories/cohorts.rb
- spec/factories/early_career_teacher_profiles.rb
- spec/requests/schools/participants_request_spec.rb
- spec/serializers/participant_serializer_spec.rb
Cohort was not a mandatory attribute for Early Career Teachers (ECT), but really should be.
- Make cohort required in the database and set a default value for existing records that are currently null.
- Change factories to add cohorts to ECTs.
- Make a :current trait that uses the existing seeded value when this year is used in a factory.
- See https://dev.to/jooeycheng/factorybot-findorcreateby-3h8k for details
Is defaulting the cohort value to 'current', the best and only option? 
Are the assumptions sound?
All existing tests and features should still pass.
It's fundamentally a refactor to make something concrete that has been previously assumed.
> CPDTP-195 Make cohort mandatory for Early Career Teachers

- app/controllers/admin/schools_controller.rb
- app/views/admin/schools/index.html.erb
- spec/cypress/integration/admin/SchoolManagment.feature
- spec/requests/admin/schools_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-501)
Enable admins to search search for schools by induction tutor email
Change the school search to additionally search against induction tutor email
Add hint text to search box to indicate what criteria should be supplied.
As an admin user, on the `/admin/schools` page the search function will also match against induction tutor email address and return schools that have a matching induction tutor (in addition to matching against school name and urn).
> Add induction tutor email to school search

- Gemfile
- Gemfile.lock
- app/controllers/csp_reports_controller.rb
- config/initializers/rack_attack.rb
- config/initializers/secure_headers.rb
- config/routes.rb
- spec/requests/csp_reports_spec.rb
- spec/support/shared_examples/rate_limiting_support.rb
Implement the missing security headers highlighted as missing in the “Details” section, above. Further information on how to achieve this is provided in the “References” section, below.It is further noted that certain HTTP security headers have been known to highlight usability issues in application functionality. When implementing security headers for the first time, rigorous testing is recommended before deploying changes to live environments.
Add host “content-security-policy” header to rails
> Finding No. 6.1.4 Add a content security policy header

- terraform/monitoring/config/development/alert.rules.yml
- terraform/monitoring/config/production/alert.rules.yml
- terraform/monitoring/config/slack.tmpl
- terraform/monitoring/config/staging/alert.rules.yml
- terraform/monitoring/resources.tf
- Add separate alert configs per environment
- Relax dev alert criteria
- Reduce severity of alerts in other environments
- Change monitoring stack to fork to allow setting slack template
- Only notify @channel for high severity alerts
> Reduce alerting noise

- terraform/monitoring/resources.tf
Never goes right the first time... I dug out all the credentials to check this with a `terraform plan` this time and it looks good
> Fix broken tf param

- app/components/lead_providers/your_schools/table.html.erb
- app/components/lead_providers/your_schools/table.rb
- app/components/lead_providers/your_schools/table_row.html.erb
- app/controllers/admin/schools_controller.rb
- app/views/admin/schools/index.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/vendor/_nhs_tables.scss
- spec/components/lead_providers/your_schools/table_spec.rb
- spec/cypress/app_commands/scenarios/admin/schools.rb
- spec/cypress/integration/admin/SchoolManagment.feature
https://dfedigital.atlassian.net/browse/CPDRP-452
the nhs responsive table is real nice so i added it to our codebase (after switching all the helpers to `govuk-` ones)
It didn't seem to actually add any styling which is ideal - the NHS design system seems to just style all `table` elements. That's why the elements have both `govuk-` and `nhsuk-` classes :)
> Make school tables responsive using NHS responsive table component

- config/environments/deployed_development.rb
e.g. `[1m[36mTRANSACTION (1.2ms)[0m  [1m[31mROLLBACK[0m`
> remove colour codes from debug logs

- app/forms/schools/add_participant_form.rb
- app/models/early_career_teacher_profile.rb
- app/models/participant_declaration.rb
- app/services/early_career_teachers/create.rb
- spec/services/early_career_teachers/create_spec.rb
Track and Pay require flags against the Early Career Teacher Profiles to ensure that we are picking up the participants
to whom uplift is required. The decision about the flags boils down to the fact that we don't care if the underlying information changes, we just care if it was applicable at the point of the registration.
This is to ensure that when a new registration happens, we set those flags against the early career teacher.
Add code to pick up the current uplift flags from sparsity and pupil premium and set them in the early career teacher profile.
Would rather have this in a service or other separated section, but there's been some work on building a multistep form that I don't want to refactor at the moment to make this more separated, so it's a callback for now.
New …
> CDPTP-195 Set payment uplift flags on new EarlyCareerTeacherProfile records

- app/controllers/api/v1/users_controller.rb
- spec/requests/api/v1/users_spec.rb
- ECF does not allow users to have duplicate emails (for obvious reasons)
- NPQ registration can create user accounts, however it is possible for a user to already exist in ECF with this same email address
- NPQ registration should check if such an account exist and use that if it exists otherwise create the account
- Allow the endpoint `/api/v1/users` to support filtering by email
- Should not negatively impact the existing endpoint for other integrations
- create an api token with `NpqRegistrationApiToken.create_with_random_token!`
- note down the token
- create a new user via command line or find an existing user and note down the email
```
curl -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer TOKEN" …
```
> /api/v1/users endpoint now supports email filter

- db/migrate/20210618160328_backfill_profile_uplift_data.rb
Registrations have already been collected in production so we need to backfill the data that was not already captured in the new field.
Part of a bigger story to process uplift information for payments. https://dfedigital.atlassian.net/browse/CPDTP-195
Add migration to backfill ECT profile uplift data
```
testing the migration:
bundle exec rails console
s1 = School.with_pupil_premium_uplift(2021).first # from existing seed data
e1 = EarlyCareerTeacherProfile.create!(school: s1, user: User.first, cohort: Cohort.first)
e1.id # make a note of the new id
l = LocalAuthorityDistrict.create!
d = DistrictSparsity.create!(start_year: 2021, local_authority_district: l)
l.sparse? # returns true
s2 = School.create!(urn:"4321321", name:"sparse migrate test school", address_line1:"x",postcode:"sw1a …
```
> CPDTP-195 Add migration to backfill ECT profile uplift data

- terraform/monitoring/config/slack.tmpl
.CommonLabels was not defined within the .Alerts range
I really hope this is the last one... Ran a terraform apply locally in develop on this one and it works, so that's good
> Fix issue with slack template for alert manager

- app/components/school_recruited_transition_component.rb
- app/jobs/partnership_activation_job.rb
- spec/components/school_recruited_transition_component_spec.rb
- spec/cypress/app_commands/scenarios/school_opted_out_but_was_recruited.rb
- spec/cypress/integration/schools/SeeChallengeBanners.feature
- spec/jobs/partnership_activation_job_spec.rb
[Jira](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-443)
Show notification banners to schools that have chosen to opt-out (diy or no ECTs) if they have been recruited by a provider
Change  condition under which the `SchoolRecruitedTransitionComponent` decides whether to render or not
Change `PartnershipActivationJob` to clear the `opt_out_of_updates` flag on `SchoolCohort`
Given a school that has chosen either the DIY or no ECTs programme choice for the current cohort:
1. create a partnership for the current cohort
2. Observe that during the challenge window, when you visit the schools dashboard and select the opted out cohort you should see the banner warning the school of the recruitment and providing the ability to challenge it.
> CPDRP-443 notification banners for opted-out schools

- spec/requests/admin/participants_request_spec.rb
Because #587 really shouldn't have broken any tests
> Escape special characters to fix flakey test

- app/validators/notify_email_validator.rb
- spec/validators/notify_email_validator_spec.rb
Sentry has caught errors caused by people entering emails ending with a
dot
> Ensure email does not end with a dot

- app/models/npq_profile.rb
- app/resources/api/v1/npq_profile_resource.rb
- db/migrate/20210625143352_add_funding_fields_to_npq_profile.rb
- db/schema.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- NPQ registration collects funding data as part of the process
- We collect whether we think they are eligible for funding based off their course and school
- If they are not eligible we ask them how they intend to fund their course
- npq profile api endpoints supports `eligible_for_funding` and `funding_choice` along with migrations to add these fields
- Should not affect other api endpoints
- create an api token with `NpqRegistrationApiToken.create_with_random_token!`
- note down the token
- create a user with
```
curl -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer TOKEN" -X POST -d '{ "data": { "type": "user", "attributes": { "full_name": "John Doe", "email": "john.doe@example.com" } } }' …
```
> store funding data for npq profiles

- spec/cypress/app_commands/scenarios/admin/school_participants.rb
- spec/cypress/app_commands/scenarios/admin/suppliers.rb
- spec/cypress/app_commands/scenarios/challenge_partnership.rb
- spec/cypress/app_commands/scenarios/cip_cohort_with_school.rb
- spec/cypress/app_commands/scenarios/confirm_cip.rb
- spec/cypress/app_commands/scenarios/school_opted_out_but_was_recruited.rb
- spec/cypress/app_commands/scenarios/school_participants.rb
- Remove random data from visual tests
- Fix duplicate cohort error
I have no idea why the cohort was sometimes a duplicate, everything is supposed to be truncated before every test.
> Cypress fixes

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- lib/tasks/schools.rake
- spec/services/invite_schools_spec.rb
CPDRP-536
Add some code so we can send an email with a nomination link to federation schools
Much the same at the task to send emails to MATs, except for different email copy
> CPDRP-536: Add task to send email to federation schools

- db/seeds/sandbox_data.rb
You can't currently submit a declaration against mentor user ids so this was a pit of failure... into which I fell.
* Don't output mentor ids in sandbox seed output.
:ship:
* rails db:reset
* See new output with less ids
* Optionally submit one of the ids to the declaration endpoint, but note there's another bug blocking this being fixed in #596
> CPDTP-204 Don't output mentor ids in sandbox seed output

- app/controllers/api/v1/participant_declarations_controller.rb
- app/services/record_participant_event.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/provider_events_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_spec.json
This patch allows providers to (at a later time) reference declarations they have created by returning to them the id of the newly created declaration record.
This may be needed to allow them to "void" declarations when they realise there has been a mistake (to be confirmed).
Currently based on branch for #596
* Refactor params validation
* Return id of newly created declaration in API
Have a look at the updated swagger, and try it out.
Here is a successful request with `id` returned:
* run db:reset to get seed ids (watch out for just-merged #597 that isn't in this branch yet)
* use swagger to post real declarations
* see declaration id now in returned json
https://ecf-review-pr-601.london.cloudapps.digital/api-docs/index.html
> CPDTP-204 Return `id` of newly created declaration in API

- app/views/layouts/_application.html.erb
- app/webpacker/packs/sentry.js
- package.json
- yarn.lock
https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?selectedIssue=CPDRP-487
The above bug was (most likely) caused by the double form submission, which somehow got around our JS shields. I **guess** this could be caused by some JS error we don't know about, so this PR introduces client-side Sentry error collecting. Let's hope we won't be flooded with errors...
> Added Javascript sentry

- Gemfile
- Gemfile.lock
- app/controllers/csp_reports_controller.rb
- config/initializers/rack_attack.rb
- config/initializers/secure_headers.rb
- config/routes.rb
- spec/cypress/integration/Sandbox.feature
- spec/cypress/support/step_definitions/misc.js
- spec/requests/csp_reports_spec.rb
- spec/support/shared_examples/rate_limiting_support.rb
The previous version of the Content Security Policy blocked the API docs and didn't report correctly. 
This change adds a very permissive CSP policy backed by a restrictive "report only" policy. It also addresses the lack of screen shots on the API Docs that would have identified the blocked content.
- Cypress tests for sandbox modified
- csp_report_controller_spec checks logging for expected logs
The developer console will need to be up. As you browse the website you should see no CSP report errors displayed or the only ones you find should be labeled "report only".
> Content security policy

- app/forms/schools/add_participant_form.rb
- app/services/mentors/create.rb
- app/services/school_cohort_delegator.rb
- db/migrate/20210630000100_add_uplift_to_mentor_profile.rb
- db/migrate/20210630000110_backfill_mentor_profile_uplift_data.rb
- db/schema.rb
- spec/services/mentors/create_spec.rb
As part of the uplift piece for payment, the sparsity uplift and pupil premium uplift flags were added to the `EarlyCareerTeacherProfile`. This adds in the corresponding flags to the `MentorProfile` and carries on the form
refactoring that was done in the earlier piece.
- Add in the new flags and flag creation to the Form
- Extract MentorProfile Creation into a separate Mentors::Create service and remove duplication from this and EarlyCareerTeachers::Create by pulling the common School/Cohort code into a shared module.
- Add in tests for MentorProfile creation in line with those added for EarlyCareerTeacherProfile creation
Functional changes are only that the uplift flags will be populated and are backfilled.
Everything else is a refactor.
New tests added to test the population of the …
> CPDTP-224 Refactor MentorProfile creation form and add uplift

- app/views/dashboard/_navigation.html.erb
Reported by Al, the Schools link in primary nav on the dashboard goes to the wrong place
> Correct LP dashboard nav link

- app/models/npq_profile.rb
- spec/models/npq_profile_spec.rb
We're adding an additional option on the registration that we'd like ECF to ingest. This PR adds another headship status to `ECFProfile`.
Registration page:
> Expand valid NPQ profile headteacher statuses

- app/models/api_token.rb
- db/seeds/initial_seed.rb
- db/seeds/sandbox_data.rb
* Stable API tokens in seeds for development
* Remove output from sandbox seeds file, the providers already have their sandbox tokens so this is no longer needed.
Currently working on https://dfedigital.atlassian.net/browse/CPDTP-232 "Seed API sandbox environment with mentor data"
I wanted to remove the token generation from the sandbox seeds as that has already served its one-time purpose of making tokens for providers to test with and it was getting in the way of the current task.
We have been using that output for local development testing, so in order to continue to facilitate that use of the tokens I've moved it to a more permanent home in the initial_seeds file and made them stable for convenience.
Are we happy with well known tokens in the code? I *think* it's a good trade-off of …
> Stable API tokens in seeds for development

- app/models/participant_profile.rb
- db/migrate/20210629103240_create_participant_profiles.rb
- db/schema.rb
This PR is the first of series of PRs for refactoring current `EarlyCareerTeacherProfile` and `MentorProfile` into a single STI `ParticipantProfile` model.
At the moment, everywhere in the code `@participant` is always an instance of `User` and `Participant` simply does not exist. We have ParticipantPolicy, which takes an instance of user, we have ParticipantsController (in school and admin namespaces) which both loads Users using participant-related scopes on User class. We have a lot of code like `@participant.is_mentor? ? @participant.mentor_profile : @participant.early_career_profile` and we're passing an instance of user from method to method and searching for the relevant profiles. This feels like a missed Polymorphism opportunity which we'll bring back here.
This PR simply creates …
> Created shadow ParticipantProfile model

- app/models/profile_declaration.rb
- db/migrate/20210701000300_remove_lead_provider_from_profile_declarations.rb
- db/schema.rb
There was a thought to use the lead_provider/declarable_id as an
index, but it's a premature thought for now. With the principle
of YAGNI, we will add it back if and when we need it.
Remove lead_provider from profile_declarations
> CDPTP-224 Remove lead_provider from profile_declarations

- config/initializers/secure_headers.rb
Seeing lots of reports for CSP violations relating to Sentry
> Add sentry to connect_src for CSP headers

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
To get ready for automated validation against DQT, we need to return more information when checking participants.
Change the participant validation service to return correct TRN, QTS status, and active flag status of a participant
> Update participant validation service

- app/controllers/schools/participants_controller.rb
- app/policies/participant_policy.rb
- app/views/schools/participants/edit_email.html.erb
- app/views/schools/participants/edit_name.html.erb
- app/views/schools/participants/email_used.html.erb
- app/views/schools/participants/show.html.erb
- config/routes.rb
- spec/cypress/integration/schools/ManageParticipants.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/requests/schools/participants_request_spec.rb
CPDRP-548
Let induction tutors edit name and email address of participants.
Blocked on content design
Ideas for how to make the whole email validation thing less messy appreciated.
Will conflict with Stan's work
Sign in as school-leader@example.com and edit some details
> CPDRP-548: Induction tutors change participant details

- app/models/early_career_teacher_profile.rb
- app/models/mentor_profile.rb
- app/models/participant_profile.rb
- db/schema.rb
- spec/cypress/app_commands/scenarios/no_mentors_for_participants.rb
- spec/cypress/integration/schools/AddParticipants.feature
- spec/cypress/support/on-rails.js
- spec/factories/cohorts.rb
- spec/factories/early_career_teacher_profiles.rb
- spec/factories/mentor_profiles.rb
- spec/factories/users.rb
- spec/requests/api/v1/particpants_spec.rb
- spec/requests/api/v1/users_spec.rb
- spec/serializers/participant_serializer_spec.rb
Another PR for ParticipantProfile migration / refactor.
This will ensure that any new changes to MentorProfile and EarlyCareerTeacherProfile will be automatically propagated to ParticipantProfile. 
Once merged, we could quickly populate ParticipantProfiles with:
```ruby
MentorProfile.all.find_each do |profile|
profile.send :save_participant_profile
end
EarlyCareerTeacherProfile.all.find_each do |profile|
profile.send :save_participant_profile
end
```
> Making ParticipantProfile to shadow legacy profile models

- db/schema.rb
- lib/tasks/data.rake
Second step of migrating legacy MentorProfile and EarlyCareerTeacherProfile into STI ParticipantProfile model.
Previous step created the model and made it shadow the legacy profile records via after_save hook. This PR, once merged, will populate the ParticipantProfile table with the existing data in legacy profiles.
Once data is fully migrated we can then refactor the code to use new model in place of legacy profiles.
> Populating the shadow ParticipantProfile table with data from legacy profiles

- app/views/schools/participants/index.html.erb
- spec/cypress/app_commands/scenarios/school_participants.rb
- spec/cypress/integration/schools/ManageParticipants.feature
- spec/cypress/support/step_definitions/common-navigation.js
CPDRP-557
Add a column to the SIT participant listing page. This displays the mentor for ECTs, and an "assign" link when one has not been assigned
Just a link to existing pages, so just added a cypress test
Sign in as school-leader@example.com
> CPDRP-557: Add mentor column to SIT participant listing

- db/migrate/20210705094926_add_mentor_fk_to_participant_profiles.rb
- db/migrate/20210705095448_validate_mentor_fk_to_participant_profiles.rb
- db/schema.rb
WE have currently migrated all the data into a new ParticipantProfile model from legacy EarlyCareerTeacherProfile and MentorProfile. The new model is kept in sync with the legacy ones via after_save hook, so we can be certain the data in new model is now fully consistent.
This PR enforces consistency by adding a missing self-referencing FK key to the new model.
> Added foreign key to mentor_profile_id on participant_profiles

- app/views/schools/core_programme/materials/show.html.erb
Spotted by Al: https://ukgovernmentdfe.slack.com/archives/C01J1J4FM50/p1624614773274600
Should be:
Was:
> Copy update

- app/controllers/api/v1/participant_validation_controller.rb
- app/serializers/participant_validation_serializer.rb
- config/routes.rb
- spec/requests/api/v1/particpant_validation_spec.rb
- NPQ registration needs to verify TRNs of applicants
- Currently this is done with the `/api/v1/dqt-records` endpoint
- A constraint of the current implementation of this endpoint means the TRNs must match in order for participant to be valid
- With the recent addition of `ParticipantValidationService` we can now wrap this service in an api endpoint
- These means it is now possible to verify participants even if the TRN they entered is incorrect but all other pieces of information are correct
- added `/api/v1/participant-validation` api endpoint which wraps `ParticipantValidationService`
- If everything goes smoothly and nothing else is using `/api/v1/dqt-records`, It can be teared down in a later change
- create an api token with …
> add /api/v1/participant-validation endpoint

- app/controllers/users/sessions_controller.rb
- spec/requests/users/sessions_spec.rb
Draft pending confirmation on applicable domains.
- Expand mock login to cover all non-production environments, including sandbox.
- Set whitelist of email domains to apply mock login to
- Can you log in with an email address with an applicable domain without using the magic-link process?
> Skip magic link auth for certain domains on non-production environments

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
- I have seen NI numbers in prod API return NI numbers that are mixed cased
- To better out matching this makes NI matching case insensitive
- nil guard is present incase api data is not provided
- Test on review app
- Test data seems to be upcased correctly so enter downcased data to verify case insensitivity
- ssh into review app
- fire up rails console
- see csv test data to create a test case
- `ParticipantValidationService.validate(trn: "CORRECT_TRN", full_name: "CORRECT_NAME", date_of_birth: WRONG_DATE, nino: "INCORRECTLY_CASED_NINO")`
- should return correct record
> DQT NI number data may be cased incorrectly

- lib/dqt/client.rb
We're seeing a few failures, track the received status code to better
understand them
> Track DQT response code in exceptions

- app/controllers/api/school_search_controller.rb
- app/decorators/school_decorator.rb
- app/forms/nomination_request_form.rb
- app/models/concerns/participant_record_state_machine.rb
- app/models/participation_record.rb
- config/application.rb
- config/initializers/inflections.rb
- spec/controllers/api/api_controller_spec.rb
- spec/decorators/school_decorator_spec.rb
- spec/serializers/school_serializer_spec.rb
For historical reasons, we have been using the "classic" autoloader. This PR switches it for :zeitwerk
- change application autoloader to :zeitwerk
- Removed "Concerns" from namespace
- Added in inflector for UTM
- Removed spurious Api:: from the Dummy Api controller
Things should behave as before. Only naming changes have been applied.
All existing tests pass. Only changes are to namespaces and automatically found names in code where they were previously incorrect, but still being included.
> CPDTP-202 Switch from classic autoloader to zeitwerk

- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/sandbox_app_env.yml
> Remove FQDN from sandbox as it has not been setup

- lib/tasks/safe_reset.rake
There are multiple lead providers with the same name in the sandbox. After discussion we think it'll be expedient to reset the whole database and recreate the tokens rather than manually fixup the data.
* Allow reset of sandbox data
> CPDTP-304 Allow reset of sandbox data

- lib/tasks/sandbox_data.rake
We've recently had a change to the shape of the ParticipantProfiles. This rake task was still pointing to the old way.
Switch EarlyCareerTeacherProfile and MentorProfile for the newer ParticipantProfile::ECT and ParticipantProfile::Mentor
Self-contained rake task that generates pseudo random participant data for each lead provider.
> Switch the sandbox_data seeding to use the new structure

- app/models/cpd_lead_provider.rb
- app/models/lead_provider.rb
- app/models/npq_lead_provider.rb
- db/migrate/20210707115324_create_cpd_lead_providers.rb
- db/migrate/20210707120216_populate_cpd_lead_providers.rb
- db/migrate/20210707123715_columns_for_lps_and_cpd_lps.rb
- db/migrate/20210707151757_populate_lp_and_cpd_lp_assocs.rb
- db/schema.rb
- spec/models/cpd_lead_provider_spec.rb
- spec/models/lead_provider_spec.rb
- spec/models/npq_lead_provider_spec.rb
- Currently there is `LeadProvider` (which are ECF specific providers) and `NpqLeadProvider` and there is some overlap between the 2 entities
- We want a way of unifying this so a provider is capable of accessing multiple APIs with a single token
- Whilst at the same time keeping the data modelling sane
- Introduce `CpdLeadProvider` which encompasses all lead providers
- These can then be associated to `LeadProvider` and `NpqLeadProvider`
- Populate `CpdLeadProvider` and the data between the different tables
- A future change will follow to make the association between `LeadProvider` + `CpdLeadProvider` or `NpqLeadProvider` + `CpdLeadProvider` mandatory. It is only optional here due to missing data
- Another future change is that api token are currently associated with `LeadProvider` this …
> introduce CpdLeadProvider

- app/models/participant_profile.rb
- db/migrate/20210708125502_add_status_to_participant_profiles.rb
- db/schema.rb
- spec/models/participant_profile_spec.rb
CPDRP-585
This is the first in a series of PRs which will allow admins to delete participants, and make that information available to LPs in the API
Add status enum to participant profiles, defaulting to active
Added unit test for enum
> CPDRP-585: Add a status enum to participant profiles

- lib/tasks/data.rake
- spec/cypress/support/axe.js
- spec/factories/npq_profiles.rb
ParticipantProfile::NPQ is now shadowing the NPQProfile. This PR introduced a rake task to migrate the create the remaining ParticipantProfile::NPQ.
> Populating missing ParticipantProfile::NPQ records

- app/services/create_induction_tutor.rb
- spec/services/create_induction_tutor_spec.rb
CPDRP-578
Previously, changing induction coordinator would not work if that user
was also a mentor. If they managed more than one school, changing any of
those schools would delete the user altogether. This change:
- Makes it possible to change induction coordinator but leave the
mentor unchanged
- Makes it possible to change induction coordinator for a school
without removing the old coordinator from any other schools
- Sign in as school-leader@example.com
- Add yourself as a mentor
- Sign in as admin@example.com
- Change induction tutor for school with urn 999999
- ensure school-leader@example.com still shows in list of participants for school
- sign in as admin@example.com
- add school-leader@example.com as induction tutor to another school
- Change induction tutor for school urn …
> CPDRP-578: Fix change induction coordinator logic

- terraform/workspace-variables/production.tfvars
Do not merge until the upgrade has taken place.
To check this, target the production space and run `cf service ecf-postgres-production`. The plan should be `small-ha-11`
> Change production db to high availability

- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v1/participants_controller.rb
- app/models/lead_provider_api_token.rb
- db/migrate/20210708091337_add_cpd_lead_provider_to_tokens.rb
- db/migrate/20210708091338_move_lp_tokens.rb
- db/schema.rb
- db/seeds/initial_seed.rb
- spec/docs/participant_declarations_spec.rb
- spec/docs/participants_spec.rb
- spec/factories/cpd_lead_provider.rb
- spec/requests/api/v1/particpants_spec.rb
- spec/requests/api/v1/provider_events_spec.rb
- ECF and NPQ have different and overlapping providers
- We want providers to be able to access our apis with a single api token
- Make existing `LeadProviderApiToken` be associated with `CpdLeadProvider` which contains all providers we deal with
- Existing api endpoints continue to work by associating with `LeadProvider` thru `CpdLeadProvider`
- Updated seeds to ensure seed setup continues to work
- Once this is deployed we can remove `LeadProviderApiToken#lead_provider`
- We will also be able to mark `belongs_to` associations are required since all data migrations should be complete
- This should also allows to introduce NPQ related api endpoints that can now be accessed by providers via the updated tokening system
- Should be able to access existing api endpoints with existing tokens
- …
> LeadProviderApiToken now hangs off CpdLeadProvider

- app/models/user.rb
- spec/models/user_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-556)
Remove whitespace around `full_name` attribute. Also noticed it would be helpful to do this for `email` to prevent validation kicking in if there was just leading/trailing whitespace when a user entered the email.
Add `before_validation` hook to `User` to strip leading and trailing whitespace from `full_name` and `email`
There are 1146 users with trailing whitespace and 22 with leading whitespace in production. We can easily identify and clean those up from the console once this is deployed with something like this:
```ruby
User.where("full_name like '% ' or full_name like ' %'").each(&:save)
```
> CPDRP-556 Remove whitespace before validation on User model

- app/mailers/school_mailer.rb
- app/models/nomination_email.rb
- app/models/school.rb
- app/services/invite_schools.rb
- app/services/partnership_notification_service.rb
- app/services/utm_service.rb
- spec/mailers/school_mailer_spec.rb
- spec/models/school_spec.rb
- spec/services/invite_schools_spec.rb
- spec/services/partnership_notification_service_spec.rb
Add and update a series of targeted mailshots.
I haven't added rake tasks for these because they're going to be scheduled (console, `InviteSchools.new.delay(run_at: sometime, queue: "mailers", priority: 1).send_induction_coordinator_choose_route_chasers`)
> CPDRP-575: Add chaser emails

- terraform/monitoring/config/production/alert.rules.yml
Retain alerts in dev/stag at lower level to catch issues before live
> Don't alert on 4xx in production

- spec/lib/payment_calculator/ecf/contract/output_payment_calculations_spec.rb
- spec/lib/payment_calculator/ecf/contract/service_fee_calculations_spec.rb
- spec/lib/payment_calculator/ecf/contract/uplift_payment_calculations_spec.rb
- spec/lib/payment_calculator/ecf/payment_calculation_spec.rb
- spec/lib/payment_calculator/turnip_steps/ecf/call_off_contract_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/service_fees_steps.rb
- spec/lib/payment_calculator/turnip_steps/ecf/uplift_payment_steps.rb
These commits fell out of the work I'm doing to convert the turnip specs to plain rspec.
https://dfedigital.atlassian.net/browse/CPDTP-302
* Remove rounding from `output_payment_calculations_spec`
* Use `build_stubbed` in payment specs (much faster)
* Aggregate failures in `service_fee_calculations_spec`
* Refactor tests - rename `DummyClass` to `ModuleTestHarness`
Have a look at the individual commits.
> Payments-spec cleanup patches

- app/models/npq_validation_data.rb
- app/models/participant_profile/npq.rb
- app/models/user.rb
- app/resources/api/v1/npq_profile_resource.rb
- spec/factories/npq_validation_data.rb
- spec/models/npq_validation_data_spec.rb
- spec/requests/api/v1/npq_profiles_spec.rb
Unlike previous MentorProfile and EarlyCareerTeacherProfile, NPQProfile contains a lot of data that is specific only to NPQ participants. Additionally, it is already exposed via API which is being used by `npq_register`.
Because of this, I have renamed the `NPQProfile` model to `NPQValidationData` and associated it with the `ParticipantProfile::NPQ` model. To avoid any API changes, I have kept the logic which automatically creates ParticpantProfile::NPQ when NPQValidationData is created via API (which we can tackle later on).
> Renamed NPQProfile to NPQValidationData

- app/services/partnership_notification_service.rb
- spec/services/partnership_notification_service_spec.rb
Also call the correct method in the test, which would have caught this
> BUGFIX: fix partnership reminder emails

- db/migrate/20210707120216_populate_cpd_lead_providers.rb
- db/migrate/20210707151757_populate_lp_and_cpd_lp_assocs.rb
- Cached classes in migration seem to be causing problems
- Use throwaway classes in migrations
- none
- Drop database and recreate empty db
- Run the migrations
- Probably can't
> change migrations to use throwaway classes

- app/forms/challenge_partnership_form.rb
- spec/forms/challenge_partnership_form_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-527)
If a school challenges a partnership with the reason that they have no ECTs, then set that school's programme choice to `no_early_career_teachers` and opt them out of updates.
Add logic to update the `SchoolCohort` with the `no_early_career_teachers` programme choice and set `opt_out_of_updates = true` to ensure the school isn't sent unnecessary comms for the cohort.
Challenging a partnership with the reason "We do not have any early career teachers this year" should result in the programme choice being changed to "No early career teachers for this cohort" (visible in the __Manage your training__ page)
> CPDRP-527 Opt out schools that report partnership as no ECTs

- spec/cypress/app_commands/scenarios/admin/school_participants.rb
`created_at` is displayed on the admin participant page, so it needs to be hardcoded in the test scenario to avoid percy failures.
> Hardcoded created_at for admin participant cypress test

- app/presenters/api_docs/schema_example.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/BadOrMissingParametersResponse.yml
- swagger/v1/component_schemas/ECFParticipantRetainedDeclaration.yml
- swagger/v1/component_schemas/ECFParticipantStartedDeclaration.yml
- swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml
- swagger/v1/component_schemas/NPQParticipantStartedDeclaration.yml
- swagger/v1/component_schemas/ParticipantDeclaration.yml
A decision was made to have "course_type" for ecf and npq provider declarations and also "evidence_held" for "retained-1..retained-4" declarations.
Update to have 4 schemas to compare the declaration against:
- course types for ecf
- course types for npq
- extra required field for evidence_held for each of the ecf "retained" declarations.
- extra required field for evidence_held for each of the npq "retained" declarations.
Note that due to the schema requirement for "oneOf" this couldn't just be two with nested attributes, since that isn't a supported structure.
> CPDTP-227 Update Matt's initial PR to support v0.3 declaration specs.

- app/services/invite_schools.rb
Add ability to delay the sending of Induction Tutor chaser email
> Add ability for delay when queuing induction tutor chaser email

- app/serializers/participant_serializer.rb
- lib/tasks/sandbox_data.rake
- spec/docs/participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/MultipleParticipantCsvResponse.yml
- swagger/v1/component_schemas/MultipleParticipantResponse.yml
- swagger/v1/component_schemas/ParticipantAttributes.yml
- swagger/v1/component_schemas/ParticipantCsvRow.yml
CPDRP-585
Lead providers need to know when a participant is withdrawn/deleted/whatever. We tell them via a status field in the API.
Remove some other fields from withdrawn participants that don't make sense/we shouldn't share (e.g. email)
> CPDRP-585: Show status in participant api

- app/controllers/api/v1/npq_applications_controller.rb
- app/controllers/concerns/api_pagination.rb
- app/controllers/concerns/api_token_authenticatable.rb
- app/models/npq_lead_provider.rb
- app/serializers/npq_application_csv_serializer.rb
- app/serializers/npq_application_serializer.rb
- config/routes.rb
- spec/docs/npq_applications_spec.rb
- spec/factories/npq_validation_data.rb
- spec/requests/api/v1/npq_applications_spec.rb
- swagger/v1/api_spec.json
- Providers need to be able to fetch NPQ applications from us
- Add `/api/v1/npq-applications` endpoint
- Can fetch json and csv responses
- Added swagger docs for this new endpoints so providers can see how to use it
- JSON endpoint accepts pagination and the CSV endpoint does not. This is by design to mirror the participants endpoint for consistency
- I've implemented the filter `updated_since` to also mirror the partcipants endpoint for consistency
- I have opted to not use `JSONAPI::Resources` although powerful it seems to lack flexibility and extensibility
- This feature is behind a feature flag so it can be made available in sandbox whilst disabled in production
- Create or use an existing `LeadProviderApiToken`
- Ensure there exists some data to fetch from the …
> NPQ applications api

- spec/lib/lead_provider_api_specification_spec.rb
- Merge of #680 caused a test failure due to merge ordering
- Add missing LP api paths to test
- None
- Test suite should pass
- Not possible
> add missing LP api paths to test

- app/resources/api/v1/npq_profile_resource.rb
- db/migrate/20210715085835_add_ni_number_to_npq_profiles.rb
- db/schema.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- For NPQ in order to better validate TRNs we need to store NI numbers against the application until they can be validated 
- Allow NPQ endpoint to store NI number against the registration
- none
- Create or use existing npq api token
- Ensure user exists
- Create profile with NI number
```sh
curl -X POST -H "Authorization: Bearer TOKEN" -H "Content-Type: application/vnd.api+json" "https://ecf-review-pr-699.london.cloudapps.digital/api/v1/npq-profiles" -d '{"data":{"type":"npq_profiles","attributes":{"teacher_reference_number":"1234567","teacher_reference_number_verified":true,"date_of_birth":"1990-12-13","school_urn":"123456","headteacher_status":"no", "national_insurance_number":"AA111111A"},"relationships":{"user":{"data":{"type":"users","id":"USER_ID"}},"npq_lead_p …
```
> NPQ Profile can be created with NI number

- config/routes.rb
- spec/docs/npq_applications_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- Feature flag for NPQ applications api endpoint is no longer needed
- Delete feature flag around NPQ applications endpoint
- none
- Same as review app
- Disable feature flag `participant_data_api`
- API endpoint should continue to be available
> delete feature flag for NPQ applications api

- db/migrate/20210707151757_populate_lp_and_cpd_lp_assocs.rb
This would otherwise break because there's no association on the temporary model to translate it to the _id column.
> Fix LP association migration

- app/serializers/npq_application_serializer.rb
- db/migrate/20210716120023_add_identifier_to_npq_course.rb
- db/schema.rb
- db/seeds/initial_seed.rb
- spec/docs/npq_applications_spec.rb
- spec/factories/npq_courses.rb
- spec/factories/npq_validation_data.rb
- spec/requests/api/v1/npq_applications_spec.rb
- swagger/v1/api_spec.json
- We better improve data communication with provider and when providers callback with declaration use identifiers for NPQ courses instead of uuids
- Add human and machine readable identifiers for NPQ courses
- Use this in the NPQ applications API
- Providers can then use this identifier later as part of the declarations API to identify courses
- There will be a small break in the continuity of service for api users when the identifier data is missing in the sandbox environment. This will be updated by hand shortly afterwards which seems acceptable in my books 
- See review app instructions
- Add identifiers to courses
- Create some NPQ applications
- Hit the end endpoint
- Should get some responses with the newly added course identifiers
> change npq applications api use course identifers

- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- db/migrate/20210715091827_add_school_cohort_to_participant_profile.rb
- db/migrate/20210715091828_add_foreign_key_school_cohort_participant_profile.rb
- db/migrate/20210715091829_validate_foreign_key_school_cohort_participant_profile.rb
- db/schema.rb
https://dfedigital.atlassian.net/browse/CPDRP-545
Add optional school_cohort field to participant profiles. Shadow it on ECT and Mentor models. 
I will need to get it deployed, and run a script to populate the school_cohort. Something like `ParticipantProfile.ecf.each { |record| record.save }` should do the trick. And I should do it in every environment.
> Add school cohorts step 1: add the field and shadow it on the models

- app/serializers/npq_application_csv_serializer.rb
- spec/requests/api/v1/npq_applications_spec.rb
- We improve data communication with providers and when providers callback with declaration use identifiers for NPQ courses instead of uuids
- This change was applied to the JSON endpoint but the CSV one was forgotten
- In the NPQ application csv api endpoint we return course identifiers instead of course uuids and names
- Related to https://github.com/DFE-Digital/early-careers-framework/pull/710 however this applies the same change to the CSV api endpoint
- See review app instructions
- Add identifiers to courses
- Create some NPQ applications
- Hit the end CSV api endpoint
- Should get some responses with the newly added course identifiers
> return course_identifier in npq applications csv

- app/models/participant_declaration.rb
- lib/tasks/payment_breakdown.rake
- lib/tasks/payment_breakdown.rb
We were asked if our current rake task could be made to generate a csv file as a demonstrator. This updates the output and adds in the CSV headings and body to do so.
Change structure of Rake task to make it easier to maintain, by creating a small class which will perform calls into the calculator for those portions of the calculations that we need. Note that this may actually drive how the calculator works in the future, so is probably a good thing even if it's just used in the rake task.
Add in aggregation scopes for ECTs and mentors.
Change the large single table into smaller tables which are more like the proposed layout for Payment Breakdown in any case.
Add in CSV generation. This is almost certainly going to be temporary code, but does actually interrogate the database and pulls …
> CPDTP-324 Change rake task for payment breakdown to generate csv output

- app/controllers/users/sessions_controller.rb
- spec/requests/users/sessions_spec.rb
Resolves an exception seen on sandbox environment when entering in an unknown email address with a domain that is in the `TEST_DOMAINS` list into `/users/sign_in`.
https://sentry.io/organizations/dfe-bat/issues/2509940522/
Skip mock login for unknown email instead of raising
:ship:
> CPDTP-342 Skip mock login for unknown email instead of raising

- config/environments/sandbox.rb
- DQT has not been configured correctly in sandbox
- Pass needed config to dqt client in sandbox
- none
- n/a
- Not possible
> configure DQT in sandbox

- app/controllers/admin/schools/participants_controller.rb
- app/forms/schools/add_participant_form.rb
- app/models/participant_profile.rb
- app/models/user.rb
- app/policies/participant_policy.rb
- app/services/mentors/create.rb
- db/seeds/dummy_structures.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/models/user_spec.rb
- spec/policies/participant_policy_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-622)
If user has registered for NPQ this prevents the same user from being added as a ECT/mentor.
When checking if the email already exists, only check against users that are already ECTs and Mentors so we can add NPQ registrants.
A test user has been added with a `ParticipantProfile::NPQ` and email address `npq-registrant@example.com`
Sign-in as the `school-leader@example.com` user and attempt to add a participant with the same email address as the NPQ user and it should succeed.
Attempting to add any existing ECT or Mentor should fail.
> CPDRP-622 Prevent NPQ registration from blocking ECT/mentor registration

- app/models/user.rb
- spec/models/user_spec.rb
There are 120 users in the service with embedded tabs in their name. We currently strip leading/trailing whitespace from the user's name and email, if we use `squish!` instead of `strip!` then it will also handle these too.
Change `strip!` to `squish!` in the `before_validation` callback for the `User` model
> Replace strip with squish

- app/forms/nominate_induction_tutor_form.rb
- app/services/create_induction_tutor.rb
- spec/cypress/integration/nominations/NominateInductionCoordinator.feature
- spec/forms/nominate_induction_tutor_form_spec.rb
- spec/requests/admin/schools/induction_coordinators_spec.rb
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-637)
When nominating an induction tutor, allow an existing user who is an NPQ registrant
See also #703 
Change the email in use check to allow NPQ registrants.
> CPDRP-637 Change email check to allow NPQ registrants

- app/controllers/api/v1/participants_controller.rb
- spec/requests/api/v1/participants_spec.rb
- This fix is in response to https://sentry.io/organizations/dfe-bat/issues/2519946117/?environment=sandbox&project=5748989&query=is%3Aunresolved
- This prevents API tokens not associated to an ECF provider such as NPQ only lead providers from accessing the participants API
- Scope API token to only those with an (ECF) `LeadProvider` to be able to access the participants API
- Existing API access should not be broken and there should be continuity of service
- Create or use an existing `CpdLeadProvder` that has a `NPQLeadProvider` but not an (ECF) `LeadProvider`
- This will mimic a NPQ only lead provider
- Create a `LeadProviderApiToken` associated to this `CpdLeadProvider`
- Attempt to access the participants api endpoint
- Should receive a 403 and not an unexpected error
- Probably …
> Scope API tokens for access to participants API

- app/models/school.rb
- spec/models/school_spec.rb
We shouldn't see this when the partnership is challenged
> BUGFIX: don't show delivery partners for challenged partnerships

- spec/requests/users/sessions_spec.rb
Noticed this while working on adding a finance user type.
Correction to login spec name
This now matches some of the other tests and is less misleading
:ship:
> Correction to login spec name

- app/helpers/application_helper.rb
- app/models/finance_profile.rb
- app/models/user.rb
- app/services/create_finance_user.rb
- config/routes.rb
- db/migrate/20210722094019_create_finance_profiles.rb
- db/schema.rb
- db/seeds/dummy_structures.rb
- lib/tasks/create_finance_user.rake
- spec/factories/finance_profiles.rb
- spec/factories/users.rb
- spec/helpers/application_helper_spec.rb
- spec/models/user_spec.rb
- spec/requests/users/sessions_spec.rb
- spec/services/create_finance_user_spec.rb
These users are DfE internal users intended to be able to view payment information.
https://dfedigital.atlassian.net/browse/CPDTP-339
* Add a new finance user type and give them default URL that they will be redirected to on login
* Add a seed finance user
* Add a rake task for creating finance users (via a service class)
This patch is largely copied from the existing admin user code.
* Rather than testing the rake task with all the stdout redirection that involves, the logic for the rake task has been pushed into a service class and that is tested instead.
```bash
bundle exec rails users:finance:create["Marge Simpson",marge@example.com]
bundle exec rails console
> User.find_by(email: "marge@example.com").finance?
...
true
```
Sign in to https://ecf-review-pr-738.london.cloudapps.digital/ …
> CPDTP-339 Add a new finance user type and give them a default URL

- app/controllers/api/v1/participants_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users_spec.rb
https://sentry.io/organizations/dfe-bat/issues/2513895315/?project=5748989&referrer=RegressionActivityEmail
Apparently npqs on their own are fine, but combination of mentors and npqs in one user, uff, it breaks our scope :( 
Add setup to tests replicating the error. Fix the code so the tests pass.
Also reuse pagination for apis in the places which could use it.
> Fix mentor and npq serialisation

- app/forms/nominate_induction_tutor_form.rb
- spec/forms/nominate_induction_tutor_form_spec.rb
- spec/requests/admin/schools/induction_coordinators_spec.rb
- spec/requests/nominations/nominate_induction_coordinator_spec.rb
CPDRP-743
We allow induction coordinators to add themselves as mentors, this
change is to allow existing mentors to be nominated (by school) or
assigned (by admin) as an induction coordinator
relax constraint on users who can gain an induction_coordinator_profile to include mentors
> CPDRP-743: Allow an existing mentor to become a induction coordinator

- app/models/participant_declaration.rb
- app/models/participant_declaration/ecf.rb
- app/models/participant_declaration/npq.rb
- db/seeds/initial_seed.rb
- spec/factories/participant_declaration.rb
- spec/models/participant_declaration_spec.rb
- spec/models/profile_declaration_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/calculation_orchestrator_spec.rb
- spec/services/feature_flag_spec.rb
- spec/services/participant_event_aggregator_service_spec.rb
Now that this is using STI we can put in proper course type validations for NPQ and ECF courses.
Inclusion validations to make sure that the correct course identifier is used for each declaration type. For NPQ it reads from the NPQCourse identifiers held in the database, so that if more courses are added, we can validate against those without having to make code changes too.
Presence validation to ensure that the required fields are passed to the model.
Factories and tests updated to ensure that correct course_identifiers are linked to the correct profile types.
> CPDTP-329 Add in model validations for participant_declarations

- app/forms/delivery_partner_form.rb
Fixes issue #336
Breaks the coverage tests since a break inside a proc is an illegal instruction.
- Switching each to any? and dropping the break will stop after the first error is added, which was the intent.
errors.add returns the errors object, which is truthy, so will stop the loop and only add it once.
> Issue#336 Stop the cohorts_validation using break from within a validation proc

- app/controllers/finance/base_controller.rb
- app/controllers/finance/lead_providers_controller.rb
- app/policies/finance_profile_policy.rb
- app/views/finance/lead_providers/index.html.erb
- config/routes.rb
- spec/cypress/app_commands/scenarios/finance_lead_providers.rb
- spec/cypress/integration/finance/Finance.feature
- spec/helpers/application_helper_spec.rb
- spec/policies/finance_profile_policy_spec.rb
- spec/requests/finance/lead_providers_controller_spec.rb
Finance users should be able to land on a page showing list of providers, the follow up work will allow them to click on any of them and get price breakdown
https://dfedigital.atlassian.net/browse/CPDTP-348
Add index page for lead providers and ability for finance users to display them
Create finance user
Login to the web app
> CPDTP-348 Create lead provider index page for finance users

- app/controllers/api/v1/ecf_users_controller.rb
- config/routes.rb
- spec/requests/api/v1/ecf_users_spec.rb
- spec/requests/finance/lead_providers_controller_spec.rb
- `/api/v1/users` endpoint at the moment contains ECF specific implementation
- NPQ at the moment requires a generic endpoint regarding users without any scoping to any subset of users
- Duplicate the `/api/v1/users` endpoint at `/api/v1/ecf-users`
- Once deployed ECF can be pointed to `/api/v1/ecf-users`
- This will free then free up `/api/v1/users` where all ECF specific implementation can be removed to make it generic
- I feel long-term we want to deprecate the `/api/v1/ecf-users` endpoints. And opt for filtering to return users only ECF is concerned about. And use https://jsonapi.org/format/#fetching-relationships for fetching desired associations 
```sh
curl -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer PRIVATE_TOKEN" "http://localhost:3001/api/v1/ecf-users" …
```
> Dupe ECF users api

- spec/components/lead_providers/partnerships/challenged_banner_spec.rb
- spec/features/start_journey_spec.rb
- spec/rails_helper.rb
Enable writing feature specs in RSpec (task from dev retro).  I've added an example feature spec with the work-around to prevent rutabaga from trying to load `.feature` file
Once the rutabaga feature tests for the payments calculator are refactored and removed, we can remove the `rutabaga: false` param.
Add `require` for capybara dependencies.
Add example feature test.
Fix spec that was using `.and` which isn't supported with Capybara::RSpecMatchers.
> Enable capybara so we can write rspec feature tests

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
- We have people that failed auto validation. turns out these people were simply missing from the temporary database
- but my understanding was they were in the database but did not have the padded trn. ie the look up failed
- eg user entered `0123456` we look for that but don’t find it because its stored under 123456
- so the temporary api now pads the request to TRA so it always finds the record
- on top of that responses to us will now contain a padded TRN
- therefore any matching we do our end must also be on a padded TRN
- without this change users who have been padding their own TRN will get auto validated. but those entering 6 digit trns will start failing
- API response will now be padded with leading zeros till 7 character length
- therefore any matching our side will also need …
> TRA API will now send us padded TRNs

- app/models/lead_provider.rb
Issue #698
Add code-doc to help avoid further `LeadProvider` naming confusion
:ship:
> Add code-doc to help avoid further `LeadProvider` naming confusion

- app/controllers/schools/year2020_controller.rb
- app/forms/schools/year2020_form.rb
- app/services/feature_flag.rb
- app/views/schools/year2020/check.html.erb
- app/views/schools/year2020/new_teacher.html.erb
- app/views/schools/year2020/no_accredited_materials.html.erb
- app/views/schools/year2020/select_cip.erb
- app/views/schools/year2020/select_induction_programme.erb
- app/views/schools/year2020/start.erb
- app/views/schools/year2020/success.html.erb
- config/routes.rb
- db/seeds/initial_seed.rb
- spec/cypress/integration/schools/Year2020.feature
- spec/cypress/support/step_definitions/common-interaction.js
- spec/cypress/support/step_definitions/common-navigation.js
- spec/forms/schools/add_participant_form_spec.rb
- spec/forms/schools/year2020_form_spec.rb
- spec/requests/schools/year2020_spec.rb
https://dfedigital.atlassian.net/browse/CPDEL-726
Add a form, a controller and a bunch of views for 2020 data input. Hide them behind a new feature flag.
Multiple participants will come in a later PR. Entry points into the flow (almost certainly emails) will come in a later PR.
This replaces https://github.com/DFE-Digital/early-careers-framework/pull/729. You might notice it is not using the multipage form. That's because there are a bunch of edge cases that I know of already (such as opting out) and things we will do for the first time (managing multiple participants), which I think the multipage form is not really geared towards handling.
And I think for speed of iterative improvement it will be better to use a more flexible approach (arbitrary controller actions) - with an ambition to …
> 2020 cohort: Add the first actual version of the flow.

- lib/dqt/api/v1/dqt_record.rb
- spec/lib/dqt/api/v1/dqt_record_spec.rb
- It seems TRA can return records that do not have a record a `qtsAwardDate` with a value of `null`
- The current implementation does not support this as `Date.parse` cannot parse `nil`
- For `qtsAwardDate` return `nil` if value is `null`
- This will therefore no longer throw an error as we no longer call `Date.parse(nil)`
- The output api slightly differs so ensuring there are no knock-on effects
- You'd have to connect to the live instance as the test instance is not available
- Find a user with no qts award date
- calling something like `Dqt::Client.new.api.dqt_record.show(params: { teacher_reference_number: "TRN", national_insurance_number: "" })` should be sufficient to validate
- Not possible this moment in time as the TRA test instance is not currently available
> able to parse TRA record when qtsAwardDate is null

- app/models/partnership.rb
- app/models/school.rb
- app/models/school_cohort.rb
- spec/components/admin/participants/table_spec.rb
- spec/models/participant_profile_spec.rb
- spec/models/partnership_spec.rb
- spec/models/school_cohort_spec.rb
- spec/models/school_spec.rb
Currently for example, when a school forms a partnership and their participants become visible to an LP, that will not be reflected in the updated_since parameter for the participants API endpoint
> Touch User whenever a change is made that is relevant to the participants API

- .github/workflows/test.yml
This should speed up the test runs. We don't use them anyway
I tried to do this before, but only changed the local setting
> prevent screenshots and video on cypress tests

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/services/invite_schools_spec.rb
We will want to send schools an email about 2020 cohort. This should include a link - when they click it, they should go to the start of our flow.
Add a new email to school mailer, and another method to the service inviting schools.
Add some tests.
We want to send the email to:
> State-funded English schools. In essence, the exact same schools who are eligible for FIP.
(from slack message)
You can't.
> 2020 Invite email: Add invite email for 2020 Cohort

- app/controllers/api/v1/ecf_users_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/serializers/ecf_user_serializer.rb
- app/serializers/user_serializer.rb
- spec/requests/api/v1/users_spec.rb
- `/api/v1/users` used to return ECF specific users and this has been duplicated to `/api/v1/ecf-users`
- This endpoint is therefore free to deal with the concept of all users in CPD
- The use case for this change is so NPQ is able to query for existing users in the system based on email address
- `/api/v1/users` now returns all users
- this is no longer scoped to ECF specific users
- serialization is now generalised removing all ECF specific attributes
- Besides NPQ no other client that I am aware of is using this endpoint and therefore safe to change. Is this the case?
- There should be no changes to the endpoint `/api/v1/ecf-users`
- See testing on review app
- Create or use an existing token with private api access
- Create or use an existing non ECF user
- Search for them 
```sh
curl …
```
> /api/v1/users now returns all users

- app/models/participant_profile.rb
- app/models/user.rb
Oops! There's a bug in TeacheProfile shadowing code causing new teacher profiles not being associated with newly created participant profiles: `self.techer_profile = <new_instance_of_record>` does not set the foregin_key value and, for some reason `self.teacher_profile.save` did not update the foreign key...
> Fixed race condition in teacher profile shadowing

- lib/tasks/payment_breakdown.rake
The Rake task for payment breakdown was still using the old `lead_provider` -> aggregation + `lead_provider` -> calculator (contract) links. Since this has been updated to move the aggregation to the parent `cpd_lead_provider`, this rake task also needs to have the appropriate aggregator to `cpd_lead_provider` changes made.
The ECF Payment Calculation Rake task needs the `CpdLeadProvider` for aggregation and
the original `LeadProvider` for the ECF `call_off_contract`.
This updates the breakdown and csv generation to support the new format.
> Update the rake task for payment calcuation with new cpd_lead_provider

- Gemfile
- Gemfile.lock
- app/controllers/admin/base_controller.rb
- app/controllers/admin/impersonates_controller.rb
- app/controllers/application_controller.rb
- app/policies/impersonation_policy.rb
- app/views/admin/schools/show.html.erb
- app/views/layouts/_application.html.erb
- config/routes.rb
- spec/cypress/integration/admin/SchoolManagment.feature
- spec/cypress/support/step_definitions/common-interaction.js
- spec/policies/impersonation_policy_spec.rb
- spec/requests/admin/impersonates_spec.rb
- Allow admin users to impersonate induction coordinators
- I haven't placed any limitations on the impersonation side as to the type of user it can impersonate. That is, it will accept any user ID that is not the impersonator or another admin user. It should just work.
- The dependent gem is relatively straight forward but is well maintained and tested with devise.
> Allow admin users to impersonate induction coordinators

- app/controllers/schools/year2020_controller.rb
- app/forms/schools/year2020_form.rb
- app/views/schools/year2020/check.html.erb
- app/views/schools/year2020/edit_teacher.html.erb
- app/views/schools/year2020/remove_teacher.html.erb
- config/routes.rb
- spec/cypress/integration/schools/Year2020.feature
- spec/cypress/support/step_definitions/common-navigation.js
- spec/forms/schools/year2020_form_spec.rb
- spec/requests/schools/year2020_spec.rb
https://dfedigital.atlassian.net/browse/CPDEL-727
Add `participants` field to the 2020 form. That's where the data for all participants is stored.
Add pages and routes for edit/update, and remove/delete teachers.
Go to `/schools/999999-example-school/year-2020/start` and play around :)
> 2020 Multiple participants: Add adding, removing and updating participants

- app/components/admin/schools/cohorts/fip_info.html.erb
- app/controllers/admin/schools/cohorts/challenge_partnership_controller.rb
- app/controllers/challenge_partnerships_controller.rb
- app/forms/challenge_partnership_form.rb
- app/policies/partnership_policy.rb
- app/services/feature_flag.rb
- app/views/admin/schools/cohorts/challenge_partnership/confirm.html.erb
- app/views/admin/schools/cohorts/challenge_partnership/new.html.erb
- app/views/challenge_partnerships/show.html.erb
- config/routes.rb
- spec/cypress/integration/ChallengePartnership.feature
- spec/features/admin/schools/challenging_partnerships_spec.rb
- spec/features/admin/schools/changing_provision_spec.rb
- spec/features_helper.rb
- spec/forms/challenge_partnership_form_spec.rb
- spec/policies/partnership_policy_spec.rb
- spec/requests/admin/schools/cohorts/challenge_partnership_spec.rb
- spec/services/admin/change_induction_choice_service_spec.rb
- spec/services/partnerships/challenge_spec.rb
- spec/support/features/feature_flag_helper.rb
- spec/support/features/interaction_helper.rb
- spec/support/features/page_assertions_helper.rb
- spec/support/features/user_helper.rb
CPDRP-616 PR 2/3 
Give admins the ability to challenge a partnership on behalf of a school. There is no time limit on this at the moment, so we will need to revisit this once the declarations start coming in
> CPDRP-616: admin challenge partnership

- README.md
Put a plain English replacement for Z2H heading in readme
The readme should be in plain English as much as possible because there will be many people of varying skills and culture who wish to understand this repo and how to use it. It certainly threw me, I assumed it was a mistake.
It seems from the PR comments on PR #773 (take 1 of this) that Z2H is an acronym for Zero-to-Hero, which is a slang way of getting set up quickly.
> Rename Z2H heading in readme

- etc/schema/0.3/npq/participant_declarations/retained/create/request_schema.json
- swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml
NPQs only have retained-1 and retained-2, so the schema for swagger and validation needs to reflect this.
Drop the retained-3 and retained-4 from the schema docs.
> Correct the number of retained for npqs

- lib/tasks/sandbox_data.rake
Wasn't updated when the participant_profiles to ecf_participant_profiles change was made.
Switch from participant_profiles in the rake task to ecf_participant_profiles to ensure that seeding works.
> CDPTP-390 Fix sandbox data seed with new ecf_participant_profiles

- app/views/lead_providers/guidance/reference.html.erb
These links are currently 404ing. They should be the API paths for each environment.
> Fix API URLs on API usage guide

- app/components/admin/schools/cohorts/cip_info.html.erb
- app/controllers/admin/schools/cohorts/change_training_materials_controller.rb
- app/forms/core_induction_programme_choice_form.rb
- app/services/feature_flag.rb
- app/views/admin/schools/cohorts/change_training_materials/confirm.html.erb
- app/views/admin/schools/cohorts/change_training_materials/show.html.erb
- config/routes.rb
- spec/features/admin/schools/changing_training_materials_spec.rb
- spec/requests/admin/schools/cohorts/change_training_materials_spec.rb
CPDRP-616
PR 3/3
This completes the set of admin managing schools' provision functionality. Allow changing the CIP
Feature flagged until review
Request and feature specs
admin@example.com
> CPDRP-616: Allow admins to change CIP materials

- config/webpacker.yml
A change was introduced in bea7a4ad827179dfcd63d8811fb3a10fe2c60956 to add the new sandbox environment to webpacker. It pushed two config settings into the sandbox environment instead of the production environment.
This PR pushes the values back into the scope of production which is then inherited by the other non-test environments.
> Fix production compilation and performance webpacker settings

- app/models/participant_profile.rb
> Ignoring user_id on participant profiles

- .github/workflows/test.yml
Per documentation https://docs.percy.io/docs/parallel-test-suites#advanced-details the nonce should be
automatically provided by github actions. Fixing it to the run number
prevents re-running a failed test run
> Do not explicitly specify percy nonce to allow test re-runs

- app/controllers/api/v1/ecf_users_controller.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/ect.rb
- app/models/participant_profile/mentor.rb
- app/models/teacher_profile.rb
- app/serializers/ecf_user_serializer.rb
- spec/requests/api/v1/ecf_users_spec.rb
Preload associations to prevent around 200 additional queries per request
I've also fixed a slightly flaky test
> Fix n+1 query on ecf-users endpoint

- app/controllers/admin/schools/participants_controller.rb
- app/controllers/api/v1/participants_controller.rb
- app/forms/schools/add_participant_form.rb
- app/services/early_career_teachers/create.rb
- app/services/invite_schools.rb
- app/services/mentors/create.rb
- spec/factories/participant_profiles.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/requests/admin/schools/participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/services/early_career_teachers/create_spec.rb
- spec/services/invite_schools_spec.rb
- spec/services/mentors/create_spec.rb
CPDRP-701
Once participant profiles have been marked as withdrawn, we should allow new profiles to be created for those users
- Ensure withdrawn profiles are displayed correctly in the participants API
- Ensure withdrawn participants are not displayed to admins
- Allow withdrawn participants to be readded by SITs
- Update email chaser logic to account for withdrawn participants
- sign in as school-leader@example.com and add a participant
- sign in as admin@example.com and remove the particiapant
- sign back in as school-leader and add the same details again
Ensure they are displayed to the school tutor and the admin correctly
> Cpdrp 701 readd withdrawn participants

- app/controllers/api/v1/npq_applications_controller.rb
- app/models/npq_validation_data.rb
- app/serializers/npq_application_csv_serializer.rb
- app/serializers/npq_application_serializer.rb
- app/services/api/error_factory.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20210802145839_add_status_to_npq_validation_data.rb
- db/schema.rb
- spec/docs/npq_applications_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/MultipleNpqApplicationsCsvResponse.yml
- swagger/v1/component_schemas/MultipleNpqApplicationsResponse.yml
- swagger/v1/component_schemas/NpqApplication.yml
- swagger/v1/component_schemas/NpqApplicationAttributes.yml
- swagger/v1/component_schemas/NpqApplicationCsvRow.yml
- swagger/v1/component_schemas/NpqApplicationResponse.yml
- As part of the end of the NPQ lifecycle before we hit track and pay we need for providers to acknowledge NPQ applications
- NPQ applications start out in a starting state of `pending`
- Providers can then hit one of two endpoints to `accept` or `reject`
- This will then change the `status` to `accepted` or `rejected` respectively
- Once an application has been accepted or rejected it cannot change state
- The first provider to accept an application will cause all other NPQ applications on the user to become rejected
- Swagger docs have been added for these endpoints
- Also included some other swagger doc changes related to NPQ application that were not correctly documented
- Do we only allow this once? Can a provider accept then reject an application?
> NPQ API to accept/reject an application

- .github/workflows/test.yml
In an attempt to fix Percy, I broke it completely. Let's see what this attempt at fixing it does...
I got the github actions syntax for setting output variables wrong. This fixes it.
> Set the nonce correctly for percy

- spec/models/user_spec.rb
There are some older tests using `should` and `should_not` rather than the more modern `expect().to` and `expect().to_not`.
This commit replaces just those tests.
> Fix the deprecation warning for rspec

- Gemfile
- Gemfile.lock
- app/middlewares/time_traveler.rb
- config/application.rb
- config/environments/deployed_development.rb
- config/environments/development.rb
- config/environments/sandbox.rb
- spec/middlewares/time_traveler_spec.rb
There is a requirement for lead providers to be able to test declaration date validation in sandbox environment. They should be able to pass a date in the ```header X-With-Server-Date``` and the server will use it as current date. Future ticket will cover validations.
Middleware to use timecop to set date for the scope of a request
Set an additional header and check the server side date will be set to that date.
> CPDTP-371 Create header to more tightly control date validation for the non-production systems

- app/helpers/google_analytics_helper.rb
- app/views/layouts/_application.html.erb
https://dfedigital.atlassian.net/browse/CPDTP-406
We want to have a separate GA space for sandbox, so we can easily track which pages ths sandbox users are visiting. We don't want to throw it into the shared mix with review apps, etc., because it is accessed by real users (LPs for example).
Extract gtm_id computation into a helper
Add sandbox value to it.
You can't. Once it is merged I will deploy to staging, sandbox and production and make sure the gtm_id values match our expectations.
> Add sandbox google analytics

- app/services/record_declarations/retained.rb
- app/services/record_declarations/retained/early_career_teacher.rb
- app/services/record_declarations/retained/mentor.rb
- app/services/record_declarations/retained/npq.rb
- config/locales/en.yml
- etc/schema/0.3/npq/participant_declarations/retained/create/request.json
- etc/schema/0.3/npq/participant_declarations/retained/create/request_schema.json
- etc/schema/0.3/npq/participant_declarations/started/create/request_schema.json
- spec/services/record_declarations/retained/early_career_teacher_spec.rb
- spec/services/record_declarations/retained/mentor_spec.rb
- spec/services/record_declarations/retained/npq_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml
We missed that when we switched from json schema validator into rails validations.
Add validations for evidence type. Add tests to show how they work.
I also changed the schemas. One was the npq retained event, because we need it to match our actual validation.
The other was for ecf started event. I think we don't want or need them on that event.
Unit tests for the validations.
Try submitting a retained event with invalid evidence held, it should fail. Before it succeeded.
> Fix validation for event type

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/invite_schools_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-799)
Enable feature flags and email participants for private beta of participant validation
Mailers for ECTs and Mentors (FIP)
Add method to `InviteSchools` to activate `:participant_validation` feature flag for each school in a list of URNs provided by the caller and send the appropriate email to the school's recipients.
Add UTM campaigns for `participant-validation-beta` and `participant-validation-research`
> CPDRP-799 feature flags and emails for beta

- spec/services/record_declarations/started/early_career_teacher_spec.rb
Fix for the output warning in the rspec test:
```
......WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally 
any othererror would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, 
`NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. 
Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. 
This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`.
Called from 
/Users/plisovin/Development/early-careers-framework/spec/services/record_declarations/started/early_career_teacher_spec.rb:93:in
`block (3 levels) in <top (required)>'.
```
> Fix rspec test output warning

- app/controllers/participants/validations_controller.rb
Typo was causing error to be raised and not storing validation data under certain circumstances
> Fix typo in participant validation journey

- app/policies/school_policy.rb
- spec/requests/schools/participants_request_spec.rb
Every couple of runs I see rspec fail in continuous integration on a particular test.
I don't really know what was going on. I think perhaps school cohort with which the ECT profile was creating had some weirdly small chance to interfere with the other one we explicitly created in test. Perhaps when cohort start year was the same between the two, or something similar. But really, this fix is a result of running a lot of tests and trial and errors. 
Before the changes, this seemed to fail like once every 100 runs locally, although I think it was a lot more common in CI.
After changes I ran it couple thousand times and it works fine.
> Hopefully fix the frustrating "no mentors found" test once and for all

- spec/features/participants/participant_validation_steps.rb
- spec/features/participants/unhappy_validation_journeys_for_ect_fip_spec.rb
A typo fixed in #827 highlighted an area that was missed by the existing tests, this adds an additional test to cover that area.
> Quick fix part 2 - Extra test for area with rescue handling

- app/serializers/ecf_user_serializer.rb
- spec/requests/api/v1/ecf_users_spec.rb
E&L need to know the cohort start year for user. This is for analytics data and for future work to remove access for cohorts that should no longer need the service. 
Links to PR [230](https://github.com/DFE-Digital/ecf-engage-and-learn/pull/230) on E&L
Adding the cohort attribute to the ecf serializer
> Add cohort year to ecf user serializer

- spec/services/record_declarations/retained/early_career_teacher_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
One PR changed one thing, another changed another thing 😢 And so we catch it when we run tests on develop.
> Fix a silent merge conflict

- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantRetainedDeclaration.yml
Swagger schema needed an update for evidence_held for API request
Add in "other" enumeration to the ECF retained documentation and regenerate the api_spec.json
Spin up the review app and go to the api reference for the "ECFParticipantRetainedDeclaration" object. Other should be listed as a possible type.
> Add "other" into the evidence_held for ECF swagger document

- app/views/lead_providers/guidance/ecf_usage.html.erb
- app/views/lead_providers/guidance/index.html.erb
- app/views/lead_providers/guidance/npq_usage.html.erb
- spec/requests/lead_providers/ecf_usage_spec.rb
- spec/requests/lead_providers/npq_usage_spec.rb
Declarations have been updated for NPQ and ECF declarations. This brings the application up-to-date with the copy which has been updated to describe the usage of the API endpoint that corresponds to each declaration type.
Update documentation and tests
> CPDTP-382 Updated usage copy for ECF and NPQ declarations.

- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/retained/early_career_teacher_spec.rb
- spec/services/record_declarations/retained/mentor_spec.rb
- spec/services/record_declarations/retained/npq_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
- spec/services/record_declarations/started/mentor_spec.rb
- spec/services/record_declarations/started/npq_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/shared/context/service_record_declaration_params.rb
Record declaration tests have common setup blocks in them. This is the first step to extract into shared context and use it in other areas for example in request type rspec test.
> CPDTP-391 Extract common setup for record declarations test

- app/controllers/participants/validations_controller.rb
- spec/features/participants/participant_validation_steps.rb
From participant validation testing - [Jira](https://dfedigital.atlassian.net/browse/CPDRP-508?focusedCommentId=32255)
Fix issue where test API actually returns a boolean not a string "No" value
Expect a boolean instead of a string value for the `:active_alert` flag value returned from DQT API.
> CPDRP-508-DQT API returns a boolean not a string value

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
At present the validation service counts a match a blank NINo from the participant and  a blank from the DQT. This is wrong.
> Do not count two blank NINos as being a match

- app/views/participants/validations/manual_details_check_fip.html.erb
- spec/features/participants/participant_validation_steps.rb
From participant validation testing - [Jira](https://dfedigital.atlassian.net/browse/CPDRP-508?focusedCommentId=32247)
The "We’re checking your details" page was missing a sentence.
Add missing content to page
> CPDRP-508 Add missing line to checking details page

- app/views/lead_providers/guidance/reference.html.erb
Found two broken links in the reference documentation which should really be code since they are the API endpoints.
Update from links to <code> blocks
Visit the /lead-providers/guidance/reference#developing page on the app and view the changes under the Environments section on the page
> CPDTP-416 Fix reference html to code rather than links

- app/forms/participants/participant_validation_form.rb
- spec/forms/participants/participant_validation_form_spec.rb
Fixes whitespace at the point of validation for the entered participant details.
Squish whitespace before validating the form.
> Participant validation journey - Fix whitespace at validation time for form

- app/views/users/sessions/new.html.erb
This fixes the journey for users coming from /participants/start-registration
- https://ecf-review-pr-844.london.cloudapps.digital/participants/start-registration
- Continue
- Click back link
- Should be on https://ecf-review-pr-844.london.cloudapps.digital/participants/start-registration not https://ecf-review-pr-844.london.cloudapps.digital/
> Change back link on sign in page

- config/environments/deployed_development.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/sandbox.rb
- config/environments/staging.rb
For some reason the middleware causes 400s. I need to dig deeper into it, for now we should disable it.
> Temporarily disable auditing middleware

- app/helpers/application_helper.rb
- app/views/dashboard/show.html.erb
- spec/cypress/integration/aaa-meta/cypress.js
- spec/cypress/integration/accessibility.js
- spec/helpers/application_helper_spec.rb
- spec/requests/users/sessions_spec.rb
- Direct participants unable to start validation to the generic dashboard
- If a participant signs in before they're able to start validation, show
a more helpful message
> Change dashboard text

- app/views/lead_providers/guidance/npq_usage.html.erb
The NPQ usage guide incorrectly uses the term "induction" when it means course on the description line.
Fix to the text
> CPDTP-417_Change induction to course on NPQ usage guide

- app/validators/future_date_validator.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
Current valudation compares the date to the beginning of the day (I think). This causes failures when a provider sends us declaration from, say, 1h ago. We should compare it to current time.
> Fix declaration date validation for current time

- app/controllers/api/v1/participants_controller.rb
- app/serializers/participant_serializer.rb
- config/routes.rb
- lib/tasks/sandbox_data.rake
- spec/factories/teacher_profiles.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/EcfParticipantAttributes.yml
- swagger/v1/component_schemas/EcfParticipantCsvRow.yml
- swagger/v1/component_schemas/MultipleEcfParticipantsCsvResponse.yml
- swagger/v1/component_schemas/MultipleEcfParticipantsResponse.yml
CPDRP-659
Add the following details to participants API
- TRN
- eligible for funding
- uplift
I will follow this up with a PR to add test data to the sandbox
Still to do:
> CPDRP-659: Extend participant API with additional information

- app/controllers/api/v1/ecf_users_controller.rb
- app/serializers/ecf_user_serializer.rb
https://dfedigital.atlassian.net/browse/CPDEL-649
The previous method shouldn't be used any more as it uses attributes that aren't
the source of truth. We should look at the school cohort to find the user' cohort.
Also use the find_school_cohort method and amend the includes in the controller to
avoid N+1 lookups to find the cohort related to the school cohort.
The previous implementation was throwing an exception on the users index endpoint, 
which is bad because it prevents some users from being synced with engage and learn.
Unfortunately it is hard to create a test for this as a user can't be created without a cohort
without bypassing validations
> [CPDEL-788] Fix error for users with no cohort

- app/controllers/participants/validations_controller.rb
- app/forms/participants/participant_validation_form.rb
- app/helpers/application_helper.rb
- app/models/participant_profile/ecf.rb
- app/models/user.rb
- app/views/layouts/school_cohort.html.erb
- app/views/participants/validations/do_you_want_to_add_mentor_information.html.erb
- app/views/participants/validations/manual_details_check_fip.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/participants/happy_validation_journeys_for_ect_fip_spec.rb
- spec/features/participants/participant_validation_steps.rb
- spec/features/participants/sit_mentor_fip_validation_journeys_spec.rb
- spec/forms/participants/participant_validation_form_spec.rb
- spec/support/features/interaction_helper.rb
- spec/support/features/user_helper.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-770)
Add changes to participant validation journey for SIT/mentors
Redirect SIT/mentors to the validation journey if not already completed on sign in.
Add extra step to process for SIT/mentors to ask whether they want to add their mentor information now or not
Add banner to that is shown to SIT/mentors if they have not completed their mentor registration
Changes to end pages for SITs
Sign in as a SIT/mentor (`cpd-test+tutor-17@example.com` is a SIT mentor).
You should be shown the "Do you want to add your mentor information" question
Selecting yes, takes you into the participant validation as normal
Selecting no, takes you to the SIT dashboard.
The SIT should see an information banner reminding them to add their mentor information until …
> CPDRP-770 SIT mentor validation

- app/serializers/participant_serializer.rb
- spec/factories/ecf_participant_validation_data.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
There is a chance that something could go wrong at ECF TRN validation
that means a TRN we get from NPQ is not correct. Be conservative in
declaring that the TRN is validated.
Also, share some TRN pre-validation
> Only show validated TRNs after ECF validation

- app/views/participants/validations/complete_cip.html.erb
- app/views/participants/validations/manual_details_check_cip.html.erb
- spec/features/participants/happy_validation_journeys_for_ect_cip_spec.rb
- spec/features/participants/happy_validation_journeys_for_mentor_cip_spec.rb
- spec/features/participants/participant_validation_steps.rb
- spec/services/invite_schools_spec.rb
Rounds out the participant validation journey with changes for CIP
Changes to the "complete" and "manual checking" end of validation pages.
Specs to cover CIP ect and mentor journey
> Add CIP changes to participant validation journey

- app/controllers/api/v1/participant_validation_controller.rb
- app/services/participant_validation_service.rb
- spec/requests/api/v1/participant_validation_spec.rb
- spec/services/participant_validation_service_spec.rb
- Policy has given the go ahead to auto validate TRNs based on first name and not the whole name
- `ParticipantValidationService` can now be passed a config hash to check first name only
- This feature is disabled by default and will check the whole name by default
- The api endpoint `api/v1/participant-validation` checks first name now
- none
- See how to test in a review app below
- Use existing `NPQRegistrationApiToken` or create a new one
- See data extract spreadsheet for test data
```
curl -H "Authorization: Bearer TOKEN" https://ecf-review-pr-791.london.cloudapps.digital/api/v1/participant-validation/TRN?full_name=FULL_NAME_WITH_WONRG_LAST_NAME&date_of_birth=DOB&nino=
```
- Should return record regardless of last names
> Check first name only for api/v1/participant-validation

- app/models/finance/schedule.rb
- app/models/npq_validation_data.rb
- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- db/migrate/20210811124609_add_start_date_to_milestones.rb
- db/schema.rb
- db/seeds/dummy_structures.rb
- db/seeds/schedules.rb
- db/seeds/test_data.rb
- lib/tasks/sandbox_data.rake
I think every participant profile should have a schedule. That's because we will want to validate whether the declaration date on the declarations LPs send us matches that schedule.
Find all places where we create participant profiles, and add a default schedule to them. Yes, NPQ participants will need their own schedule, I think, but I don't know what it is - when we do we will add it to prod and run an update.
When this is merged and deployed, I will create the default schedule on each environment, and run something like 
```
ParticipantProfile.each { |profile| profile.update!(schedule: Finance::Schedule.default) }
```
I added `start_date` migration here because I want the milestones I create in production to have the right shape. Or as right as they can have as far as I know.
> Populate schedules on participant profiles

- app/forms/schools/add_participant_form.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/requests/schools/add_participants_spec.rb
Change the check to ensure the induction coordinator is not a mentor at
all before allowing them to add themselves at a school
> Prevent induction coordinator from adding themselves as a mentor at multiple schools

- spec/factories/ecf_participant_validation_data.rb
- spec/services/feature_flag_spec.rb
I don't think we really lose anything by simplifying these, do we?
> Simply feature flag test to prevent random failures

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/invite_schools_spec.rb
We send a courtesy email to induction coordinators to inform them that we have asked their ECTs and Mentors to enter details
> Extend the beta invite task to send a notification to SITs

- lib/tasks/trn_generator.rb
- spec/lib/tasks/trn_generator_spec.rb
- spec/lib/tasks/trn_generator_spec_spec.rb
Existing TRN generation code just did a sample without a comparison which meant that scaling it up was more likely to result in collisions.
This class generates unique and unassigned TRNs without having too much impact on the database.
Create a generator which caches all possibly TRNs and removes the ones already assigned.
Add an enumerator which will return the next unassigned TRN or raise an error if all of the available ones are exhausted.
All initial population of the huge array happens during start-up.
A shuffled version of this and the read of the database to determine which ones are actually is use happens the first time that #next is called. 
Once this happens, the available is treated as a stack and the next available value is popped off it.
This minimises the chances of a …
> CPDTP-423 Generate unique TRNS for testing and sandbox purposes.

- app/models/finance/schedule.rb
- app/models/npq_validation_data.rb
- app/models/participant_profile.rb
- app/services/record_declarations/base.rb
- app/validators/declaration_date_validator.rb
- app/validators/future_date_validator.rb
- config/locales/en.yml
- spec/docs/participant_declarations_spec.rb
- spec/factories/early_career_teacher_profiles.rb
- spec/factories/finance/milestones.rb
- spec/factories/finance/schedules.rb
- spec/factories/mentor_profiles.rb
- spec/factories/participant_profiles.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/retained/early_career_teacher_spec.rb
- spec/services/record_declarations/retained/mentor_spec.rb
- spec/services/record_declarations/retained/npq_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
- spec/services/record_declarations/started/mentor_spec.rb
- spec/services/record_declarations/started/npq_spec.rb
- spec/services/record_participant_declaration_service_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/shared/context/service_record_declaration_params.rb
We want to check that the declaration has been sent in the correct milestone period.
This does not check that the declaration type (started, retained) matches the milestone. 
1. Add start dates to milestones
2. Remove non-standard schedules from the seed
3. Make all participant declaration tests aware that they need to send the correct dates on them. 
As you can see, if a participant has no schedule, the API call will fail - cause it cannot check the dates. I can temporarily change it to be an early return (so the validation passes), but it really tells me we should populate schedules on participant profiles. 
I need to set up schedules for all test participants so this can be properly tested. 
So I think I will extract the migration part from this PR, add a rake task, deploy everywhere …
> Add milestone date validation

- spec/features/participant-declarations/submit_participant_declarations_spec.rb
Despite the milestones PR taking a while, it had no conflicts in forever, so I didn't get the integration tests merged earlier today in it. And they broke, cause they were talking about old dates. 
Make integration tests aware of the time they need to be sent at.
> Add milestone setup to T&P integration tests

- lib/tasks/sandbox_data.rake
- lib/tasks/school_urn_generator.rb
- lib/tasks/trn_generator.rb
- lib/tasks/valid_test_data_generator.rb
- spec/lib/tasks/school_urn_generator_spec.rb
Creating test data can be a minefield if you don't have the correct tools in place. This rake task allows us to create batches of data for lead providers with representative samples of how the expected schools and participants would look.
- 11% sparsity_uplift
- 22% pupil_premium_uplift
- 14% withdrawn record sets for participants
- Randomised mentors and early_career_teachers with and without their equivalents (i.e. some mentors without ECTs and some ECTs without mentors)
- Even split of valid and missing TRN data for participants.
- Move methods for generation of data into callable modules and classes and out of the rake task
- Cascade creation of records where required to fulfil the numbers of schools and participants per school for each lead provider.
Run the task and watch it …
> Cpdtp 423 create tool to generate valid data for lead providers to test against

- app/models/school.rb
- spec/models/school_spec.rb
This currently prevents lead providers from declaring partnerships with these schools
> Make cip_only? return false for Section 41 schools

- terraform/app/variables.tf
After yesterdays fix for dockerhub horrors, it seems our destroy setup is not working: https://github.com/DFE-Digital/early-careers-framework/runs/3361905808?check_suite_focus=true
Set default values to the docker variables in terraform. I hope this will make them non-required.
I guess we could add them to the destroy workflow, I just don't know if it is the good idea in principle.
> Set defaults to docker variables to prevent destroy workflow failing

- app/controllers/api/v1/npq_profiles_controller.rb
- app/models/npq_validation_data.rb
- app/services/npq/create_or_update_profile.rb
- spec/cypress/app_commands/scenarios/admin/school_participants.rb
- spec/features/participant-declarations/submit_participant_declarations_spec.rb
- spec/models/npq_validation_data_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/services/npq/create_or_update_profile_spec.rb
- This is the second attempt after https://github.com/DFE-Digital/early-careers-framework/pull/863 due to other shifting changes
- There is a callback `NPQValidationData#update_participant_profile`
- It creates and persists multiple database records
- It needs to be removed so we can have finer grain control of when it happens and the behaviour of it
- Remove the callback `NPQValidationData#update_participant_profile`
- Extract the contents to a new service `NPQ::CreateOrUpdateProfile`
- Call this new service in the api controller and in tests where the data is depended upon
- There should be no behavioural changes for existing use cases
- One would be required to call this service class if `NPQValidationData` is mutated
- Not sure
- Use api calls to submit NPQ registrations
- …
> Extract NPQValidationData callback to service

- app/models/participant_profile.rb
- db/migrate/20210817084816_remove_null_from_participant_profile_schedules.rb
- db/migrate/20210817084817_validate_remove_null_from_participant_profile_schedules.rb
- db/schema.rb
- db/seeds/dummy_structures.rb
- spec/cypress/integration/schools/Year2020.feature
- spec/docs/npq_applications_spec.rb
- spec/factories/finance/schedules.rb
- spec/factories/participant_profiles.rb
- spec/forms/schools/year2020_form_spec.rb
- spec/models/npq_validation_data_spec.rb
- spec/models/participant_profile_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- spec/requests/schools/year2020_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
Participant profiles need schedules to validate that their declarations are sent at the right time.
Make all participant profiles require schedules. I will double check that this is the case in prod and sandbox before merging, but it should be.
I needed to wrap setting null in `safety_assured` because our postgres is 11, rather than 12+, and the recommended strong migrations way only works for 12+.
> CPDTP-294: Enforce schedules on participant profiles

- spec/services/npq/create_or_update_profile_spec.rb
Hopefully the last ever silent merge conflict in tests to do with schedules, now that the db-level enforcement is on `develop`.
> Add schedule to a failing spec

- app/models/participant_profile/npq.rb
- app/services/npq/create_or_update_profile.rb
- db/migrate/20210819104745_add_npq_course_to_participant_profile.rb
- db/schema.rb
- spec/services/npq/create_or_update_profile_spec.rb
- A `TeacherProfile` can have many `ParticipantProfile::NPQ`
- At the moment these are mapped one-to-one for each NPQ application that comes in
- However we only want an `ParticipantProfile::NPQ` per NPQ course
- This adds NPQ course to `participant_profiles` table
- This will enable the ability for `ParticipantProfile::NPQ` to be scoped on courses in a later change
- For new applications populate `ParticipantProfile::NPQ` with the NPQ course
- Once deployed I will retro back fill `ParticipantProfile::NPQ#npq_course` based on the attached application
- `safety_assured` was used in the migration as since it is new column with no data i don't see the duration of the operation being particularly very long
- See how to test in review app
- Via api calls
- Create a new NPQ application
- Should …
> Add NPQ course to ParticipantProfile

- app/services/npq/create_or_update_profile.rb
- spec/services/npq/create_or_update_profile_spec.rb
- My understanding is the `TeacherProfile` should be a source of truth for a TRN
- At the moment this is set when an NPQ comes in which may contain an unvalidated TRN
- Ensure only set `TeacherProfile#trn` if the trn on the NPQ has been validated
- My assumptions for TRN on `TeacherProfile` are correct?
- See testing on review app
- Through api calls
- Create an NPQ registration with an unvalidated TRN
- TRN should not be set on `TeacherProfile`
- Create an NPQ registration with a validated TRN
- TRN should be set on the `TeacherProfile`
> Only set TRN on teacher profile if NPQ validated

- app/components/admin/participants/table_row.html.erb
- app/controllers/admin/participants_controller.rb
- Minor tweaks around admin participants area
- Eager load validation decisions to prevent n+1
- Stop treating data in table as numerical, this removes it from being right aligned
- None
- Login as an admin
- View admin participants area
- Assuming there is data, there should be no n+1 queries in the logs
- All data in the table should be left aligned
- Same as local testing
> Minor admin participant tweaks

- lib/tasks/sandbox_data.rake
- lib/tasks/valid_test_data_generator.rb
One of the lead providers has asked for a different set of test data to run their tests against.
- Generate an equal spread of mentors and early career teachers
- Limited to 3 schools with 1500 of each type
- All "active" participants
- No missing TRNs
Since the existing code works on deltas and the previous run has been made, the database will need to be cleansed from the previous run. This will be done by removing schools, profiles and users and their associations created and updated between two points for this lead provider
i.e. The following snippet will be used
```where(created_at: "2021-08-18 13:43".."2021-08-18 13:49")```
The new script can then be run and will only add new schools and participants to make up the delta again (i.e. can be safely run and will only verify that the …
> Change so that one lead provider gets a different batch of data when the rake task is run

- app/controllers/concerns/api_pagination.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/Pagination.yml
Some providers were confused re: the limit. I think this is quite conservative so let's gradually increase it.
> Increase API pagination max per page from 100 to 250

- config/initializers/rack_attack.rb
We had some integration tests with LPs this week, and they ran into 300 rate limit. They mentioned it might be a bit low in some rare situations. I checked grafana for sandbox, and we reached like 16% of our processor at peak time. Request time spiked to like 0.07 seconds.
It seems not too close to our limit, so it would be interesting to see what happens when they try out more requests next week. 
Bump API endpoint throttling to 1000 per 5 minutes. 
If we are very worried about letting it into prod, I could make it environment aware, but I am not sure it's a good idea. Thoughts? 
Make more than 300 api calls in 5 minutes. If you really want to.
> Increase the rate limiting to api endpoints from 300 to 1000 per 5 minutes

- app/controllers/api/v1/participant_declarations_controller.rb
- app/serializers/participant_declaration_serializer.rb
- config/routes.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/MultipleParticipantDeclarationsResponse.yml
- swagger/v1/component_schemas/ParticipantDeclaration.yml
- swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v1/component_schemas/ParticipantDeclarationResponse.yml
Additional action (index) on participant-declaration endpoint to return list of declarations together with the eligibility for the payment status
GET request with pagination i.e. GET ```/api/v1/participant-declarations?page[per_page]=200&page[page]=1```
> CPDTP-340 Give providers feedback about declaration pay-ability

- app/controllers/api/v1/participant_declarations_controller.rb
- app/services/record_declarations/base.rb
- app/services/record_declarations/early_career_teacher.rb
- app/services/record_declarations/event_factory.rb
- app/services/record_declarations/mentor.rb
- app/services/record_declarations/npq.rb
- app/services/record_declarations/recorder_factory.rb
- app/services/record_participant_declaration.rb
- config/locales/en.yml
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/shared/context/service_record_declaration_params.rb
The participant-declaration controller had a global "catch-all" exception handler which was incorrectly always returning a message stating that the participant_id didn't match the course_identifier.
Working on the common interface for the withdrawn message highlighted this problem, when, for example, the underlying user didn't exist and a user.mentor? call (for example) would raise an exception that was then swallowed.
Refactor "participant-declarations" controller and validations as a step towards merging participant validation code into a block which will support both.
Move constant values into the class to avoid failures when the user creation fails for other validation types.
> CDPTP-206_Fix up the broken validation catch-all at the controller as a pre-step for implementing the withdrawn action

- app/serializers/ecf_user_serializer.rb
- spec/serializers/ecf_user_serializer_spec.rb
> Provide registration detail in ECF user api endpoint

- .rubocop.yml
- README.md
- app/services/importers/npq_manual_validation.rb
- spec/lib/importers/npq_manual_validation_spec.rb
- Based off https://github.com/DFE-Digital/early-careers-framework/pull/742
- The automatic TRN validation at the moment is not great due to missing data
- Therefore there is currently a manual validation process in place involving CSVs
- After the manual validation has been performed the data needs to be re-imported back into the service 
- Add CSV importer for NPQ applications
- Added new folder and therefore namespace for importers
- Differences from previous PR:
- Renamed spec to correct location
- Added `NPQ::CreateOrUpdateProfile` service
- Start rails console
- Create test NPQValidationData records with blank or incorrect TRNs
- Create a new CSV with headers `application_ecf_id,validated_trn` 
- Populate CSV with test records and correct TRNs
- `svc = …
> Service to import NPQ manual validation CSV data

- app/serializers/participant_serializer.rb
- spec/docs/participants_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantWithdrawal.yml
A few changes to the layout and content of the swagger documentation.
- Change the group order for the API endpoints
- Add in missing ECF withdrawal reasons from the withdrawal object
- Change the generated description to something less vague.
> CDPTP-206_Withdrawal_docs_wrap-up

- app/controllers/api/v1/participants_controller.rb
Withdraw participants change added some n+1 queries. I also saw some relating to `ecf_participant_validation_data`, so I fixed those too.
Load more things in the query in participants api.
Do we have (want?) tests for n+1 queries?
> Remove N+1 queries caused by serialising state

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
Make `McC...` and `Mcc...` match
> Change participant validation to be case insensitive on name

- spec/docs/npq_applications_spec.rb
Swagger generation creates a unique uuid for the examples even when nothing changes
- Force the uuid used in the examples to a fixed value to enable generation of the same json api code rather than having it change every time and possibly mask other more relevant changes.
> CDPTP-362 Stop swagger generator creating new UUIDs every time

- app/controllers/participants/validations_controller.rb
- app/jobs/validation_retry_job.rb
- lib/tasks/cron.rake
- spec/jobs/validation_retry_job_spec.rb
The DQT API went down last week, and there are records marked with API failure. We could fix it as a one-off, but I think the API is flaky enough that it's worth making this a regular thing.
I looked for ways to commonise this with the logic in the controller, but couldn't quite figure it out
> Add job to retry failed validations

- app/serializers/participant_declaration_serializer.rb
- app/services/record_declarations/base.rb
- spec/features/participant-declarations/submit_participant_declarations_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ParticipantDeclarationAttributes.yml
- swagger/v1/component_schemas/ParticipantDeclarationRecordedResponse.yml
Submission of a participant declaration should return a full participant declaration json object rather than just an ID
Modified response
Fixed rspec tests
> CPDTP-362 Change to return full participant json object instead of just an ID

- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/staging.tfvars
We're expecting an increase in load at the beginning of September. Throw more compute at the problem - bound to work
> Bump all production-like environments to four instances

- app/components/admin/participants/details/npq.html.erb
- app/components/admin/participants/details/npq_pending.html.erb
- app/components/admin/participants/table_row.html.erb
- app/components/admin/participants/table_row.rb
- app/controllers/api/v1/npq_profiles_controller.rb
- app/serializers/npq_application_csv_serializer.rb
- app/serializers/npq_application_serializer.rb
- app/serializers/npq_validation_data_serializer.rb
- app/services/npq/create_or_update_profile.rb
- db/migrate/20210825123807_add_ukprn_to_npqs.rb
- db/migrate/20210827111927_add_urn_ukprn_to_participant_profiles.rb
- db/schema.rb
- spec/components/admin/participants/details_spec.rb
- spec/components/admin/participants/table_row_spec.rb
- spec/factories/npq_validation_data.rb
- spec/factories/participant_profiles.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v1/npq_profiles_spec.rb
- spec/services/npq/create_or_update_profile_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/MultipleNPQApplicationsResponse.yml
- swagger/v1/component_schemas/NPQApplicationAttributes.yml
- UKPRN - UK Provider Reference Number - Another identifier for learning providers in the UK - register available at https://www.ukrlp.co.uk/ - It is an 8 digit number
- NPQ will officially support Further Education (FE) bodies in the near future although it is currently possible to sign up with an FE body
- These FE bodies include Local Authorities (LAs)
- These LAs only have UKPRNs associated with them and are not assigned a URN
- Incoming new NPQs will have a URN and UKPRN populated where possible
- Outgoing NPQ applications will have URN and UKPRN where the data is available
- After deployment we can retro fill any missing UKPRNs that we have so these are available to providers and for consistency
- Updated NPQ docs + guidance
- none
- Hook up to NPQ registrations app
- Register with …
> Support UKPRNs for NPQs

- spec/cypress/app_commands/scenarios/schools/multiple_schools.rb
- spec/features/schools/participants/remove_from_cohort_spec.rb
https://percy.io/c72bbcf6/early-careers-framework/builds/12451301/changed/702884991?browser=chrome&browser_ids=16&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=1280
Set induction programme choice for school cohorts. Not sure why it became random recently, but oh well...
> Remove some percy randomness

- app/services/validation_beta_service.rb
- spec/services/validation_beta_service_spec.rb
A piece of logic was missed in this previous PR: https://github.com/DFE-Digital/early-careers-framework/pull/938
We need to adjust this to make sure we don't email any schools that have opted out of updates
As above
> CPDRP-908 Don't email schools that have opted out of updates

- app/controllers/concerns/api_pagination.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/Pagination.yml
A provider would like to be able to retrieve more participants using the API so that they can continue their integration. I have tested up to 3000 participants which was returned in c. 1.5s, which seems reasonable to me.
> Increase API pagination max per page from 250 to 3000

- app/controllers/api/api_controller.rb
- app/services/api/param_error_factory.rb
- app/services/participants/profile_attributes.rb
- app/services/record_declarations/base.rb
- app/services/record_declarations/retained.rb
- config/locales/en.yml
- spec/docs/participant_declarations_spec.rb
- spec/features/participant-declarations/submit_participant_declarations_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/retained/npq_spec.rb
- spec/shared/context/service_record_declaration_params.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/Error.yml
- swagger/v1/component_schemas/ErrorResponse.yml
Errors are wrapped in the expected format i.e.
```
{
"errors": [
{
"title": "Bad or missing parameters",
"detail": "is invalid"
}
]
}
```
New factory to generate the json error object from the provided parameters.
Also validation for evidence_held has been fixed
> CPDTP-362 Consistent errors in the declaration API

- lib/tasks/manage_admins.rake
- spec/smoke_tests/participant_declarations_spec.rb
- spec/spec_helper.rb
https://dfedigital.atlassian.net/browse/CPDRP-893
There seems to be just a single test causing issues in other tests. This PR fixes the issues.
One of the tests were invoking one of the rake tasks, which in turn was calling `include <URL_HELPERS>` without any receiver. In result, url_helpers has been included into Object, making it available for all the application objects (including `nil`). In the meantime, the depth of rails routing is invoking `url_for` on the `_routes` - `_routes` is a memoized method and its memoization is dependant on `@router.respond_to?(:url_for)` (`_routes` should be an instance of ActionDispatch::Routing::RouteSet`). After the inclusion of url_helpers into `nil`, this caused the instance variable not to be set at all leading to `wrong number of arguments 4, …
> Preventing accidental inclusion of url_helpers into ALL ruby objects

- db/seeds/schedules.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
- swagger/v1/component_schemas/ECFParticipantChangeSchedule.yml
https://docs.google.com/presentation/d/1HBVEZabnGuakaAKJ6d5AGJthC7Bl21cex4MN5K8rus4/edit#slide=id.ge582d819d0_0_304 has details of two January schedules, and I think they have been communicated to the providers. 
Add two January schedules to the seeds - I will run that when deployed
Add the january identifiers to the api docs
I opted to make duplicate milestones for the big milestone "Output 2 – Retention Point 1, Output 3 – Retention Point 2" from the slides. That way we can still have one declaration type per milestone. This might be changing soon, but for now it should work well enough.
Everything should already be tested.
The api docs for change schedule should have january schedule identifiers.
> CPDTP-369: Add january schedules into the seeds and the documentation

- app/controllers/api/v1/participant_declarations_controller.rb
- app/models/participant_declaration.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ListFilter.yml
Lead providers need information about their declarations for a specific participant
A new filter ```participant_id``` has been added to the participant-declarations API
> CPDTP-429 Give providers feedback about declaration pay-ability

- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
Training status wasn't updated in the swagger documentation. This PR fixes that.
> CPDTP-465 Fix incorrect swagger documentation for training_status vs state

- config/initializers/sentry.rb
We are getting a lot of new traffic, and it seems we ran into sentry quota.
This should reduce the number of transactions we send to centry by quite a lot.
Decrease the rate of capturing requests from 0.1 to 0.01
> Reduce sentry capture rate to avoid sentry quota

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/participants_controller.rb
- spec/requests/api/v1/participants_spec.rb
@blackrat triaged a Sentry issue in the sandbox to a problem with "www-form" encoding of the optional `updated_since` param
Unescape the `updated_since` value
Add `rescue_from` handler to catch invalid SQL statement errors and return 400 status to caller.
Accessing the participants api and passing an invalid `updated_since` param will now return a 400 error instead of a 500
If the `updated_since` is encoded e.g. "2021-09-01T11\%3A48%3A09" it will be unencoded before used in the query.
> Fix sandbox issue with encoded updated_since date

- app/mailers/participant_validation_mailer.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- spec/mailers/participant_validation_mailer_spec.rb
- spec/services/validation_beta_service_spec.rb
Send another mailer to tell SITs that we have asked their ECTs and mentors for validation information. This largely uses the same criteria as https://github.com/DFE-Digital/early-careers-framework/pull/938 but because we needed a school name I had to make sure that we weren't sending to the same SIT for multiple schools. Other than that, the criteria and tests are the same.
Notify template: https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/d560fb2e-243d-48b1-bf61-c7e111f56858
> CPDRP-908 Add email to tell SITs we have asked ECTs and mentors for info

- app/mailers/participant_validation_mailer.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- spec/factories/participant_profiles.rb
- spec/mailers/participant_validation_mailer_spec.rb
- spec/services/validation_beta_service_spec.rb
This PR sends an email to ECTs and mentors who have not yet added validation information, irrespective of whether they are in the beta or not.
Template: https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/50ee41e5-06b9-41cf-9afd-d5bc4db356c4
Things to check:
1. Is the query correct?
2. Are the email template params correct?
> CPDRP-908 Add mailer for ECTs and mentors who have not yet added validation info

- .githooks/pre-commit
- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v1/participants_controller.rb
- app/controllers/concerns/api_csv.rb
- app/serializers/participant_declaration_serializer.rb
- spec/docs/participant_declarations_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/MultipleECFParticipantsCsvResponse.yml
- swagger/v1/component_schemas/MultipleNPQApplicationsCsvResponse.yml
- swagger/v1/component_schemas/MultipleParticipantDeclarationsCsvResponse.yml
- swagger/v1/component_schemas/ParticipantDeclarationCsvRow.yml
We want to support CSV formats to make ourselves as flexible to the providers importing data as possible.
https://dfedigital.atlassian.net/browse/CPDTP-428
Add an csv format support to existing participant declarations index endpoint.
Pull 'to_csv' method into its own module to share it between controllers.
Specify the format of declaration date in serialiser explicitly to avoid `to_s` in csv computation returning a different format.
Add documentation and tests.
Fix the githook saying `/components/schemas/XXXXXX` is a bloody AWS key. 
I imagine it will have some conflicts with https://github.com/DFE-Digital/early-careers-framework/pull/952, but they shouldn't be too terrible. 
Added request specs for the csv index endpoint
Hit the `/api/v1/participant-declarations.csv` endpoint with the …
> CPDTP-428: Csv participant declarations

- app/forms/participants/participant_validation_form.rb
- app/views/participants/validations/tell_us_your_details.html.erb
- spec/features/participants/participant_validation_steps.rb
- spec/forms/participants/participant_validation_form_spec.rb
[Jira](https://dfedigital.atlassian.net/browse/CPDRP-881) On the participant validation form, allow entry of mixed case and internal whitespace for the National Insurance Number and remove whitespace and force uppercase before validation
Remove all whitespace and for uppercase before validation of national insurance number on the "Tell us your details" page of the participant validation journey.
> CPDRP-881 Remove internal whitespace and force uppercase before validation of NINo

- app/models/partnership.rb
- app/models/school.rb
- app/models/school_cohort.rb
- spec/models/partnership_spec.rb
- spec/models/school_cohort_spec.rb
- spec/models/school_spec.rb
This morning a provider asked us why we updated a lot of participant records on sandbox around 6am this morning.
Well... because our gias import job ran at 6am, it saved all schools (most with no changes), which triggered `after_commit` hook for ALL schools. Which touched all participants for all GIAS schools.
1. Remove touching participants when school is updated. I am not sure we should update participants of school when school name changes.
2. Reduce touching participants on school cohort. Here I think we need to update them, because school cohort has a lot of things that matter for participants. Say, what induction programme they are following.
I can alter point 1 to be more like point 2. If we really want to. I just am not sure we really want to. 
Unit tests documenting new …
> Reduce needless touching of participants

- .github/PULL_REQUEST_TEMPLATE.md
- app/views/lead_providers/guidance/release_notes.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-470
LPs and their relationships managers are not particularly happy with how little we broadcast the changes we work on and deploy. I think we should revive the changelog and start updating it regularly - so that we can tell them to look for changes at that page first.
This should limit the surprise when we introduce new fields, endpoints, etc. Or at least give us an option of saying "this was in changelog, please follow that page closely".
For this to work we need to remember about changelog, and I reckon a PR template is a good place for it.
I used the new template for this PR, I hope it is neater :) 
2. Go to `/lead-providers/guidance/release-notes`.
Does this …
> Improve PR template, in particular mention the changelog

- app/mailers/participant_validation_mailer.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- spec/mailers/participant_validation_mailer_spec.rb
- spec/services/validation_beta_service_spec.rb
Add mailer for CIP mentors who have not added their details for validation.
Notify template: https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/e0198213-c09d-41aa-8197-b167e495e49d
(This PR is still a draft because I'm confirming whether the ((statutory_guidance)) variable is applicable. I suspect it's not.)
> Email: CIP mentors who have not added their details for validation

- app/mailers/participant_validation_mailer.rb
- app/models/participant_profile.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- db/migrate/20210906164616_add_request_for_details_sent_at_to_participant_profiles.rb
- db/schema.rb
- spec/factories/ecf_participant_eligibility.rb
- spec/factories/participant_profiles.rb
- spec/mailers/participant_validation_mailer_spec.rb
- spec/services/validation_beta_service_spec.rb
We would like to send out a number of emails requesting that participants give us more information. The first three are:
- ECTs who have not added their details for validation
- FIP mentors who have not added their details for validation
- CIP mentors who have not added their details for validation
- SITs who are ALSO mentors AND have not added their details for validation
TODO:
This PR also includes code to track whether we have already sent out such emails to participants.
> Add ECT and FIP mentor emails

- app/views/lead_providers/guidance/npq_usage.html.erb
Ticket: https://trello.com/c/AIB5ITbs/467-improve-docs-on-accept-reject-around-id
- Providers are unclear on what id to pass to the `/api/v1/npq-applications/{id}/accept` and reject endpoints
- On the guidance pages explicitly clarify that the `id` is that of the NPQ application 
- none
- visit https://ecf-review-pr-971.london.cloudapps.digital/lead-providers/guidance/npq-usage#accept-npq-application
- see updated changes from that point onwards
- none
> update guidance to expand which NPQ id to use

- app/controllers/schools/choose_programme_controller.rb
- app/forms/induction_choice_form.rb
- app/models/school_cohort.rb
- app/views/schools/choose_programme/choice_saved_school_funded_fip.html.erb
- app/views/schools/dashboard/show.html.erb
- config/locales/admin/induction_choice_form.yml
- config/locales/en.yml
- config/locales/schools/induction_choice_form.yml
- config/routes.rb
- spec/cypress/app_commands/scenarios/cip_only_school.rb
- spec/cypress/integration/schools/ChooseProgrammeCIPOnly.feature
- spec/cypress/support/step_definitions/common-interaction.js
- spec/cypress/support/step_definitions/common-navigation.js
- spec/features/schools/dashboard_spec.rb
- spec/forms/induction_choice_form_spec.rb
- spec/models/school_cohort_spec.rb
https://dfedigital.atlassian.net/browse/CPDRP-904
- Add a new "school funded fip" programme choice for cip-only schools, this is an "opt-out" choice.
- Remove the link to the school cohort from the school dashboard when the chosen programme is school funded fip. We would need a new page for this as without any changes it would tell the user that they had chosen the DfE funded FIP. We are rebuilding this dashboard where the link will be removed so it isn't worth creating a new school cohort page just for this choice.
Log in as the induction coordinator for a cip only shool, eg cip-only-induction-tutor@example.com and choose "Training provider funded by your school" as the programme choice.
> CPDRP-904 Add school funded fip induction choice

- Dockerfile
Ticket: n/a
- We are installing yarn dev dependencies into our docker images
- These aren't needed as far as I can tell as the test suite does not go through our built images
- So it's just cluttering up the produced image
- From sample size of one test run, it has shaved off about 2 minutes of the deploy to review app time 
- see inline comments
- visit https://ecf-review-pr-972.london.cloudapps.digital
- app should function as normal
- none
> only install production yarn dependencies

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/ecf_users_controller.rb
- app/controllers/api/v1/npq_applications_controller.rb
- app/controllers/api/v1/participants_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/api_filter.rb
- app/views/lead_providers/guidance/release_notes.html.erb
- spec/requests/api/v1/participants_spec.rb
A provider asked us why a format of a filter works on NPQ applications, but not on participants.
IMO they should work everywhere. And it does not hurt us to make the date format range a little wider.
I added the test to participants api - I guess technically I could add tests to all places using the filter, but since it is a shared functionality, should I really?
2. Curl `/api/v1/participants.json?filter[updated_since]=1970-01-01T00%3A00%3A00%2B01%3A00&page[page]=1&page[per_page]=100` with proper authorisation (say, ambition-token).
3. You should get 200 response and a list of values. …
> Standardise updated_since filter processing

- app/controllers/concerns/api_filter.rb
- spec/requests/api/v1/npq_applications_spec.rb
Ticket: https://trello.com/c/pTTNAH4t/466-ecf-api-handle-incorrect-input-for-filters
- An error is raised when api users pass incorrect filter to npq applications api endpoint
- This should now no longer error
- It should now return meaningful error message to the api user
- create a private api token
```
LeadProviderApiToken.create_with_random_token!(cpd_lead_provider: CpdLeadProvider.all.sample)
```
- make malformed request
```
curl -H "Authorization: Bearer TOKEN" "https://ecf-review-pr-975.london.cloudapps.digital/api/v1/npq-applications?filter=asd"
```
- expect:
```
{"errors":[{"title":"Bad parameter","detail":"Filter must be a hash"}]}
```
- Although this does affect the external api I don't feel it needs to be documented on the specific endpoint
- Do we have general documentation …
> add filter parameter check on npq applications api

- spec/services/validation_beta_service_spec.rb
The test breaks often enough that it is annoying, at least in CI.
The reason the test broke was that in the email sending service, we only send the email to the first school of the IC. But our test IC has two schools that are 'valid choices' for the service.
And then the test checks that the service sent an email to the specific first school - so sometimes it fails. For some reason failure on my local machine I needed to run it 80 times before getting 50% failure rate, but it seems on CI it happened more.
> Remove spurious failure in email sending test

- app/controllers/api/v1/participant_declarations_controller.rb
- spec/docs/participant_declarations_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
Add updated_since filter to `GET /api/v1/participant-declarations`
Allow participant declarations to be filtered by when they were created (or last updated). A provider tried to do this previously and I don't see any reason why we wouldn't let them.
> Add updated_since filter to /api/v1/participant-declarations

- app/views/lead_providers/guidance/_ecf_usage_participant_actions.html.erb
- app/views/lead_providers/guidance/ecf_usage.html.erb
- spec/docs/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ListFilter.yml
- swagger/v1/component_schemas/ListFilterDeclarations.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-463
Also fixes imperfect filter documentation in swagger
The guidance was getting lengthy, so I started using partials. They have no variables or anything complex, so I don't think we need to componentise them. 
2. Go to LP ecf guidance page
Does this change anything in our external APIs? If so, did you remember to update the CHANGELOG for Lead Providers? (lead-providers/guidance/release-notes) - no api changes
> CPDTP-463: Update participant action docs

- .rspec_parallel
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/lead_providers/openapi_controller.rb
- config/database.yml
- config/environments/test.rb
Ticket: none
- Adds ability to run rspec test suite in parallel
- This at the moment is for local developer use only as a first step
- Maybe after we can patch it into the CI process
- Has dropped down from 5/6 minutes runtime to about 90 seconds for my local machine
- n/a
- none
> Add parallel tests for rspec for dev use

- terraform/monitoring/config/staging/alert.rules.yml
I got annoyed by "high rate of failing requests" notification on staging. They seem to be 404s by bots, they happen every now and then in low volumes. But staging is just not ussed for much, so they compose a high percentage of requests, which triggers our alarms.
https://www.robustperception.io/combining-alert-conditions is where I got the `and` from.
> Set a minimum number of requests captured on staging before we raise an alert

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/invite_schools_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-929
Adds a mailer so that we can send a separate nomination email to Section 41 schools.
The notify template is: https://www.notifications.service.gov.uk/services/d1207ebf-ac0c-47b8-b1bf-16dc899e0923/templates/a4ba1de4-e401-47f4-ac77-60c1da17a0e5
> CPDRP-929: Add Section 41 schools invite mailer

- app/models/teacher_profile.rb
Slack conversation and past experience show that the teacher profile - participant profile relations don't work great
I tried quite hard to replicate the original behaviour in tests, to no avail. I think there is something clever going on with ActiveRecord caching :(
If someone can produce a test that fails on develop when it shouldn't - say, the profile exists but `user.teacher_profile.ecf_profile` doesn't get it - I would gladly bring it in. 
1. ssh into the review app
2. Get an ecf participant id - `ParticipantProfile.ecf.first.user.id`
3. exit
4. ssh again
5. `User.find("<your id from step 2>").teacher_profile.ecf_profile` - should not be nil.
> Fix annoying scopes

- app/controllers/api/v1/participants_controller.rb
- spec/requests/api/v1/participants_spec.rb
A provider noted that we are re-ordering results while they’re trying to paginate through results. We _are_ ordering results when providers use the `updated_since` filter but we don't when they aren't.
This is the first stab at allowing providers to pull results with consistent ordering from the API. Later, I think we will need to add an `updated_before` filter so that they can scope result sets properly.
---
This PR returns participants so that the oldest users are on page 1.
> Return participants ordered by created_at asc

- app/components/search_box.html.erb
- app/components/search_box.rb
- app/controllers/admin/participants_controller.rb
- app/views/admin/participants/index.html.erb
- app/webpacker/styles/search_box.scss
- spec/components/search_component_spec.rb
- spec/rails_helper.rb
- spec/requests/admin/participants_spec.rb
Ticket: A tiny part of https://trello.com/c/3FttpebV/406-handle-duplicate-signups
Desktop
Mobile
- login as an admin
- filter participants by different types
- should only return participants of selected type
- none
> admins can filter participants by type

- app/controllers/api/api_controller.rb
- app/services/record_declarations/base.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
- spec/shared/context/service_record_declaration_params.rb
When a participant declaration has been created, any subsequent duplicate declaration for this participant with any different declaration date will be rejected with the 409 status code.
> CPDTP-434 Reject different date duplicates

- config/environments/development.rb
- config/initializers/action_mailer.rb
Currently, `action_mailer.default_url_options.host` is blank in almost all environments. This leads to us adding `host: Rails.application.config.domain` to all url_helpers that are used for email purposes. If this is missed, the emails will work in development, but not in production, which is problematic.
Now, ideally this would be set in the application.rb to be shared by all environment. However, `config.domain` is set in each environment file which loads after the `application.rb` so this would not work - that's why we need to work within the initializer. Additionally, the initializer files run after railtie initializers, including ActionMailer::Railtie which is copying populating `ActionMailer::Base` configuration with `Rails.application.config.action_mailer`, whcih is why it is …
> Setting up action mailer default url host based on domain

- package.json
Ticket: none
Move JS development dependencies into the development group. So they are not cluttering the production docker image
- Visit the review app
- Should behave as normal
- none
> move axe js dependencies as dev dependencies

- app/services/early_career_teachers/create.rb
- app/services/mentors/create.rb
- app/services/npq/create_or_update_profile.rb
- db/seeds/dummy_structures.rb
- db/seeds/test_data.rb
- lib/tasks/valid_test_data_generator.rb
https://github.com/DFE-Digital/early-careers-framework/pull/990 adds resuming participants. We should not resume a participant when they are already active.
But we haven't made a training status for each participant profile yet - some are active by the fact of not having a training status.
Soo, we should just add a training status to all existing profiles. When this is merged and deployed I will run something like 
```
ParticipantProfile.each { |profile| ParticipantProfileState.find_or_create_by!({ participant_profile: profile }) }
```
Nothing I can think of.
> Add training status states to all places creating new profiles

- app/controllers/api/api_controller.rb
- app/services/record_declarations/base.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-485
The only case when we need it (as far as I can tell) is participant declarations endpoint. But if you know of more, let me know and I will fix those too. 
2. Submit a started declaration, with `evidence_held` field.
Does this change anything in our external APIs? If so, did you remember to update the CHANGELOG for Lead Providers? (lead-providers/guidance/release-notes) - not really a change. I can add something to the changelog if we think it is worth it.
> CPDTP-485: Add unpermitted parameters to participant declarations api

- app/views/lead_providers/guidance/ecf_usage.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-483
Two of the paragraphs in the updated usage guide had badly formed html. This fixes it.
> CPDTP-483 Change closing tags on two of the lines from link to paragraph

- app/controllers/schools/year2020_controller.rb
- app/views/schools/year2020/cohort_already_have_access.html.erb
- config/routes.rb
- lib/email_redirector.rb
- spec/requests/schools/year2020_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-768 (all error states except from the first were done in a separate PR)
> CPDEL 768 limit adding 2020 nqts to once only

- app/components/finance/ecf/breakdown_summary.html.erb
- app/components/finance/ecf/breakdown_summary.rb
- app/components/finance/ecf/contract.html.erb
- app/components/finance/ecf/contract.rb
- app/components/finance/ecf/contract_band_row.html.erb
- app/components/finance/ecf/contract_band_row.rb
- app/components/finance/ecf/output_payments.html.erb
- app/components/finance/ecf/service_fees.html.erb
- app/controllers/finance/lead_providers_controller.rb
- app/helpers/finance_helper.rb
- app/views/finance/lead_providers/show.html.erb
- app/views/finance/lead_providers/show_contract.html.erb
- config/locales/en.yml
- config/routes.rb
- lib/payment_calculator/ecf/breakdown_summary.rb
- spec/requests/finance/lead_providers_controller_spec.rb
- spec/services/calculation_orchestrator_spec.rb
This adds a view of contract information which allows the underlying providers contract details which forms the basis of the calculations.
There will be a wider "contract summary" and proper design, but for now, this gives a general shape that can be viewed.
Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDTP/boards/87?selectedIssue=CPDTP-473
This PR is mainly for the view components and controller actions, since it's more likely that we'll have a landing page and a more details Contract Summary once it's gone through the content design phase. …
> CDPTP-473 Add basic ECF contract display for validation of contract information

- app/controllers/participants/validations_controller.rb
- spec/features/participants/participant_validation_steps.rb
Aim to boost automatic validation rate of mentors by only comparing their first name
> Switch over validation to match against first name only

- app/serializers/participant_serializer.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
- swagger/v1/api_spec.json
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-902
Following an investigation into whether we need to update the pupil premium data following the initial import earlier in the year, it was concluded that this data was not going to change this cohort.
That means we can start to expose `pupil_premium_uplift` and `sparsity_uplift` to lead providers via the participants endpoint.
- These fields can only be `true` or `false` unless the participant is withdrawn. Is that correct?
> CPDRP-902 Add pupil premium and sparsity uplifts to participants endpoint

- spec/services/void_participant_declaration_service_spec.rb
I am not quite sure why it worked so often in the first place. `declaration_date` is the thing that matters, and the test was set up to operate on `created_at`.
I think it was a combination of a few wrong things joining into something that looked right...
> Fix flaky test

- app/controllers/participants/validations_controller.rb
- app/jobs/validation_retry_job.rb
- app/models/ecf_ineligible_participant.rb
- app/services/check_participant_eligibility.rb
- app/services/importers/ineligible_participants.rb
- app/services/participant_validation_service.rb
- app/services/validate_participant.rb
- db/migrate/20210910101052_create_ecf_ineligible_participants.rb
- db/schema.rb
- lib/tasks/ineligible_participants.rake
- spec/factories/ecf_participant_eligibility.rb
- spec/factories/ineligible_participant.rb
- spec/features/participants/participant_validation_steps.rb
- spec/fixtures/files/ineligible_participants.csv
- spec/jobs/validation_retry_job_spec.rb
- spec/services/check_participant_eligibility_spec.rb
- spec/services/importers/ineligible_participants_spec.rb
- spec/services/participant_validation_service_spec.rb
- spec/services/validate_participant_spec.rb
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CPDRP-672)
Create means to hold ineligible participants and populate from CSV files. These are be checked against during automatic participant validation.  The CSV data is sensitive so will be a one-off manual task to import.
Added the `ValidateParticipant` "service" to wrap up the `ParticipantValidationService` and the handling of creating/updating validation data and eligibility data.
In addition, the `ParticipantValidationService` now calls `CheckParticipantEligibility` during validation. This simply looks up the `trn` and returns an ineligibility reason if the TRN is in the list.
Update `Participants::ValidationController` and `ValidationRetryJob` to use new `ValidateParticipant` service.
__NOTE:__ This does not yet change the …
> CPDRP-672 update eligibility checks

- app/components/finance/ecf/breakdown_summary.html.erb
- app/components/finance/ecf/breakdown_summary.rb
- app/components/finance/ecf/contract.html.erb
- app/components/finance/ecf/contract.rb
- app/components/finance/ecf/contract_band_row.html.erb
- app/components/finance/ecf/output_payment_row.html.erb
- app/components/finance/ecf/service_fee_row.html.erb
- app/helpers/finance_helper.rb
- app/models/participant_band.rb
- config/locales/en.yml
- db/migrate/20210915155919_add_output_payment_contribution_percentage_to_band.rb
- db/migrate/20210915155919_add_percentages_to_band.rb
- db/migrate/20210915161312_add_revised_target_to_call_off_contract.rb
- db/schema.rb
- lib/payment_calculator/ecf/breakdown_summary.rb
- lib/payment_calculator/ecf/contract/output_payment_calculations.rb
- lib/payment_calculator/ecf/contract/service_fee_calculations.rb
- lib/payment_calculator/ecf/output_payment_aggregator.rb
- lib/payment_calculator/ecf/service_fees.rb
- lib/payment_calculator/ecf/service_fees_for_band.rb
- lib/tasks/payment_breakdown.rake
- lib/tasks/payment_breakdown.rb
- spec/factories/call_off_contract.rb
- spec/factories/participant_band.rb
- spec/models/participant_band_spec.rb
- spec/services/calculation_orchestrator_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-440
New banding rules are applicable to some lead providers who have been issued with revised target
This change reflects the changes to banding to support these.
1. The variable amount has changed from a fixed calculation of 60% to a variable one depending on the band, so has been moved to the DB.
2. An optional revised target which has been added to the call_off_contract as a 2nd target (with a 2% uplifted top level). NOTE: There is currently no cap on the existing 3rd band, but this may be revised too. The existing code will cope with this too if it becomes something that we set as the max value in the database. (which appears likely)
3. Output display has become conditional depending on whether the provider has contracted a revised …
> CPDTP-440 New Banding payment rules

- spec/features/schools/dashboard/manage_fip_training_spec.rb
- spec/features/schools/dashboard/manage_training_steps.rb
A recent ticket introduced feature specs that sent screenshots to Percy. Some of the views had dynamic dates. This PR is to freeze dates within the feature specs causing the problem.
Ticket:
> Fix for dynamic dates in Percy

- app/mailers/school_mailer.rb
- app/models/school.rb
- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/invite_schools_spec.rb
This includes eligible, opted-out schools and SITs
Remove the old year2020 invite email, this template will no longer be used
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-829
> CPDEL-829 Add two new emails to send in the first round of NQT+1 invites

- app/views/layouts/_application.html.erb
Firefox requires charset to appear in first 1024 bytes of response. Move the meta tag to the top of the layout to fix this. Report: https://ukgovernmentdigital.slack.com/archives/C0Q2PT1S9/p1632134954402500
> Fix special character display in firefox

- app/serializers/participant_serializer.rb
- spec/serializers/participant_serializer_spec.rb
Context: https://ukgovernmentdfe.slack.com/archives/D021MT22UEL/p1632147075009000
This should also fix the N+1 query on the endpoint: https://sentry.io/organizations/dfe-bat/performance/early-careers-framework:690e901e4b274632af4c4664b578b1cf/?project=5748989&query=transaction.duration%3A%3C15m+transaction.op%3Arails.request+event.type%3Atransaction+http.method%3AGET&statsPeriod=24h&transaction=Api%3A%3AV1%3A%3AParticipantsController%23index&unselectedSeries=p100%28%29
> Change the participant_serializer to use cached uplift

- app/controllers/participants/validations_controller.rb
- app/models/ecf_participant_eligibility.rb
- app/serializers/participant_serializer.rb
- app/services/validate_participant.rb
- spec/features/participants/participant_validation_steps.rb
- spec/jobs/validation_retry_job_spec.rb
- spec/models/ecf_participant_eligibility_spec.rb
- spec/serializers/participant_serializer_spec.rb
- spec/services/validate_participant_spec.rb
Enable the `:eligible` status to be set in `ECFParticipantEligibility` instead of forcing the status to `:matched`. Ensure that this is still handled in the validations controller as though it were `:matched` status. This is to enable us to get a picture of who will successfully validate and the different outcomes that will need to be handled.
When we have matched the participants TRN, the qts flag is set and there are no other flags, the eligibility status should be `:eligible`.  In this instance we should delete/not store the validation data, however as this is not complete yet, we need to hang on to the personal data needed to re-run validation against the participant once it is complete.
2. Follow the steps from …
> Allow eligible status in ECFParticipantEligiblilty

- app/services/participants/base.rb
- app/services/participants/change_schedule/base.rb
- app/services/participants/change_schedule/ecf.rb
- app/services/participants/change_schedule/npq.rb
- app/services/participants/defer/base.rb
- app/services/participants/defer/ecf.rb
- app/services/participants/defer/npq.rb
- app/services/participants/resume/base.rb
- app/services/participants/resume/ecf.rb
- app/services/participants/resume/npq.rb
- app/services/participants/withdraw/base.rb
- app/services/participants/withdraw/ecf.rb
- app/services/participants/withdraw/npq.rb
- app/services/record_declarations/base.rb
- app/services/record_declarations/retained.rb
- app/services/record_declarations/retained/base.rb
- app/services/record_declarations/retained/ecf.rb
- app/services/record_declarations/retained/npq.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
Someone sent us some unpermitted parameters on participant actions, and we don't want to 500 for that.
2. Try to send a 'withdraw' request for a participant, sending an extra parameter along the way.
> Guard against unpermitted params in participants api

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- spec/services/invite_schools_spec.rb
Ticket: CPDRP-958
Another email ticket. This one had an existing method I adapted. The old template is now being deleted
I've added `delivery_params` so that you can do for example `send_induction_coordinator_choose_provider_chasers(delivery_params: {wait_until: Time.zone.parse("2021-09-22T08:00Z")})`
This probably better than delaying the entire method call, because you won't accidentally email someone lots of times if there's an error and delayed_jobs retried. One thing to bear in mind though is that the information might be out of date by the time the email is sent, so it shouldn't be scheduled too far ahead
> CPDRP-958: Update chaser for SITs to choose a provider

- app/forms/schools/year2020_form.rb
- app/services/early_career_teachers/create.rb
- spec/forms/schools/year2020_form_spec.rb
We're emailing NQT+1 s telling them they need to validate. We should not do this. This quick and dirty PR prevents that - it is a temporary solution to buy time for a better fix
> BUGFIX: prevent NQT+1s from being sent validation invites

- app/helpers/application_helper.rb
- app/services/early_career_teachers/create.rb
- spec/helpers/application_helper_spec.rb
- spec/services/early_career_teachers/create_spec.rb
Attempt to prevent NQT+1 from validating by redirecting them to the no-access page on login. They could probably still validate if they knew the correct URL - are we concerned?
I've also cleaned up some of the changes from the related #1098
> Redirect NQT+1 to no access page on sign in

- app/mailers/participant_validation_mailer.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- spec/factories/school_cohort.rb
- spec/mailers/participant_validation_mailer_spec.rb
- spec/services/validation_beta_service_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-973
- Combine CIP and FIP templates into one email
- Add a limit so we only send a maximum of 5000 emails
- Update the utm campaign for this specific send including the date
- Allow resending of validation info emails if the mentor received one prior to the automation launch, similar to https://github.com/DFE-Digital/early-careers-framework/pull/1076
> CPDRP-973 Adjust mentor validation info chaser emails

- app/models/call_off_contract.rb
- app/models/participant_band.rb
- app/services/calculation_orchestrator.rb
- app/services/participant_event_aggregator.rb
- lib/payment_calculator/ecf/contract/uplift_payment_calculations.rb
- spec/lib/payment_calculator/ecf/contract/uplift_payment_calculations_spec.rb
- spec/models/call_off_contract_spec.rb
- spec/services/calculation_orchestrator_spec.rb
Ticket: 
Calculate the total contract value from the participants in the target * the price per band for each band.
Limit the uplift to 5% of this (currently a hardcoded value)
Split out the aggregator from the calculator again for a couple of reasons.
1. It's becoming big enough to be independent and will be more so when it will need to capture "paid" historic numbers to reconcile against future milestones and stories.
2. Doing it now, rather than when 1 becomes an issue make is easier to test the uplift cap without needing to seed the database. …
> CPDTP-280 Limit uplift payments

- app/services/participant_validation_service.rb
The DQT has recently added a whole load of people with TRN 0. That breaks our system to find people who gave us the wrong TRN
> BUGFIX: Find correct TRNs for people with 3/4 match

- app/services/check_participant_eligibility.rb
- spec/services/check_participant_eligibility_spec.rb
- spec/services/participant_validation_service_spec.rb
Transpires that the "previous inductee" list we are using to validate participants against is, in fact, a list of eligible TRNs.
This PR reverses the logic when validating participants against the list, removing the previous_induction flag when present and adding the previous_induction flag when not present.
This will no doubt be superceded shortly by the API
> BugFix: Apply reverse logic to TRA previous induction list

- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/services/invite_schools_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-860
- Only eligible schools
- not opted out
- only schools that haven't nominated an induction coordinator
> CPDEL-860 Add NQT+1 invite email for sitless non-opted-out schools

- app/models/finance/schedule.rb
- app/models/participant_declaration.rb
- app/services/participants/change_schedule/validate_and_change_schedule.rb
- app/services/record_declarations/base.rb
- app/views/lead_providers/guidance/release_notes.html.erb
- config/locales/en.yml
- db/migrate/20210922082602_add_declaration_type_for_milestone.rb
- db/migrate/20210922082603_populate_declaration_type_for_milestone.rb
- db/schema.rb
- db/seeds/schedules.rb
- spec/factories/finance/schedules.rb
- spec/serializers/participant_serializer_spec.rb
- spec/services/participants/change_schedule/early_career_teacher_spec.rb
- spec/services/record_declarations/retained/mentor_spec.rb
- spec/services/record_declarations/started/early_career_teacher_spec.rb
- spec/shared/context/lead_provider_profiles_and_courses.rb
- spec/shared/context/service_record_declaration_params.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-475
If there is a pending (unprocessed) declaration, and the provider tries to change schedule, we want them to void it first. The common case is someone having a declaration in September and switching to a January start schedule - we don't think the declaration from September would make much sense for them.
I added `voided` and `not_ voided` scopes to declarations because they were useful in this PR.
2. Make a declaration in Septmber for a participant
3. Try changing their schedule to a January one
4. It should fail and tell you why …
> CPDTP-475: Schedule change validation

- app/controllers/schools/year2020_controller.rb
- spec/controllers/schools/year2020_controller_spec.rb
Ticket: [855](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-855)
We want to noindex nqt plus one pages so that they don't show in search engine results
I've had a look at what other DfE services do for this and there's a few different ways. I wanted eyes on it to know whether this is right/wrong. Happy to chat about how best to do this. 
> noindex nqt plus 1 pages

- app/services/partnerships/report.rb
- spec/services/partnerships/report_spec.rb
When a partnership is reported for a school who has chosen a provision
other than FIP, we should delay changing their delivery method by two
weeks to give them time to challenge. Because this logic was written
when the only options were CIP or FIP, schools who chose NoECTs or DIY
were left in a sort of limbo
> BUGFIX: ensure schools are transitioned to FIP

- spec/policies/partnership_policy_spec.rb
- spec/policies/school_cohort_policy.rb
```
Using expect { }.not_to permit_actions could produce \
confusing results. Please use `.to forbid_actions` instead. To \
clarify, `.not_to permit_actions` will look at all of the actions and \
checks if ANY actions fail, not if all actions fail. Therefore, you \
could result in something like this: \
it { is_expected.to permit_actions([:new, :create, :edit]) } \
it { is_expected.not_to permit_actions([:edit, :destroy]) } \
In this case, edit would be true and destroy would be false, but both \
tests would pass.
```
> Fixed  issues with `.not_to permit_actions`

- lib/mail/delivery_recorder.rb
- spec/lib/mail/delivery_recorder_spec.rb
https://sentry.io/organizations/dfe-bat/issues/2679159558/?project=5748989&referrer=slack
There was an assumption made that all emails will be using notify templates with personalisation. This change fixes an issue with 2020 form submission.
> Handling email audit of emails without personalisations

- app/controllers/users/sessions_controller.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- spec/requests/users/sessions_spec.rb
Ticket: [921](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-921)
The regex in Devise initializer hasn't been used as it didn't cover many invalid formats i tried, e.g "invalid@email,com"
2. Try to log in with an incorrect email format 
https://user-images.githubusercontent.com/69353998/135220212-c39613f8-92d5-46fd-99ca-2f6f254e9437.mov
> Add email format check for sign in

- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantChangeScheduleRequest.yml
- swagger/v1/component_schemas/ECFParticipantDeferRequest.yml
- swagger/v1/component_schemas/ECFParticipantResumeRequest.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawRequest.yml
- swagger/v1/component_schemas/ParticipantDeclarationResponse.yml
The types in our api docs are not quite right. This should fix it.
> Correct json api types in api docs

- app/mailers/school_mailer.rb
- app/services/validation_beta_service.rb
This reverts commit 773e422b38927e0525f3b6a0ce8c52e5fb8c5375.
We sent this mailer this morning so this code is no longer needed.
> Revert "Remind FIP SITs to add ECTs and mentors"

- app/views/schools/dashboard/show.html.erb
- app/webpacker/styles/application.scss
CPDRP-913 has already been deployed, this is an update relating to this ticket.
Design requested that the cohort dashboard is a summary list and not a table.
The difference this will make will be the actions will be right-aligned, and will improve the spacing. 
It was possible to revert to two-thirds column width and no wrap was no longer required.
Ticket:
The table in schools/dashboard/show.html.erb has been updated to being
> Layout update to cohort dashboard

- app/mailers/school_mailer.rb
- app/models/partnership_notification_email.rb
- app/services/partnership_notification_service.rb
- app/services/utm_service.rb
- spec/services/partnership_notification_service_spec.rb
includes extending the partnership challenge deadline by 2 weeks since these schools have presumably ignored their first partnership notification email
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-993
> Add invite SIT email for partnered fip schools without a SIT

- spec/features/participant-declarations/participant_declaration_steps.rb
- spec/features/participant-declarations/voided_declaration_in_payment_breakdown_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDTP-205
As the voided declarations are already not included in the query scope used in the aggregation then only a feature test is required to ensure the payment breakdown doesn't include a voided declaration 
> CPDTP-205 Ensure no payment is made where a declaration has been voided

- app/mailers/school_mailer.rb
- app/models/school.rb
- app/models/school_cohort.rb
- app/policies/participant_profile/ecf_policy.rb
- app/services/invite_schools.rb
- spec/mailers/school_mailer_spec.rb
- spec/models/school_spec.rb
- spec/services/invite_schools_spec.rb
Criteria as per email schedule:
```
SITs with ECTs and mentors who have ALL been validated
- Do NOT include schools who are NOT eligible for FIP aka CIP only
- Do NOT include SITs who have opted out
```
Also includes adding a column to track which SITs we send emails to. We will follow this up the week after (or after that) to all eligible non-opted-out SITs that weren't sent an email in this one-off send.
> Add NQT+1 invite email for SITs who have all validated participants

- app/models/ecf_participant_eligibility.rb
- app/services/validate_participant.rb
- db/migrate/20210930125828_add_reason_to_ecf_participant_eligibilities.rb
- db/schema.rb
- spec/jobs/validation_retry_job_spec.rb
- spec/models/ecf_participant_eligibility_spec.rb
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CPDRP-1000)
Updates participant eligibility logic to account for the participant profile type.
Adds reason enum so that we can easily see the reason for the given status.
We will want to run this manually against prod, primarily to update the status for mentors that have a previous induction. Currently these are flagged for manual check but we should ignore the previous induction flag for mentors.
```ruby
ECFParticipantEligibility.where(manually_validated: false).find_each { |eligibility| eligibility.determine_status; eligibility.save! }
```
Does this change anything in our external APIs? If so, did you remember to update the …
> CPDRP-1000 Participant eligibility logic update

- app/forms/participants/participant_validation_form.rb
- spec/forms/participants/participant_validation_form_spec.rb
Ticket: [882](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-882)
Dates aren't fun.
`ActiveRecord::Type::Date.new.cast(value)` will, for example, go to 1st October 1991 when putting 31 September but Date.new(31, 9, 1991) will raise an invalid error. 
Happy to chat about if this if anyone if free. I have a couple questions about the form and how it's handling the dob.
2. login as an example email 
3. go to `/participants/validation/tell-us-your-details`
4. Try various different d.o.b's, valid and invalid …
> Handle invalid date of birth for participant validation

- app/services/npq/accept.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/services/npq/accept_spec.rb
Ticket: https://trello.com/c/yOJFfO9p/555-build-aso-journey
- When a provider accepts an NPQ application at the moment it rejects all other applications
- This change makes it so when the accept comes in, it only rejects other applications from the user on the same course. 
- ssh in to the box
- find or create a lead provider
- submit 3 NPQ applications all from the same user - 2 (a+b) on the same course and 1 (c) on another course
- in the block of 2 (a+b), accept `a` and `b` should be rejected. `c` should remain unchanged 
- There is a minor impact on the API on accepting. However do we need to document this as this feature?
> Scope rejections when Accepting NPQ applications

- app/mailers/school_mailer.rb
- app/services/invite_schools.rb
- app/services/utm_service.rb
- spec/services/invite_schools_spec.rb
SITs who chose 'use DfE materials' aka CIP BUT have NOT added ECTs or mentors.
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-998
> CPDRP-998 Add email for unpartnered cip sits with no participants

- app/controllers/api/v1/ecf_participants_controller.rb
- app/models/teacher_profile.rb
- config/initializers/preload_stis.rb
- spec/features/participant-declarations/participant_declaration_steps.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
The addition of NQT+1 as 2020 participants caused them to appear in the participants results for lead providers where they are at a partnered school. This change limits results to participants in the current cohort (for ECF only)
> Only return 2021 participants to lead provider in API

- docs/config.rb
- docs/config/tech-docs.yml
- docs/lib/govuk_tech_docs/open_api/extension.rb
- docs/lib/govuk_tech_docs/open_api/renderer.rb
- docs/lib/govuk_tech_docs/open_api/templates/any_of.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/api_reference_full.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/curl_examples.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/operation.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/parameters.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/path.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/responses.html.erb
- docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
Turns out govuk tech docs gem shows some nice things in API, but is not very good at showing examples and schemas. https://ecf-dev.london.cloudapps.digital/api-reference/reference.html
I am not quite sure why, but I know for sure that teacher training solved this problem.
I intend to go through the templates and ruby code to improve it somewhat, but the gist of it is that the review app should contain a lot more useful schemas and examples.
> Use Teacher Training API solution to show api schemas and examples in docs

- app/mailers/participant_validation_mailer.rb
- app/services/utm_service.rb
- app/services/validation_beta_service.rb
- spec/services/validation_beta_service_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-1009
- add new email for manual send: remind SITs that have unvalidated participants
- remove `tell_induction_coordinators_we_asked_ects_and_mentors_for_information`, this email used the same template (which has now been changed in notify to have different variables), so would no longer work.
> CPDRP-1009 Add reminder email for SITs with unvalidated participants

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
Ticket: none
- if no induction `start_date` then treat as no previous induction
- Otherwise it throws an error if `start_date` is `nil` as it does `nil < value` and `nil` does not implement `<`
- For the records I found a `nil` `start_date` that are erroring, seems to have inductions with the status of `Exempt`
- Not sure if this is possible with the data available in the database
- none
> fix error when no induction start_state

- app/forms/participants/participant_validation_form.rb
- spec/forms/participants/participant_validation_form_spec.rb
We have seen some support issues where users are experiencing an error that is caused by them having partially completed participant validation and the session data saved at their end.   Since the change to the TRN question in the validation journey some steps were removed and an old session will have data regarding those steps in. This causes a `ActiveModel::UnknownAttributeError` error to be raised when populating the form from the session data.
This fix reintroduces the missing attribute to smooth this out. As soon as the step is submitted the session data will get overwritten with the correct set of attributes.
This is something we can remove in due course.
Does this change …
> Participant validation - Fix problem with removed attributes and stale session data

- app/controllers/participants/validations_controller.rb
- app/forms/participants/participant_validation_form.rb
- app/views/participants/validations/tell_us_your_details.html.erb
- config/routes.rb
- spec/features/participants/happy_validation_journeys_for_ect_cip_spec.rb
- spec/features/participants/happy_validation_journeys_for_ect_fip_spec.rb
- spec/features/participants/happy_validation_journeys_for_mentor_cip_spec.rb
- spec/features/participants/participant_validation_steps.rb
- spec/features/participants/sit_mentor_fip_validation_journeys_spec.rb
- spec/features/participants/unhappy_validation_journeys_for_cip_spec.rb
- spec/features/participants/unhappy_validation_journeys_for_ect_fip_spec.rb
- spec/forms/participants/participant_validation_form_spec.rb
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CPDRP-1011) Remove name change pages from participant validation journey
This is just removing the steps that ask about surname changes and updating the TRA from the validation journey.
> CPDRP-1011 Remove name pages from participant validation

- lib/tasks/valid_test_data_generator.rb
Providers would like some dummy applications. But they want this so that they can test their accept/reject integration, so we should not pre-accept applications.
> Remove accepting applications from dummy application generators

- app/serializers/participant_serializer.rb
- app/services/feature_flag.rb
- spec/serializers/participant_serializer_spec.rb
We want to be able to show eligibility in the API before the UI is ready. Use a new feature flag to achieve this
> Decouple the api eligibility from the UI

- app/mailers/school_mailer.rb
- app/services/validation_beta_service.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-1058
Add mailer for SITs who have still not chosen a programme. This is using the same mailer as `ValidationBetaService#remind_sits_to_add_participants` but with a different audience. 
I'll revert this PR once it has been sent tomorrow.
> Add mailer for SITs who have still not chosen a programme

- app/services/validation_beta_service.rb
Partial revert of #1282
This mailer has now been sent.
> Revert "Add mailer for SITs who have still not chosen a programme"

- app/mailers/ineligible_participant_mailer.rb
- app/services/store_participant_eligibility.rb
- spec/services/store_participant_eligibility_spec.rb
We don't want to send these emails any more because we're not sure what's going on with them
> Do not send ineligibility emails about ERO mentors

- app/mailers/school_mailer.rb
- app/services/partnership_notification_service.rb
- app/services/validation_beta_service.rb
- spec/services/partnership_notification_service_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-1061
We're re-sending out two mailers that we've already sent. This PR adjusts the tagging so we can attribute them correctly. I also modify the challenge deadline extension so that it doesn't exceed the Oct 31 milestone date.
> Adjust SIT reminder mailers so they can be resent

- app/controllers/api/api_controller.rb
- app/controllers/api/errors/npq_application_already_accepted_error.rb
- app/services/api/error_factory.rb
- app/services/npq/accept.rb
- config/locales/en.yml
- spec/requests/api/v1/npq_applications_spec.rb
- spec/services/npq/accept_spec.rb
Ticket: https://trello.com/c/prKZvbBl/647-ensure-a-second-course-cannot-be-accepted-it-was-created-after-the-original-accept-reject
- I have rolled a few changes into one so it may be easier to review each commit independently
- The first is to ensure that we prevent providers from accepting multiple NPQ applications for the same course. Whether this be with one provider or across multiple providers
- This will likely need to change in the future if they wish to apply again for the same course but this can be handled at a later date
- The second change is refactoring out `NPQApplicationAlreadyAcceptedError` in favour of simple control flow. I believe this to be an improvement over raising an exception part way thru the code for it to be handle somewhere else. This keeps things a bit more …
> Prevent further npq couse accepts

- app/models/participant_profile/ecf.rb
- spec/models/participant_profile/ecf_spec.rb
Fix issue where if a participant is unmatched (we couldn't find their details during validation so did not create a `ECFParticipantEligibility` record) they disappear from the participants view for the SIT.  A support admin has a different view and can see the participant.
> BUGFIX: Fix scope query to handle where no eligibility record exists

- app/models/delivery_partner.rb
- app/models/participant_profile/ecf.rb
- spec/models/delivery_partner_spec.rb
- spec/models/participant_profile/ecf_spec.rb
Add a few scopes to models. current_cohort to make it easier to get the participant profiles we want (excluding NQT+1), and some to get the participants associated with a delivery partner
> Convenience scopes

- app/views/accessibility_statements/show.html.erb
- app/views/lead_providers/content/partnership_guide.html.erb
- app/views/nominations/request_nomination_invite/choose_location.html.erb
- app/views/nominations/request_nomination_invite/limit_reached.html.erb
- app/views/nominations/request_nomination_invite/not_eligible.html.erb
- app/views/participants/validations/change_your_details_with_tra.html.erb
- app/views/participants/validations/check_with_tra.html.erb
- app/views/participants/validations/get_a_trn.html.erb
- app/views/schools/choose_programme/show.html.erb
- app/views/schools/choose_programme/success.html.erb
- app/views/schools/cohorts/programme_choice.html.erb
- app/views/schools/partnerships/_confirm_with_provider.html.erb
- app/views/shared/_diy_what_you_can_do_now_info.html.erb
- app/views/shared/_roles.html.erb
- app/views/start/index.html.erb
- app/views/step_by_step/show.html.erb
- data/privacy_policy.html
Ticket:[1069](https://dfedigital.atlassian.net/jira/software/projects/CPDRP/boards/102?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDRP-1069)
I did a search for gov.uk, .com, .co.uk and .org. There's 4 links that go to the ECF page. I haven't done these, they'll need removing at some point. I'll create a ticket in the backlog for it. 
I also noticed `app/views/shared/_diy_what_you_can_do_now_info.html.erb` had a change, but couldn't see where it was being used. **Can it be deleted?**
> CPDRP-1069: external links open new tab

- app/controllers/api/v1/participant_declarations_controller.rb
- app/services/schema_validator.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantRetainedDeclaration.yml
- swagger/v1/component_schemas/ECFParticipantStartedDeclaration.yml
- swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml
- swagger/v1/component_schemas/NPQParticipantStartedDeclaration.yml
Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?selectedIssue=CPDLP-508
- This reintroduces schema validations for one particular set of endpoints, participant declarations
- From conversations I have had there is hesitance to make failing schema validations prevent api calls from being made 
- Therefore the outcome of this is to log the data instead
- From the logging we should be able to determine the ratio of api calls between passing and failing schema validation
- Also if something did fail validation, what that payload looks like and why it failed. this way we can either fix our end or ask api users to change their calls to conform
- The previous version of the schema validation used handcrafted json schemas to validate against. This change uses the …
> CPDLP-508 Add schema validation which logs results

- docs/source/index.html.erb
I was just reading through to test another ticket and the first link on how to auth with the api was broken.
Ticket:
> Fix broken link to authentication info in api docs

- app/controllers/users/sessions_controller.rb
- spec/requests/users/sessions_spec.rb
Some people are hitting the /confirm-sign-in page directly and it is causing a 500 error
https://sentry.io/organizations/dfe-bat/issues/2735066106/?project=5748989&query=is%3Aunresolved
Presumably through a bookmark or browser autocomplete
This is because it finds one of the many users with no login token, and checks their (nil) token expiry. To solve this, just treat the user as if their token is expired if one isn't provided - redirect them to the link-invalid page to sign in again.
Ticket:
> Fix login sentry error

- app/controllers/schools/participants_controller.rb
- app/services/set_participant_categories.rb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/kaminari/_page.html.erb
- app/views/pages/core_materials_info.html.erb
- app/views/pages/induction_tutor_materials/education_development_trust/_handbooks_and_outlines.html.erb
- app/views/participants/validations/cip_eligible.html.erb
- app/views/participants/validations/fip_eligible_no_partnership.html.erb
- app/views/participants/validations/fip_eligible_partnership.html.erb
- app/views/participants/validations/fip_mentor_previous_participation.html.erb
- app/views/sandbox/show.html.erb
- app/views/schools/add_participants/complete.html.erb
- app/views/schools/participants/index.html.erb
- config/locales/schools/participants.yml
- spec/features/participants/participant_validation_steps.rb
- spec/features/schools/participant_dashboard/manage_cip_participants_spec.rb
- spec/features/schools/participant_dashboard/manage_fip_partnered_participants_spec.rb
- spec/features/schools/participant_dashboard/manage_fip_unpartnered_participants_spec.rb
- spec/features/schools/participants/add_participants_spec.rb
- spec/features/schools/participants/remove_from_cohort_spec.rb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_cip_training_spec.rb
- spec/features/schools/training_dashboard/manage_design_our_own_training_spec.rb
- spec/features/schools/training_dashboard/manage_fip_training_spec.rb
- spec/features/schools/training_dashboard/manage_no_ect_training_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/services/set_participant_category_spec.rb
- spec/support/shared_examples/participant_actions_support.rb
Ticket: Sequel to [CPDRP-905](https://github.com/DFE-Digital/early-careers-framework/pull/1198) New participant dashboard
1. Refactoring of:  app/controllers/schools/participants_controller.rb (moving participant category logic into a `SetParticipantCategories` service allowing this to be more thoroughly tested
- Adding app/services/set_participant_categories.rb
- Adding spec/services/set_participant_category_spec.rb
2. Better implementation of Given, When, Then pattern in feature tests: 
- spec/features/schools/training_dashboard/manage_training_steps.rb (implementing Given, When, Then pattern)
- spec/features/schools/participants/add_participants_spec.rb 
- spec/features/schools/participants/update_participants_details_spec.rb
- …
> CPDRP-905 Add and refactor tests

- app/controllers/api/api_controller.rb
- app/controllers/challenge_partnerships_controller.rb
- app/controllers/concerns/api_filter.rb
- app/controllers/errors_controller.rb
- app/controllers/finance/base_controller.rb
- app/controllers/healthcheck_controller.rb
- app/controllers/lead_providers/base_controller.rb
- app/controllers/lead_providers/report_schools/csv_controller.rb
- app/controllers/schools/base_controller.rb
- app/forms/challenge_partnership_form.rb
- app/forms/core_induction_programme_choice_form.rb
- app/forms/delivery_partner_form.rb
- app/forms/finance/choose_payment_breakdown_form.rb
- app/forms/induction_choice_form.rb
- app/forms/lead_providers/report_schools_form.rb
- app/forms/nominate_how_to_continue_form.rb
- app/forms/nomination_request_form.rb
- app/forms/participant_mentor_form.rb
- app/forms/schools/add_participant_form.rb
- app/forms/supplier_user_form.rb
- app/services/void_participant_declaration.rb
- config/locales/en.yml
Goal - have all error messages in one place so that they can be easily accessed with minimal dev support, to avoid duplication and to tidy the project
Ticket: https://dfedigital.atlassian.net/browse/CPDRP-1079
> CPDRP-1079 move error messages

- app/services/participant_validation_service.rb
- lib/full_dqt/client.rb
- spec/lib/full_dqt/client_spec.rb
- spec/services/participant_validation_service_spec.rb
- Don't raise an [ambiguous](https://sentry.io/organizations/dfe-bat/issues/2699607064/?environment=production&project=5748989&query=is%3Aunresolved) exception if the TRN provided is nil.
- Remove duplicated padding method from DQT client. We already do this further up the chain.
If the review thinks it would be useful I'd be happy to report log when we receive nil TRNs. I don't think a nil TRN warrants an exception in this instance because it's expected.
> Enforce TRN requirement on participant validation service

- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NPQParticipantRetainedDeclaration.yml
Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?assignee=5e4e50b03df51b0c9374c1e4&selectedIssue=CPDLP-555
- Update docs to remove `evidence_help` from NPQ declarations endpoint
- This is so it correctly reflects the state of the API
- https://ecf-review-pr-1399.london.cloudapps.digital/api-reference/reference.html#schema-npqparticipantretaineddeclaration
- Should no longer reference `evidence_held` as client no longer needs to provide it
- No api changes but documentation has been updated to correctly reflect the state of the API
> Remove evidence held from NPQ declaration docs

- yarn.lock
This will reduce the number of vulnerabilities Dependabot thinks it has found
> Fix some yarn audit issues

- app/models/concerns/gias_types.rb
- app/models/data_stage/school.rb
- app/models/data_stage/school_change.rb
- app/models/school.rb
- app/models/school_link.rb
- app/services/data_stage/process_school_changes.rb
- app/services/rectify_participant_school.rb
- app/services/set_school_local_authority.rb
- app/services/set_school_local_authority_district.rb
- app/views/admin/gias/school_changes/show.html.erb
- db/migrate/20211001135337_create_school_links.rb
- db/schema.rb
- spec/models/data_stage/school_spec.rb
- spec/services/data_stage/process_school_changes_spec.rb
- spec/services/rectify_participant_school_spec.rb
- spec/services/set_school_local_authority_district_spec.rb
- spec/services/set_school_local_authority_spec.rb
Automatically process the more straight-forward major changes to school data received from GIAS.
__Note:__ I've not added this to the `ImportGiasDataJob` as yet as I want to run it manually initially.
This will process `DataStage::SchoolChange` records created during the GIAS data import process.
It will attempt to handle school status changes (opening and closing) and migrate data to the successor school if present.  It does not attempt to handle more complex splits and merges that potentially need more interaction or communication with the schools.
When migrating a school it will add successor and predecessor links similar to the `DataStage::SchoolLink` links imported from GIAS so we can track what has happened. These are not currently surfaced in the UI.
1. Click the link to review app …
> CPDRP-850 Track major school changes

- docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
- docs/source/api-reference/stylesheets/screen.css.scss
Ticket: https://dfedigital.atlassian.net/jira/software/projects/CPDLP/boards/87?assignee=5e4e50b03df51b0c9374c1e4&selectedIssue=CPDLP-561
- The first trivial change is widening the sidenav so schema names and endpoints fit over one line in desktop view
- The second change is the fixing of the `required` for schema which was being incorrectly populated. A required field would end showing as `false` despite the swagger docs saying otherwise
- Although now obvious it may not seem it this is due to re-assignment of the variable `schema` which has profound consequences when `binding` with `erb` is also involved.
- Compare with prod
- https://manage-training-for-early-career-teachers.education.gov.uk/api-reference/reference.html#schema-ecfparticipantstarteddeclaration
- …
> CPDLP-561 API doc improvements

- app/services/participant_validation_service.rb
- spec/services/participant_validation_service_spec.rb
It is possible that the DQT API returns "inactive" records and we are not checking for this.
> Prevent using inactive records returned from dqt

- app/controllers/admin/schools/cohort_2020_controller.rb
- app/services/early_career_teachers/create.rb
- app/views/admin/schools/cohort2020/new.html.erb
- config/locales/en.yml
- spec/requests/admin/schools/cohort_2020_spec.rb
Allow them to be creating using emails already in use
- Not allowed for active ECTs
- Allowed for other user types
- Name should not be changed for active participants
> Changes to admins creating NQT+1s

- app/services/set_participant_categories.rb
- spec/services/set_participant_categories_spec.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CPDRP-1147)
MAT SIT reported that recently the participant list for any of her schools show _all_ the participants from _all_ of her schools, including NQT+1s.
I have added a where clause to the `SetParticipantCategories#active_participant_profiles` to limit the scope to the selected school cohort
> CPDRP-1147: Restrict scope to school_cohort for participant categories

- app/controllers/api/v1/ecf_participants_controller.rb
- app/controllers/api/v1/participants_controller.rb
- app/models/lead_provider.rb
- app/models/teacher_profile.rb
- app/serializers/participant_serializer.rb
- spec/requests/api/v1/ecf_participants_spec.rb
- spec/requests/api/v1/participants_spec.rb
- spec/serializers/participant_serializer_spec.rb
Ensure that when a participant has an active profile not associated with the calling provider, the API response displays the correct withdrawn profile
> BUGFIX: ensure withdrawn profiles are always shown as such in API

- Dockerfile
Ticket: none
- I got bored of copying and pasting the various commands to fire up a rails console
- I've now added the needed command to the history 
- NOTE: I've actually tested this so unfortunately due to my testing it will have affected the history
```sh
cf target -s earlycareers-framework-dev
cf ssh ecf-review-pr-1433
````
- hit up arrow key
- hit enter
- should now be in a rails console
> add rails console command to history

- app/components/participant_status_tag_component.rb
- app/models/ecf_participant_eligibility.rb
- app/models/participant_profile/ecf.rb
- db/migrate/20211118153946_add_profile_duplicity_to_participant_profiles.rb
- db/schema.rb
- spec/factories/participant_profiles.rb
- spec/models/ecf_participant_eligibility_spec.rb
- spec/services/set_participant_categories_spec.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CPDRP-1083)
Hack so we can de-duplicate mentor profiles. This provides the means to mark duplicate mentor profiles as ineligible for funding but still appear as eligible for participation
Adds `duplicate_profile` as a `reason` on the `ECFParticipantEligibility` model
Adds `profile_duplicity` as an enum to the `ParticipantProfile::ECF` model. This can be:
* single - when no duplicates
* primary - when primary (eligible for funding) duplicate
* secondary - when (ineligible for funding) duplicate
This should allow us to manually identify and mark the duplicates as a stop gap. We still need to build the duplicate detection during validation and the changes to the success page at the end of validation.
1. Click the link to review app (posted by …
> CPDRP-1083: Add means to flag duplicate mentor profiles

- app/models/school_cohort.rb
- spec/models/school_cohort_spec.rb
Status was used in the old UI only
Ticket:
> Remove unused school cohort code

- app/models/participant_declaration.rb
- app/services/void_participant_declaration.rb
- config/locales/en.yml
- spec/requests/api/v1/participant_declarations_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-672
- At API level prevent voided, payable and paid declarations from being voidable
- I have followed the crowd for the way the error is raised. However i feel raising exceptions for validation messages is not the way forward
- still somewhat difficult given current state of dummy data
- Minor impact on API. I don't think it needs documenting at this moment in time
> CPDLP-672 Prevent voiding certain declarations

- docs/lib/govuk_tech_docs/open_api/renderer.rb
- docs/lib/govuk_tech_docs/open_api/templates/one_of.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-660
- Prior to this change api docs could not handle `oneOf` schemas
- When displaying the referenced schemas it would be blank
- These are now populated and when clicked takes user to referenced schema
- https://ecf-review-pr-1426.london.cloudapps.digital/api-reference/reference.html#schema-participantdeclarationchoices
- This is a `oneOf` schema
- it should now correctly list and link of to referenced schemas
> CPDLP-660 api docs can handle oneOf schemas

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/ecf_participants_controller.rb
Rework creation of the mentor_ids hash to eliminate the map
Before and after flamegraphs, viewable with https://www.speedscope.app/
[flamegraphs.zip](https://github.com/DFE-Digital/early-careers-framework/files/7582967/flamegraphs.zip)
I've left the perf tools in, they're probably useful. Happy to remove if wanted though
> ECF participants API performance

- app/models/npq_course.rb
- spec/components/admin/participants/details_spec.rb
- spec/cypress/app_commands/scenarios/admin/school_participants.rb
- spec/docs/npq_applications_spec.rb
- spec/factories/finance/schedules.rb
- spec/features/participant-declarations/participant_declaration_steps.rb
- spec/lib/importers/npq_manual_validation_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/serializers/npq_participant_serializer_spec.rb
- spec/services/npq/accept_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-718
- NPQ courses have been assigned the incorrect groupings and have been inverted
- This fixes it by inverting again
- There will need to be retrospective data changes to ensure NPQ applications/profiles are assigned to the correct schedule
- Find or create an NPQ application
- Accept this application
- Should now be assigned to correct schedule
- There are no external api changes
> CPDLP-718 invert NPQ leadership and specialist courses

- analytics_queries/participants.sql
- analytics_queries/schools.sql
- On the school table, is it possible to have a flag where an induction tutor has also been added as a mentor? Is it possible to also include the participant ID of that linked mentor record?
- On the participant table, TRN was missing as a field in the dummy data.
> Updates to analytics queries

- docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/BadRequestResponse.yml
- swagger/v1/component_schemas/ECFParticipantChangeScheduleRequest.yml
- swagger/v1/component_schemas/ECFParticipantCsvRow.yml
- swagger/v1/component_schemas/MultipleECFParticipantsResponse.yml
- swagger/v1/component_schemas/MultipleNPQParticipantsResponse.yml
- swagger/v1/component_schemas/MultipleParticipantDeclarationsCsvResponse.yml
While looking into a query, I noticed that the API docs didn't include the same examples that the swagger docs did, making it really hard to figure out how to call some endpoints.
I've changes the docs templates to add the examples in where they are JSON. I've also updated a couple of examples. The docs are still inconsistent (and sometimes wrong) in a few places, but this should help
> Show schema component examples in API docs

- spec/support/shared_examples/attribute_lookups.rb
- spec/support/shared_examples/participant_actions_defer_support.rb
- spec/support/shared_examples/participant_actions_resume_support.rb
- swagger/v1/api_spec.json
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-746
Some endpoints using shared examples had ECF participant hard coded. This was effecting the description of the endpoint and the operationId
> [CPDLP-746] Fix swagger descriptions of NPQ endpoints

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/participant_declarations_controller.rb
- app/controllers/api/v1/participant_validation_controller.rb
- spec/docs/participant_declarations_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1/error_spec.rb
- spec/requests/api/v1/participant_declarations_spec.rb
- spec/requests/api/v1/participant_validation_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/NotFoundResponse.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-748
On some occasions we would return an empty body with text/html, other times json.
This changes the api controller to rely on the exceptions app - see config.exceptions_app = routes in application.rb and ErrorsController, for 404s and 500 errors.
It isn't so straightforward things like BadRequest as we catch a few questionable exceptions to return that, along with a custom error message.
> Fix 404 API responses being html

- docs/source/_ecf_usage_participant_actions.html.erb
- docs/source/_usage_participant_declarations.html.erb
- docs/source/ecf-usage.html.erb
- docs/source/npq-usage.html.erb
There are a number of broken links in the API docs, this PR fixes those.
Relates to ticket: https://dfedigital.atlassian.net/browse/CPDLP-750
> CPDLP-750 fix broken links in api docs

- config/initializers/sentry.rb
Ignore `Pundit::NotAuthorizedError` exceptions in Sentry. I don't think that they are notable or exceptional — do we gain anything from having them in [Sentry](https://sentry.io/organizations/dfe-bat/issues/2735113167/?environment=production&project=5748989&query=is%3Aunresolved)?
> Ignore Pundit::NotAuthorizedError exceptions in Sentry

- spec/docs/participants_ecf_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantDeferResponse.yml
- swagger/v1/component_schemas/ECFParticipantDeferResponseData.yml
- swagger/v1/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantResumeResponse.yml
- swagger/v1/component_schemas/ECFParticipantResumeResponseData.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawDataResponse.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawResponse.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-751
- This change updates to docs to give specific examples responses for the ECF resume / defer / withdraw endpoints
- However in order to achieve this we must give new schemas which defines these examples despite all three responses fit under one schema
- https://ecf-review-pr-1501.london.cloudapps.digital/api-reference/reference.html#api-v1-participants-ecf-id-defer-put-responses
- Example response shows correct training status `deferred`
- https://ecf-review-pr-1501.london.cloudapps.digital/api-reference/reference.html#api-v1-participants-ecf-id-resume-put-responses
- Example response shows correct training status `active`
- https://ecf-review-pr-1501.london.cloudapps.digital/api-reference/reference.html#api-v1-participants-ecf-id-w …
> CPDLP-751 Update docs for participant action response examples

- terraform/monitoring/config/production/alert.rules.yml
- terraform/monitoring/config/staging/alert.rules.yml
We currently alert when any instance type crashes. This PR splits out web and worker crash alert rules so that we can better identify what type of instance has crashed.
> Split out web and worker crash alert rules

- app/models/cohort.rb
- app/models/finance/schedule.rb
- db/migrate/20211202162431_add_cohort_to_schedule.rb
- db/schema.rb
- db/seeds/schedules.rb
- spec/factories/finance/schedules.rb
- spec/models/cohort_spec.rb
- spec/models/finance/schedule_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-764
- Previously a schedule was not directly associated with a cohort
- This was implied through the name of the schedule
- This adds the association between schedules and cohorts
- The  schedule name can now therefore be free from containing the cohort year
- This change at the moment is somewhat superficial as this association is not utilised but will pave the way for future changes
- After this is deployed i will ensure all environments contain this extra data
- `cf ssh ecf-review-pr-1508`
- start rails console
- `pp Finance::Schedule.all`
- all schedules should belong to a cohort
- There are no external api changes
> CPDLP-764 cohort on schedule

- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/review.tfvars
These were added for testing purposes and are just wasteful otherwise, should have been deleted before PR was merged
Ticket:
> Remove extra sidekiq resources from review env

- terraform/app/variables.tf
We don't use this any more. This wasn't caught in review env as it has a custom web app command
Ticket:
> Remove cron:schedule from web app start command

- terraform/workspace-variables/dev.tfvars
This is something that was already done on the review env as the sidekiq process takes up the same amount of memory as the extra delayed job process and is the difference between 90% memory usage or 75% memory usage
Ticket:
> Reduce number of delayed_job workers on dev

- app/services/early_career_teachers/create.rb
- spec/services/early_career_teachers/create_spec.rb
Previously using `@participant_profile` which was nil, and the spec was just asserting that the job was called.
This call is inside a transaction, so if we can't update analytics then the whole thing gets rolled back.
On production after this is deployed, manually create a Analytics::UpsertECFParticipantProfileJob for all ParticipantProfile::ECTs created after 1pm (we only have one
error, so far)
Ticket:
> Fix call to update analytics from ECT create service

- app/components/admin/participants/details/ect_pending.html.erb
- app/components/admin/participants/details/mentor_pending.html.erb
- app/controllers/admin/participants_controller.rb
- app/views/admin/participants/edit_email.html.erb
- app/views/admin/participants/edit_name.html.erb
- app/views/admin/participants/show.html.erb
- config/routes.rb
- spec/features/admin/participants/update_participants_details_spec.rb
Ticket: [180](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-180)
This is to replace an admin having to impersonate a SIT, however this PR has not removed any of that functionality.
2. Login as admin. 
3. Go to participants tab on the dashboard, select an ECT or Mentor
4. Have a go at editing their name or email.
> CST-180 update participant in admin console

- spec/features/admin/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
[Percy is raising exceptions](https://percy.io/c72bbcf6/early-careers-framework/builds/14391449/changed/813115906?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=1280) when viewing a ppts details because the email is randomly generated. Setting them in the test should stop it.
> Set email address in update ppts feature spec

- docs/config/tech-docs.yml
- docs/lib/govuk_tech_docs/open_api/templates/api_reference_full.html.erb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-796
The following changes were made: 
- Contents tab now only shows one layer of headings
- Copy update of headings to be clearer in meaning (Update to **Endpoints** and **Base URLs**)
**Following updates:**
**Prior to updates:**
> Reduce text in contents, update headings

- README.md
- db/migrate/20211208100449_add_reason_to_versions.rb
- db/schema.rb
Add a reason column to papertrail, for recording notes about changes made on the console
> Add reasons to papertrail

- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
- app/models/participant_profile/npq.rb
Previously we were getting a NameError: uninitialized constant #<Class:0x0000000104856e70>::NPQ when running the rails server in development mode and using the api endpoints
Explicitly require the descendants of ParticipantProfile to fix this, and format the files similarly to the other STI classes.
Ticket:
> Fix STI autoloading for ParticipantProfile::NPQ

- app/models/participant_profile/npq.rb
- spec/services/record_participant_declaration_service_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-771
To my knowledge, there isn't a way to change the `eligible_for_funding` field on an npq application after it has been created, so we don't need to create a hook to update the declaration if that changes.
> CPDLP-771 Automate NPQ participant declarations transitioning to eligible

- terraform/workspace-variables/dev.tfvars
- terraform/workspace-variables/review.tfvars
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/staging.tfvars
The databases on these environments are regularly reset, so there aren't any more delayed jobs hanging around. We don't need to run this any more. This should also stop the the dev/review boxes running out of memory and the OOM killer killing the sidekiq process.
Ticket:
> Stop running delayed job in non-prod environments

- app/controllers/admin/schools/induction_coordinators_controller.rb
- app/controllers/api/v1/ecf_participants_controller.rb
- app/controllers/api/v1/ecf_users_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/schools/add_participants_controller.rb
- app/controllers/users/sessions_controller.rb
- app/forms/schools/add_participant_form.rb
- app/forms/supplier_user_form.rb
- app/models/participant_profile.rb
- app/serializers/participant_serializer.rb
- app/services/create_induction_tutor.rb
- app/services/identity.rb
- app/services/npq/build_application.rb
- app/services/participants/profile_attributes.rb
- app/services/validation_beta_service.rb
- db/migrate/20211213104559_add_foreign_key_on_participant_profile_to_participant_identity.rb
- db/schema.rb
- db/seeds/test_data.rb
- lib/devise/strategies/passwordless_authenticatable.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/forms/schools/add_participant_form_spec.rb
- spec/models/participant_profile_spec.rb
- spec/services/identity_spec.rb
Ticket: [Jira](https://dfedigital.atlassian.net/browse/CST-111)
Data has been backfilled in all the environments. This adds in functionality to use `ParticipantIdentity` for looking up `User` records by email or id.
Add a new `Identity.find_user_by` method to encapsulate the queries to smooth this transition.
Adds foreign key to `participant_profiles.participant_identity_id` and removes `optional` from `belongs_to :participant_identity` in `ParticipantProfile` model
> CST-111 Backfill identities

- db/seeds/test_data.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-773
The ticket is just to check that we are only using eligible declarations in the breakdown for NPQ output fee. The output fee page was showing N/A for the count, but this was fixed in a separate PR, so just a spec has been added to solidify this. Also added some seeds with eligible/submitted declarations for Ambition/npq-headship to make it easier to test the breakdown page.
> CPDLP-773 Add spec for breakdown count and add seeds

- config/initializers/sidekiq.rb
On running `bundle exec sidekiq`, I see the following deprecation warning:
```
2021-12-14T11:06:08.148Z pid=6620 tid=rc INFO: Booting Sidekiq 6.3.1 with redis options {}
2021-12-14T11:06:08.161Z pid=6620 tid=rc INFO: Cron Jobs - add job with name: session_trim
2021-12-14T11:06:08.172Z pid=6620 tid=rc INFO: Cron Jobs - add job with name: create_new_fake_sandbox_data
2021-12-14T11:06:08.180Z pid=6620 tid=rc INFO: Cron Jobs - add job with name: stream_big_query_participant_declarations
2021-12-14T11:06:08.188Z pid=6620 tid=rc INFO: Cron Jobs - add job with name: import_gias_data
2021-12-14T11:06:08.195Z pid=6620 tid=rc INFO: Cron Jobs - add job with name: school_analytics
2021-12-14T11:06:09.143Z pid=6620 tid=rc WARN: DEPRECATION WARNING: Initialization autoloaded the constants …
```
> Fix sidekiq-cron deprecation warning

- app/models/user.rb
- spec/models/user_spec.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CST-201)
Keep the `ParticipantIdentity.email` in sync with the `User.email` for original identity records (where `external_identifier == user_id`) when a user's email address is updated.
> CST-201 Update original identity record after email change on User

- db/seeds/schedules/npq_leadership.csv
- db/seeds/schedules/npq_specialist.csv
- spec/models/finance/schedule_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-794
- There has been a change in the desired schedule identifiers
- Any existing seeded data added by the old fixtures will be removed after this has been shipped
- This seed data will also be applied to prod after it has been shipped
- The default will not be changed until after the data has been made available
- `cf ssh ecf-review-pr-1574`
- confirm seeded schedules are present
- e.g. `Finance::Schedule::NPQSupport.all`
- No external changes yet
> CPDLP-794 change seeds for NPQ schedules

- .github/workflows/review.yml
The builds started failing with a weird error coming from this package when it tries to comment that a review app has been deployed. Attempt to go back to the previous version rather than master
https://github.com/unsplash/comment-on-pr/issues/51
Ticket:
> Pin version of comment-on-pr

- app/services/participants/change_schedule/validate_and_change_schedule.rb
- db/migrate/20220106111301_add_schedule_id_alias.rb
- db/schema.rb
- spec/support/shared_examples/participant_actions_change_schedule_support.rb
- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-830
- Also addresses: https://dfedigital.atlassian.net/browse/CPDLP-840
- schedules can be given an alias identifier
- this way a single schedule can be looked up via 2 identifiers
- giving lead providers backwards compatibility when changing schedules, when we change the schedule identifier
- once deployed on the relevant schedules i will:
-  add the current identifiers as an alias eg `ecf-september-standard-2021`
- then change the actual identifier to what they should be eg `ecf-september-standard-2021` => `ecf-standard-september`
- I tried passing in empty string as identifier lookup and fails which is what we want
- ssh into the box and start a rails app
- find an existing schedule and an alias to to it
- change a participants …
> CPDLP-830 schedules can be given an alias identifier

- app/controllers/lead_providers/partnerships_controller.rb
- app/serializers/partnership_csv_serializer.rb
- app/views/lead_providers/your_schools/index.html.erb
- config/routes.rb
- spec/cypress/integration/lead_providers/YourSchools.feature
- spec/requests/lead_providers/partnerships_spec.rb
Internally we spent a significant amount of time every week compiling a report that contains each lead providers' active partnerships with schools. The process is very cumbersome because it is inferred from external analytics systems, despite having the data easily available within the service.
This PR adds a button to the lead provider area of the service. It allows them to self-serve and download their current active partnerships at any point.
The button link isn't ideal but we can improve it in a subsequent PR. I'd also expect to add an inactive/challenged partnerships export later as well.
Copying in @fofr here to cast his eyes over the new "Download schools for <cohort year>" link below.
> Allow lead providers to download their active partnerships

- app/controllers/api/v1/npq_applications_controller.rb
- app/models/npq_application.rb
- app/models/participant_identity.rb
- app/models/user.rb
- app/policies/participant_profile/ecf_policy.rb
- app/serializers/npq_application_csv_serializer.rb
- app/serializers/npq_application_serializer.rb
- app/services/npq/accept.rb
- app/services/npq/build_application.rb
- db/migrate/20220105132616_add_participant_identity_to_npq_applications.rb
- db/schema.rb
- spec/models/participant_identity_spec.rb
- spec/services/npq/build_application_spec.rb
As part of of de-duping tasks, it was noticed that `npq_applications` are associated directly with a `User` which means that they can not be transparently transferred during an identity transfer.  If we move the association to the user's `ParticipantIdentity` instead then any `NPQApplication`s can be moved without exposing the de-duping detail to via the API endpoints.
This will need to happen in 2 parts. Most of this has been added with comments to remove old code and replaced with new code once `ParticipantIdentity` references have been added.
1. deploy this code
2. fix up data to add/use participant identity
3. uncomment code, add foreign key constraint to participant identity reference etc.
2. Follow the steps …
> DEDUPING: Add participant_identity reference to npq_application

- lib/tasks/update_school_urns.rake
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-843
Following producing the NPQ assurances report, it was noticed that more than expected NPQ Participant Profiles had the School URN missing from their records, despite it being present on the NPQ Application. This was giving the false impression that these records might be international applicants.
On investigate it was discovered a code change between 21 June and 1 September likely cause this field to be missing.
This PR is a one off rake task - to be deleted after it is run on production. …
> Create one off rake task to update school_urns on participant_profile

- app/services/importers/seed_schedule.rb
- db/seeds/schedules.rb
- db/seeds/schedules/ecf_standard.csv
- docs/source/_ecf_usage_participant_actions.html.erb
- docs/source/release-notes.html.erb
- spec/models/finance/schedule_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantAttributes.yml
- swagger/v1/component_schemas/ECFParticipantChangeScheduleAttributes.yml
- swagger/v1/component_schemas/ECFParticipantDeferAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantResumeAttributesResponse.yml
- swagger/v1/component_schemas/ECFParticipantWithdrawAttributesResponse.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-827
- Adds new schedule `ecf-standard-april`
- Updates docs accordingly
- Data will be populated post deployment
- https://ecf-review-pr-1599.london.cloudapps.digital/api-reference/ecf-usage.html#notifying-of-schedule-change-standard-induction for the docs
- To see schedule
- start a rails console on the review app
- Should see schedule and milestone present in the database
- Yes, new schedule. docs and release notes are part of this PR
> [CPDLP-827] add seeds for ecf-standard-april schedule

- app/controllers/api/v1/npq_applications_controller.rb
- app/jobs/create_new_fake_sandbox_data_job.rb
- app/models/npq_application.rb
- app/models/user.rb
- app/policies/participant_profile/ecf_policy.rb
- app/serializers/npq_application_csv_serializer.rb
- app/serializers/npq_application_serializer.rb
- app/services/npq/accept.rb
- app/services/npq/build_application.rb
- db/migrate/20220107190116_add_foreign_key_on_npq_application_to_participant_identity.rb
- db/migrate/20220108165316_remove_user_reference_from_npq_applications.rb
- db/schema.rb
- lib/tasks/valid_test_data_generator.rb
- spec/cypress/app_commands/scenarios/admin/school_participants.rb
- spec/docs/npq_participants_spec.rb
- spec/factories/npq_application.rb
- spec/factories/participant_identity.rb
- spec/factories/participant_profiles.rb
- spec/features/finance/npq/course_payment_breakdown_spec.rb
- spec/policies/participant_profile/ecf_policy_spec.rb
- spec/requests/api/v1/npq_applications_spec.rb
- spec/requests/api/v1/npq_participants_spec.rb
- spec/serializers/npq_participant_serializer_spec.rb
- spec/services/admin/change_induction_choice_service_spec.rb
- spec/services/create_induction_tutor_spec.rb
- spec/services/npq/accept_spec.rb
- spec/services/npq/build_application_spec.rb
- spec/support/shared_examples/participant_actions_resume_support.rb
Ticket:
Part 2 of #1579. Now that has been merged and deployed and we have added `ParticipantIdentity` records to all of the existing `NPQApplication`s we can add a foreign key and use the participant_identity to allow us to move a user's npq_applications with `ParticipantProfile`s when users are de-duplicated.  This ensures we can still expose the original IDs in the API endpoints and that the applications remain with the appropriate user and profiles.
> DEDUPING: Move npq applications from user to participant identity part 2

- config/routes.rb
- docs/source/release-notes.html.erb
- spec/docs/participants_spec.rb
- spec/lib/lead_provider_api_specification_spec.rb
- spec/requests/api/v1/participants_spec.rb
- swagger/v1/api_spec.json
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-829
- Adds extra endpoint `/api/vi/particicipants/ecf/ID/change-schedule`
- Does not differ from `/api/vi/particicipants/ID/change-schedule` endpoint but may do so in the fututre
- Updated docs accordingly
- Updated docs can be found at https://ecf-review-pr-1613.london.cloudapps.digital/api-reference
- Find a existing ECF user and change their schedule via new documented api endpoint
- Yes, API docs have been updated along with release notes
> [CPDLP-829] New ECF change schedule endpoint

- app/controllers/concerns/api/participant_actions.rb
- app/services/participants/change_schedule/base.rb
- app/services/participants/change_schedule/validate_and_change_schedule.rb
- docs/source/release-notes.html.erb
- spec/requests/api/v1/participants_spec.rb
- swagger/v1/api_spec.json
- swagger/v1/component_schemas/ECFParticipantChangeScheduleAttributes.yml
- swagger/v1/component_schemas/ECFParticipantChangeScheduleRequest.yml
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-844
- `Schedule#schedule_identifier` are not unique
- Eg. `ecf-standard-january` may exist twice. one for cohort `2021` and one for `2022`
- Therefore providers can specify the cohort which affects which schedule is used
- If no cohort is specified it defaults to `Cohort.current` which at this moment in time is `2021` 
- Docs have been updated accordingly
- Docs can be found at https://ecf-review-pr-1619.london.cloudapps.digital/api-reference
- Not sure we have any `2022` schedule so you may have to add some first ensure it shares a `schedule_identifier` as a `2021` schedule otherwise won't be a very good test
- Hit the endpoint for a participant with a `2022` schedule, should be updated to the specified schedule
- Yes,  docs have been …
> [CPDLP-844] Change schedule with cohort

- app/controllers/finance/schedules_controller.rb
- app/views/finance/landing_page/show.html.erb
- app/views/finance/schedules/index.html.erb
- app/views/finance/schedules/show.html.erb
- config/routes.rb
- spec/features/finance/schedules_spec.rb
Ticket: Related to but not really https://dfedigital.atlassian.net/browse/CPDLP-890
- Add schedules to finance area so finance users can see schedules
- This should allow non dev users to visualise schedules that have been persisted
Landing page
Schedules index
Schedules show
- Visit https://ecf-review-pr-1625.london.cloudapps.digital/finance
- Click `Schedules`
- Should see all persisted schedules
- Click on a schedule
- Should see milestones for the schedule
- None
> [CPDLP-890] finance users can see schedules and milestones

- app/controllers/api/v1/npq_profiles_controller.rb
- app/models/npq_application.rb
- config/routes.rb
- spec/requests/api/v1/npq_profiles_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-852
There are some npq applications that have their `eligible_for_funding` status out of sync with npq-registration. This is because the eligibility criteria has changed after they were created in ecf. This PR adds the endpoints necessary for us to sync all the statuses by running a rake task from npq-registration
> Add show and update endpoints for npq applications

- analytics_queries/participants.sql
- app/services/analytics/ecf_validation_service.rb
- db/analytics_migrate/20220114163650_add_schedule_identifier_to_ecf_participant.rb
- db/analytics_schema.rb
We currently pipe various data from the production database to BigQuery to enable the performance analysts to construct dashboards and reports in Google Data Studio.
Will Sandford has requested that schedule_identifier is added to the ECF Postgres tables and made available in BigQuery to support his analytics work.
This PR adds schedule_identifier to ecf_participants, participants.sql & ecf_validiation_service
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-878
> CPDLP-878 add schedule identifier to big query data

- .github/workflows/review.yml
We need to reduce our log output to logstash as we are hitting quotas. This PR disables logs draining to LogIt on review apps. You can enable it at any time by adding the `logstash-url` to your PR.
Review app pre-change: https://kibana.logit.io/s/51151c79-e17d-4407-be3a-01960f3f65ff/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(),index:'8ac115c0-aac1-11e8-88ea-0383c11b333a',interval:auto,query:(language:kuery,query:'cf.app:%22ecf-review-pr-1637%22'),sort:!())
This review app: https://kibana.logit.io/s/51151c79-e17d-4407-be3a-01960f3f65ff/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!(_source),filters:!(),index:'8ac115c0-aac1-11e8-88ea-0383c11b333a',interval:auto,query:(language:kuery,query:'cf.app:%22ecf-revie …
> Remove logstash from review apps

- app/components/admin/participants/details/ect_pending.html.erb
- app/components/admin/participants/details/mentor_pending.html.erb
- app/controllers/admin/notes_controller.rb
- app/views/admin/notes/edit.html.erb
- config/routes.rb
- spec/features/admin/notes/participant_note_spec.rb
- spec/features/admin/participants/participant_details_steps.rb
- spec/features/admin/participants/update_participants_details_spec.rb
Ticket: [271](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-271)
[Prototype PR with screenshots](https://github.com/DFE-Digital/early-career-framework-register-prototype/pull/243)
2. Login as `admin@example.com`
3. Go to participants dashboard, either for a school or the whole list
4. Select a ECT or Mentor
5. Add and save a note
6. Edit the note
> [CST-271] add notes field to admin console

- app/models/finance/statement/npq.rb
[Ticket:](https://dfedigital.atlassian.net/browse/CPDLP-825)
Changed it to the current milestone milestone_date
```ruby
f = Finance::Schedule.find_by(name: "NPQ Specialist November 2021")
f.milestones.order(milestone_date: :asc).where("milestone_date > ?", Date.today
).first.milestone_date # => Sat, 25 Jun 2022
```
> [CPDLP-825] - Change current NPQ payment breakdown

- app/forms/schools/add_participant_form.rb
- app/models/participant_profile.rb
- app/models/participant_profile/ecf.rb
- app/views/schools/add_participants/start_term.html.erb
- app/views/schools/participants/edit_start_term.html.erb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/requests/schools/participants_request_spec.rb
Had to move the start_term options back to ParticipantProfile.
These changes fix https://sentry.io/organizations/dfe-bat/issues/2942896307/?project=5748989&referrer=slack
> Fix for term editing

- README.md
- app/jobs/stream_big_query_participant_declarations_job.rb
- spec/jobs/stream_big_query_participant_declarations_job_spec.rb
This PR ensures that there is a relevant BigQuery table for the environment before attempting to stream declarations to it. It [stops this error](https://sentry.io/organizations/dfe-bat/issues/2949720212/?environment=deployed_development&project=5748989&query=is%3Aunresolved).
> Don't attempt to stream BQ updates if there is no table

- app/controllers/schools/change_sit_controller.rb
- app/views/layouts/school_cohort.html.erb
- app/views/schools/change_sit/check_details.html.erb
- app/views/schools/change_sit/confirm.html.erb
- app/views/schools/change_sit/email.html.erb
- app/views/schools/change_sit/name.html.erb
- app/views/schools/change_sit/success.html.erb
- app/views/schools/dashboard/show.html.erb
- config/routes.rb
- spec/features/nominations/nominate_induction_tutor_steps.rb
- spec/features/schools/change_sit/change_sit_spec.rb
- spec/features/schools/training_dashboard/manage_no_ect_training_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
- spec/requests/schools/change_sit_spec.rb
[107](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-107)
As a school induction tutor I want to change my schools induction tutor. 
For copies of the designs see [991](https://dfedigital.atlassian.net/browse/CPDRP-991)
In ticket 107 James has provided slightly tweaked versions for SITs with multiple schools. 
[multiple school confirm](https://docs.google.com/document/d/1XTxeskRhYEJ8lFauU_QzEKFrEP4WwQg8DXQJ9zFLrqo/edit#)
[multiple school success](https://docs.google.com/document/d/1hxCUh9Yx4rJa8_mF_XCGZg8c8t658QVXHQE1w_wVQRA/edit#heading=h.wcavz2duxplu)
**How to check:**
Go to [the PR app](https://ecf-review-pr-1556.london.cloudapps.digital/)
Sign in as `cpd-test+tutor-10@example.com` - they have multiple schools …
> CST-107: As a SIT I want to change my schools SIT

- app/services/participants/early_career_teacher.rb
- app/services/participants/mentor.rb
- app/services/participants/npq.rb
- app/services/participants/profile_attributes.rb
As most of the duplicate teacher profiles has been now merged together, we should be always using participant identifier to identify the profile providers are acting upon. The old logic was trying to find the profile by going identity => user => find_profile, which is not guaranteed to return the correct profile, as users can now have multiple profiles at the same time (this on it own is a result of my mistake during de-dup process and will be handled separately). For example -  `identity.user.early_career_teacher_profile`, as a `has_one` profile would return one of the profiles if two matching profiles are present. However, since providers use identifier we recorded on participant identity, we can actually find the correct profile from `identity` record with …
> Ensuring that all API actions are recorded against the correct participant profile

- app/jobs/participant_details_reminder_job.rb
- app/mailers/school_mailer.rb
- app/services/participants/withdraw/validate_and_change_state.rb
- spec/mailers/school_mailer_spec.rb
- spec/services/participants/withdraw/early_career_teacher_spec.rb
- spec/services/participants/withdraw/mentor_spec.rb
- spec/services/participants/withdraw/npq_spec.rb
- spec/support/shared_examples/participant_actions_withdraw_support.rb
Ticket: [160](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CST-160)
We need to notify SITs when their provider has withdrawn a participant.
> CST-160: Notify SITs of participant withdrawal

- app/jobs/stream_big_query_participant_declarations_job.rb
We stream declarations to BigQuery that were updated in the previous hour. If we were to update thousands of records in one go then the streamer would break as we would hit BQ limits. Instead we can rely on `find_in_batches` to stream an hours worth of declarations in batches.
> Stream declarations to BigQuery in batches

- app/components/content_list_component.html.erb
- app/components/content_list_component.rb
- app/views/pages/ect_additional_information.html.erb
- app/views/pages/mentor_additional_information.html.erb
- app/views/pages/school_leader_additional_information.html.erb
Ticket:[268](https://dfedigital.atlassian.net/browse/CST-268)
We had the css for a contents list taken from [govuk publishing components](https://components.publishing.service.gov.uk/component-guide/contents_list). I've used similar styling to how they do but after speaking with Kate, we wanted the heading and bullets a bit bigger than they example. 
2. Go to `pages/ect_additional_information` , `pages/mentor_additional_information` and`pages/school_leader_additional_information`
> [CST-268] temporary guidance pages

- app/controllers/finance/participants_controller.rb
- app/models/participant_profile/npq.rb
- app/views/finance/landing_page/show.html.erb
- app/views/finance/participants/_declaration.html.erb
- app/views/finance/participants/_ecf_profile.html.erb
- app/views/finance/participants/_npq_application.html.erb
- app/views/finance/participants/_npq_profile.html.erb
- app/views/finance/participants/index.html.erb
- app/views/finance/participants/show.html.erb
- config/routes.rb
- spec/factories/participant_profiles.rb
- spec/features/finance/participant_drilldown_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDLP-937
- Adds participant drilldown to finance area
- Can search for a user based off `participant_id`
- Returns their identities, profiles, declarations and npq applications
- No real optimisation has happened with regard to DB queries but don't think it will cause an issue
Entry point
Searching for a participant
Viewing an ECT-esque profile
Viewing an NPQ-esque profile
- https://ecf-review-pr-1685.london.cloudapps.digital/finance
- Login as finance user
- Navigate to participants drilldown
- Search for participants with following ids below:
- `2282c10c-8d0f-41eb-ac85-b8137a618b08` mentor
- `031d81f7-5541-49ba-91f6-c510ef0cab57` ect
- `79416621-a08f-4e32-acd1-25f947013e6d` npq
- Should see their correct identities, profiles, declarations …
> [CPDLP-937] Add participant drilldown to finance area

- app/services/analytics/ecf_validation_service.rb
- db/analytics_migrate/20220131150652_add_external_id_to_ecf_participant.rb
- db/analytics_schema.rb
This will allow people who consume the analytics database to determine whether a profile has been deduplicated. 
Post-deploy I'll need to re-insert all records so that they have this field.
> Add identity external identifier to analytics database

- app/views/pages/ect_additional_information.html.erb
- app/views/pages/mentor_additional_information.html.erb
- app/views/pages/school_leader_additional_information.html.erb
[316](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119/backlog?selectedIssue=CST-316&text=316)
Some content changes on the additional information pages have been picked up so this is just making those. Kate has made a note of them in the ticket comments.
Go to: 
`/pages/ect_additional_information`
`/pages/mentor_additional_information`
`/pages/school_leader_additional_information`
> Additional pages content amends

- app/models/participant_profile/ecf.rb
Ticket:[347](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?selectedIssue=CST-347)
We've had some support queries asking to choose Autumn 2021 as an option but we removed in [1580](https://github.com/DFE-Digital/early-careers-framework/pull/1580). Adding it back will allow users to select Autumn 2021 again
> [CST-347]Re-add autumn_2021 to start term options

- app/controllers/schools/add_participants_controller.rb
- app/forms/schools/add_participant_form.rb
- app/views/schools/add_participants/_ect_already_started.html.erb
- app/views/schools/add_participants/_mentor_already_started.html.erb
- app/views/schools/add_participants/started.html.erb
- spec/features/schools/participants/add_participants_spec.rb
- spec/features/schools/participants/update_participants_details_spec.rb
- spec/features/schools/training_dashboard/manage_training_steps.rb
Ticket:[316](https://dfedigital.atlassian.net/jira/software/projects/CST/boards/119?selectedIssue=CST-316)
ECTs and mentors are now moving schools, but we do not have functionality to manage this in the service yet. This causes problems if the ppt’s new school adds them as a duplicate record. We need to let SITs at the new school know to contact support instead of adding them in to the service for their school.
2. Sign in as `cpd-test+tutor-10@example.com`
3. Go to the dashboard
4. Select `Add a new ECT` or `Add a new mentor`
5. It should be the first screen you see after this step. (Depending on whether you add an ECT or mentor, you'll get slightly different content on this screen.
> [CST-316] temporary sit add ect/mentor content
